### ISSUE TITLE
Script to generate glycotree annotated glycans (sandbox)

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1]
Create new script or add to existing script `/software/glygen/sandbox-xref-download.py` to generate glycotree_annotated_glycans.tsv from [https://glygen.ccrc.uga.edu/sandbox/api/glygenData.php](https://glygen.ccrc.uga.edu/sandbox/api/glygenData.php)

Continued from issue https://github.com/glygener/glygen-frontend/issues/169

**Comment by rykahsay** [comment]
The following commands will create the files "/tmp/accessionlist.csv" and "/tmp/glycotree_annotated_glycans.csv"

```
$ cd /software/glygen/
$ python3 sandbox-xref-download.py -d accessionlist
$ python3 sandbox-xref-download.py -d glycotree_annotated_glycans
```
