### ISSUE TITLE
BLAST Improvements

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#100]
https://www.glygen.org/blast/
```
Change - Max number of hits * to Max number of hits (Proteins)*
Change in ? - Number of hit sequences to show in alignment: to Number of Proteins to show in the hit sequences alignment:
```
![image](https://user-images.githubusercontent.com/25825266/222833809-5d5fdabe-4881-4239-ba45-c3d3736e4c58.png)

https://www.glygen.org/blast-result/124 (Results)
```
Change Showing 1 to 20 of 282 Results to Showing 1 to 20 of 282 HSP Results
```
![image](https://user-images.githubusercontent.com/25825266/222834832-53288947-ba9f-438f-925c-1ba4e58a13ed.png)

```
For E-value and Identities sorting, The E-value with highest identity should be shown first
```
![image](https://user-images.githubusercontent.com/25825266/222835717-019c0765-f6e0-4e3e-99f1-8dd9c213e1fc.png)

https://www.glygen.org/blast-result/124 (Alignements)
```
 In dropdown for select protein ID - Organism name should be shown otherwise it is difficult to select the protein. If possible gene name can be also shown.
```
![image](https://user-images.githubusercontent.com/25825266/222835967-e5c66e3e-e7ff-479a-a4c1-106ef09a9442.png)

```
For the below gene name and organism should be shown.
```
![image](https://user-images.githubusercontent.com/25825266/222836235-cf077945-0e6d-4af1-8be1-5269405416ce.png)

```
The alignment tab can be sort as per E-value with highest identity.
```

**Comment by sujeetvkulkarni** [comment]
id num_alignments -> Max number of hits (Proteins) Robel issue https://github.com/glygener/glygen-issues/issues/130

**Comment by sujeetvkulkarni** [comment]
44f3068f45efd20dfb9fa088840cbb5f4e62684c

**Comment by sujeetvkulkarni** [comment]
gene name Robel : https://github.com/glygener/glygen-issues/issues/132

**Comment by sujeetvkulkarni** [comment]
HSP - spell it out

**Comment by sujeetvkulkarni** [comment]
High Scoring Pair (HSP)

**Comment by sujeetvkulkarni** [comment]
8962f85d06946d495ad4fc23f7f62f98b5aef3ac
