### ISSUE TITLE
Plan EBI - European resource evaluation

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1002]
As a first step @jeet-vora will send the proposal to Preethi. After this we will meet (maybe including Maria and Raja) to decide on a list of resources and prioritize them.

**Comment by ReneRanzinger** [comment]
@jeet-vora if this is the same as #1296 close this ticket. Otherwise advise how to proceed.

**Comment by jeet-vora** [comment]
Track ticket #1296
