### ISSUE TITLE
Triple-store query returns glycan accessions no longer in GlyGen...

### ISSUE THREAD

**Issue by edwardsnj** [glygener/glygen-issues#1003]
e.g. G01010HW

That is, one of the glycans we removed in the previous release. 

However, on the sparql.glygen.org page, the same query does not return this accession.

Here is the query. Using the endpoint directly, I get three accessions (including the one above). At the GlyGen page, I get two accessions and this one is not present.

```
        PREFIX glycan: <http://purl.jp/bio/12/glyco/glycan#>

        SELECT DISTINCT ?accession
        WHERE {
             ?saccharide a glycan:Saccharide
             BIND(STRAFTER(STR(?saccharide),"http://glygen.org/glycan/") as ?accession)
             FILTER(regex(?accession, "^G0101"))
        }
```

I am using the endpoint specified on the sparql.glygen.org page: http://sparql.glygen.org:8880/sparql

What is going on?

This is a blocker for the next GlycanData release...

**Comment by ReneRanzinger** [comment]
@edwardsnj Just to verify you wrote:
"However, on the sparql.glygen.org page, the same query does not return this accession."
But later you say it actually DOES return the access. 

In general I wonder if the triplestore was updated after the 2.3 data release.

**Comment by edwardsnj** [comment]
The difference is whether I use the embedded SPARQL interface at sparql.glygen.org or use the endpoint directly. I think the script referenced by the webpage uses a different endpoint than the public one?

**Comment by edwardsnj** [comment]
@rykahsay Any insight?

**Comment by rykahsay** [comment]
It looks like there are two graphs in the triplestore,  "http://sparql.glygen.org" and "http://beta-sparql.glygen.org", and the graph "http://beta-sparql.glygen.org" has not been updated with 2.3.1 data. If you do not specify the graph uri in your select line, both graphs are tragetted. This is the reason why I give both the "graph name" and "endpoint uri" on our sparql web site.

So, you will need to specify FROM $graph_url using one of the following options.

### Option-1:  as you can see below, your select line is commented out and replaced by the next line
```
    graph_uri = "http://sparql.glygen.org"
    endpoint = "http://sparql.glygen.org:8880/sparql"

    qs = "PREFIX glycan: <http://purl.jp/bio/12/glyco/glycan#> "
    #qs += "SELECT DISTINCT ?accession "
    qs += "SELECT DISTINCT ?accession FROM <%s> " % (graph_uri)
    qs += "WHERE { "
    qs += "?saccharide a glycan:Saccharide "
    qs += "BIND(STRAFTER(STR(?saccharide),\"http://glygen.org/glycan/\") as ?accession) "
    qs += "FILTER(regex(?accession, \"^G0101\")) "
    qs += "}"

    sparql = SPARQLWrapper(endpoint)
    sparql.setQuery(qs)
    sparql.setReturnFormat(JSON)
    triples = sparql.query().convert()
    print json.dumps(triples, indent=4)
```

### Option-2:  as you can see below, you can leave your select line the way it is and use addDefaultGraph at the bottom (this is the approach taken by my cgi script):
```
graph_uri = "http://sparql.glygen.org"
    endpoint = "http://sparql.glygen.org:8880/sparql"

    qs = "PREFIX glycan: <http://purl.jp/bio/12/glyco/glycan#> "
    qs += "SELECT DISTINCT ?accession "
    qs += "WHERE { "
    qs += "?saccharide a glycan:Saccharide "
    qs += "BIND(STRAFTER(STR(?saccharide),\"http://glygen.org/glycan/\") as ?accession) "
    qs += "FILTER(regex(?accession, \"^G0101\")) "
    qs += "}"

    sparql = SPARQLWrapper(endpoint)
    sparql.setQuery(qs)
    sparql.setReturnFormat(JSON)
    sparql.addDefaultGraph(graph_uri)
    triples = sparql.query().convert()
    print json.dumps(triples, indent=4)
```

**Comment by edwardsnj** [comment]
Ok, thank you for the insight. I will check this.

**Comment by edwardsnj** [comment]
OK, confirmed that this works. I think you should put this explicitly in the example queries (so it is explicit for others). I would prefer a different strategy for production vs dev triple-stores (URL-endpoint based) rather than single-endpoint with multiple graphs, but at least I understand how to get what I need now.
