### ISSUE TITLE
Test if Pig data is working correctly in the frontend

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1004]
After the 2.4 data update (#991) is done different pages need to be tested:
* Home page init (statistics)
* Glycan and protein search pages
* Glycan and protein list pages (left side filter)
* Glycan and protein details pages
* Publication page
* Super search

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger for publication page we are using old display. Which shows -
Sus scrofa (Pig) [[9823](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=9823)] and Sus scrofa domesticus (Pig) [[9825](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=9825)].
Not one common name/chosen name.
![Screenshot 2024-03-18 at 1 37 19 PM](https://github.com/glygener/glygen-issues/assets/13891482/9625a704-6d82-4a98-8b73-722ec66415a2)

**Comment by ReneRanzinger** [comment]
We should make it consistent. But if requires too much time on your and Robles side we move it to 2.5

On Mar 18, 2024, at 1:40 PM, Sujeet Kulkarni ***@***.***> wrote:

﻿ [EXTERNAL SENDER - PROCEED CAUTIOUSLY]


@ReneRanzinger<https://github.com/ReneRanzinger> for publication page we are using old display. Which shows -
Sus scrofa (Pig) [9823<https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=9823>] and Sus scrofa domesticus (Pig) [9825<https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=9825>].
Not one common name/chosen name.
Screenshot.2024-03-18.at.1.37.19.PM.png (view on web)<https://github.com/glygener/glygen-issues/assets/13891482/9625a704-6d82-4a98-8b73-722ec66415a2>

**Comment by sujeetvkulkarni** [comment]
Done.
Publication page change is done on tst and logged few issues related to this including for quick search.
