### ISSUE TITLE
Test Enzyme integration for O-glycans

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1008]
**Examples:**

* https://www.glygen.org/glycan/G56682BC
* https://www.glygen.org/glycan/G01614ZM

In the structure browser. 
1. I thought for empty parts there would be a "No data available." message. See Enzymes or motif.
2. We have enzymes in the Biosynthetic Enzymes section of the page, why is the structure browser tab empty?

**Comment by sujeetvkulkarni** [comment]
add a error log if enzymes from json are missing.

**Comment by sujeetvkulkarni** [comment]
Related : #1017

**Comment by sujeetvkulkarni** [comment]
cbbf4e39784521a13448f2198e87566841c81bb5d
