### ISSUE TITLE
Isoform2Canonical - open questions

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1009]
In the group meeting on the 7th we need to confirm the following questions with @pkay47:
1. How will the java command line tool be delivered to GW? Preferable containerization using docker. We could call the commandline tool in the container or if an web service API is provided we can call this.
2. How is the tool accessing the Uniprot sequences? Is it talking to an UniProt API or SparQL endpoint? 
3. We  prefer that it runs on entirely on the GlyGen server. Can we change the tool to run from a local database (Docker container) or sequence dump?
4. Can we have a GlyGen only and UniProt mode? 
5. What are the inputs (including formats) to the tool?
6. What are the outputs (including format) to the tool?
7. How are error information provided by the tool (e.g. invalid input, sequence can not be matched)?
8. Does the tool have a mode that take FASTA sequence and a site?
9. How long does the tool run? Does it need asynchronous calling?
10. How much time needs to be invested for 1-9?

**Blocker for:**
* #1010 
* #1011
* #1013
* #1012

**Comment by jeet-vora** [comment]
1. Preethi to look into containerization or provide the tool in python or just share the have code. She will get back by Feb 12.
2. Preethi to think about how to access the isoform fasta sequence from the tool.
3. Preethi to think how to cache the isoform ac and sequences that can be part of the code.
4. We can have radio buttons with default to All UniProt
5. Preethi to let us know the input format 
6. Preethi to let us know the output format 
7. Error handling is not robust yet. Invalid ac/ sequence can be pointed out with a table of failed entries
8. Will have to check and talk to Robel for preference for the cache
9. Tool to be shared by Feb 22

**Comment by ReneRanzinger** [comment]
Version 1:
* Just the GlyGen space for now
* @jeet-vora how big is the sequence space (all fasta sequences in Uniprot for all isoforms)
* @pkay47 provide Python library that takes input + configuration (mongo connect + folder in file system for fasta)

**Comment by pv47** [comment]
Am creating a service for the stand-alone java code. Once service is ready will provide answers for questions above.

Related issue - https://github.com/glygener/glygen-issues/issues/560

**Comment by ReneRanzinger** [comment]
* @pkay47 to look into [BioPython](https://biopython.org/), Preethi prefers **Java**
* We will containerize it as commandline tool
* @pkay47 will contact @edwardsnj to learn how he did it
* Input:
   * Input from the user as a file 
   * Folder with FASTA files
   * Mapping file isoform -> canonical
* Output:
   * File with the result (and the errors)
