### ISSUE TITLE
Glycans missing composition

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#101]
The following glycans were identified as missing "composition" and" expanded_composition" in API schema testing [glygen-frontend#99](https://github.com/glygener/glygen-frontend/issues/99)

Adding to agenda for 3/8 general meeting - **should these structures be excluded by automated API testing?**

https://glygen.org/glycan/G53621MK
![image](https://user-images.githubusercontent.com/90285371/223178706-0e520d95-2bc7-44e6-9465-e52c0a7b32d4.png)

https://glygen.org/glycan/G82740LG
![image](https://user-images.githubusercontent.com/90285371/223195717-e606365f-ecc2-407c-ba1c-7587be69d4e5.png)

**Comment by kmartinez834** [comment]
- Will relax schema to include glycans missing composition
- G82740LG composition is "0" for all comp types, and missing from monocounts.tsv file

```
$ grep 'accession\|G82740LG' /data/projects/glygen/downloads/glytoucan/current/export/monocomp.tsv 
accession       Hex     HexNAc  dHex    NeuAc   NeuGc   HexA    HexN    S       P       aldi    Xxx     X       Count
G82740LG        0       0       0       0       0       0       0       0       0       0       0       0       0

$ grep 'accession\|G82740LG' /data/projects/glygen/downloads/glytoucan/current/export/monocounts.tsv 
accession       monosaccharide  count
```

**Comment by kmartinez834** [comment]
@edwardsnj

**Comment by edwardsnj** [comment]
These have been updated in the latest release 1.13.0 (SUG is now supported and is shown as Xxx) and structures without valid compositions are not (erroneously) output into the monocomp.tsv file.
