### ISSUE TITLE
Tool - implement the isoform to canonical mapper in GlyGen

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1010]
We need a new tool in GlyGen (Tools menu: Isoform2Canonical).

**Input page:**
* File upload: TSV with uniprot accession with site 

**OR**
* Manual input in table:
   * Accession 
   * Sites
 
**OR**
* Manual input 
    * FASTA sequence (find canonical)  
    * Single site 

**API call**
* Not clear yet if a asynchronous call is needed.

**Output:**
Table with the following information:
* Original accession (see Input)
* Original site (see Input)
* Canonical accession (link to GlyGen or UniProt)
* Canonical site 

Table with Error:
* Original accession (see Input)
* Original site (see Input)
* Error message

**OR**
Error message if the entire process failed.

**Dependencies:**
* #1009 
* #1011 
* #1013 
* #1012

**Comment by sujeetvkulkarni** [comment]
@jeet-vora Can you please let us know for the input shown below are sites optional?

- Manual input in table:
  -  Accession
  -  Sites

**Comment by sujeetvkulkarni** [comment]
Sites is mandatory.

**Comment by sujeetvkulkarni** [comment]
2 (Accession, Sites) input sets initially then add more option - Jeet.

**Comment by sujeetvkulkarni** [comment]
done.
