### ISSUE TITLE
Isoform2Canonical - provide code/container and installation instructions for GW

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1011]
Based on the discussion in #1009 provide the tool and installation instructions for GW. 

**Dependencies:**
* #1009 

**Blocker for:**
* #1013 
* #1012
* #1010

**Comment by pv47** [comment]
Docker image: ebiglygen/mapper-java-jar:basic

steps to use docker image in https://github.com/glygener/glygen-issues/issues/560
