### ISSUE TITLE
Test beta now

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1014]
Test beta now

**Comment by ubhuiyan** [comment]
Hi there, is there documentation on how this can be tested? If so, would someone please provide it to me.

**Comment by jeet-vora** [comment]
@ubhuiyan Same as prd. Here is the link - https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7BD19FE4DF-19C7-40D3-9184-DE3A71A20409%7D&file=UQT_Beta_JW2.docx&action=default&mobileredirect=true

**Comment by Luke-Johnson-5** [comment]
~~One issue noted here: https://github.com/glygener/glygen-issues/issues/1024~~

resolved

**Comment by Luke-Johnson-5** [comment]
~~Another issue notes: https://github.com/glygener/glygen-issues/issues/1027~~
