### ISSUE TITLE
Enzyme file needs update.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1017]
Examples:

https://www.glygen.org/glycan/G56682BC
https://www.glygen.org/glycan/G01614ZM

We have enzymes in the Biosynthetic Enzymes section of the page and also getting these enzymes from json file (by Nathan) but are missing in the file shared in #814.

**Comment by kmartinez834** [comment]
@sujeetvkulkarni I've updated the file with Nathan's December data for now, and will update again once I download the glycan data for 2.4

**Comment by sujeetvkulkarni** [comment]
done.
