### ISSUE TITLE
Re-arrange seminar speakers

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1019]
@ReneRanzinger will contact Weston and check if March or April will work

@jeet-vora:
* Ask Kiyoko if she can do February
* Contact Rhea for March/April (Depending on Weston's response). Jeet -> Alan Bridge with CC:Raja.
* Contact Pride. Jeet -> Huan

**Comment by jeet-vora** [comment]
@ReneRanzinger 

Contacted
- Kiyoko for Feb
- Juan (PRIDE) for March
- Alan (Rhea) for April
