### ISSUE TITLE
GlyGen Frontend API testing

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#102]
Perform API testing (api.tst.glygen.org) to see what API is responsible for what page. Create a 2-column table afterwards documenting API_URL and Frontend_Pages. 

*Note: this table will serve as appendix in API documentation in Sharepoint.

**Comment by jeet-vora** [comment]
Yes the task is correct. I am assigning to the correct project and milestone.

**Comment by JingyueWu** [comment]
I wasn't able to find the corresponding pages to a lot of APIs. However, I created a table and filled it out the best I could. Please review and let me know how to find the rest: 

https://docs.google.com/document/d/1bN1yTmCPRNSuXZGDJQJ6sJMjXKDb45O-JnyjKjPyebY/edit?usp=sharing

**Comment by jeet-vora** [comment]
Provide me access to the document @JingyueWu

**Comment by jeet-vora** [comment]
@JingyueWu I do not have access to the document and what is the status of the task?

**Comment by JingyueWu** [comment]
Here is the link, you should have access now: https://docs.google.com/document/d/1bN1yTmCPRNSuXZGDJQJ6sJMjXKDb45O-JnyjKjPyebY/edit?usp=sharing 

I started this task a while back, but it got deprioritized in the past couple of month. I don't think it is urgent for now but will be good documentation to have. Closing this one right now to eliminate confusion and duplication. I will move it to 2.2 task once I finish downloading 2.2 data.
