### ISSUE TITLE
Hepacivirus C dead link

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1021]
From glycan detail page, searching for additional entries with Hepacivirus C species annotation works.  But clicking on Modify Search from list page leads to white page (dead link).

https://glygen.org/glycan/G97771XJ

![image](https://github.com/glygener/glygen-issues/assets/90285371/97abf017-c605-4332-88ec-b7ca6b1f9c5a)
\
![image](https://github.com/glygener/glygen-issues/assets/90285371/56e864ee-6c09-47b1-a75f-a9b8d7387963)

**Comment by sujeetvkulkarni** [comment]
8f1ea34c2476ecd39d9a741d5deb2d8a45b7a85a
Done - fixed on test server. But Organism input field on glycan search page is not prefilled with Hepacivirus C (HCV) option as it is not part of dropdown.
as https://api.tst.glygen.org/glycan/search_init api does not send HCV option.

```
organism: [
    {
        "name": "Human",
        "id": 9606
    },
    {
        "name": "Mouse",
        "id": 10090
    },
    {
        "name": "Rat",
        "id": 10116
    },
    {
        "name": "Pig",
        "id": 9823
    },
    {
        "name": "SARS-CoV-2",
        "id": 2697049
    },
    {
        "name": "Fruit fly",
        "id": 7227
    },
    {
        "name": "Cellular slime molds",
        "id": 44689
    },
    {
        "name": "HCoV-SARS",
        "id": 694009
    },
    {
        "name": "HCV-H",
        "id": 63746
    }
]
```

**Comment by kmartinez834** [comment]
@rykahsay can you add HCV to the glycan search_init?
```
organism: [
    {
        "name": "HCV",
        "id": 11103
    },
```

**Comment by rykahsay** [comment]
Try it on tst now

**Comment by kmartinez834** [comment]
HCV is present in drop down, but now Pig and Rat common names are duplicated. Can these be combined so that, for example, a search for "Rat" will give results with tax ID 10116 and 10114?

![image](https://github.com/glygener/glygen-issues/assets/90285371/ae04fad9-80b8-4ae7-b9b5-cc2d20b7aa05)

https://api.tst.glygen.org/glycan/search_init/
``` json
"organism": [
    {
      "name": "Human",
      "id": 9606
    },
    {
      "name": "Pig",
      "id": 9823
    },
    {
      "name": "Mouse",
      "id": 10090
    },
    {
      "name": "Rat",
      "id": 10116
    },
    {
      "name": "Rat",
      "id": 10114
    },
    {
      "name": "SARS-CoV-2",
      "id": 2697049
    },
    {
      "name": "Yeast",
      "id": 4932
    },
    {
      "name": "Fruit fly",
      "id": 7227
    },
    {
      "name": "HCV",
      "id": 11103
    },
    {
      "name": "Cellular slime molds",
      "id": 44689
    },
    {
      "name": "Pig",
      "id": 9825
    },
    {
      "name": "HCoV-SARS",
      "id": 694009
    },
    {
      "name": "HCV-H",
      "id": 63746
    }
  ],
```

**Comment by rykahsay** [comment]
check now

**Comment by kmartinez834** [comment]
@ubhuiyan can you verify if the number of glycans for each organism (on beta.glygen.org) matches the reviewed glycan_species.csv file? 

Ex. Pig
```
$ awk -F, '{print $1 $3}' /data/projects/glygen/generated/datasets/reviewed/glycan_species.csv | grep "Sus scrofa\|Sus scrofa domesticus" | sort -u | wc -l
7391
```
Home page statistics box:
![image](https://github.com/glygener/glygen-issues/assets/90285371/da557037-613e-4e81-9532-478a528dd46b)

Glycan advanced search for pig:
![image](https://github.com/glygener/glygen-issues/assets/90285371/5aa04172-b271-4446-a35d-fbf89b6ec307)

--> Report any discrepancies (including the one above for pig) in this issue and assign to Robel.

**Comment by ubhuiyan** [comment]
@kmartinez834 Sure thing! 

@rykahsay Here are the discrepancies depicted in the table below
| Species | BETA Glycan Value| glycan_species.csv Value| 
| ------------- | ------------- |  ------------- |  
| Rat| 7967  | 5189
| Pig  | 7319 | 7391

Note: The glycan number for yeast was the same between BETA GlyGen and the glycan_species.csv; however, this was from using the long name _Saccharomyces cerevisiae_ in my search - NOT with _Saccharomyces cerevisiae S288C_. I'm not sure if that's acceptable so just FYI as I understand the latter is the documented long name.

**Comment by rykahsay** [comment]
@kmartinez834 -- your command is counting those glycans common to "Sus scrofa" and :"Sus scrofa domesticus" twice, you should use the following command instead:

```
awk -F, '{print $1,$3}' /data/projects/glygen/generated/datasets/reviewed/glycan_species.csv | grep "Sus scrofa\|Sus scrofa domesticus"   | awk '{print $1}' |sort -u |wc
   7319    7319   80509

awk -F, '{print $1,$3}' /data/projects/glygen/generated/datasets/reviewed/glycan_species.csv | grep "Rattus\|Rattus norvegicus" | awk '{print $1}' |sort -u |wc
   7967    7967   87637

```

**Comment by rykahsay** [comment]
@ubhuiyan can you show how you got the number 5189 for Rat?

**Comment by kmartinez834** [comment]
@ubhuiyan replying to your note above re: Saccharomyces cerevisiae --> You'll want to use whatever names are used in the glycan_species.csv file.  You can view all of the unique organism names with this command:  
`awk -F, '{print $3}' /data/projects/glygen/generated/datasets/reviewed/glycan_species.csv | sort -u`

**Comment by ubhuiyan** [comment]
@rykahsay I used the command provided by Karina and switched the genus and species names. I just went over this with Karina and she explained there's a column with just "Rattus" in that csv that wasn't accounted for when I specified the species in my command. Karina explained how to do this properly next time.
