### ISSUE TITLE
Permanant URL for GlyTouCan list in GlyGen

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1022]
Based on #1007.

1. @kmartinez834 Is there a permanent URL or WS in GlyGen that we can use to retrieve all GlyTouCan IDs in GlyGen? 
2. @senaarpinar we need to retrieve this list in regular intervals and match it with our own GlyTouCan IDs. Each public glycan that is in the list should have a flag "in GlyGen". On the Glycan details page (e.g. [example](https://glygen.ccrc.uga.edu/ggarray/glycanDetail/2623376GAR)) we will add an additional link unter GlyTouCan ID with the pattern: "GlyGen: [GlyTouCan ID]". The ID is a link with the pattern: "https://www.glygen.org/glycan/[GlyTouCan ID]". All glycans that do not have the flag will not have the line with the link.

**Dependencies:**
* #1007

**Comment by kmartinez834** [comment]
The glycan masterlist dataset can be found here: https://data.glygen.org/GLY_000281

This URL points to the most current csv file: https://data.glygen.org/ln2data/releases/data/current/reviewed/glycan_masterlist.csv

Is this format acceptable or would you prefer an API?

**Comment by senaarpinar** [comment]
implemented links to glygen in the array repository
