### ISSUE TITLE
WS for retrieven the Glycan ID to GlyTouCan ID mapping

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1023]
@senaarpinar for the GlyGen integration based on #1007 @kmartinez834 needs a permanent URL or WS to give her a mapping of our internal Glycan ID and the corresponding GlyTouCan ID. 

For [example](https://glygen.ccrc.uga.edu/ggarray/glycanDetail/2623376GAR) :  2623376GAR -> G00056MO

Does a web service exists that provides this mapping for all our **public** glycans? Otherwise please implement it. @kmartinez834 doe you have any preference on the format?

@kmartinez834 The cross-reference link to GADR would have the pattern "https://glygen.ccrc.uga.edu/ggarray/glycanDetail/[Glycan ID]"

**Dependencies:**
* #1007

**Comment by senaarpinar** [comment]
@ReneRanzinger @kmartinez834 We have "https://glygen.ccrc.uga.edu/ggarray/api/array/public/getglycan/2623376GAR" to retrieve a glycan json (which has a glytoucanId field)

**Comment by ReneRanzinger** [comment]
@senaarpinar that will not work. It requires GlyGen to know all GADR glycan IDs, which they do not. It would also mean to have to call the WS for every single glycan.

**Comment by senaarpinar** [comment]
So we need a web service to return a list of all public glycans in the repository and each entry should have glytoucan id and gadr internal id fields, right?

**Comment by ReneRanzinger** [comment]
Yes. GET request please.

**Comment by senaarpinar** [comment]
Added the following API:

https://glygen.ccrc.uga.edu/ggarray/api/array/public/getglycanidmap

it returns json array of objects with two fields: glytoucanId and gadrId

You can test with the following:
curl -X 'GET' 'https://glygen.ccrc.uga.edu/ggarray/api/array/public/getglycanidmap' -H 'accept: application/json'

**Comment by ReneRanzinger** [comment]
@kmartinez834 can you please check and see if that is all you need to make cross references to the array repository in GlyGen glycans?

**Comment by kmartinez834** [comment]
It looks good to me.  I downloaded the file and created a ticket for Robel to add the new dataset to our pipeline (#1078 ).

@ReneRanzinger please close ticket if no other action needed
