### ISSUE TITLE
Glygen Beta SuperSearch API error

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#1024]
This appears to not be working causing the initial page to show blank when super search is selected and appears to be an API Issue. All major categories (ex. proteins) have a record count of zero. 

Interestingly valid lists are generated when a sample query is sample query is put into the search. 

 URL: beta-api.glygen.org/supersearch/search_init

Payload: 
{}

Output:
[response_1706727236558.json](https://github.com/glygener/glygen-issues/files/14115946/response_1706727236558.json)

**Comment by rykahsay** [comment]
Check now

**Comment by Luke-Johnson-5** [comment]
fixed
