### ISSUE TITLE
Beta-API Simple search proxy error

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#1027]
Bug causing the following error seen in the API. This is causing simple search with category any and term Homo sapiens to return a network error:
![image](https://github.com/glygener/glygen-issues/assets/144174552/19267c23-4022-458d-a8c1-227a6aa61e6a)

URL: https://beta-api.glygen.org/protein/search_simple/

Payload:
{
  "term_category": "any",
  "term": "homo sapiens"
}

Response:
![image](https://github.com/glygener/glygen-issues/assets/144174552/20f0df8f-cc2a-4ccc-b8af-22abf380b93d)

**Comment by rykahsay** [comment]
I was not able to reproduce the problem because it is working for me:

<img width="1007" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/c57aeafa-3c8f-475c-9980-a2c025419e50">

**Comment by Luke-Johnson-5** [comment]
appears to be working now for me as well
