### ISSUE TITLE
Change the following dataset file names in BCO ...

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#103]
*_citations_glycosylation_sites_o_glcnac_atlas.csv --> *_citations_glycosylation_sites_oglcnac_atlas.csv
*_citations_glycosylation_sites_o_glcnac_mcw.csv --> *_citations_glycosylation_sites_oglcnac_mcw.csv
*_glycosylation_sites_o_glcnac_atlas.csv --> *_glycosylation_sites_oglcnac_atlas.csv
*_glycosylation_sites_o_glcnac_mcw.csv --> *_glycosylation_sites_oglcnac_mcw.csv

**Comment by jeet-vora** [comment]
Done
