### ISSUE TITLE
Files missing from Refseq download

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1031]
Protein files missing from Refseq download:

- refseq_protein_all_44689.faa
- refseq_protein_all_9823.gpff
- refseq_protein_all_9823.faa

Please check

**Comment by jeet-vora** [comment]
@kmartinez834 @JingyueWu Was this issue resolved?

**Comment by kmartinez834** [comment]
@jeet-vora looks like you re-downloaded the files on Feb 18 and resolved the issue
