### ISSUE TITLE
Summer Internship Applicants Selection

### ISSUE THREAD

**Issue by Mindyporterfield** [glygener/glygen-issues#1035]
Selecting Applicants to Interview 

This summer, we will have 4 interns, 2 Bioinformatics and 2 Data Wrangling. We plan on interviewing 10 applicants in total.  

- Initial Screening: 
- - Received a total of 429 applicants for Bioinformatics and 205 for Data Wrangling. 
- - Downloaded applicants with graduation date/school year and work authorization from Handshake. 
- - Removed Freshman and Sophomore applicants. 
- - Manually scored the major for fit with the position, removing applicants with irrelevant majors (218 Bioinformatics, 78 Data Wrangling). 
- Combining and Removing Duplicates: 
- - Combined the two lists, resulting in 187 unique applicants. 
- Google Form: 
- - Sent a Google form to the remaining 187 applicants for further information. 
- Responses and Analysis: 
- - Received 150 responses to the Google form. 
- - Combined the responses with the original Handshake data using VLOOKUP and manual inspection. 
- Scoring System: 
- - Implemented a scoring system based on self-reported skill levels, year in school, and relevance of major. 
- - Penalized applicants with a complete lack of biology knowledge.  
- - Scores evaluated for overall knowledge and knowledge specific to the position. 
- - Provided a bonus for those with prior Glycan knowledge. 
- Position-specific Criteria: 
- - For Bioinformatics, prioritized skills in Java, Python, and machine learning. 
- - For Data Wrangling, prioritized skills in Excel data manipulation, and basic biology knowledge. 

- I have selected 20 applications for everyone to evaluate from applications received up to January 19 and numbered them 1-20. I will evaluate the remaining applicants (Jan 20-Jan 31) on Monday and choose 10-15 more.  

[This spreadsheet](https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Outreach/2024%20Summer%20-%20GlyGen%20%26%20CFDE%20Internship%20Workshop/InternshipApps1-8-24MP1.xlsx?d=we501c140f6d54bc19c479f76b6ce9919&csf=1&web=1&e=zgNTxw&nav=MTVfezNFMDUwQzBCLTFDMzctNEE0Ri04QzlCLTI4MDc2MUFBODgwOX0) has each applicants basic info  and scores

 [This folder](https://gwu0.sharepoint.com/sites/GlyGenTeam-GRP/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FGlyGenTeam%2DGRP%2FShared%20Documents%2FOutreach%2F2024%20Summer%20%2D%20GlyGen%20%26%20CFDE%20Internship%20Workshop%2FApplicants&viewid=6ffb8fed%2D81e7%2D4af7%2Dbfcd%2Da6f29c268132) contains a corresponding numbered folder with their additional documents  

You can see the [descriptions of the projects](https://wiki.glygen.org/index.php?title=GlyGen_Internships%2FGlyGen-CFDE_Summer_2024_Internship_Program_Announcement) 

2 Days of interviewing are scheduled : 

Monday Feb 12 1-4:30 pm and Thursday Feb 15 11:30-3pm. 

I need to notify the candidates who we select for the 1st interviews by Tue or Wednesday. I will send you all a poll to vote for your top 5 candidates for each position by number. If we need to get together to discuss them we need to schedule a webex before then.

**Comment by Mindyporterfield** [comment]
I completed the remaining applications the same way and have selected 11 more for you to see applicant numbers 30-40 
The  [excel sheet](https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7Be501c140-f6d5-4bc1-9c47-9f76b6ce9919%7D&action=edit&wdinitialsession=c1829cd5-4e45-46e2-b179-4e11c3f29f74&wdrldsc=18&wdrldc=1&wdrldr=CanvasRenderingFailure) tab group 2 final and  [documents folders](https://gwu0.sharepoint.com/sites/GlyGenTeam-GRP/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=Ml0h9e&cid=b8bf3340%2D7588%2D4849%2D8f0a%2D26a6a39851b5&FolderCTID=0x01200081407FA815A7124E846BD764353D93CC&id=%2Fsites%2FGlyGenTeam%2DGRP%2FShared%20Documents%2FOutreach%2F2024%20Summer%20%2D%20GlyGen%20%26%20CFDE%20Internship%20Workshop%2FApplicants&viewid=6ffb8fed%2D81e7%2D4af7%2Dbfcd%2Da6f29c268132) are available 
Please choose your top 7 for each category and fill out the google [form ](https://forms.gle/KpJoGJccmuedXQWA9)

We have interviews scheduled on Monday and we should let them know asap.

**Comment by jeet-vora** [comment]
@Mindyporterfield I have selected 7 candidates from the pool for each stream.
