### ISSUE TITLE
Add InChI key documentation & update BCO

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#104]
Dataset is glycan_sequences_inchi.csv (GLY_000289)

Linked to #95

**Comment by kmartinez834** [comment]
Also add Medline download to documentation

**Comment by kmartinez834** [comment]
The scripts used to generate compiled/cid2inchi.csv are downloading/copying PubChem compound files into `downloads/pubchem/compound/current` but symbolic link still points to the folder 07_16_2021

```
$ ll /data/projects/glygen/downloads/pubchem/compound/*current*
lrwxrwxrwx. 1 rykahsay glygen 10 Aug  2  2021 /data/projects/glygen/downloads/pubchem/compound/current -> 07_16_2021
```

--> Is this intended or should a new directory w/ current date be made for each download?

**Comment by rykahsay** [comment]
I am calling that folder archive --> it doesn't change, new batches get downloaded to it.

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/20584876/224852402-0d66175c-2843-4979-b39d-3ea7fd1af120.png">
