### ISSUE TITLE
Update dataset API default queries.

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#1048]
Some of the current default queries do not work at dsapi.glygen.org however, the API does appear to be working when modified. I am not adding the 2.3 milestone because I do not believe these are urgent changes needed.

1. 

**URL**: /dataset/detail
**Current query:**
{
  "bcoid": "ARGOS_000009",
  "dataversion": "1.51"
}
**does not work however, This does:**
{
  "bcoid": "GLY_000001",
  "dataversion": "2.3.1"
}

2. 
**URL**: /dataset/historydetail
**Not working Query:**
{
  "bcoid": "ARGOS_000009"
}

**Error** (_not sure how to fix this one_):
{
  "status": 0,
  "error": "field=doctype is required query field"
}

**Comment by rykahsay** [comment]
Fixed on tst
