### ISSUE TITLE
Download new Medline files

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#105]
Linked to #95

**Comment by rykahsay** [comment]
Can you give me example of PMIDs that need to be downloaded?

**Comment by kmartinez834** [comment]
PMIDs from the following files:
- rat_protein_function_refseq.csv
- human_protein_function_refseq.csv
- human_protein_reactions_reactome.csv
- mouse_protein_function_refseq.csv
- human_protein_mutation_literature.csv

**Examples:**
33686740
31721324
35181828
35257794
35183034
34920725
19168440
35070875
35955722
35886055
35290903
35768785
35848475
20504255
30716294
9605565
20173735
35596790
35802383
35705936
35269933
36005758
27515171
25245010
15754732
23526598
28173668
....

**Comment by rykahsay** [comment]
check now

**Comment by kmartinez834** [comment]
This resolved most of the missing PMIDs.

Some of the Medline files indicate that the PMID is a duplicate:

```
$ cat /data/projects/glygen/downloads/ncbi/medline/pmid.31088862.txt
id: 31088862 Error occurred: PMID 31088862 is a duplicate of PMID 31267715
```
I started a mapping file with "pmid" and "duplicate" fields in `misc/dup_pmid_mapping.csv`. I've only identified 4 dups so far, but I haven't tried running an exhaustive search.

--> Is it worth mapping these duplicates to the valid PMID?

**Comment by rykahsay** [comment]
Maybe in the next release -- create a new ticket asking me to start using generated/misc/dup_pmid_mapping.csv when creating datasets.
