### ISSUE TITLE
Provide ssh dev server access for Urnisha and Cyrus

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#1053]
Robel, can you please coordinate with Dacian to provide ssh server access for Urnisha and Cyrus? They soon will be doing data integration work on GlyGen server. 

@ubhuiyan and @CyrusAY Please provide Robel with your GW netid and email address. 

@jeet-vora @kmartinez834 FYI.

**Comment by ubhuiyan** [comment]
@rykahsay My email is sbhuiyan28@email.gwu.edu

**Comment by jeet-vora** [comment]
@ubhuiyan Sent an email RTS Help. Remind me if the access is not provided by Monday Feb 11. Thanks

Hi,

We would like Cyrus and Urnisha from our GlyGen team to get access to the GlyGen Dev server. Please provide access and login information/instructions to them.

Cyrus Chun Hong Au  - cyruschauyeung@gwmail.gwu.edu 
Urnisha Bhuiyan - sbhuiyan28@gwu.edu

Many thanks

**Comment by ubhuiyan** [comment]
Cyrus and I now have access to the server so I will close this ticket.
