### ISSUE TITLE
AWS deployment not working

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#1054]
@rykahsay Sorry for the delay I was sick Wednesday but I finished up running all the steps and doing what you instructed I do to get the site running. However, aws.glygen.org and the other AWS sites to not appear to be working. I am not sure what is causing this at this point.

Here is everything running:
![image](https://github.com/glygener/glygen-issues/assets/144174552/bc3b50b0-e33c-42cb-967b-d849a4591dc1)

However, this is what still shows on the site.
![image](https://github.com/glygener/glygen-issues/assets/144174552/13c9d1da-38cd-444a-b8eb-03bf51be936f)

**Comment by rykahsay** [comment]
Dacian has fixed the apache config issues, please continue now

<img width="529" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/893d0eea-77f6-4a5b-abb9-00bc4b9e7d5c">
