### ISSUE TITLE
Evaluation Biomarker "portal"

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1058]
What is the scope? The react code cannot be simply integrated into Robels data webpages. He is using plain HTML. So we need a different webapp running under a different URL.

1. How many pages are we talking about? Just details pages or also homepage, search etc.
2. How different is the (CFDE) biomarker webservice from the (GlyGen) biomarker webservice? Same structure - in that case we could reuse a lot of code.
3. What additional information beyond the GlyGen biomarker data need to be displayed? e.g. references to the origin

**Comment by ReneRanzinger** [comment]
From Raja:
Yes. Can we use https://hivelab.biochemistry.gwu.edu/biomarker-partnership/biomarkers 
1. Entry page, search, result. Daniall and I would like to draft a paper over the summer about the data model. Having some basic search I think would be needed to get it published. 
2. Identical 
3. Entry page, Ideas can be from https://data.oncomx.org/allbiomarkers/biomarker/A0001 (this page has lots of errors so don't look at data) and GlyGen entry page format can be used. Search page and result page can be similar to GlyGen (as much is doable)

**Comment by ReneRanzinger** [comment]
@rykahsay Can you please confirm the API response for biomarker is identical to GlyGen. We also need to know about the search feature and filters planned for search and list page.

@DaniallMasood What is the timeline we are talking about?

**Comment by seankim658** [comment]
Our API response schema is not exactly the same as the existing GlyGen Biomarker response schema. 

Daniall, Rene, and I met today (2/13/24) to discuss some early steps and considerations for the entry page. 

Things Daniall and I will work on for our next week's CFDE internal meeting:
- [ ] Details page for a biomakrer, what should that look like? Start with the GlyGen page and mock up from there what other things, changes, items we want added/removed from there
- [ ] Search functionalities, what type of searching functionality do we want, what fields can be searched on? 
- [ ] The entry page home page, what should that look like?  

Long term considerations: 
- [ ] Find some sort of potential middle ground between the GlyGen biomarker API response schema and our API response schema. If we can find some sort of middle ground, can write a set of internal endpoints so the GlyGen and biomarker entry page can reuse code.
