### ISSUE TITLE
GlyGen Dev Server Jumpstart Instructions

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#1060]
The following instructions are intended for performing data download, dataset check, and other QC-related tasks for GlyGen. Please note that such tasks require connection to the VPN.

- [ ] **Download and access the GW VPN using Global Protect: https://it.gwu.edu/vpn-global-protect** 
- [ ] **Open terminal in your computer (see screenshot as example)**
<img width="568" alt="Screen Shot 2024-02-12 at 1 56 09 PM" src="https://github.com/glygener/glygen-issues/assets/61590108/6b292e74-f484-4175-b1b9-a4a2efd94af6">

- [ ] **Log to the server using the email account name for login and not the GWID (see screenshot as example)**
<img width="567" alt="Screen Shot 2024-02-12 at 1 57 52 PM" src="https://github.com/glygener/glygen-issues/assets/61590108/720afd34-2173-439c-b0ef-31b596cde516">

- [ ] **Next, enter your GW password when prompted (see screenshot as example, note that when you enter your password, it will not show but don't worry about it, just enter your password as usual)** 

<img width="566" alt="Screen Shot 2024-02-12 at 1 59 16 PM" src="https://github.com/glygener/glygen-issues/assets/61590108/5834b297-e4f5-4afe-b817-e99ad95aa269">

- [ ] **Once you entered your password, you are in the GlyGen dev sever (see screenshot for example)**

<img width="631" alt="Screen Shot 2024-02-12 at 1 59 53 PM" src="https://github.com/glygener/glygen-issues/assets/61590108/c5812a77-da0e-4ca8-9f62-85d34ed88bcc">

- [ ] **Enter command `cd /data/projects/glygen/downloads` and then run `ls` command to explore the data resources that we download for each release (Note: the directories in the following screenshot are just some examples):** 

<img width="475" alt="Screen Shot 2024-02-12 at 2 04 19 PM" src="https://github.com/glygener/glygen-issues/assets/61590108/ab6203c4-b43d-4ad4-8bd0-4210e03ac948">

**Comment by ubhuiyan** [comment]
@JingyueWu I was able to successfully log on. Karina also showed me how to do this in VS Code as well. Thank you for the step by step instructions!
