### ISSUE TITLE
Process EBI Data for 2.4

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#1063]
Please process EBI data for 2.4, dataset-masterlist.json has been updated to reflect changes.  For this release pig has been added as organism. 

Please provide a list of failed files.

/data/projects/glygen/downloads/ebi/current

FYI @pkay47 @ubhuiyan @CyrusAY @Luke-Johnson-5  @JingyueWu

**Comment by rykahsay** [comment]
@pkay47  

1) couldn't create pig_protein_genelocus.csv because the following command gives zero lines
```
$ cat downloads/ebi/current/uniprot-proteome-sus_scrofa.nt  | grep Gene_Locus
```

2) couldn't create dicty_protein_transcsriptloucs.csv because the following command gives zero lines
```
$ cat downloads/ebi/current/uniprot-proteome-dictyostelium-discoideum.nt  | grep transcriptRange
```

**Comment by rykahsay** [comment]
Refseq downloads are not complete:

incomplete download for dicty (44689)
no files for pig (9823)

A serious question is, how did this pass your qc steps for downloads???

```
$ ls -ltr downloads/ncbi/refseq/current/refseq_protein_all_*

-rwxrwxr-x. 1 jingyue.wu glygen  1318752627 Jan 30 16:27 downloads/ncbi/refseq/current/refseq_protein_all_9606.gpff
-rwxrwxr-x. 1 jingyue.wu glygen   161967081 Jan 30 16:27 downloads/ncbi/refseq/current/refseq_protein_all_9606.faa
-rwxrwxr-x. 1 jingyue.wu glygen   640347783 Jan 30 16:27 downloads/ncbi/refseq/current/refseq_protein_all_10090.gpff
-rwxrwxr-x. 1 jingyue.wu glygen    74725329 Jan 30 16:27 downloads/ncbi/refseq/current/refseq_protein_all_10090.faa
-rwxrwxr-x. 1 jingyue.wu glygen   414262867 Jan 30 16:27 downloads/ncbi/refseq/current/refseq_protein_all_10116.gpff
-rwxrwxr-x. 1 jingyue.wu glygen    58473165 Jan 30 16:27 downloads/ncbi/refseq/current/refseq_protein_all_10116.faa
-rwxrwxr-x. 1 jingyue.wu glygen  2022773154 Jan 30 16:27 downloads/ncbi/refseq/current/refseq_protein_all_viral.gpff
-rwxrwxr-x. 1 jingyue.wu glygen   217320437 Jan 30 16:27 downloads/ncbi/refseq/current/refseq_protein_all_viral.faa
-rwxrwxr-x. 1 jingyue.wu glygen 40071080107 Jan 30 16:28 downloads/ncbi/refseq/current/refseq_protein_all_7227.gpff
-rwxrwxr-x. 1 jingyue.wu glygen  7031415019 Jan 30 16:29 downloads/ncbi/refseq/current/refseq_protein_all_7227.faa
-rwxrwxr-x. 1 jingyue.wu glygen 23681830141 Jan 30 16:30 downloads/ncbi/refseq/current/refseq_protein_all_559292.gpff
-rwxrwxr-x. 1 jingyue.wu glygen  3293293896 Jan 30 16:30 downloads/ncbi/refseq/current/refseq_protein_all_559292.faa
-rwxrwxr-x. 1 jingyue.wu glygen           0 Jan 30 16:30 downloads/ncbi/refseq/current/refseq_protein_all_44689.gpff
```

**Comment by pv47** [comment]
@rykahsay  In 2024_01 only geneRange is available for dicty/social amoeba. transcriptRange will be available from 2024_02.

**Comment by pv47** [comment]
@rykahsay For pig, there was error in glygen config, apologies. Updated QC checks for geneRange, transcriptRange, refseq & geneId xrefs 

FTP [https://ftp.ebi.ac.uk/pub/contrib/glygen/2024_01/] updated with regenerated NT & stats.

**Comment by jeet-vora** [comment]
@rykahsay 

- removed dicty_protein_transcriptlocus from masterlist.json
- Re-downloaded EBI data
- Re-downloaded RefSeq data

You can re-process the data
