### ISSUE TITLE
Process DO dataset for 2.4

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#1065]
Please process Disease Ontology data
/data/projects/glygen/downloads/do/current has been updated

please update the following datasets

protein_disease_idmap.csv
protein_disease_names.csv
*_protein_disease_glygen.csv
*_protein_disease_cdg.csv
*_protein_disease_genomics_england.csv
*_protein_disease_glyco.csv
*_protein_disease_glycosmos.csv
*_protein_disease_uniprotkb.csv
*_protein_disease_alliance_genome.csv
*_protein_disease_alliance_genome.csv

FYI @ubhuiyan @CyrusAY @Luke-Johnson-5 @JingyueWu

**Comment by rykahsay** [comment]
Done, check
