### ISSUE TITLE
Process human_protein_glycogenes_glycoenzonto.csv

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#1068]
Process human_protein_glycogenes_glycoenzonto.csv 

from the path
/data/projects/glygen/downloads/glycogenes/current/human_glycogenes_glycoenzonto.csv

**Steps 1**
- Map UniProt ACs from "UniProt" field to canonical accessions from human_protein_masterlist.csv
- Map Gene from "geneNames" to our current gene names from human_protein_masterlist.csv
- Map Entrez gene IDs from "Entrez Gene" from xref_id human_protein_xref_geneid.csv
- Map UniProt rec protein names from "Description" from human_protein_recnames.csv

Output
human_protein_glycogenes_glycoenzonto.csv

**Comment by rykahsay** [comment]
Done
```
$ head unreviewed/human_protein_glycogenes_glycoenzonto.csv 
"uniprotkb_canonical_ac","gene_name","gene_id","recommended_name_full"
"P15291-1","B4GALT1","2683","Beta-1,4-galactosyltransferase 1"
"P15291-1","GGTB2","2683","Beta-1,4-galactosyltransferase 1"
"O60512-1","B4GALT3","8703","Beta-1,4-galactosyltransferase 3"
"O60513-1","B4GALT4","8702","Beta-1,4-galactosyltransferase 4"
"O60909-1","B4GALT2","8704","Beta-1,4-galactosyltransferase 2"
"O43286-1","B4GALT5","9334","Beta-1,4-galactosyltransferase 5"
"Q9Y5Z6-1","B3GALT1","8708","Beta-1,3-galactosyltransferase 1"
"O43825-1","B3GALT2","8707","Beta-1,3-galactosyltransferase 2"
"O60507-1","TPST1","8460","Protein-tyrosine sulfotransferase 1"
```

**Comment by jeet-vora** [comment]
Done
