### ISSUE TITLE
Discard README in download directories

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#1069]
Karina's comment on Data Download documentation - "We should check with Jeet, but I think we could stop using the README in the directories from now on.  Best to keep only version of the documentation in this doc, otherwise it will end up being inconsistent." 

I agree and README.txt aren't always updated. 

https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/Data%20Download.docx?d=w6538b6993847482fac79174a1cbe6e1f&csf=1&web=1&e=IgnWmW 

Copied it over here as I've made some changes on the documentation. We can discuss during our scrum.

**Comment by kmartinez834** [comment]
All download instructions are now maintained in Sharepoint. Relevant info from READMEs will be included - individual README files to be deleted.
