### ISSUE TITLE
Inconsistency between Sequence viewer and Protvista

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1071]
https://www.glygen.org/protein/P05787-1

The site for O-glycans, Phosphorylation and mutation between sequence viewer and the corresponding ProtVista view do not match. ProtVista has more of all of them.

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger This looks like impact of server side pagination of certain tables. Data is getting shared between sequence viewer and those tables. So, truncated pagination data is showing truncated values on sequence viewer.

**Comment by ReneRanzinger** [comment]
We will have to solve this. Obvious choice would be to have these data tables not be server side paginated (white list). The bigger problem is that some of the tables (e.g. Phosphorylation) are the reason we "invented" the server side pagination. 

Alternative solution is to have additional arrays just with the positions:
* list of mutation position
* list of O-glycan positions
* etc

And use them for the sequence viewer. Since we do not have mouse over or something we only need the position. And if Robel makes a distinct the list will be even shorter.

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger Separate array lists containing all the required data for the corresponding types should solve the problem. Only problem is it might impact the search performance gains as all the records need to be searched and retrieved, only data sent will be minimal.

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger I believe these separate array lists for paginated tables used in sequence viewer, without changing existing data structure but only containing necessary data, should be precomputed, preprocessed and stored along with protein objects. This should reduce the search time, data footprint and solve our sequence viewer problem.

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger This way we can build a widget in future to be embedded by others which internally uses a web service which consumes this specific data. This was one of Jeet's request, I guess earlier. And if possible we can also publish about this viewer.

**Comment by sujeetvkulkarni** [comment]
Assigning this to Robel. Having a separate array for paginated tables(used in Sequence Viewer) with required data, without changing existing data structure but only containing necessary data, is preferred solution.

**Comment by sujeetvkulkarni** [comment]
@sujeetvkulkarni to add existing data structures with bare minimum data.

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger Please find the data below,

```
N-linked Sites:
O-linked Sites:

glycosylation: [
  {
    "type": "O-linked",
    "start_pos": 476,
    "end_pos": 476,
  },
  {
    "type": "N-linked",
    "start_pos": 653,
    "end_pos": 653,
  }
]

Variation from mutation:

snv: [
    {
        "start_pos": 43,
        "end_pos": 43,
    },
    {
        "start_pos": 67,
        "end_pos": 67,
    }
]

Sequon:

site_annotation: [
  {
    "start_pos": 294,
    "end_pos": 296,
  },
  {
    "start_pos": 402,
    "end_pos": 404,
  }
]

Phosphorylation:

phosphorylation: [
  {
    "start_pos": 2,
    "end_pos": 2,
  },
  {
    "start_pos": 26,
    "end_pos": 26,
  }
]

Glycation:

glycation: [
  {
    "start_pos": 66,
    "end_pos": 66,
  }
]
```

**Comment by ReneRanzinger** [comment]
@sujeetvkulkarni for Glycation, Phosphorylation, snv and glycosylation the sequence viewer only supports sites with single positions. So make them all integer arrays:
[1,2,3,4] 
Split n and o up in two individual arrays. No need to have "type": "N-linked" every time.

**Comment by sujeetvkulkarni** [comment]
@rykahsay Please find below the sample array lists those need to be added in protein/details api to address Sequence Viewer issue,

API: https://api.glygen.org/protein/detail/

N-linked Sites:

n_linked_sites: [
    476,
    653,
]

O-linked Sites:

o_linked_sites: [
    476,
    653,
]

Variation from mutation:

snv_sites: [
         43,
         67,
]

Sequon Sites:

sequon_annotation_sites: [
  {
    "start_pos": 294,
    "end_pos": 296,
  },
  {
    "start_pos": 402,
    "end_pos": 404,
  }
]

Phosphorylation Sites:

phosphorylation_sites: [
     2,
     26,
]

Glycation Sites:

glycation_sites: [
   66,
    68,
]

**Comment by ReneRanzinger** [comment]
I would package them in an own data property on the top level of protein details (or own webservice).
```
"sequence_features":
{
  "n_linked_sites": [
    476,
    653
  ],
  "o_linked_sites": [
    476,
    653
  ],
  "glycation_sites": [
    66,
    68
  ],
   ....
}
```

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger own web service should also capture protein sequence, length and accession etc along with site details. To make it truly independent. But details api need not contain other details except sites.

**Comment by rykahsay** [comment]
Please see below:

<img width="416" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/d119e7f8-e171-4887-930e-b17a167a5578">


```
...
  "sequence_features": {
    "n_linked_sites": [
      408
    ],
    "o_linked_sites": [
      9,
      13,
      14,
      15,
      24,
      27,
      34,
      36,
      37,
      39,
      58,
      64,
      67,
      74,
      425,
      441,
      449,
      475,
      477,
      478
    ],
    "snv_sites": [
      9,
      13,
      14,
      15,
      23,
      24,
      27,
      31,
      34,
      36,
      37,
      47,
      58,
      67,
      74,
      95,
      148,
      313,
      408,
      410,
      425,
      441,
      449,
      453,
      475,
      478
    ],
    "phosphorylation_sites": [
      2,
      9,
      13,
      14,
      15,
      21,
      22,
      24,
      25,
      26,
      27,
      31,
      34,
      35,
      36,
      37,
      39,
      43,
      44,
      74,
      104,
      204,
      228,
      240,
      243,
      251,
      253,
      258,
      267,
      274,
      291,
      315,
      330,
      400,
      404,
      410,
      417,
      424,
      427,
      431,
      432,
      436,
      437,
      438,
      441,
      442,
      445,
      451,
      456,
      475,
      477,
      478
    ],
    "sequon_annotation_sites": [
      {
        "start_pos": 272,
        "end_pos": 274
      },
      {
        "start_pos": 313,
        "end_pos": 315
      },
      {
        "start_pos": 408,
        "end_pos": 410
      },
      {
        "start_pos": 69,
        "end_pos": 71
      }
    ]
  },
...
```

**Comment by sujeetvkulkarni** [comment]
cbbf4e39784521a13448f2198e87566841c81bb5
