### ISSUE TITLE
Glycan Simple Search not working on PRD

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1072]
- "Any" search with Byonic string:
![image](https://github.com/glygener/glygen-issues/assets/90285371/129fdca3-f8fc-46f7-b2bb-3181a9e98a59)

- All Categories
![image](https://github.com/glygener/glygen-issues/assets/90285371/10986dfa-049d-43e0-9849-c856dd2a8912)

**Comment by rykahsay** [comment]
Try now
