### ISSUE TITLE
Links on Glycan subtypes go nowhere...

### ISSUE THREAD

**Issue by edwardsnj** [glygener/glygen-issues#1076]
On the Glycan details page, under Glycan Type / Glycan Subtype, the subtypes are sometimes hyperlinks that point into the GlycoMotif site. In many cases, these point to pages that don't exist (and I think never did). 

see: https://glygen.org/glycan/G17689DH (and the hyperlinked word "Complex").

Not sure if this is a back-end or front-end issue...

**Comment by ReneRanzinger** [comment]
@sujeetvkulkarni please check if the links are coming from you or Robel.

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger Robel sends the links...
API: https://api.glygen.org/glycan/detail/G17689DH

```
"classification": [
    {
        "type": {
            "name": "N-linked",
            "url": "https://glycomotif.glyomics.org/glycomotif/N-glycan"
        },
        "subtype": {
            "name": "Biantennary"
        }
    },
    {
        "type": {
            "name": "N-linked",
            "url": "https://glycomotif.glyomics.org/glycomotif/N-glycan"
        },
        "subtype": {
            "name": "Complex",
            "url": "https://glycomotif.glyomics.org/glycomotif/complex_N-glycan"
        }
    },
    {
        "type": {
            "name": "N-linked",
            "url": "https://glycomotif.glyomics.org/glycomotif/N-glycan"
        },
        "subtype": {
            "name": "Core-fucosylated"
        }
    }
]
```

**Comment by sujeetvkulkarni** [comment]
Assigning to Robel. 
Robel should remove url where there no wiki page exists.

**Comment by rykahsay** [comment]
I have removed the url for type and subtype (now on tst). 

@kmartinez834 --- please make sure this is reflected on the frontend when Sujeet deploys 2.4 version on tst server

<img width="585" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/52f4c438-0b6a-4efa-b8d2-f71ff200bb97">

**Comment by kmartinez834** [comment]
👍
