### ISSUE TITLE
New dataset: glycan_xref_gadr.csv

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1078]
|New dataset name|glycan_xref_gadr.csv|
|:-|:-|
| BCO ID |  GLY_000890| 
| Source file(s)| downloads/gadr/current/getglycanidmap.json|
|Instructions| The source file was provided by UGA and contains a mapping of the internal Glycan Array ID and the corresponding GlyTouCan ID. Create an xref dataset according to the output example below.| 

**Output example:**
```
"glytoucan_ac","xref_id","xref_key"
"G43981RC","3862081GAR","glycan_xref_gadr"
```

**Comment by rykahsay** [comment]
done, check

**Comment by kmartinez834** [comment]
Looks good
