### ISSUE TITLE
Rat numbers differ in glycan search and home page database statistics.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1079]
Home page number
<img width="353" alt="Screenshot 2024-02-16 at 2 48 39 PM" src="https://github.com/glygener/glygen-issues/assets/13891482/2b82a83b-0a80-4419-b345-462f2e2e046e">

API: https://api.glygen.org/pages/home_init

```
{
  "species": "Rat",
  "glycans": 7914,
  "proteins": 22890,
  "glycoproteins": 2673
}
```

API: https://api.glygen.org/glycan/search_init

{
  "name": "Rat",
  "id": 10116
}

id is 10116 and name is Rat in /glycan/search_init but 10116 refers to Rattus norvegicus (https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=10116).

So Glycan search uses corresponding id, name pair ("name": "Rat", "id": 10116) when glycan search is performed with Rat
returns 8139 Results. This does not match with home page numbers (7914).

https://www.glygen.org/glycan-list/0134b49d5f4efe75c347aa1f1898a2eb 

API: https://api.glygen.org/glycan/search?query={"operation":"AND","query_type":"search_glycan","glycan_name":"","organism":{"organism_list":[{"name":"Rat","id":10116}],"annotation_category":"","operation":"or"}}

<img width="1103" alt="Screenshot 2024-02-16 at 3 00 07 PM" src="https://github.com/glygener/glygen-issues/assets/13891482/81aeeeca-5d39-4177-86f0-9e9af32273a4">

Here there are two issues - 
1. Home page(7914) and glycan search numbers dont match (8139).
2. Glycan search uses 10116 tax id for Rat, as sent by /glycan/search_init.
Should we avoid using tax id for all organisms in glycan/protein search? Is backend currently ignoring id value?

**Comment by sujeetvkulkarni** [comment]
Ideally glycan search should work with or without specifying tax id, this will help in new species display where we will allow user to do glycan search based on common name.

**Comment by rykahsay** [comment]
<img width="1133" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/33e325ed-8d21-497c-8721-f8f77083ca3a">

**Comment by sujeetvkulkarni** [comment]
closing this issue but logging a new one Rat search - #1132.
