### ISSUE TITLE
Download file flags

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1080]
The software/glygen/download_summary.py script raised the following flags:

@jeet-vora / @JingyueWu 
- [x] Update permissions for glycogenes/current/
- [x] File size decrease: ebi/uniprot-proteome-hepatitis-c-virus-1b.nt
- [x] File size decrease: ebi/uniprot-proteome-sars-coronavirus.nt
- [x] File size decrease: ebi/uniprot-proteome-hepatitis-c-virus-1a.nt
- [x] File size decrease: ebi/dbSNP-rattus-norvegicus.tsv
- [x] File size decrease: ncbi/refseq/current/refseq_protein_all_44689.gpff

@kmartinez834 
- [x] The following protein files need to be updated after Nathan's export is downloaded: *_protein_matrixdb.csv
- [x] All of the OMA files decreased, mouse_dicty_oma_orthologs.txt size is now 0
- [x] File size decrease: reactome/ChEBI2Reactome_PE_Pathway.txt

**Comment by JingyueWu** [comment]
Can we close this ticket? @kmartinez834

**Comment by JingyueWu** [comment]
@kmartinez834 permissions for glycogenes/current/ looks right to me. Can you please double check? I'm not sure why it gets flagged.

**Comment by kmartinez834** [comment]
@JingyueWu please see the permissions of the files.  Can you make a ticket for Robel to fix this since Jeet is out?

**Comment by JingyueWu** [comment]
Done.
