### ISSUE TITLE
Making logging API asynchronous.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1082]
API: /log/logging?query
api needs to be asynchronous, as frontend need not know the result.
This will somewhat boost search page performance and reduce list page loading time to the user. This becomes more visible when number of users accessing the service is large, network bandwidth is less etc.

If already asynchronous, please close the ticket.

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger Once the search is performed we log search query along with list id, kind of links search query to list id in the logs. If we eliminate intermediate log before page navigation then we will loose that specific query (when the search is successful), list page logs list id.
We can try to change the logs and try to add it before search is performed. 
So when search is successful there wont be any log. Search failure we can continue to log, as we are doing right now.

**Comment by rykahsay** [comment]
I am giving start/end time stamps to show how much it is taking for the API computation, and I see it takes not time. If there is any delay, it should be a network delay. I have been complaining the docker internal network delays to Dacian and he has tried a a couple of things. In general, I am not happy about network issues within GW -- they might be doing lots of filtering/checking for security purposes.

<img width="1249" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/98b66721-fb1b-48b3-9d1e-7603331393fb">

**Comment by sujeetvkulkarni** [comment]
closing the issue without any frontend change.
