### ISSUE TITLE
Add new glygen team members to the BCOs

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#1083]
Please add Luke @Luke-Johnson-5 Luke, Urnisha @ubhuiyan and Cyrus @CyrusAY to existing GlyGen BCOs
      
       {
        "name": "Luke Johnson",
        "affiliation": "The George Washington University",
        "contribution": [
          "createdBy"
        ],
      "email": "luke.johnson@email.gwu.edu"
      },
     {
        "name": "Urnisha Bhuiyan",
        "affiliation": "The George Washington University",
        "contribution": [
          "createdBy"
        ],
      "email": "sbhuiyan28@email.gwu.edu"
      },
     {
        "name": "Cyrus Au-Yeung",
        "affiliation": "The George Washington University",
        "contribution": [
          "createdBy"
        ],
      "email": "cyruschauyeung@gwu.edu"
      }

**Comment by rykahsay** [comment]
Done, check
