### ISSUE TITLE
Check all protein datasets and make BCOs

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1085]
I have created all protein datasets, please check them.

The following datasets do not exist, please retire the corresponding BCOs.
```
GLY_000824,dicty_proteoform_glycation_sites_uniprotkb.csv,ERROR,in_bco
GLY_000828,dicty_proteoform_citations_glycation_sites_uniprotkb.csv,ERROR,in_bco
GLY_000833,dicty_protein_citations_reactome.csv,ERROR,in_bco
GLY_000834,dicty_protein_citations_refseq.csv,ERROR,in_bco
GLY_000837,dicty_protein_function_refseq.csv,ERROR,in_bco
GLY_000861,dicty_protein_xref_bgee.csv,ERROR,in_bco
GLY_000884,sarscov2_protein_genelocus.csv,ERROR,in_bco
```

The following datasets need new BCOs
```
NO-BCO,pig_protein_participants_reactome.csv,ERROR,in_fs
NO-BCO,pig_protein_participants_rhea.csv,ERROR,in_fs
NO-BCO,pig_proteoform_glycosylation_sites_glyconnect.csv,ERROR,in_fs
NO-BCO,pig_proteoform_glycosylation_sites_uniprotkb.csv,ERROR,in_fs
NO-BCO,pig_protein_reactions_reactome.csv,ERROR,in_fs
NO-BCO,pig_protein_binary_interactions.csv,ERROR,in_fs
NO-BCO,pig_protein_xref_oglcnac_db.csv,ERROR,in_fs
NO-BCO,pig_protein_xref_interpro.csv,ERROR,in_fs
NO-BCO,pig_protein_xref_kegg.csv,ERROR,in_fs
NO-BCO,pig_protein_xref_chembl.csv,ERROR,in_fs
NO-BCO,pig_protein_xref_pro.csv,ERROR,in_fs
NO-BCO,pig_protein_xref_reactome.csv,ERROR,in_fs
NO-BCO,human_protein_glycogenes_glycoenzonto.csv,ERROR,in_fs
NO-BCO,pig_protein_sequenceinfo.csv,ERROR,in_fs
NO-BCO,pig_protein_ntdata.nt,ERROR,in_fs
NO-BCO,pig_protein_ptm_annotation_uniprotkb.csv,ERROR,in_fs
NO-BCO,pig_protein_xref_oma.csv,ERROR,in_fs
NO-BCO,pig_protein_transcriptlocus.csv,ERROR,in_fs
NO-BCO,pig_protein_citations_refseq.csv,ERROR,in_fs
NO-BCO,pig_protein_signalp_fullsequences.fasta,ERROR,in_fs
NO-BCO,pig_protein_xref_panther.csv,ERROR,in_fs
NO-BCO,pig_protein_xref_rhea.csv,ERROR,in_fs
NO-BCO,pig_protein_pathways_reactome.csv,ERROR,in_fs
NO-BCO,pig_proteoform_glycosylation_sites_oglcnac_mcw.csv,ERROR,in_fs
NO-BCO,pig_protein_genelocus.csv,ERROR,in_fs
NO-BCO,pig_protein_function_refseq.csv,ERROR,in_fs
NO-BCO,pig_proteoform_citations_glycosylation_sites_oglcnac_mcw.csv,ERROR,in_fs
NO-BCO,pig_protein_xref_uniprotkb.csv,ERROR,in_fs
NO-BCO,pig_protein_xref_bgee.csv,ERROR,in_fs
NO-BCO,dicty_protein_ncbi_linkouts.csv,ERROR,in_fs
NO-BCO,pig_protein_allsequences.fasta,ERROR,in_fs
NO-BCO,pig_protein_xref_pdb.csv,ERROR,in_fs
NO-BCO,pig_protein_canonicalsequences.fasta,ERROR,in_fs
NO-BCO,pig_protein_citations_uniprotkb.csv,ERROR,in_fs
NO-BCO,pig_protein_genenames_refseq.csv,ERROR,in_fs
NO-BCO,pig_protein_xref_pfam.csv,ERROR,in_fs
NO-BCO,pig_protein_glycosylation_motifs.csv,ERROR,in_fs
NO-BCO,pig_protein_info_uniprotkb.csv,ERROR,in_fs
NO-BCO,pig_protein_xref_geneid.csv,ERROR,in_fs
NO-BCO,pig_protein_genenames_uniprotkb.csv,ERROR,in_fs
NO-BCO,pig_protein_xref_orthodb.csv,ERROR,in_fs
NO-BCO,pig_protein_function_uniprotkb.csv,ERROR,in_fs
NO-BCO,pig_protein_altnames.csv,ERROR,in_fs
NO-BCO,pig_protein_proteinnames_refseq.csv,ERROR,in_fs
NO-BCO,pig_protein_go_annotation.csv,ERROR,in_fs
NO-BCO,pig_protein_xref_refseq.csv,ERROR,in_fs
NO-BCO,pig_protein_masterlist.csv,ERROR,in_fs
NO-BCO,pig_protein_xref_cazy.csv,ERROR,in_fs
NO-BCO,pig_protein_xref_intact.csv,ERROR,in_fs
NO-BCO,pig_proteoform_phosphorylation_sites_uniprotkb.csv,ERROR,in_fs
NO-BCO,pig_protein_info_refseq.csv,ERROR,in_fs
NO-BCO,pig_protein_submittednames.csv,ERROR,in_fs
NO-BCO,pig_protein_citations_reactome.csv,ERROR,in_fs
NO-BCO,pig_protein_signalp_annotation.csv,ERROR,in_fs
NO-BCO,pig_protein_site_annotation_uniprotkb.csv,ERROR,in_fs
NO-BCO,pig_protein_xref_brenda.csv,ERROR,in_fs
NO-BCO,pig_protein_signalp_cleavedsequences.fasta,ERROR,in_fs
NO-BCO,pig_protein_xref_cdd.csv,ERROR,in_fs
NO-BCO,pig_protein_xref_glyconnect.csv,ERROR,in_fs
NO-BCO,pig_protein_recnames.csv,ERROR,in_fs
NO-BCO,pig_protein_ncbi_linkouts.csv,ERROR,in_fs
NO-BCO,pig_protein_signalp_peptidesequences.fasta,ERROR,in_fs
NO-BCO,pig_proteoform_citations_phosphorylation_sites_uniprotkb.csv,ERROR,in_fs
NO-BCO,pig_proteoform_citations_glycosylation_sites_uniprotkb.csv,ERROR,in_fs
NO-BCO,pig_protein_reactions_rhea.csv,ERROR,in_fs
```

**Comment by kmartinez834** [comment]
|BCO ID | Dataset Name| Creator Name|
|----|----|----|
|GLY_000891|pig_protein_participants_reactome.csv|Karina|
|GLY_000892|pig_protein_participants_rhea.csv|Karina|
|GLY_000893|pig_proteoform_glycosylation_sites_glyconnect.csv|Karina|
|GLY_000896|pig_proteoform_glycosylation_sites_uniprotkb.csv|Karina|
|GLY_000897|pig_protein_reactions_reactome.csv|Karina|
|GLY_000898|pig_protein_binary_interactions.csv|Karina|
|GLY_000899|pig_protein_xref_oglcnac_db.csv|Karina|
|GLY_000900|pig_protein_xref_interpro.csv|Karina|
|GLY_000901|pig_protein_xref_kegg.csv|Karina|
|GLY_000902|pig_protein_xref_chembl.csv|Karina|
|GLY_000903|pig_protein_xref_pro.csv|Karina|
|GLY_000921|pig_protein_xref_reactome.csv|Karina|
|GLY_000922|human_protein_glycogenes_glycoenzonto.csv|Karina|
|GLY_000923|pig_protein_sequenceinfo.csv|Karina|
|GLY_000925|pig_protein_ntdata.nt|Karina|
|GLY_000926|pig_protein_ptm_annotation_uniprotkb.csv|Karina|
|GLY_000927|pig_protein_xref_oma.csv|Karina|
|GLY_000929|pig_protein_transcriptlocus.csv|Karina|
|GLY_000930|pig_protein_citations_refseq.csv|Karina|
|GLY_000894|pig_protein_signalp_fullsequences.fasta|Karina|
|GLY_000931|pig_protein_xref_panther.csv|Karina|
|GLY_000933|pig_protein_xref_rhea.csv|Karina|
|GLY_000934|pig_protein_pathways_reactome.csv|Karina|
|GLY_000935|pig_proteoform_glycosylation_sites_oglcnac_mcw.csv|Karina|
|GLY_000936|pig_protein_genelocus.csv|Karina|
|GLY_000938|pig_protein_function_refseq.csv|Karina|
|GLY_000939|pig_proteoform_citations_glycosylation_sites_oglcnac_mcw.csv|Karina|
|GLY-000920|pig_protein_xref_uniprotkb.csv|Cyrus|
|GLY-000919|pig_protein_xref_bgee.csv|Cyrus|
|GLY-000918|dicty_protein_ncbi_linkouts.csv|Cyrus|
|GLY-000917|pig_protein_allsequences.fasta|Cyrus|
|GLY-000916|pig_protein_xref_pdb.csv|Cyrus|
|GLY-000915|pig_protein_canonicalsequences.fasta|Cyrus|
|GLY-000914|pig_protein_citations_uniprotkb.csv|Cyrus|
|GLY_000904|pig_protein_genenames_refseq.csv|Cyrus|
|GLY_000906|pig_protein_xref_pfam.csv|Cyrus|
|GLY_000905|pig_protein_glycosylation_motifs.csv|Cyrus|
|GLY_000907|pig_protein_info_uniprotkb.csv|Cyrus|
|GLY_000908|pig_protein_xref_geneid.csv|Cyrus|
|GLY_000909|pig_protein_genenames_uniprotkb.csv|Cyrus|
|GLY_000910|pig_protein_xref_orthodb.csv|Cyrus|
|GLY_000911|pig_protein_function_uniprotkb.csv|Cyrus|
|GLY_000912|pig_protein_altnames.csv|Cyrus|
|GLY_000913|pig_protein_proteinnames_refseq.csv|Cyrus|
|GLY_000952|pig_protein_go_annotation.csv|Luke|
|GLY_000951|pig_protein_xref_refseq.csv|Luke|
|GLY_000950|pig_protein_masterlist.csv|Luke|
|GLY_000949|pig_protein_xref_cazy.csv|Luke|
|GLY_000948|pig_protein_xref_intact.csv|Luke|
|GLY_000947|pig_proteoform_phosphorylation_sites_uniprotkb.csv|Luke|
|GLY_000946|pig_protein_info_refseq.csv|Luke|
|GLY_000945|pig_protein_submittednames.csv|Luke|
|GLY_000944|pig_protein_citations_reactome.csv|Luke|
|GLY_000894|pig_protein_signalp_annotation.csv|Luke|
|GLY_000943|pig_protein_site_annotation_uniprotkb.csv|Urnisha|
|GLY_000942|pig_protein_xref_brenda.csv|Urnisha|
|GLY_000894|pig_protein_signalp_cleavedsequences.fasta|Urnisha|
|GLY_000941|pig_protein_xref_cdd.csv|Urnisha|
|GLY_000940|pig_protein_xref_glyconnect.csv|Urnisha|
|GLY_000937|pig_protein_recnames.csv|Urnisha|
|GLY_000932|pig_protein_ncbi_linkouts.csv|Urnisha|
|GLY_000894|pig_protein_signalp_peptidesequences.fasta|Urnisha|
|GLY_000928|pig_proteoform_citations_phosphorylation_sites_uniprotkb.csv|Urnisha|
|GLY_000924|pig_proteoform_citations_glycosylation_sites_uniprotkb.csv|Urnisha|
|GLY_000895|pig_protein_reactions_rhea.csv|Urnisha|

**Comment by kmartinez834** [comment]
@jeet-vora I noticed many of the existing protein datasets (in other species) say "The dataset is derived from 2019-09 UniProt release." in their Usability Domain.  I'm assuming this is outdated, but can you confirm?  If so, should we remove this sentence since we won't be updating this section with every release?

**Comment by kmartinez834** [comment]
Same issue as above for RefSeq...Usability Domains say 2019, however, the files appear to be updated regularly (dicty example below):
![image](https://github.com/glygener/glygen-issues/assets/90285371/dd7dcf03-7e85-4e00-8bb6-64a66e61d286)

**Comment by Luke-Johnson-5** [comment]
Finished up apologies for the delay.

**Comment by kmartinez834** [comment]
Moving my comments above to #1091 

@rykahsay --> Reassigning to you to close the ticket

**Comment by rykahsay** [comment]
Remaining
```
NO-BCO,pig_proteoform_citations_glycosylation_sites_glyconnect.csv,ERROR,in_fs
```

Please don't forget to run the command given below 
```
python3 /software/glygen/check-bco2filename-mapping.py
```

**Comment by kmartinez834** [comment]
Done. 

GLY_000953 = pig_proteoform_citations_glycosylation_sites_glyconnect.csv

**Comment by Luke-Johnson-5** [comment]
https://docs.google.com/spreadsheets/d/1JxQi09YQaq39L_eduiyXtJYPzOy-kqH1GeTbfcGe2FA/edit?usp=sharing

**Comment by rykahsay** [comment]
@Luke-Johnson-5 -- I don't know what that spreadsheet is supposed to mean. If there are any issues, can you please write them here or make tickets for me.

**Comment by Luke-Johnson-5** [comment]
@rykahsay Apologies that was to make splitting the work between cyrus urnisha and I easier we almost have a full list of what needs to be double checked.

**Comment by jeet-vora** [comment]
> @jeet-vora I noticed many of the existing protein datasets (in other species) say "The dataset is derived from 2019-09 UniProt release." in their Usability Domain. I'm assuming this is outdated, but can you confirm? If so, should we remove this sentence since we won't be updating this section with every release?

@kmartinez834 Yes it needs to be removed as we cannot maintain it and the info is old.

**Comment by Luke-Johnson-5** [comment]
@kmartinez834 Protein datasets look good can I close this ticket?

**Comment by kmartinez834** [comment]
~~@Luke-Johnson-5 yes, you can close it~~

Edited - see comment below

**Comment by kmartinez834** [comment]
@Luke-Johnson-5 --> Since Robel made the ticket, can you assign back to him to close?

**Comment by Luke-Johnson-5** [comment]
Protein datasets look good.  @rykahsay
