### ISSUE TITLE
Test the frontend pages on tst.glygen.org and compare it with glygen.org

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#109]
As new REACT framework has been implemented test the frontend pages on tst.glygen.org and compare it with glygen.org.

Check for

- Visual appearance
- All options
- Buttons
- Links
- Pages

If the page on tst is different than on prd glygen.org add the issue by creating a document in https://gwu0.sharepoint.com/sites/GlyGenTeam-GRP/SitePages/ProjectHome.aspx. Add URLs and screenshot of both tst and prd

All pages on GlyGen to test - for e.g.- 

- Home Page
- Glycan and Protein search Pages (Simple, advanced composition etc)
- Glycan and Protein List Pages
- Glycan and Protein Detail Pages
- Site Search
- Super Search
- List of Motifs
- Try Me
- Quick Search
- Tools (All tools)
- Help and More

**Comment by JingyueWu** [comment]
@jeet-vora Minor change on the instruction: Since 2.0 got pushed onto beta yesterday, instead of looking at tst.glygen.org, I am looking at beta.glygen.org and compare it with glygen.org.

Status to update in my next comment.

**Comment by JingyueWu** [comment]
@jeet-vora I tested all pages, buttons, and links -- found 3 discrepancies which are documented [here](https://gwu0.sharepoint.com/sites/GlyGenTeam-GRP/_layouts/15/doc.aspx?sourcedoc={014e91e7-2acf-49af-b9ef-a8521f45e2b8}&action=edit). 

Please take a look and let me know if you need anything else, thanks.

**Comment by jeet-vora** [comment]
@JingyueWu The issue you found are good. Although they are not issues but new additions but it is good that you checked and are now aware of it.

I am not closing the ticket as I want you to do more clicks and play with it. Play with the below pages more as there are issues there. In addition to new additions test using examples.
Glycan and Protein search Pages (Simple, advanced composition etc)
Glycan and Protein List Pages
Glycan and Protein Detail Pages
Site Search
Super Search
Tools (All tools)

**Comment by JingyueWu** [comment]
@jeet-vora Most search results for the pages you mentioned above are the same between the two, however, see notes below:

1. beta.glygen.org has more gene, disease, glycol. site, protein, and enzyme number compared to glygen.org which I believe is expected. 
2. For "Tools" -> "Glycan Sequence Lookup," I see this on both after clicking "Click Me!" -- Is it normal expected? 

<img width="1188" alt="Screen Shot 2023-03-31 at 1 31 59 PM" src="https://user-images.githubusercontent.com/61590108/229189934-5b33884d-2847-4bd2-83ff-28b300569dc5.png">

3. Same as documented in my previous comment, "Glycan Structure Dictionary" is only lookup-able on beta.glygen.org.
4. ID, Name, and Motif numbers in the chart on GlycoMotif Wiki appeared to be synchronized which is good.
5. The order of "Glygen BLAST" and "Glygen Mapper" are different under "Tools" between the two sites:

<img width="1437" alt="Screen Shot 2023-03-31 at 1 36 49 PM" src="https://user-images.githubusercontent.com/61590108/229190922-9b452cae-1f0b-4db4-9fb2-ffa9266ec9f9.png">

<img width="1440" alt="Screen Shot 2023-03-31 at 1 37 09 PM" src="https://user-images.githubusercontent.com/61590108/229191015-89158e7b-aa81-48c3-9079-0d861245e3d9.png">

Please let me know if you have any questions or need any additional information, thanks.

**Comment by JingyueWu** [comment]
4/3 -- Take a closer look at Advanced.

**Comment by jeet-vora** [comment]
> @jeet-vora Most search results for the pages you mentioned above are the same between the two, however, see notes below:
> 
>     1. beta.glygen.org has more gene, disease, glycol. site, protein, and enzyme number compared to glygen.org which I believe is expected.
> 
>     2. For "Tools" -> "Glycan Sequence Lookup," I see this on both after clicking "Click Me!" -- Is it normal expected?
> 
> 
> <img alt="Screen Shot 2023-03-31 at 1 31 59 PM" width="1188" src="https://user-images.githubusercontent.com/61590108/229189934-5b33884d-2847-4bd2-83ff-28b300569dc5.png">
> 
>     3. Same as documented in my previous comment, "Glycan Structure Dictionary" is only lookup-able on beta.glygen.org.
> 
>     4. ID, Name, and Motif numbers in the chart on GlycoMotif Wiki appeared to be synchronized which is good.
> 
>     5. The order of "Glygen BLAST" and "Glygen Mapper" are different under "Tools" between the two sites:
> 
> 
> <img alt="Screen Shot 2023-03-31 at 1 36 49 PM" width="1437" src="https://user-images.githubusercontent.com/61590108/229190922-9b452cae-1f0b-4db4-9fb2-ffa9266ec9f9.png">
> 
> <img alt="Screen Shot 2023-03-31 at 1 37 09 PM" width="1440" src="https://user-images.githubusercontent.com/61590108/229191015-89158e7b-aa81-48c3-9079-0d861245e3d9.png">
> 
> Please let me know if you have any questions or need any additional information, thanks.

@JingyueWu None of the above are issues. Continue testing.
