### ISSUE TITLE
What are these query options on the motif property?

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1095]
There are only on motifs:

![motif](https://github.com/glygener/glygen-issues/assets/2267640/4b355929-10c8-407f-bfb5-020b086b6be7)

**Comment by sujeetvkulkarni** [comment]
why we need these options only on motif search and not others?

**Comment by sujeetvkulkarni** [comment]
Can we remove above highlighted entries and order all the other publication related entries to group together.

**Comment by rykahsay** [comment]
I have fixed it, and also tried to make it consistent across all concepets.

<img width="564" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/6f1176ba-0700-45a9-a41e-37def309674f">

**Comment by sujeetvkulkarni** [comment]
done.
