### ISSUE TITLE
SuperSearch: More dropdowns

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1097]
The following entries should be dropdowns or type aheads:

**Motifs**
* Aglycon
* Reducing end
* Motif alignment method

**Enzyme**
* Database

**Glycan**
* Database

**Protein**
* Database

**Comment by sujeetvkulkarni** [comment]
@rykahsay can you please provide total numbers for the above entries. So that we can turn them into drop dopdowns or type aheads based on the numbers.

**Comment by rykahsay** [comment]
Motif:aglycon --> 4 distinct values
Motif: reducing end --> 2 distinct values
Motif:Motif alignment method --> 4 distinct values

Protein:database --> 39 distinct values
Enzyme:database --> 39 distinct values
Glycan:database --> 23 distinct values

**Comment by rykahsay** [comment]
I have tried to implement this

@kmartinez834  @kmartinez834  please have the team test the supersearch interface carefully as I might have introduced a bug
