### ISSUE TITLE
Create Glycan Dictionary Card on wiki.glygen.org

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#11]
Can you create a Glycan Dictionary Card on wiki.glygen.org

Glycan Structure Dictionary
The Glycan Structure Dictionary has been developed as a reference dictionary to provide a standardized list of widely used glycan terms that can help in the curation and mapping of glycan structures described in publications.
https://wiki.glygen.org/Glycan_structure_dictionary

Also remove news section from wiki.glygen.org
We need to think what to do with Monthly Talks

**Comment by ReneRanzinger** [comment]
Did that and replaced monthly talks with [webinar series](https://wiki.glygen.org/GlyGen_Webinar_Series)
