### ISSUE TITLE
Learn to download data from other sources

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#110]
Like EBI, learn to download data from sources such as 

- [x] NCBI RefSeq
- [x] OMA
- [x] MGI
- [x] Alliance for genome resources
- [x] The O-GlcNAc Atlas
- [x] Mondo

Check if the readme is present for these resources and let me know. I will show you how to download data from these resources.

**Comment by JingyueWu** [comment]
@jeet-vora Download instructions for Alliance for genome resources and The O-GlcNAc Atlas are missing, please see following: 

**OMA**
cd /data/projects/glygen/downloads/oma
cat download_instructions

The orthology files can be downloaded from the OMA Browser - https://omabrowser.org/oma/home/ or https://omabrowser.org/oma/genomePW/

To get the orthology files between two species choose the option "Genome Pair Orthology" from tools menu option.

Enter the species 1 and 2 and select Source Data ACs (this gives the Ensembl IDs) to get the file. Repeat the process to get orthology pairs for other organisms.

Download the file and convert it into CSV and upload it to the GlyGen Dev OMA downloads folder.

**MGI**
cd /data/projects/glygen/downloads/mgi
cat download_instructions

To download the orthology fles for multiple organisms from MGI use the link - http://www.informatics.jax.org/homology.shtml or alternatively from http://www.informatics.jax.org/downloads/reports/index.html#homology

Download the file "Complete List of Vertebrate Homology Classes (plain text)" (Download a complete set of human, chimpanzee, rhesus macaque, dog, cattle, rat, chicken, western clawed frog and zebrafish 
Homology Classes for mouse genes. The report includes Chromosome and EntrezGene and OMIM IDs.) or http://www.informatics.jax.org/downloads/reports/HOM_AllOrganism.rpt

Convert the downloaded file rpt file into a CSV and upload it to the GlyGen Dev MGI downloads folder.

**Mondo**
cd /data/projects/glygen/downloads/mondo
cat cat download_instructions

To download mondo.owl access the github page - https://github.com/monarch-initiative/mondo
From the readme -> versions download the file - http://purl.obolibrary.org/obo/mondo.owl
create a folder in mondo as per the release which is mentioned on the github and wget the above file as mondo.owl

The owl file has to be converted into nt file for processing.

last edited - 12/02/2020

**The O-GlcNAc Atlas** (missing download instructions) 
cd /data/projects/glygen/downloads/atlas_oglcnac

<img width="473" alt="Screen Shot 2023-03-26 at 8 27 28 PM" src="https://user-images.githubusercontent.com/61590108/227814732-af572afe-f49e-46e6-b604-f6e7f5843cb6.png">

**NCBI RefSeq**
cd /data/projects/glygen/downloads/ncbi/refseq
cat cat download_instructions

The NCBI RefSeq files can be downloaded for all species from the NCBI RefSeq FTP Site - ftp://ftp.ncbi.nlm.nih.gov/refseq/

Files (all) related to proteins are downloaded from the FTP site in the downloads folder in the GlyGen Dev server such as -
.protein.faa.gz
.protein.gpff.gz

For homo sapiens - ftp://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/mRNA_Prot/
For mus musculus - ftp://ftp.ncbi.nlm.nih.gov/refseq/M_musculus/mRNA_Prot/
For rattus norvegicus - ftp://ftp.ncbi.nlm.nih.gov/refseq/R_norvegicus/mRNA_Prot/
For virus (all) - ftp://ftp.ncbi.nlm.nih.gov/refseq/release/viral/

Once the files are downloaded, separate files are appended together to create one file for the particular organism using cat function.
The files have to be downloaded in a new folder in /data/projects/glygen/downloads/ncbi/refseq labelled as per year and month eg. 2022_02
Follow the steps enlisted below. Complete the step before moving to the next step. The steps are to be run in the terminal in GlyGen server



For Human
=========
cd /data/projects/glygen/downloads/ncbi/refseq/*folder*/

Step 1: wget -b  ftp://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/mRNA_Prot/*protein.gpff.gz
Step 2: wget -b  ftp://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/mRNA_Prot/*protein.faa.gz
Step 3: gunzip *.gz
Step 4: cat human.*.protein.gpff > refseq_protein_all_9606.gpff
Step 5: cat human.*.protein.faa > refseq_protein_all_9606.faa


For Mouse
=========
cd /data/projects/glygen/downloads/ncbi/refseq/*folder*/

Step 1: wget -b  ftp://ftp.ncbi.nlm.nih.gov/refseq/M_musculus/mRNA_Prot/*protein.gpff.gz
Step 2: wget -b  ftp://ftp.ncbi.nlm.nih.gov/refseq/M_musculus/mRNA_Prot/*protein.faa.gz
Step 3: gunzip *.gz
Step 4: cat mouse.*.protein.gpff > refseq_protein_all_10090.gpff
Step 5: cat mouse.*.protein.faa > refseq_protein_all_10090.faa


For Rat
=======
cd /data/projects/glygen/downloads/ncbi/refseq/*folder*/

Step 1: wget -b  ftp://ftp.ncbi.nlm.nih.gov/refseq/R_norvegicus/mRNA_Prot/*protein.gpff.gz
Step 2: wget -b  ftp://ftp.ncbi.nlm.nih.gov/refseq/R_norvegicus/mRNA_Prot/*protein.faa.gz
Step 3: gunzip *.gz
Step 4: cat rat.*.protein.gpff > refseq_protein_all_10116.gpff
Step 5: cat rat.*.protein.faa > refseq_protein_all_10116.faa

For Viruses
===========
cd /data/projects/glygen/downloads/ncbi/refseq/*folder*/

Step 1: wget -b  ftp://ftp.ncbi.nlm.nih.gov/refseq/release/viral/*protein.gpff.gz
Step 2: wget -b  ftp://ftp.ncbi.nlm.nih.gov/refseq/release/viral/*protein.faa.gz
Step 3: gunzip *.gz
Step 4: cat viral.*.protein.gpff > refseq_protein_all_viral.gpff
Step 5: cat viral.*.protein.faa > refseq_protein_all_viral.faa

For Drosophila
==============
cd /data/projects/glygen/downloads/ncbi/refseq/*folder*/
Step 1: wget -b  ftp://ftp.ncbi.nlm.nih.gov/refseq/release/invertebrate/invertebrate.*.protein.gpff.gz
Step 2: wget -b  ftp://ftp.ncbi.nlm.nih.gov/refseq/release/invertebrate/invertebrate.*.protein.faa.gz
Step 3: gunzip *.gz
Step 4: cat invertebrate.*.protein.gpff > refseq_protein_all_7227.gpff
Step 5: cat invertebrate.*.protein.faa > refseq_protein_all_7227.faa

Make sure the new folder with new data has been marked as current. Create a ticket for Robel to update the files. 
If any new changes have been found notify him. Make necessary changes to the files in misc folder and if needed.
Reflect any new changes in BCOs

Robel will be processing the below files
refseq_protein_all_9606.faa
refseq_protein_all_9606.gpff
refseq_protein_all_10090.faa
refseq_protein_all_10090.gpff
refseq_protein_all_10116.faa
refseq_protein_all_10116.gpff
refseq_protein_all_viral.faa
refseq_protein_all_viral.gpff
refseq_protein_all_7227.gpff
refseq_protein_all_7227.faa

The commands/steps can be repeated for other species

last edited 10/22/2022

**Alliance for genome resources** (missing download instructions) 
cd /data/projects/glygen/downloads/alliance_genome

<img width="585" alt="Screen Shot 2023-03-26 at 8 31 53 PM" src="https://user-images.githubusercontent.com/61590108/227815032-7a266935-d14e-4508-9b02-a4299837da25.png">
