### ISSUE TITLE
SuperSearch: Invalid protein numbers after motif search

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1101]
Search motif for GlyTouCan ID G00054MO which is Sia Lewis X:

![motif](https://github.com/glygener/glygen-issues/assets/2267640/b77bf4be-9eb9-4cde-9758-ef9a300655f9)

Number of sites: 102 (suspicious but ok)
Number of proteins that bind glycans: 167 (very suspicious)
Number of proteins that have glycans attached 1 (extremely suspicious) one protein with 102 sites?

If I click on the 167 I come to proteins that are enzymes but the glycan binding section is empty.

If I click on the 1 I come to a protein which has nothing to do with the motif.

**Comment by rykahsay** [comment]
I have tried to fix it on tst, and give below is what it shows now. Remember the following "edge-rules" when searching from "motif":

```
these can be connected in both directions
species <-> protein
species <-> gene
gene <-> disease
disease <-> protein
disease <-> site

these can only be connected in one direction
species -> glycan
protein -> glycan
protein -> site
gene -> protein
enzyme -> protein
enzyme -> glycan
glycan -> motif
site -> glycan
```


<img width="1274" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/7931da97-c9e0-44e2-a3ee-13b1fa14e0ba">

**Comment by ReneRanzinger** [comment]
Sorry, how is this fixed? We have some of these glycans on 102 sites. But not a single protein that has this site?

**Comment by rykahsay** [comment]
It looks like there was a problem on the ignored edge rules. I have tried to fix it and this is what I get now:

<img width="1284" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/55a4e933-73a1-4da7-a9a7-7df186b7fd63">

**Comment by ReneRanzinger** [comment]
@sujeetvkulkarni can you please look at this. It seems still unlikely to me. We have 1208 glycosylationsites on 60 proteins. That would mean that in average each protein has at least 20 sites (glycosylation) + potential other sites. Seems a lot. Even our showcase protein only has 5 sites. Maybe there is distinct missing on site? A.k.a glycan a,b,c are all on site X of a protein and it counts it as 3 sites rather than 1?

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger I will look into it in more detail. But just to let you know 1208 is the search result number that will be listed on the site list page. Its neither number of proteins or sites. You can say its a distinct on (protein acc + site start position + site end position).

**Comment by ReneRanzinger** [comment]
`(protein acc + site start position + site end position)`
That is the (my) definition of **site**. But since we started with a motif/glycan it means that the 1208 **must** be glycosylation site. That at the same sites other stuff might be happen as well (SVN, phosphorylation etc) is possible.

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger 
![Screenshot 2024-03-07 at 1 11 45 PM](https://github.com/glygener/glygen-issues/assets/13891482/539cb271-2bd8-40f9-bfce-f297a0a3ff75)

Of 1208 looks like 587 are related to glycosylation - total filters count. 
I believe if you follow the graph ->
Motif query results in 1227 glycans which results in 102 sites - they are related to glycans and are all gycosylated.
These 102 sites result in 60 proteins but as Robel has made this edge bi directional this results in 60 protein contributing to both glycosylated and other type of 1208 sites (edge). Yellow site box shows distinct of (1208 sites + 102 sites) - 1208 sites.

I will download 1208 sites results and analyze it in more details for different type of sites.
From my point  102 glycosylation sites which contributes to 60 proteins should not  have contributed to more than 500 glycosylation sites (out of 1208). There should have been only 102 glycosylation sites out of 1208 total sites.

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger @rykahsay 
On further analysis I noticed that there are 538 glycosylation sites out of 1208 sites. 
It looks like there are some glycosylation sites from the same proteins which are not getting reported in 102 sites.
All 1208 sites, 102 sites, 538 glycosylation sites (out of 1208 sites), 60 proteins contains the same 60 proteins listed below,

```
uniprot_canonical_ac
O00300-1
O00391-1
O09164-1
O60603-1
O75888-1
P00450-1
P00738-1
P01009-1
P01011-1
P01033-1
P01588-1
P01591-1
P01833-1
P02675-1
P02750-1
P02763-1
P02765-1
P02787-1
P02788-1
P02790-1
P03951-1
P03956-1
P04004-1
P04062-1
P04070-1
P04233-1
P04925-1
P05155-1
P06858-1
P08603-1
P08637-1
P08709-1
P0C0L4-1
P0C0L5-1
P0DN86-1
P0DTC2-1
P10909-1
P13987-1
P16671-1
P19440-1
P22897-1
P23280-1
P23284-1
P24821-1
P25311-1
P32736-1
P41222-1
P41271-1
P45877-1
P47710-1
P80188-1
Q02487-1
Q08380-1
Q08431-1
Q13410-1
Q14624-1
Q6WN34-1
Q92876-1
Q99523-1
Q9BY76-1
```

Below 9 glycosylation sites from Q99523-1 are reported in 1208 sites.
```
Q99523-1	Sortilin	162	162
Q99523-1	Sortilin	274	274
Q99523-1	Sortilin	98	98
Q99523-1	Sortilin	406	406
Q99523-1	Sortilin	582	582
Q99523-1	Sortilin	206	206
Q99523-1	Sortilin	684	684
Q99523-1	Sortilin	99	99
Q99523-1	Sortilin	163	163
```

But only 1 glycosylation site is reported in 102 sites,

```
Q99523-1	Sortilin	98	98
```
https://tst.glygen.org/protein/Q99523-1#Glycosylation


Somehow glycosylation sites are getting suppressed from 1227 glycans to 102 sites edge.
In my opinion it should report all 538 glycosylation sites (out of 1208).
1227 glycans - 538 glycosylation sites - 60 proteins.

And if you dont want 1208 sites listed on site box, make site-protein edge unidirectional. So 60 proteins wont contribute back non glycosylated sites, increasing the number from 538 to 1208. Disable protein-site edge.

**Comment by sujeetvkulkarni** [comment]
Further details,
From all the glycans in glycosylation table in Q99523-1 (https://tst.glygen.org/protein/Q99523-1#Glycosylation) only G71146HJ (https://tst.glygen.org/glycan/G71146HJ#Motifs) present in 1227 glycan list. So that could be the reason for suppressing glycosylation sites to 102 - distinct (glycan id + site position). In that case it would be difficult to increase the count from 102 to 538.

**Comment by rykahsay** [comment]
I have disallowed "protein" to "site" propagation, and this is what I see now:

<img width="1296" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/9d21662f-d087-4c7b-b010-015e1d5e2c6e">

**Comment by sujeetvkulkarni** [comment]
done.
