### ISSUE TITLE
All protein Datasets being tagged as new_dataset

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#1103]
I am working on qc for the protein datasets however right now the datasets are all being shown as new_dataset with 0 id_count_old, row_count_old, and feild_count_old.

I ran the command: nohup python3 check-dataset-group.py -m protein -r 2.4 &

I am not sure if this is an issue because I ran the command wrong or if this is a processing issue?

See image:
![image](https://github.com/glygener/glygen-issues/assets/144174552/3c897d20-ea4c-4de0-8d3b-9e71bb22ff10)

**Comment by rykahsay** [comment]
You have to do 2.4.1

**Comment by rykahsay** [comment]
@kmartinez834 @jeet-vora is  there a documentation on how you use check-dataset-group.py? If not, how come? If there is, was Luke given proper guide on how the script should be used?
