### ISSUE TITLE
Reprocess glycan_species.csv

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1107]
In `unreviewed/glycan_species.csv` , replace "xref_id" for rows with "xref_key" == "glycan_xref_embl"

From: 
```
"xref_key","xref_id"
"glycan_xref_embl","GLY_000708"
"glycan_xref_embl","GLY_000709"
```

To:
```
"xref_key","xref_id"
"glycan_xref_embl","10.1101/2023.09.13.557529v1"
```

I have updated `xref_info.csv` and `doi_citations.csv` accordingly. I will update in 2.5 to point to the new datasets, also note that the BCO ids are incorrect and I've asked Nathan to fix in the next export.

**Comment by rykahsay** [comment]
Done, check

**Comment by kmartinez834** [comment]
The publication page for https://glygen.org/publication/DOI/10.1101/2023.09.13.557529v1 is missing.  The information was already added to doi_citations.csv 
 
![image](https://github.com/glygener/glygen-issues/assets/90285371/dfb7cf9d-8bad-470a-81ea-545f0f5d46a9)

**Comment by kmartinez834** [comment]
Make sure there isn't a workflow issue.  misc/doi_citations.csv was updated last release, but publication page didn't get created.

**Comment by rykahsay** [comment]
The rows have been replaced
```
$ cat unreviewed/glycan_species.csv  | awk -F"\",\"" '{print $8,$9}' | grep glycan_xref_embl |sort -u
glycan_xref_embl 10.1101/2023.09.13.557529v1
```

**Comment by kmartinez834** [comment]
For all rows with:
```
"xref_key","xref_id"
"glycan_xref_pdc-ccrcc","GLY_000961"
```

replace with:
```
"xref_key","xref_id"
"protein_xref_pdc","PDC000471"
```

**Comment by rykahsay** [comment]
done ,check

**Comment by kmartinez834** [comment]
Looks good.  

Regarding the EMBL annotations above, I've asked Nathan to add the DOI to his export next release (#1342). For 2.5 there will be an evidence badge pointing to the GlyGen datasets.
