### ISSUE TITLE
Add new member Kate Warner to GlyGen organization 

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#1109]
Hi @ReneRanzinger, can you please add Kate to the glygener organization? Starting today, she will be working as a consultant for the GlyGen project. You will get to meet her during next week's collaborators meeting. I don't seem to be able to add her to any of the GlyGen repo. 

Her GitHub username is [katewarner](https://github.com/katewarner) 

Pleases let me know if you need any additional information from my end, thanks.

**Comment by ReneRanzinger** [comment]
Done.
