### ISSUE TITLE
Common name is coming as name in Species array it should be species name.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1111]
API: https://api.tst.glygen.org/glycan/detail/G00031MO/

name is coming as "Rat" in both  "taxid": 10116 and  "taxid": 10114,
It should be  Rattus norvegicus and Rattus respectively.

```
species: [
{
  "taxid": 10116,
  "name": "Rat",
  "annotation_category": "direct",
  "evidence": [
    {
      "database": "GlyConnect",
      "id": "1947",
      "url": "https://glyconnect.expasy.org/browser/structures/1947"
    },
    {
      "database": "GlyCosmos",
      "id": "G00031MO",
      "url": "https://glycosmos.org/glycans/show/G00031MO"
    },
    {
      "database": "PubMed",
      "id": "1189846",
      "url": "https://glygen.org/publication/PubMed/1189846"
    },
    {
      "database": "PubMed",
      "id": "1191682",
      "url": "https://glygen.org/publication/PubMed/1191682"
    },
    {
      "database": "PubMed",
      "id": "2573604",
      "url": "https://glygen.org/publication/PubMed/2573604"
    },
    {
      "database": "PubMed",
      "id": "7061510",
      "url": "https://glygen.org/publication/PubMed/7061510"
    }
  ],
  "common_name": "Rat"
},
{
  "taxid": 10114,
  "name": "Rat",
  "annotation_category": "direct",
  "evidence": [
    {
      "database": "GlyCosmos",
      "id": "G00031MO",
      "url": "https://glycosmos.org/glycans/show/G00031MO"
    }
  ],
  "common_name": "Rat"
}
]
```

**Comment by rykahsay** [comment]
@ReneRanzinger ... didn't we agree to be consistent everywhere and not show the scientific names. My understanding was that there will never be  "Homo sapiens" anywhere in our system and will be replaced by "Human". That is the reason I replaced "Rattus norvegicus" and "Rattus" by "Rat".

**Comment by sujeetvkulkarni** [comment]
@rykahsay @ReneRanzinger This will get displayed when user will expand the species row in the table. On top level common name will be displayed but when user clicks on show more he will get detailed evidence with species name. Species object in the species array sends common name in   "common_name" property and should be send species name in "name" property.
This was agreed in the [Mockup](https://gwu0.sharepoint.com/:p:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7BC445A13B-E8D3-41E1-A2D2-D0959AA1847B%7D&file=Glycan_organism_display_1007.pptx&action=edit&mobileredirect=true).

**Comment by ReneRanzinger** [comment]
@sujeetvkulkarni and @rykahsay You are both right. On the top level (simple user mode) we do not use scientific names. We use the agreed names from the last column of the table in the last slide of the [Mockup](https://gwu0.sharepoint.com/:p:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7BC445A13B-E8D3-41E1-A2D2-D0959AA1847B%7D&file=Glycan_organism_display_1007.pptx&action=edit&mobileredirect=true):
* Species dropdowns (advance search, quick search, super search)
* Species filter (search result pages)
* Organism display (glycan page)

However, if the user goes into the expert mode (see more) on Organism display. He sees the actual species (Taxon ID) assignments together with the scientific name for this taxon.

**Comment by rykahsay** [comment]
<img width="436" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/47c8e7cb-50e4-42e5-ba35-5381fb2088f1">

**Comment by sujeetvkulkarni** [comment]
done.
