### ISSUE TITLE
publication, cross reference data is missing from glycan details api.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1112]
API: https://api.tst.glygen.org/glycan/detail/G17689DH/

crossref:[], publication:[] data is not coming.

Please check if any other type of data is missing.

**Comment by rykahsay** [comment]
Maybe I was loading to the MongoDB when you tried it, it is working now:

<img width="537" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/277f35dc-cc0c-4950-827f-2d19d116b13c">

<img width="485" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/d75aefc5-1aa4-472a-ae1e-4bd3c29f779b">

**Comment by sujeetvkulkarni** [comment]
done.
