### ISSUE TITLE
Add new people/remove people from about us page.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1113]
@edwardsnj I think your group composition has changed. Please let us know who to add and who to put in **Former Members**. We also need picture, name, link and role.

@rajamazumder We need the information about the new members in your group. We need picture, name, link and role.

**Comment by ReneRanzinger** [comment]
We can have a "other contributor" link on the page that goes to a Wiki page that is easier to maintain.

@ReneRanzinger will contact @edwardsnj and @rajamazumder about the list of people.
