### ISSUE TITLE
Testing for GlyGen API 

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1118]
- Download a copy of the [uqt_updated_template](https://gwu0.sharepoint.com/sites/GlyGenTeam-GRP/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=vxhgVn&cid=02722979%2D42a8%2D44c3%2D9f90%2D30f01fedcd50&RootFolder=%2Fsites%2FGlyGenTeam%2DGRP%2FShared%20Documents%2FBackend%2FTesting%2FTesting%20Results%2FUltra%20Quick%20Test&FolderCTID=0x01200081407FA815A7124E846BD764353D93CC) and answer the questions that pertain to the section you are testing. 
- Create tickets for any bugs found during testing

**Comment by Luke-Johnson-5** [comment]
api looks good on tst
