### ISSUE TITLE
GlyGen Frontend Testing 

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1119]
- Download a copy of the [uqt_updated_template](https://gwu0.sharepoint.com/sites/GlyGenTeam-GRP/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=vxhgVn&cid=02722979%2D42a8%2D44c3%2D9f90%2D30f01fedcd50&RootFolder=%2Fsites%2FGlyGenTeam%2DGRP%2FShared%20Documents%2FBackend%2FTesting%2FTesting%20Results%2FUltra%20Quick%20Test&FolderCTID=0x01200081407FA815A7124E846BD764353D93CCrl), and complete the sections that pertain to your testing. 
- Save document as _testname_server_date_initials_ - ex. _uqt_tst_030624_ub.docx_, then upload to the same folder in SharePoint (Ultra Quick Test).
- Create tickets for any bugs you discover during testing.

**Comment by JingyueWu** [comment]
Adding @katewarner to this task. Kate - please follow the instructions in the above link and perform a testing. I think this task will help you explore what information is on the GlyGen knowledgeable. Please let me or Urnisha know if you have any questions or concerns.

**Comment by ubhuiyan** [comment]
I'd also like to note that it may be helpful for all of us to look into fields of GlyGen that aren't explicitly mentioned in the document. Should you find any bugs in items that aren't documented in the UQT file please let me know and I will be happy to add it!

**Comment by katewarner** [comment]
Okay will do.
