### ISSUE TITLE
GlyCosmos xrefs

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#112]
`glycan_xref_glycosmos.csv` is set to "integrate_none" in `dataset-masterlist.json` -- is this intended?  

I can not find any glycan APIs with GlyCosmos listed the "crossref" list.

**Comment by kmartinez834** [comment]
@jeet-vora

**Comment by rykahsay** [comment]
I don't know why !

**Comment by kmartinez834** [comment]
`glycan_xref_glycosmos.csv` is now set to "integrate_all" in `dataset-masterlist.json`

Also updated `xref_info.csv` to point to correct url
