### ISSUE TITLE
Discontinue old sandbox server

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1122]
@rykahsay please check if we have any URL in the system with the base path "https://glygen.ccrc.uga.edu/sandbox/".

These should be discontinued and replace with URLs to Nathans version of the sandbox "https://sandbox.glyomics.org/".

After they are all gone assign this ticket back to me.

**Comment by rykahsay** [comment]
It looks like @kmartinez834 already changed it on our xref_info.csv dictionary file and it has taken effect on tst server.


```
$ cat generated/misc/xref_info.csv | grep sandb
glycan_xref_sandbox,SandBox,https://sandbox.glyomics.org/explore.html?%s,G00012RZ|G00017IP|G00012RZ
```

<img width="638" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/03fdd6c0-8bb4-4153-8906-f576278001b1">


<img width="674" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/800fcc22-c6b8-428d-83fe-f6817b3fcfd2">
