### ISSUE TITLE
Pig Glycans in Search Results Does Not Match Data Statistics

### ISSUE THREAD

**Issue by CyrusAY** [glygener/glygen-issues#1126]
An issue found in GlyGen frontend testing (#1119):

Data statistics table in the home page shows there are 7313 pig glycans, but glycan simple search (search term: pig; category: organism) returns 7319 search results.
All other organisms, glycans or proteins, otherwise do not have the same issue with the numbers.

**Comment by rykahsay** [comment]
That is ok, "simple" search is a text search that targets many other fields and it is possible some glycans have the word "pig" in other fields. If you want to make such comparison, you have to do "advanced" search and use "organism" pull down. This will give you the right number as shown below:

<img width="1039" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/368f1a41-c6c8-4d74-8690-f58923137330">
