### ISSUE TITLE
Glycan Simple Search Example Does Not Work

### ISSUE THREAD

**Issue by CyrusAY** [glygener/glygen-issues#1127]
An issue found in GlyGen frontend testing (#1119):

The "Homo sapiens" example in glycan search does not work. An error message showed:

Simple Search Error - No Results Found
Sorry, we couldn't find any data matching your input. Please change your search term and try again.

It still does not work even if i select "Organism" in the category dropdown menu.
It works when I type "human" instead.

**Comment by rykahsay** [comment]
Maybe it was loading when you tried it, looks like it is working now

<img width="1062" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/416a2598-6dcb-430b-975f-2748628a3d20">

**Comment by CyrusAY** [comment]
It is working today so I am closing the ticket
