### ISSUE TITLE
PubMed Links Don't Work

### ISSUE THREAD

**Issue by CyrusAY** [glygener/glygen-issues#1128]
An issue found in GlyGen frontend testing (#1119):

In glycan detail pages (I am using G08146BT as an example), under the associated protein section, when you click on the PubMed source, it expands to a list of PMIDs but none of those links work. An error message shows:

Network Error
Oops, something went wrong. Please try again later. If the problem persists then you may contact us.

None of the tables are populated in the publication detail page.

**Comment by rykahsay** [comment]
It is ok, this problem will go away once we push to production

**Comment by kmartinez834** [comment]
The `/data/shared/glygen/releases/data/v-2.3.1/jsondb/publicationdb/` folder is empty.... is this expected?

**Comment by kmartinez834** [comment]
@CyrusAY looks like this issue has been resolved now, please check

**Comment by CyrusAY** [comment]
Resolved
