### ISSUE TITLE
Edit human_protein_glycohydrolase.csv column name 

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1129]
![human_protein_glycohydrolase](https://github.com/glygener/glygen-issues/assets/90285310/d3be06c0-1759-4635-ac22-c3fb9251246f)

I found a typo in this dataset. The circled column needs to be edited.

**Comment by rykahsay** [comment]
check it now
![Uploading image.png…]()

**Comment by ubhuiyan** [comment]
@rykahsay I don't think the column has changed on the frontend side. I am still seeing "family" spelled incorrectly.

**Comment by rykahsay** [comment]
if you don't see it fixed on beta, you may need to clear your cache

<img width="1307" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/ccb61e1b-fcb4-4544-a1c4-3becbf9a96ba">
