### ISSUE TITLE
back end should not modify user query from Rat to Rattus and Rattus norvegicus.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1132]
User performs a glycan search using Rat option from Organism dropdown.

https://api.tst.glygen.org/glycan/search?query=
{"operation":"AND","query_type":"search_glycan","glycan_name":"","organism":{"organism_list":[{"name":"Rat","id":10116}],"annotation_category":"","operation":"or"}}

Back end internally changes the query to 
https://api.tst.glygen.org/glycan/list?query=
{"id":"15a47d0a95b92ae69d6001a905c3d8c2","offset":1,"sort":"hit_score","limit":20,"order":"desc","filters":[]}

response - >

```
{
    "cache_info": {
        "query": {
            "operation": "AND",
            "query_type": "search_glycan",
            "organism": {
                "organism_list": [
                    {
                        "id": 10114,
                        "name": "Rattus"
                    },
                    {
                        "id": 10116,
                        "name": "Rattus norvegicus"
                    }
                ],
                "annotation_category": "",
                "operation": "or"
            }
        },
        "ts": "2024-03-11 11:13:22 EDT-0400",
        "record_type": "glycan",
        "search_type": "search"
    },
````

Backend internally modifies the query to Rattus and Rattus norvegicus as shown above.
We should not directly modify user query. We should map user search from Rat (with any id either 10114 or 10116) internally to Rattus and Rattus norvegicus both but should not modify user query directly in cache_info.

**Comment by rykahsay** [comment]
For glycan_search  by organism, I have modified how this should work now and you will need to do the following adjustments when you perform search by organism:

### searching by common_name
This example will get you 7967 records that belong to 10116 or 10114
```
{
    "query": {
        "organism": {
            "operation": "or",
            "organism_list": [
                {
                    "common_name": "Rat"
                }
            ]
        }
    },
    "ts": "2024-03-12 07:02:32 EDT-0400",
    "record_type": "glycan",
    "search_type": "search"
}
```

### searching by tax_id
This example will get you 5189 records that belong to 10116 
```
{
    "query": {
        "organism": {
            "operation": "or",
            "organism_list": [
                {
                    "id": 10116
                }
            ]
        }
    },
    "ts": "2024-03-12 07:05:14 EDT-0400",
    "record_type": "glycan",
    "search_type": "search"
}
```

### searching by name
This example will also get you 5189 records that belong to 10116 
```
{
    "query": {
        "organism": {
            "operation": "or",
            "organism_list": [
                {
                    "name": "Rattus norv"
                }
            ]
        }
    },
    "ts": "2024-03-12 07:06:37 EDT-0400",
    "record_type": "glycan",
    "search_type": "search"
}
```

**Comment by sujeetvkulkarni** [comment]
cbbf4e39784521a13448f2198e87566841c81bb5
