### ISSUE TITLE
Dead link on SPARQL

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#1133]
https://sparql.tst.glygen.org/

WebVOWL link not working. This link is from the hyperlink within the paragraph seen below on the SPARQL site.

![image](https://github.com/glygener/glygen-issues/assets/144174552/a99dcff9-11ec-4023-ab76-5c8152f3c189)

**Comment by rykahsay** [comment]
Ignore sparql on tst
