### ISSUE TITLE
GSAAPI / GSA not working on tst.

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#1134]
https://gsaapi.tst.glygen.org/ not working on test.

![image](https://github.com/glygener/glygen-issues/assets/144174552/bacc498b-7add-4f4f-be50-01688b21abdf)

**Comment by Luke-Johnson-5** [comment]
Upon further checks it seems that the GSA page is not working on tst either. I was not sure of the domain but https://tst.gsa.glygen.org/ and https://gsa.tst.glygen.org/ do not appear to be working.

**Comment by rykahsay** [comment]
Ignore GSA on tst, you check when we go to prd

**Comment by Luke-Johnson-5** [comment]
will do
