### ISSUE TITLE
Some DSAPI default queries not working.

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#1135]
/dataset/historylist

payload:
{
  "query": ""
}

response:
{
  "status": 0,
  "error": "field=doctype is required query field"
}

---

/dataset/historydetail
payload:
{
  "bcoid": "GLY_000001"
}
Response:
{
  "status": 0,
  "error": "field=doctype is required query field"
}

**Comment by rykahsay** [comment]
Try now

**Comment by rykahsay** [comment]
<img width="494" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/9ae654d8-e5be-4099-b4e0-6517e67b9de1">

**Comment by Luke-Johnson-5** [comment]
looks good
