### ISSUE TITLE
SPARQL default query not loading on tst.

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#1137]
Waited about 15-20 mins but the SQARQL default query never never loaded on https://sparql.tst.glygen.org/ 

![image](https://github.com/glygener/glygen-issues/assets/144174552/c5be81f7-9f08-402e-be0d-a0ac95b3ac60)

**Comment by rykahsay** [comment]
Ignore sparql on tst, I only deploy it to prd
