### ISSUE TITLE
Misc Frontend Issues

### ISSUE THREAD

**Issue by CyrusAY** [glygener/glygen-issues#1140]
#1119 here lists the remainder of minor issues I spotted during frontend testing:

1.  GlyGen Super Search (not a bug)
Glycans -> Add glycan properties to search: should indicate unit of mass as input (Da or kDa)

2. Quick Search (not a bug)
What are the reported and predicted glycosylated proteins in [species]?
The reported and predicted glycosylation proteins in a species (using fruit fly as an example) do not add up:
Both: 784
Reported: 395
Predicted: 447
I understand that the total number of proteins is larger than the sum of reported and predicted because there are proteins that are "both" reported and predicted, but for the option in the current dropdown menu, linguistically, "Both" means the intersection but not union of the reported and predicted proteins. Using "All" or "Total" in lieu of "Both" might make more sense.

3. Common name of slime mold (not a bug)
Inconsistency: "slime mold" is used in the home stats table but "cellular slime molds" is shown elsewhere
I think this was previously mentioned in a Wednesday meeting but have also forgotten the result of the discussion. lmk

4. Data (https://beta-data.glygen.org/)
Scroll to the bottom you will see three broken images

**Comment by rykahsay** [comment]
Next time, please make one ticket per an issue item (it gets difficult to track things if you put many issues together).


Glycans -> Add glycan properties to search: should indicate unit of mass as input (Da or kDa)
>> addressed on beta, check


Quick Search (not a bug)
>> addressed on beta, check 

Common name of slime mold (not a bug)
>> addressed in beta, check

Data (https://beta-data.glygen.org/)
>> will be fixed when we push to prd tomorrow
