### ISSUE TITLE
Process Files for Pig 

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1146]
path for pig glycosyltransferase dataset: /data/projects/glygen/generated/datasets/compiled/pig_protein_glycosyltransferase1.csv 

path for pig glycohydrolase dataset: /data/projects/glygen/generated/datasets/compiled/pig_protein_glycohydrolase1.csv 

Note: I will create the BCOs for these datasets.

**Comment by rykahsay** [comment]
Can you please assocate "Milestone" to your tickets?

**Comment by rykahsay** [comment]
These files are have been processed:

```
compiled/pig_protein_glycosyltransferase.csv
compiled/pig_protein_glycohydrolase.csv

reviewed/pig_protein_glycohydrolase.csv
reviewed/pig_protein_glycosyltransferase.csv
```

**Comment by rykahsay** [comment]
check beta-data.glygen.org now
