### ISSUE TITLE
OGlcNAc Atlas Pig datasets

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1147]
Just noticed the following files didn't get added to the dataset-masterlist.json.  I have updated the masterlist and created BCOs.  

--> There are only 2 glycosylation sites. Please push this ticket to 2.5 if it's going to delay the 2.4 release.

|BCO ID|Dataset Name|
|-----|-----|
|GLY_000954|pig_protein_xref_oglcnac_atlas.csv|
|GLY_000955|pig_proteoform_glycosylation_sites_oglcnac_atlas.csv|
|GLY_000956|pig_proteoform_citations_glycosylation_sites_oglcnac_atlas.csv|

**Comment by rykahsay** [comment]
I have included them

**Comment by kmartinez834** [comment]
Datasets look good. 

I can not verify the page https://tst.glygen.org/protein/Q8WMH1-1 as it is giving the following error:
![image](https://github.com/glygener/glygen-issues/assets/90285371/5b84a303-4d7b-4175-82ea-c07476bfc6a2)

**Comment by rykahsay** [comment]
check now

**Comment by kmartinez834** [comment]
👍
