### ISSUE TITLE
Glycan_list organism filter options empty

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1148]
https://tst.glygen.org/glycan-list/f3cf76dbbbc57727260a5cab991ba11d

![image](https://github.com/glygener/glygen-issues/assets/90285371/fc290496-b056-414b-b1c3-2e09c9462f1d)

https://api.tst.glygen.org/glycan/list/ is missing organism info:
``` json
 {
        "id": "by_organism",
        "label": "By Organism",
        "order": 2,
        "tooltip": "",
        "options": []
      },
```

**Comment by rykahsay** [comment]
check now

**Comment by kmartinez834** [comment]
Please add HCV to list organism filters as well.

https://tst.glygen.org/glycan-list/f3cf76dbbbc57727260a5cab991ba11d
![image](https://github.com/glygener/glygen-issues/assets/90285371/b152feee-4b17-4c88-8558-c629600e906d)

**Comment by rykahsay** [comment]
Done, check

**Comment by kmartinez834** [comment]
👍
