### ISSUE TITLE
home page pig statistics is different from glycan search results.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1151]
Home page - 7313
glycan list page - 7319
both numbers should be same.

![Screenshot 2024-03-18 at 11 57 48 AM](https://github.com/glygener/glygen-issues/assets/13891482/c8b7adfe-c08d-43bc-ab23-eae39291d87d)

**Comment by rykahsay** [comment]
Fixed

**Comment by sujeetvkulkarni** [comment]
done.
