### ISSUE TITLE
Slime mold name is different in home page (Slime mold) and protein init (Cellular slime molds), glycan init (Cellular slime molds)

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1152]
Protein init vs Home page
![Screenshot 2024-03-18 at 12 09 12 PM](https://github.com/glygener/glygen-issues/assets/13891482/b5c50f08-5f55-4188-b17f-be5fb303b94e)

Glycan init vs Home page
![Screenshot 2024-03-18 at 12 12 26 PM](https://github.com/glygener/glygen-issues/assets/13891482/6dd03b45-3433-4529-94ed-5196c4702b1b)

Same with quick search init api (https://api.tst.glygen.org/usecases/search_init) uses Cellular slime molds.

Home page (https://api.tst.glygen.org/pages/home_init) should also use same name as search pages/init apis.

**Comment by rykahsay** [comment]
Fixed

**Comment by sujeetvkulkarni** [comment]
done.
