### ISSUE TITLE
Protein search is failing with some species option, returns no results.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1153]
Organisms:
Pig, Fruit fly, HCV-H, HCV-Japanese, HCoV-SARS, Mouse, Rat, SARS-CoV-2, Yeast.
All above species in protein search return no results.

API: https://api.tst.glygen.org/protein/search?query={"operation":"AND","query_type":"search_protein","organism":{"id":9823,"name":"Pig"}}

{"list_id": ""}

**Comment by rykahsay** [comment]
fixed

**Comment by sujeetvkulkarni** [comment]
done.
