### ISSUE TITLE
Super search init api not returning record counts properly.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1156]
API: https://api.tst.glygen.org/supersearch/search_init?query={}

![Screenshot 2024-03-18 at 1 43 57 PM](https://github.com/glygener/glygen-issues/assets/13891482/7c57e6d8-0969-471d-a232-2297b7a1db36)

**Comment by rykahsay** [comment]
check now

**Comment by sujeetvkulkarni** [comment]
done.

**Comment by sujeetvkulkarni** [comment]
Issue can be seen again in both beta and test.

**Comment by rykahsay** [comment]
Fixed on both, please check

**Comment by sujeetvkulkarni** [comment]
done.
