### ISSUE TITLE
Missing protein records for ALL SPECIES except Homo sapiens and Dictyostelium discoideum

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1157]
Continued from #1154  

https://tst.glygen.org/protein-list/6587be4a62c9b51692ebacc17eb2a5b9
![image](https://github.com/glygener/glygen-issues/assets/90285371/1f188312-03c1-4544-80a3-dd566fd844e2)

After downloading the results of search for all protein records, the only species present are Homo sapiens and Dictyostelium discoideum.  Tried accessing protein pages for other organisms directly through url, but got same error as #1154

**Comment by rykahsay** [comment]
check now

**Comment by kmartinez834** [comment]
👍 Number of records on tst/beta is correct now
