### ISSUE TITLE
Download script updates

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1158]
I noticed there are several download scripts that contain `&&` at the end of the lines.  Note that if the command before && fails, it will only skip the very next line:

```
wget https://someurl.com/file1.txt &&   #Let's say this command fails

wget https://someurl.com/file2.txt &&  #This line gets skipped

wget https://someurl.com/file3.txt  #This line still gets executed
```

If the first command fails, the program would skip the download of file2.txt, and move on to download file3.txt.  I don't think this is the desired outcome. 

If you want to confirm if a file is downloaded or fails, you could use something like this:
`wget https://someurl.com/file1.txt && echo "file1 download passed" || echo "file1 download failed"`

@JingyueWu @jeet-vora --> Could you take a look at the download scripts you're in charge of and double check the use of &&?

**Comment by JingyueWu** [comment]
Update: Karina will discuss with Jeet and Kate upon Jeet's return.

**Comment by kmartinez834** [comment]
The issue mentioned here caused an error (see #1242 ).  I've updated all of the download scripts.
