### ISSUE TITLE
Organism name should be common name/chosen name in protein list and supersearch list results.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1159]
https://api.tst.glygen.org/supersearch/list?query={"id":"0a02253eb99602ac65f0f8df5d92ea91","offset":1,"sort":"hit_score","limit":20,"order":"desc","filters":[]}
![Screenshot 2024-03-18 at 3 49 41 PM](https://github.com/glygener/glygen-issues/assets/13891482/176591fe-74ea-4bf5-9e1c-8bb2b7dfc559)

https://api.tst.glygen.org/protein/list?query={"id":"b6a8aba0f7e6026e70823875ab5373a9","offset":1,"limit":20,"order":"desc","sort":"hit_score","filters":[]}

![Screenshot 2024-03-18 at 3 54 00 PM](https://github.com/glygener/glygen-issues/assets/13891482/914f6f71-ab68-464d-8302-5c6d5cbc8479)

**Comment by rykahsay** [comment]
fixed

**Comment by sujeetvkulkarni** [comment]
done.
