### ISSUE TITLE
Banner for talk from  Dr. Rebekah L. Gundry

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#116]
Sujeet - for the banner:

Headline: GlyGen Webinar with Dr. Rebekah L. Gundry
Text: Expanding our View of the Cardiac Surfaceome: New Bioinformatic Tools and Technologies for Mapping Glycoproteins and Glycans from Small Sample Sizes
Link: https://wiki.glygen.org/GlyGen_Webinar_Series

You can take date and time from the wiki. Banner can be active right now till the talk.

**Comment by sujeetvkulkarni** [comment]
Done. Please check.
