### ISSUE TITLE
Start testing beta ... both frontend and APIs

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1162]
Start testing beta ... both frontend and APIs

**Comment by JingyueWu** [comment]
@katewarner please test beta: https://beta.glygen.org

The procedure is essentially the same with testing production. Please create tickets and assign Robel if you find any issues.

**Comment by Luke-Johnson-5** [comment]
beta-api looks good as far as I have seen. Will do some site checking as well to make sure.

**Comment by katewarner** [comment]
Finished testing beta and reported any issues I found.
