### ISSUE TITLE
Glycan Simple Search Bug on Production. 

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#1163]
https://api.glygen.org/

/glycan/search_simple/ is producing no list ID for:

 payload
{
  "term_category": "glycan",
  "term": "G17689DH"
}

current output: 
{
  "list_id": ""
}

Causing issue:
![image](https://github.com/glygener/glygen-issues/assets/144174552/5f8cb93f-b20c-4bf2-a5c6-d29cc0589ab7)

The following is also true for payload:
{
  "term_category": "glycan",
  "term": "Hex(5)HexNAc(4)dHex(1)"
}

this returns:
{
  "list_id": ""
}

![image](https://github.com/glygener/glygen-issues/assets/144174552/7c31474e-6096-4d10-882b-bff63a090969)

**both screenshots are from production**

**Comment by rykahsay** [comment]
check this on beta now --- please don't forget to associate "Milestone" to the tickets you make
