### ISSUE TITLE
Glycan structure & substructure search error

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1165]
**Used GlycoCT example...**
Structure search: https://beta.glygen.org/glycan-search/7f6eaa49420342b430466d83837d6a86
Substructure search: https://beta.glygen.org/glycan-search/7f6eaa49420342b430466d83837d6a86

![image](https://github.com/glygener/glygen-issues/assets/90285371/86091dd4-f8c5-4e32-b355-cb6ca015cf7d)

**Comment by rykahsay** [comment]
Try now

**Comment by kmartinez834** [comment]
@katewarner Can you verify this issue is resolved?  Check to make sure the Structure Search and Substructure Search examples work and also try "Draw Glycan" to make sure it's working

https://beta.glygen.org/glycan-search/

**Comment by katewarner** [comment]
The issues are resolved.
