### ISSUE TITLE
Citation files for UnicarbKB glycomics datasets

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#117]
_This is optional for 2.0 because the files are not currently presented on front end_

Create citation files for 

- human_proteoform_glycosylation_sites_unicarbkb_glycomics_study.csv
- rat_proteoform_glycosylation_sites_unicarbkb_glycomics_study.csv

**Comment by kmartinez834** [comment]
Ticket is dependent on https://github.com/glygener/glygen-issues/issues/18

**Comment by rykahsay** [comment]
We need to discuss this --> the citations can only be associated with glycans since these source datasets do not have protein accessions. And if we do that, we are associating citations to glycans based  on proteoform datasets -- which was never done before

**Comment by rykahsay** [comment]
Done --> please check and also make BCOs
human_proteoform_citations_glycosylation_sites_unicarbkb_glycomics_study.csv
rat_proteoform_citations_glycosylation_sites_unicarbkb_glycomics_study.csv

**Comment by kmartinez834** [comment]
👍 Datasets checked

GLY_000732 --> human_proteoform_citations_glycosylation_sites_unicarbkb_glycomics_study.csv
GLY_000733 --> rat_proteoform_glycosylation_sites_unicarbkb_glycomics_study.csv
GLY_000734 --> rat_proteoform_citations_glycosylation_sites_unicarbkb_glycomics_study.csv
