### ISSUE TITLE
Quick search generated protein list id returns species name instead of common name in cache_info.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1171]
1. API: https://beta-api.glygen.org/usecases/species_to_glycosyltransferases/9823
response: 
{"list_id": "d2e0c4cedb4766262086074f1df1d3b6"}

https://beta-api.glygen.org/protein/list?query=
{"id":"d2e0c4cedb4766262086074f1df1d3b6","offset":1,"limit":20,"order":"desc","sort":"hit_score","filters":[]}

```
{
    "cache_info": {
        "query": {
            "organism": {
                "id": 9823,
                "name": "Sus scrofa"
            }
        },
        "ts": "2024-03-22 15:58:05 EDT-0400",
        "record_type": "protein",
        "search_type": "species_to_glycosyltransferases"
    },
```

cache_info->query->organism->name should be Pig in this case.

2. API: https://beta-api.glygen.org/usecases/species_to_glycohydrolases/9823
response:
{"list_id": "d2e0c4cedb4766262086074f1df1d3b6"}

https://beta-api.glygen.org/protein/list?query=
{"id":"d2e0c4cedb4766262086074f1df1d3b6","offset":1,"limit":20,"order":"desc","sort":"hit_score","filters":[]}

```
{
    "cache_info": {
        "query": {
            "organism": {
                "id": 9823,
                "name": "Sus scrofa"
            }
        },
        "ts": "2024-03-22 16:03:04 EDT-0400",
        "record_type": "protein",
        "search_type": "species_to_glycohydrolases"
    },
```

cache_info->query->organism->name should be Pig in this case.

3. API: https://beta-api.glygen.org/usecases/species_to_glycoproteins/9823/both
response:
{"list_id": "0206e2ec43696ebc3d6a6e355d2023b0"}

https://beta-api.glygen.org/protein/list?query=
{"id":"0206e2ec43696ebc3d6a6e355d2023b0","offset":1,"limit":20,"order":"desc","sort":"hit_score","filters":[]}

```
{
    "cache_info": {
        "query": {
            "evidence_type": "both",
            "organism": {
                "id": 9823,
                "name": "Sus scrofa"
            }
        },
        "ts": "2024-03-22 16:05:44 EDT-0400",
        "record_type": "protein",
        "search_type": "species_to_glycoproteins"
    },
```

cache_info->query->organism->name should be Pig in this case.

**Comment by rykahsay** [comment]
Try now

**Comment by sujeetvkulkarni** [comment]
done.
