### ISSUE TITLE
GlyGen API testing tutorial

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#1172]
I have prepared a documentation about API testing for you guys. Please let me know if you have any questions. 

https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/Testing/Testing%20Template/GlyGen%20API%20Testing%20Documentation-2.docx?d=w9a99a60f7c6b4ae08216b1ff17dc3325&csf=1&web=1&e=AcLS89

**Comment by JingyueWu** [comment]
I just realized the image quality is poor in SharePoint document for some reason. Here is the link to the original Google doc that I prepared: https://docs.google.com/document/d/176wNuCC6kdAi5_i4ozBokb6SpqvZ2aqm2AqMfI9y8ik/edit?usp=sharing

**Comment by katewarner** [comment]
Finished the API testing and reported any issues.
