### ISSUE TITLE
Beta API /typeahead/typeahead/ not working

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#1175]
https://beta-api.glygen.org/

/typeahead/typeahead/ current default query:

{
  "query": ""
}

currently returns:
{
  "error_list": [
    {
      "error_code": "exception-error-JPTPQQ"
    }
  ]
}

**Comment by rykahsay** [comment]
The query example was not right, I have fixed it now:

<img width="457" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/c87b1bb0-5972-4b94-b5ba-b60ee7f29809">
