### ISSUE TITLE
Glycan API /glycan/image_svg/{glytoucan_ac}/ error

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1176]
While testing the /glycan/image_svg/{glytoucan_ac}/ API on the tst, beta and prd servers using the "Try it out" function, I get the following Server response:

Invariant Violation: Minified React error #31; visit [http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=%5Bobject%20Blob%5D&args[]=](http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args%5b%5d=%5Bobject%20Blob%5D&args%5b%5d=) for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

I'm not sure whether or not this is a bug.

**Comment by rykahsay** [comment]
/glycan/image_svg/{glytoucan_ac}/  is a URL with a placeholder for GlyTouCan AC. Can you please give the actual glytoucan_ac you used?

**Comment by katewarner** [comment]
I used G17689DH. Would you like me to add this to Milestone 2.5?

**Comment by rykahsay** [comment]
It is the swagger not able to display svg data -- the URL https://api.glygen.org/glycan/image_svg/G17689DH/ gives the svg and we should ignore this for now
