### ISSUE TITLE
Prd Data Download and IDmapping APIs are not working

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1177]
While testing APIs on the prd server I found problems with some of the following Data Download and IDmapping APIs when using the "Try it out" function. This only happened on the prd server, these APIs on the tst and beta servers worked okay.

**/data/detail_download/**
`{
  "error_list": [
    {
      "error_code": "exception-error-GS8ZKE"
    }
  ]
}`

**/data/section_download/**
`{
  "error_list": [
    {
      "error_code": "unexpected-field-in-query",
      "field": "type"
    },
    {
      "error_code": "unexpected-field-in-query",
      "field": "tab"
    },
    {
      "error_code": "missing-parameter",
      "field": "download_type"
    }
  ]
}`

**/typeahead/categorized_typeahead/**
`{
  "error_list": [
    {
      "error_code": "unexpected-field-in-query",
      "field": "query"
    },
    {
      "error_code": "missing-parameter",
      "field": "field"
    },
    {
      "error_code": "missing-parameter",
      "field": "value"
    },
    {
      "error_code": "missing-parameter",
      "field": "total_limit"
    },
    {
      "error_code": "missing-parameter",
      "field": "categorywise_limit"
    }
  ]
}`

**/typeahead/global_typeahead/**
`{
  "error_list": [
    {
      "error_code": "unexpected-field-in-query",
      "field": "query"
    },
    {
      "error_code": "missing-parameter",
      "field": "value"
    },
    {
      "error_code": "missing-parameter",
      "field": "limit"
    }
  ]
}`

**Comment by rykahsay** [comment]
I expect this problem on prd to be gone after we update prd on Monday. Please test this on Monday

**Comment by katewarner** [comment]
It's all working now so I'm closing the issue. Many thanks.
