### ISSUE TITLE
Beta frontend dataset download not working

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1178]
I found a problem with downloading datasets on the beta server (https://beta-data.glygen.org/)

"Download BCO" works fine but "Download dataset" has been running for over 35mins without starting the download. However, "Download dataset" works fine on the prd server.

**Comment by rykahsay** [comment]
Tried to fix it, please check again

**Comment by katewarner** [comment]
It's working so I'll close the issue. Thanks again.
