### ISSUE TITLE
"triples.tar.gz" link on SPARQL homepage does not work

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1179]
On both the tst and prd servers, I found that on the SPARQL homepage the download "triples.tar.gz" link doesn't work. The download says it “Couldn’t download – No file”.

**Comment by rykahsay** [comment]
Thanks! Can you please associate "Milestone" to the tickets? This one should be 2.4.

**Comment by rykahsay** [comment]
It has been fixed on prd -- it is ok if it doesn't work on tst/beta servers.

**Comment by katewarner** [comment]
Okay thanks. I've tested it and it's working so I'm closing the issue.
