### ISSUE TITLE
Broken isoform hyperlinks on frontend due to missing urls in the protein detail api

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1180]
During testing I noticed that the isoform accession hyperlinks in the isoform section of the protein detail page don't work (e.g. “A0A2R8YEI1-1” in the picture below).

![image](https://github.com/glygener/glygen-issues/assets/161866639/da825066-f14a-4b79-8b64-e239be0a23de)

Karina looked into this and found that the urls for these isoforms are missing, and need to be added to the isoform array on the protein details api (e.g. "url":"https://www.uniprot.org/uniprotkb/A0A2R8YEI1/entry") so that the isoform links on the frontend can work

**Comment by rykahsay** [comment]
Looks like the link was disabled purposefully to avoid broken links (during the campaign of cleaning broken links). I have edited misc/xref_info.csv -- please make sure that this link structure will work for all isoforms


<img width="1130" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/73b2d17c-7744-4117-af94-d8b134f0ef23">

**Comment by sujeetvkulkarni** [comment]
@katewarner looks like @rykahsay has addressed this issue on tst server. Can you please verify.
https://tst.glygen.org/protein/P14210-1#Isoforms

**Comment by katewarner** [comment]
@sujeetvkulkarni The UniProtKB links still don't seem to be working, it looks like the HTML doesn't contain a url e.g. `<a target="_blank" rel="noopener noreferrer">A0A2R8YEI1-1</a>`

**Comment by rykahsay** [comment]
Looks like it is working for me
<img width="842" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/6a4b00ad-8a9f-46f9-a3df-aff9290e72e6">

**Comment by katewarner** [comment]
Sorry, double-checked and it is fixed. Thanks again
