### ISSUE TITLE
Change glycan "Common Name" header to "Organism"

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1181]
For 2.4, change "Common Name" to "Organism".  Assigning to @sujeetvkulkarni --> let @rykahsay know if this requires an api change.

![image](https://github.com/glygener/glygen-issues/assets/90285371/bd75da31-42e5-4117-829e-c37c35c148c7)

**Comment by sujeetvkulkarni** [comment]
387a5f0c4ee5e150de8611b343d481df5c3c14bf

Fixed on tst sever.
https://tst.glygen.org/glycan/G17689DH#Organism
https://tst.glygen.org/publication/PubMed/24090084

**Comment by kmartinez834** [comment]
Glycan page looks good.  

@sujeetvkulkarni --> what was updated on the Publication page?

**Comment by sujeetvkulkarni** [comment]
@kmartinez834 same organism section changes like glycann page.

<img width="1600" alt="Screenshot 2024-03-27 at 4 51 53 PM" src="https://github.com/glygener/glygen-issues/assets/13891482/e27986b5-a804-425d-8bf8-d908f305b85b">

**Comment by kmartinez834** [comment]
Got it.

@rykahsay --> Publication page Referenced Proteins section: Organism should use our chosen name instead of species (Rat for example below)

https://tst.glygen.org/publication/PubMed/24090084
![image](https://github.com/glygener/glygen-issues/assets/90285371/720634c7-856c-4bdf-a9c7-b6f0312a676a)

**Comment by rykahsay** [comment]
Fixed on beta

<img width="1261" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/46cbb0f4-0590-4724-9228-aa78d9c32beb">
