### ISSUE TITLE
Missing or incorrect UniCarbKB links on Glycan detail page

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1182]
I noticed that the UniCarbKB badges in the Associated Protein, Cross-references, and Publications sections on the glycan pages, don't have urls to data.glygen.org e.g. https://www.glygen.org/glycan/G17689DH#Associated-Protein
 
The UniCarbKB badges in the Organism section do have links, but Karina noticed that the link is actually wrong (e.g. https://www.glygen.org/glycan/G17689DH#Organism), and that the missing UniCarbKB links in the other sections should match the corrected Organisms link.

**Comment by kmartinez834** [comment]
See #1318 for instructions given to Robel to address this.  Once #1318 is complete, please test above links.

**Comment by kmartinez834** [comment]
#1318 is complete, @rykahsay can you let @katewarner once you've updated the unicarbkb evidence ids?

**Comment by rykahsay** [comment]
Fixed on tst:

<img width="808" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/5d53e716-cdf8-41e4-a05a-675b7298675c">

<img width="532" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/39e0e6a1-b357-443f-b6d9-01a2f178f1ec">

**Comment by katewarner** [comment]
Thank you
