### ISSUE TITLE
2.5 Dataset Plan

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1184]
New Datasets
------
Requires new object in dataset-masterlist.json:
------
- ML-ready (glycomic)
- ML-ready (glycoproteomic)
- human_proteoform_glycosylation_sites_pdc_ccrc.csv (GLY_000961)
- human_proteoform_glyosylation_sites_diabetes_glycomic.csv (GLY_000960)
- human_proteoform_glycosylation_sites_embl.csv (GLY_000888)
- mouse_proteoform_glycosylation_sites_embl.csv (GLY_000889)

Protein Datasets 
------
chicken_protein_allsequences.fasta
chicken_protein_altnames.csv
chicken_protein_binary_interactions.csv
chicken_protein_canonicalsequences.fasta
chicken_protein_citations_uniprotkb.csv
chicken_protein_enzyme_annotation_uniprotkb.csv
chicken_protein_function_uniprotkb.csv
chicken_protein_genelocus.csv
chicken_protein_genenames_refseq.csv
chicken_protein_genenames_uniprotkb.csv
chicken_protein_glycohydrolase.csv
chicken_protein_glycosylation_motifs.csv
chicken_protein_glycosyltransferase.csv
chicken_protein_go_annotation.csv
chicken_protein_info_refseq.csv
chicken_protein_info_uniprotkb.csv
chicken_protein_masterlist.csv
chicken_protein_ncbi_linkouts.csv
chicken_protein_ntdata.nt
chicken_protein_participants_reactome.csv
chicken_protein_participants_rhea.csv
chicken_protein_pathways_reactome.csv
chicken_protein_pro_annotation.csv
chicken_protein_proteinnames_refseq.csv
chicken_protein_ptm_annotation_uniprotkb.csv
chicken_protein_reactions_reactome.csv
chicken_protein_reactions_rhea.csv
chicken_protein_recnames.csv
chicken_protein_sequenceinfo.csv
chicken_protein_signalp_annotation.csv
chicken_protein_signalp_cleavedsequences.fasta
chicken_protein_signalp_fullsequences.fasta
chicken_protein_signalp_peptidesequences.fasta
chicken_protein_site_annotation_uniprotkb.csv
chicken_protein_submittednames.csv
chicken_protein_transcriptlocus.csv
chicken_protein_xref_bgee.csv
chicken_protein_xref_brenda.csv
chicken_protein_xref_cazy.csv
chicken_protein_xref_cdd.csv
chicken_protein_xref_chembl.csv
chicken_protein_xref_geneid.csv
chicken_protein_xref_glyconnect.csv
chicken_protein_xref_intact.csv
chicken_protein_xref_kegg.csv
chicken_protein_xref_oglcnac_atlas.csv
chicken_protein_xref_oglcnac_db.csv
chicken_protein_xref_oma.csv
chicken_protein_xref_orthodb.csv
chicken_protein_xref_panther.csv
chicken_protein_xref_pfam.csv
chicken_protein_xref_pro.csv
chicken_protein_xref_refseq.csv
chicken_protein_xref_rhea.csv
chicken_protein_xref_uniprotkb.csv
human_protein_disease_alliance_genome.csv

Proteoform Datasets 
------
chicken_proteoform_glycation_sites_uniprotkb.csv
chicken_proteoform_glycosylation_sites_glyconnect.csv
chicken_proteoform_glycosylation_sites_gptwiki.csv
~~chicken_proteoform_glycosylation_sites_harvard.csv~~ (human only)
chicken_proteoform_glycosylation_sites_literature.csv
chicken_proteoform_glycosylation_sites_literature_mining.csv
chicken_proteoform_glycosylation_sites_literature_mining_manually_verified.csv
chicken_proteoform_glycosylation_sites_oglcnac_atlas.csv (source: unambiguous_sites_version_2.0.csv)
chicken_proteoform_glycosylation_sites_oglcnac_mcw.csv
chicken_proteoform_glycosylation_sites_o_gluc.csv
chicken_proteoform_glycosylation_sites_pdb.csv
chicken_proteoform_glycosylation_sites_tyr_o_linked.csv
chicken_proteoform_glycosylation_sites_unicarbkb.csv
chicken_proteoform_glycosylation_sites_unicarbkb_glycomics_study.csv
chicken_proteoform_glycosylation_sites_uniprotkb.csv
chicken_proteoform_phosphorylation_sites_iptmnet.csv
chicken_proteoform_phosphorylation_sites_uniprotkb.csv

Changing Datasets
------
**Processing changes:**
- protein_homolog_clusters.csv
- *_protein_matrixdb.csv (#1144)
- *_proteoform_glycosylation_sites_oglcnac_atlas.csv

**Possible volume changes:**
- \*proteoform_glycosylation_sites*.csv
- \*proteoform_phosphorylation_sites*.csv
- \*glycan*.csv

**Comment by ubhuiyan** [comment]
I checked all the proteoform CSVs and there was only one dataset that had chicken documented.

**Comment by kmartinez834** [comment]
@ubhuiyan can you add the new proteoform datasets that will result from the new species added to download scripts (glyconnect, oma, mcw)?

**Comment by kmartinez834** [comment]
@katewarner could you update the list of protein files in the code block above?  I updated the script because there are a few files missing here.  The instructions and a training video are here: [New datasets](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/Backend%20Workflow.docx?d=w54fd6f54e20f443ea74ff1c4aca4e6a8&csf=1&web=1&e=32Gd98&nav=eyJoIjoiMjA0MjYwMDMyOCJ9)

**Comment by ubhuiyan** [comment]
@kmartinez834 I have added the proteoform datasets. Let me know if I missed any!

**Comment by katewarner** [comment]
@kmartinez834 I've checked and added the protein datasets.

**Comment by kmartinez834** [comment]
Karina to add csv file from #1217 to documentation
