### ISSUE TITLE
Change "Cellular slime molds" to "Cellular slime mold"

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1189]

**Comment by ReneRanzinger** [comment]
* Protein details, homologs section and site details page 
   * Robel to add “reference_species” to api, example: 
```
Organism: Human 
Reference species: Homo sapiens [9606] 
```
* Comon name issue 
   * change “Common name” to “Organism” 
   * add “common_name” to api, separate object for “organism” (glygen given name)

**Comment by rykahsay** [comment]
Instead of "Organism", I am using "glygen_name". Given below is what we have now.

Species section in protein objects
```
{
            "taxid": 9606,
            "name": "Homo sapiens",
            "common_name": "Human",
            "glygen_name": "Human",
            "reference_species": "Homo sapiens [9606]",
            "evidence": [
                {
                    "database": "UniProtKB",
                    "id": "P14210",
                    "url": "https://www.uniprot.org/uniprot/P14210"
                }
            ]
        }
```

Species section in glycan objects
```
 {
            "taxid": 9606,
            "name": "Homo sapiens",
            "common_name": "Human",
            "glygen_name": "Human",
            "reference_species": "Homo sapiens [9606]",
            "annotation_category": "direct",
            "evidence": [
                {
                    "database": "GlyConnect",
                    "id": "1062",
                    "url": "https://glyconnect.expasy.org/browser/structures/1062"
                },
                {
                    "database": "GlyCosmos",
                    "id": "G59655SA",
                    "url": "https://glycosmos.org/glycans/show/G59655SA"
                },
                {
                    "database": "PubMed",
                    "id": "33167210",
                    "url": "https://glygen.org/publication/PubMed/33167210"
                },
                {
                    "database": "PubMed",
                    "id": "33383989",
                    "url": "https://glygen.org/publication/PubMed/33383989"
                },
                {
                    "database": "PubMed",
                    "id": "8130392",
                    "url": "https://glygen.org/publication/PubMed/8130392"
                },
                {
                    "database": "GlyGen",
                    "id": "GLY_000341",
                    "url": "https://data.glygen.org/GLY_000341"
                }
            ]
        },
```

**Comment by kmartinez834** [comment]
- In _Show More..._ dropdown, change "Organism" to "Common Name" and populate with "common_name" from API
https://tst.glygen.org/glycan/G85292WS#Organism
![image](https://github.com/glygener/glygen-issues/assets/90285371/d46aa9df-ece3-4f41-9d99-fb0a72e06186)


- Continued from #1200 , include both Reference Species and Organism in Protein details (species and homologs section) and site details pages
https://tst.glygen.org/protein/P05556-1
**Organism:** Mouse
**Reference Species:** Homo sapiens [9606]

**Comment by sujeetvkulkarni** [comment]
@kmartinez834 @rykahsay 
1. If we put Reference Species: Homo sapiens [9606] directly from  "reference_species": "Homo sapiens [9606]", cant add link to 9606. So have used "name [taxid]" from json on protein details page. Same for Siteview page.

2. On glycan details top table Organism value comes from glygen_name. Also Organism value on Protein details comes from 
glygen_name. Same for Siteview page.

For "Chinese hamsters" there is no "glygen_name" value.
@rykahsay needs to add glygen_name value for "Chinese hamsters".

https://tst.glygen.org/glycan/G17689DH#Organism

![Screenshot 2024-05-23 at 3 11 04 PM](https://github.com/glygener/glygen-issues/assets/13891482/4804b43c-a918-43f6-9ac7-be2f42bdfa02)

3. On protein details Homologs section:
Organism value should come from glygen_name in json.
Reference Species comes from reference_species in json.

But currently there is no glygen_name and reference_species in orthologs:[] section.
@rykahsay needs to add glygen_name and reference_species in orthologs:[] section.

https://tst.glygen.org/protein/P05556-1#Homologs

![Screenshot 2024-05-23 at 3 19 55 PM](https://github.com/glygener/glygen-issues/assets/13891482/a75de628-f179-440d-9b97-f22d1a2dcdcd)


Please let me know if I need to change anything.

**Comment by kmartinez834** [comment]
@rykahsay please add "glygen_name" to "orthologs" section of protein api:

Ex. https://api.tst.glygen.org/protein/detail/P61255-1
should look like this....
``` json
"orthologs": [
    {
      "uniprot_canonical_ac": "P53221-1",
      "protein_name": "Large ribosomal subunit protein uL24B",
      "gene_name": "RPL26B",
      "tax_id": 559292,
      "organism": "Saccharomyces cerevisiae S288C",
      "sequence": {
        "sequence": "MAKQSLDVSSDRRKARKAYFTAPSSERRVLLSAPLSKELRAQYGIKALPIRRDDEVLVVRGSKKGQEGKISSVYRLKFAVQVDKVTKEKVNGASVPINLHPSKLVITKLHLDKDRKALIQRKGGKLE",
        "length": 127
      },
      "evidence": [
        {
          "id": "P61255",
          "url": "https://omabrowser.org/oma/group/P61255/",
          "database": "OMA"
        }
      ],
      "common_name": "Baker's yeast",
      "glygen_name": "Yeast",
    },
```

**Comment by rykahsay** [comment]
done ..
<img width="569" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/a8ed7b9f-6c42-4e5a-a891-a87b1fef27eb">

**Comment by kmartinez834** [comment]
@sujeetvkulkarni populate Organism with "glygen_name"

https://tst.glygen.org/protein/P61255-1#Homologs
![image](https://github.com/glygener/glygen-issues/assets/90285371/74a07802-e59d-4864-9f53-9bee3b7fbe8f)

**Comment by sujeetvkulkarni** [comment]
@kmartinez834 
Change is already there on production and tst server.
https://www.glygen.org/protein/P61255-1#Homologs

But on tst server api is not updated.
![Screenshot 2024-06-04 at 3 50 26 PM](https://github.com/glygener/glygen-issues/assets/13891482/d24edd96-2ecc-4ce8-a5ae-0ab6b57787f0)
