### ISSUE TITLE
Reprocess glycan_citations_motif.csv

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#119]
Reprocess glycan_citations_motif.csv:

1. Split PMIDs in src_file `unreviewed/glycan_motif.csv` that are separated by ";"
```
"pmid"
"7287743; 19756298"
"2410529; 19756298"
"1567687; 6653876; 19756298"
```
3. Add these PMIDs to glycan_citations_motif.csv

**Comment by kmartinez834** [comment]
Carried over from https://github.com/glygener/glygen-issues/issues/84

**Comment by rykahsay** [comment]
I am already doing that --> I don't see a problem in unreviewed/glycan_citations_motif.csv

**Comment by kmartinez834** [comment]
My mistake, I checked again and all PMIDs are present in glycan_citations_motif.csv
