### ISSUE TITLE
Test prd server (glygen.org and api.glygen.org)

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1190]
2.4 has been pushed to prd, please test the following:

- glygen.org
- api.glygen.org

**Comment by Luke-Johnson-5** [comment]
API looks good.

**Comment by Luke-Johnson-5** [comment]
@rykahsay 
API:
These following API's return no results with current default queries

/log/access/

returns:
{
  "logs": []
}

/log/grouped/

returns:
{
  "logs": []
}

/log/init/ 

returns:
{
  "pages": [],
  "types": [],
  "users": []
}

**Comment by Luke-Johnson-5** [comment]
@rykahsay @sujeetvkulkarni 
**Not sure if this is a backend problem. I am pretty sure it is a front end problem**
Hyperlinks at the bottom of data.glygen.org not working. This being: License, Privacy Policy, Disclaimer, and Contact Us found at the bottom of the page.

In addition there appears to be a broken image. 


![image](https://github.com/glygener/glygen-issues/assets/144174552/20898c78-5cee-429c-abb8-2447922e209f)

**Comment by Luke-Johnson-5** [comment]
@sujeetvkulkarni @rykahsay 
Contact us hyperlink on https://data.glygen.org/static/about redirects to https://data.glygen.org/tst/contactus which never loads

**Comment by katewarner** [comment]
Noticed some minor issues with glygen.org (below). Didn't find any problems with api-glygen.org.

Glycan image is not available for:  https://www.glygen.org/glycan/G02161CI

Noticed a spelling mistake (in bold) on the help Wiki page:
https://wiki.glygen.org/Frequently_Asked_Questions?
•	4.13 Which UniProtKB and GlyTouCan accessions are **inclded** in GlyGen?
•	Correction: 4.13 Which UniProtKB and GlyTouCan accessions are included in GlyGen?

**Comment by sujeetvkulkarni** [comment]
@katewarner Glycan image response from api https://api.glygen.org/glycan/image/G02161CI
is image not available, so it is showing that way.

**Comment by sujeetvkulkarni** [comment]
@rykahsay I have logged #1199 and #1198 issues.
I have fixed #1199 - frontend related issue on tst server. This would need 2.4 frontend redeployment on beta and prod.
#1198 is a backend issue.

My prod testing is done.

**Comment by ReneRanzinger** [comment]
Done

**Comment by katewarner** [comment]
> @katewarner Glycan image response from api https://api.glygen.org/glycan/image/G02161CI is image not available, so it is showing that way.

@sujeetvkulkarni where are the images pulled in from? The image is in GlyTouCan (https://glytoucan.org/Structures/Glycans/G02161CI) and GlyCosmos.

**Comment by kmartinez834** [comment]
@katewarner the images are provided by @edwardsnj 

Nathan --> Will there be an image for G02161CI in the next export?  I see https://glymage.glyomics.org/ is currently able to generate an image based on the WURCS string you provided for 2.4 release.

**Comment by edwardsnj** [comment]
Images are copied from glymage when I create the release. Not sure why its missing in this case, I expect it to appear in the next release - I'll check when the time comes...
