### ISSUE TITLE
2.5 | Master List for Data Download 

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1193]
| Resource | Downloaded by |Completed (Y/N)| Notes | Issue | 
| -------- | ------- | ------- | ------- |------- |
| Cellosaurus |Karina | Y| | |
| ChEBI| Cyrus| Y| | |
| MatrixDB |Cyrus | Y| | |
| Reactome | Cyrus | Y |  | |
| Glyconnect | Urnisha  |Y |Processing change required + New species added |
| IPTMnet| Urnisha|  Y| | |
| MCW O-GlcNAc  | Urnisha |Y  | New species added | |
| OMA | Urnisha |  Y| Processing change required + New species added | |
| O-GlcNAcAtlas| Urnisha | Y |Processing change required | |
|Genomics England | Kate |  Y|  | |
|Genome Alliance | Kate |  Y|  | |
|MGI | Kate | Y |  | |
|Mondo | Kate |  Y|  | |
|EBI | Kate |  Y|  | |
|NCBI RefSeq | Kate |  Y|  | |
|Disease Ontology | Kate |  Y|  | |
|Glycosyltransferase (Chicken) | Urnisha/Kate |Y  |  | |
|Glycohydrolase (Chicken) | Urnisha/Kate | Y |  | |

[Proteoform Data Download Doc](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7BE6511E4F-F88A-452F-AB40-DAE665A5E949%7D&file=Data%20Download%20-%20Proteoform.docx&action=default&mobileredirect=true)

[Protein Data Download Doc](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B6538B699-3847-482F-AC79-174A1CBE6E1F%7D&file=Data%20Download%20-%20Protein.docx&action=default&mobileredirect=true)

**Comment by kmartinez834** [comment]
Perform download check once you've downloaded files you are responsible for.  
Instructions here: [Downloads check](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/Backend%20Workflow.docx?d=w54fd6f54e20f443ea74ff1c4aca4e6a8&csf=1&web=1&e=9Zg0y4&nav=eyJoIjoiMTA4MzE5NzUxOSJ9)

**Comment by rykahsay** [comment]
@ubhuiyan @katewarner ... when should I expect these files:

compiled/chicken_protein_glycohydrolase.csv
compiled/chicken_protein_glycosyltransferase.csv

**Comment by katewarner** [comment]
@rykahsay 

I've added the files to the compiled folder: 
compiled/chicken_protein_glycohydrolase.csv
compiled/chicken_protein_glycosyltransferase.csv

**Comment by rykahsay** [comment]
@ubhuiyan  ... I think you need to close this ticket now
