### ISSUE TITLE
Backend should always persist current outreach data, home page video data when updating version, for eg from 2.4 to 2.5 etc.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1195]
https://api.glygen.org/pages/home_init
```
video: {
  "url": "https://www.youtube.com/embed/xyV5v5nRm6A?rel=0",
  "createdts": "2024-02-26 08:39:18",
  "visibility": "visible"
}
```

https://api.glygen.org/outreach/list/

There maybe other such cases, where data which gets modified in a version, needs to be persisted across versions.
Video url in home page, outreach data are primary such examples.
There needs to be a mechanism which capture such data from existing version and then copies it over to next version before deleting it. Or maybe this type of data needs a permanent database which does not get cleaned up across version update.

**Comment by rykahsay** [comment]
We are going back to having MongoDB on host

**Comment by sujeetvkulkarni** [comment]
done.
