### ISSUE TITLE
Glycan search for Glycosylated Protein (O-GlcNAc error)

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1196]
@katewarner found that Q9QYX7-1 is glycosylated by G49108TO but giving an error.  Appears to be a bug with all proteins glycosylated with G49108TO (O-GlcNAc).  I also tried P31749-1, P37370-1

https://glygen.org/glycan-search/
![image](https://github.com/glygener/glygen-issues/assets/90285371/572f925f-65a5-40ce-a1e1-a93e19cca5ee)
![image](https://github.com/glygener/glygen-issues/assets/90285371/3cb84147-9386-4d9b-ba35-6af1ed3a8106)

**Comment by rykahsay** [comment]
Try now
