### ISSUE TITLE
motif details download for options - image, glycan list, motif data is failing. 

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1199]
This is a front end issue but once this one is fixed, backend needs to fix - #1198 for downloading motif image.

@ReneRanzinger Do you want me to quickly fix in this in 2.4?

**Comment by ReneRanzinger** [comment]
2.4

**Comment by sujeetvkulkarni** [comment]
54a2091b299ab95df212fb812c6a07271be8c8cf
Fixed on tst.

**Comment by sujeetvkulkarni** [comment]
Redeploy 2.4 front end on prod and beta.

**Comment by rykahsay** [comment]
Done, please check

**Comment by sujeetvkulkarni** [comment]
done - verified on both prod and beta.
