### ISSUE TITLE
Add "reference_species" and "organism" to APIs

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1200]
**Add `reference_species` and `organism` to Protein details (species and homologs section) and site details APIs.**

- `reference_species` refers to the scientific name and tax id
- `organism` is the GlyGen chosen name
- `common_name` is the UniProt common name

See [mockup ](https://gwu0.sharepoint.com/:p:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Mockups/2.4/%5BGlycan_organism_display_1007.pptx%5D(https://gwu0.sharepoint.com/:p:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Mockups/2.4/Glycan_organism_display_1007.pptx?d=wc445a13be8d341e1a2d2d0959aa1847b&csf=1&web=1&e=3XfbQ2)?d=wc445a13be8d341e1a2d2d0959aa1847b&csf=1&web=1&e=3XfbQ2)for all common names

Ex. https://api.glygen.org/protein/detail/P14328/
``` json 

"species": [
    {
      "name": "Dictyostelium discoideum",
      "taxid": 44689,
      "evidence": [
        {
          "database": "UniProtKB",
          "id": "P14328",
          "url": "https://www.uniprot.org/uniprot/P14328"
        }
      ],
      "common_name": "Social amoeba",
      "reference_species": "Dictyostelium discoideum [44689]",
      "organism": "Cellular slime mold",
    }
  ],
```

**Add `organism `only to Glycan details (species)** 

Ex. https://api.glygen.org/glycan/detail/G85292WS
``` json

"species": [
    {
      "taxid": 44689,
      "name": "Dictyostelium discoideum",
      "annotation_category": "direct",
      "evidence": [
        {
          "database": "GlyCosmos",
          "id": "G85292WS",
          "url": "https://glycosmos.org/glycans/show/G85292WS"
        }
      ],
      "common_name": "Social amoeba",
      "organism": "Cellular slime mold"
    }
  ],
```

**Comment by rykahsay** [comment]
See ticket #1189

**Comment by kmartinez834** [comment]
Issue continued in #1189, closing this ticket
