### ISSUE TITLE
Update permissions for downloads/atlas_glcnac/ folder 

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1202]
We need to update the permissions to the atlas_glcnac folder to allow everyone on the GW GlyGen team access (drwxrwsr-x). This is so I can download the proteoform data.

**Comment by rykahsay** [comment]
done
```
$ ls -ltr downloads/ | grep atlas_oglcnac
drwxrwsr-x.  3 jeetvora       glygen     5 Oct 21  2022 atlas_oglcnac
```
