### ISSUE TITLE
Logo download from website not working

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1203]
I tried to download the GlyGen logo from the website (https://github.com/glygener/glygen-frontend/tree/master/src/GlyGen-logos) and it returned error "404-page not found".

**Comment by sujeetvkulkarni** [comment]
d99addab392160d8efbb7713575cc328dadbfd3e

**Comment by sujeetvkulkarni** [comment]
@katewarner Fixed on test server. please verify now.

**Comment by katewarner** [comment]
It works! Thank you
