### ISSUE TITLE
AWS data.glygen not working.

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#1207]
@rykahsay 

AWS server is up and running however, I am having some difficulty getting the aws.data.glygen.org up and running. I have https://aws.dsapi.glygen.org/ working but the data page itself is not working. I am not sure what I need to do to fix this.

I attached the 2.5 Milestone to this because I would like to have this finished and the AWS finished by at least the next release.

**Comment by Luke-Johnson-5** [comment]
@rykahsay 

Looked into this further and the APP/API containers are running and the dataset API seems to working and is returning results when using the test commands. I have looked into the *.conf files and these are also mapped to the correct ports so I am not sure what the problem is should I make a ticket to RTS support and CC you? 

Test queries used were:
![image](https://github.com/glygener/glygen-issues/assets/144174552/d0afe7af-1771-4765-bce9-78bccfd00e49)

**Comment by rykahsay** [comment]
@Luke-Johnson-5  --- I will take care of these tasks for now
