### ISSUE TITLE
Process protein datasets for 2.5

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1208]
Please process the downloaded protein datasets for 2.5. The EBI dataset includes the new organism Chicken.

/data/projects/glygen/downloads/genomics_england/current
/data/projects/glygen/downloads/alliance_genome/current
/data/projects/glygen/downloads/mgi/current
/data/projects/glygen/downloads/mondo/current
/data/projects/glygen/downloads/ebi/current
/data/projects/glygen/downloads/ncbi/refseq/current
/data/projects/glygen/downloads/do/current

**Comment by rykahsay** [comment]
Done, check
