### ISSUE TITLE
Setting up GlyGen main API and frontend modules on AWS server

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#121]
So far, you have successfully installed

- https://aws.data.glygen.org (data module)
- https://aws.dsapi.glygen.org/ (DSAPI or API for data module)

Next step is to set up the following modules 
- https://aws.api.glygen.org/  (GlyGen main API module or API module for the main GlyGen frontend, following instructions on https://github.com/glygener/glygen-backend-api/tree/2.0)
- https://aws.glygen.org/  (GlyGen frontend module or main GlyGen frontend, following instructions on https://github.com/glygener/glygen-frontend/tree/master)

**Comment by tiwa1154** [comment]
@rykahsay I am setting up the main API. Ran into an issue in Step 3 [https://github.com/glygener/glygen-backend-api/tree/2.0#step-3-initialize-and-populate-your-mongodb-database]. 

I ran `python3 populate_all_collections.py -s prd -v 2.0.3 -m full` and received error message "Usage: 
populate_all_collections.py  [options]

populate_all_collections.py: error: no such option: -m"

**Comment by tiwa1154** [comment]
@rykahsay For the frontend module, I followed https://github.com/glygener/glygen-frontend/blob/master/server-installation.md but the docker-glygen-frontend.service file is missing in the repo.

**Comment by tiwa1154** [comment]
@rykahsay I ran `python3 populate_collections.py -s $DEP -v $VER` but got error in the screenshot below:
![Screen Shot 2023-04-24 at 13 14 24](https://user-images.githubusercontent.com/90009613/234069180-4888de55-f5b7-4292-9daa-9be58c3fa7b0.png)

**Comment by tiwa1154** [comment]
@rykahsay For the frontend module, which branch are we using? Master or ver_2.0?

**Comment by rykahsay** [comment]
Yes, use 2.0 branch. 

For the logs, create the logs dir:
```
mkdir logs
```

**Comment by tiwa1154** [comment]
@rykahsay 
For the main API:
1. created the container running_glygen_api_prd but can't start the container with `sudo systemctl start docker-glygen-api-prd.service`. See screenshot: ![Screen Shot 2023-04-25 at 15 07 38](https://user-images.githubusercontent.com/90009613/234378758-cad193b5-48f2-4dee-8e8a-20beb074ce53.png)

For Frontend:
1. ran `sudo make -f MakeFile prod` and received some errors: 
![Screen Shot 2023-04-25 at 15 14 20](https://user-images.githubusercontent.com/90009613/234379579-bcaafb7d-fa11-4397-a79b-0f4f2ab9000a.png)

**Comment by tiwa1154** [comment]
Also, for the API, I ran `python3 update-search-init.py -s tst`, received Failed to establish a new connection, see screenshot:
![Screen Shot 2023-04-25 at 15 20 48](https://user-images.githubusercontent.com/90009613/234380882-5e2b48c6-89b4-43dc-af6c-06a375599576.png)

**Comment by rykahsay** [comment]
We need to look into these issues on webex -- please set up a meeting on Friday after the group meeting.

**Comment by tiwa1154** [comment]
@rykahsay Sent an email invitation for Friday's meeting.

**Comment by tiwa1154** [comment]
Successfully created the frontend on the server
![Screen Shot 2023-05-17 at 13 09 34](https://github.com/glygener/glygen-issues/assets/90009613/c811e978-4bc0-4021-9504-6bd845d55571)

@rykahsay Tried to map it to a public domain of aws.glygen.org in the /etc/httpd/conf.d/awsdata.conf. However, it seems to be not connected correctly and aws.glygen.org still shows not found.

**Comment by tiwa1154** [comment]
@rykahsay For the main API implementation, also ran into issues with populating the mongodb database. See screenshot:
![Screen Shot 2023-05-17 at 15 39 14](https://github.com/glygener/glygen-issues/assets/90009613/a8753a5c-8663-4c25-93ba-506bb7298508)
showing FileNotFoundError

**Comment by tiwa1154** [comment]
@rykahsay 

For dataset-api, had an issue with populating mongodb database: python3 load_current_release.py -s prd -v 2.0.3 -m full:
![Screen Shot 2023-05-17 at 13 49 29](https://github.com/glygener/glygen-issues/assets/90009613/d0f0446b-3fcd-44f0-8352-a84a65b392e2)

**Connection refused.**

**Comment by rykahsay** [comment]
> For the logs, create the logs dir:
> 
> ```
> mkdir logs
> ```

**Comment by rykahsay** [comment]
For the second last comment you made, I have already gave you a solution --> scroll up and find it.

For the last comment, it is working now:
<img width="1407" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/59724a7c-d67d-4776-9f77-7f53e52e6f68">

**Comment by tiwa1154** [comment]
Running the last step of API testing, ran s`udo python3 run_api_test.py -m 1 -g protein -s prd`, received error:
![Screen Shot 2023-05-24 at 11 58 43](https://github.com/glygener/glygen-issues/assets/90009613/52cdd243-118f-47db-b617-007760e5b105)
Also, you mentioned modifying config.json, not sure what exactly I should modify. @rykahsay

**Comment by tiwa1154** [comment]
@rykahsay 
1. I have finished setting up Main GlyGen API: [aws.api.glygen.org/](url) and the frontend container is running on the server but seems like [/aws.glygen.org/](url) is not created by Dacian yet.
2. I tried to reset the dataset API and APP but when I go to [aws.data.glygen.org/](url) and [aws.dsapi.glygen.org](http://aws.dsapi.glygen.org/), see error in the screenshot:
![Screen Shot 2023-06-13 at 14 19 58](https://github.com/glygener/glygen-issues/assets/90009613/142f542e-4cfc-42e8-a9cb-355e87dd9413).
I assume it's because I changed the file path in the conf file to /efc/shared instead of the original path of /data/shared/ because when I run `sudo python3 create_api_container.py -s prd`, some steps are shown as CACHED and making directory in the /date/shared path
![Screen Shot 2023-06-13 at 14 39 30](https://github.com/glygener/glygen-issues/assets/90009613/7f302d46-6171-4d84-8567-efaa9033b31a)

**Comment by tiwa1154** [comment]
@rykahsay 
I am downloading the new data release. 2 issues so far:

1. No permission to access initdb.tar.gz
<img width="549" alt="Screen Shot 2023-06-21 at 14 20 09" src="https://github.com/glygener/glygen-issues/assets/90009613/58485a88-dc91-4030-8dc1-237fce6b09c7">
2. For the files that's successfully downloaded, 'recordsdb' has a different permission restriction
<img width="435" alt="Screen Shot 2023-06-21 at 14 20 50" src="https://github.com/glygener/glygen-issues/assets/90009613/5142f29c-a05e-41a2-bf8d-667e0251814a">

**Comment by tiwa1154** [comment]
@rykahsay 

1.  Downloaded 2.1.1, tried to create and start docker container for the APP. Seems still not working on https://aws.data.glygen.org/. Shown as a blank page. 
2. When I populated the MongoDB, using `python3 load_cur
rent_release.py -s {DEP} -v {VER}`, encountered an error, see screenshot:
![Screen Shot 2023-06-22 at 12 31 58](https://github.com/glygener/glygen-issues/assets/90009613/350fd1d7-042e-4dae-a304-c93d80baad5e)

**Comment by rykahsay** [comment]
It should work now, but before you get to do that, you had to load the data. I have started the loading using the command given below. 
```
python3 load_current_release.py  -s prd -v 2.1.1
```

It is loading to the last container (c_records) which takes some time.

<img width="1255" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/81d896d2-be19-4804-bbad-9fea877847d1">

**Comment by tiwa1154** [comment]
Thanks, @rykahsay 

So I created and started the docker container for the APP but the https://aws.data.glygen.org/ is shown as a blank page. How should I troubleshoot?

**Comment by rykahsay** [comment]
I have fixed the problem --> there needs to be additional customization of the app/conf/config.json file as shown below:

<img width="1164" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/7af8e732-cc1b-47c4-a458-50fc5e605b8f">

**Comment by rykahsay** [comment]
<img width="1377" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/5295d932-cd8b-4d6e-a0bd-d2f40a28447b">

**Comment by tiwa1154** [comment]
aws.glygen.org domain has been created but the certificate is invalid. Should I send an email to Dacian or @rykahsay you will handle it?

**Comment by tiwa1154** [comment]
![Screen Shot 2023-07-03 at 11 53 30](https://github.com/glygener/glygen-issues/assets/90009613/e3e616c4-8d21-48d4-bc49-e74df3dc0148)
