### ISSUE TITLE
FAES meeting registration wiki and tweet

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1214]
Create a wiki page for the FAES meeting/workshop you can get some information from [their webpage](https://education.faes.org/search/publicCourseSearchDetails.do?method=load&courseId=2529149). 

We also need a [tweet text](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B1A02CAE5-B282-49F0-A56A-9B0179EABFDB%7D&file=Tweet%20of%20the%20week.docx&action=default&mobileredirect=true) for @ReneRanzinger. 

And information for @sujeetvkulkarni to make a banner on GlyGen.

**Comment by JingyueWu** [comment]
@ReneRanzinger When do you need this to be done from me?

**Comment by ReneRanzinger** [comment]
Make this highest priority right after any data release related tasks.

**Comment by JingyueWu** [comment]
@ReneRanzinger 

Finished, please take a look and let me know what you think:

https://wiki.glygen.org/GlyGen_and_Foundation_for_Advanced_Education_in_the_Sciences_(FAES)_2024_Workshop#Registration

For tweet content, how about: 

"Academic Programs at the NIH (FAES) and the GlyGen team is pleased to offer a one day, in-person, workshop at the National Institutes of Health, Bethesda campus on June 10, 2024. Sign up now: https://wiki.glygen.org/GlyGen_and_Foundation_for_Advanced_Education_in_the_Sciences_(FAES)_2024_Workshop#Registration"

**Comment by ReneRanzinger** [comment]
@rajamazumder Jingyue made the wiki page and we tweeted about it.
