### ISSUE TITLE
Update biomarker details for new datamodel

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1219]
After the changes of the datamodel (#1218) we need to update the biomarker details page to work with the updated model.

**Dependencies:**
* #1218

**Comment by sujeetvkulkarni** [comment]
d04560972575efff3cec325422f7b4374f098aef

**Comment by sujeetvkulkarni** [comment]
1d9671ce51cc23b65acdb7a2b23fcaddd471882e
