### ISSUE TITLE
Pictures for About us page

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#122]
Hi Jeet,

Can you please share pictures of Evan Bolton and Paul Thiessen for about us page.

**Comment by jeet-vora** [comment]
Paul Thiessen (https://www.linkedin.com/in/thiessenpaul/)

![image](https://user-images.githubusercontent.com/25825266/226470967-bb61996d-f4c1-4ebc-8ca3-262864c9477d.png)

Evan Bolton (https://www.linkedin.com/in/pubchem/)
![image](https://user-images.githubusercontent.com/25825266/226471033-6ed96e19-e7eb-4d49-8a50-bbdd2f965df3.png)

**Comment by sujeetvkulkarni** [comment]
5a4c73baa9d0f7e7302a42813ce6791df657a282

**Comment by sujeetvkulkarni** [comment]
About us page - consultant - Collaborator

**Comment by sujeetvkulkarni** [comment]
2c700f232900455cf159154d278466e8c4f2a549

**Comment by sujeetvkulkarni** [comment]
e6860af85148f831b252b672fa51c39a16ec4cc8
