### ISSUE TITLE
Implement biomarker search page

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1223]
Based on the init and search API in #1221 implement the biomarker search page. It will be added as menu entry in explore (after Protein search) and as card on the frontpage (after protein search, also move quick search before blast).

**Dependencies:**
* #1222 
* #1221 
* #1218

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood As per #1221 in the Advanced search field name is Disease or Biomarker Disease. But in the same ticket #1221 field in Simple search is named Condition. Also as per #1224 table column is named Condition. So should we use same name in all places and change Disease/Biomarker Disease field in Advanced search to Condition?

**Comment by sujeetvkulkarni** [comment]
Created a separate ticket for above issue - https://github.com/glygener/glygen-issues/issues/1268

**Comment by sujeetvkulkarni** [comment]
611480d2de8822f239a7e2be8a0ee6178c1e593d
