### ISSUE TITLE
Download API update for biomarker changes

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1225]
The download API needs to support 
* the new biomarker datamodel
* biomarker search result

**Dependencies:**
* #1224
* #1221 
* #1218

**Blocker for:**
* #1226

**Comment by sujeetvkulkarni** [comment]
related to list api download- #1264

**Comment by rykahsay** [comment]
Done, request query examples are given below

#### biomarker detail
```
{
    "id":"AN4493-1",
    "download_type":"biomarker_detail",
    "format":"json",
    "compressed":false
}
```

#### biomarker search result
```
{
        "id": "4f21c7f3a27853952adcd0838b8dc5cb",
        "download_type": "biomarker_list",
        "format": "csv",
        "compressed": false
}
```

**Comment by sujeetvkulkarni** [comment]
d04560972575efff3cec325422f7b4374f098aef,
611480d2de8822f239a7e2be8a0ee6178c1e593d
