### ISSUE TITLE
New links on motif list page

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1232]
On the [motif list page](https://www.glygen.org/list-of-motifs/) 
* remove the links in the "Motif Name" and "Motif Synonym(s)" column
* Change the link in the "No of glycans" column to trigger a glycan search by motif ID
* Add a link in the "No of proteins" column to trigger a super search by motif ID to find proteins

**Comment by sujeetvkulkarni** [comment]
search image slightly above aligned with numbers.

**Comment by sujeetvkulkarni** [comment]
use this in tooltip.

**Comment by sujeetvkulkarni** [comment]
611480d2de8822f239a7e2be8a0ee6178c1e593d
