### ISSUE TITLE
Peptide search as standalone feature

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1234]
On the protein search page:
- In "Advanced Search" remove the input fields for "Protein or Peptide Sequence"
- Add a new tab "Sequence search" between "Advanced Search" and "Tutorial"
- Add the removed fields from Advanced Search in the new tab

Make sure if "Modify" is clicked on the protein search result page it goes to the right tab.

**Comment by sujeetvkulkarni** [comment]
Enter a protein or peptide sequence. Use 'X' as wild card character for any amino acid for example, NXT. Use '[]' for alternate amino acids for example, N[SV]T to search for protein which contains either NST or NVT.

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger Should we add retrieve sequence like blast - https://www.glygen.org/blast/
for Sequence Search tab in protein search. One for blasts retrieves all sequences in UniProt based on id not just in GlyGen. We can use typeahead here to guide user to get GlyGen only UniProt IDs.

**Comment by ReneRanzinger** [comment]
@sujeetvkulkarni no. If you have the protein ID you can do an ID search instead. And that an entire protein sequence is a substructure in another protein is very unlikely. We could make something for a Peptide database. But I rather wait for a request.

**Comment by sujeetvkulkarni** [comment]
611480d2de8822f239a7e2be8a0ee6178c1e593d
