### ISSUE TITLE
The downloads script/instructions still needs work. It is is missing cases like this:

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1238]
The downloads script/instructions still needs work. It is is missing cases like this:

<img width="1397" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/944a7ec4-3cda-437f-8616-c64dfd57bd67">

**Comment by kmartinez834** [comment]
Looks like some of these files weren't unzipped on April 4th.  Just checked the download script, it is working.  Maybe the unzipping process was interrupted.

@katewarner did the $username_download_summary.csv script flag these files?

**Comment by katewarner** [comment]
@kmartinez834 

Apologies, that dataset is showing an error message in my download summary. I must have missed it when I looked through the log. I double checked and none of the other protein datasets are showing an error message. I also checked the files in each dataset to make sure they had been unzipped.

**Comment by kmartinez834** [comment]
@katewarner ok thanks for checking!  I'm making some minor changes to the script also.  

@rykahsay ok to close this ticket?
