### ISSUE TITLE
OMA downloads are expected to be text/tsv files (not JSON)

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1239]
Can you please download tsv formats under downloads/oma/current/? The script expects tsv files and is breaking

**Comment by katewarner** [comment]
@rykahsay Urnisha and Katrina were processing the OMA downloads, so I think the ticket should be assigned to them.

**Comment by ubhuiyan** [comment]
@rykahsay We are unable to have the OMA downloads as tsv/txt given the size of those files often leads to an error. @kmartinez834 spoke to someone at OMA and they suggested we use an API to produce json files instead. The instructions for how to do this is provided in ticket #1220.
