### ISSUE TITLE
add swagger api options related to event, video and other apis.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#124]
Add api options related to auth_login , video_addnew, video_delete, event_addnew, event_update etc.

**Comment by rykahsay** [comment]
I have exposed those as well but I still need to figure out how to allow user to give access_token in addition to the payload query. From your javascript, the way you provide the access token is as follows. When you use /auth/login API, a successfull login should give the "login_response" given at the bottom

In Javascript, you can store this to local storage using localStorage.setItem("access_csrf", login_response.access_csrf) and pass it in your subsequent requests to access restricted APIs as:

var svcUrl = "https://api.tst.glygen.org/video/addnew";
var reqObj = {"url":"url_to_my_video"};
const requestOptions = { 
      method: 'POST', 
      headers: { 'Content-Type': 'application/json', 'X-CSRF-TOKEN': access_csrf},
      body: JSON.stringify(reqObj), 
      credentials: 'include'
};
fetch(svcUrl, requestOptions).then((res) => res.json()).then( ...



Alternatively, from command line using shell script:

ACCESS_TOKEN= "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NzgzODk4NTIsIm5iZiI6MTY3ODM4OTg1MiwianRpIjoiMTViOTkyNDEtYjVmMi00NDAzLTg1NGYtYTQzZjA5OGViYjlkIiwiZXhwIjoxNjc4NDc2MjUyLCJpZGVudGl0eSI6InJ5a2Foc2F5QGd3dS5lZHUiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MiLCJjc3JmIjoiYjc1NzE2NGEtMzlkZC00N2JiLWJiNzctNmE5OWE2ZDY0YmE3In0.HJVapcMKd3--wr9iqNbHkQUQZkwumHXEzKWltzupW4s",

curl -H "Content-Type: application/json" -H "Authorization: Bearer $ACCESS_TOKEN" https://api.tst.glygen.org/video/addnew -d '{"url":"https://www.youtube.com/embed/xyV5v5nRm6A?rel=0"}'





login response
===========
{
    "access_csrf": "b757164a-39dd-47bb-bb77-6a99a6d64ba7",
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NzgzODk4NTIsIm5iZiI6MTY3ODM4OTg1MiwianRpIjoiMTViOTkyNDEtYjVmMi00NDAzLTg1NGYtYTQzZjA5OGViYjlkIiwiZXhwIjoxNjc4NDc2MjUyLCJpZGVudGl0eSI6InJ5a2Foc2F5QGd3dS5lZHUiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MiLCJjc3JmIjoiYjc1NzE2NGEtMzlkZC00N2JiLWJiNzctNmE5OWE2ZDY0YmE3In0.HJVapcMKd3--wr9iqNbHkQUQZkwumHXEzKWltzupW4s",
    "refresh_csrf": "24897187-8e60-4933-b109-8246964de8da",
    "status": 1,
    "username": "rykahsay@gwu.edu"
}

**Comment by sujeetvkulkarni** [comment]
@rykahsay 
myglygen@gmail.com (email) and it's corresponding password does not work in test /auth/login/ api. It works in prod api.

**Comment by sujeetvkulkarni** [comment]
@rykahsay 
I have registered myglygen@gmail.com email id and getting below response while adding video can you please give it authorization?
{"msg":"Missing JWT in cookies or headers (Missing cookie \"access_token_cookie\"; Missing Authorization Header)"}
Also, in the above example(I have given below) you have passed access_csrf but not token dont we need to pass access_token too to the api as one of the parameter along with url?

var svcUrl = "https://api.tst.glygen.org/video/addnew";
var reqObj = {"url":"url_to_my_video"};
const requestOptions = {
method: 'POST',
headers: { 'Content-Type': 'application/json', 'X-CSRF-TOKEN': access_csrf},
body: JSON.stringify(reqObj),
credentials: 'include'
};
fetch(svcUrl, requestOptions).then((res) => res.json()).then( ...

**Comment by sujeetvkulkarni** [comment]
@rykahsay, 
When I try login now I am getting
https://api.tst.glygen.org/auth/login
{"error_list": [{"error_code": "inactive account"}]}
for myglygen@gmail.com email id
but if try to register it again it says
{
  "error_list": [
    {
      "error_code": "email-already-regisgered"
    }
  ]
}

**Comment by rykahsay** [comment]
Use these credentials:

{"email":"myglygen@gmail.com"}

**Comment by sujeetvkulkarni** [comment]
@rykahsay 
I am getting {"error_list": [{"error_code": "exception-error-IW8FQZ"}]}
response when I am trying to login on beta using above credentials.

**Comment by rykahsay** [comment]
Please try now on beta. As you can see, I was able to login now.

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/20584876/230501264-afc10b98-f954-4d76-9cea-9f8ea1a237a0.png">
