### ISSUE TITLE
Reprocess chicken protein files

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1242]
There was a bug in the download script which caused some `chicken*.faa` files to be excluded from `refseq_protein_all_9031.faa`.  All other downloads are correct. 

--> Reprocess files that depend on `refseq_protein_all_9031.faa` (this does not appear in the usage logs but is used in [refseq-downloader-step2.py](https://github.com/glygener/glygen-backend-integration/blob/master/dataset-maker/refseq-downloader-step2.py)

FYI @katewarner @Luke-Johnson-5 :
I implemented a `wait` command in `download_refseq.sh` that will prevent `gunzip` from running until all files are done downloading

**Comment by rykahsay** [comment]
@kmartinez834 --> I don't use those files. Maybe you can stop downloading them

**Comment by kmartinez834** [comment]
I made a ticket to implement this change in the next release
