### ISSUE TITLE
Motif list page number differ from super search list page in case of No of Proteins.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1245]
Motif ID : GGM.000001

https://www.glygen.org/list-of-motifs/
No of Proteins : 280

![Screenshot 2024-04-16 at 1 54 50 PM](https://github.com/glygener/glygen-issues/assets/13891482/9f9dbf72-780e-4307-b3c2-55a60ff2bcc5)

https://www.glygen.org/protein-list/970d068a0b60f46f838884f82143556a/sups
No of Proteins : 219

![Screenshot 2024-04-16 at 1 56 50 PM](https://github.com/glygener/glygen-issues/assets/13891482/db9c601c-896c-4508-b6e2-c50b4ce1923d)

API:
```
https://api.glygen.org/protein/list?query=
{"id":"211ae287b86f847c4b8eec43dceef754","offset":1,"limit":20,"order":"desc","sort":"hit_score","filters":[]}
```

These two numbers should match each other. As we will be providing direct search option to the user on motif list page user will get to see different numbers in this case.

**Comment by rykahsay** [comment]
This is because some motifs are in glycans that glycosylate a protein at unknown position and I have not been making site objects if position is unknown. From this version on, I will start making site objects for unknown positions by considering start_pos=1 and end_pos=len(protein_seq) and the numbers will be the same. I hope this will not introduce other issues -- we need to test carefully

**Comment by rykahsay** [comment]
Corrected on tst now:

<img width="1268" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/2fe9daa5-e7f9-46e7-b58c-728cfd1b10d4">


<img width="1406" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/a9347b07-f033-4913-a587-bf62f6e0d3f3">

**Comment by sujeetvkulkarni** [comment]
To reduce the overall impact it would be best to add -1 as start and end position. Some invalid value to identify those sites.
As this would result in lot of sites getting reported if searched with site start position as 1.
tst server:
https://tst.glygen.org/site-list/5334fa1b047d936431a87909c0857803/sups

prod server:
https://www.glygen.org/site-list/5334fa1b047d936431a87909c0857803/sups

this is little confusing to the user.
Front end can show -1 as unknown site as special case.

**Comment by rykahsay** [comment]
I don't understand, can you be a little bit more clear?

**Comment by sujeetvkulkarni** [comment]
@rykahsay ok, I have added more details below. Looks like the links shared above are not working now and when I tried to perform new search now list page is showing some error, but I have added screen shots and other details below, please let me know if more clarification is needed.


Question:
Can we have start position and end position values other than 1  for start_pos and length of sequence for end_pos? 
Can use some invalid numbers like -1 for start pos and end pos?

When you perform a search using super search interface with start position as 1 (in Site box), we get 10,013 numbers as results on Site box.

<img width="1496" alt="Screenshot 2024-05-18 at 2 06 10 PM" src="https://github.com/glygener/glygen-issues/assets/13891482/69832cad-c8d3-46db-9c5b-5209911858ce">

<img width="1447" alt="Screenshot 2024-05-18 at 2 06 41 PM" src="https://github.com/glygener/glygen-issues/assets/13891482/49781f3a-e0f3-4541-8f05-be9cb429db69">


But it looked like not all sites in the results with start position 1 are valid, and some of them had got listed because of the changes made to show unknown sites with 
start_pos=1 and end_pos=len(protein_seq) .

Earlier when clicked on Site box with 10,013 results it showed list page with results but now looks like it is failing as shown below.
link: https://tst.glygen.org/site-list/5334fa1b047d936431a87909c0857803/sups

<img width="1456" alt="Screenshot 2024-05-18 at 2 14 06 PM" src="https://github.com/glygener/glygen-issues/assets/13891482/f8fbbb1a-934d-4637-90a6-84103a47dcd3">

**Comment by rykahsay** [comment]
Please try now. I am using 0, instead of -1 

Sites with start = 1
<img width="1243" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/04f9984a-8563-4957-8507-9e104cc1b87e">


Sites with start = 0
<img width="1232" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/7a7762ae-11c8-491a-9608-3c0f3a63fffe">

**Comment by sujeetvkulkarni** [comment]
@rykahsay though I think ideally with Sites with start = 0 should return 0. But currently it returns a number but when clicked it shows no results. This should be fine.

But can you please tell me what is the value we are using at end pos for unknown sites?
Is it end_pos=len(protein_seq)? Will the unknown positions get listed if searched in super search interface with End Position values as length of positions.

![Screenshot 2024-05-20 at 11 23 23 AM](https://github.com/glygener/glygen-issues/assets/13891482/6c6e8e83-947c-4c18-b011-bca8b5a28926)

**Comment by rykahsay** [comment]
I have tried to fix it now but you need to relax your condition and show sites with start_pos=0 and end_pos=0 .... supersearch/list API is responding with results but you are now showing them

<img width="701" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/4151b804-7cc6-4252-add9-9d5aa317806e">

**Comment by rykahsay** [comment]
You will need to adjust your site list table (avoid linking of start_pos=0 and end_pos=0):

<img width="1399" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/46ec5258-5758-4757-9c54-805bb0ce5f24">

**Comment by sujeetvkulkarni** [comment]
c2553910239102e7e0718b8f9b17e9d79f32006c

**Comment by sujeetvkulkarni** [comment]
Fixed.
