### ISSUE TITLE
Update permissions for glycogenes directory

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#1246]
Could you please update permissions for glycogenes directory? In particular, `2024_02_14` and `current`:

![Screen Shot 2024-04-16 at 3 44 38 PM](https://github.com/glygener/glygen-issues/assets/61590108/5276d420-a0c2-4970-811e-acb90126141a)

FYI @kmartinez834 @jeet-vora

**Comment by rykahsay** [comment]
Done.

![Uploading image.png…]()
