### ISSUE TITLE
Add new datasets to csv file for Nathan

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1249]
Add proposed rows here before updating files4nathan.csv

| File Name | Path | Source | GlyGen Datasets | PMID | PMID Field | Notes
| --- | --- |--- |--- |--- |--- |--- |
|chicken_o_glcnacome_mcw.csv| mcw_oglcnac/current/| OGlcNAcDB|GLY_000959:Chicken|   | PMIDS
|ambiguous_sites.csv | atlas_oglcnac/current/| OGlcNAcAtlas| GLY_000708:Human,GLY_000709:Mouse,GLY_000710:Rat,GLY_000711:FruitFly,GLY_000800:Yeast,GLY_000955:Pig,GLY_000962:Chicken| | pmid
|unambiguous_sites.csv | atlas_oglcnac/current/ | OGlcNAcAtlas| GLY_000708:Human,GLY_000709:Mouse,GLY_000710:Rat,GLY_000711:FruitFly,GLY_000800:Yeast,GLY_000955:Pig,GLY_000962:Chicken| | pmid
|ccRCC_TMT_intact_glycopeptide_abundance_MD-MAD.tsv| pdc/current/ | PDC| GLY_000961:Human|37074911||"Nglycan" column needs to be mapped to GlyTouCan accession
diabetes_glycomic_mapping.csv|export_files/current/|Gornik Lab|GLY_000960:Human|28905229||Row 44 with no GlyTouCan ID is the submission that is "still processing"|
|glygen_upload.csv|embl/current/|	EMBL|GLY_000888:Human,GLY_000889:Mouse| DOI:10.1101/2023.09.13.557529| |
|Custom_MatrixDB_biomolecules.tsv|matrixdb/current/|MatrixDB||||provides information on GAG_* accessions

**Comment by ubhuiyan** [comment]
@kmartinez834 could you check this and let me know if I am on the right track?

**Comment by kmartinez834** [comment]
@ubhuiyan off to a good start, here are my corrections/comments:

- `chicken_o_glcnacome_mcw.csv` PMID field should be "PMIDS" (should match header exactly as written in source file)
- Lines for `ambiguous_sites.csv` and `umambiguous_sites.csv` should be edits to current rows for `ambiguous_sites_version_2.0.csv `and `unambiguous_sites_version_2.0.csv`
--> Also note PMID field should be "pmid"
- The source file for `human_proteoform_glycosylation_sites_pdc.csv` is now located in `downloads/pdc/current`, please update
- The source file for `*_proteoform_glycosylation_sites_embl.csv` is located in `downloads/embl/current`, please update
- I'll provide info for `human_proteoform_glyosylation_sites_diabetes_glycomic.csv` source file when its ready

**Comment by kmartinez834** [comment]
For the diabetes glycomic file:
| File Name | Path | Source | GlyGen Datasets | PMID | PMID Field | Notes
| --- | --- |--- |--- |--- |--- |--- |
diabetes_glycomic_mapping.csv|export_files/current/|Gornik Lab|GLY_000960:Human|28905229||Row 44 with no GlyTouCan ID is the submission that is "still processing"|

**Comment by kmartinez834** [comment]
PDC dataset id is GLY_000961

**Comment by kmartinez834** [comment]
I added a note to the human_proteoform_glycosylation_sites_pdc.csv row.  Everything looks good.  Please update the file and README and push to GitHub.
