### ISSUE TITLE
Glycan files ready for Nathan

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1252]
All changes for 2.5 have been applied to https://github.com/glygener/glygen-glycan-pipeline. Please proceed with glycan export processing.

_fyi @ubhuiyan_

**Comment by kmartinez834** [comment]
@edwardsnj  I used your exact_synonym.txt file to map compositions to GlyTouCan accessions in the PDC file ccRCC_TMT_intact_glycopeptide_abundance_MD-MAD.tsv

Some of the comps were missing from exact_synonym.txt, but were present in the GNOme composition browser:
```
G84225JN,N2H11F1S0G0
G89045VA,N2H10F1S1G0
G54010QB,N4H8F1S0G0
G19918RR,N6H7F5S2G0
G38773MR,N6H3F4S2G0
G58908DB,N7H4F0S4G0
G06991MU,N10H12F1S1G0
G37995HC,N2H10F1S0G0
G94390IS,N7H8F4S0G0
G72197KC,N4H8F1S1G0
G57794FS,N8H10F0S3G0
G98129XB,N7H4F1S2G0
G68735SN,N4H7F1S2G0
G05119ZZ,N9H10F3S0G0
G15670WD,N5H6F1S5G0
G88313PD,N8H10F0S4G0
G42976ON,N9H11F0S3G0
G92551PG,N7H8F5S0G0
G45624GT,N12H5F2S3G0
```
And these I couldn't map from the file or the browser:
```
N6H7F4S4G0
N6H7F5S4G0
N8H10F6S1G0
N10H11F6S3G0
```

I'm attaching my file that maps all of the "Nglycan" strings to GlyTouCan accessions for reference:
[pdc_glytoucan_mapping.csv](https://github.com/glygener/glygen-issues/files/15085333/pdc_glytoucan_mapping.csv)

**Comment by edwardsnj** [comment]
I already wrote code to do this mapping, the missing ones will need to be registered with GlyTouCan. The interactive GNOme browser does some normalization of the composition strings that helps it find compositions with zeros and monosaccharides in a different order.

**Comment by edwardsnj** [comment]
And I just added code to tolerate the "G" which you must have had to work around.

**Comment by kmartinez834** [comment]
Got it.  I created the mapping file for Robel to process the proteoform data, but wanted to make you aware of the issue.

Would you mind submitting the missing compositions to GlyTouCan?  Not urgent this release, but when you get a chance.

**Comment by edwardsnj** [comment]
Submitted the missing compositions to GlyTouCan.

**Comment by kmartinez834** [comment]
@edwardsnj are these accessions still pending?

**Comment by edwardsnj** [comment]
Here they are:

N6H7F4S4G0 HexNAc6Hex7Fuc4NeuAc4 [G65344XH](https://glytoucan.org/Structures/Glycans/G65344XH)
N6H7F4S4G0 HexNAc6Hex7Fuc4NeuAc5 [G29580WD](https://glytoucan.org/Structures/Glycans/G29580WD)
N8H10F6S1G0 HexNAc8Hex10Fuc6NeuAc1 [G30521DU](https://glytoucan.org/Structures/Glycans/G30521DU)
N10H11F6S3G0 HexNAc10Hex11Fuc6NeuAc3 [G99660SU](https://glytoucan.org/Structures/Glycans/G99660SU)

**Comment by kmartinez834** [comment]
Thanks a lot.  Was Kiyoko able to help with that other topology structure you submitted for me?

**Comment by edwardsnj** [comment]
Yes (and no). Solution was to use another tool to generate corresponding WURCS sequence and submit that for registration. I haven't got back to it but I can make that happen today. Stay tuned.

**Comment by edwardsnj** [comment]
Here is the accession: G42752DG
