### ISSUE TITLE
GlyGen Poster for BCO Conference

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#1253]
https://gwu0.sharepoint.com/:p:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Conference%20Abstracts%20and%20Posters/Posters/BCO%20Conference%202024.pptx?d=w8f43474ca261472283c5a848034c7a4e&csf=1&web=1&e=51ADj0

**Comment by JingyueWu** [comment]
@ubhuiyan @kmartinez834 @CyrusAY @katewarner I think having "Data Integration and Quality Assurance," "BioCompute Objects (BCO): Enabling Data Documentation and Exchange," and "Case Study: Human Glycosylation Site Dataset" sections is good. However, I'm struggling to think of a good way to expand on the section headers. In particular, adding good visualizations (i.e. needs to be better than just screenshots of JSON or BCO). I wrote the brief descriptions for them. Can you guys help me out here?

**Comment by katewarner** [comment]
@JingyueWu I can help you with the visuals if you send me the descriptions. I used to help people make figures for their posters at my old job

**Comment by JingyueWu** [comment]
@katewarner Thanks! The descriptions are on the poster. Or would you like me to send you more details?

**Comment by katewarner** [comment]
Oh sorry, I didn't see that you've added the file. I'll take a look early tomorrow morning

**Comment by kmartinez834** [comment]
In the conclusion, I recommend changing 
"Visit **https://data.glygen.org** for access to the latest glycoscience data and tools."
to 
"Visit **https://glygen.org** for access to the latest glycoscience data and tools."

Or, if you want to direct people to the data module, remove "tools" from this sentence.

**Comment by JingyueWu** [comment]
Updated version per 4/24: https://gwu0.sharepoint.com/:p:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Conference%20Abstracts%20and%20Posters/Posters/BCO%20Conference%202024.pptx?d=w8f43474ca261472283c5a848034c7a4e&csf=1&web=1&e=f86WRe

Thanks @katewarner for generating the figures. Do you think you could modified the figure under "Data Integration and Quality Assessment" section, so it looks different from the one in Robel's paper? Happy to share BioRender with you and work on it together, please just let me know. 

@kmartinez834 @ubhuiyan let me know what y'all think in terms of overall how we can improve this.
