### ISSUE TITLE
Examples needed for biomarker search options

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1255]
We will be needing one example for each biomarker search option listed below. These options will be provided to the user for better understanding of how to use search interface. 

   * Specimen
   * LOINC code
   * Biomarker Entity
   * Biomarker ID
   * Disease
   * DOID
   * Pubmed ID
   * Exposure Agent ID

related #1221

**Comment by DaniallMasood** [comment]
Examples:

- Specimen: blood (UBERON:0000178)
- LOINC code: 65759-3
- Biomarker entity: CD4+ T cell
- Biomarker ID: AA4691-4
- Disease: colorectal cancer
- DOID: DOID:9256
- Pubmed ID: 32479790
- Exposure agent ID: (need to find an example of this for now)


All searches above are related to the same biomarker: decreased CD4+ T count
