### ISSUE TITLE
Tooltips needed for biomarker search options

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1256]
* Specimen
   * LOINC code
   * Assessed entity type
   * Biomarker Entity
   * Biomarker ID
   * Disease
   * BEST Biomarker Role
   * Exposure Agent ID

related to #1221

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood tooltips are needed to explain user about a particular field on the biomarker search page like shown below.
User can hover over the question mark icon next to field name and will get to see the tooltip text.

![Screenshot 2024-04-23 at 1 44 45 PM](https://github.com/glygener/glygen-issues/assets/13891482/1b24aa57-4cb2-4f70-8903-166f561370f3)

**Comment by DaniallMasood** [comment]
Specimen:
The type of sample in which a biomarker is identified (such as tissue, blood, etc.)
LOINC Code:
LOINC codes are assigned to lab test results. Search for biomarkers associated with lab observations using LOINC codes.
Assessed Entity Type:
Search for biomarkers based on what type of biological molecule the biomarker is (e.g protein, gene, metabolite)
Biomarker Entity:
Search for biomarkers based on the entity that is being changed (e.g IL6, BRCA2)
Biomarker ID:
Search for biomarkers based on the unique Biomarker ID is assigned to it. Biomarker IDs are in two levels; canonical level ID is the unique entity change that makes a biomarker and the secondary ID is the unique biomarker-disease association)
Condition:
Search for biomarkers that are related to a specific condition.
Disease ID:
Search for biomarkers that are related to a specific disease. Specify the disease using MONDO, DOID or MIM.
Pubmed ID:
A PMID is the unique identifier number used in PubMed for each article. The PMID is assigned to each article record when it enters the PubMed system.

@sujeetvkulkarni

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood Added above tooltips. Done.
