### ISSUE TITLE
Need a home page image for biomarkers

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1258]
Need an image to display Biomarker search card on home page.

**Comment by ReneRanzinger** [comment]
That should be a vector graphic (SVG) with ratio 283x212.

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood this is how it would look on the home page. Temporarily I am using Protein search image for biomarker search here.

![Screenshot 2024-04-23 at 1 39 16 PM](https://github.com/glygener/glygen-issues/assets/13891482/86556a35-89d7-446f-bddb-81f503082d44)

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood  You can also provide a small sentence describing biomarker search like shown in the image above.

**Comment by DaniallMasood** [comment]
Biomarker Search
Search for biomarkers based on their entity, condition, BEST role, and annotations.

**Comment by ReneRanzinger** [comment]
@DaniallMasood do you have an idea for the biomarker graphics? Do you have something we can reuse? Maybe something along the line of [this](https://blog.bccresearch.com/biomarkers-advancing-drug-development-dominating-the-market).

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood can you please share the image, as we will be moving to beta now.

**Comment by DaniallMasood** [comment]
![biomarker home page](https://github.com/glygener/glygen-issues/assets/116293652/6df84cb7-899a-4839-acc9-71e5cdf1a16f)

**Comment by ReneRanzinger** [comment]
@DaniallMasood do you have a high resolution version of this or a vector graphics (SVG, Illustrator)? Also please make sure if you use images from other resources that we are not violating copy right and license constrains. Some image share sites have licenses that do not allow for reuse (without pay) or use without acknowledging the source.

**Comment by DaniallMasood** [comment]
I made this image on my own and not from another resource. was made on biorender let me get the SVG version instead and i will place it here

**Comment by ReneRanzinger** [comment]
OK, just make sure that we abide by the license 

https://www.biorender.com/basic-license  section 3.

**Comment by DaniallMasood** [comment]
ok let me work on this and will provide a better image soon

**Comment by DaniallMasood** [comment]
![biomarker home page](https://github.com/glygener/glygen-issues/assets/116293652/ac3ee09f-0d48-46c4-95f5-f5fb6e33b0a6)

redone completely on ppt using stock images from within ppt. will this work?

**Comment by ReneRanzinger** [comment]
I mean nobody is going to sue us ... hopefully. If i take stock images I make sure they are CC0 or allow use without need for attribution or other restrictions.

**Comment by DaniallMasood** [comment]
https://support.microsoft.com/en-us/office/insert-icons-in-microsoft-365-e2459f17-3996-4795-996e-b9a13486fa79?ui=en-us&rs=en-us&ad=us

Here is what I used and it states "These icons are free to use and there's no royalty or copyright to worry about."

**Comment by ReneRanzinger** [comment]
@DaniallMasood thanks, sorry for the hassle but with LLM copyright becomes more and more important and copyright violation is not a road we want to go.

**Comment by DaniallMasood** [comment]
Not a problem. This is all very new to me (the licensing and permission to use stuff) and I dont want to make things difficult or problematic down the road. So is the best option to find an image or stock images that have a CC0 or permission to use while citing the source? 

Let me know what is best and thank you for the direction. I can continue to work on this

**Comment by ReneRanzinger** [comment]
Thanks for working on this. Licenses that require citation can be problematic too. If you use the illustration in a PowerPoint slide you can always add a URL in the bottom of the slide. But for a webpage you do not really have a space to provide the citation. It also looks strange if you have to thank somebody else for your webpage (or part of it) ;-)
