### ISSUE TITLE
Rows lost due to protein masterlist updates

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#126]
Rows lost due to new Uniprotkb ac (ex D3ZQ57-1):
```
$ grep "uniprotkb\|D3ZQ57" /data/projects/glygen/generated/datasets/unreviewed/rat_proteoform_glycosylation_sites_unicarbkb.csv
"uniprotkb_canonical_ac","glycosylation_site_uniprotkb","amino_acid","saccharide","glycosylation_type","xref_key","xref_id","src_xref_key","src_xref_id","start_pos","end_pos","start_aa","end_aa","site_seq","site_type","src_file_name","uckb_id","composition","curation_notes","additional_notes","pdb","swiss_model","abundance","source_tissue_id","source_tissue_name","source_cell_line_cellosaurus_id","source_cell_line_cellosaurus_name","n_sequon","n_sequon_type"

$ grep "uniprotkb_canonical_ac\|D3ZQ57" /data/shared/glygen/releases/data/v-1.12.3/reviewed/rat_proteoform_glycosylation_sites_unicarbkb.csv
"uniprotkb_canonical_ac","glycosylation_site_uniprotkb","amino_acid","saccharide","glycosylation_type","xref_key","xref_id","src_xref_key","src_xref_id","start_pos","end_pos","start_aa","end_aa","site_seq","site_type","src_file_name","uckb_id","composition","curation_notes","additional_notes","pdb","swiss_model","abundance","n_sequon","n_sequon_type"
"D3ZQ57-1","393","Asn","G80920RR","N-linked","protein_xref_unicarbkb","D3ZQ57","protein_xref_unicarbkb","D3ZQ57","393","393","Asn","Asn","N","known_site","known_legacy_human_mouse_rat_glygen","","comp_HexNAc2Hex9dHex0NeuAc0NeuGc0Pent0S0P0KDN0HexA0","","","","","","NLT","NXT"
"D3ZQ57-1","393","Asn","G80920RR","N-linked","protein_xref_pubmed","24090084","protein_xref_unicarbkb","D3ZQ57","393","393","Asn","Asn","N","known_site","known_legacy_human_mouse_rat_glygen","","comp_HexNAc2Hex9dHex0NeuAc0NeuGc0Pent0S0P0KDN0HexA0","","","","","","NLT","NXT"
"D3ZQ57-1","393","Asn","G60230HH","N-linked","protein_xref_unicarbkb","D3ZQ57","protein_xref_unicarbkb","D3ZQ57","393","393","Asn","Asn","N","known_site","known_legacy_human_mouse_rat_glygen","1081","","ASN-393","","","","","NLT","NXT"
"D3ZQ57-1","393","Asn","G60230HH","N-linked","protein_xref_pubmed","24090084","protein_xref_unicarbkb","D3ZQ57","393","393","Asn","Asn","N","known_site","known_legacy_human_mouse_rat_glygen","1081","","ASN-393","","","","","NLT","NXT"
"D3ZQ57-1","393","Asn","G60230HH","N-linked","protein_xref_unicarbkb","D3ZQ57","protein_xref_unicarbkb","D3ZQ57","393","393","Asn","Asn","N","known_site","known_legacy_human_mouse_rat_glygen","1081","","GlycoSuiteDB  curation notes. Reported structure can be attached to the following: ASN-393 ; ASN-393","","","","","NLT","NXT"
"D3ZQ57-1","393","Asn","G60230HH","N-linked","protein_xref_pubmed","24090084","protein_xref_unicarbkb","D3ZQ57","393","393","Asn","Asn","N","known_site","known_legacy_human_mouse_rat_glygen","1081","","GlycoSuiteDB  curation notes. Reported structure can be attached to the following: ASN-393 ; ASN-393","","","","","NLT","NXT"
```

Previously "uniprotkb_canonical_ac" is now "unreviewed_isoforms"
```
$ grep "uniprotkb\|D3ZQ57" /data/projects/glygen/generated/datasets/unreviewed/rat_protein_masterlist.csv 
"uniprotkb_canonical_ac","status","gene_name","reviewed_isoforms","unreviewed_isoforms"
"A0A0G2K2Y9-1","unreviewed","Plxnb2","","D3ZQ57-1"

$ grep "uniprotkb\|D3ZQ57" /data/shared/glygen/releases/data/v-1.12.3/reviewed/rat_protein_masterlist.csv 
"uniprotkb_canonical_ac","status","gene_name","reviewed_isoforms","unreviewed_isoforms"
"D3ZQ57-1","unreviewed","Plxnb2","","D3ZQ57-1"
```

--> @rykahsay should dataset maker be mapping to new uniprotkb_canonical_ac now?  Or are these missing rows expected due to the proteome update?

**Comment by rykahsay** [comment]
It is not a canonical anymore and we only map information to canonicals 


>tr|A0A0G2K2Y9-1|A0A0G2K2Y9_RAT Isoform 1 of Plexin B2 OS=Rattus norvegicus OX=10116 GN=Plxnb2 PE=1 SV=1 CANONICAL=A0A0G2K2Y9-1
MAQPLWALTLLGLMGLGLSLRSRKPESFRSETELNHLVVDEASGVVYVGAVNALYQLSAD
LQVQQHVVTGPFLDNKKCTPPIEPSQCHEAMLTDNFNQLLLLDPPGKRLVECGSLFKGIC
ALRAMSNISVRLFYEDGSGEKSFVASNDERVATVGLVSSTRPDGERVLFVGKGNGPHDNG
IIVSTRLLDRSEGREAFEAYSDHTTFKAGYLSTNTQQFVAAFEDGRYVFFIFNQQDKHPA
KNRTLLARMCKDDPSYYSYVEMDLLCKDPTEPQNSVFGTCLAASVATPGAGRALYAVFSR
DGRSTGGPGAGLCMFPLEKVHEMMEANRNTCYAGTRESGRTNFYKPFHGDIQCGGHARGA
SESFPCGSEHLPYPLGSRDGLEATALLHRGGLNLTAVTVTAENGHTIAFLGTSDGRILKV
YLAPDGTSSEYGSIPVDINKKIKGDLALSGNLSNLYAMTQDKVFRLPVQECLSYATCAQC
RDSQDPYCGWCVIEGRCTRKSECSRAEEAGHWLWSREKSCVTITDAFPQNMSRRAQGEVR
LSVSPLPTLAKEDELLCLFGESPPHSARVEDDAVICNSPSSIPSTPPGQDHVDVSIQLLF
KHGNVFLTSHQYPFYDCREAMSLVENLPCISCASNRWTCQWDLQYYECREASPNPEDGII
RAHMEDNCPQFLAPNPLVIPMNHETEVTFQGKNLETVKVSSLYVGSDLLKFEETVTMHES
DTFSFRTPKLSHDANETLPLHLYVKSFGKNIDSKLQVTLYNCSFGRSDCSLCLAADPAYR
CVWCRGQNRCVYEALCSNVTSECPPPVITRIQPETGPLGGGILVTIHGSNLGVKADDVKK
ITVAGQDCAFEPRGYSVSTRIVCAIEASETPFTGGIEVDVNGKLGHSPPHVQFTYQQPQP
LSVEPRQGPQAGGTTLTINGTYLDTGSKEDVRVTLNDVPCEVTKFGAQLQCVTGSQLAPG
QVALEISYGGSRVPSPGISFTYCENPVLRAFEPLRSFVSGGRSINVTGQGFSLIQKFAMI
VIAEPLRSWRRRREAGSLEPVTVMGTEYVFYNDTKVVFLSPAVPEEPEAYNLTALIQMDG
HRALLRTEAGAFEYVADPTFENFTGGVKKQVNKLIHARGTNLNKAMTLEEAEAFVGAERC
IMKTLTETDLYCEPPEVQPPPKRRQKRDTAHNLPEFIVKFGSREWVLGRVEYDTRASDVP
LSLILPLVMVPMVFIIVVSIYCYWRKSQQAEREYEKIKSQLEGLEESVRDRCKKEFTDLM
IEMEDQTNDVHEAGIPTLDYKTYTDRVFFLPSKDGDKDVMITGKLDIPESRRPIVEQALY
QFSNLLNSKSFLINFIHTLENQREFSARAKVYFASLLTVALHGKLEYYTDIMRTLFLELM
EQYVVAKNPKLMLRRSETVVERMLSNWMSICLYQYLKDSAGEPLYKLFKAIKHQVEKGPV
DAVQKKAKYTLNDTGLLGDDVEYAPLTVSVIVQDEGIDAIPVKVLNCDTISQVKEKIIDQ
VYRTQPCSCWPKPDSVVLEWRPGSTAQILSDLDLTSQREGRWKRINTLMHYNVRDGATLI
LSKVGVSQQPEDSQQDLPGERHALLEEENRVWHLVRPTDEVDEGKSKRGSMKEKERTKAI
TEIYLTRLLSVKGTLQQFVDNFFQSVLAPGHAVPPAVKYFFDFLDEQAEKHDIRDEDTIH
IWKTNSLPLRFWVNILKNPHFIFDVHVHEVVDASLSVIAQTFMDACTRTEHKLSRDSPSN
KLLYAKEISTYKKMVEDYYKGIRQMVQVSDQDMNTHLAEISRAHTDSLNTLVALHQLYQY
TQKYYDEIINALEEDPAAQKMQLAFRLQQIAAALENKVTDL



>tr|D3ZQ57-1|A0A0G2K2Y9_RAT Isoform 1 of Plexin B2 OS=Rattus norvegicus OX=10116 GN=Plxnb2 PE=1 SV=2 CANONICAL=A0A0G2K2Y9-1
MAQPLWALTLLGLMGLGLSLRSRKPESFRSETELNHLVVDEASGVVYVGAVNALYQLSAD
LQVQQHVVTGPFLDNKKCTPPIEPSQCHEAMLTDNFNQLLLLDPPGKRLVECGSLFKGIC
ALRAMSNISVRLFYEDGSGEKSFVASNDERVATVGLVSSTRPDGERVLFVGKGNGPHDNG
IIVSTRLLDRSEGREAFEAYSDHTTFKAGYLSTNTQQFVAAFEDGRYVFFIFNQQDKHPA
KNRTLLARMCKDDPSYYSYVEMDLLCKDPTEPQNSVFGTCLAASVATPGAGRALYAVFSR
DGRSTGGPGAGLCMFPLEKVHEMMEANRNTCYAGTRESGRTNFYKPFHGDIQCGGHARGA
SESFPCGSEHLPYPLGSRDGLEATALLHRGGLNLTAVTVTAENGHTIAFLGTSDGRILKV
YLAPDGTSSEYGSIPVDINKKIKGDLALSGNLSNLYAMTQDKVFRLPVQECLSYATCAQC
RDSQDPYCGWCVIEGRCTRKSECSRAEEAGHWLWSREKSCVTITDAFPQNMSRRAQGEVC
AAVSTLYPMAPGTDLLPAGHRARSSPTLYHVDVSIQLLFKHGNVFLTSHQYPFYDCREAM
SLVENLPCISCASNRWTCQWDLQYYECREASPNPEDGIIRAHMEDNCPQFLAPNPLVIPM
NHETEVTFQGKNLETVKVSSLYVGSDLLKFEETVTMHESDTFSFRTPKLSHDANETLPLH
LYVKSFGKNIDSKLQVTLYNCSFGRSDCSLCLAADPAYRCVWCRGQNRCVYEALCSNVTS
ECPPPVITRIQPETGPLGGGILVTIHGSNLGVKADDVKKITVAGQDCAFEPRGYSVSTRI
VCAIEASETPFTGGIEVDVNGKLGHSPPHVQFTYQQPQPLSVEPRQGPQAGGTTLTINGT
YLDTGSKEDVRVTLNDVPCEVTKFGAQLQCVTGSQLAPGQVALEISYGGSRVPSPGISFT
YCENPVLRAFEPLRSFVSGGRSINVTGQGFSLIQKFAMIVIAEPLRSWRRRREAGSLEPV
TVMGTEYVFYNDTKVVFLSPAVPEEPEAYNLTALIQMDGHRALLRTEAGAFEYVADPTFE
NFTGGVKKQVNKLIHARGTNLNKAMTLEEAEAFVGAERCIMKTLTETDLYCEPPEVQPPP
KRRQKRDTAHNLPEFIVKFGSREWVLGRVEYDTRASDVPLSLILPLVMVPMVFIIVVSIY
CYWRKSQQAEREYEKIKSQLEGLEESVRDRCKKEFTDLMIEMEDQTNDVHEAGIPTLDYK
TYTDRVFFLPSKDGDKDVMITGKLDIPESRRPIVEQALYQFSNLLNSKSFLINFIHTLEN
QREFSARAKVYFASLLTVALHGKLEYYTDIMRTLFLELMEQYVVAKNPKLMLRRSETVVE
RMLSNWMSICLYQYLKDSAGEPLYKLFKAIKHQVEKGPVDAVQKKAKYTLNDTGLLGDDV
EYAPLTVSVIVQDEGIDAIPVKVLNCDTISQVKEKIIDQVYRTQPCSCWPKPDSVVLEWR
PGSTAQILSDLDLTSQREGRWKRINTLMHYNVRDGATLILSKVGVSQQPEDSQQDLPGER
HALLEEENRVWHLVRPTDEVDEGKSKRGSMKEKERTKAITEIYLTRLLSVKGTLQQFVDN
FFQSVLAPGHAVPPAVKYFFDFLDEQAEKHDIRDEDTIHIWKTNSLPLRFWVNILKNPHF
IFDVHVHEVVDASLSVIAQTFMDACTRTEHKLSRDSPSNKLLYAKEISTYKKMVEDYYKG
IRQMVQVSDQDMNTHLAEISRAHTDSLNTLVALHQLYQYTQKYYDEIINALEEDPAAQKM
QLAFRLQQIAAALENKVTDL
