### ISSUE TITLE
Issues for questionable enzymes

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1261]
In your github create tickets for the questionable enzymes. @mtiemeyer0919 will recruite some experts (#1260) to help with the resolving of these issues.

**Comment by edwardsnj** [comment]
Issues have been started here: https://github.com/glygen-glycan-data/glycoTree/issues

**Comment by edwardsnj** [comment]
I am tracking enzyme issues in the above repository: [https://github.com/glygen-glycan-data/glycoTree](https://github.com/glygen-glycan-data/glycoTree)
