### ISSUE TITLE
Dataset issues: protein_homolog_clusters.csv

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1263]
The input files for protein_homolog_clusters.csv were changed from txt to json files (see #1220 for details).  Please double check this file at `/data/projects/glygen/generated/datasets/unreviewed/protein_homolog_clusters.csv`

--> Add any other issues you find to the comment below, then assign to Robel

**Comment by kmartinez834** [comment]
Issues
-------
- There are 54264 lines with missing uniprotkb_canonical_ac
```
$ awk -F, '{print $2}' unreviewed/protein_homolog_clusters.csv | grep '""' | wc -l
54264
```

**Comment by Luke-Johnson-5** [comment]
Addressed in ticket 1271
