### ISSUE TITLE
biomarker details api needs to support biomarker_canonical_id format.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1265]
Biomarker list api returns biomarker_canonical_id but biomarker details api needs to support both format.

API: https://api.tst.glygen.org/biomarker/list
id: 1e14c465c506a9fe2a55d1acc878199b
 returns 

```
"results": [
    {
      "biomarker_canonical_id": "A0001.1",
      "biomarker": "increased IL6 level",
      "assessed_biomarker_entity_id": "P05231-1",
      "assessed_entity_type": "protein",
      "assessed_biomarker_entity": "Interleukin-6",
      "specimen": "blood (0000178)",
      "best_biomarker_role": "prognostic",
}
]
```

biomarker details api needs to support both formats A0001 and A0001.1.
https://api.glygen.org/biomarker/detail/A0001
https://api.glygen.org/biomarker/detail/A0001.1

**Comment by rykahsay** [comment]
Please check now

**Comment by sujeetvkulkarni** [comment]
closing.
