### ISSUE TITLE
Changing Disease or Biomarker Disease name to Condition in advanced search tab.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1268]
As per https://github.com/glygener/glygen-issues/issues/1221 in the Advanced search field name is Disease or Biomarker Disease. But in the same ticket https://github.com/glygener/glygen-issues/issues/1221 field in Simple search is named Condition. Also as per https://github.com/glygener/glygen-issues/issues/1224 table column is named Condition. So should we use same name in all places and change Disease/Biomarker Disease field in Advanced search to Condition?

Please refer below given is screenshot.

 
![Screenshot 2024-04-23 at 1 44 45 PM](https://github.com/glygener/glygen-issues/assets/13891482/b1ba1f60-95bb-49ca-8e4d-5c6df4afc472)

**Comment by DaniallMasood** [comment]
Yes change to condition. I think i was making the list at separate time points and used condition and disease interchanging. Condition is fine and makes everything uniform
