### ISSUE TITLE
In a job if the list id is empty in results api then result count from status api should be 0.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#127]
https://api.tst.glygen.org/job/addnew

{
    "jobtype": "structure_search",
    "parameters": {
        "seq": "RES\n1b:x-dgal-HEX-1:5\n2s:n-acetyl\n3b:b-dgal-HEX-1:5\n4b:b-dglc-HEX-1:5|6:a\n5s:amino\nLIN\n1:1d(2+1)2n\n2:1o(3+1)3d\n3:3o(3+1)4d\n4:4d(2+1)5n",
        "align": "wholeglycan"
    }
}

https://api.tst.glygen.org/job/status/?query={"jobid":54}

{"tsid": "0", "status": "finished", "exit_status": "died with exit code 0", "command": "python /app/job_submitters/structure_search.py -i /data/shared/glygen//userdata/tst/jobs/54/input.json -o /data/shared/glygen//userdata/tst/jobs/54/output.json", "slots_required": "1", "enqueue_time": "Thu Mar  9 18:52:04 2023", "start_time": "Thu Mar  9 18:52:04 2023", "end_time": "Thu Mar  9 18:52:05 2023", "time_run": "1.196300s", "output_files": [{"format": "json", "url": "https://data.tst.glygen.org/ln2data/userdata/tst/jobs/54/output.json"}], "result_count": 3}

here in status api the "result_count" is 3.

But results api returns empty list id.

'https://api.tst.glygen.org/job/results/?query={"jobid":54}

{"list_id": "", "status": "finished", "jobtype": "structure_search", "parameters": {"seq": "RES\n1b:x-dgal-HEX-1:5\n2s:n-acetyl\n3b:b-dgal-HEX-1:5\n4b:b-dglc-HEX-1:5|6:a\n5s:amino\nLIN\n1:1d(2+1)2n\n2:1o(3+1)3d\n3:3o(3+1)4d\n4:4d(2+1)5n", "align": "wholeglycan"}}

If the list_id is empty in results api then status api should return 0 as "result_count".
This aplies to for substructure too.

**Comment by rykahsay** [comment]
Fixed
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/20584876/224137805-c2b98db5-cd61-4aa5-b71b-7fdc17f9ad93.png">
