### ISSUE TITLE
BiomarkerKB files have changed and no longer match files4nathan...

### ISSUE THREAD

**Issue by edwardsnj** [glygener/glygen-issues#1275]
The name allbiomarkers.tsv to allbiomarkers-all.csv of this file has changed, and its contents. I have adjusted my pipeline to match the current version of this file. Please update the files4nathan.csv and avoid making changes to the headers, format, or semantic content of the files without notifying me? Thx

**Comment by kmartinez834** [comment]
@rykahsay added this file - are we using allbiomarkers.tsv or allbiomarkers-all.csv?

**Comment by rykahsay** [comment]
We are using allbiomarkers.tsv

```
$ ls -ltr downloads/biomarkerdb/current/
total 970
-rwxrwxr-x. 1 rykahsay glygen  174518 Apr 24 06:06 annotations.json
-rwxrwxr-x. 1 rykahsay glygen 1065553 Apr 26 05:30 allbiomarkers.tsv
drwxrwsr-x. 2 rykahsay glygen       4 Apr 26 05:31 archive
-rwxrwxr-x. 1 rykahsay glygen 5704956 Apr 26 08:01 allbiomarkers.json
```

**Comment by kmartinez834** [comment]
I've updated files4nathan.csv and documented changes in the README
