### ISSUE TITLE
OGlcNAcAtlas filename changed without updating files4nathan.csv

### ISSUE THREAD

**Issue by edwardsnj** [glygener/glygen-issues#1276]
Now called [ambiguous_sites.csv](https://data.glygen.org/ln2downloads/atlas_oglcnac/current/ambiguous_sites.csv) and [unambiguous_sites.csv](https://data.glygen.org/ln2downloads/atlas_oglcnac/current/unambiguous_sites.csv).

Please don't change the filenames like that!

They used to have _version_2.0 on the end.

I write code that embeds the URL to the file. When the file changes names the code just silently fails and annotations get lost.

**Comment by kmartinez834** [comment]
The file is no longer version 2.0.  We've removed the version from the file name so it can remain static.

**Comment by edwardsnj** [comment]
I don't care *why* it was done, per se. I see now a notation about it. Must have missed it previously.
