### ISSUE TITLE
Landing host for GlycoSight tool on AWS.

### ISSUE THREAD

**Issue by pmcneely** [glygener/glygen-issues#1278]
We will need to update the Apache configuration to support running GlycoSight. I will have a container listening for file/information upload requests. I would like Apache to direct traffic from either `glycosight.aws.glygen.org` or `aws.glygen.org/glycosight` (either is fine, up to Robel's preference, or another reasonable target) to that container on localhost. Any port is fine as well; I've been using port 5000 in development.

**Comment by rykahsay** [comment]
I have edited the http conf file so that aws.glygen.org/glycosight get served from http://127.0.0.1:5050/. Please use port 5050 for your container


```
<VirtualHost 10.10.0.204:443>
  ServerName aws.glygen.org

  SSLEngine on
  SSLProtocol all -SSLv2 -SSLv3
  SSLCipherSuite HIGH:3DES:!aNULL:!MD5:!SEED:!IDEA
  SSLCertificateFile /etc/pki/tls/certs/hive.aws.biochemistry.gwu.edu.crt
  SSLCertificateKeyFile /etc/pki/tls/private/bco.biochemistry.gwu.edu.key
  Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure
  
  ProxyPass /glycosight http://127.0.0.1:5050/
  ProxyPassReverse /glycosight http://127.0.0.1:5050/

  ProxyPass / http://127.0.0.1:6060/
  ProxyPassReverse / http://127.0.0.1:6060/
</VirtualHost>

```

**Comment by pmcneely** [comment]
Containers are debugged and live on the server at `aws.glygen.org/glycosight`. Thanks.
