### ISSUE TITLE
Can "Motif is too big" error text be  "Structure is too big" or  "Substructure is too big"  depending upon api.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#128]
https://api.tst.glygen.org/job/addnew
{
    "query": {
        "jobtype": "structure_search",
        "parameters": {
            "seq": "RES\n1b:x-dglc-HEX-1:5\n2b:b-dglc-HEX-1:5\n3b:b-dglc-HEX-1:5\n4b:b-dglc-HEX-1:5\n5b:b-dglc-HEX-1:5\n6b:b-dglc-HEX-1:5\n7b:b-dglc-HEX-1:5\n8b:b-dglc-HEX-1:5\n9b:b-dglc-HEX-1:5\n10b:b-dglc-HEX-1:5\n11b:b-dglc-HEX-1:5\n12b:b-dglc-HEX-1:5\nLIN\n1:1o(3+1)2d\n2:2o(3+1)3d\n3:3o(3+1)4d\n4:4o(3+1)5d\n5:5o(3+1)6d\n6:6o(3+1)7d\n7:7o(3+1)8d\n8:8o(3+1)9d\n9:9o(3+1)10d\n10:10o(3+1)11d\n11:11o(3+1)12d",
            "align": "wholeglycan"
        }
    }
}

{"submission": "new", "status": {"tsid": "4", "status": "running", "command": "python /app/job_submitters/structure_search.py -i /data/shared/glygen//userdata/tst/jobs/52/input.json -o /data/shared/glygen//userdata/tst/jobs/52/output.json", "slots_required": "1", "enqueue_time": "Thu Mar  9 18:36:27 2023", "start_time": "Thu Mar  9 18:36:27 2023", "time_running": "0.009355s"}, "jobid": 52}

https://api.tst.glygen.org/job/status/?query={"jobid":52}

{"tsid": "4", "status": "died", "command": "python /app/job_submitters/structure_search.py -i /data/shared/glygen//userdata/tst/jobs/52/input.json -o /data/shared/glygen//userdata/tst/jobs/52/output.json", "slots_required": "1", "enqueue_time": "Thu Mar  9 18:36:27 2023", "start_time": "Thu Mar  9 18:36:27 2023", "end_time": "Thu Mar  9 18:36:29 2023", "time_run": "1.203917s", "error": "Motif is too big"}

"error": "Motif is too big" Can error text be "Structure is too big" 

This would also apply to substructure too. If possible error text should be "Substructure is too big" 

https://api.tst.glygen.org/job/status/?query={"jobid":53}

{"tsid": "5", "status": "died", "command": "python /app/job_submitters/structure_search.py -i /data/shared/glygen//userdata/tst/jobs/53/input.json -o /data/shared/glygen//userdata/tst/jobs/53/output.json", "slots_required": "1", "enqueue_time": "Thu Mar  9 18:43:06 2023", "start_time": "Thu Mar  9 18:43:06 2023", "end_time": "Thu Mar  9 18:43:07 2023", "time_run": "1.205191s", "error": "Motif is too big"}

**Comment by rykahsay** [comment]
I don't have control -- these error message are coming from the container.

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger , "Motif is too big"  error comes from third party container.

**Comment by sujeetvkulkarni** [comment]
replace Motif is too big with Structure is too big in the frontend.

**Comment by sujeetvkulkarni** [comment]
7d6f0ab9cebca35cf97fcb1b1398209a052f3cf3
