### ISSUE TITLE
Please verify biomarker search and list page.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1280]
Please verify biomarker search and list page and let me know if any changes are needed.

Also, please check Simple Search tab and see if we need to add an example.

https://tst.glygen.org/biomarker-search/
https://tst.glygen.org/biomarker-list/4cb9fb05cf7e461c8f5c1c0ed9ca5af5

Note: biomarker details page is not working currently.

**Comment by sujeetvkulkarni** [comment]
also details page is available for testing now.
https://tst.glygen.org/biomarker/AA4686-12

**Comment by DaniallMasood** [comment]
Looks great!

**Comment by DaniallMasood** [comment]
@sujeetvkulkarni when do you think a tst page with the biomarker api will be done? We have an NIH monthly meeting on Monday and were hoping to show something then

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood  https://glygen.ccrc.uga.edu/frontend/ is the page for biomarker portal. But it uses tst api. I can change it to use 
https://hivelab.tst.biochemistry.gwu.edu/biomarker/api/
shared by @seankim658 in #1305 but it wont work unless apis are ready and use same endpoints.

**Comment by DaniallMasood** [comment]
Sorry for the confusion on my end. This is great! I talked to Sean yesterday and he finished the rewrites and testing the API. @seankim658 please confirm here so we can continue.

Thank you @sujeetvkulkarni for all the hard work in putting this together

**Comment by sujeetvkulkarni** [comment]
let me know when to update the root url to https://hivelab.tst.biochemistry.gwu.edu/biomarker/api/, I can do it and build it.
Then https://glygen.ccrc.uga.edu/frontend/  will use https://hivelab.tst.biochemistry.gwu.edu/biomarker/api/  api.

**Comment by seankim658** [comment]
I'm just changing the endpoint URLs as suejeet mentioned in the other ticket that he referenced. @sujeetvkulkarni this should be done in an hour or so. I'll add to the other ticket when that's done.

**Comment by DaniallMasood** [comment]
Sounds great @seankim658 @sujeetvkulkarni let me know when this is done and I can test it

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood @seankim658 
I have updated the api - https://hivelab.tst.biochemistry.gwu.edu/biomarker/api/ and build is ready. Please test https://glygen.ccrc.uga.edu/frontend/.

Note:  There may be some of data, api issues that still need to be fixed.

 @seankim658 please compare/verify api query parameter, responses from 
https://glygen.ccrc.uga.edu/frontend/ and https://tst.glygen.org/ to match your query parameters, api responses.

**Comment by DaniallMasood** [comment]
@sujeetvkulkarni is it possible to remove the GlyGen tag and relate GlyGen things from the test page for now or no?

could it be replaced with this 
Biomarker Partnership Project
Biomarker Partnership is a Common Fund Data Ecosystem ([CFDE](https://commonfund.nih.gov/dataecosystem)) sponsored project to develop a knowledgebase that will organize and integrate biomarker data from different public sources. The data will be connected to contextual information to show a novel systems-level view of biomarkers.

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood yes it is possible to change the front page. I have updated header, footer, added a temporary logo (which can be changed in future).
In the header CFDE link is not there in text but there is a button next to it "Member of cfde" which takes user to same link.
For footer the l have reduced the text and CFDE link is there in text.

You can use the current changes for now and we will update them in future if required.
https://glygen.ccrc.uga.edu/frontend/

**Comment by DaniallMasood** [comment]
![image](https://github.com/glygener/glygen-issues/assets/116293652/254d7fcb-36da-40f2-a7e2-aa21dc6bfc21)
@sujeetvkulkarni just text needs to be changed where it says “proteins in glygen” to “biomarkers in the biomarker partnership data”

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood 
Done - please check.

**Comment by DaniallMasood** [comment]
@sujeetvkulkarni just a small request for underneath the biomarker simple search. If you could replace the current biomarker ID example with AN6278-1. The IDs were redone because oncomx was recurated. thank you

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood Done. Changed the biomarker ID in both simple and advanced biomarker search.

**Comment by DaniallMasood** [comment]
thank you so much @sujeetvkulkarni we should be all set for ISMB now. only thing is color but we can work on that after we come back from the conference
