### ISSUE TITLE
"unused" folder in downloads/ebi 

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1283]
There are folders in **downloads/ebi/unused** that were used according to BCO IO domains (see examples below).  This is causing my `download_summary.py` script to crash, and dead links in the BCOs.

I'm unable to move the folders back (getting permission denied error).  Is this unused folder necessary and can you move the folders back to **downloads/ebi**?

```
/data/shared/glygen/releases/data/v-2.4.1/jsondb/bcodb/GLY_000951.json
"uri": "https:/data.glygen.org/ln2downloads/ebi/2024_02_19/uniprot-proteome-sus_scrofa.nt"

/data/shared/glygen/releases/data/v-2.2.1/jsondb/bcodb/GLY_000810.json
"uri": "https:/data.glygen.org/ln2downloads/ebi/2023_07_11/uniprot-proteome-saccharomyces-cerevisiae.nt"
```

**Comment by rykahsay** [comment]
You have permission now, and can move back those folders that are used

**Comment by kmartinez834** [comment]
Thanks, done.
