### ISSUE TITLE
Biomarker Entry Page Order and Name Changes

### ISSUE THREAD

**Issue by DaniallMasood** [glygener/glygen-issues#1284]
For the entry pages, the changes discussed are fine.

The order of information can be as follows:

1. General
2. Components
3. Condition
4. Evidence

As for the label changes, only two are needed:

1. Biomarker Status -> Biomarker
2. Best Biomarker Type -> BESR Biomarker Role

**Comment by sujeetvkulkarni** [comment]
done.
