### ISSUE TITLE
Glycan downloads ready

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1285]
Glycan downloads are complete, proceed with processing glycan and proteoform datasets

FYI @ubhuiyan @katewarner @Luke-Johnson-5 @CyrusAY @jeet-vora @JingyueWu

**Comment by rykahsay** [comment]
Please start checking unreviewed/glycan_* dataset files

**Comment by rykahsay** [comment]
@ubhuiyan @kmartinez834  ... all proteoform datasets have been created. Please check

**Comment by kmartinez834** [comment]
Glycan and proteoform dataset issues have been documented as separate tickets.  Closing this issue.
