### ISSUE TITLE
Edit Virtual GlyGen-CFDE Workshop Recording

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#1286]
Please edit the virtual GlyGen-CFDE workshop. Following the similar video editing protocols before, please don't forget to put chapters and keywords.

Link: https://gwu-edu.zoom.us/rec/share/KdLbnJVVMLnfdnrcJtmfF4XxwkxYFfs9mw-RzZ-KCdPIuWzU9PBPQHXxHEwqU6sI.j5XeNNltdJSUTrsr?startTime=1714575850000

Passcode: $y#=6GW? 

FYI: @jeet-vora

**Comment by CyrusAY** [comment]
@JingyueWu Do you want the video split into three parts with respect to the three presenters?

**Comment by JingyueWu** [comment]
No. Instead of dividing it into three parts for each presenter, the final video should be presented as a single, unified whole. Thanks!

**Comment by CyrusAY** [comment]
Divided into three parts as suggested by Rene last Wednesday:

Link to videos and timestamps:
https://drive.google.com/drive/folders/15khkjzOv-W6QYQ1EbsxKdp5XAf5hu3u0?usp=share_link

**Comment by jeet-vora** [comment]
@CyrusAY Create a folder [here](https://drive.google.com/drive/u/1/folders/1W58cwJQMLygQbxt3EZCt9ALQL0v1K7eo) as per the event and date eg Virtual GlyGen and CFDE Bioinformatics May 1 2024 Workshop. Ensure all recording are stored in this folder. Also rename the edited videos, add date and name of the presenter. Let me know once done.
Share it with Rene for now - https://drive.google.com/drive/folders/15khkjzOv-W6QYQ1EbsxKdp5XAf5hu3u0?usp=share_link

**Comment by CyrusAY** [comment]
Materials uploaded at https://drive.google.com/drive/folders/1H10caJP-RVItOr4zX72f5diF4Omth90u?usp=share_link

**Comment by jeet-vora** [comment]
Done
