### ISSUE TITLE
Medline and InChi download for 2.5

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#1288]

**Comment by rykahsay** [comment]
@kmartinez834 -- shouldn't this be opened by @ubhuiyan? 


InChi downloads have been updated to produce compiled/cid2inchi.csv which affects unreviewed/glycan_sequences_inchi.csv

Please compare compiled/cid2inchi.csv and unreviewed/glycan_sequences_inchi.csv with 
/data/shared/glygen/releases/data/v-2.4.1/compiled/cid2inchi.csv and /data/shared/glygen/releases/data/v-2.4.1/reviewed/glycan_sequences_inchi.csv

**Comment by kmartinez834** [comment]
@rykahsay that's my bad - I forgot to tell her to make a ticket for you. Will make sure to document

**Comment by kmartinez834** [comment]
No issues with cid2inchi.csv and glycan_sequences_inchi.csv
