### ISSUE TITLE
All datasets ready for QC

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1299]
Please perform QC and create separate tickets for each issue you find

**Comment by CyrusAY** [comment]
Glycan datasets qc done; no issues
#1297

**Comment by katewarner** [comment]
Proteoform datasets QC completed, no issues. 
[#1303](https://github.com/glygener/glygen-issues/issues/1303)

**Comment by Luke-Johnson-5** [comment]
Protein Dataset QC Complete. Looks good.
#1243

**Comment by ubhuiyan** [comment]
Glycan Dataset QC Completed. No issues were detected.
