### ISSUE TITLE
Create new dataset glycan_biomarkers.csv

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#13]
Biomarker DB (aka OncoMX) source file now includes protein and glycan entries. Create new dataset glycan_biomarkers.csv

**Input file:**  /data/projects/glygen/downloads/biomarkerdb/current/allbiomarkers-all.csv
**Output file:** reviewed/glycan_biomarkers.csv

Follow same processing steps as #12, with the following exceptions:

**1.  Output primary field will be glytoucan_ac**

- Headers for output file:
**"glytoucan_ac"**,"biomarker_id","assessed_biomarker_entity","biomarker","best_biomarker_type","loinc_code","notes","anatomical_entity","uberon_id","do_id","do_name","assessed_entity_type","xref_key","xref_id","src_xref_key","src_xref_id"

**2. Extract only entries where "Main x-ref" starts with GTC:**
- Ex. GTC:G53972TI

**Comment by rykahsay** [comment]
done --> check

**Comment by kmartinez834** [comment]
@rykahsay can you confirm if this is the mapping file you're using for "do_id" and "do_name"?
generated/misc/doid2uberonid_mapping_v5.csv

`-rwxr-xr-x. 1 escauley glygen   703 Feb 15  2022 doid2uberonid_mapping_v5.csv`

If yes, please update permissions so I can add DOID:1319

**Comment by kmartinez834** [comment]
@rykahsay the "anatomical_entity" field should match the "uberon_id" field.  Use the misc/sample_mapping.csv file for Uberon mapping.

Currently in unreviewed/glycan_biomarkers.csv:
```
"anatomical_entity","uberon_id"
"DOID:1612 / Breast Cancer","0000178"
```

Should be:
```
"anatomical_entity","uberon_id"
"blood","0000178"
```

**Comment by kmartinez834** [comment]
👍 Dataset created, moved issues to #135 for next data release
