### ISSUE TITLE
Change "Max number of hits" label to "Max number of hits (Proteins)" in job init api

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#130]
Change - "Max number of hits" label  to "Max number of hits (Proteins)" for "num_alignments" id as per Jeet's recommendation.
https://api.tst.glygen.org/job/init?query={}
{"id": "num_alignments", "label": "Max number of hits", "value": 250}

**Comment by rykahsay** [comment]
done 
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/20584876/224201061-f520c941-d4cc-4f30-a965-52b14307ff26.png">
