### ISSUE TITLE
Biomarker data sent by backend on glycan, protein, publication, motif details api needs to be synchronized with new data model.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1304]
Biomarker data sent by backend on glycan, protein, publication, motif details api needs to be synchronized with new biomarker data/id namespace.

below is list of apis,
https://api.tst.glygen.org/glycan/detail/G17689DH
https://api.tst.glygen.org/publication/detail
https://api.tst.glygen.org/protein/detail/P14210-1/
https://api.glygen.org/motif/detail

Please check if any other data objects have biomarker data associated with it.

**Comment by rykahsay** [comment]
Please check now

**Comment by sujeetvkulkarni** [comment]
@rykahsay 
protein, glycan, publication details page biomarker data exists.
But for motif details page I have not seen  biomarker data on any page. 
Can you give me motif id with biomarker data.

**Comment by rykahsay** [comment]
Sorry -- motif data is updated now and here is an example 

<img width="1364" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/4b06107c-9f5d-400b-b44d-d7903b745d63">

**Comment by sujeetvkulkarni** [comment]
verified - https://tst.glygen.org/motif/GGM.000008
done.
