### ISSUE TITLE
Provide glycans ids for lot of expression data.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1307]
Also, expression data is displayed on publication details page, so if you have any publication ids where there is lot of expression data then, we will need them too.

**Comment by ubhuiyan** [comment]
Looks like Robel already provided that information. Did you need anything else?

**Comment by sujeetvkulkarni** [comment]
[G39188ZX](https://tst.glygen.org/glycan/G39188ZX#Expression) expression data is the id I have.

https://glygen.org/publication/PubMed/29741879#Expression for publication.
