### ISSUE TITLE
biomarker search init and details is failing.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1308]
biomarker search init:

![Screenshot 2024-05-08 at 10 29 08 AM](https://github.com/glygener/glygen-issues/assets/13891482/85e7d4da-6fd6-4a74-b3e1-5a15d9baa736)

biomarker details:
![Screenshot 2024-05-08 at 11 18 38 AM](https://github.com/glygener/glygen-issues/assets/13891482/870278bf-43bf-4c2d-a2d2-5517c41870f7)

**Comment by rykahsay** [comment]
Please try it now

**Comment by sujeetvkulkarni** [comment]
done. closing.
