### ISSUE TITLE
Add UnicarbKB tissue mapping & expression to glycan detail API

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#131]
_This is optional for 2.0 and can be implemented in 2.1 if it will delay release_

None of the expression data from UnicarbKB appears in the glycan detail APIs.  

Will add more details...

**Comment by kmartinez834** [comment]
👍 Expression info from UniCarbKB is present on tst API

❓ @jeet-vora @ReneRanzinger @rykahsay The `tissue.uberon` key is accepting ontologies other than UBERON...
--> Does this cause any problems with CFDE?  
--> Can we change `"uberon"` key to something else ("ontology_id" or "id")?

ex. https://api.tst.glygen.org/glycan/detail/G62765YT/
``` json
{
      "uniprot_canonical_ac": "Q00960-1",
      "start_pos": 348,
      "end_pos": 348,
      "residue": "Asn",
      "tissue": {
        "name": "synaptosomes",
        "uberon": "OMIT:0014437",
        "url": "http://purl.obolibrary.org/obo/OMIT:0014437"
      },
```

**Comment by ReneRanzinger** [comment]
@sujeetvkulkarni please test glycan "G62765YT" and see if it breaks.

**Comment by kmartinez834** [comment]
Tickets opened:
#141 
#142 
#143
