### ISSUE TITLE
New dataset: human_proteoform_ml_ready_pdc_ccrc.csv

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1310]
**Source file:**
compiled/pdc_ccrcc_preprocessed.csv

**Output file:**
human_proteoform_ml_ready_pdc_ccrc.csv

**Instructions:**
Copy directly from compiled file, no changes needed

**Comment by rykahsay** [comment]
Done, please note the file name change under compiled:

```
compiled/pdc_ccrcc_preprocessed.csv --> compiled/human_proteoform_ml_ready_pdc_ccrc.csv
```
