### ISSUE TITLE
New dataset: human_proteoform_ml_ready_diabetes_glycomic.csv

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1311]
**Source file:**
compiled/finrisk_preprocessed.csv.csv

**Output file:**
human_proteoform_ml_ready_diabetes_glycomic.csv

**Instructions:**
Copy directly from compiled file, no changes needed

**Comment by rykahsay** [comment]
Done, please note that I have changed the file name under compiled 

```
compiled/finrisk_preprocessed.csv --> compiled/human_proteoform_ml_ready_diabetes_glycomic.csv
```
