### ISSUE TITLE
Start testing 2.5 on tst

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1312]
Please start testing tst.glygen.org and api.tst.glygen.org from the data/API perspective

**Comment by rykahsay** [comment]
@ubhuiyan @sujeetvkulkarni  ... here is a GlyTouCan example with too many expression rows:

<img width="1329" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/43bcff12-5f3c-4fe4-ba2c-6cfca2a2a2d1">

**Comment by katewarner** [comment]
@rykahsay I've finished testing the tst.glygen.org and api.tst.glygen.org and made tickets for any issues I found. 

I checked: 

- All the links on the header and footer of the homepage 
- Protein, Glycan and Biomarker Simple Search Pages and Advanced Search Pages (All searches, examples, text and links)
- All the different search types on the home page such as Supersearch, blast, list of motifs etc.  (All searches, examples, and links)
- List pages (Links, pages, filters, download)
- Protein and Glycan detail pages (All data sections and links)
- API Page (All APIs, examples and Links)

**Comment by Luke-Johnson-5** [comment]
@rykahsay Finished on TST. All Issues I found were reported.

Issues found
#1324 
#1347 

Checked:
- All things listed on detailed testing document.
- API
- All searches
- Protein and Glycan info pages
- Various other utilities (Structure browser, list of motifs, etc.)
-

**Comment by katewarner** [comment]
I found another problem which I think is a front end issue so I've assigned to Sujeet, and assigned myself back onto this ticket: 

[#1358 ](https://github.com/glygener/glygen-issues/issues/1358)

**Comment by sujeetvkulkarni** [comment]
Done testing, logged issues.
