### ISSUE TITLE
Biomarker section download failing

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1315]
https://api.tst.glygen.org/data/section_download?query=
{"id":"AA4686-11","download_type":"biomarker_section","section":"component_protein","format":"csv","compressed":false}

response :
{"error_list": {"error_code": "missing-section-field"}}

**Comment by rykahsay** [comment]
You need to change your query a little as follows:

```
$ cat tests/examples/data/section_download.biomarker.biomarker_component.json

{"id":"AA4686-11","download_type":"biomarker_section","section":"biomarker_component","format":"csv","compressed":false}
```

```
$ http POST :8082/data/section_download <  tests/examples/data/section_download.biomarker.biomarker_component.json

HTTP/1.1 200 OK
Connection: close
Content-Length: 136
Content-Type: text/csv; charset=utf-8
Date: Sat, 11 May 2024 10:12:36 GMT
Server: gunicorn

"Biomarker Entity ID","Biomarker Entity Type","Biomarker","Biomarker Entity"
"P05231-1","protein","increased IL6 level","Interleukin-6"
```

**Comment by sujeetvkulkarni** [comment]
@rykahsay 
earlier user could download separate protein (section: "component_protein") and glycan (section: "component_glycan") tables. Now we will only support only one download "section":"biomarker_component"?

**Comment by rykahsay** [comment]
I don't see a problem, I am giving entity type and one can sort by that field
