### ISSUE TITLE
Consolidating src_xref_key to point to data.glygen.org

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1316]
From now on, you will need to edit the the file "generated/misc/ds2bco.json" to associate BCO ID values for src_xref_id. I have tried to populate this file -- please check.

As a result, the following rows have been removed from "generated/misc/xref_info.csv" 

```
glycan_xref_harvard,GlyGen,https://data.glygen.org/GLY_000142,
glycan_xref_unicarbkb_comp_citations,UniCarbKB,https://data.glygen.org/GLY_000285,
glycan_xref_unicarbkb_comp_species,UniCarbKB,https://data.glygen.org/GLY_000341,
protein_xref_biomarkerdb,GlyGen,https://data.glygen.org/GLY_000625,
glycan_xref_biomarkerdb,GlyGen,https://data.glygen.org/GLY_000737,
glycan_xref_oglcnacatlas,GlyGen,https://data.glygen.org/%s,
glycan_xref_oglcnacdb,GlyGen,https://data.glygen.org/%s,
glycan_xref_gorniklab,GlyGen,https://data.glygen.org/%s,GLY_000960
```

The following rows, which are already in "generated/misc/xref_info.csv", will cover the above rows
```
protein_xref_glygen_ds,GlyGen,https://data.glygen.org/%s,GLY_000490|GLYGDS000489|GLYGDS000487
glycan_xref_glygen_ds,GlyGen,https://data.glygen.org/%s,GLY_000335|GLY_000633|GLY_000711
```

**Comment by kmartinez834** [comment]
Comment removed

**Comment by kmartinez834** [comment]
In glycan_species.csv, we are using "glycan_xref_gnome".  
```
$ grep G05049YU.*gnome unreviewed/glycan_species.csv
"G05049YU","9031","Gallus gallus","Subsumption","GNOme","G27919IH","","glycan_xref_gnome","G27919IH","False"
```
In xref_info.csv, the "xref_badge" is "GNOme", but on the front end and API, it appears as "Subsumption."  Where is "Subsumption" coming from, and should we update this row of xref_info.csv?

```
xref_key,xref_badge,xref_url,xref_id_examples
glycan_xref_gnome,GNOme,https://www.glygen.org/glycan/%s,G84891DZ|G57710SU|G84891DZ
```

https://api.tst.glygen.org/glycan/detail/G05049YU
``` json
"species": [
    {
      "taxid": 9031,
      "name": "Gallus gallus",
      "annotation_category": "subsumption",
      "evidence": [
        {
          "database": "Subsumption",
          "id": "G27919IH",
          "url": "https://www.glygen.org/glycan/G27919IH"
        },
```

**Comment by kmartinez834** [comment]
@rykahsay the Unicarbkb issue above affects more datasets than I initially thought.  I'm moving to a separate issue and will address the other datasets as well

**Comment by rykahsay** [comment]
If I remember correctly, I think it was Rene's idea to replace "GNome" by "Subsumption" ... please bring this up in our meeting tomorrow

<img width="1211" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/7979ca87-a860-4603-9edb-e17f0a2d9474">

**Comment by kmartinez834** [comment]
I think I remember that as well, could we just update xref_info.csv instead of hard coding the replacement?

**Comment by kmartinez834** [comment]
**human_proteoform_glycosylation_sites_harvard.csv**
- Remove rows where "xref_key" and "src_xref_key" are both "protein_xref_glygen_ds"
```
"uniprotkb_canonical_ac","glycosylation_site_uniprotkb","amino_acid","saccharide","glycosylation_type","xref_key","xref_id","src_xref_key","src_xref_id","composition","n_sequon","n_sequon_type","start_pos","end_pos","start_aa","end_aa","site_seq"
"Q6ZSR9-1","150","Ser","G70994MS","O-linked","protein_xref_glygen_ds","GLY_000142","protein_xref_glygen_ds","GLY_000142","HexNAz2Si(1)","","","150","150","Ser","Ser","S"
```

**human_proteoform_glycosylation_sites_tyr_o_linked.csv**
- Remove rows where "xref_key" and "src_xref_key" are both "protein_xref_glygen_ds"
```
"uniprotkb_canonical_ac","glycosylation_site_uniprotkb","amino_acid","saccharide","glycosylation_type","xref_key","xref_id","src_xref_key","src_xref_id","start_pos","end_pos","start_aa","end_aa","site_seq"
"O14672-1","37","Tyr","","O-linked","protein_xref_glygen_ds","GLY_000268","protein_xref_glygen_ds","GLY_000268","37","37","Tyr","Tyr","Y"
```

**protein_disease_idmap.csv**
- Currently contains GLYGDS bco ids, the source compiled files need to be updated.
```
"xref_id","xref_key","mondo_id","do_id","xref_map_src","do_map_src"
"GLYGDS000489","protein_xref_glygen_ds","0005091","2945","mondo","do"
"GLYGDS000487","protein_xref_glygen_ds","0005231","1883","mondo","do"
"GLYGDS000487","protein_xref_glygen_ds","0005155","5082","mondo","do"
"GLYGDS000487","protein_xref_glygen_ds","0007256","684","mondo","do"
```

**Comment by rykahsay** [comment]
These have been fixed:

- human_proteoform_glycosylation_sites_harvard.csv
- human_proteoform_glycosylation_sites_tyr_o_linked.csv

I have modified BCO IDs in compiled/*protein_disease.csv files, and here is the diff in protein_disease_idmap now:

```
$ diff reviewed/protein_disease_idmap.csv unreviewed/protein_disease_idmap.csv
10193,10196c10193,10196
< "GLYGDS000489","protein_xref_glygen_ds","0005091","2945","mondo","do"
< "GLYGDS000487","protein_xref_glygen_ds","0005231","1883","mondo","do"
< "GLYGDS000487","protein_xref_glygen_ds","0005155","5082","mondo","do"
< "GLYGDS000487","protein_xref_glygen_ds","0007256","684","mondo","do"
---
> "GLY_000489","protein_xref_glygen_ds","0005091","2945","mondo","do"
> "GLY_000487","protein_xref_glygen_ds","0005231","1883","mondo","do"
> "GLY_000487","protein_xref_glygen_ds","0005155","5082","mondo","do"
> "GLY_000487","protein_xref_glygen_ds","0007256","684","mondo","do"
```

**Comment by kmartinez834** [comment]
@ubhuiyan please review the last two comments regarding human_proteoform_glycosylation_sites_harvard.csv, human_proteoform_glycosylation_sites_tyr_o_linked.csv and protein_disease_idmap.csv

Let me know if you have questions

**Comment by ubhuiyan** [comment]
I have checked, and the corresponding changes look good to me.
