### ISSUE TITLE
2.5 TST - Biomarker disease and Biomarker Type are not working

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1319]
I found some issues with the Biomarker searches within the Protein advanced search.

1. Searching for Biomarker disease using the shown example “liver cancer” results in error “No results found”. 
2. The Biomarker type drop-down only displays "role" and doesn’t display any of the Biomarker types i.e. "Diagnostic", "Monitoring" etc.

**Comment by katewarner** [comment]
@rykahsay I just found that the same errors occur with Biomarker searches within the Glycan advanced search as well.

**Comment by rykahsay** [comment]
Please try now

**Comment by katewarner** [comment]
The issues above are fixed but I noticed some other problems. 

1. When you're typing in the biomarker disease the list of (autocomplete) suggestions don't appear like they do on the website i.e.: 
![image](https://github.com/glygener/glygen-issues/assets/161866639/f25263a9-84b8-4797-adc9-b1101b7039ac)

2. The Biomarker type drop-down displays 3 more items than on 2.4 (i.e. "response", "risk" and "safety"), and when you try to search for them they return a search error message. 
![image](https://github.com/glygener/glygen-issues/assets/161866639/6ae64d69-96fe-481a-ba21-6de73e233bb8)

**Comment by rykahsay** [comment]
On first issue: 
  " ... don't appear like they do on the website i.e.:" --> which website?

Cannot reproduce the second issue -- I see same number of roles on both 2.4 (prd) and 2.5 (tst)

**Comment by katewarner** [comment]
@rykahsay 

> ... don't appear like they do on the website i.e.:" --> which website?

Sorry I meant 2.4 prd

> Cannot reproduce the second issue -- I see same number of roles on both 2.4 (prd) and 2.5 (tst)

That's strange because I've tried it on different browsers and still get the same issue. For me it doesn't have "response", "risk" and "safety" in the drop-down list on 2.4 prd (see below):

![image](https://github.com/glygener/glygen-issues/assets/161866639/7f632eca-cd65-462e-b1ae-0f519a40607f)

**Comment by rykahsay** [comment]
Yes, there seems to be a problem. Here are some commands you want to do next time to drill deeper

### headers of  /data/shared/glygen/releases/data/v-2.4.1/reviewed/glycan_biomarkers.csv
```
$ cat /data/shared/glygen/releases/data/v-2.4.1/reviewed/glycan_biomarkers.csv | head -1
"glytoucan_ac","biomarker_id","assessed_biomarker_entity","biomarker","best_biomarker_type","loinc_code","notes","literature_evidence","anatomical_entity","uberon_id","do_id","do_name","assessed_entity_type","xref_key","xref_id","src_xref_key","src_xref_id"
```

### unique values in 5th column of  /data/shared/glygen/releases/data/v-2.4.1/reviewed/glycan_biomarkers.csv
```
$ cat /data/shared/glygen/releases/data/v-2.4.1/reviewed/glycan_biomarkers.csv | awk -F"\",\"" '{print $5}' |sort -u
best_biomarker_type
diagnostic
monitoring
predictive
prognostic
```

### headers of  /data/shared/glygen/releases/data/v-2.5.1/reviewed/glycan_biomarkers.csv
```
$ cat /data/shared/glygen/releases/data/v-2.5.1/reviewed/glycan_biomarkers.csv | head -1
"glytoucan_ac","biomarker_id","assessed_biomarker_entity","biomarker","best_biomarker_type","loinc_code","notes","literature_evidence","anatomical_entity","uberon_id","do_id","do_name","assessed_entity_type","xref_key","xref_id","src_xref_key","src_xref_id"
```

 ### unique values in 5th column of /data/shared/glygen/releases/data/v-2.4.1/reviewed/glycan_biomarkers.csv
```
$ cat /data/shared/glygen/releases/data/v-2.5.1/reviewed/glycan_biomarkers.csv | awk -F"\",\"" '{print $5}' |sort -u
best_biomarker_role
diagnostic
monitoring
monitoring;prognostic
predictive
prognostic
risk
```

**Comment by rykahsay** [comment]
It is fixed now, please check

<img width="695" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/6b232dbb-b5ea-46b0-bc08-8a3ee521a7d6">

**Comment by katewarner** [comment]
The issues are fixed, and I copied the linux commands for future reference. Thank you very much.
