### ISSUE TITLE
Can we add gene name to the in the blast result response per proteins.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#132]
Can we add gene name for protein results in blast search as per Jeet's recommendation. 

https://api.tst.glygen.org/job/results/?query={"jobid":68}

details		{10}
	species		{3}
tax_id	:	9606
name	:	Homo sapiens
common_name	:	Human
protein_name	:	Pyruvate kinase PKLR
uniprot_id	:	KPYR_HUMAN
	ptm_annotation		[0]
	glycation		[0]
	snv		[8]
	site_annotation		[2]
	glycosylation		[1]
	mutagenesis		[0]
	phosphorylation

**Comment by rykahsay** [comment]
<img width="701" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/1abc2043-0d2c-414f-a0a3-87ddfade6ce7">

**Comment by sujeetvkulkarni** [comment]
c3340ba89fd0e2e10469249556a60ebf3da78927
