### ISSUE TITLE
Does biomarkers with assessed ids as glycans have LOINC Code values in any of them, should we hide that column for glycans.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1320]
https://tst.glygen.org/biomarker/AN4074-1

![Screenshot 2024-05-14 at 10 37 58 AM](https://github.com/glygener/glygen-issues/assets/13891482/e0a0f53c-316a-43a3-8135-6716ad145d8c)

**Comment by rykahsay** [comment]
Not in the current input data we get from the biomarkers team

**Comment by sujeetvkulkarni** [comment]
Hiding the LOINC Code column for glycan table as there is no data.

**Comment by sujeetvkulkarni** [comment]
1e78481031b380aabc2b7253270113e9e64f8c4f
