### ISSUE TITLE
Add Kate to all GlyGen BCOs

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#1323]
@katewarner needs to be added to all the existing BCOs in GlyGen to get access to edit.

  {
                "name": "Kate Warner",
                "affiliation": "The George Washington University",
                "contribution": [
                    "createdBy"
                ],
                "email": "k.warner1@gwu.edu"
            }

**Comment by rykahsay** [comment]
Done, please check

**Comment by jeet-vora** [comment]
No issues
