### ISSUE TITLE
Glycan Substructure Search Example Queries Not Working - TST

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#1324]
Glycan substructure example queries are not working for both GlycoCT and WURCS on tst.glygen.org . Not able to identify where this is in the api however, what is being returned likely tells me this is a backend issue.

![image](https://github.com/glygener/glygen-issues/assets/144174552/422f6e38-848b-482c-a62c-9c0451c41fcf)
![image](https://github.com/glygener/glygen-issues/assets/144174552/4a0aaf59-c178-435e-afcf-941c21f191b2)

**Comment by Luke-Johnson-5** [comment]
Same issue occurring with Structure Search example searches.

![image](https://github.com/glygener/glygen-issues/assets/144174552/628c76b8-d9d6-474b-ba3d-1a6219cf58d1)
![image](https://github.com/glygener/glygen-issues/assets/144174552/c67c087d-ae52-4f76-9e4b-671fad5c238e)

**Comment by rykahsay** [comment]
check now

**Comment by Luke-Johnson-5** [comment]
working
