### ISSUE TITLE
Glycan and protein biomarker components have the same info

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1328]
@DaniallMasood  ... why do the protein components have the same "Biomarker" and "Assessed Biomarker Entity" values as the glycan components?

<img width="1378" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/441ee8c6-d30e-4f47-9e9e-2726644ef769">

<img width="1331" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/08d9c2e6-6aec-4183-9372-505cb82ef576">

**Comment by kmartinez834** [comment]
@DaniallMasood Should we push the biomarker data as-is to production, or are you making additional changes to the file on github?

**Comment by DaniallMasood** [comment]
I can find the proteins and update that data but glycans will be tough for me update

**Comment by DaniallMasood** [comment]
https://github.com/GW-HIVE/biomarker-glygen-conversion/blob/main/allbiomarker-final.tsv

here is the changed file that addresses the issue here
