### ISSUE TITLE
Missing Reactome datasets

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1329]
The following organisms are not listed in the datasets-masterlist.json for the respective datasets.  Was this intentional or an oversight?

`*_protein_xref_reactome.csv`
- yeast

`*_protein_citations_reactome.csv`
- mouse
- rat
- yeast
- dicty
- pig

`*_protein_pathways_reactome.csv`
- yeast

**Comment by rykahsay** [comment]
Dataset files yeast_protein_xref_reactome.csv and yeast_protein_pathways_reactome.csv have been created, please check.

The dataset files *_protein_citations_reactome.csv are created from *_protein_reactions_reactome and *_protein_xref_reactome using "pathway_id" as an anchor. For those species you listed, *_protein_reactions_reactome does not contain pathway_id that connect to *_protein_xref_reactome

**Comment by kmartinez834** [comment]
No issues with the yeast datasets.

One more missing file though --> 
GLY_000925,pig_protein_ntdata.nt,ERROR,in_bco

I see pig_protein_ntdata.nt has a usage log log from April 11, but there is no file with this name in the generated/datasets/unreviewed or generated/datasets/reviewed folders

**Comment by rykahsay** [comment]
Please check now:

```
$ python3 check-bco2filename-mapping.py  | grep ERROR

NO-BCO,chicken_protein_glycohydrolase.csv,ERROR,in_fs
NO-BCO,chicken_proteoform_glycosylation_sites_literature.csv,ERROR,in_fs
NO-BCO,chicken_protein_submittednames.csv,ERROR,in_fs
NO-BCO,chicken_proteoform_glycosylation_sites_pdb.csv,ERROR,in_fs
NO-BCO,chicken_protein_xref_cdd.csv,ERROR,in_fs
NO-BCO,chicken_protein_citations_refseq.csv,ERROR,in_fs
NO-BCO,chicken_protein_recnames.csv,ERROR,in_fs
NO-BCO,chicken_proteoform_citations_glycosylation_sites_uniprotkb.csv,ERROR,in_fs
NO-BCO,chicken_protein_reactions_reactome.csv,ERROR,in_fs
NO-BCO,chicken_protein_xref_geneid.csv,ERROR,in_fs
NO-BCO,chicken_proteoform_phosphorylation_sites_uniprotkb.csv,ERROR,in_fs
NO-BCO,chicken_protein_reactions_rhea.csv,ERROR,in_fs
NO-BCO,chicken_proteoform_glycosylation_sites_unicarbkb.csv,ERROR,in_fs
```

**Comment by kmartinez834** [comment]
@ubhuiyan assigning this to you.  Read the last comment made by Robel and myself - please verify that the missing file was created and is not causing a BCO ERROR flag

**Comment by ubhuiyan** [comment]
@rykahsay it appears `pig_protein_ntdata.nt` is present within both the reviewed and unreviewed folders. I do not think this file is creating the error.

**Comment by rykahsay** [comment]
Yes, I created it after Karina reported it as missing
