### ISSUE TITLE
Biomarker example search not working on TST

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1330]
On the Biomarker search page (https://tst.glygen.org/biomarker-search/), selecting biomarker from the drop down then using the example search "AA4691-4" does not return any results. However, other biomarkers such as "AA4686-1" work with this query so maybe change the example.

![image](https://github.com/glygener/glygen-issues/assets/161866639/d68eaa38-79ae-42a5-986a-0245d0975d68)

**Comment by rykahsay** [comment]
@sujeetvkulkarni  ... why is the frontend failing when the API (shown below) is giving results?

```
$ cat  tests/examples/biomarker/search_simple.json
{"term":"AA4686-4","term_category":"biomarker"}

$ http POST :8082/biomarker/search_simple/ < tests/examples/biomarker/search_simple.json
HTTP/1.1 200 OK
Connection: close
Content-Length: 127
Content-Type: application/json
Date: Fri, 17 May 2024 13:12:53 GMT
Server: gunicorn

{
    "list_id": "a16f3fa42572b52549dc657d475e9283",
    "query": {
        "term": "AA4686-4",
        "term_category": "biomarker"
    },
    "resultcount": 1
}
```

**Comment by sujeetvkulkarni** [comment]
with AA4691-4 biomarker simple search fails but is not listed as example.
Current example is AA4686-1 which works.
Also, AA4686-4 listed above by @rykahsay works fine.
So closing the issue.
