### ISSUE TITLE
Image_svg not working on 2.5 tst API

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1340]
The /glycan/image_svg/{glytoucan_ac}/ isn't working on the 2.5 tst API. I tried the example and a few other glytoucan acs and got the same error message:

![image](https://github.com/glygener/glygen-issues/assets/161866639/69703bef-2caf-41fc-8f60-1c2d9a4d46a7)

**Comment by rykahsay** [comment]
Let's ignore this problem --- it also exists in prd. It is Swagger not able to display svg ....

**Comment by katewarner** [comment]
Okay
