### ISSUE TITLE
Yamada's review of Motifs

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1343]
Hi Nathan,

Yamada reviewed your Motif webpage and found a few issues (listed in the attached file):
•	1a – d are related to spelling errors in motif names or missing motif names. 
•	2a – e are related to incorrect WURCS encoding for sulfate and phosphate

Please have a look and let us know what you think. 

Best,
  René

[Yamadas comments regarding Motifs.docx](https://github.com/glygener/glygen-issues/files/15379052/Yamadas.comments.regarding.Motifs.docx)

**Comment by ReneRanzinger** [comment]
Hi Rene, Yamada, Kiyoko,

First, thanks for taking a good look at the motifs.

All of your comments are on point.

Unfortunately, they are all a consequence of integrating others' motif
collections that have their own errors and issues.

The "GM" collection represents the union of all motif collections by
motif GlyTouCan accession (so any errors in one of the collections
propagate to the union entry). The "Same As" property can help you see
the entries that contribute names, alignment types, etc.

The GlyGen motifs "GGM" collection has been extensively hand-curated and
repaired by me where I can. None of the issues you identified touch the
GlyGen motifs collection.

I can correct others' collections, but then they are no longer theirs
(if they still exist). Sometimes I can use the other entries as I try to
understand how to correct or add motifs to the GlyGen collection, but
there is a lot of chaff and minor differences that are not very helpful.

Most of these name / WURCS problems are from GlyDin - Cummings it kinda
looks like they had an undergraduate do OCR for the names (or bad
copy-and-paste?) GlyDin - Cermav also seems to be a source of these. The
30-sulfo cases are interesting, I think these are probably 3' not 3O, at
least by pattern matching with other collections' names.

Should I edit others' collections? Or maybe just delete the bad entry
from the collection with a note on the collection page? I don't really
feel like I should be responsible for curation of others' data, per se.
I can and do stand by the GGM collection as I feel like I'm responsible
for its content.

Cheers!

- n

**Comment by ReneRanzinger** [comment]
Hi Nathan,

 

Sorry for the delayed response.  Rene reminded me of this.

I understand your dilemma.  Perhaps without editing the original data, in order to indicate the fact that we are aware of discrepancies, would it be possible to include a comment or footnote of some kind?  At least then mistaken or inconsistent data would (hopefully) not get propagated, or at least made clearer.

 

I wanted to discuss this at the GlySpace meeting actually, to see if there might be a way for the alliance to form a Motif List working group or something of some kind, to once and for all create a “standardized” list of motifs that is consistent throughout the three portals.  I hope I can chat with Rene, Mike and Frederique at the MIRAGE meeting to discuss the best way forward.

 

Thanks for all your work on this!

 

Kiyoko

**Comment by edwardsnj** [comment]
This was discussed in the GlySpace meeting.
