### ISSUE TITLE
Floating Numbers in the https://tst.glygen.org/

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1345]
![Screenshot 2024-05-20 at 12 44 16 PM](https://github.com/glygener/glygen-issues/assets/90285310/fb52d1bb-2d27-4ac6-a02c-a5dfd3735fcc)

**Comment by rykahsay** [comment]
Next time, please use your judgement to differentiate frontend issues from backend issues. This is a frontend issue and I am assigning it to @sujeetvkulkarni .

@kmartinez834  ... looks like many of the new team members are not being trained to differentiate frontend issues from backend issues, or do not know they have to report frontend issues to Sujeet. Can you please add that in the training documents?

**Comment by sujeetvkulkarni** [comment]
@ubhuiyan can you please provide id?

**Comment by ubhuiyan** [comment]
@sujeetvkulkarni Glycan ID: G49108TO

**Comment by sujeetvkulkarni** [comment]
4d8f063d805ebee4e0b82897bf0d7bda5d6702b5

**Comment by sujeetvkulkarni** [comment]
@ubhuiyan Fixed on test server. please verify now.

**Comment by ubhuiyan** [comment]
@sujeetvkulkarni Looks good!
