### ISSUE TITLE
Example search for /biomarker/detail/{biomarker_id}/ on 2.5 TST API not working

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1346]
The "Try it out" example search for /biomarker/detail/{biomarker_id}/ doesn't work 

The default value (A0001) doesn't match the example value (AA4686-1) (see below), and A0001 was a biomarker ID for a human protein biomarker in the last release (human_protein_biomarkers.csv) but it is not a biomarker ID for the 2.5 release. If the default value in the example search is changed to AA4686-1 then it works.

![image](https://github.com/glygener/glygen-issues/assets/161866639/5a01c9d3-69a3-47a6-a721-242838664249)

**Comment by rykahsay** [comment]
Fixed, please check

**Comment by katewarner** [comment]
Thank you. It's working now
