### ISSUE TITLE
Glycan Sandbox not able to see entire info tables online.

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#1347]
In the glycan sandbox you are unable to see the entire table online for the Residues, Enzymes and, Related Glycans. There is no way to scroll over and see these. 

![image](https://github.com/glygener/glygen-issues/assets/144174552/841696fa-f1c5-4ccb-b4be-efa12f388b96)

**Comment by rykahsay** [comment]
@Luke-Johnson-5  ... this seems to be a frontend issue ... I am assigning it to @sujeetvkulkarni. Next time, use your judgement to distinguish frontend issues from backend issues

**Comment by sujeetvkulkarni** [comment]
assigning the issue to @edwardsnj

**Comment by edwardsnj** [comment]
This is a will-not-fix at this time - the whole site needs a redesign - I have someone coming onboard that should be able to make a dent in the many issues, but not until the beginning of July-ish.

**Comment by Luke-Johnson-5** [comment]
Sounds good @edwardsnj I will close this ticket for now then.
