### ISSUE TITLE
Example search for /biomarker/search/ on 2.5 TST API not working

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1350]
The example search for /biomarker/search/ on 2.5 TST API is not working, it produces an empty "list_id"

It looks like the problem is an incorrect publication id in the example search. It's currently:

"publication_id": "32234467" 

But this publication isn't associated with prostrate cancer for this biomarker. If you change the publication id to 10914713, 32479790 or 32369209 then it retrieves a list_id, i.e. the example search would look like this:

{
  "biomarker_id": "AA4686-1",
  "biomarker": "increased IL6 level",
  "biomarker_entity_name": "Interleukin-6",
  "biomarker_entity_id": "P05231-1",
  "biomarker_entity_type": "protein",
  "specimen_name": "blood",
  "specimen_id": "0000178",
  "specimen_loinc_code": "26881-3",
  "best_biomarker_role": "prognostic",
  "condition_id": "DOID:10283",
  "condition_name": "prostate cancer",
  "publication_id": "10914713"
}

**Comment by rykahsay** [comment]
Thanks ... very helpful. I have tried to fix it now, please check

**Comment by katewarner** [comment]
That's fixed. Thank you again
