### ISSUE TITLE
Data Portal All records tab duplicate entires for Glycan Xrefs datasets

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#1353]
On **data.tst.glygen.org**

The 'All records' tab is blank for all the datasets.
`https://data.tst.glygen.org/GLY_000001`

![image](https://github.com/glygener/glygen-issues/assets/25825266/61d96956-7e26-47a5-bb13-7913714822b5)

on **data.glygen.org**

The 'All records' tab for the dataset on data.glygen.org for some Glycan Xrefs datasets is showing duplicate entries.
For eg - `https://data.glygen.org/GLY_000304`, `https://data.glygen.org/GLY_000305`

![image](https://github.com/glygener/glygen-issues/assets/25825266/bf472c89-021a-4510-a079-6c313492efca)

![image](https://github.com/glygener/glygen-issues/assets/25825266/efbf37f9-838b-416d-847c-56ccbba1b93e)

**Comment by rykahsay** [comment]
data.tst.glygen.org was not ready when you tested this ... have a look the ticket I created #1364 today

**Comment by jeet-vora** [comment]
The above duplication problem still persists.
@ubhuiyan @katewarner Please add the issue when testing for 2.7

**Comment by ubhuiyan** [comment]
I am no longer seeing duplicate entries for these datasets: 

![Screenshot 2024-12-05 at 1 31 39 PM](https://github.com/user-attachments/assets/f6e35adb-f05d-48e8-9d18-8989187675a8)
![Screenshot 2024-12-05 at 1 33 47 PM](https://github.com/user-attachments/assets/0c888b11-df1d-41f5-9415-fd641fed9bd1)

Therefore, this ticket will be closed.
