### ISSUE TITLE
Integrating Alphafold structures

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1355]
Explore integrating Alphafold cross-referencing and 3D structures of proteins not in PDB

**Comment by Luke-Johnson-5** [comment]
Alphafold 3 server is very interesting and maybe something for the future. https://golgi.sandbox.google.com/ 

However, at this time it is still in the beta and alphafold 3 is not open source... with a current limit of 20 queries per day.

**Comment by katewarner** [comment]
@Luke-Johnson-5 it does look interesting, and I can see it has a glycan example! - https://golgi.sandbox.google.com/example/examplefold_pdb_7bbv

Thanks for the heads up. Hopefully they'll make it open source soon so we can use it.

**Comment by jeet-vora** [comment]
@pkay47 

We will need your help in integrating Alphafold structures. Can you try to find answers to the questions. Kate and I will be working with you.

- [ ] What files does UniProt import to show Alphafold structures - PDB or mmCIF?
- [ ] Are there any cases where there is more than one predicted structure?
- [ ] Are Alphafold structures present for all glygen organisms

**Comment by pv47** [comment]
@jeet-vora  Uniprot uses alphafold api https://alphafold.ebi.ac.uk/api/prediction/<uniprot_accession> & uses the cif url in the response to display structures.

eg: https://alphafold.ebi.ac.uk/api/prediction/P05067 ; Response also has info like version, pdburl for structure in pdb format, etc 

 AlphaFoldDB xrefs is available for 9 organisms. No xrefs for viruses.

**Comment by rykahsay** [comment]
@katewarner ... I would expect the last comment from @pkay47  to trigger the actions to create *_protein_xref_alphafold.csv dataset files which involves the following other tasks (I have done them for now and I am writing this FYI)

Edit misc/xref_info.csv
```
$ head  generated/misc/xref_info.csv
xref_key,xref_badge,xref_url,xref_id_examples
protein_xref_alphafolddb,AlphaFoldDB,https://www.uniprot.org/uniprotkb/%s/entry#structure,X6RLV5
```

Edit mis/dataset-masterlist.json
```
{
        "name": "xref_alphafolddb",
        "format": "csv",
        "primaryfield": "uniprotkb_canonical_ac",
        "target_objects": [
            "protein"
        ],
        "integration_status": {
            "status": "integrate_all",
            "excludelist": []
        },
        "categories": {
            "molecule": "protein",
            "species": [
                "human",
                "mouse",
                "rat",
                "fruitfly",
                "yeast",
                "dicty",
                "pig",
                "chicken",
                "arabidopsis"
            ]
        }
    }
```
And creating me a separate ticket to make these new datasets

**Comment by katewarner** [comment]
@rykahsay Sorry about that. Thank you for creating the dataset and the info for next time. 

I had a look at the dataset and spoke to Jeet. It looks like the dataset maps the canonical protein Alphafold structure to the canonical protein and to all the isoforms in the GlyGen entry e.g. Q9Y2R9-1 is mapped to it's isoforms:

```
"uniprotkb_canonical_ac","xref_key","xref_id","xref_label"
"Q9Y2R9-1","protein_xref_alphafolddb","J3KSV8",""
"Q9Y2R9-1","protein_xref_alphafolddb","J3QLS3",""
"Q9Y2R9-1","protein_xref_alphafolddb","J3QKW2",""
"Q9Y2R9-1","protein_xref_alphafolddb","Q9Y2R9",""
```

But they have very different sequences (https://glygen.org/alignment/Q9Y2R9-1/isoformset.uniprotkb) and they have their own unique Alphafold structures e.g. https://alphafold.ebi.ac.uk/entry/J3KSV8. So we think that the sequences should map to their own Alphafold structure (when available) and the dataset would look as below. On the Frontend, only the canonical sequence Alphafold structure should be displayed on the protein details page, and the Alphafold structures for the isoforms will be available in the xref section.  

```
"uniprotkb_canonical_ac","xref_key","xref_id","xref_label"
"J3KSV8-1","protein_xref_alphafolddb","J3KSV8",""
"J3QLS3-1","protein_xref_alphafolddb","J3QLS3",""
"J3QKW2-1","protein_xref_alphafolddb","J3QKW2",""
"Q9Y2R9-1","protein_xref_alphafolddb","Q9Y2R9",""
```

**Comment by katewarner** [comment]
Apologies. I'll close the ticket

**Comment by katewarner** [comment]
Opened the ticket again in case this needs to be passed on to Sujeet

**Comment by rykahsay** [comment]
Please close this, there is another ticket

**Comment by katewarner** [comment]
Okay done
