### ISSUE TITLE
Database Stats for HCV on tst homepage incorrect

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1358]
The homepage on the tst 2.5 is only showing data for HCV-H77 as HCV:

![image](https://github.com/glygener/glygen-issues/assets/161866639/a4360c9e-44ba-4d19-90eb-3ea25194fce2)
@ReneRanzinger please correct me if I'm wrong, but I think in one of the general meetings we decided to separate the different entries in the statistic section. So there should be three HCV stats (info from misc/species_info.csv): 

1. **HCV** = 3052230,,Hepacivirus C,HCV,HCV,,no,1000
2. **HCV-H77** = 63746,hcv1a,Hepatitis C virus (isolate H77),HCV,HCV-H77,uniprot-proteome-hepatitis-c-virus-1a.nt,yes,9
3. **HCV-Japanese** = 11116,hcv1b,Hepatitis C virus (isolate Japanese),HCV,HCV-Japanese,uniprot-proteome-hepatitis-c-virus-1b.nt,yes,10

So I think the database statistics for HCV should look like this: 

**HCV**
Glycans   50
Proteins  0
Glycoproteins  0

**HCV-H77**
Glycans   14
Proteins  1
Glycoproteins  1

**HCV-Japanese**
Glycans   0
Proteins  1
Glycoproteins  1

**Comment by sujeetvkulkarni** [comment]
This information is displayed using 
API: https://api.tst.glygen.org/pages/home_init

![Screenshot 2024-05-23 at 12 36 36 PM](https://github.com/glygener/glygen-issues/assets/13891482/99b76be4-4cdb-42c4-9715-43d052fd7a4f)

So as long as format remains same, no change is needed on frontend.
@ReneRanzinger please review above request and assign it to @rykahsay if required.

**Comment by ReneRanzinger** [comment]
@katewarner is right.

**Comment by rykahsay** [comment]
I am updating the stats and it will show only "HCV-H77" and "HCV-Japanese". The reason "HCV" will come in the stats panel is because we have agreed not to show stats for non-reference species

```
$ cat generated/misc/species_info.csv | grep HCV

tax_id,short_name,long_name,common_name,glygen_name,nt_file,is_reference,sort_order
63746,hcv1a,Hepatitis C virus (isolate H77),HCV,HCV-H77,uniprot-proteome-hepatitis-c-virus-1a.nt,yes,9
11116,hcv1b,Hepatitis C virus (isolate Japanese),HCV,HCV-Japanese,uniprot-proteome-hepatitis-c-virus-1b.nt,yes,10
11103,,Hepacivirus C,HCV,HCV,,no,1000
3052230,,Hepacivirus C,HCV,HCV,,no,1000
```

**Comment by rykahsay** [comment]
<img width="289" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/7db16b17-064b-4732-b7b9-d084b8415ed7">

**Comment by katewarner** [comment]
Looks great! Thanks again
