### ISSUE TITLE
Missing BCOs or bad output file names in BCO io_domain

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#136]

**Comment by rykahsay** [comment]
File names for these BCOs need to be updated (use correct file name as you see it in the unreviewed folder)
```
GLY_000629 sarscov1_proteoform_citations_glycosylation_unicarbkb.csv only_in_bco
GLY_000625 human_protein_biomarkers_cancer.csv only_in_bco
GLY_000609 rat_proteoform_citations_phosphorylation_uniprotkb.csv only_in_bco
GLY_000138 human_proteoform_citations_glycosylation_unicarbkb.csv only_in_bco
GLY_000139 mouse_proteoform_citations_glycosylation_unicarbkb.csv only_in_bco
GLY_000251 rat_proteoform_citations_glycosylation_unicarbkb.csv only_in_bco
GLY_000482 sarscov2_proteoform_citations_glycosylation_unicarbkb.csv only_in_bco
GLY_000483 proteoform_citations_glycosylation_sites_glyconnect.csv only_in_bco
GLY_000483 human_proteoform_citations_glycosylation_glyconnect.csv only_in_bco
GLY_000484 mouse_proteoform_citations_glycosylation_glyconnect.csv only_in_bco
GLY_000485 rat_proteoform_citations_glycosylation_glyconnect.csv only_in_bco
GLY_000511 human_proteoform_citations_glycosylation_literature.csv only_in_bco
GLY_000512 hcv1a_proteoform_citations_glycosylation_literature.csv only_in_bco
GLY_000513 human_proteoform_citations_glycosylation_harvard.csv only_in_bco
GLY_000514 human_proteoform_citations_glycosylation_tyr_o_linked.csv only_in_bco
GLY_000515 sarscov1_proteoform_citations_glycosylation_literature.csv only_in_bco
GLY_000516 human_proteoform_citations_glycosylation_literature_mining.csv only_in_bco
GLY_000517 human_proteoform_glycosylation_sites_o_glcnac_mcw.csv only_in_bco
GLY_000518 human_proteoform_citations_glycosylation_o_glcnac_mcw.csv only_in_bco
GLY_000535 sarscov2_proteoform_citations_glycosylation_glyconnect.csv only_in_bco
GLY_000556 glycan_citations_glycomotif.csv only_in_bco
GLY_000560 human_proteoform_citations_glycosylation_uniprotkb.csv only_in_bco
GLY_000561 mouse_proteoform_citations_glycosylation_uniprotkb.csv only_in_bco
GLY_000562 rat_proteoform_citations_glycosylation_uniprotkb.csv only_in_bco
GLY_000563 hcv1a_proteoform_citations_glycosylation_uniprotkb.csv only_in_bco
GLY_000564 hcv1b_proteoform_citations_glycosylation_uniprotkb.csv only_in_bco
GLY_000565 sarscov2_proteoform_citations_glycosylation_uniprotkb.csv only_in_bco
GLY_000566 sarscov1_proteoform_citations_glycosylation_uniprotkb.csv only_in_bco
GLY_000567 human_proteoform_citations_phosphorylation_iptmnet.csv only_in_bco
GLY_000568 mouse_proteoform_citations_phosphorylation_iptmnet.csv only_in_bco
GLY_000569 rat_proteoform_citations_phosphorylation_iptmnet.csv only_in_bco
GLY_000573 mouse_proteoform_citations_glycosylation_literature_mining.csv only_in_bco
GLY_000574 rat_proteoform_citations_glycosylation_literature_mining.csv only_in_bco
GLY_000575 human_proteoform_citations_glycation_uniprotkb.csv only_in_bco
GLY_000577 rat_proteoform_citations_glycation_uniprotkb.csv only_in_bco
GLY_000600 glycan_evidence_ncfg.csv only_in_bco
GLY_000607 human_proteoform_citations_phosphorylation_uniprotkb.csv only_in_bco
GLY_000608 mouse_proteoform_citations_phosphorylation_uniprotkb.csv only_in_bco
GLY_000631 mouse_proteoform_glycosylation_sites_o_glcnac_mcw.csv only_in_bco
GLY_000632 rat_proteoform_glycosylation_sites_o_glcnac_mcw.csv only_in_bco
GLY_000633 fruitfly_proteoform_glycosylation_sites_o_glcnac_mcw.csv only_in_bco
GLY_000675 fruitfly_proteoform_citations_glycosylation_glyconnect.csv only_in_bco
GLY_000676 fruitfly_proteoform_citations_glycosylation_o_glcnac_mcw.csv only_in_bco
GLY_000677 fruitfly_proteoform_citations_glycosylation_uniprotkb.csv only_in_bco
GLY_000678 fruitfly_proteoform_citations_phosphorylation_iptmnet.csv only_in_bco
GLY_000679 fruitfly_proteoform_citations_phosphorylation_uniprotkb.csv only_in_bco
GLY_000696 mouse_proteoform_citations_glycosylation_o_glcnac_mcw.csv only_in_bco
GLY_000697 rat_proteoform_citations_glycosylation_o_glcnac_mcw.csv only_in_bco
```
The following dataset file names seem to be missing BCOs
```
NULL human_protein_citations_mutation_germline.csv only_in_fs
NULL human_proteoform_citations_glycosylation_sites_literature_mining.csv only_in_fs
NULL human_proteoform_citations_glycosylation_sites_harvard.csv only_in_fs
NULL human_proteoform_citations_glycosylation_sites_tyr_o_linked.csv only_in_fs
NULL fruitfly_proteoform_glycosylation_sites_oglcnac_mcw.csv only_in_fs
NULL glycan_citations_biomarkers.csv only_in_fs
NULL glycan_toolsupport.csv only_in_fs
NULL human_proteoform_citations_glycosylation_sites_glyconnect.csv only_in_fs
NULL glycan_biomarkers.csv only_in_fs
NULL rat_proteoform_citations_glycation_sites_uniprotkb.csv only_in_fs
NULL rat_proteoform_citations_phosphorylation_sites_uniprotkb.csv only_in_fs
NULL fruitfly_protein_xref_oglcnac_atlas.csv only_in_fs
NULL protein_glygen_iptmnet_xref_mapping.csv only_in_fs
NULL sarscov2_proteoform_citations_glycosylation_sites_unicarbkb.csv only_in_fs
NULL mouse_proteoform_citations_glycosylation_sites_uniprotkb.csv only_in_fs
```

**Comment by kmartinez834** [comment]
Most of the existing BCOs were already updated in the Draft.  Verified all are correct now:

GLY_000629 
sarscov1_proteoform_citations_glycosylation_unicarbkb.csv only_in_bco
sarscov1_proteoform_citations_glycosylation_sites_unicarbkb.csv

GLY_000625 
human_protein_biomarkers_cancer.csv only_in_bco
human_protein_biomarkers.csv

GLY_000609 rat_proteoform_citations_phosphorylation_uniprotkb.csv only_in_bco
rat_proteoform_citations_phosphorylation_sites_uniprotkb.csv

GLY_000138 
human_proteoform_citations_glycosylation_unicarbkb.csv only_in_bco
human_proteoform_citations_glycosylation_sites_unicarbkb.csv

GLY_000139 
mouse_proteoform_citations_glycosylation_unicarbkb.csv only_in_bco
mouse_proteoform_citations_glycosylation_sites_unicarbkb.csv

GLY_000251 
rat_proteoform_citations_glycosylation_unicarbkb.csv only_in_bco
rat_proteoform_citations_glycosylation_sites_unicarbkb.csv

GLY_000482 
sarscov2_proteoform_citations_glycosylation_unicarbkb.csv only_in_bco
sarscov2_proteoform_citations_glycosylation_sites_unicarbkb.csv

GLY_000483 
proteoform_citations_glycosylation_sites_glyconnect.csv only_in_bco
human_proteoform_citations_glycosylation_sites_glyconnect.csv

GLY_000483 
human_proteoform_citations_glycosylation_glyconnect.csv only_in_bco
See above

GLY_000484 
mouse_proteoform_citations_glycosylation_glyconnect.csv only_in_bco
mouse_proteoform_citations_glycosylation_sites_glyconnect.csv

GLY_000485 
rat_proteoform_citations_glycosylation_glyconnect.csv only_in_bco
rat_proteoform_citations_glycosylation_sites_glyconnect.csv

GLY_000511 
human_proteoform_citations_glycosylation_literature.csv only_in_bco
human_proteoform_citations_glycosylation_sites_literature.csv

GLY_000512 
hcv1a_proteoform_citations_glycosylation_literature.csv only_in_bco
hcv1a_proteoform_citations_glycosylation_sites_literature.csv

GLY_000513 
human_proteoform_citations_glycosylation_harvard.csv only_in_bco
human_proteoform_citations_glycosylation_sites_harvard.csv

GLY_000514 
human_proteoform_citations_glycosylation_tyr_o_linked.csv only_in_bco
human_proteoform_citations_glycosylation_sites_tyr_o_linked.csv

GLY_000515 
sarscov1_proteoform_citations_glycosylation_literature.csv only_in_bco
sarscov1_proteoform_citations_glycosylation_sites_literature.csv

GLY_000516 
human_proteoform_citations_glycosylation_literature_mining.csv only_in_bco
human_proteoform_citations_glycosylation_sites_literature_mining.csv

GLY_000517 
human_proteoform_glycosylation_sites_o_glcnac_mcw.csv only_in_bco
human_proteoform_glycosylation_sites_oglcnac_mcw.csv

GLY_000518 
human_proteoform_citations_glycosylation_o_glcnac_mcw.csv only_in_bco
human_proteoform_citations_glycosylation_sites_oglcnac_mcw.csv

GLY_000535 
sarscov2_proteoform_citations_glycosylation_glyconnect.csv only_in_bco
sarscov2_proteoform_citations_glycosylation_sites_glyconnect.csv

GLY_000556 
glycan_citations_glycomotif.csv only_in_bco
glycan_citations_motif.csv

GLY_000560 
human_proteoform_citations_glycosylation_uniprotkb.csv only_in_bco
human_proteoform_citations_glycosylation_sites_uniprotkb.csv

GLY_000561 
mouse_proteoform_citations_glycosylation_uniprotkb.csv only_in_bco
mouse_proteoform_citations_glycosylation_sites_uniprotkb.csv

GLY_000562 rat_proteoform_citations_glycosylation_uniprotkb.csv only_in_bco
rat_proteoform_citations_glycosylation_sites_uniprotkb.csv

GLY_000563 
hcv1a_proteoform_citations_glycosylation_uniprotkb.csv only_in_bco
hcv1a_proteoform_citations_glycosylation_sites_uniprotkb.csv

GLY_000564 
hcv1b_proteoform_citations_glycosylation_uniprotkb.csv only_in_bco
hcv1b_proteoform_citations_glycosylation_sites_uniprotkb.csv

GLY_000565 
sarscov2_proteoform_citations_glycosylation_uniprotkb.csv only_in_bco
sarscov2_proteoform_citations_glycosylation_sites_uniprotkb.csv

GLY_000566 
sarscov1_proteoform_citations_glycosylation_uniprotkb.csv only_in_bco
sarscov1_proteoform_citations_glycosylation_sites_uniprotkb.csv

GLY_000567 
human_proteoform_citations_phosphorylation_iptmnet.csv only_in_bco
human_proteoform_citations_phosphorylation_sites_iptmnet.csv

GLY_000568 
mouse_proteoform_citations_phosphorylation_iptmnet.csv only_in_bco
mouse_proteoform_citations_phosphorylation_sites_iptmnet.csv

GLY_000569 
rat_proteoform_citations_phosphorylation_iptmnet.csv only_in_bco
rat_proteoform_citations_phosphorylation_sites_iptmnet.csv

GLY_000573 
mouse_proteoform_citations_glycosylation_literature_mining.csv only_in_bco
mouse_proteoform_citations_glycosylation_sites_literature_mining.csv

GLY_000574 
rat_proteoform_citations_glycosylation_literature_mining.csv only_in_bco
rat_proteoform_citations_glycosylation_sites_literature_mining.csv

GLY_000575 
human_proteoform_citations_glycation_uniprotkb.csv only_in_bco
human_proteoform_citations_glycation_sites_uniprotkb.csv

GLY_000577 
rat_proteoform_citations_glycation_uniprotkb.csv only_in_bco
rat_proteoform_citations_glycation_sites_uniprotkb.csv

GLY_000600 
glycan_evidence_ncfg.csv only_in_bco
glycan_ncfg.csv

GLY_000607 
human_proteoform_citations_phosphorylation_uniprotkb.csv only_in_bco
human_proteoform_citations_phosphorylation_sites_uniprotkb.csv

GLY_000608 
mouse_proteoform_citations_phosphorylation_uniprotkb.csv only_in_bco
mouse_proteoform_citations_phosphorylation_sites_uniprotkb.csv

GLY_000631 
mouse_proteoform_glycosylation_sites_o_glcnac_mcw.csv only_in_bco
mouse_proteoform_glycosylation_sites_oglcnac_mcw.csv

GLY_000632 
rat_proteoform_glycosylation_sites_o_glcnac_mcw.csv only_in_bco
rat_proteoform_glycosylation_sites_oglcnac_mcw.csv

GLY_000633 
fruitfly_proteoform_glycosylation_sites_o_glcnac_mcw.csv only_in_bco
fruitfly_proteoform_glycosylation_sites_oglcnac_mcw.csv

GLY_000675 
fruitfly_proteoform_citations_glycosylation_glyconnect.csv only_in_bco
fruitfly_proteoform_citations_glycosylation_sites_glyconnect.csv

GLY_000676 
fruitfly_proteoform_citations_glycosylation_o_glcnac_mcw.csv only_in_bco
fruitfly_proteoform_citations_glycosylation_sites_oglcnac_mcw.csv

GLY_000677 
fruitfly_proteoform_citations_glycosylation_uniprotkb.csv only_in_bco
fruitfly_proteoform_citations_glycosylation_sites_uniprotkb.csv

GLY_000678 
fruitfly_proteoform_citations_phosphorylation_iptmnet.csv only_in_bco
fruitfly_proteoform_citations_phosphorylation_sites_iptmnet.csv

GLY_000679 
fruitfly_proteoform_citations_phosphorylation_uniprotkb.csv only_in_bco
fruitfly_proteoform_citations_phosphorylation_sites_uniprotkb.csv

GLY_000696 
mouse_proteoform_citations_glycosylation_o_glcnac_mcw.csv only_in_bco
mouse_proteoform_citations_glycosylation_sites_oglcnac_mcw.csv

GLY_000697 
rat_proteoform_citations_glycosylation_o_glcnac_mcw.csv only_in_bco
rat_proteoform_citations_glycosylation_sites_oglcnac_mcw.csv

**Comment by kmartinez834** [comment]
"The following dataset file names seem to be missing BCOs"
--> BCO IDs are below:

```
GLY_000739 - NULL human_protein_citations_mutation_germline.csv only_in_fs
GLY_000516 - NULL human_proteoform_citations_glycosylation_sites_literature_mining.csv only_in_fs
GLY_000513 - NULL human_proteoform_citations_glycosylation_sites_harvard.csv only_in_fs
GLY_000514 - NULL human_proteoform_citations_glycosylation_sites_tyr_o_linked.csv only_in_fs
GLY_000633 - NULL fruitfly_proteoform_glycosylation_sites_oglcnac_mcw.csv only_in_fs
GLY_000738 - NULL glycan_citations_biomarkers.csv only_in_fs
GLY_000707 - NULL glycan_toolsupport.csv only_in_fs
GLY_000483 - NULL human_proteoform_citations_glycosylation_sites_glyconnect.csv only_in_fs
GLY_000737 - NULL glycan_biomarkers.csv only_in_fs
GLY_000577 - NULL rat_proteoform_citations_glycation_sites_uniprotkb.csv only_in_fs
GLY_000609 - NULL rat_proteoform_citations_phosphorylation_sites_uniprotkb.csv only_in_fs
GLY_000735 - NULL fruitfly_protein_xref_oglcnac_atlas.csv only_in_fs
GLY_000736 - NULL protein_glygen_iptmnet_xref_mapping.csv only_in_fs
GLY_000482 - NULL sarscov2_proteoform_citations_glycosylation_sites_unicarbkb.csv only_in_fs
GLY_000561 - NULL mouse_proteoform_citations_glycosylation_sites_uniprotkb.csv only_in_fs
```
