### ISSUE TITLE
TST | species not shown as GlyGen name in glycan simple search

### ISSUE THREAD

**Issue by CyrusAY** [glygener/glygen-issues#1363]
In the glycan search summary page, organism filters on the left are showing species in their common name instead of the glygen name. There are also issues with the collapsing of species-specific metrics data.

Here, using B4GALT1 as an example in glycan simple search shows:
![image](https://github.com/glygener/glygen-issues/assets/144174496/2504bbd3-0b66-470b-bb4c-ecf1fe1448c5)
https://tst.glygen.org/glycan-list/4362b820cab3d6cb4df1e9cd68a98a4e

- Rattus and Rat, Domestic pig and Pig should be collapsed to Rat and Pig, respectively
- Common names are shown instead of GlyGen names (SARS-CoV-2 -> 2019-nCoV), same goes to social amoeba (cellular slime mold)

API query shows:
/glycan/list
```
{
  "id": "4362b820cab3d6cb4df1e9cd68a98a4e"
}
```
<details>
<summary>Response</summary>

```json
{
        "id": "by_organism",
        "label": "By Organism",
        "order": 2,
        "tooltip": "",
        "options": [
          {
            "id": "Human",
            "label": "Human",
            "count": 3939,
            "order": 1
          },
          {
            "id": "Mouse",
            "label": "Mouse",
            "count": 768,
            "order": 2
          },
          {
            "id": "Rat",
            "label": "Rat",
            "count": 571,
            "order": 3
          },
          {
            "id": "Pig",
            "label": "Pig",
            "count": 955,
            "order": 4
          },
          {
            "id": "Chicken",
            "label": "Chicken",
            "count": 470,
            "order": 5
          },
          {
            "id": "Fruit fly",
            "label": "Fruit fly",
            "count": 7,
            "order": 6
          },
          {
            "id": "Baker's yeast",
            "label": "Baker's yeast",
            "count": 1,
            "order": 1000
          },
          {
            "id": "2019-nCoV",
            "label": "2019-nCoV",
            "count": 2,
            "order": 12
          },
          {
            "id": "Rattus",
            "label": "Rattus",
            "count": 399,
            "order": 1000
          },
          {
            "id": "Domestic pig",
            "label": "Domestic pig",
            "count": 1,
            "order": 1000
          },
          {
            "id": "Chinese hamsters",
            "label": "Chinese hamsters",
            "count": 489,
            "order": 1000
          }
        ]
      },
```
</details>

**Comment by CyrusAY** [comment]
A new 'Glygen_name' column was added to species_info.csv in this release, it should be used instead of 'Common_name' to populate the apis.
<img width="1064" alt="image" src="https://github.com/glygener/glygen-issues/assets/144174496/6af199ad-4aa1-422a-bde7-17f95e2321e9">

*thanks karina for helping with analyzing the issue

**Comment by rykahsay** [comment]
check now:

<img width="642" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/f02c6fca-e1d4-461b-bc7f-9051151d39a2">

**Comment by CyrusAY** [comment]
Issue resolved.
