### ISSUE TITLE
Test data.tst.glygen.org

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1364]
Please itemize the things you tested in this ticket (I am expecting there is a detail test guide). For all the issues you find, please make a separate ticket

**Comment by ubhuiyan** [comment]
I have finished testing. The following were QC'd: 

1. Checked **Home, FAQ, Release History, File Uploads, About, PORTAL, API, and SPARQL** tabs to make sure pages populate. - No issues found 
2. Checked "...view details" on Details column within Home page. -Found Issue #1376 
4. Checked All Side bar features - No Issues 
5. Submit SPARQL Query - No Issues
6. Checked detail page within Release History - No Issues 
7. Selected all questions in FAQ page - No Issues 
8. Checked Questions/Comments link within About page - No issues

**Comment by Luke-Johnson-5** [comment]
I am still testing however up to this point I have QC'd:

1. Sidebar features: No problem
2. FAQ page: some issues documented and fixed. Tickets now closed.
3. About, File uploads and Release history pages: Checked no issues.
4. Still waiting for #1376 to be fixed to confirm that #1373 is fixed.
5. Created #1374 to add descriptions to to datasets without them for 2.6

**Comment by katewarner** [comment]
I've completed the testing and all issues I reported have been fixed. 
Testing I carried out:
- Checked text, images, and links on the data homepage.
- Checked if datasets have tables displayed
- Checked whether the filters and reset filters work on not 
- Clicked on several datasets to ensure they have sample view page
- Checked description and "all records" table is displayed on the sample view page
- Checked that datasets can be toggled to different version when the option is available
- Checked BCOs and readme links display the content
- Checked the download datasets and download BCOs work
- Checked the other menu links such as FAQs, Release history
- Checked the FAQ page text makes sense and the links work
