### ISSUE TITLE
Broken FAQ and About links on data.tst.glygen.org

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1365]
The FAQ link at the top of the Data homepage appears to be broken and produces the following error: 

![image](https://github.com/glygener/glygen-issues/assets/161866639/03b8adfd-ec34-437a-9575-e50d068f273d)

I'm not sure how to investigate the error to suggest a solution, so it'd be great to find out what the problem was.

**Comment by katewarner** [comment]
@rykahsay The "About" link at the top of the Data page (https://data.tst.glygen.org/static/about) also produces the same error

**Comment by rykahsay** [comment]
Fixed:

<img width="704" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/69d09371-77dd-4c11-a8de-cca60597d062">


<img width="696" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/28784b9f-e6bd-41dd-8f28-cb7f6e0cb01e">

**Comment by katewarner** [comment]
Thank you!
