### ISSUE TITLE
Reset button broken on data page 

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1366]
On the data page on tst 2.5, but also on prd 2.4, the "Reset" button bellow the filters doesn't work. I'm assuming that the reset button should clear any filters I've applied but it doesn't. This happened when I applied filters on the homepage or applying filters after a search e.g. after searching for "kinase" (https://data.tst.glygen.org/results/84d0ece6d6efe4d591e3f20bfff37c80). 

Also does the "Apply" button at the bottom of the filters have a purpose? I noticed that filters are automatically applied when they are selected, so I'm not really sure why the Apply button is there and what it should do.

**Comment by rykahsay** [comment]
I have tried to fix it, check now

**Comment by katewarner** [comment]
It still doesn't work for me. Is the reset button supposed to remove the filters I've applied?

**Comment by rykahsay** [comment]
Maybe you need to clear your cache ... right click on the page --> inspect --> network --> "Disable cache" and then refresh your page several times by checking and unchecking the "Disable cache" checkbox

<img width="511" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/c2abfb2e-a196-41c5-a72c-7d6aa09738ff">

**Comment by katewarner** [comment]
Okay it looks if you perform a search, such as "kinase", then filter the results, pressing the reset button works and removes all the filters. 

But if you're on the homepage and haven't performed any searches, then filter all the datasets, pressing the reset button doesn't work to remove the filters.

**Comment by rykahsay** [comment]
Try on tst, ignore prd for now

**Comment by katewarner** [comment]
It works. Thank you again.
