### ISSUE TITLE
All links in footer of data page are broken

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1367]
On the data page on tst 2.5, but also on prd 2.4, all the links in the footer at the bottom of the data homepage are broken i.e. "License", "Privacy Policy", "Disclaimer" and "Contact Us". They don't link out to any page so I think the hyperlinks are missing the urls

![image](https://github.com/glygener/glygen-issues/assets/161866639/1b2effbd-831b-4dd8-8018-110d29351fe8)

**Comment by rykahsay** [comment]
Try now

**Comment by katewarner** [comment]
It's fixed on tst but not on prd.

**Comment by rykahsay** [comment]
It will go away as we push 2.5 to prd

**Comment by katewarner** [comment]
Okay great. Thanks again.
