### ISSUE TITLE
Icon thumbnail in data homepage footer

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1368]
On the data page on tst 2.5, but also on prd 2.4, there's an icon thumbnail to the left of the Georgia University emblem in the footer of the data homepage. I'm not sure if there is supposed to be an image there that's missing or if it just needs to be deleted.

![image](https://github.com/glygener/glygen-issues/assets/161866639/d9882086-75b4-41cf-b3ab-52c9c926e050)

**Comment by rykahsay** [comment]
Missing image for GW logo -- have fixed it on tst (again, you will need to clear your cache)

<img width="763" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/bc898d33-dbb4-4b85-9eb7-f9c754160d30">

**Comment by rykahsay** [comment]
can't re-assign me without a comment/reason

**Comment by katewarner** [comment]
Sorry, I thought I had commented but I must have forgotten to click the comment button. 

I just said it's fixed but the GW logo looks very fuzzy. Should I pass the ticket to Sujeet to find a better logo?

**Comment by rykahsay** [comment]
I have changed the size -- it looks ok to me now
