### ISSUE TITLE
Incorrect link on FAQ page on data.tst

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1369]
On the FAQ page for data (https://data.tst.glygen.org/static/faq) I found incorrect links under the following questions:

**2. | How do I find a GlyTouCan accession for my glycan composition?**
The HTML link for "composition search" should have the url "https://www.glygen.org/glycan-search#Composition-Search"
`<a href="https://www.glygen.org/glycan-search#Composition-Search"> composition search </a>`

**3. | How do I find a GlyTouCan accession for my glycan structure?**
The HTML link for text "here" should have the url "https://rings.t.soka.ac.jp/downloads.html"
`<a href="https://rings.t.soka.ac.jp/downloads.html">here</a>`

**4. | How can I convert my glycan sequence to different formats (e.g IUPAC, WURCS, GlycoCT, LinearCode, etc.)?**
The HTML link for "Swagger" should have the url "https://api.glycosmos.org/glycanformatconverter/#version-2.8.2"
`<a href="https://api.glycosmos.org/glycanformatconverter/#version-2.8.2">Swagger</a>`

**2. | What are the different resources integrated into GlyGen?**
The HTML link for text "here" should have the url "https://glygen.org/license/"
`<a href="https://glygen.org/license/">here</a>`

**5. | How can I access the GlyGen Data?**
I think you can remove the text "(coming in future)" as we have SPARQL now
![image](https://github.com/glygener/glygen-issues/assets/161866639/a60d1782-6a9b-42b2-864c-b71532758d25)

**7. | What is a GlyGen data object?**
I think the text for HTML "GLYDS000001" should be changed to "GLY_000001" and the url should be set to "https://data.glygen.org/GLY_000001"
`<a href="https://data.glygen.org/GLY_000001">GLY_000001</a>`

**10. | How can I submit my data?**
The HTML link for "page" should have the url "https://www.glygen.org/contact-us/"
`<a href="https://www.glygen.org/contact-us/">page</a>`

14. | Which UniProtKB and GlyTouCan accessions are included in GlyGen?
The glycan datasets are outdated. I asked Karina and she said that she thinks it should be only the glycan_masterlist.csv, which would be GLY_000281 for all species. Please change to the following.

```
" The GlyTouCan accession list is compiled when the accession falls under one or more selected criteria: Visit GlyGen dataset object "
<a href="https://data.glygen.org/GLY_000281"> GLY_000281</a>
"for more information. "
```

**Comment by rykahsay** [comment]
The source files are under /data/projects/glygen/generated/html/ on GlyGen dev server. Please edit /data/projects/glygen/generated/html/faq.html to correct those links and assign back the ticket to me when you are done.

**Comment by katewarner** [comment]
I've made the corrections

**Comment by rykahsay** [comment]
I have pushed the changes -- please check. You may need to clear your cache ...

**Comment by katewarner** [comment]
All the links are fixed but I noticed that the image was missing from question 9. I tried to correct the FAQ file so please push the changes again.

**Comment by rykahsay** [comment]
If you are talking about the Wiki image, I have fixed the link ... your link had a problem:

<img width="1254" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/bec337e6-3da8-49de-815b-36a19d53a8fc">


<img width="853" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/e2159a3f-e876-49f1-9546-f9fa81c48953">

**Comment by katewarner** [comment]
Ah I see, thanks for fixing it
