### ISSUE TITLE
Document and Use

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#137]
This script will allow you to see the standing on dataset file names in the BCOs and file system. Please add it to our documentation and start using it.

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/20584876/225125100-f9ea177b-c1bb-4d9d-8d7f-f8baa5a2e0c9.png">

**Comment by kmartinez834** [comment]
👍 Added to Data Integration doc in Sharepoint
