### ISSUE TITLE
Data.tst.glygen.org broken link in in FAQ on TST

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#1370]
Under FAQs in Glycan FAQ section under number 2 drop down the "composition search" link out takes you to blank GlyGen page.

![image](https://github.com/glygener/glygen-issues/assets/144174552/562c7a36-d0a2-4fe8-b53f-85c5d77de91b)
![image](https://github.com/glygener/glygen-issues/assets/144174552/e8225dcd-a044-4115-8517-b058b9f6ae0c)

**Comment by sujeetvkulkarni** [comment]
@rykahsay can you please fix this composition search link on data portal.

**Comment by rykahsay** [comment]
@Luke-Johnson-5  ... please read comments on #1369  ... learn you need to do to make edits on the static pages

**Comment by Luke-Johnson-5** [comment]
I see kate seems to have handled this
