### ISSUE TITLE
Data.glygen contact us page never loads.

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#1372]
The contact us page on data.glygen spins forever and never loads. I believe this is a front end issue.

![image](https://github.com/glygener/glygen-issues/assets/144174552/016c4a6b-f314-48c2-89b5-577fc33878f9)

**Comment by sujeetvkulkarni** [comment]
assigning it to @rykahsay

**Comment by sujeetvkulkarni** [comment]
@Luke-Johnson-5 https://data.tst.glygen.org/ contact us link in footer takes you glygen portal and working. Can you please verify it now. Also, data portal issues can be assigned to @rykahsay

**Comment by Luke-Johnson-5** [comment]
@sujeetvkulkarni Yes this is correct my apologies I should have been more specific on where this issue is. The issue is when you are on the about page there is a link out that says "click here" to contact us. This link is the one that takes you to a page that never loads, see below. I see I will reassign any tickets I made for you on data portal over to @rykahsay 

![image](https://github.com/glygener/glygen-issues/assets/144174552/6f28190e-461a-4929-a913-956957883bd4)

**Comment by rykahsay** [comment]
I have fixied it this time but please read #1369 to learn on how to edit contents for the static pages
