### ISSUE TITLE
Update BCO version number for 2.5.1

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#1373]
Dataset BCO's seem to still all be set to version "v-x.x.x". I checked many BCO's and they all seem to be this way.

![image](https://github.com/glygener/glygen-issues/assets/144174552/f4a813a0-2e61-4b08-8c88-316ebb9c7007)

**Comment by rykahsay** [comment]
check now

**Comment by Luke-Johnson-5** [comment]
I believe this is fixed however, cannot view bcos at this time and will look at this again when I can.

**Comment by Luke-Johnson-5** [comment]
done.
