### ISSUE TITLE
Add descriptions to BCO's

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#1374]
Here is a list with the BCOs that are missing a description domain that we may want to add in the future.

GLY_000507
GLY_000508
GLY_000509
GLY_000522
GLY_000526
GLY_000540
GLY_000543
GLY_000544
GLY_000567
GLY_000568
GLY_000569
GLY_000570
GLY_000571
GLY_000572
GLY_000577
GLY_000589
GLY_000593
GLY_000600
GLY_000601
GLY_000602
GLY_000603
GLY_000604
GLY_000605
GLY_000606
GLY_000608
GLY_000609
GLY_000610
GLY_000611
GLY_000612
GLY_000617
GLY_000618
GLY_000619
GLY_000627
GLY_000678
GLY_000679
GLY_000733
GLY_000803
GLY_000804
GLY_000850
GLY_000855
GLY_000895
GLY_000922
GLY_001015
GLY_001025

**Comment by katewarner** [comment]
@Luke-Johnson-5 I added the descriptions for the following BCOs while creating the human_protein_disease_alliance_genome BCO
GLY_000543
GLY_000544

**Comment by jeet-vora** [comment]
Something to work on for 2.8
