### ISSUE TITLE
"All Records" not populating on data.tst.glygen.org/

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1376]
![Screenshot 2024-05-24 at 9 45 23 AM](https://github.com/glygener/glygen-issues/assets/90285310/f65c7aa5-3476-4e1f-ab05-50d38f6bbd0b)

Appears to be the case for all datasets on tst site.

**Comment by rykahsay** [comment]
Probably it was loading when you tried it, please check this on prd now and let me know if there is a problem

**Comment by ubhuiyan** [comment]
All good now!
