### ISSUE TITLE
glycan advanced search issue - Organism search is failing for some organisms.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1379]
1. glycan search fails if user chooses HCV-H77, HCoV-SARS, Cellular slime mold, SARS-CoV-2 from the dropdown and performs search.

API : 
https://api.tst.glygen.org/glycan/search?query=
{"operation":"AND","query_type":"search_glycan","glycan_name":"","organism":{"organism_list":[{"common_name":"HCV-H77"}],"annotation_category":"","operation":"or"}}

![Screenshot 2024-05-24 at 3 44 17 PM](https://github.com/glygener/glygen-issues/assets/13891482/aad996bd-bfee-4965-95cf-b5231a992061)

**Comment by rykahsay** [comment]
You need to use "glygen_name":"HCV-H77" not "common_name":"HCV-H77". BTW, why are you sending "glycan_name":""?

**Comment by sujeetvkulkarni** [comment]
@rykahsay with glygen_name organism search is not working, it lists all organisms.

API:
https://api.tst.glygen.org/glycan/search?query={"operation":"AND","query_type":"search_glycan","organism":{"organism_list":[{"glygen_name":"Chinese hamster"}],"annotation_category":"","operation":"or"}}

![Screenshot 2024-05-28 at 1 16 44 PM](https://github.com/glygener/glygen-issues/assets/13891482/1f35c79d-53cd-4972-81a3-be8c97046546)

**Comment by rykahsay** [comment]
Ok, we can address that but you need to stop using "common_name" because we have agreed to work with "glygen_name" only. Please change your code that all your ogranism pull down are using "glygen_name"

**Comment by rykahsay** [comment]
BTW, the "Chinese hamster" search with glygen_name works now:

<img width="1104" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/ad32e507-7d50-432d-840c-78ac8e4e5fe3">

**Comment by sujeetvkulkarni** [comment]
@rykahsay we are using glygen_name but the search does use the organism criterion applied and displays all results like shown below. The search works but it does not filter search results with organism criterion applied, that's the issue. 

In below case 'Chicken' is searched but result is showing all 53384 glycans. It should only show 'Chicken' related glycans.

https://api.tst.glygen.org/glycan/search?query=
{"operation":"AND","query_type":"search_glycan","organism":{"organism_list":[{"glygen_name":"Chicken"}],"annotation_category":"","operation":"or"}}

https://api.tst.glygen.org/glycan/list?query=
{"id":"e5c71f13d6dedd7274f7726fa80fefbc","offset":1,"sort":"hit_score","limit":20,"order":"desc","filters":[]}

![Screenshot 2024-05-30 at 11 05 56 AM](https://github.com/glygener/glygen-issues/assets/13891482/46f41442-0966-4e04-9f91-1254d25b3c5e)

**Comment by rykahsay** [comment]
Fixed, please check

<img width="1339" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/c21d1685-a2c3-432b-9dfe-dc67acd5201c">

**Comment by sujeetvkulkarni** [comment]
done - closing.
