### ISSUE TITLE
does glygen blast init and result api needs to use glygen_name for organisms?

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1380]
glygen blast init:
API : https://api.tst.glygen.org/job/init?query={
<img width="1126" alt="Screenshot 2024-05-26 at 6 05 21 PM" src="https://github.com/glygener/glygen-issues/assets/13891482/5cb33711-273e-4dfa-99bf-70f6d074c27f">

glygen blast result:
API: https://api.tst.glygen.org/job/results/?query={"jobid":75}

<img width="1135" alt="Screenshot 2024-05-26 at 6 10 10 PM" src="https://github.com/glygener/glygen-issues/assets/13891482/8c66b1c9-052f-46ee-91c9-9165353f5d11">

**Comment by rykahsay** [comment]
Check now --

**Comment by sujeetvkulkarni** [comment]
done.
0b7c85e4edee8716c7563759b9f039f09abb08b6
