### ISSUE TITLE
Arabidopsis species on tst server

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1382]
Arabidopsis species is not part of 2.5 but listed on tst server. For 2.5 it should not get listed.

![Screenshot 2024-05-28 at 1 56 39 PM](https://github.com/glygener/glygen-issues/assets/13891482/66b10cdc-39c2-498d-9fc7-a2e3f505d901)

**Comment by rykahsay** [comment]
Good question for @kmartinez834  ...

BTW, this works now:

https://api.tst.glygen.org/glycan/search/?query={%22operation%22:%22AND%22,%22query_type%22:%22search_glycan%22,%22glycan_name%22:%22%22,%22organism%22:{%22organism_list%22:[{%22glygen_name%22:%22Arabidopsis%22}],%22annotation_category%22:%22%22,%22operation%22:%22or%22}}

**Comment by kmartinez834** [comment]
We have Arabidopsis and Chinese hamster species annotations because they are are included in Nathan's export.  However, since they are not formally "GlyGen organisms" yet, please remove both from the glycan/search_init:

``` json
{
      "name": "Chinese hamster",
      "id": 10029
    },
    {
      "name": "Arabidopsis",
      "id": 3702
    },
```

**Comment by sujeetvkulkarni** [comment]
@kmartinez834  @rykahsay If a species is showed in Organism section it needs to be shown in search. Otherwise it will affect direct search on details pages. If removed then remove completely from glygen Organism section on details pages too.

@ReneRanzinger please share your opinion?

**Comment by kmartinez834** [comment]
@sujeetvkulkarni ok then we need to update the list init because they're not included in the filters...

**Comment by rykahsay** [comment]
@kmartinez834 I hope you guys are working in the ticket I created for you -- coming up with a standard ways to address these species related issue (what to show where ...). I will stop doing any adhoc fixes anymore --- it's getting out of hand now.

**Comment by kmartinez834** [comment]
Closing ticket, see #1325 regarding species issues
