### ISSUE TITLE
hit score is -1 on biomarker list page if no condition is applied during biomarker search.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1383]
https://tst.glygen.org/biomarker-list/5660e007f5ba46e4d57cd635c132afff

![Screenshot 2024-05-28 at 2 58 28 PM](https://github.com/glygener/glygen-issues/assets/13891482/3680fa32-e057-429a-a6e7-764eeccc25e3)

**Comment by rykahsay** [comment]
Test now

**Comment by sujeetvkulkarni** [comment]
59f2f49bbd0aee3bbac698622245f63ca5a54152
