### ISSUE TITLE
Datasets "view details" never load on data.tst

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1384]
On data.tst if we select "...view details" for any of the datasets, the details page never loads it just shows the spinning loading icon. Luke, Urnisha and I were wondering if this was to do with this issue: https://github.com/glygener/glygen-issues/issues/1376 ? If so I'll close this issue.

**Comment by rykahsay** [comment]
Check now

**Comment by katewarner** [comment]
It's fixed. Thank you
