### ISSUE TITLE
Biomarker Score

### ISSUE THREAD

**Issue by DaniallMasood** [glygener/glygen-issues#1385]
I see that the hit score exists within the Biomarker results tables (this is for the biomarker front end) and seems to be copied over from GlyGen. We have our own version of the biomarker score and would like to use that in place of the hit score if possible. @seankim658 has developed a mechanism for that if that can be implemented and used for the scoring.

https://github.com/clinical-biomarkers/biomarker-score-calculator

this is the score calculator. Sean if you can advise on how to use it and @sujeetvkulkarni if this is possible to implement or how we can?

**Comment by sujeetvkulkarni** [comment]
you can use your own score just keep the name and same format.

**Comment by DaniallMasood** [comment]
Ok just talked to Sean. The score for biomarkers should already be in the API. it comes underneath the field "score"
if that can be placed within the score column on the results

**Comment by seankim658** [comment]
@sujeetvkulkarni I'll implement this on my end in the format that hit score on glygen does. Right now we have it in a different format.

**Comment by DaniallMasood** [comment]
@sujeetvkulkarni could you change the equation in the score information to this
![image](https://github.com/glygener/glygen-issues/assets/116293652/38880458-9e55-4635-bc54-8f477d595491)

**Comment by sujeetvkulkarni** [comment]
@seankim658 @DaniallMasood 
For Hit score -
weights would be same for every biomarker and 
frequency would be different.
So weights should be constants.

So I believe the formula would be,
∑ (Weight * Frequency)

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood @seankim658 

In case of where hit score value is 0. You have to adjust your frequency to reflect the Hit score value based on the ∑ (Weight * Frequency) formula.

![Screenshot 2024-07-01 at 4 11 59 PM](https://github.com/glygener/glygen-issues/assets/13891482/d565280c-3afd-41ee-9ad6-8106eb5a6dd7)

![Screenshot 2024-07-01 at 4 13 02 PM](https://github.com/glygener/glygen-issues/assets/13891482/c61be686-5a30-425b-ad01-1a81b9010771)
