### ISSUE TITLE
Beta: Site search - all sites

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1386]
On Beta:
* Go to Site search
* Do not change anything just click "Search"

![Untitled](https://github.com/glygener/glygen-issues/assets/2267640/a833b5d2-2975-4277-a991-45220c6a492b)

Supersearch all sites version is working (I think due to cache).

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger 
I tried but looks like Site Search is working now. 
https://beta.glygen.org/site-list/e5e9e8999a3451a947eb2f05508b4a29

![Screenshot 2024-05-29 at 5 37 46 PM](https://github.com/glygener/glygen-issues/assets/13891482/91ce1171-6f90-4f23-8ecc-65d369243d99)

**Comment by sujeetvkulkarni** [comment]
working on beta, so closing.
