### ISSUE TITLE
Chicken datasets are not in the release data folders

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1387]
On data.tst I tried downloading chicken datasets but got a error message of file not found e.g.:

File not found:
https://data.tst.glygen.org/ln2data/releases/data/v-2.5.1/reviewed/chicken_protein_participants_reactome.csv

I had a look in the data release folders and found that the chicken datasets were missing. I was going to move them to the release folder from the unreviewed folder but I wasn't sure which was the correct release data folder. Is it:  

/data/projects/glygen/releases/data/v-1.5.1/reviewed/
or
/data/projects/glygen/releases/data/v-1.5.26/reviewed/

**Comment by rykahsay** [comment]
try now

**Comment by katewarner** [comment]
Fixed. Thanks again
