### ISSUE TITLE
Provide contacts for CFDE DCCs

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1390]
@Mindyporterfield will need a list of contacts to reach out to each DCC. It does not (should not?) the PI. She plans to setup a meeting with the contact person to discuss possible ways of linking GlyGen and the DCC or to exchange data.

**Comment by jeet-vora** [comment]
Here is the list - https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/Shared%20Documents/CFDE/DCC%20PM%20and%20PI%20Contact%20List%20(1).xlsx?d=we43137ee2fe548aa844003acdaf292b3&csf=1&web=1&e=ruOEC4

**Comment by jeet-vora** [comment]
https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/Shared%20Documents/CFDE/Centers,%20DCC%20PM%20and%20PI%20Contact%20List.xlsx?d=wc4e7f2ae10604c6aaabdb72f475af87f&csf=1&web=1&e=Vruh2G

**Comment by Mindyporterfield** [comment]
got them, thanks
