### ISSUE TITLE
ISOglyP Task

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#1396]
- [x] Read IsoGlyP paper
- [x] Review the portal and code
- [x] Review Seun' work and run the script
- [x] Prepare a dataset + BCO
- [x] Draw mockups to show the data

**Comment by Luke-Johnson-5** [comment]
Location if IsoGlyp project files on glygen dev server: /software/o_glycos/

**Comment by Luke-Johnson-5** [comment]
Make dataset:
Mechanism to run IsoGlyp on any new proteins every release:

**Comment by Luke-Johnson-5** [comment]
Complete
