### ISSUE TITLE
Biomarker simple search with example query

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1398]
I checked both the search and list APIs, they are giving results --- I don't know why the frontend fails to show results

683edfaa8222aca6c79dcb51abbe2c79

<img width="1118" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/570b23b0-25e2-4c05-8783-3ed3e9b99e11">

**Comment by sujeetvkulkarni** [comment]
@rykahsay yes list id is there but results array is empty. So result array needs to have values in it.

![Screenshot 2024-06-02 at 12 01 02 PM](https://github.com/glygener/glygen-issues/assets/13891482/659e1866-7d1b-4bf4-9913-438af90d6f2f)

**Comment by rykahsay** [comment]
I don't know why you getting that -- shown below I what I see from the API
<img width="554" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/fa72056e-3600-474c-8e1d-4da1425c3b45">
<img width="554" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/fa72056e-3600-474c-8e1d-4da1425c3b45">

**Comment by sujeetvkulkarni** [comment]
@rykahsay it could be a GET, POST issue. Please check with GET request, we are using GET request in frontend.

API:
https://api.glygen.org/biomarker/list?query=
{"id":"683edfaa8222aca6c79dcb51abbe2c79","offset":1,"sort":"hit_score","limit":20,"order":"desc","filters":[]}

![Screenshot 2024-06-03 at 10 54 11 AM](https://github.com/glygener/glygen-issues/assets/13891482/204d85dc-89c1-456c-b915-31902205d50c)

**Comment by sujeetvkulkarni** [comment]
done - closing the issue.
