### ISSUE TITLE
Super search Organism name should use glygen_name.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1399]
![Screenshot 2024-06-03 at 12 03 46 PM](https://github.com/glygener/glygen-issues/assets/13891482/48d591be-6bf0-49cc-bc5f-c5e0d733af06)

**Comment by rykahsay** [comment]
Fixed:

<img width="866" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/bf3f7012-7c6e-45ef-b56c-d8119525eca1">

**Comment by sujeetvkulkarni** [comment]
Names are appearing properly but in some cases if you search with a organism name like "Cellular slime mold" result counts are 0.

Results counts are 0 in case a super search is performed with  all below organism name cases,
1. Cellular slime mold
2. HCV-H77
3. HCV-Japanese
4. HCoV-SARS
5. SARS-CoV-2
6. Yeast

![Screenshot 2024-07-02 at 2 51 38 PM](https://github.com/glygener/glygen-issues/assets/13891482/5b07d4eb-26c0-4b85-8d3f-978fa512c036)

![Screenshot 2024-07-02 at 2 51 49 PM](https://github.com/glygener/glygen-issues/assets/13891482/c50aaa07-7b61-488c-85df-dc7ede43b49a)

**Comment by rykahsay** [comment]
Works now

<img width="992" alt="image" src="https://github.com/user-attachments/assets/0b827ab9-d606-4f98-bdc5-d4d8a9f1b868">

**Comment by sujeetvkulkarni** [comment]
Done, closing.
