### ISSUE TITLE
New EMBL sites are on TST and BETA but not PRD

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1400]
https://tst.glygen.org/glycan/G62765YT#Associated-Protein
https://beta.glygen.org/glycan/G62765YT#Associated-Protein
![image](https://github.com/glygener/glygen-issues/assets/90285371/9d3a2bab-20e0-4f8b-a435-128b2d94ed58)

https://glygen.org/glycan/G62765YT#Associated-Protein
![image](https://github.com/glygener/glygen-issues/assets/90285371/218cae63-e203-4882-81e7-9b26e4cc2a63)

**Comment by rykahsay** [comment]
Fixed, please check

<img width="1148" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/72bf8752-58e7-4bee-a29b-397061fc4e53">
