### ISSUE TITLE
Covalently Attached Glycan number on protein list page does not match number of glycoproteins on glycan list page.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1401]
Use direct search on glycan list page in No of Glycoproteins  column near the number.

In this case here the number was 30.
The search takes you to protein list page where the number is 29.
The number should match.

https://api.tst.glygen.org/protein/search?query=
{"operation":"AND","query_type":"search_protein","attached_glycan_id":"G17689DH"}

![Screenshot 2024-06-03 at 1 25 04 PM](https://github.com/glygener/glygen-issues/assets/13891482/17324c4e-e8bf-480c-bca8-3a0d56e40b85)

![Screenshot 2024-06-03 at 1 25 42 PM](https://github.com/glygener/glygen-issues/assets/13891482/cdfad18f-cb64-478e-8889-eedcd92ef2e2)

**Comment by rykahsay** [comment]
check now

**Comment by sujeetvkulkarni** [comment]
done.
