### ISSUE TITLE
Generating the glycan_xref_chebi.csv file

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1402]
Karina and I noticed that glycan G17689DH - that's in ChEBI, has a GlyGen xref, and is listed in the chebi download - is missing from the glycan_xref_chebi.csv file and so it's ChEBI xref is missing on it's glycan detail page.

Karina looked into it and found that it is missing a GlyToucan accession so she was thinking that you're probably only looking for rows with "GlyTouCan":
```
$ grep G17689DH /data/projects/glygen/downloads/chebi/2024_04_02/database_accession.tsv
1045468 87782   GlyGen  GlyGen accession        G17689DH

$ grep G95929CC /data/projects/glygen/downloads/chebi/2024_04_02/database_accession.tsv
1028436 155519  GlyTouCan       GlyTouCan accession     G95929CC
1050158 155519  GlyGen  GlyGen accession        G95929CC
```

Can you please alter the script to use rows with both GlyGen and GlyTouCan in the "SOURCE" field of database_accession.tsv

**Comment by rykahsay** [comment]
I have fixed it:

```
$ cat unreviewed/glycan_xref_chebi.csv  | grep G17689DH
"G17689DH","87782","glycan_xref_chebi"
```
