### ISSUE TITLE
Protein advanced search on prd

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1403]
On the Protein advanced search tab, I searched for "Alpha-(1,3)-fucosyltransferase 10" in the "Protein name" section:
![image](https://github.com/glygener/glygen-issues/assets/161866639/af0a0577-2a31-49e4-8134-0d716a437ba0)

The results were correct, I clicked "Modify results" and returned to the advanced search page (https://www.glygen.org/protein-search/cdcb7e5d275d8672a1c6103c0cc622fe), but when I clicked inside the "Protein name" section to try another protein, the screen went completely blank, and the advanced search only reappeared when I reloaded the page.

**Comment by rykahsay** [comment]
@sujeetvkulkarni ... can you please let us know what is goin on here?

**Comment by sujeetvkulkarni** [comment]
Search query:
https://api.tst.glygen.org/protein/search?query={"operation":"AND","query_type":"search_protein","protein_name":"Alpha-(1,3)-fucosyltransferase 10"}

List api:
https://api.tst.glygen.org/protein/list?query={"id":"cdcb7e5d275d8672a1c6103c0cc622fe","offset":1,"limit":20,"order":"desc","sort":"hit_score","filters":[]}

cache_info in list api modifies user input to \ to it. 
input is modified from "Alpha-(1,3)-fucosyltransferase 10" to "Alpha-\\(1,3\\)-fucosyltransferase 10"

```
cache_info: {
  "query": {
    "operation": "AND",
    "query_type": "search_protein",
    "protein_name": "Alpha-\\(1,3\\)-fucosyltransferase 10"
  },
  "ts": "2024-06-17 14:20:43 EDT-0400",
  "record_type": "protein",
  "search_type": "search"
}
```

"Alpha-\\(1,3\\)-fucosyltransferase 10" input (\ in it) causes typeahed api to return error_list. resulting in page going blank.

https://api.tst.glygen.org/typeahead/typeahead?query=
{"field":"protein_name","value":"Alpha-\(1,3\)-fucosyltransferase 10 ","limit":100}

```
{
    "error_list": [
        {
            "error_code": "unexpected-field-in-query",
            "field": "error_list"
        },
        {
            "error_code": "missing-parameter",
            "field": "field"
        },
        {
            "error_code": "missing-parameter",
            "field": "value"
        },
        {
            "error_code": "missing-parameter",
            "field": "limit"
        }
    ]
}
```

Issues:
1. Backend should not modify user input from "Alpha-(1,3)-fucosyltransferase 10" to "Alpha-\\(1,3\\)-fucosyltransferase 10" to include \ in it.
2. Backend should not return error_list in typeahed api in case \ is present in input.
3. Frontend should handle the case if backend typeahead api returns error_list.

@rykahsay you need to fix 1 and 2 issue.
I will need to fix issue 3.

**Comment by rykahsay** [comment]
@katewarner  ... I have tried to fix it, please check

**Comment by katewarner** [comment]
It's fixed thank you
