### ISSUE TITLE
Glycan Simple Search Results not matching side bar

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#1405]
When you search "Human" on glycan simple search you get 39710 results but side bar to sort by organism it shows 23511 human results.

![image](https://github.com/glygener/glygen-issues/assets/144174552/ed0f54f3-a79d-4f85-8bed-48701e957ad0)

**Comment by Luke-Johnson-5** [comment]
Same occurs in protein simple search.
![image](https://github.com/glygener/glygen-issues/assets/144174552/63af8721-63db-4031-a66d-be619d1930ad)

**Comment by rykahsay** [comment]
@Luke-Johnson-5  ... I think this is fine since a given glycan/protein document can have the word "human" mentioned in it some where but the glycan/protein is not necessarily human glycan/protein.

**Comment by Luke-Johnson-5** [comment]
Oh I see that makes sense
