### ISSUE TITLE
Download for glycan G49108TO looks different to other glycans

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1406]
When you download the results of a glycan search (in this case all glycans with a ChEBI xref), G49108TO results look very different to the other glycans (see below). It looks like the long list of glycoproteins have been split and added to separate cells in the row and the following few rows. I was wondering if the entire list of glycoproteins can be added to an individual cell under the "glycoprotein" column but I'm not sure if it's a limitation with the csv format.

![image](https://github.com/glygener/glygen-issues/assets/161866639/894f42f0-181c-4060-9b39-229cb33e1312)

**Comment by rykahsay** [comment]
Sorry, I cannot replicate the problem. Can you please reproduce the problem again and give me the download link again?

**Comment by katewarner** [comment]
@rykahsay Apologies, it was a problem with using Excel to open the csv. When I used a different program it looked perfect.
