### ISSUE TITLE
Updates to APIs (tissue expression)

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#141]
Change tissue expression in APIs to look like the following:

- Glycan details api
ex. https://api.tst.glygen.org/glycan/detail/G62765YT/
``` json
"tissue": {
    "name": "Synaptosomes",
    "namespace":"OMIT",
    "id": "0014437", 
    "url": "http://purl.obolibrary.org/obo/OMIT_0014437"
    }, 
```

- Protein details api
ex. https://api.tst.glygen.org/protein/detail/P31749-1/
``` json
"expression_tissue": [
{
    "tissue": {
    "name": "Kidney", 
    "namespace": "UBERON",
    "id": "0000082", 
    "url": "http://purl.obolibrary.org/obo/UBERON_0000082"
    }, 
```

--> Assign to @sujeetvkulkarni when this is done

**Comment by kmartinez834** [comment]
@sujeetvkulkarni once Robel is done with the above task, update Glycan details tissue expression section to look like this:

![image](https://user-images.githubusercontent.com/90285371/225442239-42b1cb57-b94a-4b6d-ae98-b6fc46694d6d.png)

**Comment by rykahsay** [comment]
Here are the namespaces I see in the data:
```
source_cell_line_cellosaurus_id  --> [CL, CVCL]
source_tissue_id  --> [UBERON, MESH, OMIT]
```

In sarscov2_proteoform_glycosylation_sites_unicarbkb.csv, the value "CL:0000738" was being given to source_tissue_id instead of source_cell_line_cellosaurus_id and I have taken the liberty to correct it. Please let me know if it is source_tissue_id

For each name space, I have created an entry on the generated/misc/xref_info.csv. Please edit and correct

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/20584876/225742192-9e0c40b5-9738-4f2a-af36-85fe1b02fbb8.png">

**Comment by kmartinez834** [comment]
"CL:0000738" should be treated as source_tissue_id.  Per the publication, the leukocytes were sourced from patient blood samples, not a cell line. 

Updated generated/misc/xref_info.csv:
```
tissue_xref_mesh,Medical Subject Headings,http://id.nlm.nih.gov/mesh/%s
tissue_xref_uberon,UBERON,http://purl.obolibrary.org/obo/UBERON_%s
tissue_xref_omit,Ontology for MIRNA Target,http://purl.obolibrary.org/obo/OMIT_%s
cell_xref_cvcl,Cellosaurus,https://web.expasy.org/cellosaurus/CVCL_%s
tissue_xref_cl,Cell Ontology,http://purl.obolibrary.org/obo/CL_%s
```

**Comment by kmartinez834** [comment]
@jeet-vora

**Comment by rykahsay** [comment]
<img width="625" alt="image" src="https://user-images.githubusercontent.com/20584876/226472820-cd239ab9-483a-4517-b61c-ff3da6925ed0.png">

**Comment by kmartinez834** [comment]
👍 API updated

Ready for @sujeetvkulkarni to make front end changes:

Ex. https://tst.glygen.org/glycan/G02815KT#Expression
![image](https://user-images.githubusercontent.com/90285371/226680483-c6b86a90-e1c7-417b-b996-01274ee7989b.png)

--> Make sure Cellosaurus ID appears in Cell Line Expression tab too:
![image](https://user-images.githubusercontent.com/90285371/226681415-3cf78366-e182-4d53-89b6-6248d3572764.png)

**Comment by sujeetvkulkarni** [comment]
@kmartinez834 
Do we have to do similar changes in Cell Line Expression tab?
remove Cellosaurus ID column and add everything in one column
cellLineName (namespace : id)

**Comment by kmartinez834** [comment]
@sujeetvkulkarni Right now, Cellosaurus is the only namespace for cell line.  Can we discuss with the group during the developer call Wednesday?

**Comment by sujeetvkulkarni** [comment]
@kmartinez834 we can but Robel has made similar changes at api level for cell line

**Comment by kmartinez834** [comment]
@sujeetvkulkarni Ok, I'm fine with the change to make everything one column named "Cell Line"

**Comment by sujeetvkulkarni** [comment]
8d1529212fc49c48e99486e2d3b9233bcbeb9d3b

**Comment by kmartinez834** [comment]
@ReneRanzinger @rykahsay 
Just FYI...the tissue ontologies are all either lowercase (ex. synaptosomes) or capitalized (ex. Sciatic Nerve).  Only cell line terms use mixed case (ex. BeWo, ZHBTc4).
