### ISSUE TITLE
Add ontology term ID and name to UnicarbKB datasets

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#143]
1. Add headers `"ontology_term_id","ontology_term_name"` to ***_proteoform_citations_glycosylation_sites_unicarbkb.csv** and ***_proteoform_glycosylation_sites_unicarbkb_glycomics_study.csv** datasets

2. Map `"term_id","term_name"` from **misc/sample_mapping.csv** to these new headers
-->End result should look like *_proteoform_glycosylation_sites_oglcnac_atlas.csv files

ex. rat_proteoform_glycosylation_sites_unicarbkb.csv
```
"uniprotkb_canonical_ac","glycosylation_site_uniprotkb","amino_acid","saccharide","glycosylation_type","xref_key","xref_id","src_xref_key","src_xref_id","start_pos","end_pos","start_aa","end_aa","site_seq","site_type","src_file_name","uckb_id","composition","curation_notes","additional_notes","pdb","swiss_model","abundance","source_tissue_id","source_tissue_name","source_cell_line_cellosaurus_id","source_cell_line_cellosaurus_name","ontology_term_id","ontology_term_name","n_sequon","n_sequon_type"
"Q00960-1","348","Asn","G62765YT","N-linked","protein_xref_unicarbkb","Q00960","protein_xref_unicarbkb","Q00960","348","348","Asn","Asn","N","known_site","known_34106099_glygen","G62765YT","HexNAc2Hex8dHex0NeuAc0NeuGc0Pent0S0P0KDN0HexA0","","","","","","OMIT:0014437; Synaptosomes","Synaptosomes","","","OMIT:0014437","Synaptosomes","NLS","NXS"
```

**Comment by rykahsay** [comment]
I have removed the fields:

"ontology_term_id","ontology_term_name" 

and moved the values to:

"source_tissue_id","source_tissue_name","source_cell_line_cellosaurus_id","source_cell_line_cellosaurus_name",
