### ISSUE TITLE
Biomarker Publications and Citations Page

### ISSUE THREAD

**Issue by DaniallMasood** [glygener/glygen-issues#1439]
From GlyGen "How to Cite" Page:

- [x] Remove GlyGen Logo download
- [x] Replace "Our Publications & Citations" with "Relevant Publications"
- [x] Remove all GlyGen related papers
- [x] Remove "Our Papers" and "Related Papers" and Website Citation and How to Cite (These can be added later)
- [x] Add "Relevant Papers" Page 
- [x] Add publication list from below

Publication List:

1. Lyman DF, Bell A, Black A, Dingerdissen H, Cauley E, Gogate N, Liu D, Joseph A, Kahsay R, Crichton DJ, Mehta A, Mazumder R. Modeling and integration of N-glycan biomarkers in a comprehensive biomarker data model. Glycobiology. 2022 Sep 19;32(10):855-870. doi: [/glycob/cwac046](https://academic.oup.com/glycob/article/32/10/855/6655823?login=true). PMID: [35925813](https://pubmed.ncbi.nlm.nih.gov/35925813/).
2. Gogate N, Lyman D, Bell A, Cauley E, Crandall KA, Joseph A, Kahsay R, Natale DA, Schriml LM, Sen S, Mazumder R. COVID-19 biomarkers and their overlap with comorbidities in a disease biomarker data model. Brief Bioinform. 2021 Nov 5;22(6):bbab191. doi: [/bib/bbab191](https://academic.oup.com/bib/article/22/6/bbab191/6278606?login=true). PMID: [34015823](https://pubmed.ncbi.nlm.nih.gov/34015823/).
3. Lyman D, Natale D, Schriml L, Anton K, Crichton DC, Mazumder R. Analysis of Biomarker Data Towards Development of a Molecular Biomarker Ontology. Proceedings of the International Conference on Biomedical Ontologies 2021 (ICBO 2021) co-located with the Workshop on Ontologies for the Behavioural and Social Sciences (OntoBess 2021) as part of the Bolzano Summer of Knowledge (BOSK 2021) Bozen-Bolzano, Italy. 2021 Sep 16-18; [ceur-ws.org](https://ceur-ws.org/).
4. Dingerdissen HM, Bastian F, Vijay-Shanker K, Robinson-Rechavi M, Bell A, Gogate N, Gupta S, Holmes E, Kahsay R, Keeney J, Kincaid H, King CH, Liu D, Crichton DJ, Mazumder R. OncoMX: A Knowledgebase for Exploring Cancer Biomarkers in the Context of Related Cancer and Healthy Data. JCO Clin Cancer Inform. 2020 Mar;4:210-220. doi: [10.1200/CCI.19.00117](https://ascopubs.org/doi/10.1200/CCI.19.00117). PMID: [32142370](https://pubmed.ncbi.nlm.nih.gov/32142370/).

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood 
Done. GitHub - 4777f226163f8a664b4ef1eb643ec417da9c65f0.
https://glygen.ccrc.uga.edu/frontend/
Please check and let me know.
