### ISSUE TITLE
Biomarker Our Mission Page

### ISSUE THREAD

**Issue by DaniallMasood** [glygener/glygen-issues#1440]
Changes to Our Mission Page from GlyGen

- [x] Our Mission (at the top)

"Provide computational and informatics resources and tools for biomarker research.
Integrate biomarker data and knowledge from diverse resources."

- [x] Get To Know Our Story

"Biomarker Partnership is a Common Fund Data Ecosystem ([CFDE](https://commonfund.nih.gov/dataecosystem)) sponsored project to develop a knowledgebase that will organize and integrate biomarker data from different public sources. The data will be connected to contextual information to show a novel systems-level view of biomarkers.

The motivation for this project is to improve the harmonization and organization of biomarker data. This will be done by mapping biomarkers from public sources to, and across, CF data elements. This mapping will bridge knowledge across multiple Data Coordinating Centers (DCCs) and biomedical disciplines."

- [x] Our Goals

- Mapping biomarkers from public sources to relevant data elements.
- Mapping contextual data from participating DCCs.
- Developing a framework for organizing biomarker data.
- Creating tools for querying and exploring biomarker data.
- Disseminating the results of this project to the research community.

- [x] The GlyGen Global Effort - remove

- [x] What We Do

- Improved access to biomarker data.
- Increased understanding of the relationships between biomarkers and disease.
- Facilitated drug development and clinical trials.
- Improved personalized medicine.
- Improved searching and filtering for biomarker data.

- [x] Biomarker Partnership Funding

The [CFDE](https://commonfund.nih.gov/dataecosystem) Biomarker Partnership is funded by the [National Institutes of Health Office of Strategic Corrdination - The Common Fund](https://commonfund.nih.gov/) under the grant # [1OT2OD032092](https://reporter.nih.gov/project-details/10397274).

- [x] Collaborators

Principal Investigators:

- Raja Mazumder ([GlyGen](https://www.glygen.org/))
- Michael Tiemeyer ([GlyGen](https://www.glygen.org/))
- Christophe Lambert ([IDG](https://commonfund.nih.gov/idg))
- Jeremy Yang ([IDG](https://commonfund.nih.gov/idg))
- Shankar Subramaniam ([MW](https://www.metabolomicsworkbench.org/))
- Avi Ma'ayan ([LINCS](https://lincsproject.org/))
- Jonathan Silverstein ([SN/HuBMAP](https://hubmapconsortium.org/))
- Nicola Neretti ([SN/HuBMAP](https://hubmapconsortium.org/))

Project Managers:

- Daniall Masood [(GlyGen)](https://www.glygen.org/)
- Sean Kim [(GlyGen)](https://www.glygen.org/)
- Grace Faustino ([IDG](https://commonfund.nih.gov/idg))
- Mano Maurya ([MW](https://www.metabolomicsworkbench.org/))
- Sherry Jenkins ([LINCS](https://lincsproject.org/))
- Jesse Helfer ([SN/HuBMAP](https://hubmapconsortium.org/))

Consultants:

- Darren Natale
- Nikolai Daraselia

Remove logos below

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood 
Done. GitHub - 4777f226163f8a664b4ef1eb643ec417da9c65f0.
https://glygen.ccrc.uga.edu/frontend/
Please check and let me know.
