### ISSUE TITLE
My Biomarker Pages

### ISSUE THREAD

**Issue by DaniallMasood** [glygener/glygen-issues#1441]
Same as My GlyGen pages

- [x] Privacy Settings Page (just replace GlyGen with Biomarker Partnership)

"Biomarker Partnership is NOT currently monitoring your searches; you can improve/streamline your searches by allowing Biomarker Partnershipto monitor your interaction with our system. For example, your searches can be recorded so you can review them at a later date. [Learn more.](https://github.com/glygener/glygen-frontend/wiki/Logging-user-activity)"

- [x] License Page 

"We have chosen to apply the [Creative Commons Attribution 4.0 International (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/) license to all our database sets. This means that you are free to copy, distribute, display and make commercial use of these databases in all legislations, provided you give us credit.

The source code of the project is released under [MIT License](https://opensource.org/license/mit) and is available in our [Biomarker Partnership GitHub ](https://github.com/clinical-biomarkers/biomarker-partnership)repository.

Licenses for databases:

- [Disease Ontology](https://disease-ontology.org/resources/): [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/)
- [UniProtKB](https://www.uniprot.org/help/uniprotkb): [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
- [ChEBI](https://www.ebi.ac.uk/chebi/aboutChebiForward.do): [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
- [GlyTouCan](http://code.glytoucan.org/sitePolicy/): [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
- [NCBI PubChem](https://pubchem.ncbi.nlm.nih.gov/): [NCBI License](https://www.ncbi.nlm.nih.gov/home/about/policies/)
- [NCBI PubMed](https://www.ncbi.nlm.nih.gov/pubmed/): [NCBI License](https://www.ncbi.nlm.nih.gov/home/about/policies/)
- [PRO](http://www.obofoundry.org/ontology/pr.html): [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
- [OpenTargets](https://www.opentargets.org/): [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/)
- [GWAS](https://www.ebi.ac.uk/gwas/home): [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/)
- [ClinVar](https://www.ncbi.nlm.nih.gov/clinvar/): [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
- [UBERON](https://obophenotype.github.io/uberon/): [CC BY 3.0](https://creativecommons.org/licenses/by/3.0/)
- [LOINC](https://loinc.org/): [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)

- [x] Privacy Policy Page

replace 'GlyGen' with "biomarker Partnership" whenever GlyGen is mentioned
Effective Data: July 1, 2024

- [x] Disclaimer Page

replace 'GlyGen' with "biomarker Partnership" whenever GlyGen is mentioned
Effective Data: July 1, 2024

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood 
-  Privacy Settings Page (just replace GlyGen with Biomarker Partnership)

In this Learn More link points to glygen github examples, which is fine for time being but you might want to change it in future.

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood 
Done. GitHub - 4777f226163f8a664b4ef1eb643ec417da9c65f0.
https://glygen.ccrc.uga.edu/frontend/
Please check and let me know.

**Comment by DaniallMasood** [comment]
![image](https://github.com/glygener/glygen-issues/assets/116293652/bacc7aa2-4da3-4d23-8f5c-dd9016cb17ab)
@sujeetvkulkarni bottom of the page still says “My GlyGen”

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood Have fixed it. Please check.
