### ISSUE TITLE
Biomarker Help Pages

### ISSUE THREAD

**Issue by DaniallMasood** [glygener/glygen-issues#1442]
Reformat GlyGen Help Pages for biomarker partnership

- [x] Remove Tutorials, Documentations pages
- [x] Can link FAQ page to https://hivelab.biochemistry.gwu.edu/biomarker-partnership/data/static/faq
- [x] Contact Us Page

- Is it possible to change where the message goes (maybe my email if anyone decides to send a message through there: daniallmasood@gwu.edu)
- Also remove locations

- [x] Feedback Page

Same as above. if comments can be linked to my email but if not then it can be removed

**Comment by sujeetvkulkarni** [comment]
- Is it possible to change where the message goes (maybe my email if anyone decides to send a message through there: [daniallmasood@gwu.edu](mailto:daniallmasood@gwu.edu))

@DaniallMasood yes, you have to do it in API, @seankim658 needs to modify contact us related api.

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood 
-  Feedback Page
It is google form, so you have to create your own google form with the questionnaire. So, for now I will remove it.

**Comment by DaniallMasood** [comment]
@sujeetvkulkarni that is fine. I will work on Google form and get back to you later

**Comment by seankim658** [comment]
Contact endpoint is done and working.

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood 
Done. GitHub - 4777f226163f8a664b4ef1eb643ec417da9c65f0.
https://glygen.ccrc.uga.edu/frontend/
Please check and let me know.
