### ISSUE TITLE
Create new triples connecting enzyme EC number and reaction ID

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1443]
Triples like this (this is for Rhea but I also want the same for Reactome reaction IDs):

```
<http://rdf.rhea-db.org/69607> <https://sparql.glyge.org/ontology/hasEnzyme> <http://purl.uniprot.org/enzyme/2.3.1.308> .
```

![image](https://github.com/glygener/glygen-issues/assets/20584876/6d956be5-e1f8-44d1-b262-39edba253d62)

**Comment by pv47** [comment]
This is available in 2024_04 datasets: https://ftp.ebi.ac.uk/pub/contrib/glygen/current_release/

bash-4.4$ zgrep hasEnzyme uniprot-proteome-homo-sapiens.nt.gz | grep 69607
<http://rdf.rhea-db.org/69607> <https://sparql.glygen.org/ontology/hasEnzyme> <http://purl.uniprot.org/enzyme/2.3.1.308> .


bash-4.4$ zgrep -c hasEnzyme uniprot-proteome*
uniprot-proteome-arabidopsis-thaliana.nt.gz:1250
uniprot-proteome-dictyostelium-discoideum.nt.gz:636
uniprot-proteome-drosophila-melanogaster.nt.gz:692
uniprot-proteome-gallus-gallus.nt.gz:984
uniprot-proteome-hepatitis-c-virus-1a.nt.gz:3
uniprot-proteome-hepatitis-c-virus-1b.nt.gz:3
uniprot-proteome-homo-sapiens.nt.gz:1632
uniprot-proteome-mus-musculus.nt.gz:1606
uniprot-proteome-rattus-norvegicus.nt.gz:1390
uniprot-proteome-saccharomyces-cerevisiae.nt.gz:868
uniprot-proteome-sars-coronavirus.nt.gz:5
uniprot-proteome-sars-cov-2.nt.gz:5
uniprot-proteome-sus-scrofa.nt.gz:1094

**Comment by pv47** [comment]
@rykahsay please take a look
