### ISSUE TITLE
LmSite curation tasks

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1444]
Here are some of the LmSite curation assignments, please go to https://data.dev.glygen.org/lmsite/LMS_0000002/recordlist sort the table by the field "set_gw_new_pass" field and find your PMIDs assigned to you below. Then click on the link and set the curation drop downs after reading the sentences.

<google-sheets-html-origin><style type="text/css"></style>
Cyrus | 1314561
-- | --
Cyrus | 12956774 ✅
Cyrus | 8702840 ✅
Cyrus | 25944660 ✅
Cyrus | 8344946 ✅
Cyrus | 34322281 ✅
Cyrus | 28630087 ✅
Cyrus | 26567221 ✅
Cyrus | 17259069 ✅
Cyrus | 10887202 ✅
Karina | 10864452 ✅
Karina | 22516225 ✅
Karina | 36149962 ✅
Karina | 35931119 ✅
Karina | 25585345 ✅
Karina | 36266488 ✅
Karina | 33709491 ✅
Karina | 27690717 ✅
Karina | 25628020 ✅
Karina | 16401092 ✅
Kate | 34631661 ✅
Kate | 15869464 ✅
Kate | 34981854 ✅
Kate | 35126971✅
Kate | 24509848✅
Kate | 35467332✅
Kate | 33273015✅
Kate | 26854602✅
Kate | 25502804✅
Kate | 15379548✅
Luke | 26784534 ✅
Luke | 26585416 ✅
Luke | 9572875 ✅
Luke | 28776757✅
Luke | 12093813✅
Luke | 34662441✅
Luke | 28753425✅
Luke | 26620801✅
Luke | 23878260✅
Luke | 1150658 (?)
Urnisha | 29915530✅
Urnisha | 32028604✅
Urnisha | 11511810✅
Urnisha | 29427759✅
Urnisha | 24403531✅
Urnisha | 34869209✅
Urnisha | 31014754✅
Urnisha | 26797772✅
Urnisha | 24526702✅
Urnisha | 14670950 - Not present

**Comment by Luke-Johnson-5** [comment]
28776757: This ID does not refer to a site on a protein with the text mining. This refers to times.

**Comment by Luke-Johnson-5** [comment]
Finished my assigned portion. However, ID: 1150658 is not showing up on the site. @rykahsay

**Comment by kmartinez834** [comment]
Finished.  

Note, PMID:16401092 does not have a pull-down for Thr - 156, although it is highlighted in the abstract

**Comment by katewarner** [comment]
Completed. 
15869464 - highlights phosphorylation and glycosylation sites, but most of the returned sites are the phosphorylation sites.

24509848 - only returned phosphorylation sites

15379548 - glycosylation sites are highlighted but are not in the drop downs. The drop down only show disulphide bond sites.

**Comment by ubhuiyan** [comment]
Completed

PMID: 11511810 Does not have a pull-down for Asn-60, Asn-105. 

I couldn't find PMID: 14670950.
