### ISSUE TITLE
DOI/10.1101/2023.09.13.557529v1 missing on PRD

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1446]
I added 10.1101/2023.09.13.557529v1 to generated/datasets/compiled/doi_citations.csv but it still hasn't been created on PRD:

https://glygen.org/publication/DOI/10.1101/2023.09.13.557529v1
![image](https://github.com/glygener/glygen-issues/assets/90285371/865b5365-d1cc-4a5b-bf3b-48379641e44f)

**Comment by rykahsay** [comment]
Check now

<img width="1094" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/b3449127-041a-418b-a235-0553f27301f4">

**Comment by kmartinez834** [comment]
Working now. 

Unfortunately, the v1 at the end of the URL is only for bioRxix, so the doi.org/ link is broken.  I corrected the compiled/doi_citations.csv file:

```
"10.1101/2023.09.13.557529","Deep quantitative glycoproteomics reveals gut microbiome induced remodeling of the brain glycoproteome","bioRxiv","2023","Potel C.M., Burtscher M.L., Garrido-Rodriguez M., Brauer-Nikonow A., Becher I., Typas A., Zimmermann M., Savitski M."
```

**Comment by rykahsay** [comment]
Oh ... it is better to tolerate this for 2.5, I don't want to update all the objects in prd and introduce other potential issues.

**Comment by kmartinez834** [comment]
Ok that is fine
