### ISSUE TITLE
Provide enzyme mapping script to Nathan

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1449]
Per F2F developer meeting, Nathan will add a Sandbox enzyme file to his export.  Here's the script I'm using to generate the enzyme mapping file for UGA (see #814 for file usage):

https://github.com/kmartinez834/glygen-software/raw/main/software/enzyme-mapping.py

Input files are here:
https://data.glygen.org/ln2downloads/sandbox/current/glycotree_annotated_glycans.tsv
https://data.glygen.org/ln2data/releases/data/v-2.5.1/misc/species_info.csv

The output file can be accessed here:
https://data.glygen.org/ln2downloads/export_files/for_uga/enzyme_mapping.json

**Comment by edwardsnj** [comment]
Sandbox enzyme dump files are now provided as part of the GlycanData export.
