### ISSUE TITLE
File name clean up

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1452]
We need to clean up our own file names...
OGlcNAcDB = oglcnac_mcw = oglcnacdb (All of the files have the mcw suffix except for xref files, which have db)
OGlcNAc Atlas = oglcnac_atlas (edited) 

For DB, use the proteoform datasets *_proteoform_glycosylation_sites_oglcnac_mcw.csv instead of *_protein_xref_oglcnac_db.csv (this is a cross ref file)

**Comment by kmartinez834** [comment]
I think we can close this ticket, action item is now documented in #1470

**Comment by katewarner** [comment]
Okay thanks
