### ISSUE TITLE
Confirm Arabidopsis names for 2.6

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1454]
@ReneRanzinger we are proposing the following names for Arabidopsis.  Note "Mouse-ear cress" is the common name according to UniProt.  Can you confirm or change if needed?

tax id | file prefix | scientific name | common name | glygen name
-- | -- | -- | -- | --
3702 | arabidopsis | Arabidopsis thaliana | Mouse-ear cress | Arabidopsis

FYI @jeet-vora @ubhuiyan @katewarner @Luke-Johnson-5 @CyrusAY @rykahsay

**Comment by ReneRanzinger** [comment]
Arabidopsis
