### ISSUE TITLE
2.6 | Master List for Data Download

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1455]
| Resource | Downloaded by |Completed (Y/N)| Notes | Issue | 
| -------- | ------- | ------- | ------- |------- |
| Cellosaurus |Urnisha|Y| | |
| ChEBI|Urnisha|Y| | |
| MatrixDB |Urnisha|Y| | |
| Reactome | Urnisha| Y |  | |
| Glyconnect | Urnisha | Y|New Species |
| IPTMnet| Urnisha|Y | | |
| MCW O-GlcNAc  |Urnisha | Y | New Species| |
| OMA |Urnisha | Y |New Species | |
| O-GlcNAcAtlas| Urnisha |Y  |Updated Download Script + New Species | |
|Genomics England |Kate | Y |  | |
|Genome Alliance |Kate | Y |  | |
|MGI |Kate | Y |  | |
|Mondo |Kate | Y |  | |
|EBI | Kate | Y |  | |
|NCBI RefSeq | Kate| Y |Updated Download Script + New Species  | |
|Disease Ontology |Kate | Y |  | |
|Glycohydrolase (arabadopsis) | Kate |  |  | |
|Glycosyltransferase (arabadopsis) | Kate |  |  | |
|PRIDE xref dataset |Kate |  |  | |
|MassIVE xref dataset | Kate|  |  | |
|FlyBase Linkout File | Kate |  |  | |
|user submission | Kate |  |  | |

[Proteoform and Protein Data Download Doc](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/doc2.aspx?sourcedoc=%7BE6511E4F-F88A-452F-AB40-DAE665A5E949%7D&file=Data%20Download%20-%20Proteoform.docx&action=default&mobileredirect=true)

**Comment by kmartinez834** [comment]
@ubhuiyan @katewarner Please add any new resources' downloads to the table as well

**Comment by katewarner** [comment]
@kmartinez834 @ubhuiyan I've added the new resources. I'm not sure who's working on the Massive and Pride datasets so will ask Jeet at next scrum.
