### ISSUE TITLE
BCOs with multiple output files not accessible in data.glygen.org

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1456]
For 2.6, need to think about how to handle this...

Ex. https://data.tst.glygen.org/GLY_000622

**Comment by kmartinez834** [comment]
Modify dataset viewer and downloads to show all output files (or give user a dropdown to select the file they want to view/download)

See the example above.

**Comment by rykahsay** [comment]
This will require too much effort and I think we can afford to ignore it for now
