### ISSUE TITLE
2.5 Release notes

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#1457]
- [x] Add data release notes to https://wiki.glygen.org/Data_release_notes#Version_2.5.1
- [x] Copy the same release notes add to https://wiki.glygen.org/Data_release_notes/2.5.1 (Link under Main article)
- [x] From the data release select 3-4 top/major data items and add to the portal release notes https://wiki.glygen.org/Portal_release_notes

For new data items compilation, check you tickets and issues for the release.
Ensure you have access to the wiki.

Once added let me and Karina know.

**Comment by ubhuiyan** [comment]
@katewarner I've added a few updates on the glycan/proteoform end. Please feel free to add anything on the protein end and assign to Karina/Jeet once completed!

**Comment by katewarner** [comment]
@ubhuiyan looks good to me

**Comment by ubhuiyan** [comment]
@kmartinez834 and @jeet-vora please check, let me know if there's anything else I should add, otherwise please close if satisfied.

**Comment by kmartinez834** [comment]
Made some changes:

- Deleted comment about OMA, we don't need to mention changes to source files, only changes to output files on data.glygen.org
- Updated comment about xrefs
- Added notes about the other new files, and links to datasets
