### ISSUE TITLE
Create dataset-masterlist.csv

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1460]
For new arabidopsis files only, see example from previous release at /data/projects/glygen/generated/misc/dataset-masterlist.csv

You can overwrite the old file and save as dataset-masterlist.csv

--> Tag @kmartinez834 @jeet-vora 
--> Create tickets for Robel to update dataset-masterlist.json & process protein datasets

**Comment by katewarner** [comment]
@jeet-vora @kmartinez834 @ubhuiyan - please review the new dataset-masterlist file. I've  temporarily called it: /data/projects/glygen/generated/misc/dataset-masterlist_kw
#1450

**Comment by kmartinez834** [comment]
You can remove the following lines, as they've already been added to dataset-masterlist.json:
- human,protein,disease_alliance_genome,csv
- chicken,protein,xref_oglcnac_mcw,csv
- chicken,proteoform,citations_glycosylation_sites_glyconnect,csv

Also remove these:
- arabidopsis,proteoform,glycosylation_sites_o_gluc,csv (this source file is human only)
- arabidopsis,proteoform,glycosylation_sites_literature,csv (this source file is human only)

And add these lines:
- arabidopsis,proteoform,citations_glycation_sites_uniprotkb,csv
- arabidopsis,proteoform,citations_glycosylation_sites_literature_mining,csv
- arabidopsis,proteoform,citations_phosphorylation_sites_iptmnet,csv

Thanks!

**Comment by katewarner** [comment]
Thank you @kmartinez834 I made all your corrections.

**Comment by katewarner** [comment]
@ubhuiyan @jeet-vora I've changed the file name to /data/projects/glygen/generated/misc/dataset-masterlist.csv so that Robel can start processing.

**Comment by ubhuiyan** [comment]
@kmartinez834 should `arabidopsis,proteoform,citations_glycosylation_sites_literature_mining,csv` be removed given what Jeet mentioned today?

**Comment by kmartinez834** [comment]
@ubhuiyan Since the csv file is already with Robel, let's wait for him to finish #1469 then we can remove these files from `dataset-masterlist.json`
