### ISSUE TITLE
Sequence viewer position number change +10 to 10 and move the top level marker

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1464]
![Screenshot 2024-06-21 at 11 51 55 AM](https://github.com/glygener/glygen-issues/assets/13891482/dbfeda31-7afa-4ef1-b859-3171ee32f63c)

**Comment by ReneRanzinger** [comment]
We decided to remove the +10 line entirely.

**Comment by sujeetvkulkarni** [comment]
removed the +10 line from all places sequence viewer is shown.
protein details - sequence, isoforms, homologs.
