### ISSUE TITLE
Backend should not send site information in case of isoforms for blast results.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1465]
Raja's email

---
Is this usecase supported?

I am a user with several glycosylation sites in different proteins that I identified and have published :) and now I want to share my list with GlyGen. I am trying to do the mapping to the canonical sequence manually and also retain any isoform information if relevant.
D2JYI1 -> 95
I go to GlyGen and notice that the  D2JYI1  search does not retrieve any results
I then plug that accession into GlyGen BLAST to get this mapping and notice that the N-linked site highlight system might be wrong for the best hit (P37173-2). So I manually identify my site (https://glygen.org/blast-result/193)

D2JYI1 -> 95 | P37173-2 -> 95 (0% gap, 100% identity),  | P37173-1 -> 70 (4% gap, 96% identity)

It would be nice if I can upload a list of such accessions and get canonical sequence mapping and also the isoform best mapping + % gap + % identity

See incorrect N-linked highlights below

![image](https://github.com/glygener/glygen-issues/assets/13891482/67c81119-bc9e-412f-8c80-7a217808d78c)

Image from where I manually mapped to canonical
![image](https://github.com/glygener/glygen-issues/assets/13891482/7ec98eea-2311-4a18-9720-4cc8a9f7c4e9)
---

Site information should only be sent for [P37173-1](https://glygen.org/protein/P37173-1) but not for [P37173-2](https://glygen.org/protein/P37173-1).

https://api.glygen.org/job/results/?query={%22jobid%22:193}
![Screenshot 2024-06-21 at 1 11 37 PM](https://github.com/glygener/glygen-issues/assets/13891482/b97b7456-3068-4ded-82d7-136dfc130d4f)

**Comment by rykahsay** [comment]
Fixed, please check

**Comment by sujeetvkulkarni** [comment]
done.
