### ISSUE TITLE
Please review new datasets in dataset-masterlist.json

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1466]
I've added the datasets that required new objects (see #1450) to the dataset-masterlist.json. Except the "xref_flybase" already had an object and the "xref_carbabnk" object, which Urnisha is going to be complete. Please let me know if I've made any mistakes. I've temporarily called it: /data/projects/glygen/generated/misc/dataset-masterlist_tmp.json   

I called the user submission "glycosylation_sites_larance_1338" - larance is the submitters name and 1338 is the github ticket. I can change it to something else

**Comment by kmartinez834** [comment]
flybase will need new object specific to flybase linkout (see other objects ending in _linkout for example)

@ubhuiyan --> carbbank will need proteoform object (see glycosylation_sites_unicarbkb for example) 

Other changes to dataset-masterlist_tmp.json look good to me

**Comment by katewarner** [comment]
@ubhuiyan I've changed the file name to /data/projects/glygen/generated/misc/dataset-masterlist.json so that Robel can start processing the protein datasets. If you notice any mistakes can you make the changes to the file. Thanks

**Comment by rykahsay** [comment]
Few items here:
- *_proteoform_glycosylation_sites_larance_1338 is too specific (you will need to create BCO for every individual user), I would say *_proteoform_glycosylation_sites_user_submission --> which will contain all user submitted glycosylationd ata
- I need "instructions ticket for making new dataset" to create  *_proteoform_glycosylation_sites_user_submission  datasets
- I need "instructions ticket for making new dataset" to create  *_proteoform_glycosylation_sites_carbbank  datasets

The above items are a blocker for me to finish creating datasets -- introducing delay to our milestone
