### ISSUE TITLE
Please process the protein datasets for 2.6

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1467]
Please process the following downloaded protein datasets for 2.6. The EBI and NCBI datasets include the new organism Arabidopsis.

/data/projects/glygen/downloads/genomics_england/current
/data/projects/glygen/downloads/mgi/current
/data/projects/glygen/downloads/mondo/current
/data/projects/glygen/downloads/ebi/current
/data/projects/glygen/downloads/ncbi/refseq/current
/data/projects/glygen/downloads/do/current

**Comment by rykahsay** [comment]
I am wondering why you think I should create the following datasets (based on presence of corresponding triples in the nt files):
  
dicty_protein_xref_pride.csv 
chicken_protein_xref_pride.csv 

Please update the dataset-masterlist.json if you think these datasets should not be created.

**Comment by katewarner** [comment]
You're right, these species don't currently have any Pride xrefs in UniProt, so the datasets shouldn't be created for these species. 

I've updated the dataset-masterlist.json and removed these species from the Pride object.
