### ISSUE TITLE
Test APIs on tst server

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#147]
Please test the APIs using the swagger page ONLY (I will be doing the automated test myself) and report the issues you finding by creating tickets labeled "backend_api"

Also, test the frontend (tst.glygen.org) and any issues you find, try to drill down the corresponding API issue if you can and report your API issue findings by creating tickets labeled "backend_api". If the issue is not caused by API, then create a ticket for Sujeet and label them "frontend"

**Comment by rykahsay** [comment]
Some of the APIs require authentication -- please skip these API from your test.

- video APIs
- event APIs
- auth APIs

**Comment by JingyueWu** [comment]
@kmartinez834 @jeet-vora 

I have finished all the API testing on Swagger (except video, event, and auth APIs as Robel said above) and all of them are working.

The only tricky one was data/download/ as I got an error code 500 in my first try. Then I saw that it was asking for glycan list, so I figured I need to get it from /glycan/search from the above. Did so, entered 2316faab272e5ecd9522d547f67c9d82 and got success. 

Please let me know if you need anything else.
