### ISSUE TITLE
Change name of all mcw datasets

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1470]
Hold off on the following.  See comment below for Jeet.

~~The name of all OGlcNAc MCW datasets (*_oglcnac_mcw*) need to be changed to *_oglcnac_db*~~

~~--> Update dataset-masterlist.json~~
~~--> Create ticket for Robel letting him know which files have changed and which dataset rely on these files (check usage logs)~~
~~--> Update output domain of BCOs~~

**Comment by kmartinez834** [comment]
Wait for Robel to finish #1469 before making changes to the json

**Comment by kmartinez834** [comment]
@jeet-vora we are using "mcw" everywhere (downloads folder, download file names, proteoform datasets, citations datasets) except for the xref output files.

For consistency, and to avoid making changes to all of the above, I think we should continue using mcw for all of the files.  We can leave the badge as O-GlcNAc Database. Changing the above to db will require updates to both Robel and Nathan's pipelines - not worth it I think.

**Comment by ubhuiyan** [comment]
I have checked all the files listed with "mcw," and agree with Karina that this would be a big change to switch to db. We can keep mcw for our internal files and maintain O-GlcNAc Database as the public badge as Karina has suggested. I can make sure of this when we begin creating BCOs for 2.6.
