### ISSUE TITLE
Draft Files for Nathan 

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1471]
### files4nathan.csv

| File Name | Path | Source | GlyGen Datasets | PMID | PMID Field | Notes
| --- | --- |--- |--- |--- |--- |--- |
|arabidopsis_o_glcnacome_mcw.csv| mcw_oglcnac/current/| OGlcNAcDB|GLY_001049:Arabidopsis|   | PMIDS
|ambiguous_sites.csv | atlas_oglcnac/current/| OGlcNAcAtlas| GLY_000708:Human,GLY_000709:Mouse,GLY_000710:Rat,GLY_000711:FruitFly,GLY_000800:Yeast,GLY_000955:Pig,GLY_000962:Chicken,GLY_001050:Arabidopsis| | pmid
|unambiguous_sites.csv | atlas_oglcnac/current/ | OGlcNAcAtlas| GLY_000708:Human,GLY_000709:Mouse,GLY_000710:Rat,GLY_000711:FruitFly,GLY_000800:Yeast,GLY_000955:Pig,GLY_000962:Chicken,GLY_001050:Arabidopsis||||
1-s2.0-S1535947624000070-mmc5.xlsx |user_submission/platelet_o_linked/current| UserSubmission|GLY_001051:Human| 38237698 |||
1-s2.0-S1535947624000070-mmc7.xlsx |user_submission/platelet_o_linked/current/| UserSubmission|GLY_001051:Human| 38237698 |||
glyconnect_arabidopsis.json| glyconnect/current/ | GlyConnectCompositionGlyConnectStructure | |pmid|
PubChem_substance_compound.csv| snfg/current/ | SNFG| |||for snfg xref file, see readme|
sia-table2.tsv| snfg/current/ |SNFG | | | |for snfg xref file, see readme| 

### README
**Updates for 2.6 release:**

1. Please use the SNFG files to create an SNFG xref file and map these SIDs/CIDs to GlyTouCan. These files also contain names, which you might be able to add to your names.tsv file. Ticket #843 has more information. 
2. Added arabidopsis for glyconnect, mcw, and dataset ID to OGlcNAcAtlas rows
3. New user submitted data added

**Comment by ubhuiyan** [comment]
@kmartinez834 Can you take a look at what I have so far and let me know if I am missing something?

Will finish creating BCOs tomorrow.

**Comment by kmartinez834** [comment]
Please add glyconnect also

**Comment by kmartinez834** [comment]
Updates for user submitted file (glycosylation_sites_larance_1338):

- glycosylation_sites_larance_1338: This is the output file name, need to find out from @katewarner what the input is called
- Path is wherever the above is stored in the downloads folder, need to find out from Kate
- Source should be the name of the folder (ex. user_submission) - need to discuss during dev meeting, as this will apply to other files associated with a single publication

**Comment by katewarner** [comment]
There are two input files for glycosylation_sites_larance_1338. If we keep the file names as they are in the publication, they are called: 
1-s2.0-S1535947624000070-mmc5
1-s2.0-S1535947624000070-mmc7

**Comment by kmartinez834** [comment]
@katewarner 
1. Please create a folder in downloads named `user_submission`
2. To keep the files organized, please create a subfolder named `larance_1338`, then create another subfolder with today's date (ex. `2024_06_26`)
3. Add these files to `downloads/user_submission/larance_1338/2024_06_26/`
4. Create `current` symbolic link
5. Create BCO (you only need to populate BCO name and output domain for now), provide BCO id to Urnisha

@ubhuiyan 
1. Make path for these files `user_submission/larance_1338/current`
2. Update BCO id once provided by Kate

**Comment by ubhuiyan** [comment]
@katewarner I've pushed my updated to files4nathan.csv and README. Could you create the user_submission folder and add the data soon? Currently getting an error message since the folder doesn't exist atm.

**Comment by katewarner** [comment]
@ubhuiyan and @kmartinez834  Sorry for the delay. Jeet wanted us to change the name of the folder/user submission so both excel files are in:  
`/data/projects/glygen/downloads/user_submission/platelet_o_linked/2024_06_26`

The BCO name could be: "Human blood platelet O-Glucosylation Glycosylation Sites"
The output domain will be: "human_proteoform_glycosylation_sites_platelet_o_linked.csv"

**Comment by kmartinez834** [comment]
@ubhuiyan just need to update files4nathan.csv with the new path that Kate mentioned above

**Comment by ubhuiyan** [comment]
I've updated the path. Will wait for the BCO ID then notify Nathan.
