### ISSUE TITLE
Add reducing end monosaccharide to General section of glycan details page

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1472]
![image](https://github.com/glygener/glygen-issues/assets/90285371/0934b678-eac1-426e-87bf-5f87eaa13119)

This will require updating the API:
https://api.glygen.org/glycan/detail/G59722IA

Ex.
  "red_end_mono": GlcNAc,

--> This will require either a new dataset or change to existing dataset (for example, add red_end column to glycan_masterlist.csv). Add to next developer meeting agenda to discuss with Robel

**Comment by ReneRanzinger** [comment]
@kmartinez834  will assign ticket to Robel and he decides on the dataset  it will be added. Karina will document this better first.
