### ISSUE TITLE
Updating help links on the website so they direct user to FAQ page

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1473]
I noticed that on the website, the help button "read more" link for "UniProtKB Accession", "RefSeq Accession" and "Gene name" on the Protein advanced search takes you to the respective databases home page.

<img src="https://github.com/glygener/glygen-issues/assets/161866639/e37274f8-0f6b-4781-b36c-609dc8cdfe42" width="200" />

I think that we should keep the user within the website pages as much as possible, so I think it would be better if the help links take you to the GlyGen FAQ wiki page ([Frequently Asked Questions - GlyGen Wiki](https://wiki.glygen.org/Frequently_Asked_Questions)) to the section where all these questions are already answered. Then within the FAQ answers (if they're not there), we add links to the databases where they have further information.

**Comment by ReneRanzinger** [comment]
If you have better pages to link to. Please send them to @sujeetvkulkarni as tickets and he can change them.

**Comment by katewarner** [comment]
Closed for now - waiting for wiki pages to be updated

**Comment by katewarner** [comment]
Closed for now - waiting for wiki pages to be updated. Will send new link pages to Sujeet as new tickets
