### ISSUE TITLE
Integrating PDB and Alphafold structures from UniProt

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1476]
Can Preethi give us the PDB and Alphafold 3D structure files for all the organisms (and perhaps proteins) in GlyGen?

Once we have the files Robel will filter them to create a dataset of the best structures to provide within the GlyGen protein entries. 

**Blocker for:**
* #1517 
* #1518 
* #1489

**Comment by ReneRanzinger** [comment]
Related to 
* #1354 
* #1355
