### ISSUE TITLE
2.6 Glycan files ready for Nathan

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1479]
All changes for 2.6 have been applied to https://github.com/glygener/glygen-glycan-pipeline. Please proceed with glycan export processing.

fyi
@kmartinez834

**Comment by edwardsnj** [comment]
@ubhuiyan Could I request the .xlsx files be transformed to .tsv (or .csv) (user_submission/platelet_o_linked/current/*.xlsx) before I process them. This will resolve the question of which sheet is desired, too.

**Comment by ubhuiyan** [comment]
@edwardsnj I will convert the .xlsx to .tsv files where each sheet will be its own .tsv and update files4nathan accordingly. 

For example:  1-s2.0-S1535947624000070-mmc5_sheet1.tsv, 1-s2.0-S1535947624000070-mmc5_sheet2.tsv. 

Please let me know if you prefer an alternate naming convention. Otherwise, I will go ahead with the example I've provided. 

Just a heads up: 
The first sheet is the most important for each of the two .xlsx files provided. Feel free to look through the other files if you'd like more context, but I'm told the first sheet in both .xlsx files are the only ones you would need.

**Comment by edwardsnj** [comment]
Great, thanks! I agree that the first sheet in each is the only sheets that appear to be relevant to me.
