### ISSUE TITLE
Add Reducing End Mapping for General Section of GlyCan Detail Page 

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1480]
**Source File:** ` /data/projects/glygen/downloads/glytoucan/current/export/redendmono.tsv`

**Mapping Files:** 
```
mono_mapping.json 
monosaccharide_residue_name.csv
```

**Mapping Instructions:** 
1. Map each glycan structure to the most specific residue available in `mono_mapping.json`, where if the number of entries is more than one, choose the child term.

Ex: G59722IA can have a residue of HexNAc or GlcNAc. Final row would appear: 

| Accession | Reducing End |
| --- | --- |
|G59722IA| GlcNAc|                    
2. Then map each of the specific residues to their corresponding CIDs using `monosaccharide_residue_name.csv`.

Ex: 

| Accession | Reducing End | CID|
| --- | --- | --- |
|G59722IA| GlcNAc| 439174|

3. Add to existing glycan dataset.

4. Add to glycan detail APIs.

Ex: 
```
"redendmono": [
    {
      "name": "N-Acetylhexosamine",
      "residue": "hexnac",
      "cid": "899",
      "url": "https://pubchem.ncbi.nlm.nih.gov/compound/899"
    }
```

**Comment by rykahsay** [comment]
I have done the first part -- adding the information in the unreviewed/glycan_masterlist.csv dataset (created using old data). Please check and make sure that the selection algorithm is working correctly:

```
$ head unreviewed/glycan_masterlist.csv 
"glytoucan_ac","glytoucan_type","glycan_mass","glycan_permass","base_composition","composition","topology","monosaccharides","is_motif","missing_score","reducing_end_mono","reducing_end_cid","xref_key","xref_id"
"G00002CF","Topology","956.29687423","1236.60987563","G28882EF","G35219UR","G00002CF","4","False","1969","Glc","5793","",""
"G00009BX","Saccharide","894.33286578","1118.5832669","G93579XB","G40076YB","G97996TJ","5","False","393","GlcNAc","439174","",""
"G00012MO","Saccharide","707.248407805","903.467508785","G08590QR","G53509NM","G15216HY","4","False","492","Glc","5793","",""
"G00012RZ","Saccharide","2734.99351197","3379.71341519","G28989NC","G74930DK","G01087FD","15","False","432","GlcNAc","439174","",""

```

**Comment by ubhuiyan** [comment]
@rykahsay it appears good to me. Shall I close this ticket?
```
[sbhuiyan28@glygen-vm-dev unreviewed]$ awk -F, '{print $11, $12}' glycan_masterlist.csv | sort -u | grep -v reducing_end_mono
"" ""
"dHex" "840"
"Fuc" "17106"
"Gal" "6036"
"GalNAc" "35717"
"Glc" "5793"
"GlcA" "94715"
"GlcN" "439213"
"GlcNAc" "439174"
"Hex" "206"
"HexA" "610"
"HexN" "739"
"HexNAc" "899"
"IdoA" "441039"
"Kdn" "13991616"
"Man" "18950"
"ManNAc" "439281"
"NeuAc" "439197"
"NeuGc" "440001"
"Pent" "229"
"Sia" "0"
"Xxx" "0"
"Xyl" "135191"
```
