### ISSUE TITLE
Problem with RefSeq downloads

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1481]
I remember raising this issue before --- looks like these gpff files are not species specific. These are big files and include proteins from lots of species. Please change your download scripts so that these files contain species specific data.

$ ls -ltr downloads/ncbi/refseq/current/refseq_protein_all_*.gpff
-rwxrwxr-x. 1 k.warner1 glygen 41928681959 Jun 24 09:12 downloads/ncbi/refseq/current/refseq_protein_all_7227.gpff
-rwxrwxr-x. 1 k.warner1 glygen 24820500219 Jun 24 09:13 downloads/ncbi/refseq/current/refseq_protein_all_559292.gpff
-rwxrwxr-x. 1 k.warner1 glygen  4538659530 Jun 24 09:14 downloads/ncbi/refseq/current/refseq_protein_all_44689.gpff
-rwxrwxr-x. 1 k.warner1 glygen 73568323306 Jun 24 09:16 downloads/ncbi/refseq/current/refseq_protein_all_9031.gpff
-rwxrwxr-x. 1 k.warner1 glygen 33236712734 Jun 24 09:18 downloads/ncbi/refseq/current/refseq_protein_all_3702.gpff

**Comment by kmartinez834** [comment]
@rykahsay The only organisms with species-specific folders are: Human, Mouse, Rat, Pig

The other downloads are coming from folders such as "vertebrate_other" and "invertebrate" so you will need to parse them (unless you'd like us to manipulate them on our end)
