### ISSUE TITLE
biomarker search init, log api is failing

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1483]
![Screenshot 2024-06-28 at 2 34 22 PM](https://github.com/glygener/glygen-issues/assets/13891482/34ea069b-0429-44bb-aa96-fd9b6d60f8d0)

**Comment by seankim658** [comment]
Hmm.. it seems to be only working on the VPN right now

**Comment by seankim658** [comment]
We should probably switch to the production endpoints if possible. The tst server seems to go back and forth with firewall access

**Comment by sujeetvkulkarni** [comment]
give me the url. I will update it

**Comment by seankim658** [comment]
Same URL just without the `.tst` part. So https://hivelab.biochemistry.gwu.edu/biomarker/api/

**Comment by seankim658** [comment]
I'm looking at the httpd access logs on the tst server and the requests aren't coming through at all so its definitely a firewall/VPN block.

**Comment by sujeetvkulkarni** [comment]
ok, I will update the url and let you know.

**Comment by sujeetvkulkarni** [comment]
done - https://glygen.ccrc.uga.edu/frontend/home/
Please check.
