### ISSUE TITLE
White list for Nathans species data

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1487]
When processing Nathans species data it may include species that are not (yet) in GlyGen (e.g. currently Chinese Hamster). To avoid these species showing up both on data as well as GlyGen pages @rykahsay will filter the species and only process entries associated with allowed species. We will use a white list that will be maintained be Robel.

**Comment by kmartinez834** [comment]
When making glycan_species.csv dataset, remove tax id’s that are not GlyGen ref id’s or collapsed id’s (refer to generated/misc/species_map.json), with the exception of HCV (11103 and 3052230). 

[GlyGen Organism Decisions](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/Backend%20Workflow/Supplemental%20Files/GlyGen%20Organisms.docx?d=w4e505d8e40aa4bc5970cac7da288107d&csf=1&web=1&e=DTgtqR)

**Comment by ubhuiyan** [comment]
I have included this information in the `species_rules.txt`, can we close this ticket or should we discuss further?

**Comment by rykahsay** [comment]
Done, please check

**Comment by ubhuiyan** [comment]
Looks good. This information has also been provided in the species_rules.txt.
