### ISSUE TITLE
"Unofficial organism" display on glycan details page

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1490]
For "unofficial" organisms that are combined with "official" GlyGen organisms:
1. Should we leave common name blank if one isn't assigned in UniProt?  Or match the common name of the official GlyGen organism?
2. Change "Species" to "Scientific Name"?

![image](https://github.com/glygener/glygen-issues/assets/90285371/5a6ee948-192c-4d9c-8381-b9927da48e1d)

@ubhuiyan can you bring this up in the Wednesday call?

**Comment by ReneRanzinger** [comment]
We could fall back to NCBI Taxonomy common name in that case

https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=10114&lvl=3&lin=f&keep=1&srchmode=1&unlock

But even than, there is a possibility that there is none. My vote is for leaving empty.

**Comment by kmartinez834** [comment]
One more issue I'd like to confirm so I can update documentation for Robel:

1. On Glycan search, do we want to keep HCV and HCV-H77 separate?
![image](https://github.com/glygener/glygen-issues/assets/90285371/2b4983c6-cf6b-4889-8260-362ac6da32a3)

2. Should HCV filter result in only glycans with non-reference taxid, or both ref and nonref? Currently the filter numbers indicate they're separate, but when you filter by "HCV" you get results for both HCV and HCV-H77: 
![image](https://github.com/glygener/glygen-issues/assets/90285371/d85efd11-3dd1-49ad-bcf0-8f73e3cc63b5)

**Comment by kmartinez834** [comment]
1. Should we leave common name blank if one isn't assigned in UniProt? Or match the common name of the official GlyGen organism?
--> Deal with this on a case by case basis, document outcomes on [GlyGen Organsism](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/Backend%20Workflow/Supplemental%20Files/GlyGen%20Organisms.docx?d=w4e505d8e40aa4bc5970cac7da288107d&csf=1&web=1&e=LNdIPx)
2. Change "Species" to "Scientific Name"?
--> @sujeetvkulkarni to update this
3. On Glycan search, do we want to keep HCV and HCV-H77 separate?
--> Yes, Raja wanted this
4. Should HCV filter result in only glycans with non-reference taxid, or both ref and nonref? 
--> Keep them separate, need to update the results list so HCV results are only HCV, not HCV-H77
