### ISSUE TITLE
Biomarker component issue

### ISSUE THREAD

**Issue by DaniallMasood** [glygener/glygen-issues#1492]
@sujeetvkulkarni In the component section for a lot of biomarkers there is no component being shown even though it has components and information in there. It seems that it is using the GlyGen structure still of it being either protein or a glycan. We have different types of biomarkers and their components are not being shown (example below) is there a way to fix that? What has to be done?

The information can just be put out into a table and not have the tabs of "glycan" or "protein" or any other entity

@seankim658 

![Image](https://github.com/glygener/glygen-issues/assets/116293652/5d6fba29-8144-4594-988f-096aedde3f2d)

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood It can be shown. We just have to come up with a strategy - All in one table with type property or different tabs etc.

**Comment by DaniallMasood** [comment]
@sujeetvkulkarni  i think table with type property would be best since we have so many different types of biomarkers.

eventually panel biomarkers will have components of different entity types so this would be best.

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood Ok, then we will need to have 8 columns including Type. 
Glycan Image will remain empty in other cases and LOINC Code will remain empty in Glycan case.

https://www.glygen.org/biomarker/AA5041-1#Components

![Screenshot 2024-07-02 at 12 25 43 PM](https://github.com/glygener/glygen-issues/assets/13891482/2d133b6b-0371-4446-973d-21ac21a821b0)

https://www.glygen.org/biomarker/AA4761-1#Components

![Screenshot 2024-07-02 at 12 26 08 PM](https://github.com/glygener/glygen-issues/assets/13891482/38ec3699-d59e-43ac-abfd-afb97367de41)

**Comment by DaniallMasood** [comment]
@sujeetvkulkarni maybe there is some misunderstanding but I was thinking just displaying the table withoout the tabs above. Just display the data from the json and have it like the second screenshot with the assessed_entity_type present as well where it would indicate if it is a protein,glycan, gene, etc

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood I showed current columns in the screen shots and proposed a single table with 8 columns. 
I think you are proposing 7 columns and dont want Glycan Image in it.

**Comment by DaniallMasood** [comment]
@sujeetvkulkarni yes but we can keep 8 columns and just add in the information of assessed_entity_type which is in the json, instead of having glycan image if possible

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood ok, I will add assessed_entity_type and remove Glycan Image in a single table. Total 7 columns.

**Comment by DaniallMasood** [comment]
@sujeetvkulkarni oh yes that is my fault. I was not counting correctly and missed that. Thank you and sounds good to me

**Comment by DaniallMasood** [comment]
@sujeetvkulkarni when do you think this change will be done by? Is it possible to be completed this week

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood yes, I will do it and let you know.

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood I have made the change.
https://glygen.ccrc.uga.edu/frontend/biomarker/AA4686-16
Please have a look.
