### ISSUE TITLE
BCO creation & edits

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1502]
Create BCOs for all new datasets 

**Dependencies:**
* #1450 
* #1455 
* #1479 
* #1493 
* #1494 
* #1495 
* #1467 
* #1497
* #1498
* #1499 
* #1496 
* #1500
* #1501

**Comment by ubhuiyan** [comment]
Note for myself: Update oglcnac BCOs output files that end in "db".

**Comment by katewarner** [comment]
|BCO ID | Dataset Name| Creator Name|Notes|
|----|----|----|----|
|GLY_001052|arabidopsis_protein_allsequences.fasta|Kate|
|GLY_001053|arabidopsis_protein_altnames.csv|Kate|
|GLY_001054|arabidopsis_protein_binary_interactions.csv|Kate|
|GLY_001055|arabidopsis_protein_canonicalsequences.fasta|Kate|
|GLY_001056|arabidopsis_protein_citations_uniprotkb.csv|Kate|
|GLY_001057|arabidopsis_protein_enzyme_annotation_uniprotkb.csv|Kate|
|GLY_001058|arabidopsis_protein_function_uniprotkb.csv|Kate|
|GLY_001059|arabidopsis_protein_genelocus.csv|Kate|
|GLY_001060|arabidopsis_protein_genenames_refseq.csv|Kate|
|GLY_001061|arabidopsis_protein_genenames_uniprotkb.csv|Kate|
|GLY_001062|arabidopsis_protein_glycosylation_motifs.csv|Kate|
|GLY_001064|arabidopsis_protein_go_annotation.csv|Kate|
|GLY_001065|arabidopsis_protein_info_refseq.csv|Kate|
|GLY_001066|arabidopsis_protein_info_uniprotkb.csv|Kate|
|GLY_001067|arabidopsis_protein_masterlist.csv|Kate|
|GLY_001068|arabidopsis_protein_ncbi_linkouts.csv|Kate|
|GLY_001070|arabidopsis_protein_participants_rhea.csv|Cyrus|
|GLY_001071|arabidopsis_protein_pro_annotation.csv|Cyrus|missing usability domain|
|GLY_001072|arabidopsis_protein_proteinnames_refseq.csv|Cyrus|usability domain depend on other BCOs|
|GLY_001073|arabidopsis_protein_ptm_annotation_uniprotkb.csv|Cyrus|
|GLY_001074|arabidopsis_protein_reactions_rhea.csv|Cyrus|missing usability domain|
|GLY_001075|arabidopsis_protein_recnames.csv|Cyrus|
|GLY_001076|arabidopsis_protein_sequenceinfo.csv|Cyrus|
|GLY_001077|arabidopsis_protein_signalp_annotation.csv|Cyrus|
|GLY_001078|arabidopsis_protein_site_annotation_uniprotkb.csv|Cyrus|
|GLY_001079|arabidopsis_protein_submittednames.csv|Cyrus|
|GLY_001080|arabidopsis_protein_transcriptlocus.csv|Cyrus|
|GLY_001081|arabidopsis_protein_xref_brenda.csv|Cyrus|
|GLY_001082|arabidopsis_protein_xref_cazy.csv|Cyrus|
|GLY_001083|arabidopsis_protein_xref_cdd.csv|Cyrus|
|GLY_001084|arabidopsis_protein_xref_chembl.csv|Cyrus|
|GLY_001085|arabidopsis_protein_xref_geneid.csv|Luke|
|GLY_001086|arabidopsis_protein_xref_intact.csv|Luke|
|GLY_001087|arabidopsis_protein_xref_interpro.csv|Luke|
|GLY_001088|arabidopsis_protein_xref_kegg.csv|Luke|
|GLY_001089|arabidopsis_protein_xref_oma.csv|Luke|
|GLY_001090|arabidopsis_protein_xref_orthodb.csv|Luke|
|GLY_001091|arabidopsis_protein_xref_panther.csv|Luke|
|GLY_001093|arabidopsis_protein_xref_pdb.csv|Luke|
|GLY_001094|arabidopsis_protein_xref_pfam.csv|Luke|
|GLY_001095|arabidopsis_protein_xref_pro.csv|Luke|
|GLY_001096|arabidopsis_protein_xref_refseq.csv|Luke|
|GLY_001097|arabidopsis_protein_xref_rhea.csv|Luke|
|GLY_001098|arabidopsis_protein_xref_uniprotkb.csv|Luke|
|GLY_001099|arabidopsis_protein_glycohydrolase.csv|Luke|
|GLY_001092|arabidopsis_protein_glycosyltransferase.csv|Luke|
|GLY_001136|arabidopsis_protein_xref_oglcnac_atlas.csv|Kate|
|GLY_001137|arabidopsis_protein_xref_glyconnect.csv|Kate|
|GLY_001138|arabidopsis_protein_xref_oglcnac_mcw.csv|Kate|
|GLY_001139|chicken_protein_xref_oglcnac_mcw.csv|Kate|
|GLY_001135|chicken_proteoform_citations_glycosylation_sites_glyconnect.csv|Kate|
|GLY_001130|arabidopsis_protein_xref_pride.csv|Kate|
|GLY_001128|human_protein_xref_pride.csv|Kate|
|GLY_001131|yeast_protein_xref_pride.csv|Kate|
|GLY_001132|pig_protein_xref_pride.csv|Kate|
|GLY_001129|mouse_protein_xref_pride.csv|Kate|
|GLY_001133|rat_protein_xref_pride.csv|Kate|
|GLY_001134|fruitfly_protein_xref_pride.csv|Kate|
|GLY_001127|human_protein_xref_massive.csv|Kate|
|GLY_001063|human_protein_disease_alliance_genome.csv|Kate|
|GLY_001051|human_proteoform_glycosylation_sites_platelet_o_linked.csv|Kate|
|GLY_001164|human_proteoform_citations_glycosylation_sites_platelet_olinked.csv|Kate|
|GLY_001126|protein_glygen_flybase_linkout.tsv|Kate|
|GLY_001117|human_protein_xref_alphafolddb.csv|Kate|
|GLY_001118|mouse_protein_xref_alphafolddb.csv|Kate|
|GLY_001119|rat_protein_xref_alphafolddb.csv|Kate|
|GLY_001120|fruitfly_protein_xref_alphafolddb.csv|Kate|
|GLY_001121|yeast_protein_xref_alphafolddb.csv|Kate|
|GLY_001122|dicty_protein_xref_alphafolddb.csv|Kate|
|GLY_001123|pig_protein_xref_alphafolddb.csv|Kate|
|GLY_001124|chicken_protein_xref_alphafolddb.csv|Kate|
|GLY_001125|arabidopsis_protein_xref_alphafolddb.csv|Kate|
|GLY_001100|arabidopsis_proteoform_glycosylation_sites_glyconnect.csv| Urnisha 
|GLY_001101|arabidopsis_proteoform_citations_glycosylation_sites_glyconnect.csv| Urnisha
|GLY_001102|arabidopsis_proteoform_glycosylation_sites_pdb.csv| Urnisha
|GLY_001103|arabidopsis_proteoform_citations_glycosylation_sites_uniprotkb.csv| Urnisha
|GLY_001104|arabidopsis_proteoform_citations_glycosylation_sites_oglcnac_atlas.csv| Urnisha
|GLY_001105|arabidopsis_proteoform_glycosylation_sites_oglcnac_atlas.csv| Urnisha
|GLY_001106|arabidopsis_proteoform_citations_glycosylation_sites_oglcnac_mcw.csv| Urnisha
|GLY_001107|arabidopsis_proteoform_glycosylation_sites_oglcnac_mcw.csv| Urnisha
|GLY_001108|arabidopsis_proteoform_citations_phosphorylation_sites_uniprotkb.csv| Urnisha
|GLY_001109|arabidopsis_proteoform_phosphorylation_sites_uniprotkb.csv| Urnisha
|GLY_001110|arabidopsis_proteoform_glycosylation_sites_uniprotkb.csv| Urnisha
|GLY_001111|arabidopsis_proteoform_citations_phosphorylation_sites_iptmnet.csv| Urnisha
|GLY_001112|arabidopsis_proteoform_phosphorylation_sites_iptmnet.csv| Urnisha
|GLY_001113|human_proteoform_glyosylation_sites_carbbank.csv| Urnisha 
|GLY_001114|mouse_proteoform_glyosylation_sites_carbbank.csv| Urnisha
|GLY_001115|rat_proteoform_glyosylation_sites_carbbank.csv| Urnisha
|GLY_001116|yeast_proteoform_glyosylation_sites_carbbank.csv| Urnisha

**Comment by katewarner** [comment]
@CyrusAY One of the BCOs you created (GLY_001078) is producing an error message that there is no BCO. Can you check that you've uploaded the BCO to BioCompute correctly?

`NO-BCO,arabidopsis_protein_site_annotation_uniprotkb.csv,ERROR,in_fs`

**Comment by katewarner** [comment]
@CyrusAY Urnisha checked and the BCO is on Biocompute. I'll ask Karina if she knows why it's producing an error

**Comment by CyrusAY** [comment]
GLY_001078 is fixed

**Comment by rykahsay** [comment]
Please do not forget to run:

python3 /software/glygen/check-bco2filename-mapping.py

I see a bunch of errors that can/should be fixed by you ... for example what is given below should be familiar and you should know how to fix it.

Set-1
```
GLY_000553,human_protein_xref_oglcnac_db.csv,ERROR,in_bco
GLY_000673,fruitfly_protein_xref_oglcnac_db.csv,ERROR,in_bco
GLY_000694,mouse_protein_xref_oglcnac_db.csv,ERROR,in_bco
GLY_000695,rat_protein_xref_oglcnac_db.csv,ERROR,in_bco
GLY_000788,yeast_protein_xref_oglcnac_db.csv,ERROR,in_bco
GLY_000899,pig_protein_xref_oglcnac_db.csv,ERROR,in_bco
```

Set-2
```
NO-BCO,chicken_protein_xref_oglcnac_mcw.csv,ERROR,in_fs
NO-BCO,arabidopsis_protein_xref_oglcnac_mcw.csv,ERROR,in_fs
```


Set-3
These should go away if you fix set-1
```
NO-BCO,fruitfly_protein_xref_oglcnac_mcw.csv,ERROR,in_fs
NO-BCO,mouse_protein_xref_oglcnac_mcw.csv,ERROR,in_fs
NO-BCO,pig_protein_xref_oglcnac_mcw.csv,ERROR,in_fs
NO-BCO,yeast_protein_xref_oglcnac_mcw.csv,ERROR,in_fs
NO-BCO,human_protein_xref_oglcnac_mcw.csv,ERROR,in_fs
NO-BCO,rat_protein_xref_oglcnac_mcw.csv,ERROR,in_fs
```

**Comment by katewarner** [comment]
@rykahsay I've fixed the bco errors so I'll make you a ticket to push the BCOs to TST

**Comment by katewarner** [comment]
All BCOs have been created and passed the error check, except the user dataset `human_proteoform_glycosylation_sites_platelet_olinked.csv` which is still being created

**Comment by katewarner** [comment]
Additional BCOs:

|BCO ID | Dataset Name| Creator Name|Notes|
|----|----|----|----|
|GLY_001141|mouse_protein_pdb_map.csv|Urnisha|
|GLY_001147|sarscov1_protein_pdb_map.csv|Urnisha| Retired
|GLY_001142|yeast_protein_pdb_map.csv|Urnisha|
|GLY_001143|rat_protein_pdb_map.csv|Urnisha|
|GLY_001144|fruitfly_protein_pdb_map.csv|Urnisha|
|GLY_001145|human_protein_pdb_map.csv|Urnisha|
|GLY_001146|pig_protein_pdb_map.csv|Kate|
|GLY_001148|chicken_protein_pdb_map.csv|Kate|
|GLY_001149|dicty_protein_pdb_map.csv|Kate|
|GLY_001140|arabidopsis_protein_pdb_map.csv|Kate|
|GLY_001150|protein_reaction2ec_rhea.csv|Kate|

**Comment by Luke-Johnson-5** [comment]
| BCO ID | Dataset Name                                                      | Creator Name | Notes |
| ------ | ----------------------------------------------------------------- | ------------ | ----- |
|GLY_001156| arabidopsis_proteoform_glycosylation_sites_predicted_isolglyp.csv |      Kate        |       |
|GLY_001161| chicken_proteoform_glycosylation_sites_predicted_isolglyp.csv     |       Kate       |       |
|GLY_001162| dicty_proteoform_glycosylation_sites_predicted_isolglyp.csv       |         Kate     |       |
|GLY_001163| fruitfly_proteoform_glycosylation_sites_predicted_isolglyp.csv    |      Kate        |       |
|    GLY_001154    | hcv1a_proteoform_glycosylation_sites_predicted_isolglyp.csv       |        Luke      |       |
|    GLY_001155    | hcv1b_proteoform_glycosylation_sites_predicted_isolglyp.csv       |         Luke     |       |
|    GLY_001151    | human_proteoform_glycosylation_sites_predicted_isolglyp.csv       |     Luke         |       |
|    GLY_001153    | mouse_proteoform_glycosylation_sites_predicted_isolglyp.csv       |       Luke       |       |
|    GLY_001152    | pig_proteoform_glycosylation_sites_predicted_isolglyp.csv         |       Luke       |       |
|      GLY_001157  | rat_proteoform_glycosylation_sites_predicted_isolglyp.csv         |   Urnisha    |       |
|    GLY_001158    |  sarscov1_proteoform_glycosylation_sites_predicted_isolglyp.csv   |      Urnisha        |       |
|    GLY_001159    | sarscov2_proteoform_glycosylation_sites_predicted_isolglyp.csv    |        Urnisha      |       |
|      GLY_001160  | yeast_proteoform_glycosylation_sites_predicted_isolglyp.csv       |       Urnisha       |       |

template available at /software/glygen/bco_templates/human_proteoform_glycosylation_sites_predicted_isolglyp.json

Note: many of the files might say isolglyp instead of isoglyp so if you see this error please change it to isoglyp I am working to fix this now.
