### ISSUE TITLE
Finish testing tst - Round I

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1504]
Phase I testing on tst site

**Dependencies:**
* #1501 

**Blocker for:**
* #1505
* #1506
* #1507
* #1508
* #1509
* #1510
* #1511

**Comment by rykahsay** [comment]
Please start testing

**Comment by katewarner** [comment]
Finished testing and created tickets for any issues found. 

I did the following:
•    Checked whether datasets have tables displayed 
•    Checked whether the filters work
•    Checked if datasets have sample view page 
•    Checked that description and sample table is displayed on the sample view page 
•    Checked that datasets can be toggled to different versions
•    Checked BCOs and readme links are displayed 
•    Checked I could download dataset files and BCOs 
•    Checked all links and the menu links on the home page such as FAQs, Release history 
•    Checked that the API, SPARQL and Portal links worked

**Comment by ubhuiyan** [comment]
#### Table for Testing tst.glygen.org - Existing Datasets 

| Page | Example ID | Status (P/F**) | Assignment | Ticket Number| Instructions | Notes
| --- | --- | --- | --- | --- | --- |  --- | 
|Global Search | P14210, G17689DH, collagen alpha-1(I) chain preproprotein| P| Urnisha | #1622 (Resolved) |Ensure the global search is working and results are displayed in less than 20 secs | Biomarker Filter Glitch 
|Protein Simple Search| P14210| P | Luke | | | Search Passed no problem |
|Protein Simple Search (HR*)| P0DTC2| P | Jeet | | | Passed
|Glycan Simple Search| G17689DH| F| Cyrus| #1622 (Resolved) | | Encountered similar filter problems|
|Glycan Simple Search (HR*)| G39365VM | P| Urnisha| | | All Fields Passed  
|Protein Advanced Search| P14210 | P | Luke| | Please test all fields | All Fields Passed |
|Protein Advanced Search (HR)| P0DTC2 | P | Luke| | Please test all fields | All Fields Passed |
|Glycan Advanced Search| G17689DH| P| Cyrus| | Please test all fields  | All Fields Passed |
|List of Motifs| GGM.000001|P| Urnisha| | Check glycan image display and generated detail pages | All Fields Passed
|Protein Details Page| P14210, P0DTC2| P | Luke| #1618 (Resolved) #1619 (False Alarm)  |Check links, page displays, correct data, generated details page, filters |Working on prd so issue solved |
|Glycan Details Page| G17689DH, G49108TO | F| Cyrus|#1629 (Resolved) #1630 (False Alarm)|Check links, page displays, correct data, generated details page, filters |Some issues found|
|Publication Details| https://tst.glygen.org/publication/DOI/10.1101/2023.09.13.557529| P | Jeet | #1638 (Resolved) | Check the page content, information, check links | All passed
|Super Search| NA| P| Urnisha| #1623 (Resolved) | Check dropdown and link functionality | Organism Result Display Issue 
|Site Search| NA| P| Jeet| | Check link functionality, dropdown, generated results | All passed
|Quick Search| NA| F | Cyrus|#1631 (Resolved) #1632 #1633 (Resolved) | Check all the quick searches with the example IDs, ensure correct pages are displayed| Some issues found|
|Tools - Glycan Sequence Lookup| NA | P | Cyrus| | Check if the tool is working | No issues |
|Tools - Glycan Structure Dictionary| NA | P |Cyrus | |Check if the wiki page opens | No issues |
|Tools - Glycan Motifiwiki | NA | P | Cyrus |  |Check if the wiki page opens | No issues |
|Tools - GlyGen Blast | P14210 | P | Cyrus | |Check whether the BLAST if working, List page, alignment is shown | No issues |
|Tools - GlyGen Mapper | NA | P |Cyrus | |Check the example IDs for Protrein and Glycan databases can be mapped, check if new databases for new organism are present | No issues |
|Tools - GlyGen Sandbox | G17689DH | P |Cyrus | | Check all the features are working | No issues |
|Tools - Structure Browser | NA | P |Cyrus | |Add monosach. for O and N glycan and see you get the results, links are working. | No issues; monosaccharides shown |
|API Page| NA| P | Urnisha | |Check API execution, correct data display, working links | No issues
|SPARQL| NA| P| Luke | |Check if links and examples working | does not get updated until beta so will need to be rechecked there. |



HR* = High Records 
P/F** = Pass Fail 
Detailed Testing Document - [Link](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7BF43A37D7-14B2-485C-B931-D3862C1554EA%7D&file=Detail%20Testing.docx&action=default&mobileredirect=true&DefaultItemOpen=1)

**Note:** Please follow the instructions within the **Detailed Testing Document** per your assigned sections thoroughly. Assign any issues you find to Robel and provide the ticket number in this table.

**Comment by ubhuiyan** [comment]
#### Table for Testing tst.glygen.org - New Datasets 

| Page | Example ID | Status (P/F**) | Assignment | Ticket Number| Instructions | Notes
| --- | --- | --- | --- | --- | --- |  --- | 
|Isoglyp Datasets | B7ZCC9 | P | Urnisha | | | 
|Platelet Datasets | P01859 | P | Urnisha | #1634 (False Alarm)  | | Glycosylation/Associated Protein not represented on detail page. 
|Carbbank Datasets | G36855WW | F | Urnisha | #1634 (Resolved)  | | Glycosylation/Associated Protein not represented on detail page.

**Comment by Luke-Johnson-5** [comment]
Looked into IsoGlyP datasets on tst and appear to be presenting correctly.
