### ISSUE TITLE
Finish testing on beta

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1509]
beta testing 

**Dependencies:**
* #1501 
* #1504
* #1505
* #1506
* #1508

**Blocker for:**
* #1510
* #1511

**Comment by ubhuiyan** [comment]
#### Table for Testing beta.glygen.org - Existing Datasets 

| Page | Example ID | Status (P/F**) | Assignment | Ticket Number| Instructions | Notes
| --- | --- | --- | --- | --- | --- |  --- | 
|Global Search | P14210, G17689DH, collagen alpha-1(I) chain preproprotein| F | Cyrus |  |Ensure the global search is working and results are displayed in less than 20 secs | Collagen alpha-1(I) took 25 seconds|
|Protein Simple Search| P14210| P | Kate | | | Passed no issues |
|Protein Simple Search (HR*)| P0DTC2| P | Cyrus | | | No issues| 
|Glycan Simple Search| G17689DH| P| Urnisha|  | | Passed no issues|
|Glycan Simple Search (HR*)| G39365VM | P | Urnisha| | |Passed no issues
|Protein Advanced Search| P14210 | F | Kate| #1679 | Please test all fields |  |
|Protein Advanced Search (HR)| P0DTC2 | P | Kate| | Please test all fields | Passed no issues |
|Glycan Advanced Search| G17689DH| P| Cyrus| | Please test all fields  | No issues|
|List of Motifs| GGM.000001|P| Urnisha| | Check glycan image display and generated detail pages | Passed no issues
|Protein Details Page| P14210, P0DTC2| F | Kate| #1683  |Check links, page displays, correct data, generated details page, filters 
|Glycan Details Page| G17689DH, G49108TO | P| Urnisha| |Check links, page displays, correct data, generated details page, filters | | | Passed no issues |
|Publication Details| 10092871 | P | Cyrus |  | Check the page content, information, check links | No issues|
|Publication Details (HR)| 37074911 | F | | #1678  | Check the page content, information, check links | Robel raised this issue. Added to table for next test
|Super Search| NA| P| Urnisha| | Check dropdown and link functionality |  Passed no issues
|Site Search| NA| P| Cyrus| | Check link functionality, dropdown, generated results | No issues|
|Quick Search| NA| F | Urnisha| #1666  | Check all the quick searches with the example IDs, ensure correct pages are displayed|  | Issue with selecting O-Glycosylation Filter 
|Tools - Glycan Sequence Lookup| NA | P | Cyrus| | Check if the tool is working | No issues |
|Tools - Glycan Structure Dictionary| NA | P |Urnisha | |Check if the wiki page opens |  Passed no issues |
|Tools - Glycan Motifiwiki | NA | P | Urnisha |  |Check if the wiki page opens | Passed no issues | 
|Tools - GlyGen Blast | P14210 | P | Urnisha | |Check whether the BLAST if working, List page, alignment is shown | Passed no issues
|Tools - GlyGen Mapper | NA | F |Kate | #1680  |Check the example IDs for Protrein and Glycan databases can be mapped, check if new databases for new organism are present | 
|Tools - GlyGen Sandbox | G17689DH | P |Urnisha | | Check all the features are working | Passed no issues
|Tools - Structure Browser | NA | P |Urnisha | |Add monosach. for O and N glycan and see you get the results, links are working. |  Passed no issues | 
|API Page| NA| P | Kate | |Check API execution, correct data display, working links | Passed no issues
|SPARQL| NA| F| Kate | #1681  |Check if links and examples working | 



HR* = High Records 
P/F** = Pass Fail 
Detailed Testing Document - [Link](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7BF43A37D7-14B2-485C-B931-D3862C1554EA%7D&file=Detail%20Testing.docx&action=default&mobileredirect=true&DefaultItemOpen=1)

**Note:** Please follow the instructions within the **Detailed Testing Document** per your assigned sections thoroughly. Assign any issues you find to Robel and provide the ticket number in this table.

**Comment by ubhuiyan** [comment]
#### Table for Testing beta.glygen.org - New Datasets 

| Page | Example ID | Status (P/F**) | Assignment | Ticket Number| Instructions | Notes
| --- | --- | --- | --- | --- | --- |  --- | 
|Isoglyp Datasets | B7ZCC9 | P | Urnisha | | | Passed no issues
|Platelet Datasets | P01859 | P | Urnisha |   | |  Moved to 2.7
|Carbbank Datasets | G36855WW | P | Urnisha |   | |  Passed no issues
|PDB map Datasets |  | F | Kate| might be issue: #1683   | | 
|Pride xref Datasets | | F | Kate|  #1684  | | 
|Arabidopsis Datasets | A8R7E6 G49108TO | P/F | Kate|   | |

**Comment by ubhuiyan** [comment]
@katewarner and @CyrusAY I have provided the testing table above. Please complete by 12PM (5PM GMT) on Thursday, August 29th.

**Comment by ubhuiyan** [comment]
I have completed testing and found only one issue.

**Comment by katewarner** [comment]
I have completed testing and made tickets for any issues I found.
