### ISSUE TITLE
Finish testing on production

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1511]
**Dependencies:**
* #1501 
* #1504
* #1505
* #1506
* #1507
* #1508
* #1509
* #1510

**Comment by ubhuiyan** [comment]
#### Table for Testing glygen.org - Existing Datasets 

| Page | Example ID | Status (P/F**) | Assignment | Ticket Number| Instructions | Notes
| --- | --- | --- | --- | --- | --- |  --- | 
|Global Search | P14210, G17689DH, collagen alpha-1(I) chain preproprotein| P | Kate|  |Ensure the global search is working and results are displayed in less than 20 secs | Passed no issues
|Protein Simple Search| P14210| P | Kate | ||  Passed no issues
|Protein Simple Search (HR*)| P0DTC2| P | Kate| | |  Passed no issues
|Glycan Simple Search| G17689DH| P| Urnisha|  | | Passed no issues 
|Glycan Simple Search (HR*)| G39365VM | P | Urnisha| | | Passed no issues
|Glycan Structure Search | | F | Kate | #1723  |Please test both examples | 
|Glycan Substructure Search | | F | Kate  | #1723 |Please test both examples | 
|Protein Advanced Search| P14210 | P | Kate| | Please test all fields |Passed no issues
|Protein Advanced Search (HR)| P0DTC2 | P | Kate| | Please test all fields | Passed no issues
|Glycan Advanced Search| G17689DH| P| Kate | | Please test all fields  | Passed no issues
|List of Motifs| GGM.000001|P| Urnisha| | Check glycan image display and generated detail pages | Passed no issues. 
|Protein Details Page| P14210, P0DTC2| P | Kate|   |Check links, page displays, correct data, generated details page, filters |Passed no issues 
|Glycan Details Page| G17689DH, G49108TO | P| Urnisha| |Check links, page displays, correct data, generated details page, filters | | Passed no issues
|Publication Details| 10092871 | P | Cyrus |  | Check the page content, information, check links | Passed no issues 
|Publication Details (HR)| 37074911 | F/P | Kate | | Check the page content, information, check links | Passed no Issues
|Super Search| NA| P| Urnisha| | Check dropdown and link functionality |  Passed no Issues
|Site Search| NA| P| Cyrus| | Check link functionality, dropdown, generated results | Passed no issues
|Quick Search| NA| P | Urnisha|   | Check all the quick searches with the example IDs, ensure correct pages are displayed|  | No issues 
|Tools - Glycan Sequence Lookup| NA | P | Cyrus| | Check if the tool is working | Passed no issues
|Tools - Glycan Structure Dictionary| NA | P |Urnisha | |Check if the wiki page opens |  
|Tools - Glycan Motifiwiki | NA | P | Urnisha |  |Check if the wiki page opens | 
|Tools - GlyGen Blast | P14210 | P | Urnisha | |Check whether the BLAST if working, List page, alignment is shown | 
|Tools - GlyGen Mapper | NA | F |Kate |   |Check the example IDs for Protrein and Glycan databases can be mapped, check if new databases for new organism are present | Passed no issues
|Tools - GlyGen Sandbox | G17689DH | P |Urnisha | | Check all the features are working | Passed no issues. 
|Tools - Structure Browser | NA | P |Urnisha | |Add monosach. for O and N glycan and see you get the results, links are working. |   | Passed no issues. 
|API Page| NA| P | Kate | |Check API execution, correct data display, working links |  Passed no issues 
|SPARQL| NA| F | Kate | Issue being fixed - #1681   |Check if links and examples working |



HR* = High Records 
P/F** = Pass Fail 
Detailed Testing Document - [Link](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7BF43A37D7-14B2-485C-B931-D3862C1554EA%7D&file=Detail%20Testing.docx&action=default&mobileredirect=true&DefaultItemOpen=1)

**Note:** Please follow the instructions within the **Detailed Testing Document** per your assigned sections thoroughly. Assign any issues you find to Robel and provide the ticket number in this table.

**Comment by ubhuiyan** [comment]
#### Table for Testing glygen.org - New Datasets 

| Page | Example ID | Status (P/F**) | Assignment | Ticket Number| Instructions | Notes
| --- | --- | --- | --- | --- | --- |  --- | 
|Isoglyp Datasets | B7ZCC9 | P | Urnisha | | | Passed no issues
|Carbbank Datasets | G36855WW | P | Urnisha |   | | Passed no issues
|PDB map Datasets |  | P | Kate|   | | Passed no issues
|Pride xref Datasets | | F | Kate| Issue being fixed - #1684 | | 
|Arabidopsis Datasets | A8R7E6 G49108TO | P | Kate|   | | Passed no issues

**Comment by ubhuiyan** [comment]
@katewarner and @CyrusAY Please fill out the table for prd testing.

**Comment by ubhuiyan** [comment]
I have completed testing and found no issues.

**Comment by katewarner** [comment]
I finished testing and made tickets for any issues (see table above).
