### ISSUE TITLE
Run Isoglycp to predict glycosylation sites

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1519]
**Blocker for:**
* #1520

**Comment by Luke-Johnson-5** [comment]
How to handle Isoglyp Scoring?

| n_known_sites | n_predicted_sites_known_gt_1.5 | n_predicted_sites_known_gt_9 | n_predicted_sites_known_gt_13.5 | Organism    |
| ------------- | ------------------------------ | ---------------------------- | ------------------------------- | ----------- |
| 22296         | 8022                           | 370                          | 105                             | human       |
| 7108          | 2813                           | 78                           | 23                              | mouse       |
| 179           | 79                             | 6                            | 1                               | pig         |
| 994           | 270                            | 11                           | 3                               | rat         |
| 4             | 3                              | 0                            | 0                               | sarscov1    |
| 29            | 12                             | 0                            | 0                               | sarscov2    |
| 2953          | 568                            | 2                            | 1                               | yeast       |
| 63            | 12                             | 1                            | 0                               | chicken     |
| 16            | 13                             | 7                            | 2                               | dicty       |
| 205           | 67                             | 2                            | 1                               | fruitfly    |
| 329           | 95                             | 2                            | 1                               | arabidopsis |
| 0             | 0                              | 0                            | 0                               | hcv1a       |
| 6             | 3                              | 0                            | 0                               | hcv1b       |

**Comment by Luke-Johnson-5** [comment]
From Seun:

"Even with EVP limits 6-9 times more stringent than recommended, precision does not surpass 13 - 20%, meaning only about 13 - 20 % of positive predictions are likely true​"

**Comment by Luke-Johnson-5** [comment]
Done
