### ISSUE TITLE
protein detail schema

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#152]
Robel here is the csv for protein detail schema for required properties - misc/protein_detail_response_schema.csv

If you made new changes to schema then they won't be reflected here as I couldn't find latest schema. for eg tissue_expression

Let me know if this works or causes any issues.

**Comment by jeet-vora** [comment]
@rykahsay Robel,
Few sections such as phosphorylation, glycation, ptm_annotation, site_annotation are missing from the current protein detail schema. Can you please check.

**Comment by rykahsay** [comment]
I pushed my last commit

**Comment by jeet-vora** [comment]
I am looking at 2.0 branch in the https://github.com/glygener/glygen-backend-api/blob/2.0/specs/protein/detail/response.schema.json-default

These are missing - phosphorylation, glycation, ptm_annotation, site_annotation

If you have changed then let me know where to look for them.

**Comment by rykahsay** [comment]
Those are added now

<img width="852" alt="image" src="https://user-images.githubusercontent.com/20584876/229637102-eec21f89-0c9b-4cba-a3e7-f887cb79704a.png">

**Comment by jeet-vora** [comment]
Done
