### ISSUE TITLE
Add more consensus sequences to protein details

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1521]
Create a JSON with patterns provided in #1532. This can be provided to the frontend by API, as file from data ...

**Dependencies:**
* #1532 

**Blocker for:**
* #1522

**Comment by rykahsay** [comment]
@ubhuiyan   ... where is the mapping file under the misc?

**Comment by ubhuiyan** [comment]
@rykahsay commented on ticket 1532, but will leave here as well: `misc/consensus_sequon_mapping.json`

**Comment by rykahsay** [comment]
Also commented on #1532 

@sujeetvkulkarni 

Release specific URL for the file is:
https://data.glygen.org/ln2releases/data/v-2.6.1/misc/consensus_sequon_mapping.json


After we push to prd, you can also use this URL:
https://data.glygen.org/ln2releases/data/current/misc/consensus_sequon_mapping.json

**Comment by sujeetvkulkarni** [comment]
@rykahsay 
We have referred these consensus sequences but a copy in frontend will be used to display and highlight protein sequences.
Closing this ticket.
Adding label informative for future reference.
