### ISSUE TITLE
Add more consensus to the sequence viewer

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1522]
Sequon is no longer a tickbox option. Its the parent entry for all the sequons (#1521). The are grouped by a radio button group user can only select one at the time for the highlight. If can make sequon expandable and collapsible it would be nice but by default its expended. 

**Dependency:**
* #1521 
* #1532

**Comment by sujeetvkulkarni** [comment]
Implemented templates functionality for highlighting consensus sequences on client side. Done.
