### ISSUE TITLE
Test ID Mapping API 

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#153]
ID Mapping API might not behave as desired since I have changed the ID tracking history schema trying address the protein/glycan detail APIs.

Please test them carefully giving it example accessions like Q69ZH5, Q13065, G3X9Q5, B1AXE0, A0A161SEP9, A0A008XH72 and report all incorrect reasons. For example, when I give it Q13065, the reason comes as "Invalid ID".

<img width="607" alt="image" src="https://user-images.githubusercontent.com/20584876/226667603-67584f0a-ee6b-4cdb-888e-ae2206502c04.png">

**Comment by jeet-vora** [comment]
For ID Mapping 2

**Comment by ReneRanzinger** [comment]
Part of smart ID mapper.
