### ISSUE TITLE
Mockup for user data submission badges

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1531]

**Comment by kmartinez834** [comment]
[Badges mockup](https://gwu0.sharepoint.com/:p:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Mockups/[Badges](https://gwu0.sharepoint.com/:p:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Mockups/Badges.pptx?d=w0b67b7a6f0ed4eb9bcf1a307e370f395&csf=1&web=1&e=ycv2zG).pptx?d=w0b67b7a6f0ed4eb9bcf1a307e370f395&csf=1&web=1&e=ycv2zG)
