### ISSUE TITLE
Provide the sequons and label for these highlighting templates

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1532]
* C-Man consensus sequence (WxxW) 
* O-glc
* O-fuc

**Comment by ubhuiyan** [comment]
Kate/Urnisha: Create mapping file based off of data Mike provides for misc folder.

**Comment by rykahsay** [comment]
@ubhuiyan  ... any update on this?

**Comment by katewarner** [comment]
Here are the consensus sequences we found. @sujeetvkulkarni you may want to check these with @mtiemeyer0919 to make sure they are correct: 

**C-Mannosylation** 
WXXW
WXXC
WXXWXXW
WXXWXXWXXC

**O-glucosylation**
CXSX(P/A)C
CXNTXGSFXC

**O-fucosylation**
CXXXX(S/T)C
CXX(S/T)C

**Comment by sujeetvkulkarni** [comment]
@katewarner all other consensus sequences are found in https://www.ncbi.nlm.nih.gov/books/NBK579906/ except  WXXWXXW (C-Mannosylation). What is the source of WXXWXXW (C-Mannosylation)?

**Comment by katewarner** [comment]
@sujeetvkulkarni It was from this paper: https://febs.onlinelibrary.wiley.com/doi/10.1111/febs.16265

**Comment by rykahsay** [comment]
@ubhuiyan  ... where is the mapping file under the misc?

**Comment by ubhuiyan** [comment]
@rykahsay To my understanding, Sujeet had conducted his own research on consensus sequences and has already applied them to the front end. Kate has provided the sequences we found in this ticket for Sujeet to compare with his findings. I don't think she created a file in the misc folder for this given Sujeet has already been working on this. 

Would you like for this mapping to also be present within our misc folder?

**Comment by ubhuiyan** [comment]
@rykahsay I have provided this mapping in `misc/consensus_sequon_mapping.json`. Please let me know if you'd like me to change anything.

**Comment by rykahsay** [comment]
@sujeetvkulkarni 

Release specific URL for the file is:
https://data.glygen.org/ln2releases/data/v-2.6.1/misc/consensus_sequon_mapping.json


After we push to prd, you can also use this URL:
https://data.glygen.org/ln2releases/data/current/misc/consensus_sequon_mapping.json

**Comment by sujeetvkulkarni** [comment]
@rykahsay
We have referred these consensus sequences but a copy in frontend will be used to display and highlight protein sequences.
Closing this ticket.
Adding label informative for future reference.
