### ISSUE TITLE
Change Assessed Biomarker Entity to Biomarker information

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#1533]
Currently, the Biomarker sections shows `Assessed Biomarker Entity` information which is redundant instead it should show `Biomarker` for the protein or glycan.

eg. - https://www.glygen.org/protein/P14210#Biomarkers
eg. - https://www.glygen.org/biomarker/AA4761-1

<img width="943" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/12db0de4-a753-4470-aa53-5c0227912f6f">

<img width="472" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/6470bb05-475f-4ec9-876c-91d3779daa7b">

The change should reflect on

**Protein Detail
Glycan Detaill
Publication
Motif**

Current json for biomarker on - https://api.glygen.org/protein/detail/P14210/
```
  "biomarkers": [
    {
      "biomarker_id": "AA4761-1",
      "biomarker_canonical_id": "AA4761",
      "best_biomarker_role": [
        "prognostic"
      ],
      "condition": {
        "name_list": [
          "diabetes mellitus",
          "diabetes"
        ],
        "id_list": [
          "DOID:9351"
        ]
      },
      "evidence": [
        {
          "id": "GLY_000625",
          "database": "GlyGen",
          "url": "https://data.glygen.org/GLY_000625"
        },
        {
          "id": "16759302",
          "database": "PubMed",
          "url": "https://glygen.org/publication/PubMed/16759302"
        }
      ],
      "assessed_biomarker_entity": [
        "Hepatocyte growth factor"
      ]
    },
```

**Comment by rykahsay** [comment]
@sujeetvkulkarni  ... I have added the "biomarker" property, please use that value:

<img width="567" alt="image" src="https://github.com/user-attachments/assets/ec8b047b-8861-41d2-b8bf-b1bf5c016e7b">

**Comment by sujeetvkulkarni** [comment]
@jeet-vora Fixed for glycan, protein and motif pages.
https://tst.glygen.org/motif/GGM.000024#Biomarkers
https://tst.glygen.org/protein/P04275-1#Biomarkers
https://tst.glygen.org/glycan/G85767HW#Biomarkers

@rykahsay biomarker information needs to be added in publication api response. It is currently missing.
https://tst.glygen.org/publication/PubMed/32619411#Biomarkers
https://api.tst.glygen.org/publication/detail?query={"id":"32619411","type":"PubMed","paginated_tables":[]}
![Screenshot 2024-08-22 at 3 24 26 PM](https://github.com/user-attachments/assets/7f324bd9-518c-4197-8518-c84c39d6f0c7)

**Comment by jeet-vora** [comment]
@sujeetvkulkarni 
https://tst.glygen.org/motif/GGM.000024#Biomarkers ✅
https://tst.glygen.org/protein/P04275-1#Biomarkers ✅
https://tst.glygen.org/glycan/G85767HW#Biomarkers ✅

**Comment by rykahsay** [comment]
Fixed:

<img width="1350" alt="image" src="https://github.com/user-attachments/assets/e9792c0c-0e73-414b-9865-31a3fd60cd97">

**Comment by jeet-vora** [comment]
https://tst.glygen.org/publication/PubMed/32619411#Biomarkers ✅

@sujeetvkulkarni You can close the ticket if you have reviewed.

**Comment by sujeetvkulkarni** [comment]
Done. Closing issue.
