### ISSUE TITLE
Biomuta Xref links not working

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#1534]
Biomuta is defunct now and hence the Biomuta links are not showing the source entries any more, from the GlyGen SNV section.

https://hive.biochemistry.gwu.edu/biomuta/proteinview/P14210

**Comment by katewarner** [comment]
@rykahsay I emailed Reeya and she said that the Biomuta xref links should be fixed by this week and they would keep us updated. So do you think we should hold off disabling the xref links for now as they should be fixed before the release?

**Comment by rykahsay** [comment]
It is disabled on tst now, please check

**Comment by jeet-vora** [comment]
@rykahsay  Yes they are disabled now. Confirmed on the https://api.tst.glygen.org/protein/detail/P14210/ as the frontend was not loading up @sujeetvkulkarni FYI
