### ISSUE TITLE
Protein tissue ID missing

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#154]
Tissue ID is missing from protein tissue expression tab:

https://tst.glygen.org/protein/Q9BYF1-1#Expression-Tissue
![image](https://user-images.githubusercontent.com/90285371/226681829-b9e52313-0d6e-4e02-9592-7f60567fb178.png)

Protein details API was updated to include the following fields:
``` json
"expression_tissue": [{
    "tissue": {
    "name": "Kidney",
    "namespace": "UBERON",
    "id": "0000082",
    "url": "http://purl.obolibrary.org/obo/UBERON_0000082"
    },
```

Issue related to #141

**Comment by kmartinez834** [comment]
@jeet-vora

**Comment by sujeetvkulkarni** [comment]
8d1529212fc49c48e99486e2d3b9233bcbeb9d3b
