### ISSUE TITLE
For &quot;Glycosylated Protein&quot; help button,  the &quot;read more&quot; url should be changed to https://www.uniprot.org/help/accession_numbers

Kate

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1546]
## Details
**Created by:** myGlygen

**Feedback from:** myGlyGen@gmail.com

**Assigned to:** myGlygen

**Priority:**  normal

[Open Note](https://app.pageproofer.com/to/note/350408)

## Note
> For &amp;quot;Glycosylated Protein&amp;quot; help button,  the &amp;quot;read more&amp;quot; url should be changed to https://www.uniprot.org/help/accession_numbers

Kate

## Browser Information
**Window Size:** 1533 x 695
**Screen Size:** 1197 x 673
**Device:** WebKit
**Browser:** Edge version: 126.0.0.0
**Platform:** Windows version: 10.0

**Comment by sujeetvkulkarni** [comment]
@katewarner I have deployed the changes on tst please check.
https://tst.glygen.org/glycan-search/

**Comment by katewarner** [comment]
Thank you
