### ISSUE TITLE
The &quot;RefSeq Accession&quot; search help button &quot;read more&quot; url should be changed to
https://www.ncbi.nlm.nih.gov/books/NBK50679/#RefSeqFAQ.what_is_the_difference_between

Kate

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1548]
## Details
**Created by:** myGlygen

**Feedback from:** myGlyGen@gmail.com

**Assigned to:** myGlygen

**Priority:**  normal

[Open Note](https://app.pageproofer.com/to/note/350410)

## Note
> The &amp;quot;RefSeq Accession&amp;quot; search help button &amp;quot;read more&amp;quot; url should be changed to
https://www.ncbi.nlm.nih.gov/books/NBK50679/#RefSeqFAQ.what_is_the_difference_between

Kate

## Browser Information
**Window Size:** 1533 x 695
**Screen Size:** 1197 x 673
**Device:** WebKit
**Browser:** Edge version: 126.0.0.0
**Platform:** Windows version: 10.0

**Comment by sujeetvkulkarni** [comment]
@katewarner I have deployed the changes on tst please check.
https://tst.glygen.org/protein-search/

**Comment by katewarner** [comment]
Thank you
