### ISSUE TITLE
Generate arabidopsis_protein_xref_pride dataset

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1550]
I should have added arabidopsis to the protein_xref_pride object in the dataset-masterlist.json because there are 9 entries in UniProt with Pride xrefs that are present in our arabidopsis_protein_masterlist. 

![image](https://github.com/glygener/glygen-issues/assets/161866639/525e2925-fd86-4371-b8e4-b19259637084)
 
I've added arabidopsis to the xref_pride object in the dataset-masterlist.json. Please re-process the pride datasets.

**Comment by rykahsay** [comment]
Done, given below is what I see -- please check:

```
$ cat unreviewed/arabidopsis_protein_xref_pride.csv 
"uniprotkb_canonical_ac","xref_key","xref_id","xref_label"
"F4IBG4-1","protein_xref_pride","F4IBG4",""
"F4KCH3-1","protein_xref_pride","F4KCH3",""
"A8MS31-1","protein_xref_pride","A8MS31",""
"F4I9G2-1","protein_xref_pride","F4I9G2",""
"A8MRU6-1","protein_xref_pride","A8MRU6",""
"Q5EAH9-1","protein_xref_pride","Q9M048",""
"A8MQS5-1","protein_xref_pride","A8MQS5",""
"B3H7I1-1","protein_xref_pride","B3H7I1",""
"B3H4Y2-1","protein_xref_pride","B3H4Y2",""
```

**Comment by katewarner** [comment]
Those are correct. Many thanks
