### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1552]
GW team is having trouble accessing the server at the moment. I keep getting an error that the connection was unsuccessful.

**Comment by Luke-Johnson-5** [comment]
I as well am unable to connect dev.glygen server.

Here is the issue I am having.
![image](https://github.com/glygener/glygen-issues/assets/144174552/f1dd5bc9-8871-4e41-a775-ca07c9564f57)

**Comment by rykahsay** [comment]
I have asked Dacian to look into it -- looks like he messed up something
