### ISSUE TITLE
Incorrect glycan error message - G85526ZL

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1555]
Related to ticket #1551. GlyTouCan ID G85526ZL is valid in GlyTouCan but was removed in GlyGen (@ubhuiyan confirmed that). The error message on the GlyGen page says:

<img width="408" alt="Screenshot 2024-07-10 at 2 37 22 PM" src="https://github.com/glygener/glygen-issues/assets/2267640/6dd46072-3e35-4e66-9ca6-271db3a3c6d7">

There are several problems:
* G85526ZL **IS** a valid Glycan ID
* Its supposted to say when it was removed from GlyGen (version/date)
* Its supposted to have a link to GlyTouCan

**Comment by sujeetvkulkarni** [comment]
Will update display response for discontinued_in_glygen type. 
We dont have version or history in this case though as per #71.

Current api response is below.
https://api.glygen.org/glycan/detail/G85526ZL/

```
{
  "error_list": [
    {
      "error_code": "non-existent-record"
    }
  ],
  "reason": {
    "type": "discontinued_in_glygen",
    "description": "GlyTouCan accession discontinued in GlyGen"
  }
}
```

**Comment by sujeetvkulkarni** [comment]
@rykahsay 
Can you please add version when the id was discontinued in the description.

**Comment by rykahsay** [comment]
<img width="624" alt="image" src="https://github.com/user-attachments/assets/a8774714-8d56-49f6-9500-abc42c8d1b82">
