### ISSUE TITLE
Process Glycan and Proteoform Datasets 

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1558]
Data Download and Checking is completed. Please proceed with processing glycan and proteoform datasets.

**Comment by rykahsay** [comment]
This also mentioned in ticket #1466 
- *_proteoform_glycosylation_sites_larance_1338 is too specific (you will need to create BCO for every individual user), I would say *_proteoform_glycosylation_sites_user_submission --> which will contain all user submitted glycosylationd ata
- I need "instructions ticket for making new dataset" to create  *_proteoform_glycosylation_sites_user_submission  datasets
- I need "instructions ticket for making new dataset" to create  *_proteoform_glycosylation_sites_carbbank  datasets

The above items are a blocker for me to finish creating datasets -- introducing delay to our milestone

**Comment by rykahsay** [comment]
@ubhuiyan ... any update on this? This is a blocker

**Comment by ubhuiyan** [comment]
@rykahsay I can remove the carbbank object from the data-master list.json. I will be able to complete part of the instructions this release, but the remaining instructions will take some time. I can put it back once I have all the instructions available for that dataset for you. 

Kate is working on the user submitted data (this includes the protoeform dataset). She will have this completed and provide you with the instructions soon.
