### ISSUE TITLE
Github - page proofer integration

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#156]
Check if we can integrate Github - page proofer or not.

**Comment by sujeetvkulkarni** [comment]
Connect PageProofer with GitHub #157

**Comment by ReneRanzinger** [comment]
Monday: 
- #744 was deleted in PageProofer, check if its still there in GitHub
- #745 was closed on GitHub. Is it still open on PageProofer?
- Create an new ticket. Close in PageProofer. Is it still open in GitHub after this?

**Comment by sujeetvkulkarni** [comment]
When you create a ticket on PageProofer a ticket gets created on github. When you comment on PageProofer ticket comment gets added on Github. When you close a ticket on PageProofer ticket is closed on Github - https://github.com/glygener/glygen-issues/issues/782

**Comment by ReneRanzinger** [comment]
What happens in the delete case? Ticket is delete in PageProofer. Does it affect GitHub at all?

**Comment by sujeetvkulkarni** [comment]
If you delete ticket on PageProofer the ticket has no effect on Github.

**Comment by sujeetvkulkarni** [comment]
send an email.

**Comment by sujeetvkulkarni** [comment]
done.
