### ISSUE TITLE
EMBL datasets issue

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#1570]
Karina, below are my issue findings for the EMBL datasets
### Human

The Human Glycosylation Sites (EMBL) [GLY_000888](https://data.glygen.org/GLY_000888) dataset has discrepancy in site and amino acid assignment. These entries should have been flagged in the logs and discarded from the dataset by the QC.

eg.
`O75477-1	106	Asn` At 106 position there is a valine instead of asparagine.

<img width="636" alt="image" src="https://github.com/user-attachments/assets/799fad3a-69ad-4693-b321-35e59defe47f">

`O94901-8	732	Asn` At 732 position there is a phenylalanine instead of asparagine.

<img width="647" alt="image" src="https://github.com/user-attachments/assets/c4ab928e-3bfe-4c90-9ae3-2a8ff378731e">

 There are a total of **`58`** such sites in the datasets. 

### Mouse

The Mouse Glycosylation Sites (EMBL) [GLY_000889]([url](https://data.glygen.org/GLY_000889)) dataset also has discrepancy in site and amino acid assignment
eg.
`A2RS43-1	1130	Asn` This is interesting case, there is no 1130 position in the protein as the protein's length is 1069 only.

<img width="634" alt="image" src="https://github.com/user-attachments/assets/360b198e-a755-4771-af84-f2ab2159862d">

`Q00651-1	626	Asn` At 626 position there is a alanine instead of asparagine.

<img width="638" alt="image" src="https://github.com/user-attachments/assets/48409e6d-fd6c-4800-a16f-d3d5c98c72eb">

There are a total of **`427`** such sites in the datasets.  

Can you please review and let Robel know to reprocess the dataset. I am not sure why Robel's QC didn't detect it. We should also let the authors know about the incorrect assignemnt.

**Comment by kmartinez834** [comment]
Looks like their software has an old version of the sequences.  For instance, the position of O75477 shifted by 2 aa's, which explains why they're saying the glycosite is at 106:

>sp|O75477|Release 2019_03/2019_03|10-Apr-2019
MTQARVLVAAVVGLVAVLLYASIHKIEEGHLAVYYRGGALLTSPSGPGYHIMLPFITTFR
SVQTTLQTDEVKNVPCGTSGGVMIYIDRIEVVNMLAPYAVFDIVRNYTADYDKTLIFNKI
HHELNQFCSAHTLQEVYIELFDQIDENLKQALQKDLNLMAPGLTIQAVRVTKPKIPEAIR
RNFELMEAEKTKLLIAAQKQKVVEKEAETERKKAVIEAEKIAQVAKIRFQQKVMEKETEK
RISEIEDAAFLAREKAKADAEYYAAHKYATSNKHKLTPEYLELKKYQAIASNSKIYFGSN
IPNMFVDSSCALKYSDIRTGRESSLPSKEALEPSGENVIQNKESTG

>sp|O75477|ERLN1_HUMAN Erlin-1 OS=Homo sapiens OX=9606 GN=ERLIN1 PE=1 SV=2
MNMTQARVLVAAVVGLVAVLLYASIHKIEEGHLAVYYRGGALLTSPSGPGYHIMLPFITT
FRSVQTTLQTDEVKNVPCGTSGGVMIYIDRIEVVNMLAPYAVFDIVRNYTADYDKTLIFN
KIHHELNQFCSAHTLQEVYIELFDQIDENLKQALQKDLNLMAPGLTIQAVRVTKPKIPEA
IRRNFELMEAEKTKLLIAAQKQKVVEKEAETERKKAVIEAEKIAQVAKIRFQQKVMEKET
EKRISEIEDAAFLAREKAKADAEYYAAHKYATSNKHKLTPEYLELKKYQAIASNSKIYFG
SNIPNMFVDSSCALKYSDIRTGRESSLPSKEALEPSGENVIQNKESTG

I didn't get a chance to reach out to them, will have to pass this back to you Jeet.  Could you also bring this issue to their attention:
--> The human_proteoform_glycosylation_sites_embl.csv file contains brain entries because they used the human UniProt accessions in their file, however this should be mouse:
```
$ tail reviewed/human_proteoform_glycosylation_sites_embl.csv
"P15586-1","387","Asn","G90382BL","N-linked","protein_xref_doi","10.1101/2023.09.13.557529v1","protein_xref_glygen_ds","GLY_000888","UBERON:0000002","uterine cervix","CVCL_0030","HeLa","387","387","N","N","MLVANIDLGPTILDIAGYDLNK","sialylated","GNS","HexNAc(5)Hex(5)Fuc(1)NeuAc(2)","2553.9098","NKT","NXT"
"Q5T4B2-1","153","Asn","G83460ZZ","N-linked","protein_xref_doi","10.1101/2023.09.13.557529v1","protein_xref_glygen_ds","GLY_000888","UBERON:0000002","uterine cervix","CVCL_0030","HeLa","153","153","N","N","NWGADYILFADTDNILTNNQTLR","high mannose","CERCAM","HexNAc(2)Hex(10)","2026.6871","NQT","NXT"
"Q99650-1","307","Asn","G80920RR","N-linked","protein_xref_doi","10.1101/2023.09.13.557529v1","protein_xref_glygen_ds","GLY_000888","UBERON:0000002","uterine cervix","CVCL_0030","HeLa","307","307","N","N","NWCNWQITQDSQETYNFTLIAENYLR","high mannose","OSMR","HexNAc(2)Hex(9)","1864.6342","NFT","NXT"
"P10586-1","295","Asn","G76295SF","N-linked","protein_xref_doi","10.1101/2023.09.13.557529v1","protein_xref_glygen_ds","GLY_000888","UBERON:0000002","uterine cervix","CVCL_0030","HeLa","295","295","N","N","SANYTCVAISSLGMIEATAQVTVK","sialylated","PTPRF","HexNAc(5)Hex(4)Fuc(1)NeuAc(1)","2100.7615","NYT","NXT"
"Q12913-1","431","Asn","G39471UU","N-linked","protein_xref_doi","10.1101/2023.09.13.557529v1","protein_xref_glygen_ds","GLY_000888","UBERON:0000002","uterine cervix","CVCL_0030","HeLa","431","431","N","N","SSTFYNITVCPVLGDIEGTPGFLQVHTPPVPVSDFR","complex/hybrid","PTPRJ","HexNAc(8)Hex(9)","3083.1105","NIT","NXT"
"P10909-1","145","Asn","G25079LO","N-linked","protein_xref_doi","10.1101/2023.09.13.557529v1","protein_xref_glygen_ds","GLY_000888","UBERON:0000002","uterine cervix","CVCL_0030","HeLa","145","145","N","N","QLEEFLNQSSPFYFWMNGDRIDSLLENDR","complex/hybrid","CLU","HexNAc(6)Hex(4)","1866.6876","NQS","NXS"
"Q9H0X4-1","473","Asn","G62765YT","N-linked","protein_xref_doi","10.1101/2023.09.13.557529v1","protein_xref_glygen_ds","GLY_000888","UBERON:0000002","uterine cervix","CVCL_0030","HeLa","473","473","N","N","VLLELANVSTHIVAFDAVLFEPSR","high mannose","FAM234A","HexNAc(2)Hex(8)","1702.5814","NVS","NXS"
"P01112-1","85","Asn","G27915IV","N-linked","protein_xref_doi","10.1101/2023.09.13.557529v1","protein_xref_glygen_ds","GLY_000888","UBERON:0000955","brain","","","85","85","N","N","DQYMRTGEGFLCVFAINNTKSFEDIHQYR","fucosylated","HRAS","HexNAc(6)Hex(5)Fuc(1)","2174.7984","NNT","NXT"
"P04040-1","244","Asn","G02815KT","N-linked","protein_xref_doi","10.1101/2023.09.13.557529v1","protein_xref_glygen_ds","GLY_000888","UBERON:0000955","brain","","","244","244","N","N","NLSVEDAAR","high mannose","CAT","HexNAc(2)Hex(5)","1216.4229","NLS","NXS"
"P04040-1","439","Asn","G14972EH","N-linked","protein_xref_doi","10.1101/2023.09.13.557529v1","protein_xref_glygen_ds","GLY_000888","UBERON:0000955","brain","","","439","439","N","N","FNTANDDNVTQVR","fucosylated","CAT","HexNAc(5)Hex(5)Fuc(3)","2263.8347","NVT","NXT"
```
--> You can see in the source file, these rows are mus musculus & brain:
```
$ grep "P01112\|P04040" /data/projects/glygen/downloads/embl/current/glygen_upload.csv
"P01112","HRAS","85","Asn","N-linked","69","97","DQYMRTGEGFLCVFAINNTKSFEDIHQYR","10090","mus musculus","HexNAc(6)Hex(5)Fuc(1) % 2174.7984","2174.7984","fucosylated","","UBERON:0000955","brain","","","https://www.biorxiv.org/content/10.1101/2023.09.13.557529v1.full"
"P04040","CAT","244","Asn","N-linked","244","252","NLSVEDAAR","10090","mus musculus","HexNAc(2)Hex(5) % 1216.4229","1216.4229","high mannose","","UBERON:0000955","brain","","","https://www.biorxiv.org/content/10.1101/2023.09.13.557529v1.full"
"P04040","CAT","439","Asn","N-linked","432","444","FNTANDDNVTQVR","10090","mus musculus","HexNAc(5)Hex(5)Fuc(3) % 2263.8347","2263.8347","fucosylated","","UBERON:0000955","brain","","","https://www.biorxiv.org/content/10.1101/2023.09.13.557529v1.full"
```

**Comment by jeet-vora** [comment]
@rykahsay 

The datasets Human Glycosylation Sites (EMBL) [GLY_000888](https://data.glygen.org/GLY_000888) and the Mouse Glycosylation Sites (EMBL) [GLY_000889](https://data.glygen.org/GLY_000889) have issues. Please see my comments below.

**Input** - 
/data/projects/glygen/downloads/embl/current/glygen_upload.csv
**Output** - 
https://data.glygen.org/ln2data/releases/data/v-2.5.1/reviewed/human_proteoform_glycosylation_sites_embl.csv
https://data.glygen.org/ln2data/releases/data/v-2.5.1/reviewed/mouse_proteoform_glycosylation_sites_embl.csv


1) The amino acid in the source dataset does not match with the protein dataset. Human - `O75477-1	106	Asn` At 106 position there is a valine instead of asparagine.

2) The site in the source dataset does not match with the current protein site. Human - `A2RS43-1	1130	Asn` This is interesting case, there is no 1130 position in the protein as the protein's length is 1069 only.

2) The organisms and the protein in the source dataset does not match. In the below the accession should have been mouse as the organism mentioned is mouse however the accession added by authors is human which is incorrect. P04040 is a human protein accession, it should have been mouse.
```
$ grep "P01112\|P04040" /data/projects/glygen/downloads/embl/current/glygen_upload.csv
"P01112","HRAS","85","Asn","N-linked","69","97","DQYMRTGEGFLCVFAINNTKSFEDIHQYR","10090","mus musculus","HexNAc(6)Hex(5)Fuc(1) % 2174.7984","2174.7984","fucosylated","","UBERON:0000955","brain","","","https://www.biorxiv.org/content/10.1101/2023.09.13.557529v1.full"
"**P04040**","CAT","244","Asn","N-linked","244","252","NLSVEDAAR","10090","**mus musculus**","HexNAc(2)Hex(5) % 1216.4229","1216.4229","high mannose","","UBERON:0000955","brain","","","https://www.biorxiv.org/content/10.1101/2023.09.13.557529v1.full"
"P04040","CAT","439","Asn","N-linked","432","444","FNTANDDNVTQVR","10090","mus musculus","HexNAc(5)Hex(5)Fuc(3) % 2263.8347","2263.8347","fucosylated","","UBERON:0000955","brain","","","https://www.biorxiv.org/content/10.1101/2023.09.13.557529v1.full"
```

Please run the QC steps to check the amino acid, site, protein-organism and reprocess the dataset. Also, generate a log file with filter entries with reason so that it could be shared with the authors.

FYI @katewarner @ubhuiyan to understand the issue and track. For new datasets please let Robel know to include QC steps and also do a check yourself for similar issue in the source file.

**Comment by jeet-vora** [comment]
For testing

Methionine is shown as glycosylated - Q91ZU6 Site 4457

<img width="966" alt="image" src="https://github.com/user-attachments/assets/c68b5988-4662-4209-b824-188c84d48e3f">

**Comment by rykahsay** [comment]
It is being filtered out now, please check as follows:

```
$ cat logs/human_proteoform_glycosylation_sites_embl.log  | grep O75477
"O75477","ERLIN1","106","Asn","N-linked","106","113","NYTADYDK","9606","homo sapiens","HexNAc(2)Hex(9) % 1864.6342","1864.6342","high mannose","","UBERON:0002113","kidney","CVCL_0063","HEK293T","https://www.biorxiv.org/content/10.1101/2023.09.13.557529v1.full","aa_mismatch"
```

**Comment by jeet-vora** [comment]
@rykahsay Check the accession for the organism in the source dataset.

The organisms and the protein in the source dataset does not match. In the below the accession should have been mouse as the organism mentioned is mouse however the accession added by authors is human which is incorrect. P04040 is a human protein accession, it should have been mouse.

```
$ grep "P01112\|P04040" /data/projects/glygen/downloads/embl/current/glygen_upload.csv
"P01112","HRAS","85","Asn","N-linked","69","97","DQYMRTGEGFLCVFAINNTKSFEDIHQYR","10090","mus musculus","HexNAc(6)Hex(5)Fuc(1) % 2174.7984","2174.7984","fucosylated","","UBERON:0000955","brain","","","https://www.biorxiv.org/content/10.1101/2023.09.13.557529v1.full"
"**P04040**","CAT","244","Asn","N-linked","244","252","NLSVEDAAR","10090","**mus musculus**","HexNAc(2)Hex(5) % 1216.4229","1216.4229","high mannose","","UBERON:0000955","brain","","","https://www.biorxiv.org/content/10.1101/2023.09.13.557529v1.full"
"P04040","CAT","439","Asn","N-linked","432","444","FNTANDDNVTQVR","10090","mus musculus","HexNAc(5)Hex(5)Fuc(3) % 2263.8347","2263.8347","fucosylated","","UBERON:0000955","brain","","","https://www.biorxiv.org/content/10.1101/2023.09.13.557529v1.full"
```

**Comment by rykahsay** [comment]
Please check now

**Comment by jeet-vora** [comment]
Done
