### ISSUE TITLE
Duplicated rows in protein datasets

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1571]
During dataset checking I found a number of protein datasets appear to have duplicated rows as the number of rows in a number of datasets is larger than the number of unique rows e.g. 

```
[k.warner1@glygen-vm-dev glygen]$ cat /data/projects/glygen/generated/datasets/unreviewed/arabidopsis_protein_transcriptlocus.csv | wc -l
52098
[k.warner1@glygen-vm-dev glygen]$ sort -u /data/projects/glygen/generated/datasets/unreviewed/arabidopsis_protein_transcriptlocus.csv | wc -l
40284
[k.warner1@glygen-vm-dev ~]$ cat /data/projects/glygen/generated/datasets/unreviewed/fruitfly_protein_xref_orthodb.csv | wc -l
20597
[k.warner1@glygen-vm-dev ~]$ sort -u /data/projects/glygen/generated/datasets/unreviewed/fruitfly_protein_xref_orthodb.csv | wc -l
13364
```

**Duplicated rows in csv**
`/data/projects/glygen/generated/datasets/unreviewed/arabidopsis_protein_transcriptlocus.csv`
![image](https://github.com/user-attachments/assets/179561fa-3bb9-42b0-baa6-aaa9059ec5c5)

**The datasets which look like they have duplicated rows:**
arabidopsis_protein_transcriptlocus.csv
chicken_protein_transcriptlocus.csv
fruitfly_protein_transcriptlocus.csv
human_protein_transcriptlocus.csv
mouse_protein_transcriptlocus.csv
pig_protein_transcriptlocus.csv
rat_protein_transcriptlocus.csv

arabidopsis_protein_xref_oma.csv
chicken_protein_xref_oma.csv
fruitfly_protein_xref_oma.csv
human_protein_xref_oma.csv
mouse_protein_xref_oma.csv
pig_protein_xref_oma.csv
rat_protein_xref_oma.csv

arabidopsis_protein_xref_orthodb.csv
chicken_protein_xref_orthodb.csv
fruitfly_protein_xref_orthodb.csv
human_protein_xref_orthodb.csv
mouse_protein_xref_orthodb.csv
pig_protein_xref_orthodb.csv
rat_protein_xref_orthodb.csv

arabidopsis_protein_xref_panther.csv
chicken_protein_xref_panther.csv
dicty_protein_xref_panther.csv
fruitfly_protein_xref_panther.csv
human_protein_xref_panther.csv
mouse_protein_xref_panther.csv
pig_protein_xref_panther.csv
rat_protein_xref_panther.csv
yeast_protein_xref_panther.csv

arabidopsis_protein_xref_pfam.csv
chicken_protein_xref_pfam.csv
dicty_protein_xref_pfam.csv
human_protein_xref_pfam.csv
mouse_protein_xref_pfam.csv
pig_protein_xref_pfam.csv

arabidopsis_protein_xref_rhea.csv
chicken_protein_xref_rhea.csv
dicty_protein_xref_rhea.csv
fruitfly_protein_xref_rhea.csv
human_protein_xref_rhea.csv
mouse_protein_xref_rhea.csv
pig_protein_xref_rhea.csv
rat_protein_xref_rhea.csv

**Comment by rykahsay** [comment]
please check now

**Comment by katewarner** [comment]
The "*_protein_transcriptlocus.csv" datasets looked fixed but the other datasets (see below), still seem to have duplicated rows.

*_protein_xref_oma.csv
*_protein_xref_orthodb.csv
*_protein_xref_panther.csv
*_protein_xref_pfam.csv

**Comment by rykahsay** [comment]
Sorry, check now

**Comment by katewarner** [comment]
This dataset still has duplicated rows (I forgot to add it in my last comment): 
*_protein_xref_rhea.csv

The other datasets look correct

**Comment by rykahsay** [comment]
I have done it systematically now and there shouldn't be any dataset with redundant rows

**Comment by katewarner** [comment]
Looks fixed. Thank you
