### ISSUE TITLE
Reprocess PDC ccRCC files

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1572]
There was a minor typo in the file names. I've updated the json masterlist and BCOs. Please reprocess the following datasets:

human_proteoform_glycosylation_sites_pdc_ccrc
human_proteoform_citations_glycosylation_sites_pdc_ccrc
human_proteoform_ml_ready_pdc_ccrc

Thanks!

**Comment by kmartinez834** [comment]
Files should be ccrcc for clear cell renal cell carcinoma (they were missing the last "c")
- @rykahsay please update the json masterlist to change the output file names to: *_pdc_ccrcc and reprocess

I have already updated:

- BCOs (GLY_000961, GLY_001027, GLY_001046)
- Compiled file for the ML file: compiled/human_proteoform_ml_ready_pdc_ccrcc.csv

**Comment by rykahsay** [comment]
Done, please check
