### ISSUE TITLE
Document 3D structure selection and display from EBI

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1573]
Document how we select and display 3D structures so that UniProt can provide us with the correct PDB and AlphaFold xrefs for 2.7.

1. Select 3D structures as in selection criteria: See #1517
2. Always provide AlphaFold structures

**Comment by katewarner** [comment]
@rykahsay At the beginning of 2.6, I remember that a decision was made that you would create the PDB and Alphafold xref datasets for 2.6 and then UniProt would provide them for 2.7 onwards. 

Do you still want UniProt to provide the PDB and Alphafold xrefs for 2.7, because in the last PDB ticket you asked me to document in our release protocol that you will download the PDB coordinate files after the creation of the *_protein_pdb_map.csv and *_protein_xref_alphafolddb.csv datasets, which suggests that UniProt will not be required to create the datasets or files.

**Comment by katewarner** [comment]
@rykahsay sorry but can you let me know about this asap, in case they need to add this to the 2.7 downloads

**Comment by katewarner** [comment]
@rykahsay can you reply to my question above asap? Do you still want UniProt to provide the PDB and Alphafold xrefs for future releases? I think it's too late now if you want UniProt to do it for 2.7, but I can start working with Jie or Preethi's replacement to put this in place for 2.8

**Comment by rykahsay** [comment]
Yes, please have them provide  PDB and Alphafold xrefs

**Comment by katewarner** [comment]
@rykahsay okay I'll speak to Jie about implementing this for 2.8
