### ISSUE TITLE
ln2data current pointing to folder from 19-Jan-2024

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1574]
https://data.glygen.org/ln2data/releases/data/current/

![image](https://github.com/user-attachments/assets/5d0643a4-19d8-4c51-b96c-9f6844b5bf99)

**Comment by rykahsay** [comment]
Check now:

<img width="644" alt="image" src="https://github.com/user-attachments/assets/87eb9f4e-e58e-4980-8c67-450256471ee0">
