### ISSUE TITLE
Error for BCO GLY_001078

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1577]
One of the BCOs (#1502) you created (GLY_001078) is producing an error message that there is no BCO, even though the BCO is on BioCompute. 

`NO-BCO,arabidopsis_protein_site_annotation_uniprotkb.csv,ERROR,in_fs`

Karina took a look and it looks like you copied GLY_001056 (arabidopsis_protein_citations_uniprotkb.csv) and forgot to change the name of the bco and the output files.

**Comment by CyrusAY** [comment]
@katewarner,
fixed
