### ISSUE TITLE
human_protein_xref_cfde_gdlpa dataset contains only one accession

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1582]
The appears to be a problem with protein mapping in the `human_protein_xref_cfde_gdlpa.csv` dataset. In the last release there was 18941 protein ACs but the latest dataset only contains one AC. Between the two releases the downloads looks the same, and the number or rows hasn't changed between the releases so it looks like the one accession has been mapped to all the rows in the dataset.

```
[k.warner1@glygen-vm-dev ~]$ awk -F, '{print $1}' /data/shared/glygen/releases/data/v-2.5.1/reviewed/human_protein_xref_cfde_gdlpa.csv | sort -u | grep -v "uniprotkb_ac" | wc -l
18943
[k.warner1@glygen-vm-dev ~]$ awk -F, '{print $1}' /data/projects/glygen/generated/datasets/unreviewed/human_protein_xref_cfde_gdlpa.csv | sort -u | grep -v "uniprotkb_ac" | wc -l
2
```

human_protein_xref_cfde_gdlpa.csv

**Comment by rykahsay** [comment]
Please check now

**Comment by katewarner** [comment]
Thank you it's fixed
