### ISSUE TITLE
Updates publication APIs (tissue expression)

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#159]
Change tissue and cell line expression in APIs to look like the protein and glycan details api:

https://api.tst.glygen.org/publication/detail?query={%22id%22:%2233077685%22,%22type%22:%22PubMed%22}
https://api.tst.glygen.org/publication/detail?query={%22id%22:%2210.1039/D0MO00044B%22,%22type%22:%22DOI%22}

/publication/PubMed/33077685
/publication/DOI/10.1039/D0MO00044B

**Comment by rykahsay** [comment]
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/20584876/228074578-6e3b7c4e-5a19-49fb-84d6-39460894f20c.png">

**Comment by sujeetvkulkarni** [comment]
c17cd800e322f151d76a3f12f04fccc740e1758d
