### ISSUE TITLE
Logfile for datasets ...

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1591]
It looks like you are not looking into logfiles of datasets to understand why some records from input/download files are filtered out. Please do not forget to so -- and put that in the backend documentation if it is not already there.

For example, here I am asking why site 431 on protein Q96RK0 is filtered out, and the answer is in the last column.

```
$ cat logs/human_proteoform_phosphorylation_sites_iptmnet.log | grep Q96RK0 | grep 431
"Q96RK0-1","431","Ser","","","protein_xref_hprd","Q96RK0","protein_xref_iptmnet","Q96RK0","aa_mismatch"
"Q96RK0-1","431","Ser","","","protein_xref_psp","Q96RK0","protein_xref_iptmnet","Q96RK0","aa_mismatch"
```

Here, am asking why record for P55786 is filtered out in /human_proteoform_glycosylation_sites_oglcnac_atlas, and the answer is "aa_pos_non_numeric" 
```
$ cat logs/human_proteoform_glycosylation_sites_oglcnac_atlas.log | grep P55786
"P55786-1","203.0","Ser","G49108TO","O-linked","protein_xref_pubmed","29351928","protein_xref_oglcnac_atlas","P55786","3065","T cells","MS","HTP","GlcNAc","O-GlcNAcylation","aa_pos_non_numeric"
```

**Comment by katewarner** [comment]
I've added this to our documentation for checking datasets: [doc](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7BA8D8EA0A-F1A5-4C3E-8DB7-0C63D8AD070F%7D&file=Dataset%20Checking%20(QC).docx&action=default&mobileredirect=true)
