### ISSUE TITLE
Xref badge/url changes

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1592]
Make tickets for Robel:

1. Biomuta datasetes that contain annotations (not xref only), change xref_key to protein_xref_glygen_ds and xref_id to bco number
2. List of all datasets for which badge will change from GlyGen to Data Submission, change xref_key to protein_xref_data_submission
Use this command to print the first occurrence in each unreviewed file: `$ grep -m1 _xref_glygen_ds unreviewed/*`
3. Make a separate ticket to change xref_id of the following datasets (from GLYGDS... to GLY_....):
```
$ grep -m1 GLYGDS unreviewed/*
unreviewed/hcv1a_protein_disease_glygen.csv:"P27958-1","protein_xref_glygen_ds","GLYGDS000487","1883","",""
unreviewed/hcv1b_protein_disease_glygen.csv:"P26662-1","protein_xref_glygen_ds","GLYGDS000488","1883","",""
unreviewed/sarscov1_protein_disease_glygen.csv:"P59596-1","protein_xref_glygen_ds","GLYGDS000489","2945","",""
```

**Comment by katewarner** [comment]
Started task 3: #1602
