### ISSUE TITLE
Empty protein_pdb_map.csv datasets

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1594]
The `sarscov2_protein_pdb_map.csv`, `hcv1a_protein_pdb_map.csv` and `hcv1b_protein_pdb_map.csv` datasets are empty except for text along the lines of:  

```
one of the required files [unreviewed/hcv1a_protein_canonicalsequences.fasta,unreviewed/hcv1a_protein_xref_alphafolddb.csv] does not exist!
```

These organisms/proteins do have PDB xrefs so I think they should have pdb_map datasets. However, I had a look on UniProt and these organisms don't have Alphafold xrefs which may be affecting your script. Are we including the Alphafold mapping in the "protein_pdb_map.csv" datasets?

**Comment by rykahsay** [comment]
I have removed them, they shouldn't have been created

**Comment by katewarner** [comment]
Okay many thanks
