### ISSUE TITLE
New Google Analytics 4 (GA4) property

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#16]
We would need to create new GA4 property.

On July 1, 2023, this property will stop processing data. Starting in March 2023, for continued website measurement, you should create a new Google Analytics 4 (GA4) property, or one will be created for you based on your original property and reusing existing site tags.

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/25825266/216383113-1ac9f393-e6d4-4b38-bd1a-665a5e486a5a.png">

**Comment by ReneRanzinger** [comment]
@sujeetvkulkarni lets talk about it next Wednesday.

**Comment by ReneRanzinger** [comment]
We did this.
