### ISSUE TITLE
type ahead api not working

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#160]
https://api.tst.glygen.org/typeahead?query={"field":"glytoucan_ac","value":"g","limit":100}

**Comment by rykahsay** [comment]
Your URL is not correct, use 
```
https://api.tst.glygen.org/typeahead/typeahead?query={"field":"glytoucan_ac","value":"g","limit":100}
```


<img width="1438" alt="image" src="https://user-images.githubusercontent.com/20584876/227265987-a0472872-edfd-442b-80f4-1c71f1266a74.png">

**Comment by sujeetvkulkarni** [comment]
bc313d2242732481d1e55f39a3150a7eb196bcc3
