### ISSUE TITLE
Glycan search list - HCV issue

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1600]
https://glygen.org/glycan-list/c204dc540b1769522e9348d641ad5803

HCV and HCV-H77 search results are collapsed, but they should be separate.  Filter numbers are correct, 

![image](https://github.com/user-attachments/assets/84afb1bc-6f47-4bae-8582-3cd73239ac96)

**Comment by rykahsay** [comment]
Fixed on tst

<img width="863" alt="image" src="https://github.com/user-attachments/assets/3e031cd7-bd73-407d-9718-9e86fdb86327">
