### ISSUE TITLE
Missing record on prd data page: https://data.glygen.org/GLY_000143

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1601]
The "human_proteoform_glycosylation_sites_literature.csv" dataset is missing from the data page: https://data.glygen.org/GLY_000143

I'm not sure, but it may be because the base url which is `baseURI: "https://data.glygen.org/results/34c91629ba1ab8615050db0926bd7336"`, but according to the other dataset url links, it should be `baseURI: "https://data.glygen.org/"`

**Comment by rykahsay** [comment]
Tried to fix it, please check

**Comment by katewarner** [comment]
It's fixed. Thank you
