### ISSUE TITLE
Change xref id from GLYGDS... to GLY...

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1602]
Please change the "xref_id" of the following datasets, from GLYGDS... to GLY_....

```
$ grep -m1 GLYGDS000 unreviewed/*
unreviewed/hcv1a_protein_disease_glygen.csv:"P27958-1","protein_xref_glygen_ds","GLYGDS000487","1883","",""
unreviewed/hcv1b_protein_disease_glygen.csv:"P26662-1","protein_xref_glygen_ds","GLYGDS000488","1883","",""
unreviewed/sarscov1_protein_disease_glygen.csv:"P59596-1","protein_xref_glygen_ds","GLYGDS000489","2945","",""
```

Should be: 
```
unreviewed/hcv1a_protein_disease_glygen.csv:"P27958-1","protein_xref_glygen_ds","GLY_000487","1883","",""

unreviewed/hcv1b_protein_disease_glygen.csv:"P26662-1","protein_xref_glygen_ds","GLY_000488","1883","",""

unreviewed/sarscov1_protein_disease_glygen.csv:"P59596-1","protein_xref_glygen_ds","GLY_000489","2945","",""
```

**Comment by rykahsay** [comment]
Done, please check. Again, this involved entering the mapping to the ds2bco.json ( I have done it already).

<img width="966" alt="image" src="https://github.com/user-attachments/assets/116a15ba-edc1-4526-8e3f-8a8f12b65621">

**Comment by katewarner** [comment]
Sorry about that. The datasets are fixed thank you, but I have a question about the ds2bco.json

I couldn't find any documentation on the "ds2bco.json" file so I'll add it our guidelines. Could you clarify the purpose of the "ds2bco.json" file so that I get it right, is it to map datasets to their BCO which is used in the dataset as a xref_key?

**Comment by ubhuiyan** [comment]
I believe the ds2bco.json is a file we typically update when we have a new resource we are adding to glygen. The way I think of it is if I have to provide mapping instructions for a dataset for Robel, then that likely means I'll have to update the ds2bco.json before I send the ticket to have Robel create the respective datasets. I could help write the documentation for that section if you'd like Kate!

**Comment by rykahsay** [comment]
If a record in a given dataset CAN NOT be referenced to an external database website, then it has to be referenced to the dataset page on data.glygen.org. The way to do this is by setting the src_xref_key/src_xref_id (or xref_key/xref_id) fields in the dataset to "proteinxref_glygen_ds/GLY_XXXXXXX" values.  Question is, how does the script that creates the dataset know if the dataset needs this kind of special treatment? Answer: it looks in ds2bco.json

Points to note:
- Not all datasets need this kind of treatment (only those whose records CANNOT be referenced to external database site)

**Comment by katewarner** [comment]
Thank you both, I understand it now. I'll add that info to the documentation
