### ISSUE TITLE
xref_data_submission datasets

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1607]
Please review the list of datasets for which I think the badge should change from GlyGen to Data Submission to highlight datasets that have been submitted by a user. In these cases the xref_key will change to `protein_xref_data_submission` or `glygen_xref_data_submission`

Data submission
GLY_000600	glycan_ncfg.csv
GLY_000538	glycan_citations_ncfg.csv
GLY_000342	glycan_species_customized_neuac_neugc.csv
GLY_000309	glycan_synthesized.csv
GLY_000960	human_proteoform_glycosylation_sites_diabetes_glycomic.csv
GLY_000888	human_proteoform_glycosylation_sites_embl.csv
GLY_000142	human_proteoform_glycosylation_sites_harvard.csv
GLY_000716	human_proteoform_glycosylation_sites_o_gluc.csv

**Comment by ubhuiyan** [comment]
@katewarner do you mind doing a brief call sometime Wednesday (I'll propose 1pm) to go over this ticket? I just have a few questions I wanna clear up before I give the O.K!

**Comment by katewarner** [comment]
@ubhuiyan Sure, that's a good idea. We could also go through each dataset on the call. See you at 1pm!

**Comment by ubhuiyan** [comment]
@katewarner I have taken a look at each of the resources you've listed, and they all check out for the Data Submission badge in my opinion. Great work!

**Comment by ubhuiyan** [comment]
@jeet-vora Can you verify these and then close the ticket if the suggested badge changes look okay to you.

**Comment by jeet-vora** [comment]
@katewarner @ubhuiyan The list looks good

Add this as well - `GLY_000335 hcv1a_proteoform_glycosylation_sites_literature.csv`

**Comment by katewarner** [comment]
Okay great! Thank you both. 

I will move this to 2.7 as it's too late for 2.6
