### ISSUE TITLE
Dataset name change for user dataset

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1608]
As we discussed yesterday, can you please change the filename of the `human_proteoform_glycosylation_sites_platelet_olinked.csv` user dataset (see #1578 ) to `human_proteoform_glycosylation_sites_platelet.csv`.

I've already updated the dataset-masterlist.json and the ds2bco.json with the new file name. Once the filename has been updated I'll update the BCOs .

**Comment by rykahsay** [comment]
Done, please check

**Comment by katewarner** [comment]
Thank you
