### ISSUE TITLE
No records on data.tst.glygen.org

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1609]
When I try to view the datasets on data.tst.glygen.org the records are empty:

![image](https://github.com/user-attachments/assets/1880b4b4-d98b-4fa9-a695-11c256d55d6f)

e.g. https://data.tst.glygen.org/GLY_000029, https://data.tst.glygen.org/GLY_000026, https://data.tst.glygen.org/GLY_000294

**Comment by rykahsay** [comment]
Try now:

<img width="810" alt="image" src="https://github.com/user-attachments/assets/e7564023-9f58-4967-90d8-202a4febaac0">

**Comment by katewarner** [comment]
Fixed thank you

**Comment by katewarner** [comment]
Fixed thank you
