### ISSUE TITLE
Missing version transitions on history_list

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1610]
On https://data.tst.glygen.org/history_list some of the version transitions don't create a dataset:

v-2.5.1 to v.2.6.1
v-2.3.1 to v.2.4.1
v-2.2.1 to v.2.3.1
v-2.1.1 to v.2.2.1
v-2.0.3 to v.2.1.1
v-1.12.3 to v.2.0.3
v-2.5.1 to v.2.6.1

![image](https://github.com/user-attachments/assets/fa0248be-ee37-4427-a36f-a7eb36ac6834)

**Comment by rykahsay** [comment]
This is what I see now:

<img width="698" alt="image" src="https://github.com/user-attachments/assets/08c21b48-e4ec-4992-bf76-db7bbe025dab">

**Comment by katewarner** [comment]
The version transition for 2.5.1 to v.2.6.1 is fixed, but I still don't see a dataset for the following versions: 

v-2.3.1 to v.2.4.1
v-2.2.1 to v.2.3.1
v-2.1.1 to v.2.2.1
v-2.0.3 to v.2.1.1
v-1.12.3 to v.2.0.3
v-2.5.1 to v.2.6.1

**Comment by rykahsay** [comment]
Please check now

**Comment by katewarner** [comment]
It's fixed. Thank you
