### ISSUE TITLE
Filters not working on data.tst.glygen.org

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1611]
When I try the different filters on the data.tst.glygen.org home page (i.e. species, file type, molecule, scope, status, usability) it tells me how many datasets should be shown after filtering, but the displayed datasets are not filtered and there seems to be no change in the number of displayed datasets: 
![image](https://github.com/user-attachments/assets/619b88ef-02ec-48db-a3b9-e378bd1990da)

**Comment by rykahsay** [comment]
Please check now

**Comment by katewarner** [comment]
Fixed. Many thanks
