### ISSUE TITLE
Cannot download datasets on data.tst.glygen.org

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1612]
When I try to download a dataset on the downloads tab, I get the following error message: 

```
	File not found:
https://data.tst.glygen.org/ln2data/releases/data/v-2.6.1/reviewed/human_protein_masterlist.csv
```
I tried to download several datasets and got the same error message. The URL looks correct when I compare it to the one on PRD, but I'm not sure where on the sever I can find the directory `/ln2data/releases/data/` to check that the `v-2.6.1/reviewed/` folder is there and contains the datasets.

**Comment by rykahsay** [comment]
please check now

**Comment by katewarner** [comment]
It's fixed, but I noticed something else (I'm not sure if it's an issue or not). 

When you select "Download dataset file" and you have another browser tab open, it switches to the next tab, stays on that tab and then starts the download. This doesn't happen on PRD.

**Comment by rykahsay** [comment]
Let's ignore this

**Comment by katewarner** [comment]
Okay thanks

**Comment by katewarner** [comment]
Okay will do
