### ISSUE TITLE
Issue with ntdata files version history

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1613]
I noticed a strange bug with the version history for EBI-UniProtKB NT files. On the sample view page for the dataset, when you select different version histories using the drop down, after the second or third selection the dataset disappears (see below). This only seemed to happen with the protein_ntdata.nt datasets.

![image](https://github.com/user-attachments/assets/c01197b7-91c6-4b6d-a6ad-1fc5fe2ef4d1)

**Comment by rykahsay** [comment]
"... after the second or third selection  ..." 
>> when you report an issue, can you please give the exact (very specific) scenario that produces an error. For example, in this case, you could have given me the exact value of the drop down value that results in an error as a screenshot shown below:

<img width="811" alt="image" src="https://github.com/user-attachments/assets/38a432e9-697d-4e34-86d9-cb2f81a393d8">

**Comment by katewarner** [comment]
I didn't include the exact value in the drop down that produces the error because it didn't seem to matter which value you selected. The dataset disappeared after selecting the second or third value and it didn't seem to matter which values you selected before it disappeared, because I tried lots of different combinations and they always disappeared after the second or third selection.

**Comment by rykahsay** [comment]
It seems to be working for me:

<img width="1015" alt="image" src="https://github.com/user-attachments/assets/e7e82aa1-c407-4009-9abf-0a8c1c42f3cd">

**Comment by katewarner** [comment]
@rykahsay Apologies, after double-checking it does seem to be certain versions that are missing records. I started trying to list all the versions that were missing but it was taking a very long time and I can't see what the issue is as the files and BCOs seem to be within the releases folders. For example the following versions for the *_protein_ntdata are missing their records, there may be older versions that are missing records: 

human - 1.8.25, 1.10.6, 2.1.1, 2.2.1, 2.3.1 (missing records)
mouse - 1.8.24, 1.10.6, 2.1.1, 2.2.1, 2.3.1 (missing records)
rat - 1.8.24, 1.9.9, 1.11.2, 2.1.1, 2.2.1, 2.3.1 (missing records)
hcv1a - 1.8.24, 1.9.9, 1.11.2, 2.1.1, 2.2.1, 2.3.1 (missing records)
hcv1b - 1.8.24, 1.9.9, 1.11.2, 2.1.1, 2.2.1, 2.3.1 (missing records)
SARS-CoV1 - 1.8.24, 1.9.9, 1.11.2, 2.1.1, 2.2.1, 2.3.1 (missing records)
SARS-CoV2 - 1.8.24, 1.9.9, 1.11.2, 2.1.1, 2.2.1, 2.3.1 (missing records)
yeast - 2.2.1, 2.3.1 (missing records)

And for these species, you can remove these versions from the drop-down options because these species were not in these releases:
pig - 2.2.1, 2.3.1 (remove, these releases do not contain this species)
Chicken - 2.6.1 and 2.5.1 (remove, these releases do not contain this species)

**Comment by rykahsay** [comment]
I am not sure I understand the issue, what does "human - 1.8.25, 1.10.6, 2.1.1, 2.2.1, 2.3.1 (missing records)" mean? What about "pig - 2.2.1, 2.3.1 (remove, these releases do not contain this species)"?

**Comment by katewarner** [comment]
Apologies, the numbers are the releases/versions available in the drop down e.g. 

![image](https://github.com/user-attachments/assets/5522208e-6114-43a6-8251-450c90b630ba)

The issue is that when you select the following releases from the drop down, the resulting page has no dataset record and/or is empty:  

![image](https://github.com/user-attachments/assets/97d011d4-f9de-4f1f-bf8c-f7753c63f2ca)

|protein_ntdata.nt| version numbers with no records
|--|--|
|human| 1.8.25, 1.10.6, 2.1.1, 2.2.1, 2.3.1
|mouse| 1.8.24, 1.10.6, 2.1.1, 2.2.1, 2.3.1
|rat| 1.8.24, 1.9.9, 1.11.2, 2.1.1, 2.2.1, 2.3.1
|hcv1a| 1.8.24, 1.9.9, 1.11.2, 2.1.1, 2.2.1, 2.3.1
|hcv1b| 1.8.24, 1.9.9, 1.11.2, 2.1.1, 2.2.1, 2.3.1
|SARS-CoV1| 1.8.24, 1.9.9, 1.11.2, 2.1.1, 2.2.1, 2.3.1
|SARS-CoV2| 1.8.24, 1.9.9, 1.11.2, 2.1.1, 2.2.1, 2.3.1
|yeast|  2.2.1, 2.3.1

For pig and chicken, the version numbers in the drop down go back further than these species has been in GlyGen, so these versions can be removed from the drop down as they do not have datasets for these releases. 

|protein_ntdata.nt| version numbers that can be removed from dropdown
|--|--|
|pig| 2.2.1, 2.3.1
|Chicken| 2.6.1, 2.5.1
