### ISSUE TITLE
Version history list longer than species have been in GlyGen

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1614]
I noticed that for all the datasets of newer species the version history lists older releases which did not contain that species e.g. the earliest release with Chicken was 2.5.1 and Pig was 2.4 but the version history goes back to the 1st release. And if you try to select the earlier releases you get a no record found error.   

![image](https://github.com/user-attachments/assets/ee81371c-fcce-48f2-aa64-5befb50d527c)

![image](https://github.com/user-attachments/assets/7b19b165-0338-4342-bf12-faf1e405c8b9)

**Comment by rykahsay** [comment]
It looks like this is fixed now:

<img width="951" alt="image" src="https://github.com/user-attachments/assets/ba537619-542f-445a-9824-5597f6de891c">

**Comment by katewarner** [comment]
The chicken files are fixed but I noticed that the pig, arabidopsis and slime mold datasets version histories are still incorrect so I've put what releases should be included in their version histories in the table below: 

| Datasets  | Releases |
| ---------- | ------------- |
| arabidopsis | 2.6.1 |
| pig | 2.6.1, 2.5.1 and 2.4.1 |
| dicty | 2.6.1, 2.5.1, 2.4.1 and 2.3.1 |

**Comment by rykahsay** [comment]
check now

**Comment by katewarner** [comment]
Fixed thanks

**Comment by katewarner** [comment]
Fixed thanks
