### ISSUE TITLE
Link out to PMID not working for protein detail page P14210-1

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#1618]
Link out under function tab for PMID: 38364458 returns and empty page. https://glygen.org/publication/PubMed/38364458

![image](https://github.com/user-attachments/assets/5b52c573-451f-4c40-a656-a9c9284035fc)

**Comment by rykahsay** [comment]
The page exists on tst, so the issue will go away when we go to prd

<img width="1065" alt="image" src="https://github.com/user-attachments/assets/0a6f7d6e-9dd5-44a9-9268-d3ebf8ac968a">

**Comment by rykahsay** [comment]
I am closing the ticket
