### ISSUE TITLE
PRO links go to empty pages for protein detail page P14210-1

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#1619]
PRO links lead to dead pages. Ex: https://proconsortium.org/app/entry/PR:000055404/ 

This occurs for all PRO links in Proteoform Annotation section.

![image](https://github.com/user-attachments/assets/563a816a-99ab-4db9-8c14-a82e1cfc87e2)

**Comment by rykahsay** [comment]
Please edit the misc/xref_info.csv file to point to a replacement site or disable this link. At this point, I expect you know how to disable an xref link

**Comment by ubhuiyan** [comment]
These links are working for me just fine. I will close this ticket.
