### ISSUE TITLE
Links on SPARQL page not working.

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#1621]
Privacy Policy leads to empty page: https://sparql.tst.glygen.org/privacy_policy.html

Link in Overview Diagram section never loads
![image](https://github.com/user-attachments/assets/d47ce716-e90c-410f-905f-f2e3ab4b8f20)
this is the link: https://sparql.tst.glygen.org/webvowl/#glygen

**Comment by sujeetvkulkarni** [comment]
@rykahsay can you please look into this.

**Comment by rykahsay** [comment]
Check now

**Comment by sujeetvkulkarni** [comment]
@Luke-Johnson-5 @rykahsay has made changes to point to 
https://sparql.tst.glygen.org/webvowl/#glygen
but looks like the page is not working.

![Screenshot 2024-08-22 at 1 44 16 PM](https://github.com/user-attachments/assets/ac589da7-25df-4eb5-99c9-8582ef1edfc0)

**Comment by rykahsay** [comment]
Works now:

<img width="834" alt="image" src="https://github.com/user-attachments/assets/47a9a27b-44e4-457b-aec6-345888e52a20">
