### ISSUE TITLE
Glitch in Filter on Results Page 

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1622]
I have noticed after searching for "G17689DH" in the Global Search field and then selecting "Glycoprotein", that the numbers within the  "By Biomarker Type" filter for "Diagnostic", "Monitoring", and "Prognostic" count change when they are selected.
![Screenshot 2024-08-13 at 2 37 03 PM](https://github.com/user-attachments/assets/c10ca4e3-23ac-4039-96a3-97d471386d53)

You will notice there are 2 and 1 records for "Diagnostic" and "Monitoring" prior to selecting either filter. 

![Screenshot 2024-08-13 at 2 37 20 PM](https://github.com/user-attachments/assets/daf5e7fe-9d6c-4525-a1a9-0a5daae532d9)

Now notice once "Diagnostic" is selected, there are no available entries. This similar issue occurs when selecting "Monitoring," but this issue does not occur when selecting "Prognostic". 

I don't work with the biomarker data directly, so I am unsure if this is a true glitch or issue. I wanted to bring this to your attention regardless.

**Comment by rykahsay** [comment]
Good catch! Please check now

**Comment by ubhuiyan** [comment]
Seems to be working fine now.

**Comment by CyrusAY** [comment]
Hi Robel, it seems that the filter problem is not totally fixed.

1. 
Filtering by Glycan Type -> N-glycan : initially showing 90 results
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/b0f94043-2205-4fa9-87c5-59061a7a6fae">

After checking the box, no matched results are shown:
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/cc91f5df-d341-4d00-8c21-94992f1f361c">

2. 
The same goes for filtering by sequence details.
Before checking the box 'composition', it shows that there are 8 matched results. After checking the box, a list of 9 results are shown.
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/be4a7d61-62e2-4c3d-a9af-217b73fcb0f3">

**Comment by rykahsay** [comment]
Tried to address those, please check:

<img width="894" alt="image" src="https://github.com/user-attachments/assets/bfae6731-674a-4396-b52b-31480914d4d8">

<img width="828" alt="image" src="https://github.com/user-attachments/assets/93bc532d-58e1-48f9-92fc-526591a75df5">

**Comment by CyrusAY** [comment]
Resolved
