### ISSUE TITLE
Super Search Display Issue for tst.glygen.org 

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1623]
The Super Search does not seem to display the results for each node (Glycan, Protein, Site, etc;) when searching by organism name for some organisms, but will populate results when searching by TaxID. All others appear to display the same result counts for each node when searching with name or TaxID. 

Organisms that have this discrepancy: 

- Arabidopsis 
- Cellular Slime Mold 
- Yeast 
- HCV-H77
- HCV-Japanese 
- HCoV-SARS 
- SARS-CoV-2

**Comment by rykahsay** [comment]
Try now

**Comment by ubhuiyan** [comment]
Works fine now.
