### ISSUE TITLE
In case of invalid input error status code should be 200 and result_count 0.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1625]
1. In case user provides invalid input like invalid sequence status code should be 200 and not 500. Also, result_count should 0 to know there are no results. 
2. In success cases result_count should have greater than 0 value (actual result count).

Error case :

<img width="1547" alt="Screenshot 2024-08-13 at 7 03 00 PM" src="https://github.com/user-attachments/assets/37e2c725-b7ed-49d1-b77d-9b236e4c4078">

<img width="1544" alt="Screenshot 2024-08-13 at 7 03 23 PM" src="https://github.com/user-attachments/assets/7bcc74d9-03a2-4c1a-8b21-4d86a5d55471">

Success case :

<img width="1553" alt="Screenshot 2024-08-13 at 7 04 42 PM" src="https://github.com/user-attachments/assets/5c7f8eea-e37e-4e00-9f15-e3414917a73b">

**Comment by sujeetvkulkarni** [comment]
@sujeetvkulkarni 
add bare minimum response

**Comment by rykahsay** [comment]
1)
```
$ http POST :8082/job/addnew/ < tests/examples/job/job_addnew.isoform_mapper.3.json 
HTTP/1.1 200 OK
Connection: close
Content-Length: 83
Content-Type: application/json
Date: Thu, 15 Aug 2024 05:58:21 GMT
Server: gunicorn

{
    "error_list": [
        {
            "error_code": "no-isoform-accessions-found"
        }
    ],
    "result_count": 0
}

```


2)
```
$ http POST :8082/job/status/ < tests/examples/job/job_status.json
HTTP/1.1 200 OK
Connection: close
Content-Length: 578
Content-Type: application/json
Date: Thu, 15 Aug 2024 05:49:06 GMT
Server: gunicorn

{
    "cmd_info": "/usr/local/bin/ts -i 2",
    "cmd_status": "/usr/local/bin/ts -s 2",
    "command": "python /app/job_submitters/isoform_mapper.py -i /data/shared/glygen//userdata/tst/jobs/259/input.csv",
    "end_time": "Thu Aug 15 05:35:31 2024",
    "enqueue_time": "Thu Aug 15 05:35:29 2024",
    "exit_status": "died with exit code 0",
    "output_files": [
        {
            "format": "tsv",
            "url": "https://data.tst.glygen.org/ln2data/userdata/tst/jobs/259/output.tsv"
        }
    ],
    "result_count": 2,
    "slots_required": "1",
    "start_time": "Thu Aug 15 05:35:29 2024",
    "status": "finished",
    "time_run": "2.592624s",
    "tsid": "2"
}
```

**Comment by sujeetvkulkarni** [comment]
@rykahsay this is fine. if no job id is generated then job status is not required like shown in above example 1.

**Comment by sujeetvkulkarni** [comment]
done.
