### ISSUE TITLE
File upload of isoform mapper is not working.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1627]
@rykahsay 
I tried to implement the file upload for isoform mapper but its not working. Can you please provide some more details like input values etc.
Also, tried to implement it like id mapper, files input like you have shown etc but it is not working.

<img width="1624" alt="Screenshot 2024-08-13 at 7 27 37 PM" src="https://github.com/user-attachments/assets/26216759-8c67-45e6-ac99-2cc3f559b1ba">

related to #1012
```
import json
import requests
from requests.packages.urllib3.filepost import encode_multipart_formdata

url = "http://localhost:8082/job/addnew/"
in_file = "tmp/input.csv"
files = {"userfile": open(in_file, 'rb')}
req_obj = {}
res = requests.post(url, files=files, data=req_obj)
res_obj = json.loads(res.content)
print (json.dumps(res_obj, indent=4))
```

**Comment by rykahsay** [comment]
@sujeetvkulkarni  ... this should work, please try

```
import json
import requests


in_file = "tmp/input.csv"
url = "http://localhost:8082/job/addnew/"

req_obj = {
    "parameters":{},
    "jobtype":"isoform_mapper"
}
files = {
    "data":json.dumps(req_obj),
    "userfile": open(in_file, 'rb')
}

res = requests.post(url, files=files, data=req_obj)
res_obj = json.loads(res.content)
print (json.dumps(res_obj, indent=4))


```

**Comment by sujeetvkulkarni** [comment]
@rykahsay 
I tried implementing this approach, this is a python specific solution. It works in python but with javascript this has difficulty in mimicking the request parameters. 
requests.post(url, files=files, data=req_obj) in this files is a very python specific parameter and the library internally passes
form-data in different way.

I think we should implement file upload functionality technology independent like we do in Glygen id mapper (shown below) 
![Screenshot 2024-08-16 at 12 12 28 PM](https://github.com/user-attachments/assets/5cc17330-451d-4bb1-936c-1ad21d804f5c)

For isoform mapper file upload parameters can be in below format
![Screenshot 2024-08-16 at 12 17 44 PM](https://github.com/user-attachments/assets/fa046ac1-af89-4eee-b468-92eda62c2a47)

file data will be binary and Content-Type like below,
"Content-Type": "multipart/form-data",

**Comment by rykahsay** [comment]
Ok, I have tried to make it close to idmapper and given below is how you post it using python. I think this should work on your JS code if you follow exactly what you are doing for idmapper. The only issue is that, the keys in the "req_obj" can have only simple values and req_obj cannot be like {"jobtype":"isoform_mapper", "parameters":{}} -- for this reason, I am adding I am adding the "parameters":{} part after getting your request


```
import json
import requests


in_file = "tmp/input.csv"
url = "http://localhost:8082/job/addnew/"

req_obj = {
    "jobtype":"isoform_mapper"
}
files = {
    "userfile": open(in_file, 'rb')
}
res = requests.post(url, files=files, data=req_obj)
res_obj = json.loads(res.content)
print (json.dumps(res_obj, indent=4))
```

**Comment by rykahsay** [comment]
Please see below the code lines in the API for your own understanding on how this is being handled now:

<img width="983" alt="image" src="https://github.com/user-attachments/assets/be72cb45-abc4-4eed-90a0-56fe6ba34634">

**Comment by sujeetvkulkarni** [comment]
@rykahsay this works.

This has only one problem - in file input currently it looks like comma is mandatory even if amino_acid value is not given. 

Below file input works,
```
isoform_ac,amino_acid_pos,amino_acid
A6NJB7-2,3,T
A6NJB7-2,8,S
P08697-2,36,
```
But below file input throws error,
```
isoform_ac,amino_acid_pos,amino_acid
A6NJB7-2,3,T
A6NJB7-2,8,S
P08697-2,36
```
Only difference is comma is missing in third row where amino acid value is not provided.
![Screenshot 2024-08-16 at 3 39 11 PM](https://github.com/user-attachments/assets/99dabd58-699b-4301-b7f1-28c87ed51be9)

This should work in both cases with or without comma.
Also, addnew should not return 500, should return 200 Status Code.

**Comment by rykahsay** [comment]
I have changed the 500 to 200 but the file shown below is a structurally malformed CSV file and the error response is appropriate:

```
isoform_ac,amino_acid_pos,amino_acid
A6NJB7-2,3,T
A6NJB7-2,8,S
P08697-2,36
```

```
$ python3 test_file_upload.py 
200
{
    "error_list": [
        {
            "error_code": "bad-row",
            "row_index": 3
        }
    ],
    "result_count": 0
}
```

**Comment by sujeetvkulkarni** [comment]
done.
