### ISSUE TITLE
Organism name 'Chinese hamster' not showing in glycan details page

### ISSUE THREAD

**Issue by CyrusAY** [glygener/glygen-issues#1629]
See first column of Organism field.
Organism name supposed to be shown before expanding the table in the glycan details page - G17689DH

<img width="1676" alt="image" src="https://github.com/user-attachments/assets/2ccc2f1e-838c-464e-8614-d9a838d8b70f">

**Comment by rykahsay** [comment]
@ubhuiyan  ... based on the rules ("generated/misc/species_rules.txt"), is this acceptable? If not, please decide what needst to be done and update the rules if it has to be updated

**Comment by ubhuiyan** [comment]
Based on the rules documented, we are not displaying species that are not in the current repertoire of GlyGen species. I will close this ticket.
