### ISSUE TITLE
API is throwing exception for below protein id 

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#163]
https://api.tst.glygen.org/protein/detail/E9PWH1

**Comment by rykahsay** [comment]
Fixed!

**Comment by sujeetvkulkarni** [comment]
@rykahsay 
{"error_list": [{"error_code": "non-existent-record"}], "reason": {"description": "Valid current UniProtKB accession never been in GlyGen", "type": "never_in_glygen_current_in_uniprotkb"}}

Is this is a new type ("never_in_glygen_current_in_uniprotkb")? Is this similar to or replacement of "never_in_glygen".
And can you give me a similar example in Glycans.
Also it would be better if we use similar types in proteins or glycans and not use anything like uniprotkb or glytucan in type.

https://api.tst.glygen.org/glycan/detail/G00001LE returns "never_in_glygen".

**Comment by rykahsay** [comment]
I have moved your last comment to ticket 71 (accession history issues). please close this ticket
