### ISSUE TITLE
(Protein) Quick search error

### ISSUE THREAD

**Issue by CyrusAY** [glygener/glygen-issues#1631]
1. What are the orthologs of protein X in different organisms
No results found using protein example (HGF)

<img width="711" alt="image" src="https://github.com/user-attachments/assets/c7ac2d4c-92a4-4376-a9d6-e2d8b8f891dc">

2. What are the functions of protein X
Example protein leads to function page that does not load even after 5 minutes

<img width="1552" alt="image" src="https://github.com/user-attachments/assets/6bd1da31-588f-472c-96da-686e392bf757">

**Comment by ubhuiyan** [comment]
![Screenshot 2024-08-23 at 4 12 11 PM](https://github.com/user-attachments/assets/a751af3a-9787-49bc-8b3f-3a8999976f83)

Seems to be working fine for me. Will close ticket.
