### ISSUE TITLE
(Organism) quick search - cannot access predicted glycosylated proteins

### ISSUE THREAD

**Issue by CyrusAY** [glygener/glygen-issues#1633]
Drop down menu does not contain the 'predicted' option:
<img width="671" alt="image" src="https://github.com/user-attachments/assets/a16a4db9-4d32-4e5c-b0dd-d8e4a3bf334c">

**Comment by rykahsay** [comment]
Check now:

<img width="1298" alt="image" src="https://github.com/user-attachments/assets/cdd92702-2db3-46b9-85f5-1e4b08cc0bea">

**Comment by CyrusAY** [comment]
Resolved.
