### ISSUE TITLE
We are GlyGen and How to Cite changes

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#1635]
Hi Sujeet 
Here are the changes to We are GlyGen and How to Cite

**Move to Past members**
Karina (July 2024), Jingyue (May), Michelle (?), Dorteja (?), Preethi (August), Luke (August, currently not there on the page)

**Paper to be added**

Functional implications of glycans and their curation: insights from the workshop held at the 16th Annual International Biocuration Conference in Padua, Italy
DOI - https://doi.org/10.1093/database/baae073
PMID - 39137905
PubMed - https://pubmed.ncbi.nlm.nih.gov/39137905/

Attached citation files are in email.

**Comment by sujeetvkulkarni** [comment]
Doroteja Dragovic left my lab in August 2023.
Michelle Vesser left my lab in July 2023.

Abdullah Abdul
Bioinformatics Programmer
Georgetown University,
Washington DC
mid-Sept 2024

**Comment by sujeetvkulkarni** [comment]
I have made above changes and added new members who have shared details. Please check.
https://tst.glygen.org/about/
https://tst.glygen.org/how-to-cite/

**Comment by jeet-vora** [comment]
@sujeetvkulkarni 

How to cite looks good.

In the about page - Urnisha and Cyrus are missing. You should have gotten their emails with info.

**Comment by sujeetvkulkarni** [comment]
@jeet-vora No, I dont have Urnisha and Cyrus's information. Please ask them to send it.

**Comment by sujeetvkulkarni** [comment]
@jeet-vora  Added Urnisha and Cyrus's information. Please check. 
https://tst.glygen.org/about/

**Comment by jeet-vora** [comment]
Checked. No issues Closing the ticket.
