### ISSUE TITLE
Question about Publications 

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1637]
I found an instance where we provided the DOI for a publication, but there appears to be a PMID available now (PMID: 33167210). In these instances, do we update the resource or leave it as is? I found this on the detail page for G56749GV. 

![Screenshot 2024-08-15 at 4 45 17 PM](https://github.com/user-attachments/assets/1a05a26e-5c52-49a0-8907-43e1fb290ec3)

**Comment by rykahsay** [comment]
Association of "10.1016/j.talanta.2020.121495" and "G56749GV" is for sure coming from some downloaded/source file and here is a framework (series of questions) I want you to answer to find out which download file is giving that information.

1. which citations dataset is connecting "10.1016/j.talanta.2020.121495" and "G56749GV"  ($species_$molecule_citations_$dataset.csv)?
2. which dataset ($species_$molecule_$dataset.csv) was used to make citations dataset ($species_$molecule_citations_$dataset.csv)?
3. what is the download/source file used to make $species_$molecule_$dataset.csv?
4. how do we change the download/source file?

**Comment by ubhuiyan** [comment]
Okay, here is my thought process:
1. The citation dataset appears to be: `human_proteoform_citations_glycosylation_sites_unicarbkb.csv`
2. This means the dataset is: `human_proteoform_glycosylation_sites_unicarbkb.csv`
3. The source file for this dataset appears to be: `known_33167210_glygen.csv`

When you look into the source file, the PMID is already listed (unsurprisingly given the file itself is named after this PMID):
```
[sbhuiyan28@glygen-vm-dev current]$ awk -F, '{print $6, $10, $(NF-10)}' known_33167210_glygen.csv | grep "G56749GV"
toucan, Pmid, doi 
G56749GV 33167210 10.1016/j.talanta.2020.121495
G56749GV 33167210 10.1016/j.talanta.2020.121495
G56749GV 33167210 10.1016/j.talanta.2020.121495
G56749GV 33167210 10.1016/j.talanta.2020.121495
```

So I am a bit unsure why we are displaying the DOI on the front end instead of the PMID in this case.

**Comment by rykahsay** [comment]
Great! Now, I will look into it

**Comment by rykahsay** [comment]
I see both of them, I don't see what the harm is ... let's ignore this problem for now.


<img width="664" alt="image" src="https://github.com/user-attachments/assets/7b2a33e0-ad53-4bea-ac57-ad3e38a9cb74">

**Comment by ubhuiyan** [comment]
I meant more so in the publications section. It displays the DOI but all other resources appear to have PMID displayed if it is available. Regardless, the paper is cited anyway so I suppose it is fine how it is.
