### ISSUE TITLE
Publication details protein synonym name issue

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#1638]
<img width="715" alt="image" src="https://github.com/user-attachments/assets/12b07cc6-4072-4ab7-88d4-da200295b4f4">
<img width="1396" alt="image" src="https://github.com/user-attachments/assets/202d27df-98f9-40cf-844d-79bec6fd67b0">

The Publication details API is not working and I am doing something incorrect. Hence reporting the issue through portal screen shots

**`https://tst.glygen.org/publication/DOI/10.1101/2023.09.13.557529`**

<img width="963" alt="image" src="https://github.com/user-attachments/assets/b1dad1b3-7656-4c99-8adf-ca1f1397e5a7">

The protein name for the A0A077KA19 has no rec. name but has two synonyms. THese two synonyms are being displayed on the publication details page. Can you display only one synonym name in the cases where there are only synonym names available. So in the this case the name that will be displayed will be **CD200 molecule like 2**

**CD200 molecule like 2; ISEC2 protein, intestinal secretory cell protein 2**	[A0A077KA19-1](https://tst.glygen.org/protein/A0A077KA19-1)

FYI @ubhuiyan @katewarner @CyrusAY

**Comment by rykahsay** [comment]
On the name change: we can do that but do we really have to? What is the problem with showing multiple synonyms?


On the API:
Your query is OK but Swagger is complaining:

<img width="556" alt="image" src="https://github.com/user-attachments/assets/4a080a15-1184-4ba2-9de6-b1651559e597">

In such cases, you want to use the browser direct as shown below:

```
https://api.tst.glygen.org/publication/detail/?query={ "id": "10.1101/2023.09.13.557529", "type": "DOI"}
```

<img width="1008" alt="image" src="https://github.com/user-attachments/assets/ef293590-cc8d-4c22-92dc-58118f32fc52">

**Comment by jeet-vora** [comment]
@rykahsay

Noted the browser direct.

 There is nothing wrong with it, per se, just that it is a consistency issue. The protein with with rec names will have one protein name displayed and protein with synonym will have two protein names displayed. 
 
 If you want to skip the changes, please close to the issue
