### ISSUE TITLE
1000 entry limit for isoform mapper file, sequence and accession specific input.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1639]
@sujeetvkulkarni will implement 1000 entry limit for sequence and accession specific input in isoform mapper functionality.
@rykahsay will implement 1000 entry limit for file, sequence and accession specific input in isoform mapper functionality.

**Comment by rykahsay** [comment]
I have tried to implement 1000 limit on size of intable ... please try

**Comment by sujeetvkulkarni** [comment]
done.
