### ISSUE TITLE
GlyGen website security certificate expired

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1642]
I keep getting a security alert when I try to enter the GlyGen website. It looks like our security certificate may have expired as my computer clock is correct. 

![image](https://github.com/user-attachments/assets/1a75aa0d-1b1d-4318-b4bb-d373b2aa2c58)

**Comment by sujeetvkulkarni** [comment]
@rykahsay 
You may want to talk with Dacian regarding renewing glygen certificate.
