### ISSUE TITLE
Species target for GlyGen 2.7-2.9

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1646]
the GlyGen team had a meeting and decided on the next species we would like to add to GlyGen over the next few releases:
* Bovine (2.7)
* Zebrafish / Hamster (2.8)
* Rice (2.9)

The number in parentheses is the intended GlyGen release with:

* 2.7 (September - November)
* 2.8 (December - February)
* 2.9 (March - May)

Altthough we can include species earlier if that is possible. As a first step I would like to know how many reference proteomes do exist for each and what their NCBI taxonomy IDs are.

It would also be good to know if you think the species can be included in the timeframes above. If there are ways to include them earlier let me know as well.

**Comment by ReneRanzinger** [comment]
* Bovine just one. Proteome ID UP000009136 TaxID 9913 BOVIN Bos taurus (Bovine) Euk/mammal
* Zebrafish just one Proteome ID UP000000437 TaxID 7955 DANRE Danio rerio (Zebrafish) (Brachydanio rerio) Euk/Animal
* Hamster there are multiple proteomes. I think we should use  Proteome ID UP000001075 TaxID 10029 CRIGR Cricetulus griseus (Chinese hamster) (Cricetulus barabensis griseus) Euk/mammal. Would like to get input from UniProt proteome group and SP curators if they prefer another one.
* Rice there are multiple proteomes. I think we should use Proteome ID UP000059680 Tax ID 39947 ORYSJ Oryza sativa subsp japonica (Rice).  Would like to get input from UniProt proteome group and SP curators if they prefer another one.

**Comment by jieluo321** [comment]
UP000009136 taxid 9913 is the uniprot reference proteome. So I can import this proteome

**Comment by jieluo321** [comment]
UP000000437 with taxid 7955 is also uniprot reference proteome, i will try to import later on

**Comment by jieluo321** [comment]
UP000001075 with taxid 10029 is uniprot reference proteome

**Comment by jieluo321** [comment]
UP000059680 with taxid 39947 is uniprot reference proteome

**Comment by ReneRanzinger** [comment]
@rajamazumder is the decision with this final or is there still need for Hamster and Rice to discuss with UniProt proteome group and SP curators?
