### ISSUE TITLE
Isoform mapper functionality (accession based, file based and sequence based) fails with large input like 900 rows etc.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1647]
Isoform mapper functionality (accession based, file based and sequence based) fails with large input but less than 1000 (agreed higher limit). User should be able to provide input rows <= 1000 rows and functionality should work fine.

![Screenshot 2024-08-20 at 12 11 32 PM](https://github.com/user-attachments/assets/cdcd0096-17dd-4269-8090-a5887bfee37b)

**Comment by rykahsay** [comment]
Please try now

**Comment by sujeetvkulkarni** [comment]
done.
