### ISSUE TITLE
Isoform mapper card image

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#1648]
@sujeetvkulkarni @ReneRanzinger 

Here is my take on the isoform mapper card image that show site mapping from the 2 isoforms to the isoform that is canonical.
Here are the SVG, PNG for the card image - https://gwu0.sharepoint.com/:f:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Images%20Templates/Homepage%20cards/Isoform%20Mapper?csf=1&web=1&e=0ZSHGE

**Comment by sujeetvkulkarni** [comment]
@jeet-vora can you please also give 1 line summary to be displayed on card.

**Comment by jeet-vora** [comment]
@sujeetvkulkarni The GlyGen Isoform Mapper allows to find and map the amino acid and site position of a isoform protein sequence to the corresponding canonical isoform protein sequence.

Also, I believe in the help icon, we should provide the definition of the word canonical and isoform for users who are not aware of the terms.

**Comment by sujeetvkulkarni** [comment]
@jeet-vora I have deployed the card image changes on tst. Please share the tooltips details/info you want.
