### ISSUE TITLE
Xref section empty within protein pages on tst 

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1649]
I just noticed that the cross-reference section on all the protein pages (that I looked at) on tst are empty, whereas they contain data on 2.5 PRD.  

e.g. https://tst.glygen.org/protein/Q6S8J3-1#Cross-References

![image](https://github.com/user-attachments/assets/6bd88241-b653-4dae-8e8b-dcd5019ef043)

On PRD the protein does have cross-reference data: https://www.glygen.org/protein/Q6S8J3-1#Cross-References
And the 'crossref' data is on the protein api: https://api.tst.glygen.org/protein/detail/Q6S8J3

**Comment by sujeetvkulkarni** [comment]
Fixed issue on tst, but logged a different issue - #1653.

**Comment by katewarner** [comment]
Thank you, I'll take a look at the ticket. 

The cross-reference section is there but I noticed that a section is missing the xref database/dataset title e.g. UniProt, Biomuta etc..., and I'm not sure what it should be: 

https://tst.glygen.org/protein/Q6S8J3-1#Cross-References
![image](https://github.com/user-attachments/assets/1836ab26-3622-4df7-9cb9-69153b208294)

**Comment by sujeetvkulkarni** [comment]
@katewarner I can see similar classifications as there were in production.
But if you want to add a different classification/database then we will need to make changes in api response.

https://tst.glygen.org/protein/P14210-1#Cross-References

![Screenshot 2024-08-22 at 2 05 58 PM](https://github.com/user-attachments/assets/c6b11cbf-b0b1-4f75-ab78-7e39d529cbf2)

https://www.glygen.org/protein/P14210-1#Cross-References

![Screenshot 2024-08-22 at 2 05 36 PM](https://github.com/user-attachments/assets/68db2257-00bf-47ed-ba6e-9e224cb02243)

**Comment by katewarner** [comment]
@sujeetvkulkarni sorry I've just realised that you've already found this issue - that's what the other ticket https://github.com/glygener/glygen-issues/issues/1653. is about. So I'll close this issue and work on the https://github.com/glygener/glygen-issues/issues/1653.
