### ISSUE TITLE
isoform mapper api is failing in accession, file based and sequence based input.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1652]
![Screenshot 2024-08-21 at 4 59 23 PM](https://github.com/user-attachments/assets/ed12ba47-06bf-450a-81ec-d5b701572583)

![Screenshot 2024-08-21 at 4 59 09 PM](https://github.com/user-attachments/assets/d84caadc-fcce-4d4d-a60e-0ac3b4aed428)

**Comment by rykahsay** [comment]
Please try now, there was bug I introduced trying to fix the more than 900 rows (please test that as well).

<img width="828" alt="image" src="https://github.com/user-attachments/assets/a0e6de02-d2a0-4f5e-9b8d-790c017824cd">

**Comment by sujeetvkulkarni** [comment]
done.
