### ISSUE TITLE
In some cases cross ref array objects have missing information like database, url etc

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1653]
Minimum id and database information should be there in cross ref array objects.
https://api.tst.glygen.org/protein/detail/P14210-1/

![Screenshot 2024-08-22 at 1 21 00 PM](https://github.com/user-attachments/assets/d173d621-7830-4f81-99bd-3b1f1ba1abcb)

**Comment by katewarner** [comment]
@rykahsay it looks like these might be the PRIDE datasets. 

Currently on the api (https://[api.tst.glygen.org/protein/detail/P11142-1](https://api.tst.glygen.org/protein/detail/P11142-1)) it looks like: 
![image](https://github.com/user-attachments/assets/6958afcd-578f-47b8-b76e-3d7a34d264e8)
But I think it should be like this (I've left the URL blank and I'm not sure) 
```
        {
            "id": "E9PI65",
            "url": "....",
            "database": "PRIDE",
            "categories": [
                "Other"
            ]
        },
```

**Comment by rykahsay** [comment]
Fixed now, please check

**Comment by katewarner** [comment]
Looks fixed to me. @sujeetvkulkarni can this ticket be closed?

**Comment by sujeetvkulkarni** [comment]
Done, closing.
