### ISSUE TITLE
Ortholog/Homologs information is missing in protein details api.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1654]
On tst orthologs:[] array is missing.
https://api.tst.glygen.org/protein/detail/P14210-1/

![Screenshot 2024-08-22 at 1 30 02 PM](https://github.com/user-attachments/assets/85a13cb9-6c7c-4ee8-a3d3-2c0030a376d9)

On prod same protein has orthologs:[] array.
https://api.glygen.org/protein/detail/P14210-1/

![Screenshot 2024-08-22 at 1 33 20 PM](https://github.com/user-attachments/assets/3dec760e-1ad4-410f-89cf-be7c3d1fecbd)

**Comment by rykahsay** [comment]
<img width="649" alt="image" src="https://github.com/user-attachments/assets/6d99965c-136a-4311-8eb0-1f4a820c6f75">

**Comment by sujeetvkulkarni** [comment]
done.
