### ISSUE TITLE
Plan meeting to synchronize GW and GlyGen tasklist

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1658]
Raja, Jeet and Rene will meet about integrating the GW tasks into the main tasks list.

**Comment by ReneRanzinger** [comment]
I will not be available in the first two weeks of September.

**Comment by jeet-vora** [comment]
@ReneRanzinger 

I just had a call with Raja saying that we have discontinued a separate GW tasklist for GlyGen. There is only one task list which is managed by you that contains all the tasks and even the new tasks will be added there.

The only current tasklist is for CFDE. Raja agreed and recalled the information.

So I guess there is not separate meeting needed but if needed it can be quickly re-confimed in the general meeting.

**Comment by ReneRanzinger** [comment]
@jeet-vora ok, moving forward the standard workflow should be that GlyGen related task (wishes) from Raja are shared with me.

**Comment by jeet-vora** [comment]
Yes they will be shared with you.
