### ISSUE TITLE
(Quick search) Help icons and text

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#166]
Add help icons and text to the quick search input fields (for all quick searches.) If help is needed for the text create a spreadsheet for @jeet-vora and @ReneRanzinger .

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger @jeet-vora 
Add description, url text and url for quick search tool tips in below file,

https://gwu0.sharepoint.com/:f:/r/sites/GlyGenTeam-GRP/Shared%20Documents/GlyGen%20Tasks?csf=1&web=1&e=AQwhLf

File name : QuickSearchToolTip

**Comment by ReneRanzinger** [comment]
@jeet-vora please review and assign to @sujeetvkulkarni when done.
