### ISSUE TITLE
Protein pathway search returns incorrect entries

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1661]
When you carry out a Protein search (on tst or prd), select the "Any" category and search for the example pathway "hsa:3082", it returns proteins that do not have the "hsa:3082" pathway, e.g. [P31749-1](https://[api.tst.glygen.org/protein/detail/P31749-1](https://api.tst.glygen.org/protein/detail/P31749-1)) is returned which only has the pathway "hsa:207".

![image](https://github.com/user-attachments/assets/823de50f-ef28-4b26-8998-e6e035e29258)

I've wondering if the search is picking up hsa or the number 3082 in the pubmed ID, and if so, can we possibly change the "Any" category search to an exact search?

**Comment by sujeetvkulkarni** [comment]
@katewarner looks like partial user input is getting matched (in Any category) which is resulting in large number of results.
 on tst 
 Category "Any" Input : hsa:3082 results ->19022
 Category "Any" Input : hsa:207 results -> 19020

Even random input like (hsa:49999),
 Category "Any" Input : hsa:49999 results -> 18939

on prod  same input results in below output,
 Category "Any" Input : hsa:3082 results -> 3
 Category "Any" Input : hsa:207 results -> 19010
 Category "Any" Input : hsa:49999 results -> 18968

As for exact match you can change category from Any to Pathway in the dropdown.
Then on both prd and tst it results in below output,

 Category "Pathway" Input : hsa:3082 results -> 
prd output: 3
tst output: 3

 Category "Pathway" Input : hsa:207 results ->
prd output: 10
tst output: 10

 Category "Pathway" Input : hsa:49999 results ->
prd output: No results
tst output: No results

I believe you can raise "Any" category issue with @rykahsay as I dont know the current implementation to match partial user input string is desirable as it will always match "hsa" string whatever the number maybe (like hsa:49999).

 Category "Any" Input : hsa results ->
prd output: 18968
tst output: 18939

 Category "Pathway" Input : hsa results ->
prd output: 18951
tst output: 18922

Any category matches user input string in multiple categories like Disease, Glycan, Protein etc including Pathway.
After selecting specific category like Pathway from drop down, it forces to match user input to only Pathway category.

**Comment by katewarner** [comment]
Okay thanks

**Comment by katewarner** [comment]
@sujeetvkulkarni I also tried searching (on prd and tst):

Category "Disease" Input : hsa:3082 results -> 3, two of which are incorrect because they have a partial match to hsa:3082. Personally, I think when you select the drop-down for anything other than "Any", then the search result should be exact and not return partial matches. I will bring this up at the next meeting and see what everyone thinks.
