### ISSUE TITLE
Problem with mouse on tst protein advanced search

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1662]
On the tst protein advanced search, when you select mouse in the "Organism" drop down it returns both mouse and arabidopsis proteins. This doesn't happen when you select any of the other species. 

i.e. https://tst.glygen.org/protein-list/664ae0e53c8f03ca264c8817573bc95d 

![image](https://github.com/user-attachments/assets/e86f974e-b2cb-46fc-853d-7db71acc0514)

**Comment by rykahsay** [comment]
Please check now

**Comment by katewarner** [comment]
Fixed thank you
