### ISSUE TITLE
Isoform mapper placing and image

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1663]
The Isoform mapper is part of 2.6.

Since its a new tool we placed him in the top row on the front page. We used the image Jeet create for us. 

Tst server : https://tst.glygen.org/

If you have suggestions or alternative Ideas let us know.

**Comment by ReneRanzinger** [comment]
follow up for #1648

**Comment by sujeetvkulkarni** [comment]
Done all suggested changes.

**Comment by ubhuiyan** [comment]
Shall we close this ticket or move to 2.7?
