### ISSUE TITLE
uniprotkb_canonical_ac2ensembl.csv

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#1668]
Robel can you share a script which can generate the mapping between uniprotkb_canonical_ac and ensembl_gene_id as a csv file for all organisms in GlyGen, including the ones that will be added in the future. Example file below.

I have to use it frequently for CFDE data package.

**Input files** - *_protein_genelocus.csv
**Output file** - **`uniprotkb_canonical_ac2ensembl.csv`**

`uniprotkb_canonical_ac,ensembl_gene_id`
Q658T7-1,ENSG00000205879
P30613-1,ENSG00000143627
Q5MIZ7-1,ENSG00000275052
A0A1W2PQ27-1,ENSG00000284438

**Comment by rykahsay** [comment]
Done for now, please have Urnisha do some scripting next time.

```
$ cd /software/glygen/
$ python3 dump-uniprot2ensemble.py  -r 2.6.1 > logs/junk.csv 
```

Output
```
$ head logs/junk.csv 
species_short_name,uniprotkb_canonical_ac,ensembl_gene_id
rat,D3ZB44-1,ENSRNOG00000027436
rat,D3ZB49-1,ENSRNOG00000009358
rat,D3ZB48-1,ENSRNOG00000026226
rat,A0A0G2JVG6-1,ENSRNOG00000053366
rat,P30938-1,ENSRNOG00000018834
rat,A0A8I6A2G6-1,ENSRNOG00000066828
rat,A0A096MJY4-1,ENSRNOG00000033134
rat,A0A096MJY7-1,ENSRNOG00000021133
rat,A0A096MJY1-1,ENSRNOG00000046660
```

**Comment by jeet-vora** [comment]
Done
