### ISSUE TITLE
GlyGen 2.0 on beta server

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#167]
@rajamazumder  ... 

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/20584876/227077078-7923ade2-02c8-459c-9867-97afa5d57033.png">

**Comment by sujeetvkulkarni** [comment]
@rykahsay @ReneRanzinger @jeet-vora @kmartinez834 
For me looks like beta and production both glygen websites work only when I am connected to GW vpn otherwise I can't access them. Is this specific to me or others are facing the same issue?

**Comment by ReneRanzinger** [comment]
beta and production work fine for me (also from home but without VPN). Shift+Reload?

**Comment by sujeetvkulkarni** [comment]
Still not working for me, even with shift+reload. Looks like server is rejecting request from my ip.

**Comment by kmartinez834** [comment]
Both are working for me off VPN
