### ISSUE TITLE
Quick check on o_glycan_aa_mismatch in QC pipeline

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1673]
Based on #1641. There are multiple datasets and resources having a _o_glycan_aa_mismatch_. Most noteably:
```
47558,o_glycan_aa_mismatch,human_proteoform_glycosylation_sites_pdc_ccrcc
```
Similar to #1671: Lets try to find out what happened. If the problem is that the glycan annotation was done on an isoform and it failed since Robel assumes the canonical it means we need to get the isoform2canonical mapper into the pipeline. If there is another case and the error is on their side we should try to contact the dataset owners and either get feedback from them or ask them to fix the issue. 

If the authors can or do not want to resolve the issue we need to discuss in a group meeting if we want to treat them as fuzzy annotation (glycan somewhere on the protein, no position or range).

**Comment by katewarner** [comment]
I think this can be closed
