### ISSUE TITLE
Implementation of evidence badge descision for user submitted data

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1674]
Please check if the changes discussed with Karina regarding the [labeling of evidence badges ](https://gwu0.sharepoint.com/:p:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Mockups/Presentation.pptx?d=w0b67b7a6f0ed4eb9bcf1a307e370f395&csf=1&web=1&e=FadCNk) for user submitted data have been implemented as part of 2.6. 

If this is still pending please create 2.7 tickets for it.

**Comment by katewarner** [comment]
It wasn't implemented for 2.6 so I'm going to move this ticket to 2.7 as a reminder

**Comment by katewarner** [comment]
@ReneRanzinger the badges have been added is in 2.7, and this is what the badges look like: 
https://tst.glygen.org/glycan/G39018CC
![image](https://github.com/user-attachments/assets/507f498b-4cf1-4545-b877-5f544663fcc4)

And the datasets with these badges can be found here:
#1758
