### ISSUE TITLE
Issues with regards to TCGA and COSMIC data

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1676]
**Summary**
Some time ago we made the decision that we should retrieve all mutation data via UniProt instead of UniProt and BioMuta in parallel. That was also partially due to licensing issues on TCGA and/or COSMIC.
 
**Problems we face**
1. Jie investigated this and found out that the data from COSMIC, that he has access to, has no disease relationship in it.
2. A similar issue may apply to the TCGA data but Jie and Robel looking into workaround to get to this information (ongoing email discussion)
3. Especially due to 1. and 2.replicating the old BioMuta dataset is currently not possible (columns)
4. There is also the question regarding what data to include (rows)
5. It seems that there is also some hassle regarding payment (license costs) for these datasets

 
For 2.7 (UniProt2GlyGen data update happens in beginning of September) we will be using the old BioMuta data till we can sort the issues out. If we cannot easily resolve this via this email thread we should setup a meeting with all parties involved.

**Comment by jeet-vora** [comment]
Maria is working on cbioportal for Biomuta data, CiVIC and COSMIC
