### ISSUE TITLE
 TCGA data and disease

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1677]
### From Robel
Hi Jie,

The file name (before the first ".") is the patient identifier -- you just need to download another file that matches that patient id to sample_id and then to cancer type. In the link you gave, I also saw a sample identifier which can be mapped to cancer type with the help of other files you can download separately.

Best,
Robel

**Comment by ReneRanzinger** [comment]
### From Robel
I am sure they are providing files corresponding to what I am showing below that is available to the public through the web.


The file name (before the first ".") is what they call UUID and here is how I can see the TCGA projects (for example, TCRA-BRCA means breast cancer).

"TCGA" is selected from the "Program" filters, then when you click on the "TCGA-BRCA" value of the "Project" column, you will see the UUID for BRCA cancer types.


<img width="1420" alt="image(1)" src="https://github.com/user-attachments/assets/8786c4d2-04c7-493e-be0c-c8760190fc5f">


<img width="688" alt="image(2)" src="https://github.com/user-attachments/assets/1a7360c0-837c-4657-b55e-f6391c6238ae">

**Comment by rykahsay** [comment]
@ReneRanzinger  ... this is now being done by our team

**Comment by rykahsay** [comment]
This is done now at GW -- tracked on ticket #1725
