### ISSUE TITLE
High volume record identifiers that need to be included in the test table

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1678]
On the glygen dev serve, please have a look at the list of protein, glycan and publication JSON files under the following directories and use them as example IDs that have high volume that must be checked during testing.

-  /data/projects/glygen/generated/datasets/jsondb/jumbodb/proteindb/
- /data/projects/glygen/generated/datasets/jsondb/jumbodb/glycandb/
- /data/projects/glygen/generated/datasets/jsondb/jumbodb/publicationdb/

For example, as given below, 37074911 is a high volume publication record that must be used to test publication detail page. In your beta testing, looks like you were not able to find out https://beta.glygen.org/publication/PubMed/37074911
is not working,

```
$ ls /data/projects/glygen/generated/datasets/jsondb/jumbodb/publicationdb/ | grep  37074911
pubmed.37074911.json
```

```
$ ls /data/projects/glygen/generated/datasets/jsondb/jumbodb/publicationdb/
P04637-1.json
```

**Comment by katewarner** [comment]
I've added the high record publication check to the Beta test table, so we don't forgot it for the next round of testing. High-record glycan and protein entries are already in the testing table.
