### ISSUE TITLE
Protein advanced search missing Glycosylation types 

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1679]
On beta, there are missing and additional glycosylation types in the "Select Glycosylation Type" drop-down. They should be C-, N-, O-, P- and S-linked sites as seen on prd.

**On beta:** https://beta.glygen.org/protein-search/27e0221741cd4d9cf7799cbcb39b80cb
![image](https://github.com/user-attachments/assets/654bf85e-d493-4878-acc6-ff30e32cca49)

**On prd:** https://www.glygen.org/protein-search/
![image](https://github.com/user-attachments/assets/b0a582f9-3dda-49c2-8078-d4e95c0612b9)

**Comment by sujeetvkulkarni** [comment]
@rykahsay 
In beta glycosylation_types should be similar to prod.
"N-linked;o-linked" is getting shown instead of "P-linked" in beta.

On beta:
https://beta-api.glygen.org/protein/search_init
```
 "glycosylation_types": {
        "N-linked": [
            "Complex",
            "High mannose",
            "Hybrid"
        ],
        "O-linked": [
            "O-GlcNAcylation",
            "O-GalNAcylation",
            "O-Fucosylation",
            "Other",
            "O-Galactosylation",
            "O-Glucosylation",
            "O-Mannosylation"
        ],
        "S-linked": [],
        "N-linked;o-linked": [],
        "C-linked": [
            "C-Mannosylation"
        ]
    },
```

On prod:
https://beta-api.glygen.org/protein/search_init

```
"glycosylation_types": {
        "N-linked": [
            "Complex",
            "High mannose",
            "Hybrid"
        ],
        "O-linked": [
            "O-GlcNAcylation",
            "O-Glucosylation",
            "O-GalNAcylation",
            "O-Galactosylation",
            "O-Fucosylation",
            "Other",
            "O-Mannosylation"
        ],
        "C-linked": [
            "C-Mannosylation"
        ],
        "S-linked": [],
        "P-linked": []
    },
```

**Comment by rykahsay** [comment]
"N-linked;o-linked" will be removed soon. As for "P-linked", looks like we don't have any dataset that contains "P-linked". There was one in 2.5.1 for dicty but it is now being excluded because it fails QC check:

```
$ cat logs/dicty_proteoform_glycosylation_sites_glyconnect.global.log |grep P14328 
"P14328-1","","","G98043YN","P-linked","protein_xref_pubmed","10766852","protein_xref_glyconnect","578","578","44689","Dictyostelium discoideum","1283","G98043YN","P-Man","P-Linked","0,1,1,0,0,0,0,0,0,0,0,0,0,0","N1F1","HexNAc(1)dHex(1)","367.1479","367.3533","HexNAc:1 dHex:1","","","","","","","","","","","","","","","","glycan_without_glytype"
```

**Comment by rykahsay** [comment]
Done, please check:
<img width="534" alt="image" src="https://github.com/user-attachments/assets/36cbf78e-7ba7-4efd-9857-ddfbadc323a6">

**Comment by sujeetvkulkarni** [comment]
@katewarner Looks good to me, close if looks ok.

**Comment by katewarner** [comment]
Perfect. Thank you both
