### ISSUE TITLE
Help text on advanced searches

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#168]
Add some text above the two upper buttons on the advanced search pages (glycan, protein) and the site search page:

"Please enter search criteria for one OR multiple of the following fields. You can also perform a search without filling any field, which will result in a list of all [SEARCH-RESULT] in GlyGen."

SEARCH-RESULT can be "glycans", "proteins" or "sites"

Use the same font as from the text line in supersearch. If @Mindyporterfield has suggestions for the text let us know.

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger 
Sure, I will add below lines in respective pages.

"Please enter search criteria for one OR multiple of the following fields. You can also perform a search without filling any field, which will result in a list of all glycans in GlyGen."

"Please enter search criteria for one OR multiple of the following fields. You can also perform a search without filling any field, which will result in a list of all proteins in GlyGen."

"Please enter search criteria for one OR multiple of the following fields. You can also perform a search without filling any field, which will result in a list of all sites in GlyGen."

**Comment by sujeetvkulkarni** [comment]
e8e5c3a0f3097188c7a7ab78dda6e4f37f10b1bc
