### ISSUE TITLE
Error message on beta GlyGen Mapper homepage

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1680]
When you go to the GlyGen Mapper tool on beta (https://beta.glygen.org/mapper/  ) an error message appears and the dropdowns "Select Molecule", "From ID Type" and "To ID Type" are empty:

![image](https://github.com/user-attachments/assets/97ff71e8-a297-4752-abdd-272ad629cd86)

Whereas on prd it has selections available: https://www.glygen.org/mapper/  

![image](https://github.com/user-attachments/assets/8fa78d61-cdf6-4ba9-8620-d86f428c1cf6)

**Comment by rykahsay** [comment]
Please check now, I was loading data (that's probably the reason):

<img width="1030" alt="image" src="https://github.com/user-attachments/assets/61b587bd-50e9-4520-86f6-54b4d37caf3f">

**Comment by katewarner** [comment]
Yes it's working now thank you
