### ISSUE TITLE
On beta SPAQRL example query does not work

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1681]
on https://beta-sparql.glygen.org/ when you try the example below it does not return any results. The other examples work with no issues. I don't know anything about SPARQL queries so I'm not sure why it's not working 

![image](https://github.com/user-attachments/assets/edebfb81-bfd0-444a-bcdf-246d40d31dd4)

**Comment by rykahsay** [comment]
tried to fix it, please try ... also fixing prd (please check after an 1 hr)

**Comment by katewarner** [comment]
Works great many thanks
