### ISSUE TITLE
Cannot see carbbank glycosylation sites citation files. 

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1682]
Appears to be present in `data/v-2.6.1/reviewed`

```
[sbhuiyan28@glygen-vm-dev reviewed]$ ll *_proteoform_citations_glycosylation_sites_carbbank.csv
-rw-r--r--. 1 rykahsay glygen  967 Aug 28 14:51 human_proteoform_citations_glycosylation_sites_carbbank.csv
-rw-r--r--. 1 rykahsay glygen 5472 Aug 28 14:52 mouse_proteoform_citations_glycosylation_sites_carbbank.csv
-rw-r--r--. 1 rykahsay glygen  142 Aug 28 14:52 rat_proteoform_citations_glycosylation_sites_carbbank.csv
-rw-r--r--. 1 rykahsay glygen 1837 Aug 28 14:52 yeast_proteoform_citations_glycosylation_sites_carbbank.csv
[sbhuiyan28@glygen-vm-dev reviewed]$ cat human_proteoform_citations_glycosylation_sites_carbbank.csv

```

Though I cannot seem to search for them in [beta-data.glygen.org](http://beta-data.glygen.org/) 

<img width="1214" alt="Screenshot 2024-08-29 at 3 07 49 PM" src="https://github.com/user-attachments/assets/361d6f28-32a0-4a2b-b636-1fcd2ccee02c">

I checked the BCOs and they appear to be correct, so I am unsure why the citation files aren't showing up.

**Comment by rykahsay** [comment]
You need to fix the problem and assign the ticket back to me:

```
$ python3 /software/glygen/check-bco2filename-mapping.py  | grep ERROR

NO-BCO,mouse_proteoform_citations_glycosylation_sites_carbbank.csv,ERROR,in_fs
NO-BCO,rat_proteoform_citations_glycosylation_sites_carbbank.csv,ERROR,in_fs
NO-BCO,human_proteoform_citations_glycosylation_sites_carbbank.csv,ERROR,in_fs
NO-BCO,yeast_proteoform_citations_glycosylation_sites_carbbank.csv,ERROR,in_fs
```

**Comment by ubhuiyan** [comment]
My apologies for this slipping my mind. I've created BCOs for all the carbbank citation datasets. 


|BCO ID | Dataset Name| Creator Name|
|----|----|----|
|GLY_001165|human_proteoform_citations_glycosylation_sites_carbbank.json|Urnisha|
|GLY_001166|mouse_proteoform_citations_glycosylation_sites_carbbank.json|Urnisha|
|GLY_001167|yeast_proteoform_citations_glycosylation_sites_carbbank.json|Urnisha|
|GLY_001168|rat_proteoform_citations_glycosylation_sites_carbbank.json|Urnisha|

**Comment by rykahsay** [comment]
I am tagging such cases as "missing_protocol" and including @jeet-vora so that he comes up with a way to avoid "fogetting".

TAG: missing_protocol

**Comment by rykahsay** [comment]
They are availabe, 
They are working with the exception of GLY_001168, which I want you to dig and find out why the dataset file is empty.

<img width="753" alt="image" src="https://github.com/user-attachments/assets/566bbb20-0a3c-42fb-b6d8-89f7df14578e">

<img width="753" alt="image" src="https://github.com/user-attachments/assets/452e806f-8c0b-4bc4-af6b-d72007b3f85a">

**Comment by ubhuiyan** [comment]
It appears that PMID is not a valid PMID. Upon checking `carbbank/current/carbbank.json`, I was able to locate the paper and search for the PMID by the title  `O-linked_fucose and other post-translational modifications unique to EGF modules` and the correct PMID would be 8358148. Correcting this would populate a row within the citations file. 

In this case, would we manually change the information in the source file as this may be due to human error?

**Comment by rykahsay** [comment]
Please bring this up on our Monday meeting, there is protocol that was supposed to catch this things that is not being followed --- I would be surprised if that is not in the documentation.

@jeet-vora ... we need to talk about going through the documentation

**Comment by rykahsay** [comment]
@ubhuiyan ... if this problem is still existing in 2.7, don't forget to make sure there is a ticket that tries to correct this

**Comment by ubhuiyan** [comment]
We will be discussing what to do with the carbbank PMID discrepancy in our next Wednesday meeting (12/11/24). I will close this ticket given the original issue has been resolved.
