### ISSUE TITLE
Arabidopsis protein Q5EAH9-1 doesn't load on beta

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1683]
An error message appears and the page has empty sections but it's fine on tst and it's in the jsondb folder: 
https://beta.glygen.org/protein/Q5EAH9-1

![image](https://github.com/user-attachments/assets/666db100-c86d-48d8-ae3a-1d1660270ebf)

**Comment by katewarner** [comment]
@rykahsay I've also found some human and mouse entries with the same issue, they are on tst: 

https://beta.glygen.org/protein/Q2NKX8
https://beta.glygen.org/protein/P18858

It is mainly happening when I'm testing the` pdb_protein_map.csv` file. It doesn't happen with all the entries in this mapping file that have pdb 3D structures but it happens with most of them.

**Comment by rykahsay** [comment]
fixed, please check

**Comment by katewarner** [comment]
Looks good. Thanks
