### ISSUE TITLE
Pride cross-references on beta protein pages

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1684]
I can't see the pride cross references in the cross-references section of the protein page or on the api. 

For examples, in `/data/projects/glygen/generated/datasets/unreviewed/human_protein_xref_pride.csv` it looks like this accession should have a pride xref: 

`"P55795-1","protein_xref_pride","P55795",""`

But I can't find in on the protein detail page (https://beta.glygen.org/protein/P55795-1#Cross-References) or on the api: https://[api.tst.glygen.org/protein/detail/P55795-1](https://api.tst.glygen.org/protein/detail/P55795-1)

**Comment by rykahsay** [comment]
Someone turn it off in misc/xref_info.csv. I don't know what the reason was but if you think it should be on, please uncomment and let me know

```
$ grep protein_xref_pride generated/misc/xref_info.csv
#protein_xref_pride,PRIDE,https://www.ebi.ac.uk/pride/searchSummary.do?queryTypeSelected=identification accession number&identificationAccessionNumber=%s,
```

**Comment by katewarner** [comment]
Apologies, I have no idea why it was inactivated. I've asked the rest of the team if they know why it was commented, but I'm sure it was just a mistake. I think it should be activated so I've uncommented the line, please re-integrate the dataset.

**Comment by rykahsay** [comment]
Link does not seem to work:

https://www.ebi.ac.uk/pride/searchSummary.do?queryTypeSelected=identification accession number&identificationAccessionNumber=P02511

**Comment by katewarner** [comment]
Apologies, I've updated the xref info link to `protein_xref_pride,PRIDE,https://www.ebi.ac.uk/pride/peptidome/peptidesearch?keyword=%s,`

Please check to see if I've fixed it.

**Comment by rykahsay** [comment]
Done, please check during API test

<img width="1202" alt="image" src="https://github.com/user-attachments/assets/465e12c6-5ca0-4a97-9934-9dce3a71b42a">

**Comment by katewarner** [comment]
Fixed, thank you
