### ISSUE TITLE
initial super search count is zero.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1685]
https://beta-api.glygen.org/supersearch/search_init?query={}

![Screenshot 2024-08-29 at 3 35 25 PM](https://github.com/user-attachments/assets/12a064ac-9caf-4d20-9d3e-d2a99ad51c2a)

**Comment by rykahsay** [comment]
fixed now

**Comment by sujeetvkulkarni** [comment]
Done.
