### ISSUE TITLE
Update function section evidence for HAMAP IDs

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1686]
In the function section of the protein pages, the HAMAP link (e.g. "MF_04099" in the image below) is not working 

https://www.glygen.org/protein/P0DTC2-1#Function

![image](https://github.com/user-attachments/assets/87bce5dd-5459-4a96-b641-4a4a1587b8f4)

Here's the corresponding incorrect section highlighted in the protein details page https://[api.glygen.org/protein/detail/P0DTC2](https://api.glygen.org/protein/detail/P0DTC2)
![image](https://github.com/user-attachments/assets/e0193339-8aca-435c-aca0-ce69ad115d86)

It looks like the xref in the nt file is provided as HAMAP not UniProtKB:
```
[k.warner1@glygen-vm-dev 2024_06_20]$ grep P0DTC2 uniprot-proteome-sars-cov-2.nt | grep MF_04099
<http://purl.uniprot.org/uniprot/P0DTC2> <http://www.w3.org/2000/01/rdf-schema#seeAlso> <http://purl.uniprot.org/hamap/MF_04099> .
```

I've uncommented a line in the `xref_info.csv` to use to correct the xref: 
`protein_xref_hamap,HAMAP,https://hamap.expasy.org/signature/%s,MF_03070|MF_03206|MF_03070
`

Please update your script for creating the function.evidence section of the protein page for ids with the syntax "MF_*" (HAMAP IDs), so that `"database": "UniProtKB" `is changed to  `"database": "HAMAP"`, and the base url is changed from `https://www.uniprot.org/uniprot/%s#function` to `https://hamap.expasy.org/signature/%s`. So the section above when corrected should look as follows:
```
                {
                    "database": "HAMAP",
                    "id": "MF_04099",
                    "url": "https://hamap.expasy.org/signature/MF_04099"
                },
```

**Comment by rykahsay** [comment]
It will come up as shown below after we push to tst, please check during API test:

<img width="947" alt="image" src="https://github.com/user-attachments/assets/17f69dbf-3e16-451b-9665-5180fb44c7b5">

**Comment by katewarner** [comment]
Checked on tst and it looks good
