### ISSUE TITLE
Reintegrate BCO GLY_000980 into data.glygen.org

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1687]
Please reintegrate BCO `GLY_000980` for dataset `chicken_proteoform_glycosylation_sites_glyconnect.csv` into data.glygen.org 

Jeet noticed that there were some taxon ID mistakes in the usability domain which I've now corrected.

@jeet-vora FYI

**Comment by rykahsay** [comment]
Done, please check:

<img width="999" alt="image" src="https://github.com/user-attachments/assets/646f11bc-1b0c-493b-a127-b918abfe7dcd">

**Comment by katewarner** [comment]
Perfect. Thank you
