### ISSUE TITLE
Look for an adverticement free alternative to SlideShare 

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#169]
Most of the slides in the tutorial section of the search pages and the media page are hosted on SlideShare. The advertisement around the slides and pop-ups are very annoying. Look for an alternative place or a widget how we can display pptx or PDF ourselves on these pages.

**Comment by sujeetvkulkarni** [comment]
look for react library too.

**Comment by sujeetvkulkarni** [comment]
react library - 
https://www.npmjs.com/package/react-doc-viewer

**Comment by sujeetvkulkarni** [comment]
https://www.ispringsolutions.com/blog/top-9-slideshare-alternatives

**Comment by sujeetvkulkarni** [comment]
Google slide - publish on web then use that link to display and pdf version of slides to download.
PDF version can be embedded in web page but doesn't look like ppt file.

**Comment by sujeetvkulkarni** [comment]
2 tickets 2.3 
1- rene - google docs folder for putting slides and pdf.
2 ticket - to update webpages.
