### ISSUE TITLE
Some Datasets are not opening or getting downloaded using the URL (with current)

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#1692]
Dataset issue
**example**
https://data.glygen.org/ln2data/releases/data/current/reviewed/human_proteoform_glycosylation_sites_carbbank.csv

<img width="1089" alt="image" src="https://github.com/user-attachments/assets/c41ba17c-e032-4d96-853e-1f762d1c7c48">

However this works - https://data.glygen.org/ln2data/releases/data/v-2.6.1/reviewed/human_proteoform_glycosylation_sites_carbbank.csv

This also works - 
https://data.glygen.org/ln2data/releases/data/current/reviewed/human_proteoform_glycosylation_sites_uniprotkb.csv

@ubhuiyan

**Comment by rykahsay** [comment]
check now

**Comment by jeet-vora** [comment]
Works no issues.

**Comment by ReneRanzinger** [comment]
Is this fixed for all files or just for the carbbank file? There were ~15 or so with this issue.

**Comment by jeet-vora** [comment]
All files fixed
