### ISSUE TITLE
About us page text

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#170]
----------------------------------------------------------------
![image](https://user-images.githubusercontent.com/25825266/215189719-816ac154-efec-450c-804f-49abfd9b9be6.png)

Also Raja suggested to change the below,
 as discover word doesn't fit 
![image](https://user-images.githubusercontent.com/25825266/220731899-a7003f7c-0132-465e-8054-89b8dc9fe258.png)

Text change for the below to say what we do
![image](https://user-images.githubusercontent.com/25825266/220732110-566bbd20-fff1-4396-b257-f9ee0b624c02.png)

The text will have to change as you have added above. We can discuss what to put in. Also I will provide you with a list of Affliations of GlyGen Members

**Comment by ReneRanzinger** [comment]
https://gwu0.sharepoint.com/:p:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7BD66F4735-4FB5-4DDA-AB2A-CFEE74F995F5%7D&file=2023.03.31-About%20us%20page%20text%20changes.pptx&action=edit&mobileredirect=true

**Comment by sujeetvkulkarni** [comment]
f297f16f24cc1fbfdd587908de6092c89faa2245

**Comment by sujeetvkulkarni** [comment]
2c767ee4c9e627ce3c0d27c595a48605d085ed51
