### ISSUE TITLE
Changes to Glycan category of the Protein simple search

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1701]
The glycan category of the protein simple search, only works with glycans that have an associated proteins. Glycans without an associated protein results in an error message. We think the search should also show the enzyme proteins that are involved in the glycan biosynthesis or there should be another category to show the enzymes e.g. 

![image](https://github.com/user-attachments/assets/ace5bcca-7f12-40c9-ab43-8f45909220a3)

https://www.glygen.org/protein/Q9NS00-1#Synthesized-Glycans

![image](https://github.com/user-attachments/assets/c663654d-83bc-462f-aed4-7c234479205a)

**Comment by katewarner** [comment]
@sujeetvkulkarni as discussed during the general meeting, please add a message when the glycan category is selected on the protein simple search page, that says something along the lines of: 

"Searches for proteins that have a certain glycan covalently attached."

**Comment by sujeetvkulkarni** [comment]
@sujeetvkulkarni create 2 tickets one for search changes - robel.
one to add message - robel and sujeet.

**Comment by sujeetvkulkarni** [comment]
related #1980, #1981.

**Comment by sujeetvkulkarni** [comment]
closing the issue as we have logged other issues.
