### ISSUE TITLE
Design a general datastructure for list pages

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1705]
With the changes for dynamic list pages we talked about having a general scheme for all three list pages (e.g. backend delivers a list of column headings and a matrix of cell that are only displayed by frontend). Make a design for this data structure + example and discuss with @sujeetvkulkarni if this is feasible. Important consideration:
* Sorting of columns
* Filtering of results
* Original user query needs to be accessible to the frontend
* Frontend would not know which columns to display backend needs to provide this
* Each column also needs to come with a datatype (e.g. some columns are images, some are links, some have tool tips (score), some are numbers that need to be formated)
* Frontend will have to tell backend, which of the columns the user wants

@sujeetvkulkarni if there are other items that need to be considered please add.

**Blocker for**
* #1706 
* #1707 
* #1718 
* #1719

**Comment by sujeetvkulkarni** [comment]
We will use the current option and not go for dynamic expansion of column option.
