### ISSUE TITLE
Implementation of dynamic list pages

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1707]
Update the frontend code to support dynamic list pages based on the decision in #1705 and the implementation in #1706. We will also need a widget for the user to choose the columns that he wants to display. This can be similar to the UniProt column chooser or the GRITS Toolbox column chooser.
![GRITS-column chooser](https://github.com/user-attachments/assets/19782914-9879-41fc-b5bc-5c3ee84e8036)

**Dependencies**
* #1704
* #1705 
* #1706

**Comment by ReneRanzinger** [comment]
We will use the UniProt style rather than the one propose in the screenshot. In difference to UniProt it should an own page (full page).

**Comment by sujeetvkulkarni** [comment]
Done, closing.
