### ISSUE TITLE
Develop a strategy for displaying "full screen" version of tables

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1709]
Look into options to expand the tables of details pages to a "full screen" display. If the option for a real full screen exists propose it in a Wednesday meeting, otherwise a full browser widget display is ok.

**Blocker for**
* #1711

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger I have looked into this and fullscreen modal dialogue is a way to handle this. We would have to develop all controls on top of it which will make user feel he is the same page and not on dialogue (pop-up). So table, filter (on tables we agreed), download and a button to toggle between views will be there. On load this view will call init api to get all the filter options.

bootstrap option:
![Screenshot 2024-09-03 at 10 20 41 PM](https://github.com/user-attachments/assets/85ca823e-ded5-441d-9182-a3a7c604ad34)


material ui option:
![Screenshot 2024-09-03 at 10 24 26 PM](https://github.com/user-attachments/assets/773a8834-e48c-40a1-9dea-d8cc5de3ea17)
