### ISSUE TITLE
Full screen version of details tables (which tables)

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1710]
Confirm that all tables on:
* protein page
* glycan page
* site page
* publication page
* motif page
* biomarker page
should have a full screen option or if some of them should be excluded. Make an Excel file with all the tables per page and discuss it on Wednesday.

**Blocker for**
* #1711

**Comment by sujeetvkulkarni** [comment]
all tables. Demo when one table is done and then based on efforts we can decide how many tables need to be covered. By default all tables need to be covered.

**Comment by sujeetvkulkarni** [comment]
Demo done - all possible tables needs to be supported.
Full screen mode more columns. - Mike (a different task).
Download option for all tables in full screen mode. - Raja.
Download option with filters. - Raja
