### ISSUE TITLE
Filter for glycosylation table (Protein page)

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1712]
For the 4 glycosylation tables on protein detail page:
* Reported Site with Glycan
* Reported Sites
* Predicted Only
* Text Mining

find out what filtering options are desired for each table. Make an file and start with the glycan search result filters where applicable. Bring this up on Wednesday to collect feedback.

**Blocker for**
* #1713
* #1714 
* #1720 
* #1721

**Comment by sujeetvkulkarni** [comment]
File to provide filter options : [TableFilterOptions](https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/_layouts/15/doc.aspx?sourcedoc=%7B90ed76da-34f0-4028-90a5-4b91e9185856%7D&action=edit)

**Comment by sujeetvkulkarni** [comment]
Send the file to all.
Glycan list + site list filters for glycosylation tables.

**Comment by ReneRanzinger** [comment]
The list is finalized.
