### ISSUE TITLE
Implement filter option for glycosylation tables

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1714]
Based on the implementation in #1713 implement filter panels for the glycosylation tables on the protein details page. 

**Dependencies**
* #1713 
* #1712
* #1817

**Comment by sujeetvkulkarni** [comment]
Done.

**Comment by sujeetvkulkarni** [comment]
https://tst.glygen.org/protein/P0DTC2-1#Glycosylation
