### ISSUE TITLE
Integration of text mining data (GW)

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1716]
Integrate the text mining data produced by Robels pipeline into the GlyGen release. Frontend wise that should have little impact since it just more data. How do we deal with the case that your and Vijays pipeline produced:
* the same results
* slightly different results

This is also related to documenting the algorithm used (#1717) in the frontend.

**Comment by rykahsay** [comment]
@katewarner @ubhuiyan  ... please add the following step as part of the downloads that should be done in every release (including now), which will be one of the inputs for the *_proteoform_glycosylation_sites_literature_mining.csv dataset files:

```
$ cp /data/shared/lmsite/generated/predicted/glycosylation_sites_lmsite.csv /data/shared/glygen/downloads/lit_min/current/
```

**Comment by ubhuiyan** [comment]
@rykahsay Appears the `glycosylation_sites_lmsite.csv` file is locked. Could you give me permissions?

```
[sbhuiyan28@glygen-vm-dev ~]$ ll /data/shared/lmsite/generated/predicted/
total 81
-rw-r--r--. 1 rykahsay glygen 164193 Sep 23 13:31 glycosylation_sites_lmsite.csv
```

**Comment by ubhuiyan** [comment]
I was able to copy it regardless. It's also been updated in the documentation.
