### ISSUE TITLE
Text mining algorithm in protein glycosylation text mining tab

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1717]
How is the algorithm that produced text mining glycosylation present in the corresponding table on proteins details glycosylation section? Is it a column or a badge? We need to be able so show that some data came from @rykahsay pipeline and some from Vijays.

**Comment by sujeetvkulkarni** [comment]
https://tst.glygen.org/protein/P12931-1#Glycosylation
mining_tool: "lmsite_pipeline"

![Screenshot 2024-11-18 at 5 07 10 PM](https://github.com/user-attachments/assets/ab7cf6dd-bd61-41c0-9982-ec9f660f30fe)

**Comment by sujeetvkulkarni** [comment]
semicolon separated list.
Tool - Column name.

**Comment by sujeetvkulkarni** [comment]
related #1978

**Comment by sujeetvkulkarni** [comment]
Done, closing. Related issue created for robel https://github.com/glygener/glygen-issues/issues/1978
