### ISSUE TITLE
Download option for dynamic list pages (Backend)

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1718]
Adjust the list page download option to consider the user specific column selection for the download as well. Frontend will have to provide list ID, filters, column selection to the download web service.

**Dependencies**
* #1704 
* #1705 
* #1706 

**Blocker for**
* #1719

**Comment by sujeetvkulkarni** [comment]
@rykahsay
Download api with user selected column JSON:
https://api.glygen.org/data/list_download?query=
{"id":"a7e4068d39c1f9c017cb6f3c069e6ea5",
"download_type":"glycan_list",
"format":"csv",
"compressed":false,
"filters":[{"id":"by_organism","operator":"OR","selected":["Rat"]}],
"columns":["glycan_id", "glycan_image", "monoisotopic_mass", "no_of_sugars", "no_of_glycoproteins"]
}

Frontend will send list of user selected column ids it has received from list_init api and backend will include these columns along with mandatory/immutable columns as response.
Similar changes will apply for protein_list and site_list downloads.

**Comment by rykahsay** [comment]
When ever you make a call to list API, you will get "listcache_id" key under the "cache_info" key. Using that "listcache_id" in your downloads payload ( "id" key), you will be able to download the specific table that was displayed to the user after making filters/columns. This means you don't have to send "filters" and "columns" in your download API payload.


```
{
    "cache_info": {
        "query": {},
        "ts": "2024-10-22 11:20:53 EDT-0400",
        "record_type": "protein",
        "search_type": "search",
        "cache_id": "4e1e51f13312f68dc1b18834205a8f19",
        "listcache_id": "406001e7305d4152bd24a37ac6f5c871"
    },
    "filters": {
        "applied": [],
        "available": []
    },
    "results": [
        {
            "uniprot_canonical_ac": "P14272-1",
            "uniprot_id": "KLKB1_RAT",
            "mass": 71274.0,
            "length": 638,
            "protein_name": "Plasma kallikrein",
            "gene_name": "Klkb1",
            "organism": "Rat",
            "refseq_name": "",
            "refseq_ac": "",
            "total_n_glycosites": 6,
            "total_o_glycosites": 0,
            "filter_code": "0000000.0000111.100000.00000000000100.00101",
            "hit_score": -1.0,
            "score_info": {
                "contributions": [],
                "formula": "sum(w + 0.01*f)",
                "variables": {
                    "c": "condition name",
                    "w": "condition weight",
                    "f": "condition match frequency"
                }
            }
        },
       ....
```

**Comment by sujeetvkulkarni** [comment]
use listcache_id in all cases.

**Comment by sujeetvkulkarni** [comment]
@rykahsay 
Download api only returns paginated response should return all the records.
In below case it only returns 20 records instead of 91.
https://api.tst.glygen.org/data/list_download?query=
{"id":"dd5719069bb1e853008e1f2e7bca5727","download_type":"glycan_list","format":"csv","compressed":false,"filters":[]}

![Screenshot 2024-10-28 at 11 20 03 AM](https://github.com/user-attachments/assets/dfab4804-7f4a-40ec-87b9-1f8adbcbc0f8)

**Comment by rykahsay** [comment]
Tried to fix it, please check now

**Comment by sujeetvkulkarni** [comment]
Done, closing.
