### ISSUE TITLE
All GlyTouCan accession tracking

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#172]
Our GlyTouCan ID tracking relies on dataset files glycan_glytoucanidlist.csv and  glycan_glytoucan_accession_history.csv which depend on these downloads:
```
downloads/glycan_list/current/* --> unreviewed/glycan_glytoucanidlist.csv
downloads/glytoucan/current/export/glygen_retired_accessions.tsv --> unreviewed/glycan_glytoucan_accession_history.csv
```

I don't know if you are downloading  downloads/glycan_list/current  manually but it needs to updated to reflect current status of IDs in GlyTouCan. In the future, you may need to work with Nathan to get this in his exports

**Comment by kmartinez834** [comment]
@rykahsay I am not downloading downloads/glycan_list/ at all...it hasn't been updated since 05_17_2021.  I'll touch base with Nathan to get the updated lists --> is this needed for 2.0?

**Comment by kmartinez834** [comment]
@kmartinez834 to reach out to Nathan to add these lists to his export for 2.1

**Comment by kmartinez834** [comment]
@edwardsnj could you provide the following files to us?  

glytoucan_allacc.txt (all GlyTouCan accessions)
glytoucan_archived.txt (all archived GlyToucan accessions)
glytoucan_replaced.txt (all replaced GlyTouCan accessions)

**Comment by edwardsnj** [comment]
These are available here (tagged w/ release version if you prefer, as with other GlycanData files):

  https://github.com/glygen-glycan-data/PyGly/tree/master/smw/glycandata/data

For current released version, the tag is: GlyGen-GlycanData-Export-Current 
Explicit current version tag is: GlyGen-GlycanData-Export-v1.13.0

https://github.com/glygen-glycan-data/PyGly/tree/GlyGen-GlycanData-Export-Current/smw/glycandata/data

Direct download of raw files (for glytoucan_allacc.txt):

  https://raw.githubusercontent.com/glygen-glycan-data/PyGly/GlyGen-GlycanData-Export-Current/smw/glycandata/data/glytoucan_allacc.txt

**Comment by kmartinez834** [comment]
👍 Much appreciated!
