### ISSUE TITLE
Glycan Structure and Substructure not working on prd

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1723]
The Glycan Structure and Substructure search tools not working on prd. 

![image](https://github.com/user-attachments/assets/0a4c3ef9-9fe3-4d86-8477-a6f21752fdd2)

I tried both the GlycoCT and WURCS examples, and I tried some GlycoCT and WURCS IDs I copied from some glycan entries and got the same error message with no results. 

![image](https://github.com/user-attachments/assets/ef5d2a0b-27c4-497a-a6fd-3c39852b965e)

**Comment by rykahsay** [comment]
Tried to fix it, please try now

**Comment by katewarner** [comment]
Fixed. Thank you
