### ISSUE TITLE
Update release versions to 2.7 on all GlyGen prd pages 

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1724]
I noticed that the release version is still 2.6 on GlyGen prd e.g. https://www.glygen.org/ and https://data.glygen.org/. 
![image](https://github.com/user-attachments/assets/10447d92-9077-4813-9a4e-2e5ae581cc07)

Please update to 2.7, and also add 2.7.1 to https://[api.glygen.org/misc/verlist](https://api.glygen.org/misc/verlist)

**Comment by ReneRanzinger** [comment]
Wait. we released 2.6.

2.7 is from Septebmer to November.

**Comment by katewarner** [comment]
Yes sorry, whoops!!
