### ISSUE TITLE
Create glygen/current_release/README.txt for 2.7

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1728]
Hi Jie, can you please create a new README.txt for the UniProt glygen current 2.7 release i.e. `https://ftp.ebi.ac.uk/pub/contrib/glygen/current_release/README.txt` 

It looks like the current text file is for the 2.6 release as it doesn't mention Bos taurus (cow) but does mention Arabidopsis.

**Comment by jieluo321** [comment]
I updated README.txt, can you double check

**Comment by katewarner** [comment]
Excellent. Thank you very much!
