### ISSUE TITLE
Test APIs on beta

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#173]
Test all APIs on beta: https://beta-api.glygen.org and report any broken ones in the next comment.

**Comment by JingyueWu** [comment]
@kmartinez834 @jeet-vora I tested all APIs and got 2 error messages, please see the following: 

In /directsearch/glycan/ API, I got this error message: 

![Screen Shot 2023-03-23 at 3 50 30 PM](https://user-images.githubusercontent.com/61590108/227335014-2cbaad47-a932-4e27-8d11-62cd808afc24.png)

In /job/delete API, I got this error message: 

![Screen Shot 2023-03-23 at 3 59 05 PM](https://user-images.githubusercontent.com/61590108/227337235-5d6ecbd7-fa3b-440d-a395-2e11c3b8b2fd.png)

**Comment by kmartinez834** [comment]
**- /directsearch/glycan/** 
--> "protein_identifier" query is timing out, I'm getting a loading wheel and then an unresponsive notification from my browser (Chrome). If I wait long enough, I eventually get the RangeError mentioned by Jingyue for the example protein, and others (ex. P19827-1)
--> Other queries for this API are working (ex. https://beta-api.glygen.org/directsearch/glycan/?query={%22offset%22:1,%22limit%22:100})

**- /job/delete**
--> I created a new job ("jobid": 2) and tried to delete it, but got an exception error
![image](https://user-images.githubusercontent.com/90285371/227561800-db3bf043-924d-47a6-b439-14b716a6f50b.png)

**Comment by rykahsay** [comment]
@kmartinez834 -- does your swagger show directsearch APIs? That is the old version, the direct search APIs should be gone. This is what you should see on beta now:

<img width="735" alt="image" src="https://user-images.githubusercontent.com/20584876/227979255-e54b40ac-5aa2-44f7-ace7-525d08c86f86.png">

**Comment by kmartinez834** [comment]
@rykahsay --> yes, I cleared my cache too and still seeing directsearch:

![image](https://user-images.githubusercontent.com/90285371/227983257-04d11d91-7bf6-4f7d-9668-677ba547f112.png)

**Comment by rykahsay** [comment]
Ok, can you check now?

**Comment by kmartinez834** [comment]
👍
