### ISSUE TITLE
Protein dataset QC

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1736]

**Comment by jeet-vora** [comment]
@rykahsay @ubhuiyan @katewarner
 **Here is the table with Dataset QC checks.**  (Please add others if needed)

| QC category                 | Assignment | Status (P/F\\\*\\\*) | Ticket Number              | Instructions                                                                                                                           | Notes                                                                           |
| --------------------------- | ---------- | -------------------- | -------------------------- | -------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------- |
| Check Ready datasets for QC | Kate       | F                    |                            | python3 wrap-check-datasets-all.py -m protein                                                                                          | Check logs/protein.log to see which datasets are ready for QC                   |
| Check Datasets  Manually    | Kate       | F                    | #1801, #1802, #1812, #1813 | Manually check if the datasets look good in unreviewed folder. Check size and check whether new datasets have been processed correctly | Check the dataset whose size is 0 of few KBs or Bs. Edit masterlist accordingly |
| Check Datasets Group        | Kate       | F                     | #1815, #1832, #1834, #1835, #1837             | Run check-dataset-group.py -m protein -r 1.12.3  | Compare the protein datasets with previous release and check the major differences in numbers |
| Check Citations             | Kate       |   F                   | #1852, #1853, #1854         | check-citation-datasets.py                                                                                                             | Run this script to see whether if any citations are missing                     |

**Comment by rykahsay** [comment]
@katewarner @ubhuiyan 
Protein datasets are created, please start QC

**Comment by ubhuiyan** [comment]
Add citation script at /software/glygen/check-citation.py
