### ISSUE TITLE
Nathan's export ready

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1737]
Nathan provides glycan files for @ubhuiyan

**Comment by ubhuiyan** [comment]
@edwardsnj all files are ready. Please proceed. Here is a copy of the notes:

- Added mw_refmet_mapping_result.tsv - a new resource we are implementing that contains monosaccharide information. Please add the xrefs on your end.
- Updated the user submitted data to tsv format: 1-s2.0-S1535947624000070-mmc5.tsv and 1-s2.0-S1535947624000070-mmc7.tsv
- Added bovine files for glyconnect, mcw, and dataset ID to OGlcNAcAtlas rows.
- The file previously named allbiomarkers.tsv has been renamed to oncomx.tsv. This change reflects the new organization by the BiomarkerKB team, which now separates their data by resource. The oncomx.tsv file will now include all protein and glycan biomarker data going forward.

**Comment by edwardsnj** [comment]
Done
