### ISSUE TITLE
Missing publications for Biomarkers

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1745]
https://www.glygen.org/biomarker/AA4761-1

There are multiple paper links on the page but the publication section is empty. Frontend or backend?

**Comment by sujeetvkulkarni** [comment]
Backend issue.
Backend is not sending citation array and also section_stat contains total count 0 for citation table id.

API:
https://api.glygen.org/biomarker/detail/AA4761-1?query={%22paginated_tables%22:{"paginated_tables":[{"table_id":"publication","offset":1,"limit":200,"sort":"date","order":"desc"}]}

![Screenshot 2024-09-06 at 10 42 58 AM](https://github.com/user-attachments/assets/51de6594-3f01-4582-8c0c-58c5526e37e8)

**Comment by rykahsay** [comment]
Fixed at the JSON level, will reflect when we push data to API on tst. Please check this when we are testing APIs and frontend on tst server

<img width="1392" alt="image" src="https://github.com/user-attachments/assets/ef0f7414-912f-4c42-8cb6-ade8e26822d3">

**Comment by katewarner** [comment]
I don't think this is fixed, I noticed that there were several proteins where there are pubmed evidence badges are present in the Evidence and Components sections of the Biomarker page (on the front end and API), but these pubmed IDs are not collected and displayed in the Publications section. For example "AA4695-6" contains data and evidence from Pubmeds:32224151, 32369209 and 24481866, but these are not listed in the Publications section. Also the Pubmed ID: 32479790 is missing from the Publications section in several proteins including "AA4737-8", AA4737-3 and AA4737-2

**Comment by rykahsay** [comment]
Please check now

<img width="1037" alt="image" src="https://github.com/user-attachments/assets/c7c510bb-abf1-4a5d-b81f-6d11133fd578">

**Comment by katewarner** [comment]
The backend/ biomarker pages looks fixed, but there seems to be a problem with the biomarker search using publications so I'll make Sujeet a new ticket
