### ISSUE TITLE
Problems with 2.7 EBI downloads

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1746]
It looks like there might be an issue with the processing of the uniprot-proteome-.nt files for 2.7. I noticed the size of many of the nt files has decreased from the 2.6 release.

According to the 2.7 release notes it says: 
```
Changes in this release: 
------------------------ 
Species: dictyostelium-discoideum and drosophila-melanogaster do not have geneRange and transcriptRange since the genomic coordinate are directly imported from INSDC
```
Please let me know if I've misinterpreted something (as you know I'm not a developer) but when you look at the statistics json files for the decreased downloads, it looks like the removal of the coordinates may be the reason for the decrease in size because, for example in the dicty stats the following predicates are zero in this release but 1000s were present in the 2.6 release :"gly:exonRange" : 0, "gly:geneRange" : 0, "gly:hasLocus" : 0, and "gly:reverseStrand" : 0. However, there are also zero predicate expressions for other species such as Arabidopsis and S.cerevisiae which had expressions in the last release.

I understand the INSDC/ensembl data is directly imported into UniProt but I think you've always provided this data to GlyGen as triples as we don't get it directly from ensembl, for example in the arabidopsis file for the 2.6 release:
```
<http://rdf.ebi.ac.uk/resource/ensembl.transcript/AT5G45830.3> <https://sparql.glygen.org/ontology/transcriptRange> <http://purl.uniprot.org/range/873837727d36444c84e636e1885cbfe1> .
<http://rdf.ebi.ac.uk/resource/ensembl.transcript/AT5G45830.3> <https://sparql.glygen.org/ontology/transcriptRange> <http://purl.uniprot.org/range/49f6511441214ea2a9335d04d729bc7f> .
<http://rdf.ebi.ac.uk/resource/ensembl.transcript/AT5G45830.3> <https://sparql.glygen.org/ontology/exonRange> <http://purl.uniprot.org/range/91050e699ae24c5f9e33fd0df545e2e7> .
<http://rdf.ebi.ac.uk/resource/ensembl.transcript/AT5G45830.3> <https://sparql.glygen.org/ontology/exonRange> <http://purl.uniprot.org/range/7a10622b10c24fd58afda301e136f204> .
 ```
Can you please check the glygen processing protocol and let us know whether or not there is an issue? And can you also let us know why you think that the INSDC/ensembl data should not be included ?

**Comment by jieluo321** [comment]
For Arabidopsis and S.cerevisiae, proteins are imported from insdc. Before we did not have genomic coordinate pipelines for insdc proteomes, we imported the genomic coordinate from ensembl for these two species, So that we have ensembl gene/transcript/protein and other ensembl related data in the genomic coordinates for these two proteomes. From 2024_04, we had the genomic coordinate pipelines for insdc (imported genomic coordinate directly from insdc data set). Since these two proteomes were imported from insdc, we switched the genomic coordinate data import for these two proteomes to insdc pipelines. So ensembl related data are not there.

**Comment by katewarner** [comment]
Okay, makes sense. We really don't want to lose this information in GlyGen so which would be the best way for us to retrieve this data? Is there a way that UniProt can provide this data to us or do we need to create an/or download a new dataset?

**Comment by jieluo321** [comment]
zebrafish proteome that will be added next is imported from refseq not from ensembl. The genomic coordinate for this proteome will not have ensembl gene/transcript/protein.

**Comment by katewarner** [comment]
Okay, thanks for the info about the zebrafish. 

In case you don't see me last comment (as it looks like we were writing comments at the same time) - Regarding the proteins imported from insdc, and the refseq data from Zebrafish, we really don't want to lose this information in GlyGen so which would be the best way for us to retrieve this data? Is there a way that UniProt can provide this data to us or do we need to create an/or download a new dataset? It looks like genomic localisation is from "mane select", is that correct?

**Comment by jieluo321** [comment]
Our reference proteomes are imported from ensembl, insdc and refseq. All genomic coordinate have nucleotideID
The first example is imported from ensembl
https://www.ebi.ac.uk/proteins/api/coordinates/A0JNW5?format=json
"ensemblGeneId": "ENSG00000111647",
"ensemblTranscriptId": "ENST00000279907",
"ensemblTranslationId": "ENSP00000279907"
"nucleotideId": "CM000674.2",

imported from refseq
https://www.ebi.ac.uk/proteins/api/coordinates/A0A024B5K5?format=json
"nucleotideId": "NC_007126.7"

imported from indsc
https://www.ebi.ac.uk/proteins/api/coordinates/B8XCH5?format=json
"nucleotideId": "CP002684.1"

**Comment by katewarner** [comment]
@jieluo321 Okay thank you for the information. It's definitely something we need to look into so I've added this to the main meeting agenda tomorrow so we can discuss it. 
Talking about it with other members of the GlyGen team, they seem to think that Preethi may have created a patch to fix this issue in the past. It's likely related to this ticket that she worked on: https://github.com/glygener/glygen-issues/issues/840

**Comment by katewarner** [comment]
@jieluo321 Hi Jie, any updates on the progress of the ebi downloads?

**Comment by katewarner** [comment]
@jieluo321 Can you also generate the stats and accession history files for the three new nt.gz files because it looks like they haven't been updated and are based on the three old files. Many thanks 
```
-rwxrwxr-x. 1 k.warner1 glygen       239944 Jul 31 07:32 accession-history-arabidopsis-thaliana.tsv
-rwxrwxr-x. 1 k.warner1 glygen        37346 Jul 31 07:32 accession-history-dictyostelium-discoideum.tsv
-rwxrwxr-x. 1 k.warner1 glygen       108423 Jul 31 07:32 accession-history-drosophila-melanogaster.tsv
-rwxrwxr-x. 1 k.warner1 glygen         7268 Jul 31 07:32 statistics-arabidopsis-thaliana.json
-rwxrwxr-x. 1 k.warner1 glygen         7176 Jul 31 07:32 statistics-dictyostelium-discoideum.json
-rwxrwxr-x. 1 k.warner1 glygen         7260 Jul 31 07:32 statistics-drosophila-melanogaster.json
```

**Comment by jieluo321** [comment]
The six new files are in ftp now.     
        7281 Sep 18 08:33 statistics-arabidopsis-thaliana.json
        7191 Sep 18 08:34 statistics-dictyostelium-discoideum.json
       7284 Sep 18 08:35 statistics-drosophila-melanogaster.json
      107915 Sep 18 08:35 accession-history-arabidopsis-thaliana.tsv.gz
      15346 Sep 18 08:35 accession-history-dictyostelium-discoideum.tsv.gz
      48812 Sep 18 08:37 accession-history-drosophila-melanogaster.tsv.gz

**Comment by katewarner** [comment]
@jieluo321 The new arabidopsis file looks good but the other files are missing some data when I compare it to the 2.6 release, so I have some questions for you.
1. Most of the uniprot-proteome-.nt files for 2.7 (except for Covid and HCV files) show a decrease in data compared to 2.6. I looked at the stats and it seems like a general decrease in many different keys (except for the number of proteins and genes), so I'm wondering if you've carried out some filtering or tidying up of the data you provide to us? 
2.  According to the stats files, the new `uniprot-proteome-dictyostelium-discoideum.nt `and `uniprot-proteome-drosophila-melanogaster.nt `files that you provided to us yesterday, is still missing some gene locus data (see below for a comparison between the 2.6 and 2.7 stats). Is there a reason for this?
```
Dicty
2.7
  "class" : {
    "gly:Gene_Locus" : 0,

  "predicate" : {
    "gly:geneRange" : 0,
    "gly:hasLocus" : 0,

2.6 
  "class" : {
    "gly:Gene_Locus" : 13002,

  "predicate" : {
    "gly:geneRange" : 13002,
    "gly:hasLocus" : 13010,


Drosophila 
2.7
  "class" : {
    "gly:Gene_Locus" : 0,

  "predicate" : {
    "gly:geneRange" : 0,
    "gly:hasLocus" : 0,

2.6
  "class" : {
    "gly:Gene_Locus" : 13885,

  "predicate" : {
    "gly:geneRange" : 13885,
    "gly:hasLocus" : 22053,
```
Thanks in advance

**Comment by jieluo321** [comment]
gene info input files were removed by Preethi for these two proteomes, i will add them and regenerate the data set

**Comment by jieluo321** [comment]
Regenerate drosophila-melanogaster and dictyostelium-discoideum data set with gene info in ftp now dictyostelium-discoideum has few genes in ensembl

**Comment by jieluo321** [comment]
Now dictyostelium-discoideum with gene locus in ftp

 "gly:Gene_Locus" : 13009,
"gly:geneRange" : 14267,
"gly:hasLocus" : 13555,

**Comment by katewarner** [comment]
@jieluo321 Thank you so much so doing this so quickly. We really appreciate it

Regarding the other NT files that have shown a decrease, is this because you've carried out some filtering or tidying up of the data you provide to us? For example, the homo sapiens nt file size has decreased by 50273047, and according to the stats, it's the following predicates that have decreased in size:
```
  "class" : {
    "up:Resource" : 1848301,

"predicate" : {
    "gly:attribution" : 1281238,
    "rdfs:seeAlso" : 3342588,
    "up:classifiedWith" : 1153947,
    "up:database" : 1911872,
    "up:evidence" : 483462,
```
I also checked mouse and the same predicates had also decreased in size, so I'm wondering has some redundant data been removed from the nt files? If that's the case then that's great, and we'll go ahead with the release. I just wanted to confirm it with you first.

**Comment by jieluo321** [comment]
We did not update data generation implementation. The only update related to data generation is configuration file for input data. Preethi updated configuration file for input data (due to our switch of INSDC genomic coordinate): removed 2 gene files, i reversed back yesterday and regenerated the data. 
The switch of INSDC genomic coordinate issue is also reversed back (affecting three proteomes)

**Comment by katewarner** [comment]
@jieluo321 Thanks again. Apologies but in my last comment I mentioned that the other nt files were also displaying a decrease in data. I had a closer look at this: 

1., It looks like the rat nt file is displaying a decrease in the predicates mentioned in my last comment.
2. The chicken nt file is displaying a decrease a decrease in the following predicates: 
<img src="https://github.com/user-attachments/assets/c4a495db-e967-4bbd-b26a-0432569c3418" width=60%>
3. The yeast and pig nt files have the same issue as the drosophila and dicty datasets in that the genomic co-ordinate data has decreased e.g.

<img src="https://github.com/user-attachments/assets/d1030d97-2973-431e-8da7-6368c867bd9e" width=70%>

Sorry to be a pain but could you possibly reverse back to the old gene input files and regenerate the following datasets as well (including cow for consistency) : 

**uniprot-proteome-bos-taurus.nt
uniprot-proteome-gallus-gallus.nt
uniprot-proteome-rattus-norvegicus.nt
uniprot-proteome-saccharomyces-cerevisiae.nt
uniprot-proteome-sus-scrofa.nt**

Once I've sent these files for processing, I can start working with you or Preethi's replacement on how to change where we get our gene co-ordinate information from for 2.8

**Comment by jieluo321** [comment]
i cannot reverse. The gene file is fetched for each release from release database. we don't have database for 2024_03. This is also related to ensembl release version. So it cannot be reversed. 2024_03 used different ensembl version

**Comment by katewarner** [comment]
@ReneRanzinger @rykahsay @jeet-vora 
Had a zoom meeting with @jieluo321 he is able to regenerate the pig nt file because their gene locus data is from ensembl. But they cannot regenerate the yeast nt file as it's from INSDC and it's too far along in the UniProt release to retrieve the ensembl data for this species. 

As discussed in the dev meeting yesterday I think we should use the yeast nt file from the 2.6 release so that we can release 2.7 on schedule.

**Comment by jieluo321** [comment]
I cleaned all input files for PIG and regenerated input file and then regenerated output files. The output files are the same as the ones in ftp site.
