### ISSUE TITLE
BCO readme version is v-x.x.x

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#175]
https://beta-data.glygen.org/GLY_000001

![image](https://user-images.githubusercontent.com/90285371/227585953-e71a963c-8a3c-4c41-a9f0-4216847acf08.png)

**Comment by rykahsay** [comment]
Fixed
<img width="818" alt="image" src="https://user-images.githubusercontent.com/20584876/228042874-e48bfab7-c8d8-4982-bc33-fe49117f0a52.png">

**Comment by kmartinez834** [comment]
👍
