### ISSUE TITLE
Ensembl Gene link does not work for some species

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1750]
![image](https://github.com/user-attachments/assets/966bc4d5-481d-43e8-beaf-da3a5de35ca0)

I noticed that the "Ensembl Gene" link does not work for some species, and the link needs updating. 

The current hyperlink works for vertebrates (species not yet in GlyGen are in italics) i.e. 
**Vertebrate - https://www.ensembl.org/id/%s** e.g. https://www.ensembl.org/id/ENSG00000176510
Human
Mouse 
Rat
Chicken
Pig
Cow
_Zebrafish 
Chinese hamster_ 

But the hyperlinks do not work for the following non-vertebrates and needs to be changed to the following
**Non-vertebrates - https://www.ensemblgenomes.org/id/%s**  e.g. https://www.ensemblgenomes.org/id/AT1G14760
Arabidopsis thaliana 
Drosophila melanogaster 
Dictyostelium discoideum
Saccharomyces cerevisiae 
_C.elegans_
_Rice_

UniProt does not have the following xref link for SARS-CoV-2 but we may want to add it- https://covid-19.ensembl.org/Sars_cov_2/Gene/Summary?g=/%s e.g. https://covid-19.ensembl.org/Sars_cov_2/Gene/Summary?g=ENSSASG00005000005

**Comment by katewarner** [comment]
@rykahsay I'm not sure how to correct these urls (see above). I thought they were xefs urls but I couldn't find a line for "Ensembl Gene" in the xref_info.csv. It looks like they are `gene.locus.evidence.database` objects within the protein detail page (see below):

https://[api.glygen.org/protein/detail/F4IHS2-1](https://api.glygen.org/protein/detail/F4IHS2-1)

![image](https://github.com/user-attachments/assets/12aa4c24-380f-4b11-aa5a-53e5f271b9ca)

How do I provide instructions to add the `gene.locus.evidence.url` to the protein details pages of the non-vertebrate species listed above? I don't think it is by adding lines to the xref_info file, or is it?

**Comment by rykahsay** [comment]
This is fixed on the other ticket

**Comment by katewarner** [comment]
Thank you
