### ISSUE TITLE
Create araport xref dataset for arabidopsis proteins 

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1752]
Once the ebi files have been downloaded and checked, please create an araport xref dataset for arabidopsis proteins only. 

**Source file:** `uniprot-proteome-arabidopsis-thaliana.nt`
**Output file:** `arabidopsis_protein_xref_araport.csv`

The output file should have the following headers: 
```
"id", "xref_key", "xref_id", "xref_label" 
``` 

**Input file:**
Xref data for araport is present in triples within `uniprot-proteome-arabidopsis-thaliana.nt` e.g. 
```
<http://purl.uniprot.org/uniprot/A0A0A7EPL0> <http://www.w3.org/2000/01/rdf-schema#seeAlso> <http://purl.uniprot.org/araport/AT1G08910> .
<http://purl.uniprot.org/uniprot/F4JYG0> <http://www.w3.org/2000/01/rdf-schema#seeAlso> <http://purl.uniprot.org/araport/AT5G41580> .
<http://purl.uniprot.org/uniprot/A0A178VEK7> <http://www.w3.org/2000/01/rdf-schema#seeAlso> <http://purl.uniprot.org/araport/AT3G60460> .
```

**Output file**
Make new `arabidopsis_protein_xref_araport.csv` file for arabidopsis only.

Example output file: 

| id| xref_key | xref_id |xref_label| 
| -------- | ------- | ------- | ------- |
| A0A0A7EPL0-1 | protein_xref_araport | AT1G08910 |  |
| F4JYG0-1 | protein_xref_araport | AT5G41580 |  |
| A0A178VEK7-1 | protein_xref_araport | AT3G60460|  |

**Comment by rykahsay** [comment]
Done

**Comment by katewarner** [comment]
Looks good thank you
