### ISSUE TITLE
BCO Issue 

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1754]
I am noticing I cannot create BCOs and receive this error message: 

```[sbhuiyan28@glygen-vm-dev glygen]$ python3 create-bco.py -t fc37b506d4dfc3cf5a8a63fe048d88e15fd9b2a9 -f bco_templates/glycan_xref_mw.json
Traceback (most recent call last):
  File "/software/glygen/create-bco.py", line 8, in <module>
    import requests
  File "/usr/local/lib/python3.9/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/local/lib/python3.9/site-packages/urllib3/__init__.py", line 42, in <module>
    raise ImportError(
ImportError: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/216```

**Comment by rykahsay** [comment]
Please try now, and if it doesn't work, run the following command (to remove requests module if you have it locally installed in your home) and try again:

```
pip3 uninstall requests
```

**Comment by ubhuiyan** [comment]
@rykahsay It appears to be still giving me the same error. I am also unable to uninstall requests - the permissions were denied.

**Comment by rykahsay** [comment]
show me the fully python3 create-bco.py command you are doing

**Comment by ubhuiyan** [comment]
`python3 create-bco.py -t fc37b506d4dfc3cf5a8a63fe048d88e15fd9b2a9 -f bco_templates/glycan_xref_mw.csv`
