### ISSUE TITLE
How to download PDB and Alphafold data 

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1755]
Can you please provide instructions on how to download PDB and Alpafold data for each release? I will then document the process in our data downloads file.

**Comment by rykahsay** [comment]
@katewarner @jeet-vora @ubhuiyan 
I guess I have to keep doing this since datasets *_protein_pdb_map.csv and *_protein_xref_alphafolddb.csv must be created first (which depend on EBI nt downloads). 

Instead, during every release, make sure to create a ticket for me on updating the following downloads I do on my end:
- medline
- pubchem
- pdb
- alphafold

**Comment by katewarner** [comment]
@rykahsay 

Okay no problem. At which point in the release would you like the ticket? When we've started the downloading or when we've completed our downloads and they're ready for processing?

**Comment by ubhuiyan** [comment]
@rykahsay @katewarner Just a heads up, I believe I write a ticket for Robel to download the Medline files as per the [Glycan Download Instructions](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B330BDF37-0D03-47DD-A4C4-1FED97C67EA5%7D&file=Data%20Download%20-%20Glycan.docx&action=default&mobileredirect=true), would we prefer to consolidate all these resources into a single ticket? I typically write the ticket while I am downloading Nathan's exports.

**Comment by katewarner** [comment]
@ubhuiyan sounds like a good idea. You would have to wait until I've downloaded and QC'd the protein datasets to make the ticket, but I don't see that as a problem as long as the downloads have no issues since I've usually finished the downloads when you're preparing the files for Nathan

**Comment by rykahsay** [comment]
Yea, one ticket is good idea --- the ticket should be created at the beginning of the release

**Comment by ubhuiyan** [comment]
Sure thing. I can add this to the documentation.

**Comment by ubhuiyan** [comment]
I have added this to the documentation. Closing the ticket now.
