### ISSUE TITLE
Change src_xref_key in user submitted datasets

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1758]
We are changing the source xref badge from "GlyGen" to "Data Submission" in datasets that have been submitted by a user. In these cases the src_xref_key in the datasets will need to change to either "protein_xref_data_submission" or "glygen_xref_data_submission" and the badge on the front end will change to "Data Submission". 

Please update how you process the following datasets to change the `src_xref_key` data to the following:

Change the `"src_xref_key"` data from `"glycan_xref_glygen_ds"` to `"glygen_xref_data_submission"` in the following datasets: 

|BCO dataset| Dataset output file| updated src_xref_key
|----|----|----|
|GLY_000538|glycan_citations_ncfg.csv| glygen_xref_data_submission|
|GLY_000309|glycan_synthesized.csv| glygen_xref_data_submission|

Change the `"src_xref_key"` data from `"protein_xref_glygen_ds"` to `"protein_xref_data_submission"` in the following datasets: 
|BCO dataset| Dataset output file| updated src_xref_key
|----|----|----|
|GLY_000960| human_proteoform_glycosylation_sites_diabetes_glycomic.csv|protein_xref_data_submission|
|GLY_000888| human_proteoform_glycosylation_sites_embl.csv|protein_xref_data_submission|
|GLY_000142| human_proteoform_glycosylation_sites_harvard.csv|protein_xref_data_submission|
|GLY_000716| human_proteoform_glycosylation_sites_o_gluc.csv|protein_xref_data_submission|
|GLY_000335| hcv1a_proteoform_glycosylation_sites_literature.csv|protein_xref_data_submission|

The new xref keys have already been added to xref_info.csv

**Comment by rykahsay** [comment]
Done, please check ... note that  "human_proteoform_glycosylation_sites_o_gluc.csv" is empty because all rows are failing QC and I am removing the empty file

**Comment by katewarner** [comment]
Thank you looks good
