### ISSUE TITLE
Duplicated rows in the Human GlycoEnzOnto dataset

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1759]
Please check your script for processing the human_protein_glycogenes_glycoenzonto.csv dataset

Jeet noticed that there are duplicated rows in the `human_protein_glycogenes_glycoenzonto.csv` dataset (https://data.glygen.org/GLY_000922). e.g. Q96EU7-1, Q2PZI1-1, U3KPV4-1 etc.

![image](https://github.com/user-attachments/assets/28719c86-683b-4933-8552-763a67e904e5)

I checked the downloaded file you use to create the dataset (`/data/projects/glygen/downloads/glycogenes/current/human_glycogenes_glycoenzonto.csv`) and I couldn't find any duplicated rows so I think there may be an issue with the processing script for this dataset.

**Comment by rykahsay** [comment]
This is because the mongoDB containing records/rows from human_glycogenes_glycoenzonto.csv is old and was forgottedn to be updated after we fix the duplication issue. This will go away when we push 2.7.1 to prd. Please keep this ticket with you and check it when we update data.tst.glygen.org

**Comment by katewarner** [comment]
Checked on tst and its fixed. Many thanks
