### ISSUE TITLE
Dataset filters (https://beta-data.glygen.org/)

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#176]
The following "dataset_categories" are outliers:

![image](https://user-images.githubusercontent.com/90285371/227589595-05c581b9-1226-46d4-8504-daf32681e564.png)

@jeet-vora confirm if we should update the BCOs for:

GLY_000615
GLY_000143
GLY_000326 
GLY_000335 

to `"category_value": "SARS coronavirus (SARS-CoV-2 or 2019-nCoV)"` and `"category_value": "Reviewed"`, respectively

**Comment by jeet-vora** [comment]
Changes done on BioCompute Portal

@JingyueWu Please create a ticket for yourself to check once Robel pushed next to tst/beta

**Comment by kmartinez834** [comment]
@jeet-vora --> I have changed GLY_000615 species to "SARS coronavirus (SARS-CoV-2 or 2019-nCoV)"

**Comment by JingyueWu** [comment]
@jeet-vora Please review the ticket I just made -- should I be checking BioCompute or GlyGen DB?
