### ISSUE TITLE
Create tair xref dataset for arabidopsis proteins

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1760]
Once the ebi files have been downloaded and checked, please create a tair xref dataset for arabidopsis proteins only. 

**Source file:** `uniprot-proteome-arabidopsis-thaliana.nt`
**Output file:** `arabidopsis_protein_xref_tair.csv`

The output file should have the following headers: 
```
"id", "xref_key", "xref_id", "xref_label" 
``` 

**Input file:**
Xref data for tair is present in triples within `uniprot-proteome-arabidopsis-thaliana.nt` e.g. 
```
<http://purl.uniprot.org/uniprot/A0A0A7EPL0> <http://www.w3.org/2000/01/rdf-schema#seeAlso> <http://purl.uniprot.org/tair/AT1G08910> .
<http://purl.uniprot.org/uniprot/F4JYG0> <http://www.w3.org/2000/01/rdf-schema#seeAlso> <http://purl.uniprot.org/tair/AT5G41580> .
<http://purl.uniprot.org/uniprot/A0A178VEK7> <http://www.w3.org/2000/01/rdf-schema#seeAlso> <http://purl.uniprot.org/tair/AT3G60460> .
```

**Output file**
Make new `arabidopsis_protein_xref_tair.csv` file for arabidopsis only.

Example output file: 

| id| xref_key | xref_id |xref_label| 
| -------- | ------- | ------- | ------- |
| A0A0A7EPL0-1 | protein_xref_tair | AT1G08910 |  |
| F4JYG0-1 | protein_xref_tair | AT5G41580 |  |
| A0A178VEK7-1 | protein_xref_tair | AT3G60460|  |

**Comment by rykahsay** [comment]
Please check:

```
$ head unreviewed/arabidopsis_protein_xref_tair.csv
"uniprotkb_canonical_ac","xref_key","xref_id","xref_label"
"Q9M9K1-1","protein_xref_tair","AT3G08590",""
"Q58FU4-1","protein_xref_tair","AT5G05330",""
"P42737-1","protein_xref_tair","AT5G14740",""
"A8MQY6-1","protein_xref_tair","AT5G36320",""
"A8MQY1-1","protein_xref_tair","AT4G01540",""
"Q9LPK6-1","protein_xref_tair","AT1G21350",""
"Q3EAR7-1","protein_xref_tair","AT3G42180",""
"A8MQY8-1","protein_xref_tair","AT2G16505",""
"A8MQY9-1","protein_xref_tair","AT2G33847",""

```

**Comment by katewarner** [comment]
Looks good thank you
