### ISSUE TITLE
Update gene sections for proteins from non-vertebrate species

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1762]
When you create the `"Ensembl gene"` sections on the protein pages of arabidopsis, fruitfly, yeast and sarscov2  e.g. 

https://[api.glygen.org/protein/detail/F4IHS2-1](https://api.glygen.org/protein/detail/F4IHS2-1)

![image](https://github.com/user-attachments/assets/12aa4c24-380f-4b11-aa5a-53e5f271b9ca)

Please update your code to correct the url to ensembl as follows (it's actually two additional base urls not one): 

Original database url in xref_info.csv: 
`protein_xref_ensembl,ENSEMBL,https://www.ensembl.org/id/%s,rs1600462368|rs1600462368|rs1583656583
`

For arabidopsis proteins change to: 
`protein_xref_ensembl_arabidopsis,ENSEMBL,https://www.ensemblgenomes.org/id/%s,AT1G14760|AT4G36540|AT5G15900`
For fruitfly proteins change to: 
`protein_xref_ensembl_fruitfly,ENSEMBL,https://www.ensemblgenomes.org/id/%s,FBgn0052803|FBgn0051155|FBgn0028996`
For yeast change to:
`protein_xref_ensembl_yeast,ENSEMBL,https://www.ensemblgenomes.org/id/%s,YBL079W|YPL060W|YOL064C
`
For sarscov2 change to:
`protein_xref_ensembl_sarscov2,ENSEMBL, https://covid-19.ensembl.org/Sars_cov_2/Gene/Summary?g=%s,ENSSASG00005000005|ENSSASG00005000004|ENSSASG00005000013`

**Comment by rykahsay** [comment]
It is fixed now and will be shown as below -- please check when during API test

<img width="1057" alt="image" src="https://github.com/user-attachments/assets/ae4444dc-51c5-42e9-a9ec-020b45cf84f6">

**Comment by katewarner** [comment]
Checked on tst and it looks good
