### ISSUE TITLE
Testing plan for 2.7

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1767]
Based on the testing meeting on 9/17:

- All GlyGen team will test including GU and EBI.
- GW will share the testing table and all the testing will be split among teams (no redundancy in testing).
- Raja will send emails to Maria and Nathan to participate in testing.

@jeet-vora will share the testing table with people assignment. After this he will setup a meeting to discuss this.

**Comment by ReneRanzinger** [comment]
@jeet-vora this will become a blocker very quickly now. Just as a reminder from this discussion. You would share version of GW testing table, which @ubhuiyan and @katewarner have been using, with us that would contain who is doing which testing (in 2.7). That would also include "proposals" for testing done by @edwardsnj. I am to use this to start a discussion with Nathan about this. Two changes since the ticket was created:
* for 2.7 EBI will not do any testing. As soon as the new full time employee is hired that person will join on the same level as Urnisha and Kate
* @Mindyporterfield will join from the UGA side. We allocated 2 weeks of her time to help with testing on beta and production

I am also not sure if you were part of the server discussion meeting. The decision there is that there will be no testing on tst. In the beginning of the testing phase we deploy directly to beta. I will confirm with @sujeetvkulkarni if he as beta access now.

**Comment by jeet-vora** [comment]
@ReneRanzinger I have almost finalised the testing strategy document for 2.7 testing. Plan to send the template now and discuss it in the next meeting.

I am aware of the other changes. Thanks

**Comment by ReneRanzinger** [comment]
Ok, lets call this the testing plan (what tests need to be done and who does them). There is another ticket for strategy #1840 which is concerned about how is it done.

**Comment by ReneRanzinger** [comment]
I created a ticket for @rykahsay to get Sujeet the beta access (#1843)

**Comment by jeet-vora** [comment]
Notes from the meeting on Oct 4, 2024

- All the 4 servers (tst, dev, beta and prd) will be kept as is
- Instead of pushing to tst, push will now happen to beta, multiple pushes can happen, Sujeet can make the pushes.
- Sujeet to get beta access from Robel
- From beta, there will be a push to prd
- Robel to look into having a separate instance for prd for 2.8 (#1850)
- Ticket for Vishal to look into hardware proposal (#1851)
- For testing, Nathan and team and Mindy from UGA will participate
- There will be no redundant front-end testing, all testing tasks will be distributed equally.
- Jeet to provide the testing template and information.

**Comment by ReneRanzinger** [comment]
@jeet-vora I have not seen this plan, yet. If that was discussed with all (including Nathan!!!) disregard this. 

If not, I will not be able to have a discussion with Nathan regarding his test involvement before the testing phase. Due to holiday, travel, FAES meeting etc. Please take charge of this. If you do not feel comfortable having this discussion with him make sure the plan is shared next week and ask him if we can discuss this on FAES-Monday (over lunch or dinner). Might be best anyway - that way Raja can be part of the discussion.
