### ISSUE TITLE
Using the 2.6 uniprot-proteome-saccharomyces-cerevisiae.nt file for 2.7

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1768]
I noticed that there was an issue with the gene locus/co-ordinates predicates in the pig and yeast nt files Preethi created (https://github.com/glygener/glygen-issues/issues/1746#issuecomment-2360855747). I had a zoom meeting with Jie this afternoon and he is able to regenerate the pig nt file because their gene locus data is from ensembl, but they cannot regenerate the yeast nt file as it's from INSDC and it's too far along in the UniProt release to retrieve the ensembl data for this species.

As discussed in the dev meeting yesterday I think we should use the yeast nt file from the 2.6 release for dataset processing so that we can release 2.7 on schedule. Do you think that this is the right way to proceed or do you see any problems with this strategy?

**Comment by ReneRanzinger** [comment]
I think we should go ahead with this to not delay any further. @rykahsay do you see a problem?

**Comment by rykahsay** [comment]
It should be fine

**Comment by katewarner** [comment]
Okay thanks. I'll make you a ticket to let you know that you can start processing the protein downloads
