### ISSUE TITLE
Unable to open dataset on https://beta-data.glygen.org/

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#177]
Getting the following error when I try to open all datasets GLY_000707 --> GLY_000739 in beta-data.glygen.org/

![image](https://user-images.githubusercontent.com/90285371/227592240-b6b9403e-3ba2-4ebd-a76a-64ef2d769b75.png)

**Comment by rykahsay** [comment]
check now

**Comment by kmartinez834** [comment]
👍
