### ISSUE TITLE
Dublicated SNV entries

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1772]
Reported by Raja:
![image(3)](https://github.com/user-attachments/assets/fa2d6be9-2354-4099-bc6c-68e5ed183cca)
![image(4)](https://github.com/user-attachments/assets/636f0458-dea7-43e5-ad34-880af61ee44e)

The [API ](https://api.glygen.org/protein/detail/Q8IWL2-1/?query={%22paginated_tables%22:[{%22table_id%22:%22glycosylation_reported_with_glycan%22,%22offset%22:1,%22limit%22:20,%22sort%22:%22start_pos%22,%22order%22:%22asc%22},{%22table_id%22:%22glycosylation_reported%22,%22offset%22:1,%22limit%22:20,%22sort%22:%22start_pos%22,%22order%22:%22asc%22},{%22table_id%22:%22glycosylation_predicted%22,%22offset%22:1,%22limit%22:20,%22sort%22:%22start_pos%22,%22order%22:%22asc%22},{%22table_id%22:%22glycosylation_automatic_literature_mining%22,%22offset%22:1,%22limit%22:20,%22sort%22:%22start_pos%22,%22order%22:%22asc%22},{%22table_id%22:%22phosphorylation%22,%22offset%22:1,%22limit%22:20,%22sort%22:%22start_pos%22,%22order%22:%22asc%22},{%22table_id%22:%22snv_disease%22,%22offset%22:1,%22limit%22:20,%22sort%22:%22start_pos%22,%22order%22:%22asc%22},{%22table_id%22:%22snv_non_disease%22,%22offset%22:1,%22limit%22:20,%22sort%22:%22start_pos%22,%22order%22:%22asc%22},{%22table_id%22:%22publication%22,%22offset%22:1,%22limit%22:200,%22sort%22:%22date%22,%22order%22:%22desc%22}]})sends the duplicated entries.

**Comment by katewarner** [comment]
@rykahsay See issue above. The datasets look fine and it looks like the duplicated snv entries in the api has been fixed (e.g. [https://api.glygen.org/protein/detail/Q8IWL2](https://api.glygen.org/protein/detail/Q8IWL2)) but the SNV section is still displaying the duplicated entries for both "Disease associated mutations" and "Non-disease associated mutations" on the front end e.g. [https://www.glygen.org/protein/Q8IWL2-1#Single-Nucleotide-Variation](https://www.glygen.org/protein/Q8IWL2-1#Single-Nucleotide-Variation): 

![image](https://github.com/user-attachments/assets/5d114acd-5a5f-4b09-b4f6-a014c0dd9c66)

Note that it says there are 3 entries but 6 entries are displayed due to the duplicated entries.

**Comment by rykahsay** [comment]
@sujeetvkulkarni  ... I don't know why the frontend is showing duplicate rows -- the ApI gives the following objects:

One disease SNV
```
{
    "evidence": [
        {
            "id": "Q8IWL2",
            "database": "BioMuta",
            "url": "https://hivelab.biochemistry.gwu.edu/biomuta/proteinview/Q8IWL2"
        }
    ],
    "start_pos": 19,
    "end_pos": 19,
    "subjects_tested": "0",
    "subjects_positive": "0",
    "frequency": "0.0",
    "sequence_org": "V",
    "sequence_mut": "A",
    "comment": "Somatic mutation passed 1 out of 6 filters: num. of cancers (4).",
    "chr_id": "10",
    "chr_pos": "79611881",
    "ref_nt": "T",
    "alt_nt": "C",
    "site_lbl": "V19",
    "keywords": [
        "biomuta",
        "somatic",
        "cancer",
        "disease"
    ]
}
```

Three non-disease SNVs
```
{
    "evidence": [
        {
            "id": "rs1860011166",
            "database": "dbSNP",
            "url": "https://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs1860011166"
        },
        {
            "id": "rs1860011166",
            "database": "TOPMed",
            "url": "https://www.ncbi.nlm.nih.gov/snp/rs1860011166#frequency_tab"
        }
    ],
    "glycoeffect": [
        "n-glyco-sequon-gain"
    ],
    "start_pos": 173,
    "end_pos": 173,
    "sequence_org": "A",
    "sequence_mut": "T",
    "comment": "Germline mutation passed 1 out of 1 filters: n-glyco-sequon-gain (NEA->NET).",
    "chr_id": "10",
    "chr_pos": "79613883",
    "ref_nt": "A",
    "alt_nt": "null",
    "site_lbl": "A173",
    "keywords": [
        "ebi",
        "germline"
    ]
}

{
    "evidence": [
        {
            "id": "rs761796084",
            "database": "dbSNP",
            "url": "https://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs761796084"
        },
        {
            "id": "rs761796084",
            "database": "ExAC",
            "url": "https://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs761796084"
        },
        {
            "id": "rs761796084",
            "database": "TOPMed",
            "url": "https://www.ncbi.nlm.nih.gov/snp/rs761796084#frequency_tab"
        },
        {
            "id": "rs761796084",
            "database": "gnomAD",
            "url": "http://gnomad.broadinstitute.org/awesome?query=rs761796084"
        }
    ],
    "glycoeffect": [
        "n-glyco-sequon-loss"
    ],
    "start_pos": 207,
    "end_pos": 207,
    "sequence_org": "N",
    "sequence_mut": "K",
    "comment": "Germline mutation passed 1 out of 1 filters: n-glyco-sequon-loss (NYT->KYT).",
    "chr_id": "10",
    "chr_pos": "79613987",
    "ref_nt": "G",
    "alt_nt": "null",
    "site_lbl": "N207",
    "keywords": [
        "ebi",
        "germline"
    ]
}

{
    "evidence": [
        {
            "id": "rs1554854656",
            "database": "dbSNP",
            "url": "https://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs1554854656"
        },
        {
            "id": "rs1554854656",
            "database": "ENSEMBL",
            "url": "https://www.ensembl.org/id/rs1554854656"
        }
    ],
    "glycoeffect": [
        "n-glyco-sequon-loss",
        "o-glyco-site-loss"
    ],
    "start_pos": 209,
    "end_pos": 209,
    "sequence_org": "T",
    "sequence_mut": "N",
    "comment": "Germline mutation passed 1 out of 1 filters: n-glyco-sequon-loss (NYT->NYN).",
    "chr_id": "10",
    "chr_pos": "79613992",
    "ref_nt": "A",
    "alt_nt": "null",
    "site_lbl": "T209",
    "keywords": [
        "ebi",
        "germline"
    ]
}

```

**Comment by ReneRanzinger** [comment]
@rykahsay please use the [link ](https://api.glygen.org/protein/detail/Q8IWL2-1/?query=%7B%22paginated_tables%22:%5B%7B%22table_id%22:%22glycosylation_reported_with_glycan%22,%22offset%22:1,%22limit%22:20,%22sort%22:%22start_pos%22,%22order%22:%22asc%22%7D,%7B%22table_id%22:%22glycosylation_reported%22,%22offset%22:1,%22limit%22:20,%22sort%22:%22start_pos%22,%22order%22:%22asc%22%7D,%7B%22table_id%22:%22glycosylation_predicted%22,%22offset%22:1,%22limit%22:20,%22sort%22:%22start_pos%22,%22order%22:%22asc%22%7D,%7B%22table_id%22:%22glycosylation_automatic_literature_mining%22,%22offset%22:1,%22limit%22:20,%22sort%22:%22start_pos%22,%22order%22:%22asc%22%7D,%7B%22table_id%22:%22phosphorylation%22,%22offset%22:1,%22limit%22:20,%22sort%22:%22start_pos%22,%22order%22:%22asc%22%7D,%7B%22table_id%22:%22snv_disease%22,%22offset%22:1,%22limit%22:20,%22sort%22:%22start_pos%22,%22order%22:%22asc%22%7D,%7B%22table_id%22:%22snv_non_disease%22,%22offset%22:1,%22limit%22:20,%22sort%22:%22start_pos%22,%22order%22:%22asc%22%7D,%7B%22table_id%22:%22publication%22,%22offset%22:1,%22limit%22:200,%22sort%22:%22date%22,%22order%22:%22desc%22%7D%5D%7D) provided above that is used by the frontend

```
https://api.glygen.org/protein/detail/Q8IWL2-1/?query=%7B%22paginated_tables%22:%5B%7B%22table_id%22:%22glycosylation_reported_with_glycan%22,%22offset%22:1,%22limit%22:20,%22sort%22:%22start_pos%22,%22order%22:%22asc%22%7D,%7B%22table_id%22:%22glycosylation_reported%22,%22offset%22:1,%22limit%22:20,%22sort%22:%22start_pos%22,%22order%22:%22asc%22%7D,%7B%22table_id%22:%22glycosylation_predicted%22,%22offset%22:1,%22limit%22:20,%22sort%22:%22start_pos%22,%22order%22:%22asc%22%7D,%7B%22table_id%22:%22glycosylation_automatic_literature_mining%22,%22offset%22:1,%22limit%22:20,%22sort%22:%22start_pos%22,%22order%22:%22asc%22%7D,%7B%22table_id%22:%22phosphorylation%22,%22offset%22:1,%22limit%22:20,%22sort%22:%22start_pos%22,%22order%22:%22asc%22%7D,%7B%22table_id%22:%22snv_disease%22,%22offset%22:1,%22limit%22:20,%22sort%22:%22start_pos%22,%22order%22:%22asc%22%7D,%7B%22table_id%22:%22snv_non_disease%22,%22offset%22:1,%22limit%22:20,%22sort%22:%22start_pos%22,%22order%22:%22asc%22%7D,%7B%22table_id%22:%22publication%22,%22offset%22:1,%22limit%22:200,%22sort%22:%22date%22,%22order%22:%22desc%22%7D%5D%7D
```

That will result into dublication. The default API call (without parameters) does not.

**Comment by rykahsay** [comment]
Fixed and prd is patched, please check:

<img width="1321" alt="image" src="https://github.com/user-attachments/assets/18d51125-bc02-4a74-9daa-34915726cecb">

<img width="1294" alt="image" src="https://github.com/user-attachments/assets/86e03248-db4d-4a4b-b2a1-93b29a54f128">

**Comment by katewarner** [comment]
Fixed. Many thanks
