### ISSUE TITLE
SVN evidence links dublicated or incorrect

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1773]
Related to #1772. The links to dbSNP, TOPMed and ExAC all point to the same page.

**Comment by katewarner** [comment]
ExAC no longer exists and points to gnomAD which we already have as an xref
`protein_xref_exac,ExAC,https://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=%s,rs782785872|rs782785872|rs781788150`

![image](https://github.com/user-attachments/assets/58aecd51-d84a-4d96-8b2d-1e482bb8781a)

![image](https://github.com/user-attachments/assets/5d10cb16-5070-4eae-976b-8f0033a29949)

**Comment by katewarner** [comment]
xrefs updated so should be fixed
