### ISSUE TITLE
Invalid protein IDs end up as Oops

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1776]
Invalid protein IDs:

https://www.glygen.org/protein/Q96BV4

end up as  the Oops error message. That should result into a normal error message as with glycans:

https://www.glygen.org/glycan/G179DH

**Comment by sujeetvkulkarni** [comment]
@rykahsay 
Backend sends internal server error (500) in case of invalid protein id in protein details api response. 
API: https://api.glygen.org/protein/detail/Q96BV4

![Screenshot 2024-09-20 at 10 55 18 AM](https://github.com/user-attachments/assets/f6915c3e-b4c5-48bf-9faf-06023e38ef50)

Backend should send proper error response.

@ReneRanzinger does this need to be resolved in 2.6 too?

**Comment by ReneRanzinger** [comment]
2.7 - its rare that somebody will run into this.

**Comment by rykahsay** [comment]
I have fixed it and patched prd. It says it is replaced by P99999-1  --- strange accession

<img width="497" alt="image" src="https://github.com/user-attachments/assets/cb26aaf1-0952-4cf3-8ef8-0641a547aafb">

**Comment by sujeetvkulkarni** [comment]
Ha ha... where to did you get Q96BV4 - accession from...it is replaced  by P99999-1 which is valid one. I thought it was a mistake.

**Comment by ReneRanzinger** [comment]
* https://www.glygen.org/protein/Q9

That is not right is that a substring match?

* https://www.glygen.org/protein/Q96BN
* https://www.glygen.org/protein/ABC

**Comment by rykahsay** [comment]
Tried to fix, patched prd:

<img width="519" alt="image" src="https://github.com/user-attachments/assets/310cb2e5-2a01-4a3b-94ee-01377e7f1735">
