### ISSUE TITLE
Please process the protein datasets for 2.7

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1777]
Please process the following downloaded protein datasets for 2.7. The EBI and NCBI datasets include the new organism cow.

/data/projects/glygen/downloads/genomics_england/current
 /data/projects/glygen/downloads/alliance_genome/current
/data/projects/glygen/downloads/mgi/current
/data/projects/glygen/downloads/mondo/current
/data/projects/glygen/downloads/ebi/current
/data/projects/glygen/downloads/ncbi/refseq/current
/data/projects/glygen/downloads/do/current

**For the EBI downloads:** 
As discussed in the other ticket, due to the problems with retrieving the ensembl data for yeast, we're going to use the yeast download files from 2.6 to generate the yeast datasets for 2.7 (#1768). I've copied the following yeast download files from the 2.6 download folder `2024_06_20` to the `ebi/current` folder, that way you don't have to change the input path of your script for ebi datasets.
```
accession-history-saccharomyces-cerevisiae.tsv
dbSNP-saccharomyces-cerevisiae.tsv
statistics-saccharomyces-cerevisiae.json
uniprot-proteome-saccharomyces-cerevisiae.nt
```
According to your new script for checking the downloads, the human, mouse and fruitfly nt files are displaying a large decrease in the resource predicate e.g. 
```
[k.warner1@glygen-vm-dev glygen]$ cat logs/uniprot-proteome-mus-musculus.nt.stat.log |sort -nr |head
30304,decreased,964662,994966,<http://purl.uniprot.org/core/Resource>
```` 
But when I looked at these individual resources in the nt files, so pfam, prosite and smart, I can't find a large decrease in the number of lines with these resources. 
```

[k.warner1@glygen-vm-dev ~]$ grep 'prosite' /data/projects/glygen/downloads/ebi/current/uniprot-proteome-mus-musculus.nt | wc -l
91447
[k.warner1@glygen-vm-dev ~]$ grep 'prosite' /data/projects/glygen/downloads/ebi/2024_06_20/uniprot-proteome-mus-musculus.nt | wc -l
91320
[k.warner1@glygen-vm-dev ~]$ grep 'pfam' /data/projects/glygen/downloads/ebi/2024_06_20/uniprot-proteome-mus-musculus.nt | wc -l
145243
[k.warner1@glygen-vm-dev ~]$ grep 'pfam' /data/projects/glygen/downloads/ebi/current/uniprot-proteome-mus-musculus.nt | wc -l
145317
[k.warner1@glygen-vm-dev ~]$ grep 'smart' /data/projects/glygen/downloads/ebi/2024_06_20/uniprot-proteome-mus-musculus.nt | wc -l
37572
[k.warner1@glygen-vm-dev ~]$ grep 'smart' /data/projects/glygen/downloads/ebi/current/uniprot-proteome-mus-musculus.nt | wc -l
37593
```
Jie tried regenerating the downloads but got the same results so all I can think is that Preethi updated her scripts to tidy up some of the data she provides. Also these resources (pfam, prosite and smart) use predictions so it may be that some of them have been removed from UniProt. If you would like me to look into this more let me know, otherwise please proceed with the processing.

**Comment by rykahsay** [comment]
Is this done, or do I need to do anything?

**Comment by katewarner** [comment]
It's done thank you
