### ISSUE TITLE
Rename cross reference category

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1778]
Protein details page -> "Cross References" section -> "Glycan" category

Rename the category to "Glycomics"

**Comment by sujeetvkulkarni** [comment]
Need to change Protein/Glycan details  -> "Cross References" section -> "Glycan" category
to "Glycomics"

Glycan details:
https://www.glygen.org/glycan/G17689DH#Cross-References
API: https://api.glygen.org/glycan/detail/G17689DH/

![Screenshot 2024-12-03 at 10 49 10 AM](https://github.com/user-attachments/assets/f074755c-5e0e-4f48-8bbe-5cfe2a303927)

Protein details:
https://tst.glygen.org/protein/P14210-1#Cross-References
API: https://api.tst.glygen.org/protein/detail/P14210-1/

![Screenshot 2024-12-03 at 10 45 19 AM](https://github.com/user-attachments/assets/67785f22-8738-4889-89c8-bf7b88f2bb00)

**Comment by rykahsay** [comment]
<img width="1432" alt="image" src="https://github.com/user-attachments/assets/7e285a83-62a9-40bd-8ee9-626a59f164fe" />

<img width="1375" alt="image" src="https://github.com/user-attachments/assets/b5c3f4a6-0608-4bae-8e68-137f0cf8bdcc" />
