### ISSUE TITLE
Expression tab/label changes on frontend

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#178]
@ReneRanzinger @sujeetvkulkarni @rykahsay @kmartinez834 

These are sample types in the data - cell_line, tissue, cell, bodily_fluid, organelle, anatomical_stucture, artificial_structure

My proposal is to condense 
    cell_line, cell > Cell/Cell Line category
    tissue,bodily_fluid, organelle, anatomical_stucture, artificial_structure > Tissue/Bodily Fluid
    (we have few entries for organelle, anatomical_stucture, artificial_structure and they are closely related to tissue)

****Open to Changes****

Here are the basic mockups based on my proposal
**For Glycan Expression** (https://tst.glygen.org/glycan/G17689DH#Expression)

![image](https://user-images.githubusercontent.com/25825266/227615706-addfe48d-b79d-490d-83f1-8ff566feb8bf.png)

![image](https://user-images.githubusercontent.com/25825266/227580276-a977010a-4d41-4f3a-a63d-69d9af9bec00.png)

**For Glycan Expression on Publication Detail** (https://glygen.org/publication/PubMed/8407880#Expression)

![image](https://user-images.githubusercontent.com/25825266/227580511-c6234026-f2d0-4630-a8eb-f1b25e0fb4ae.png)

![image](https://user-images.githubusercontent.com/25825266/227580576-89fd0d0b-d407-4f16-bb50-6aaddb761ef4.png)

**Note - There is no change required for Protein Expression Tissue on the Protein Detail Page.**

I think you would need mapping of names space to tabs/label. I have compiled one but need to confirm with @rykahsay 

| API_namespace | tab/label           |
| ------------- | ------------------- |
| OMIT          | Tissue/Bodily Fluid |
| CVCL          | Cell/Cell Line      |
| UBERON        | Tissue/Bodily Fluid |
| BTO           | Tissue/Bodily Fluid |
| MeSH          | Tissue/Bodily Fluid |
| NCIT          | Tissue/Bodily Fluid |
| EFO           | Tissue/Bodily Fluid |
| CL            | Cell/Cell Line      |

**Comment by ReneRanzinger** [comment]
I am fine with this. @sujeetvkulkarni lets make the label changes. @jeet-vora lets bring it up during the next main meeting to see if Raja or Mike have a better suggestion for the combined label.

**Comment by sujeetvkulkarni** [comment]
c17cd800e322f151d76a3f12f04fccc740e1758d
