### ISSUE TITLE
Information request: GLYCAM extension for format converter or glycan search

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1781]
Related to #1780: Just as an information request. How much effort would be needed to:
* add a GLYCAM to WURCS (or GlycoCT) option to the format converter on glyomics?
* add a GLYCAM option to the structure and sub-structure search container?

**Comment by ReneRanzinger** [comment]
Hi Rene,

I'm able to produce a condensed IUPAC, but I'm not sure how to encode derivatives and there aren't docs that I can find:
All(b1-3)[Neu5Ac(a2-6)Gal(b1-4)Glc[3S](b1-2)Alt(a1-4)][Tal[2S,3Me](a1-6)Man(a1-6)]Man(b1-4)Gul[6Ac](b1-4)GlcNAc(b1-
That's a mixture of IUPAC condensed with GLYCAM condensed for the derivatives. If you're familiar with the format for derivatives in IUPAC condensed please let me know how. I only need to handle Acetyl, Methyl or Sulfate groups.

I checked https://api.glygen.org/ and it looks like I should generate a glytoucan ID to perform a glycan search.
@Dan and @Rob, do you know what information you want from GlyGen? There is a lot of possible info to show a user. Here is an example response:

https://api.glygen.org/glycan/detail/G17689DH/

Best,
Oliver Grant

**Comment by ReneRanzinger** [comment]
Hi,

derivatives on an example of position 2 on mannose:

Methyl: Man2Me
Acetyl: Man2Ac
Sulfate: Man2S

Combinations: Man2S3Me

GlyGen APIs:
If you use the GlycanFormatConverter API it will you give the GlyTouCan ID as part of the response:

{"id":"G20624LQ","wurcs":"...

If the sequence does not have an ID:

{"message":"Accession not found.","WURCS":"...

But in the latter case you will not find it in GyGen anyway. Also keep in mind that GlyGen has a focus on certain species. There are Glycans with GlyTouCanIDs that are not in GlyGen.

Information selection:
You can look at the JSON response Oliver shared or you can look at the corresponding webpage that is rendered from this JSON response:
https://www.glygen.org/glycan/G17689DH

Best,
  René

**Comment by ReneRanzinger** [comment]
Oliver,

We also looked into this for adding Glycam format to our converter. That is doable but due to other commitments will take several months to implement, test and release. If you decide to go the route via generating IUPACcondensed, using GlyCanFormatConverter API to get wurcs/GlyTouCanID and using GlyGen API to retrieve information ... please let me know. In that case we do not have to implement this solution.

Best,
  René

**Comment by ReneRanzinger** [comment]
We talked about using GlyLookup instead of converter on our side. Nathan will provide a timeline since it will take several months till we actual can work on this.

**Comment by gitoliver** [comment]
I'm able to produce Iupac condensed now from our underlying software (gmml):
Index ordered GLYCAM condensed:

`DManpa1-2DManpa1-2DManpa1-3[DManpa1-2DManpa1-3[DManpa1-2DManpa1-6]DManpa1-6]DManpb1-4DGlcpNAcb1-4DGlcpNAc[2Ac,3Me,6S]b1-OH`

Can also be written as condensed IUPAC:

`Man(a1-2)Man(a1-2)Man(a1-3)[Man(a1-2)Man(a1-3)[Man(a1-2)Man(a1-6)]Man(a1-6)]Man(b1-4)GlcNAc(b1-4)GlcNAc2Ac3Me6S(b1-`

I'll just have this be returned automatically in every request to our carbohydrate builder. From this we can do the API chaining to get the GlyTouCanID for querying Glygen.

**Comment by ReneRanzinger** [comment]
Ok, in this case we can close the ticket since you found another way to get what you want.

@gitoliver just one comment. GlcNAc2Ac3Me6S that should not be possible. Since GlcNAc has a NAc at position 2. It can not have a 2Ac as well. But it probably was just a bad example.

**Comment by edwardsnj** [comment]
> Man(a1-2)Man(a1-2)Man(a1-3)[Man(a1-2)Man(a1-3)[Man(a1-2)Man(a1-6)]Man(a1-6)]Man(b1-4)GlcNAc(b1-4)GlcNAc2Ac3Me6S(b1-

FYI, minus the wacky reducing end monosaccharide, this form of IUPAC sequence is currently supported by the GlyLookup web-site and web-service.

Paste: 

  Man(a1-2)Man(a1-2)Man(a1-3)[Man(a1-2)Man(a1-3)[Man(a1-2)Man(a1-6)]Man(a1-6)]Man(b1-4)GlcNAc(b1-4)GlcNAc(b1-

into the dialog box here: 

  http://glylookup.glyomics.org/

See: 

  https://glylookup.glyomics.org/?task_id=58abdd6add97864c51fcbcc8087310f78342444aee83f03ce412

JSON response from the web-service is here:

  https://glylookup.glyomics.org/retrieve?task_id=58abdd6add97864c51fcbcc8087310f78342444aee83f03ce412

Notice that the GlyTouCan accession is supplied, and if it in GlyGen, this is indicated too. Let me know if there are reasonable classes of IUPAC sequences that fail, and I'll look at how to add them.

I'll attach an example script you can use as a client for the web-service (documentation at glylookup.glyomics.org needs updating).

**Comment by edwardsnj** [comment]
Send IUPAC sequences, one per line, into standard input.

[submit.py.gz](https://github.com/user-attachments/files/17211750/submit.py.gz)
