### ISSUE TITLE
Update isoform sections for proteins from non-vertebrate species

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1782]
Related to #1762. 

When you create the "Ensembl Transcript" and "Ensembl Peptide" sections on the protein pages of arabidopsis, fruitfly, yeast and sarscov2 e.g.

https://api.glygen.org/protein/detail/P07663-1
![image](https://github.com/user-attachments/assets/180dabea-f5a7-4797-8e4b-ec40e84cfc5b)

For arabidopsis, fruitfly, yeast and sarscov2 proteins, change the database url in these sections to the following:
```
protein_xref_ensembl_arabidopsis,ENSEMBL,https://www.ensemblgenomes.org/id/%s,AT1G14760|AT4G36540|AT5G15900
protein_xref_ensembl_fruitfly,ENSEMBL,https://www.ensemblgenomes.org/id/%s,FBgn0052803|FBgn0051155|FBgn0028996
protein_xref_ensembl_yeast,ENSEMBL,https://www.ensemblgenomes.org/id/%s,YBL079W|YPL060W|YOL064C
protein_xref_ensembl_sarscov2,ENSEMBL, https://covid-19.ensembl.org/Sars_cov_2/Gene/Summary?g=%s,ENSSASG00005000005|ENSSASG00005000004|ENSSASG00005000013
```

**Comment by rykahsay** [comment]
Done! They will look like this after we push to tst, please check after I push:

<img width="1383" alt="image" src="https://github.com/user-attachments/assets/7ac204f3-9287-42a2-8a4f-cd1dcb154108">

**Comment by katewarner** [comment]
Checked on tst and it's fixed
