### ISSUE TITLE
Update isoform mapper container

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1784]
@jieluo321 put the new version of the isoform mapper on docker hub. 

```
The tool is now in my docker repository. The new image includes data for cow (bovine)
```

We need to update the container, either now if the update is non-critical and testing is quick for with the 2.7 release.

**Comment by katewarner** [comment]
@rykahsay 
https://hub.docker.com/repository/docker/jieluo321/mapper-java-jar/general

**Docker Pull Command:** docker pull jieluo321/mapper-java-jar

**Comment by rykahsay** [comment]
@jieluo321 ... here is what I am using now, please share the new image information on dockhub

```
docker pull ebiglygen/mapper-java-jar:basic
```

**Comment by jieluo321** [comment]
https://hub.docker.com/layers/jieluo321/mapper-java-jar/basic/images/sha256-e90d9190f6e7b348127b999107b9749dcc1987555e388256fbe9db9cbce14f4e?context=repo
Docker Pull Command: docker pull jieluo321/mapper-java-jar:basic

**Comment by rykahsay** [comment]
Done. @ReneRanzinger  ... since "glygen/isoform-mapper" is empty, I have used " jieluo321/mapper-java-jar:basic"
