### ISSUE TITLE
Update download_summary.py script

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1790]
Please update the `download_summary.py` script so that if the `current_folder` and `previous_folder` columns are identical is produces an error message in the `error_flag` column. 

For example, in the most recent download_summary output (see below) the `current_folder` and `previous_folder` for Refseq are identical i.e. `/data/projects/glygen/downloads/ncbi/refseq/2024_06_24/` so in these cases it would be great if there was an `error_flag` that says some like "Download failed: no new download folder" 	

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/kawar/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/kawar/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">

resource | file_name | previous_folder | current_folder | previous_ctime | current_ctime | ctime_flag | previous_size | current_size | size_flag | permissions_flag | folder_status | error_flag
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ncbi | refseq_protein_all_3702.gpff | /data/projects/glygen/downloads/ncbi/refseq/2024_06_24/ | /data/projects/glygen/downloads/ncbi/refseq/2024_06_24/ | 07/30/2024, 11:40:31 | 07/30/2024, 11:40:31 | same | 352229135 | 352229135 |   |   | same |  
ncbi | refseq_protein_all_9606.gpff | /data/projects/glygen/downloads/ncbi/refseq/2024_06_24/ | /data/projects/glygen/downloads/ncbi/refseq/2024_06_24/ | 09/05/2024, 10:41:06 | 09/05/2024, 10:41:06 | same | 1322064964 | 1322064964 |   |   | same |  
ncbi | refseq_protein_all_9823.gpff | /data/projects/glygen/downloads/ncbi/refseq/2024_06_24/ | /data/projects/glygen/downloads/ncbi/refseq/2024_06_24/ | 09/05/2024, 10:41:06 | 09/05/2024, 10:41:06 | same | 279404223 | 279404223 |   |   | same |  
ncbi | refseq_protein_all_10090.gpff | /data/projects/glygen/downloads/ncbi/refseq/2024_06_24/ | /data/projects/glygen/downloads/ncbi/refseq/2024_06_24/ | 09/05/2024, 10:41:06 | 09/05/2024, 10:41:06 | same | 660199875 | 660199875 |   |   | same |  
ncbi | refseq_protein_all_viral.gpff | /data/projects/glygen/downloads/ncbi/refseq/2024_06_24/ | /data/projects/glygen/downloads/ncbi/refseq/2024_06_24/ | 09/05/2024, 10:41:06 | 09/05/2024, 10:41:06 | same | 2020643689 | 2020643689 |   |   | same |  
ncbi | refseq_protein_all_44689.gpff | /data/projects/glygen/downloads/ncbi/refseq/2024_06_24/ | /data/projects/glygen/downloads/ncbi/refseq/2024_06_24/ | 07/01/2024, 20:42:31 | 07/01/2024, 20:42:31 | same | 95995620 | 95995620 |   |   | same |  
ncbi | refseq_protein_all_7227.gpff | /data/projects/glygen/downloads/ncbi/refseq/2024_06_24/ | /data/projects/glygen/downloads/ncbi/refseq/2024_06_24/ | 07/01/2024, 19:25:53 | 07/01/2024, 19:25:53 | same | 480816836 | 480816836 |   |   | same |  
ncbi | refseq_protein_all_10116.gpff | /data/projects/glygen/downloads/ncbi/refseq/2024_06_24/ | /data/projects/glygen/downloads/ncbi/refseq/2024_06_24/ | 09/05/2024, 10:41:06 | 09/05/2024, 10:41:06 | same | 430973543 | 430973543 |   |   | same |  
ncbi | refseq_protein_all_9031.gpff | /data/projects/glygen/downloads/ncbi/refseq/2024_06_24/ | /data/projects/glygen/downloads/ncbi/refseq/2024_06_24/ | 07/01/2024, 17:28:31 | 07/01/2024, 17:28:31 | same | 615098329 | 615098329 |   |   | same |  
ncbi | refseq_protein_all_559292.gpff | /data/projects/glygen/downloads/ncbi/refseq/2024_06_24/ | /data/projects/glygen/downloads/ncbi/refseq/2024_06_24/ | 07/01/2024, 20:30:52 | 07/01/2024, 20:30:52 | same | 39798105 | 39798105 |   |   | same |  

</body>

</html>

FYI @ubhuiyan

**Comment by rykahsay** [comment]
@ubhuiyan ... any update on this?

**Comment by ubhuiyan** [comment]
@rykahsay I ran the script overnight and it appears to have downloaded successfully. Please proceed with processing: 

```
[sbhuiyan28@glygen-vm-dev current]$ ll /data/projects/glygen/downloads/ncbi/refseq/current/
total 105353989
-rwxrwxr-x. 1 sbhuiyan28 glygen    12316502 Sep 24 14:04 cow.1.protein.faa.gz
-rwxrwxr-x. 1 sbhuiyan28 glygen   279266502 Sep 24 14:04 cow.1.protein.gpff
-rwxrwxr-x. 1 sbhuiyan28 glygen    65220886 Sep 13 00:54 fungi.10.protein.faa.gz
-rwxrwxr-x. 1 sbhuiyan28 glygen   840765162 Sep 13 00:54 fungi.10.protein.gpff
-rwxrwxr-x. 1 sbhuiyan28 glygen    55820612 Sep 13 00:54 fungi.11.protein.faa.gz
-rwxrwxr-x. 1 sbhuiyan28 glygen   754321505 Sep 13 00:54 fungi.11.protein.gpff
```

**Comment by rykahsay** [comment]
@katewarner  You can close this ticket
