### ISSUE TITLE
GeneID xref missing from current EBI downloads

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1791]
### command gives no rows for current download
```
$ cat downloads/ebi/current/uniprot-proteome-sars-cov-2.nt | grep " <http://purl.uniprot.org/core/database> " | grep GeneID

```

### command gives rows for old downloads
```
$ cat downloads/ebi/2024_06_20/uniprot-proteome-sars-cov-2.nt | grep " <http://purl.uniprot.org/core/database> " | grep GeneID

<http://purl.uniprot.org/geneid/43740578> <http://purl.uniprot.org/core/database> <http://purl.uniprot.org/database/GeneID> .
<http://purl.uniprot.org/geneid/43740568> <http://purl.uniprot.org/core/database> <http://purl.uniprot.org/database/GeneID> .
<http://purl.uniprot.org/geneid/43740569> <http://purl.uniprot.org/core/database> <http://purl.uniprot.org/database/GeneID> .
<http://purl.uniprot.org/geneid/43740574> <http://purl.uniprot.org/core/database> <http://purl.uniprot.org/database/GeneID> .
<http://purl.uniprot.org/geneid/43740570> <http://purl.uniprot.org/core/database> <http://purl.uniprot.org/database/GeneID> .
<http://purl.uniprot.org/geneid/43740571> <http://purl.uniprot.org/core/database> <http://purl.uniprot.org/database/GeneID> .
<http://purl.uniprot.org/geneid/43740575> <http://purl.uniprot.org/core/database> <http://purl.uniprot.org/database/GeneID> .
<http://purl.uniprot.org/geneid/43740572> <http://purl.uniprot.org/core/database> <http://purl.uniprot.org/database/GeneID> .
<http://purl.uniprot.org/geneid/43740573> <http://purl.uniprot.org/core/database> <http://purl.uniprot.org/database/GeneID> .
<http://purl.uniprot.org/geneid/43740577> <http://purl.uniprot.org/core/database> <http://purl.uniprot.org/database/GeneID> .
<http://purl.uniprot.org/geneid/43740576> <http://purl.uniprot.org/core/database> <http://purl.uniprot.org/database/GeneID> .
```

**Comment by katewarner** [comment]
@jieluo321 

It looks like the NIH GeneIDs are missing in the latest uniprot-proteome-sars-cov-2.nt download (see above), and I can see that they are no longer provided in the UniProt entries for this species. 

Is there any way we can retrieve the GeneID data for this species for this release? Or is it too late in the UniProt release and we should we use the 2.6 download as we did for yeast?

**Comment by jieluo321** [comment]
https://www.uniprot.org/uniprotkb?query=%28xref%3Ageneid-43740578%29
https://www.uniprot.org/uniprotkb?query=%28xref%3Ageneid-43740568%29
https://www.uniprot.org/uniprotkb?query=%28xref%3Ageneid-43740569%29
https://www.uniprot.org/uniprotkb?query=%28xref%3Ageneid-43740574%29
https://www.uniprot.org/uniprotkb?query=%28xref%3Ageneid-43740570%29

I checked first 5 geneid as above. There is no entry mapped in current public release

**Comment by jieluo321** [comment]
However, i checked data in coming release (2024_05), the xref data is there.

I will discuss with our uniprot team why these cross references are missing in 2024_04

**Comment by jieluo321** [comment]
There are the new gene Ids. It will appear in the coming public release (2nd October). I will generate new glygen data after we have done public release

**Comment by katewarner** [comment]
@jieluo321 Okay thank you for letting us know. We're falling behind with the 2.7 release so I think we will use the 2.6 file as we did for yeast

**Comment by katewarner** [comment]
@rykahsay For 2.7 I think we should go ahead and use the 2.6 files for sarscov2 as we did for yeast otherwise we'd have to delay it to the 2nd of October. I've copied the following sarscov2 download files from the 2.6 download folder `2024_06_20` to the `ebi/current` folder, that way you don't have to change the input path of your script for ebi datasets. Please  go ahead and try to re-process these downloads.

```
accession-history-sars-cov-2.tsv 
statistics-sars-cov-2.json
uniprot-proteome-sars-cov-2.nt
```
