### ISSUE TITLE
dataset master list not edited to reflect addition of bovine

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1797]
Please document this:
When you add a new species, you can use the following commands to automatically add the species short name to dataset-masterlist.json:

```
$ cd /software/glygen/
$ python3 update-datamasterlist.py -s bovine
```

Then, manually edit generated/misc/dataset-masterlist.json to remove "bovine" from datasets that you know shouldn't apply.

I am doing all this for bovine, but please document this

**Comment by katewarner** [comment]
@rykahsay Following the documentation we added the new bovine dataset information to the dataset-masterlist.csv file so that you can push a bulk update to the dataset-masterlist.json file. Do you want us to make you a ticket when the csv file is ready for the next release?

**Comment by rykahsay** [comment]
From next release, once you finish creating/updating dataset-masterlist.csv, all you need to do is run the following:

```
$ cd /software/glygen/
$ python3 update-datamasterlist.py -s bovine
```

Please add the above to the documentation and give me back the ticket

**Comment by katewarner** [comment]
Okay thank you. I've added the protocol to the documentation.
