### ISSUE TITLE
Edit list_int csv files under generated/misc/

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1798]
The list_init API response depends CSV files "generated/misc/list_init_categories.csv" and "generated/misc/list_init_fields.csv" I have initiated that you will start maintain. Please update those files based on the spreadsheet Sujeeet shared and assign back the ticket to me when you are done

```
$ head generated/misc/list_init_fields.csv
record_type,field_id,field_label,field_order,is_default,is_immutable,category_id_list
protein,uniprot_canonical_ac,UniProtKB Accession,1,true,true,General
protein,mass,Chemical Mass (Da),2,true,false,General
protein,protein_name,UniProtKB Name,3,true,false,General
protein,gene_name,Gene Name,4,true,false,General
protein,organism,Organism,5,true,false,General
protein,refseq_name,RefSeq Name,6,true,false,General
protein,refseq_ac,RefSeq Accession,7,true,false,General
protein,tax_id,Taxonomy ID,8,false,false,General
protein,missing_score,missing_score,9,false,false,General

$ head generated/misc/list_init_categories.csv 
record_type,cat_id,cat_label,cat_order
protein,General,General,1
protein,Biomarkers,Biomarkers,1
protein,Diseases,Diseases,1
protein,Function,Function,1
protein,Glycation,Glycation,1
protein,Glycosylation,Glycosylation,1
protein,Interactions,Interactions,1
protein,Mutagenesis,Mutagenesis,1
protein,Mutagensis,Mutagensis,1

```

**Comment by ubhuiyan** [comment]
@rykahsay I have copied a backup file in: `/generated/misc/backup_list_innit_2.7/`

I have edited `list_init_categories.csv` and `list_init_fields.csv` as best as I could. There are some rows for the `field_id` I was unsure of. I tried looking through api.glygen.org to find the correct values but if you wouldn't mind filling in the ones I couldn't figure out. I'd appreciate it. 

I also noticed some fields have similar rows but are different by `category_id_list`. For any that are similar, I tried to give them the same `description`.  I think I got them all, but there's a chance I missed a few. 

Lastly, I noticed some rows had multiple values in `category_id_list`, so I separated these with a pipe (|).

**Comment by ubhuiyan** [comment]
@rykahsay You can proceed.

**Comment by sujeetvkulkarni** [comment]
@ubhuiyan  Check - order, name, default true, no category assigned etc cases and update them.

**Comment by ubhuiyan** [comment]
@rykahsay @sujeetvkulkarni There are a few categories that are separated by a pipe. Currently, I have them looking like this:

```
[sbhuiyan28@glygen-vm-dev ~]$ head /data/projects/glygen/generated/misc/list_init_categories.csv 
record_type,cat_id,cat_label,cat_order
protein,Annotation|Protein Modification,Annotation|Protein Modification,1
```

Is this okay or do you suggest something else?

**Comment by rykahsay** [comment]
@ubhuiyan ... in file "list_init_fields.csv", you have duplicate rows (shown below containing save value for "record_type" and "field_id" combo). A given "record_type" and "field_id" combo show have only one row, and multiple categories should be assigned to it using "|" separator.

Please fix this now


```
glycan,classification
glycan,glycam
glycan,glycoct
glycan,glytoucan_ac
glycan,mass
glycan,mass_pme
glycan,motifs
glycan,number_enzymes
glycan,number_monosaccharides
glycan,number_proteins
glycan,publication
glycan,species_list
glycan,wurcs

protein,gene_name
protein,protein_name
protein,refseq_name
protein,total_n_glycosites
protein,total_o_glycosites
protein,uniprot_canonical_ac

site,end_pos
site,glycation
site,glycosylation
site,mutagenesis
site,phosphorylation
site,protein_name
site,residue
site,snv
site,start_pos
site,uniprot_canonical_ac
```

**Comment by ubhuiyan** [comment]
@rykahsay I have applied the changes. Please Check. 

I also gave each category it's own row within the `list_init_categories.csv ` file: 

```
[sbhuiyan28@glygen-vm-dev ~]$ head /data/projects/glygen/generated/misc/list_init_categories.csv 
record_type,cat_id,cat_label,cat_order
protein,Annotation,Annotation,1
protein,Protein Modifiction,Protein Modification,2
protein,Biomarkers,Biomarkers,3
protein,Diseases,Diseases,4
protein,Function,Function,5
protein,General,General,6
protein,General|Identifier,General|Identifier,7
protein,Glycation,Glycation,8
protein,Glycosylation,Glycosylation,9
```

**Comment by rykahsay** [comment]
@jeet-vora  ... please have a look at this and work with @ubhuiyan to make sure I don't get back and forth about this again. I will not work on the blocker issue (blocking Sujeet) unless this is done properly.

**Comment by ubhuiyan** [comment]
@jeet-vora and @rykahsay I have checked the following and all looks good:

1. All headers in `field_id` are capitalized with spacing for front-end view 
2. Duplicate rows with the same `record_type` and `field_id` have been merged and rows with multiple categories have been separated with | in `category_id_list`
3. All rows that share a `field_id` but different `record_type` have matching `is_default` and `is_immutable` values 
4. `field_order` and `cat_order` are all given unique values 
5. All `category_id_list` were assigned a value, so none should show up empty 
6. Spelling was checked for both fields and categories files 

@sujeetvkulkarni Please let me know if there are any additional concerns you have. I can fix them now before Robel processes.

**Comment by ubhuiyan** [comment]
@rykahsay I have applied the changes. Please check and proceed.

**Comment by rykahsay** [comment]
@sujeetvkulkarni  ... I have updated it, please try now

**Comment by sujeetvkulkarni** [comment]
Done, closing.
