### ISSUE TITLE
human_proteoform_glycosylation_sites_unicarbkb_glycomics_study.csv contains publication w/ rat data

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#18]
PMID 34106099 is titled "N-Glycosylation in isolated rat nerve terminals"
- Change dataset to species agnostic or remove rows from this publication and create rat glycomics dataset

**Comment by kmartinez834** [comment]
@rykahsay -->

Please process the following datasets:
- human_proteoform_glycosylation_sites_unicarbkb_glycomics_study.csv
- rat_proteoform_glycosylation_sites_unicarbkb_glycomics_study.csv (✨new dataset)

src_file | changes
-- | --
generated/misc/n_sequon_info.csv | N/A
downloads/unicarbkb/current/known_unicarbkb_glycomics_study.csv | Generate files according to "species" field<br/> **Possible values:**<br/>"Homo sapiens" <br/> "Rattus norvegicus"

**Comment by rykahsay** [comment]
<img width="1374" alt="image" src="https://user-images.githubusercontent.com/20584876/224157810-cf043a89-4c8b-4567-a27d-83f928cf9eed.png">
