### ISSUE TITLE
Create a list of experimental technique terms for Mindys curation work

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#180]
For Mindy's curation effort there is a "experimental technique" column in her spreadsheet that lists for each glycan the technique used for identification. @mtiemeyer0919 will create a list of terms to use. On the first level that should be easy just to ensure that the spelling is always the same. But we also need to decide how detailed do we want to be. For example:
* MS vs LC-MS/MS, MS profile, or MS/MS
* NMR vs Cosy, Tocsy

**Comment by ReneRanzinger** [comment]
The usual suspects would be:
MS profile
MS/MS
LC-MS/MS
LC-MS
CE-MS
CE-MS/MS
CE
HPLC

**Comment by mtiemeyer0919** [comment]
Might add

NMR
GC
GC-MS
Gel filtration
Paper chromatography

-------------------------
Michael Tiemeyer
Joint Director, Complex Carbohydrate Research Center
and Center for Molecular Medicine
Distinguished Research Professor
The Department of Biochemistry and Molecular Biology
University of Georgia
315 Riverbend Rd.
Athens, GA 30602
706-542-2740 Office
706-542-4412 FAX
***@***.***
________________________________

**Comment by Mindyporterfield** [comment]
MS
MS/MS
LC-MS/MS
LC-MS
CE-MS
CE-MS/MS
CE
HPLC
GC
GC-MS

**Comment by ReneRanzinger** [comment]
@Mindyporterfield I added the list of terms to the google with the curation table.
