### ISSUE TITLE
What are these datasets? 

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1803]
I don't know who added these to dataset-masterlist.json. If they are new, where are the instructions tickets for them?

<img width="533" alt="image" src="https://github.com/user-attachments/assets/0b915374-491a-4866-927c-81f8fe7bcdfb">

<img width="436" alt="image" src="https://github.com/user-attachments/assets/0d21d07e-30cb-4ef0-891a-22c8434dd932">

**Comment by ubhuiyan** [comment]
@rykahsay I added these per Jeet's request. Here are the instructions: https://github.com/glygener/glygen-issues/issues/1751
