### ISSUE TITLE
Bad sandbox download

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1804]
```
$ cat downloads/sandbox/current/glycotree_annotated_glycans.tsv

"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4.01 Transitional//EN"" ""http://www.w3.org/TR/html4/loose.dtd"">"
"<HTML><HEAD><META HTTP-EQUIV=""Content-Type"" CONTENT=""text/html; charset=iso-8859-1"">"
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>504 Gateway Timeout ERROR</H1>
<H2>The request could not be satisfied.</H2>
"<HR noshade size=""1px"">"
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
"<BR clear=""all"">"
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
"<BR clear=""all"">"
"<HR noshade size=""1px"">"
<PRE>
Generated by cloudfront (CloudFront) HTTP3 Server
Request ID: 5X5g6Um_Hm3PL0UC2YyjTh-BQx9QCuhrIoU0D8IAIch1PPShl4lJ_Q&#x3D;&#x3D;
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

**Comment by ubhuiyan** [comment]
@rykahsay Sandbox is the last dataset I download and check. I hadn't gotten to it yesterday. I did the download again and the issue reappeared. I can figure out what is going on today. Appears we aren't being given access.

**Comment by rykahsay** [comment]
@ubhuiyan @jeet-vora ... I know it was not forgotten but my expectation of the protocol is that the downloaded files contain the expected data in them. It is part of the download task to make sure all downloaded data does not have issues like this.

**Comment by ubhuiyan** [comment]
I hadn't finished testing which is why I hadn't created a ticket for you to begin the processing.

**Comment by ubhuiyan** [comment]
@rykahsay The API link for `glycotree_annotated_glycans.tsv` is returning a 504 error. I've emailed Nathan about it, but in the meantime, I've downloaded and placed the file in `/sandbox/current/`.

@rykahsay @jeet-vora I checked the current release of `glycotree_annotated_glycans.tsv `on Nathan's GitHub. The headers are mostly the same as the previous release, except for a new caveat header with 114 rows of data. Nathan also provided a separate `glycotree_glycan_caveats.tsv` with 283 rows, all caveats, which I've also copied to `/sandbox/current/`.

@rykahsay Please proceed with processing for now. As @jeet-vora mentioned, we'll need to discuss what to do with the caveats with Nathan further.

**Comment by ubhuiyan** [comment]
@jeet-vora and @rykahsay I've updated the script to pull from the GlycanData export (the github repo). Nathan said not to download directly from sandbox. The download script works fine now.
