### ISSUE TITLE
Retire dataset human_proteoform_glycosylation_sites_o_gluc.csv  and its BCO 

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1807]
This dataset is created based on compiled/human_proteoform_glycosylation_sites_o-gluc.csv and all of the rows are failing QC. So, I am removing it from dataset-masterlist.json

```
cat logs/human_proteoform_glycosylation_sites_o_gluc.global.log
```

**Comment by jeet-vora** [comment]
@katewarner Can you check the reasons why the dataset is failing. It is a user submitted dataset for human.
We can discuss in the meeting.

**Comment by katewarner** [comment]
The original ticket for dataset creation is here: https://github.com/glygener/glygen-issues/issues/53

It's the GlyTouCan ID in the input dataset that's causing the issue. There's only one GlyTouCan ID for all sites that was provided in the raw dataset which is G71142DF (https://www.glygen.org/glycan/G71142DF). G71142DF is not in the glycan_classification.csv dataset file or a base composition, so it gets flagged as "glycan_without_glytype".

There is published evidence that Hex(1) is an O-glycan [here](https://febs.onlinelibrary.wiley.com/doi/epdf/10.1111/j.1432-1033.1997.00334.x)

**Comment by edwardsnj** [comment]
Just to reiterate my comments on the call, the GlyTouCan accession [G71142DF](https://www.glygen.org/glycan/G71142DF) is not Hex, it is Glc. There is a O-Glc core O-glycan classification (see: [GGM.001031](https://glycomotif.glyomics.org/glycomotif/GGM.001031 )) that will ultimately mark it as an O-glycan. Whether G71142DF is the correct accession here (vs G81399MY or one of the other Hex(1) candidates) is an open question. I do not anticipate it being a good idea to mark Hex reducing-end glycans (or Hex(1) glycans only) as O-glycans, but if that is the consensus, it can be done...

**Comment by ubhuiyan** [comment]
I have retired this dataset for now, and have updated the documentation regarding retiring BCOs.

**Comment by katewarner** [comment]
Issue resolved

**Comment by ReneRanzinger** [comment]
@katewarner we [planned](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B21E3DD1D-2373-4FBC-B93D-7F1C6D101737%7D&file=2024.11.06.docx&action=default&mobileredirect=true) to create a mechanism of black and white list files. Is that in place or was there a ticket create for this?

**Comment by katewarner** [comment]
> @katewarner we [planned](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B21E3DD1D-2373-4FBC-B93D-7F1C6D101737%7D&file=2024.11.06.docx&action=default&mobileredirect=true) to create a mechanism of black and white list files. Is that in place or was there a ticket create for this?

@ReneRanzinger apologies for the delay. Here's the ticket #1942

**Comment by katewarner** [comment]
I think this ticket can be closed
