### ISSUE TITLE
BioMuta not working

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1810]
<img width="1054" alt="image" src="https://github.com/user-attachments/assets/3096dc3b-0b9b-4326-9ae2-61ffbb5f6926">

**Comment by Reeya123** [comment]
@seankim658 Both Biomuta and BioXpress data searches are not working on prd. However they tend to work fine on the tst server. I noticed that API calls are not being successfully made in prd. Could this be a database connectivity issue?

**Comment by seankim658** [comment]
The docker containers weren't running. Just started them.
