### ISSUE TITLE
The human_protein_xref_cfde_gdlpa.csv dataset contains only one UniProt AC

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1812]
Please reprocess the "human_protein_xref_cfde_gdlpa.csv" dataset. The dataset should contain 18933 UniProt acs but the new dataset in `/unreviewed/human_protein_xref_cfde_gdlpa.csv' contains only one UniProt ac which has been added to all rows.

```
[k.warner1@glygen-vm-dev glygen]$ awk -F, '{print $1}' /data/shared/glygen/releases/data/v-2.6.1/reviewed/human_protein_xref_cfde_gdlpa.csv | sort -u | grep -v "uniprotkb_canonical_ac" | wc -l
18933
[k.warner1@glygen-vm-dev glygen]$ awk -F, '{print $1}' /data/projects/glygen/generated/datasets/unreviewed/human_protein_xref_cfde_gdlpa.csv | sort -u | grep -v "uniprotkb_canonical_ac" | wc -l
1
```

**Comment by rykahsay** [comment]
check now  ... should be QC'ed during part-II

**Comment by rykahsay** [comment]
Check now, this file depends on compiled/human_protein_xref_cfde_gdlpa.csv (may be it was not prepared)

**Comment by katewarner** [comment]
It's fixed thank you
