### ISSUE TITLE
Create alphafold bovine datasets

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1813]
Please create the following datasets for bovine: `bovine_protein_xref_alphafolddb.csv` and `bovine_protein_pdb_map.csv`

I realised during dataset QC that I forgot to add "bovine" to these datasets in the dataset-masterlist.json, and bovine does have alphafolddb data in the cow EBI nt files. I've now updated the datset-masterlist.json so that you can create these datasets.

**Comment by rykahsay** [comment]
Please check now

**Comment by katewarner** [comment]
Both datasets look good. Many thanks
