### ISSUE TITLE
Update menu structure

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#182]
Update menu structure according to the [proposed changes](https://docs.google.com/document/d/1uzsuTa-PBkqQHCIhO7CUZY8L8LW_Q_dCb4do_RgvXYg/edit).

**Comment by sujeetvkulkarni** [comment]
8f9e1621886a029735e29503bf28db4282bf7f36

**Comment by sujeetvkulkarni** [comment]
Other Resource - in the end with separator.

**Comment by sujeetvkulkarni** [comment]
a60c296f207f0eccabbd5adf020bc11848fcece1

**Comment by sujeetvkulkarni** [comment]
2ef420f52b4f9a7d54d90f3a8eea71bf334205fc
