### ISSUE TITLE
Caveats for glycans integration

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1821]
Integrated the caveats from Nathan into the download and we can also put them up on the data website. In this version we will not integrate them into the dataset. But starting from 2.8 we will. Send @ReneRanzinger examples for the two flavors that Nathan mentioned:
* Caveats related to enzymes
* Caveats related to glycans/monosaccharides

**Comment by ubhuiyan** [comment]
@ReneRanzinger If I remember correctly, you will be creating a front-end mockup of how this data might be presented on GlyGen? Shall I move this ticket to 2.8?

**Comment by ReneRanzinger** [comment]
@ubhuiyan If you already download them in this version can you send me a file with example records. I need to see what he has in the files for each of the two versions.

**Comment by ReneRanzinger** [comment]
**Blocker for:**
* #1874

**Comment by ubhuiyan** [comment]
@ReneRanzinger, here's an example below: 

| glytoucan_ac | residue_name               | residue_id | uniprot | gene_name | gene_id | parent_residue_id | enzyme_type | species       | caveat                                                                                      |
|--------------|----------------------------|------------|---------|-----------|---------|-------------------|-------------|----------------|---------------------------------------------------------------------------------------------|
| G00042MO     | O-glycan_b-D-GlcpNAc_157  | O157       | Q09324  | Gcnt1     | 14537   | OC                | GT          | Mus musculus  | transfer of residue O157 (b-D-GlcpNAc) by Q09324 in Mus musculus requires residue O152 (b-D-Galp) |
| G00049HA     | N-glycan_a-D-Galp_51      | N51        | P16442  | ABO       | 28      | N10               | GT          | Homo sapiens  | transfer of residue N51 (a-D-Galp) by P16442 in Homo sapiens requires residue N200 (a-L-Fucp)     |


_Let me know if you need more information._
