### ISSUE TITLE
EBI download missing file downloads/ebi/current/all_accessions.csv

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1828]
#### Current download
```
$ ls -ltr downloads/ebi/current/all_accessions.csv
ls: cannot access downloads/ebi/current/all_accessions.csv: No such file or directory
```

#### Old downloads
```
$ ls -ltr downloads/ebi/*/all_accessions.csv
-rw-r--r--. 1 rykahsay   glygen 3016906875 Mar  5  2023 downloads/ebi/2022_05/all_accessions.csv
-rwxrwxr-x. 1 jingyue.wu glygen 3075215332 May 16  2023 downloads/ebi/2023_02/all_accessions.csv
-rwxrwxr-x. 1 jeetvora   glygen 3110920232 Jul  4  2023 downloads/ebi/2023_07_11/all_accessions.csv
-rwxrwxr-x. 1 jeetvora   glygen 3155734811 Sep 17  2023 downloads/ebi/2023_10_30/all_accessions.csv
-rwxrwxr-x. 1 jeetvora   glygen 3358552385 Feb  9  2024 downloads/ebi/2024_02_19/all_accessions.csv
-rwxrwxr-x. 1 jeetvora   glygen 3358552385 Feb  9  2024 downloads/ebi/2024_02_13/all_accessions.csv
-rwxrwxr-x. 1 k.warner1  glygen 3436274832 Apr  6  2024 downloads/ebi/2024_04_08/all_accessions.csv
-rwxrwxr-x. 1 k.warner1  glygen 3623047534 Jun  3 21:04 downloads/ebi/2024_06_20/all_accessions.csv
```

**Comment by katewarner** [comment]
@jieluo321 Hi Jie, the `all_accessions.csv.gz `file in the current release appears to be empty or non-existent i.e. `https://ftp.ebi.ac.uk/pub/contrib/glygen/current_release/all_accessions.csv.gz` . 

When I click the "all_accessions.csv.gz" link on the current_release directory it should start downloading the file (as in the previous releases) but instead I get the following forbidden permission access error: 
![image](https://github.com/user-attachments/assets/e6c84368-30dc-4c32-99b4-c8955f001c5e)

**Comment by jieluo321** [comment]
File is there, but file permission is wrong. You can the file in the directory, but you cannot download it.  I changed the file permission. Now you can download.

**Comment by katewarner** [comment]
@rykahsay I've uploaded the latest `all_accessions.csv.gz` file to `downloads/ebi/current/all_accessions.csv` please let me know if there are any issues
