### ISSUE TITLE
IsoGlyp Downloads 

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1831]
- [x] arabidopsis_protein_canonicalsequences.fasta
- [x] bovine_protein_canonicalsequences.fasta
- [x] chicken_protein_canonicalsequences.fasta
- [x] dicty_protein_canonicalsequences.fasta
- [x] fruitfly_protein_canonicalsequences.fasta
- [x] hcv1a_protein_canonicalsequences.fasta
- [x] hcv1b_protein_canonicalsequences.fasta
- [x] human_protein_canonicalsequences.fasta
- [x] pig_protein_canonicalsequences.fasta
- [x] rat_protein_canonicalsequences.fasta
- [x] mouse_protein_canonicalsequences.fasta
- [x] sarscov1_protein_canonicalsequences.fasta
- [x] sarscov2_protein_canonicalsequences.fasta
- [x] yeast_protein_canonicalsequences.fasta

Check off completed organisms.

**Comment by ubhuiyan** [comment]
## Isoglyp Dataset QC

Here's the updated table with an additional column showing the difference between the two values (2.7 minus 2.6) for each species:

| Species     | 2.6 Rows     | 2.7 Rows    | Difference (2.7 - 2.6) |
|-------------|----------|----------|------------------------|
| Human       | 1567732  | 1571084  | 3352                   |
| Mouse       | 1643494  | 1645215  | 1721                   |
| Rat         | 1618958  | 1620125  | 1167                   |
| Chicken     | 1471113  | 1471113  | 0                      |
| Pig         | 1572042  | 1570285  | -1757                  |
| Fruitfly    | 1040996  | 1040866  | -130                   |
| Dicty       | 1073423  | 1073423  | 0                      |
| Sarscov1    | 2010     | 2010     | 0                      |
| Sarscov2    | 2055     | 2055     | 0                      |
| Arabidopsis | 1577244  | 1576870  | -3734                  |
| Bovine      | X        | 1794020  | N/A                    |
| Yeast       | 437799   | 437799   | 0                      |
| HCV1a       | 435      | 435      | 0                      |
| HCV1b       | 445      | 445      | 0                      |

**Comment by jeet-vora** [comment]
@ubhuiyan 
No need to change any EVP value in the code.

Just compare the rows from 2.7 tool output (Not final dataset) with EVP max value greater than 10 and then compare the rows of EVP max value greater than 10 from 2.6 tool output. You can also compare the volume of 2.7 and 2.6.

Once done assign the ticket to Robel

**Comment by ubhuiyan** [comment]
## Max Threshold of 10

| Species       | 2.7 Rows | 2.6 Rows | Difference (2.7 - 2.6) |
|---------------|----------|----------|------------------------|
| Human         | 7122     | 7087     | 35                     |
| Mouse         | 6430     | 6422     | 8                      |
| Rat           | 6363     | 6360     | 3                      |
| Chicken       | 5572     | 5572     | 0                      |
| Pig           | 6648     | 6659     | -11                    |
| Fruitfly      | 4377     | 4377     | 0                      |
| Dicty         | 2981     | 2981     | 0                      |
| Sarscov1      | 3        | 3        | 0                      |
| Sarscov2      | 1        | 1        | 0                      |
| Arabidopsis   | 3466     | 3467     | -1                     |
| Bovine        | 7570     | X        | X                      |
| Yeast         | 877      | 877      | 0                      |
| HCV1a         | 4        | 4        | 0                      |
| HCV1b         | 3        | 3        | 0                      |

**Comment by jeet-vora** [comment]
@ubhuiyan Did @rykahsay Robel take a look at the ticket. I would assign this to him and not close. If he is ok and looked at it then close.

**Comment by ubhuiyan** [comment]
@jeet-vora I linked this ticket in the ticket to Robel to process.
