### ISSUE TITLE
Introduction into testing with Selenium

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1839]
Provide an introduction for testing with Selenium to @katewarner, @ubhuiyan and @Mindyporterfield. The aim for 2.7 is to record as many test cases and put them into a github repository. In 2.8+ these will be used to automatically test some frontend features. That hopefully will help to shrink down the time of frontend testing (in 2.8+). In 2.7 it will be additional work.

**Comment by sujeetvkulkarni** [comment]
Done.
