### ISSUE TITLE
Testing for Jingyue

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#184]
1. Read the documentation for the following QC scripts located in the [data_integration.docx](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/[data_integration.docx](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/data_integration.docx?d=w0c84e59c4be6494d91cc017661cc9944&csf=1&web=1&e=gbRflS&nav=eyJoIjoiMTY0NDg1NjE5OCJ9)?d=w0c84e59c4be6494d91cc017661cc9944&csf=1&web=1&e=gbRflS&nav=eyJoIjoiMTY0NDg1NjE5OCJ9) in Sharepoint. 

2. Run the following commands according to the document and save the results in your home directory:

- [x] Check citation datasets (`check-citation-datasets.py`)
- [x] Dataset testing (`check-dataset-group.py`)
  - glycan
  - protein
  - proteoform

3. Tag @jeet-vora and I when this is done and we can give more instructions.

**Comment by JingyueWu** [comment]
@kmartinez834 @jeet-vora Output after running `check-citation-datasets.py` in `/software/glygen/`

<img width="1059" alt="Screen Shot 2023-03-31 at 3 18 07 PM" src="https://user-images.githubusercontent.com/61590108/229209986-72c5871c-d168-43d8-8bf6-548a32e5fc45.png">

<img width="1045" alt="Screen Shot 2023-03-31 at 3 18 34 PM" src="https://user-images.githubusercontent.com/61590108/229210069-21f75713-8100-47fc-8cf2-f890d3e435b4.png">

Robel taught me to report the bizarre ones (i.e. number goes down that is unexplainable). What are those numbers going down? Please see following: 

`16,human_proteoform_phosphorylation_sites_iptmnet.csv,22129,human_proteoform_citations_phosphorylation_sites_iptmnet.csv,22113`

`1,mouse_proteoform_phosphorylation_sites_iptmnet.csv,4424,mouse_proteoform_citations_phosphorylation_sites_iptmnet.csv,4423`

`1,human_protein_biomarkers.csv,300,human_protein_citations_biomarkers.csv,299`

`2,glycan_masterlist.csv,1261,glycan_citations_glytoucan.csv,1259`

`1,human_proteoform_glycosylation_sites_glyconnect.csv,420,human_proteoform_citations_glycosylation_sites_glyconnect.csv,419`

`1,rat_protein_function_refseq.csv,13578,rat_protein_citations_refseq.csv,13577`

`30,human_protein_function_refseq.csv,57557,human_protein_citations_refseq.csv,57527`

`4,human_protein_mutation_somatic.csv,397,human_protein_citations_mutation_somatic.csv,393`

`1,mouse_proteoform_glycosylation_sites_oglcnac_mcw.csv,209,mouse_proteoform_citations_glycosylation_sites_oglcnac_mcw.csv,208`

`1,mouse_protein_function_refseq.csv,31810,mouse_protein_citations_refseq.csv,31809`

`2,human_protein_mutation_literature.csv,4597,human_protein_citations_mutation_literature.csv,4595`

**Comment by JingyueWu** [comment]
Dataset testing - glycan: 

<img width="844" alt="Screen Shot 2023-03-31 at 3 44 20 PM" src="https://user-images.githubusercontent.com/61590108/229214842-83596c2c-eaaf-4d40-a589-8ae87b17ec72.png">

@kmartinez834 Do you need me to check literally all protein and proteoform .csv?

**Comment by kmartinez834** [comment]
@JingyueWu use `check-dataset-group.py` instead

**Comment by JingyueWu** [comment]
@kmartinez834 It seems like it is only giving me the column header names? I tried selecting `-m` as the parameter as it would give us molecule `protein/glycan/proteoform`? Please let me know if I'm on the right track.

<img width="1064" alt="Screen Shot 2023-03-31 at 4 51 41 PM" src="https://user-images.githubusercontent.com/61590108/229227700-ea28fb5a-bdc4-4568-9802-e4ddf7d117d9.png">

**Comment by kmartinez834** [comment]
@JingyueWu Yes, you need to add the molecule.  See the Sharepoint doc `python3 check-dataset-group.py -m glycan -r 1.12.3`

**Comment by JingyueWu** [comment]
@kmartinez834 Thanks, I see! 

Glycan: 

<img width="1056" alt="Screen Shot 2023-03-31 at 5 01 50 PM" src="https://user-images.githubusercontent.com/61590108/229229374-61e33815-c343-429f-b0af-c9d872041a55.png">
<img width="811" alt="Screen Shot 2023-03-31 at 5 02 36 PM" src="https://user-images.githubusercontent.com/61590108/229229489-7b8ad8ea-f8f5-4f99-a5c1-bc038a5526e9.png">

Protein:


<img width="1103" alt="Screen Shot 2023-03-31 at 5 08 08 PM" src="https://user-images.githubusercontent.com/61590108/229231265-d96536c1-f151-4da5-8826-ac89ccfcb152.png">
<img width="996" alt="Screen Shot 2023-03-31 at 5 09 01 PM" src="https://user-images.githubusercontent.com/61590108/229231507-614ba8ad-3119-474c-9aad-3c3b25b66938.png">
<img width="1102" alt="Screen Shot 2023-03-31 at 5 09 43 PM" src="https://user-images.githubusercontent.com/61590108/229231704-9b5d96ee-09d4-496b-8056-b9c6f783c5dc.png">
<img width="1067" alt="Screen Shot 2023-03-31 at 5 10 22 PM" src="https://user-images.githubusercontent.com/61590108/229231924-aa241089-a5c9-4fb3-ba4b-fdc4aba1c618.png">
<img width="1104" alt="Screen Shot 2023-03-31 at 5 11 01 PM" src="https://user-images.githubusercontent.com/61590108/229232070-a63230eb-cb5b-498a-a7fe-8f17805480ad.png">
<img width="1102" alt="Screen Shot 2023-03-31 at 5 11 58 PM" src="https://user-images.githubusercontent.com/61590108/229232215-7ca1a37a-dc47-4860-bf55-e4a5bd27b561.png">
<img width="1105" alt="Screen Shot 2023-03-31 at 5 12 28 PM" src="https://user-images.githubusercontent.com/61590108/229232263-4c583b42-9d65-43a9-b4f5-4ffa1d2f63e4.png">
<img width="1097" alt="Screen Shot 2023-03-31 at 5 12 56 PM" src="https://user-images.githubusercontent.com/61590108/229232327-7823cadb-7819-4a6d-aed1-f2a181ccae53.png">

Proteoform:

<img width="1073" alt="Screen Shot 2023-03-31 at 5 14 28 PM" src="https://user-images.githubusercontent.com/61590108/229232564-ba890a40-8cf3-46d0-9048-f6fc92f17905.png">
<img width="1125" alt="Screen Shot 2023-03-31 at 5 14 53 PM" src="https://user-images.githubusercontent.com/61590108/229232621-009eae17-457c-4ccb-a42c-1f23bba359b7.png">
<img width="1113" alt="Screen Shot 2023-03-31 at 5 15 15 PM" src="https://user-images.githubusercontent.com/61590108/229232674-14d1d265-96d7-46a9-afb9-ebb278811222.png">

**Comment by JingyueWu** [comment]
Status update: finished checking glycan dataset (i.e. opened file on terminal and sent it to local machine in .csv format for easier visualization)

Next action items: do the same with Protein and Proteoform.
