### ISSUE TITLE
Evaluation of glycowork

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#185]
There was a talk about glycowork in the [GLIC seminar series](https://glic.glycoinfo.org/seminars/glycan-arrays-2023/). Part of the python package is a glycan library with more than 50,000 records. Not all records are complete but they can have the following information:
* glycan
* Species
* Genus
* Family
* Order
* Class
* Phylum
* Kingdom
* Domain
* ref
* glytoucan_id
* predicted_taxonomy
* glycan_type
* immunogenicity
* disease_association
* disease_id
* disease_sample
* disease_direction
* disease_ref
* disease_species
* tissue_sample
* tissue_id
* tissue_ref
* tissue_species
* Composition

Which include taxon annotation, reference, disease and tissue information. A quick count showed:
* ~9000 records Human
* ~2000 records Mouse
* ~ 500 records Rat

Partially from other databases but also manual curation.

Careful! Not all records have GlyTouCan IDs. That is something to work on.

The database can be found [here](https://github.com/BojarLab/glycowork/blob/master/glycowork/glycan_data/v7_sugarbase.csv).

**Comment by Mindyporterfield** [comment]
https://github.com/BojarLab/glycowork/blob/master/05_examples.ipynb
here are some examples of what you can do in it, could be a good spark for ideas @ReneRanzinger @kmartinez834 @edwardsnj

**Comment by kmartinez834** [comment]
Changing assignment to Cyrus, as he's been looking into Glycowork
