### ISSUE TITLE
Missing citations in human_protein_citations_mutation_germline.csv

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1852]
There are 27 citations missing in the `human_protein_citations_mutation_germline.csv`. I checked the missing PMIDs and they are still valid and the `human_protein_mutation_germline.csv` does contain the PMIDs. I checked some of them in the dataset and I couldn't see why these specific IDs were not downloaded. Here are the missing PMIDs:
```
27,human_protein_mutation_germline.csv,399,human_protein_citations_mutation_germline.csv,372
19911184
1903761
16940445
26563160
12124407
19502294
15024729
1407588
1765377
31508243
16098032
8013151
10652351
7200565
27165006
10022448
15886248
10204861
10480369
15579795
10971344
15090543
2239969
14678799
12220451
11138927
11036902
```

**Comment by rykahsay** [comment]
Please check now

**Comment by katewarner** [comment]
It's fixed. Thank you
