### ISSUE TITLE
Dr. Daniel Kolarich Webinar Video Editing

### ISSUE THREAD

**Issue by SwathiMurali** [glygener/glygen-issues#1859]
- Edit the video by trimming unnecessary parts of the recording.
- Add timestamps/chapters to the video
- Create a thumbnail

**Comment by SwathiMurali** [comment]
Hi @ReneRanzinger. Here's the Google Drive link containing the edited video (Webinar_YT_DanielKolarich.mp4), the thumbnail and the timestamps doc: https://drive.google.com/drive/folders/1sZiBvScw8b1N_eJvyF-qA05inexRP6PC

**Comment by ReneRanzinger** [comment]
@SwathiMurali There is a problem with the timestamps. The video is 50 minutes long but the timestamps are for 90 minutes (wrong file?)

**Comment by SwathiMurali** [comment]
Hi @ReneRanzinger . Sorry about that oversight. I've added the right doc in our Drive. Can you please check now? Thanks

**Comment by ReneRanzinger** [comment]
https://www.youtube.com/watch?v=mog-VZW5w4g
