### ISSUE TITLE
Search w/ draw glycan tool isn't working

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#186]
Tried substructure search w/ N-core template, and got the following error message. Expected to get a list of all fully defined N glycans (and any partially defined structures with this core).
![image](https://user-images.githubusercontent.com/90285371/228070142-cb701f47-8a17-4c93-be14-2aeda18d0328.png)

![image](https://user-images.githubusercontent.com/90285371/228069873-eed7e454-d27a-4625-ade0-d20caabe4229.png)

**Comment by rykahsay** [comment]
@sujeetvkulkarni -- can you please check this and give us the API call you are making if the problem is from the backend?

**Comment by sujeetvkulkarni** [comment]
@kmartinez834 
I tried it with N-core template for substructure search and got below results.
For your reference giving you list of api calls,
https://api.tst.glygen.org/job/addnew
https://api.tst.glygen.org/job/status/?query={"jobid":6}
https://api.tst.glygen.org/job/results/?query={"jobid":6}
https://api.tst.glygen.org/glycan/list?query={"id":"24c278157312c99397dbe261050fdd19","offset":1,"sort":"hit_score","limit":20,"order":"desc","filters":[]}

You can see the results here,
https://tst.glygen.org/glycan-list/24c278157312c99397dbe261050fdd19

Also, you can check above api call list for any other cases where it might be failing.

**Comment by kmartinez834** [comment]
👍 Thanks, it's working now
