### ISSUE TITLE
Please document this on when/why you make QC ticket

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1861]
When you perform dataset QC and find out row is missing in the current release we are trying to package (compared to last release in production), you cannot just create a ticket for me listing the missing rows without digging further. You need to dig into the source/input/downloaded files to answer the following question:

Is all the data need to make a given missing row in the input/downloaded file?

If the answer is "yes", then you make a ticket for me saying that the row is missing from the current dataset "for no good reason". On the other hand, if the answer is "no", then you to go back and check the download was done properly or work with the source folks to find out why data is missing

**Comment by katewarner** [comment]
I've documented this in the Dataset Checking doc
