### ISSUE TITLE
supersearch/list api is failing with 500 error

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1864]
https://api.tst.glygen.org/supersearch/list?query=
{"id":"09a7c68179c78b465dc37c421e7c337a","offset":1,"sort":"hit_score","limit":20,"order":"desc","filters":[],"columns":[]}

https://api.tst.glygen.org/supersearch/list?query=
{"id":"09a7c68179c78b465dc37c421e7c337a","offset":1,"sort":"hit_score","limit":20,"order":"desc","filters":[],"columns":["uniprot_canonical_ac","protein_name","hit_score","organism","uniprot_id","length","refseq_ac","refseq_name","gene_name","n_glycosylation_count","o_glycosylation_count"]}

![Screenshot 2024-10-28 at 12 42 25 PM](https://github.com/user-attachments/assets/7e21fa2f-acfb-463f-b9f7-2529d9fd0916)

**Comment by rykahsay** [comment]
I have tried to fix this, please try

**Comment by sujeetvkulkarni** [comment]
@rykahsay /supersearch/list/ api is still failing.
https://api.tst.glygen.org/supersearch/list?query=
{"id":"dc9607e6559443b01587f8db16c39f08","offset":1,"sort":"hit_score","limit":20,"order":"desc","filters":[],"columns":[]}

https://api.tst.glygen.org/supersearch/list?query=
{"id":"dc9607e6559443b01587f8db16c39f08","offset":1,"sort":"hit_score","limit":20,"order":"desc","filters":[],"columns":["uniprot_canonical_ac","protein_name","hit_score","organism","uniprot_id","length","refseq_ac","refseq_name","gene_name","n_glycosylation_count","o_glycosylation_count"]}

![Screenshot 2024-11-06 at 3 04 57 PM](https://github.com/user-attachments/assets/1df8b02c-f8d0-49f9-855c-e0a0d1341e09)

**Comment by rykahsay** [comment]
I have tried to fix it, please check

**Comment by sujeetvkulkarni** [comment]
closing.
