### ISSUE TITLE
Error in Biomarker Simple Search

### ISSUE THREAD

**Issue by SwathiMurali** [glygener/glygen-issues#1867]
![image](https://github.com/user-attachments/assets/1faccac8-1f77-4337-9651-d50fff665786)

- It works for the "Condition" filter but the "Biomarker" filter seems to be broken.
- Used the example Biomarker for the search and got the above error

**Comment by sujeetvkulkarni** [comment]
Please check. Fixed on tst.
https://tst.glygen.org/biomarker-search/
