### ISSUE TITLE
Additional data coming in expression array for glycans

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#187]
Entries/objects in the expression array does not contain either tissue or cell line object.
These entries should not be part of expression array. Similar changes may apply for expression array in publications api.
https://api.tst.glygen.org/glycan/detail/G17689DH

"expression": [{"uniprot_canonical_ac": "P07911-1", "start_pos": 396, "end_pos": 396, "residue": "Asn", "evidence": [{"id": "P07911", "database": "UniCarbKB", "url": "http://unicarbkb.org/proteinsummary/P07911/annotated"}, {"id": "2136357", "database": "PubMed", "url": "https://glygen.org/publication/PubMed/2136357"}, {"id": "9884403", "database": "PubMed", "url": "https://glygen.org/publication/PubMed/9884403"}]}, ...]

https://api.tst.glygen.org/publication/detail?query={%22id%22:%228407880%22,%22type%22:%22PubMed%22}

schema should define either one of both tissue or cell_line object as mandatory and if both of them are missing test case should capture it.

**Comment by sujeetvkulkarni** [comment]
```
"expression": [{"uniprot_canonical_ac": "P07911-1", "start_pos": 396, "end_pos": 396, "residue": "Asn", "evidence": [{"id": "P07911", "database": "UniCarbKB", "url": "http://unicarbkb.org/proteinsummary/P07911/annotated"}, {"id": "2136357", "database": "PubMed", "url": "https://glygen.org/publication/PubMed/2136357"}, {"id": "9884403", "database": "PubMed", "url": "https://glygen.org/publication/PubMed/9884403"}]}, ...]
```

**Comment by sujeetvkulkarni** [comment]
Formatted JSON 
```
"expression": [
    {
        "uniprot_canonical_ac": "P07911-1",
        "start_pos": 396,
        "end_pos": 396,
        "residue": "Asn",
        "evidence": [
            {
                "id": "P07911",
                "database": "UniCarbKB",
                "url": "http://unicarbkb.org/proteinsummary/P07911/annotated"
            },
            {
                "id": "2136357",
                "database": "PubMed",
                "url": "https://glygen.org/publication/PubMed/2136357"
            },
            {
                "id": "9884403",
                "database": "PubMed",
                "url": "https://glygen.org/publication/PubMed/9884403"
            }
        ]
    }, ...
]
```

**Comment by rykahsay** [comment]
done -- please check

**Comment by kmartinez834** [comment]
@rykahsay I do not see a change to the glycan detail api:
https://api.tst.glygen.org/glycan/detail/G17689DH

``` json
"expression": [{
		"uniprot_canonical_ac": "P07911-1",
		"start_pos": 396,
		"end_pos": 396,
		"residue": "Asn",
		"evidence": [{
			"id": "P07911",
			"database": "UniCarbKB",
			"url": "http://unicarbkb.org/proteinsummary/P07911/annotated"
		}, {
			"id": "2136357",
			"database": "PubMed",
			"url": "https://glygen.org/publication/PubMed/2136357"
		}, {
			"id": "9884403",
			"database": "PubMed",
			"url": "https://glygen.org/publication/PubMed/9884403"
		}]
	}, {
```

**Comment by rykahsay** [comment]
Please check now

<img width="654" alt="image" src="https://user-images.githubusercontent.com/20584876/229643279-e50658aa-c0f1-457e-9961-2749558f15c4.png">

**Comment by rykahsay** [comment]
<img width="665" alt="image" src="https://user-images.githubusercontent.com/20584876/229643590-1f77e706-766d-4ac6-872d-94a8b4932b66.png">

**Comment by kmartinez834** [comment]
Looks good to me.  

@sujeetvkulkarni --> please review

**Comment by sujeetvkulkarni** [comment]
Looks like additional data is not coming now.
