### ISSUE TITLE
Start testing APIs on tst

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1871]
The APIs are ready for testing. I am not sure if @sujeetvkulkarni has finished all his work for us to start testing the frontend.

**Comment by katewarner** [comment]
@rykahsay I've finished testing the APIs on tst. I tested all APIs using the examples, and I also tested with other queries as well. I used some high-record entries (from jumbodb) when it asked for glycan ac, protein ac, or publication ID, and I also tested the appropriate APIs with Bovine proteins.
I found a few issues which I created tickets for. I've listed all the issues I found during testing here: https://github.com/glygener/glygen-issues/issues/1875#issuecomment-2483632380
