### ISSUE TITLE
Activate human_proteoform_glycosylation_sites_o_gluc.csv and it's BCO

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1872]
We've fixed the problem with this dataset (#1869). If you haven't already, please activate the `human_proteoform_glycosylation_sites_o_gluc.csv` dataset and it's BCO, or please show me how to do it :-D

**Comment by ubhuiyan** [comment]
Done! I can show you how to do this during one of our internal meetings if you'd like.
