### ISSUE TITLE
Testing on tst

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1875]
**Blocker for:**
* #1908 
* #1910 
* #1876 
* #1911

**Comment by jeet-vora** [comment]
Please use the spreadsheet to tst - https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Tasks%20planning/GlyGen%20-%20version%202.7/Testing/Tst%20-%202.7.xlsx?d=w3eee344a828548109695d06c34258512&csf=1&web=1&e=OaEH9Q

Enter your issues ID here separately. @katewarner @ubhuiyan

**Comment by ReneRanzinger** [comment]
@jeet-vora I do not see any entry for @Mindyporterfield. Does this mean she is not needed for 2.7?

**Comment by jeet-vora** [comment]
@ReneRanzinger She will be added for 2.7 prd testing for this release which does not require VPN to access. Does it sound good?

**Comment by ReneRanzinger** [comment]
@jeet-vora Sounds good. I just wanted to confirm it.

**Comment by jeet-vora** [comment]
@katewarner Add your issues tickets here

Add ticket number to GitHub Ticket, Status = Pending or Resolved, Notes any notes about issue

| GitHub Ticket | Status | Notes |
| ------------- | ------ | ----- |
| #1917  |Resolved|  |
| #1918   | Pending     | For Sujeet |
| #1919    | Resolved|  |
| #1920 | Resolved|  |
| #1661 | Pending  ||
|#1922 |Resolved||
|#1929 |Resolved||
|#1940 |Resolved||
|#1943 |Resolved||
|#1947 |Resolved||
|#1950 |Resolved||
|#1952 |Resolved||
|#1953 |Pending |For Sujeet|
|#1956 |Pending |Check again when testing prd|
|#1957 |Pending |For Sujeet|
|#1961 |Pending ||
|#1963| Pending |For Sujeet|
|#1995| Pending |For Sujeet|
|#1997|Pending||
|#1998|Pending||
|#1999|Pending||

**Comment by jeet-vora** [comment]
@ubhuiyan Add your issues tickets here.

Add ticket number to GitHub Ticket, Status = Pending or Resolved, Notes any notes about issue
| GitHub Ticket | Status | Notes |
| ------------- | ------ | ----- |
| #1915             | Resolved    | Substructure Search |
| #1976            | Resolved    | Super Search |
| #1967            | Pending    | Glycan Lookup - For Sujeet |

**Comment by katewarner** [comment]
Testing completed and all issues reported.
