### ISSUE TITLE
Testing on production

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1876]
**Dependencies:**
* #1875
* #1908 
* #1910 

**Blocker for:**
* #1911

**Comment by jeet-vora** [comment]
@ubhuiyan @katewarner 
Here is the testing template for PRD. Please add your issues here.

https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Tasks%20planning/GlyGen%20-%20version%202.7/Testing/Prd%20-%202.7%20testing.xlsx?d=wff4285a1e9cb4d3ba5093e722406c588&csf=1&web=1&e=qxgZ7g

**Comment by ubhuiyan** [comment]
Testing Issues: 

- https://github.com/glygener/glygen-issues/issues/2021
- https://github.com/glygener/glygen-issues/issues/2026
- https://github.com/glygener/glygen-issues/issues/2019
- https://github.com/glygener/glygen-issues/issues/2028
- https://github.com/glygener/glygen-issues/issues/2030
- https://github.com/glygener/glygen-issues/issues/2034
- https://github.com/glygener/glygen-issues/issues/2035
- https://github.com/glygener/glygen-issues/issues/2037
- https://github.com/glygener/glygen-issues/issues/2039

**Comment by katewarner** [comment]
I found the following issues. As requested I also tested glycosylation numbers reported/predicted in several organisms and didn't find any issues.

Testing issues:
- https://github.com/glygener/glygen-issues/issues/2015 
- https://github.com/glygener/glygen-issues/issues/2018 
- https://github.com/glygener/glygen-issues/issues/2020 
- https://github.com/glygener/glygen-issues/issues/2022
- https://github.com/glygener/glygen-issues/issues/2017
- https://github.com/glygener/glygen-issues/issues/2025
- https://github.com/glygener/glygen-issues/issues/2023 
- https://github.com/glygener/glygen-issues/issues/2027 
- https://github.com/glygener/glygen-issues/issues/2029 
- https://github.com/glygener/glygen-issues/issues/2031
- https://github.com/glygener/glygen-issues/issues/2032
- https://github.com/glygener/glygen-issues/issues/2033 
- https://github.com/glygener/glygen-issues/issues/2036 
- https://github.com/glygener/glygen-issues/issues/2041 
- https://github.com/glygener/glygen-issues/issues/2044

**Comment by jeet-vora** [comment]
@rykahsay

@ubhuiyan and @katewarner have finished testing and created tickets for issues.

**Comment by rykahsay** [comment]
@jeet-vora  ... please close this if testing is finished
