### ISSUE TITLE
Poster for Upcoming GlyGen Webinar (November)

### ISSUE THREAD

**Issue by SwathiMurali** [glygener/glygen-issues#1877]
Details to include in the poster: 
Title: Restoring Protein Glycosylation with GlycoShape

Abstract: The introduction of machine learning (ML) for protein structure prediction, awarded with the 2024 Nobel Prize in Chemistry, revolutionized structural biology, boosting our ability to source and resolve protein structures, and broadening the potential for therapeutic discovery. One limitation affecting all ML-derived structures is the lack post-translational modifications, which are key to the correct folding, structural stability, and function of the underlying protein. In this webinar I will introduce GlycoShape (https://glycoshape.org/ and https://doi.org/10.1038/s41592-024-02464-7), a unique OA online resource that allows users to rapidly and easily restore glycoproteins from ML, from the Protein Data Bank, or own, to their native state by adding the missing glycan 3D information in seconds.

LinkedIn: https://www.linkedin.com/in/elisa-fadda-a012b194/?originalSubdomain=ie

Twitter Handle: @elisaTelisa

**Comment by SwathiMurali** [comment]
https://gwu0.sharepoint.com/:b:/r/sites/GlyGenTeam-GRP/Shared%20Documents/GlyGen_Webinar_Talks/Elisa%20Fadda/[GlyGen_Webinar_Series_Elisa_Fadda_Nov19_2024.pdf](https://gwu0.sharepoint.com/:b:/r/sites/GlyGenTeam-GRP/Shared%20Documents/GlyGen_Webinar_Talks/Elisa%20Fadda/GlyGen_Webinar_Series_Elisa_Fadda_Nov19_2024.pdf?csf=1&web=1&e=b7uKsb)?csf=1&web=1&e=b7uKsb

**Comment by ReneRanzinger** [comment]
@SwathiMurali that is a dead link. Maybe a copy and paste error?
