### ISSUE TITLE
Protein list api is failing with 500 error.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1878]
https://api.tst.glygen.org/protein/list api is failing.

![Screenshot 2024-11-07 at 11 45 30 AM](https://github.com/user-attachments/assets/011c5ccc-86e3-4ad9-b471-f9aee24c4ce3)

**Comment by rykahsay** [comment]
Yea, I just fixed it

**Comment by sujeetvkulkarni** [comment]
closing.
