### ISSUE TITLE
Tissue and cell line entries have same publication evidence entry and part of same object in expression array for glycan

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#188]
glycan expression array contains objects which contains both cell line and tissue objects and have common publication (PMID: 8407880) as evidence, please have a look at validity of such entries which contain both tissue, cell_line objects and have common evidence.

"expression": [...{"uniprot_canonical_ac": "P14210-1", "start_pos": 294, "end_pos": 294, "residue": "Asn", "tissue": {"name": "ovary", "namespace": "UBERON", "id": "0000992", "url": "http://purl.obolibrary.org/obo/UBERON_0000992"}, "cell_line": {"name": "CHO", "namespace": "CVCL", "id": "0213", "url": "https://web.expasy.org/cellosaurus/CVCL_0213"}, "evidence": [{"id": "1077", "database": "GlyConnect", "url": "https://glyconnect.expasy.org/browser/structures/1077"}, {"id": "219", "database": "GlyConnect", "url": "https://glyconnect.expasy.org/browser/proteins/219"}, {"id": "8407880", "database": "PubMed", "url": "https://glygen.org/publication/PubMed/8407880"}]}...]

https://pubmed.ncbi.nlm.nih.gov/8407880/
Paper : https://www.jstage.jst.go.jp/article/biochemistry1922/114/1/114_1_76/_pdf/-char/en

This may apply to publication details api too.
https://api.tst.glygen.org/publication/detail?query={%22id%22:%228407880%22,%22type%22:%22PubMed%22}

**Comment by ReneRanzinger** [comment]
Please use code style for this since its better readable.
```
  "expression": [
   ...
    {
      "uniprot_canonical_ac": "P14210-1",
      "start_pos": 294,
      "end_pos": 294,
      "residue": "Asn",
      "tissue": {
        "name": "ovary",
        "namespace": "UBERON",
        "id": "0000992",
        "url": "http://purl.obolibrary.org/obo/UBERON_0000992"
      },
      "cell_line": {
        "name": "CHO",
        "namespace": "CVCL",
        "id": "0213",
        "url": "https://web.expasy.org/cellosaurus/CVCL_0213"
      },
      "evidence": [
        {
          "id": "1077",
          "database": "GlyConnect",
          "url": "https://glyconnect.expasy.org/browser/structures/1077"
        },
        {
          "id": "219",
          "database": "GlyConnect",
          "url": "https://glyconnect.expasy.org/browser/proteins/219"
        },
        {
          "id": "8407880",
          "database": "PubMed",
          "url": "https://glygen.org/publication/PubMed/8407880"
        }
      ]
    }
   ...
  ]
```

**Comment by rykahsay** [comment]
This is what we have in our downloaded/input data from glyconnect (downloads/glyconnect/current/glyconnect_human.json). As you can see, both tissue and cell line sources are given with only one reference paper

```
{
    "taxonomy": {
        "id": 227,
        "species": "Homo sapiens",
        "common_name": "Human",
        "taxonomy_id": "9606"
    },
    "protein": {
        "id": 219,
        "name": "Hepatocyte growth factor",
        "reviewed": true,
        "uniprots": [
            {
                "uniprot_acc": "P14210",
                "uniprot_id": "HGF_HUMAN",
                "nextprot": "NX_P14210",
                "genecards": "HGF",
                "glygen": "P14210"
            }
        ]
    },
    "composition": {
        "id": 448,
        "format_numeric": "5,4,1,2,0,0,0,0,0,0,0,0,0,0",
        "format_glyconnect": "Hex:5 HexNAc:4 dHex:1 NeuAc:2",
        "format_byonic": "HexNAc(4)Hex(5)dHex(1)NeuAc(2)",
        "format_condensed": "H5N4F1S2",
        "mass": 2370.1661,
        "mass_monoisotopic": 2368.8409,
        "reviewed": true,
        "glytoucan_id": "G22310AV"
    },
    "structure": {
        "id": 1077,
        "glytoucan_id": "G17689DH",
        "reviewed": true,
        "is_undefined": false,
        "has_image": true,
        "glycan_type": "N-Linked",
        "glycan_core": "Complex"
    },
    "site": {
        "glyco_site": "Asn-653",
        "location": 653
    },
    "source": {
        "cell_line": {
            "id": 89,
            "name": "CHO",
            "cellosaurus_id": "CVCL_0213",
            "is_problematic": false
        },
        "tissue": {
            "id": 145,
            "name": "Ovary",
            "uberon_id": "UBERON_0000992"
        }
    },
    "references": [
        {
            "id": 1382,
            "title": "Structural study of the N-linked oligosaccharides of hepatocyte growth factor by two-dimensional sugar mapping.",
            "authors": "Hara H, Nakae Y, Sogabe T, Ihara I, Ueno S, Sakai H, Inoue H, Shimizu S, Nakamura T, Shimizu N",
            "pmid": 8407880,
            "doi": "10.1093/oxfordjournals.jbchem.a124143",
            "year": 1993
        }
    ]
}
```

**Comment by kmartinez834** [comment]
@rykahsay -> If there is both tissue and cell line, ignore the tissue

**Comment by rykahsay** [comment]
Please check now:

<img width="457" alt="image" src="https://user-images.githubusercontent.com/20584876/230656083-c7d39fca-843a-498a-b5be-428d6fb60234.png">


<img width="379" alt="image" src="https://user-images.githubusercontent.com/20584876/230655851-51ed87f5-b9b9-4456-b41c-355cce6bc097.png">

**Comment by kmartinez834** [comment]
Looks good

Found another issue where Glyconnect is only giving us tissue "ovary" for expression found in Chinese Hamster Ovary cell line:  #233 

--> Will send an email to Frederique after Biocuration
