### ISSUE TITLE
Process Isoglyp Data

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1901]
I have run all necessary scripts and conducted QC. Everything looks good and is documented in ticket #1831. The files are available in` /isoglyp/current/`.

**Comment by rykahsay** [comment]
No rows pass for sarscov2, I have removed the dataset for sarscov2 and retired the bco.
Please check the others

**Comment by ubhuiyan** [comment]
I have checked and all datasets look good.
