### ISSUE TITLE
Error in Biomarker Simple Search

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1906]
![image](https://github.com/user-attachments/assets/44f126f4-1894-44ce-bac5-0c63fc70f837)

- With Biomarker category AN6278-1 example returns 0 results. It works with Any category.

API:
https://api.tst.glygen.org/biomarker/search_simple?query=
{"operation":"AND","query_type":"biomarker_search_simple","term":"AN6278-1","term_category":"biomarker"}

Response:
```
{
    "list_id": "",
    "query": {
        "operation": "AND",
        "query_type": "biomarker_search_simple",
        "term": "AN6278-1",
        "term_category": "biomarker"
    },
    "resultcount": 0
}
```

**Comment by rykahsay** [comment]
There is no biomarker associated with "AN6278-1" -- there was a bug that was resulting in having search results when category is "any". I have fixed that issue and you shouldn't get any results for that query for any category.

@katewarner ... please provide @sujeetvkulkarni a working example queries for biomarkers search

**Comment by jeet-vora** [comment]
@sujeetvkulkarni 
Try these
AA5028-1
AN4117-1

**Comment by sujeetvkulkarni** [comment]
Please check. Fixed on tst.
https://tst.glygen.org/biomarker-search/

**Comment by katewarner** [comment]
Looks good
