### ISSUE TITLE
2.7 Release notes 

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1907]
Filling the wiki pages with the information:
* https://wiki.glygen.org/Release_notes (@sujeetvkulkarni, @katewarner and @ubhuiyan )
* https://wiki.glygen.org/Data_release_notes/2.7 (@katewarner and @ubhuiyan )
* https://wiki.glygen.org/Data_release_notes (@katewarner and @ubhuiyan)
* https://wiki.glygen.org/Portal_release_notes/2.7 (@sujeetvkulkarni )
* https://wiki.glygen.org/Portal_release_notes (@sujeetvkulkarni )

**Blocker for:**
* #1911

**Comment by jeet-vora** [comment]
Data Release notes - https://wiki.glygen.org/Data_release_notes/2.7.1
@ReneRanzinger We have been creating data release main page as X.X.X and not X.X.

**Comment by sujeetvkulkarni** [comment]
Added 2.7 release notes.
https://wiki.glygen.org/Release_notes
https://wiki.glygen.org/Portal_release_notes
https://wiki.glygen.org/Portal_release_notes/2.7

**Comment by ubhuiyan** [comment]
Shall we close this ticket?
