### ISSUE TITLE
Test Glycosylation section for protein P0DTC2

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#191]
Description

Robel added the alternative properties to the glycosylation section. We need to see it that breaks the GUI. After this we need to talk about how we implement this.

P0DTC2-1

Sujeet Kulkarni 
January 4, 2022 at 12:34 PM
Will be discussed with Mathew in data meeting. Then we will discuss how to handle this.

Edit

Delete

Sujeet Kulkarni 
December 6, 2021 at 1:46 PM
Edited

Sujeet - Tuesday meeting - after 1.11 release (January).

Edit

Delete

Tatiana Williamson 
June 25, 2021 at 4:10 PM
I’ve tested it and the current version is working fine.

Tatiana Williamson 
June 10, 2021 at 4:25 PM
Edited

[https://lh5.googleusercontent.com/5f7AcAA_emqRenux7jzoRola1tNb39H5XVtUjjuulDHcfbWyNrWcmCTGLK9cUakwgWsQL42rXcAteI9arCdIoKifsoIXcs6Z66hoS3FLCSPIf9ZlB8ZQt3hvK35_dRxedxGaBgh6]

Here are my responses to your questions:

did you put this on test or is it just on dev?

>> yes, I thought you could see the URL in the screenshot I sent.

are these additional properties or do they replace existing properties

>> they are all new additional properties

we need an example ID for all these to test it.

>> like I explained in the email, the screenshot gives example ID for the three properties but we do not have an example for property "glytoucan_ac_list"

https://api.tst.glygen.org/protein/detail/P0DTC2-1

rene@ccrc.uga.edu 
June 4, 2021 at 10:36 PM
I am not sure if this is too late for you to incorporate the beta release we are planning to push today. In any case, these are the new properties within the glycosylation objects.

alternate_start_pos_list (example given in the screenshot below)

alternate_end_pos_list (example given in the screenshot below)

alternate_amino_acid_list (example given in the screenshot below)

alternate_glytoucan_ac_list (not shown in the example, the example we have is being filtered out because it fails one of our QC rule, and will show up after we relax the QC rule or do something about it)

**Comment by kmartinez834** [comment]
Check alternative/range issues @rykahsay @kmartinez834
