### ISSUE TITLE
Universal Substructure Example 

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1915]
The WURCS example we provide does not appear to occur at the terminal level of the Substructure Search (as far as I understand). Should we replace it with an example that applies universally across all levels (i.e., none, reducing end, and terminal)? 

![Screenshot 2024-11-19 at 1 22 45 PM](https://github.com/user-attachments/assets/e20cf0b1-4277-431f-abc6-9e3ac0523ee3)

**Comment by jeet-vora** [comment]
The substructure search on tst does not work with the above selections. Please look into it.

**Comment by rykahsay** [comment]
Please check now

**Comment by ubhuiyan** [comment]
It works fine now. Thanks!
