### ISSUE TITLE
Test data.tst.glygen.org so that we can push it to prd on Friday

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1916]
Test data.tst.glygen.org so that we can push it to prd on Friday

**Comment by jeet-vora** [comment]
Current issues

#1926 
#1925 
#1923 
#1924  (Kate is investigating)

After resolving the issue please push again
identical to issue #1909

**Comment by rykahsay** [comment]
Data is being uploaded to prd now, it will finish in few hours ... please test data.glygen.org after two hours
