### ISSUE TITLE
Missing scroll bar in News section

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1918]
In the News section on the homepage of tst and prd, the arrows and draggable part of the scroll bar are very hard to see. Can they be made darker so they're more obvious? 

![image](https://github.com/user-attachments/assets/49cf56f8-9799-45b5-9ef2-0d0c8a118ff1)

**Comment by sujeetvkulkarni** [comment]
Fixed, please check.

**Comment by katewarner** [comment]
Looks great! Many thanks

**Comment by katewarner** [comment]
Reopened because scroll bar is missing on prd:
![image](https://github.com/user-attachments/assets/6c9cb773-b6ad-45da-9d82-fc5ad132ab41)

**Comment by sujeetvkulkarni** [comment]
Looks like cache issue on your side. Please try different browser, delete cache etc.

![Screenshot 2024-12-17 at 9 54 40 AM](https://github.com/user-attachments/assets/d225092e-158e-4321-9380-28fdfa8cc4a8)

**Comment by katewarner** [comment]
Yes, sorry you're right, it was a cache issue. Fixed now
