### ISSUE TITLE
UniProtKB ID max length should be greater than 10 - valid id A0A0A6YXX7_MOUSE gets an error.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#192]
https://api.tst.glygen.org/supersearch/search_init?query={}
super search init api max length limit for UniProtKB Accession needs to be increased to fit valid ids like A0A0A6YXX7_MOUSE  at all the places.

{
    "id": "uniprot_ac",
    "label": "UniProtKB Accession/ID",
    "type": "string",
    "maxlength": 10,
    "url": "https://wiki.glygen.org/index.php/uniprot_ac",
    "oplist": [
        "$eq",
        "$regex",
        "$ne"
    ],
    "typeahead": "uniprot_canonical_ac",
    "enum": [],
    "order": 100
}

Page proofer : Note - 270

This message should not be shown for a valid UniProtKB ID A0A0A6YXX7_MOUSE
Entry is too long - max length is 10.

**Comment by rykahsay** [comment]
please check now

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/20584876/229644820-8f182995-abe8-4ca7-8d15-1a19c4a77303.png">

**Comment by sujeetvkulkarni** [comment]
@rykahsay Looks like it's still not working for Enzyme - UniProtKB Accession/ID.
```
{
    "id": "enzyme",
    "label": "Enzyme",
    "description": "GlyGen Enzyme Concept",
    "fields": [
        {
            "id": "uniprot_ac",
            "label": "UniProtKB Accession/ID",
            "type": "string",
            "maxlength": 10,
            "url": "https://wiki.glygen.org/index.php/uniprot_ac",
            "oplist": [
                "$eq",
                "$regex",
                "$ne"
            ],
            "typeahead": "",
            "enum": [],
            "order": 100
        }
...
    ]
}
```

and also not working for Protein - Ortholog UniProt Accession

```
{
    "id": "orthologs.uniprot_canonical_ac",
    "label": "Ortholog UniProt Accession",
    "type": "string",
    "maxlength": 12,
    "url": "https://wiki.glygen.org/index.php/orthologs.uniprot_canonical_ac",
    "oplist": [
        "$eq",
        "$regex",
        "$ne"
    ],
    "typeahead": "",
    "enum": [],
    "order": 1200
}
```

**Comment by rykahsay** [comment]
please check now

**Comment by sujeetvkulkarni** [comment]
max limit increased.
