### ISSUE TITLE
Broken Kegg xref_url

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1920]
I noticed that the Kegg pathway url on the tst protein pages were broken. I've corrected the xref_url so that you can update the protein details pages.

![image](https://github.com/user-attachments/assets/43af74af-b9cb-48bf-b875-00862f1afea3)

I changed the base url to `https://www.genome.jp/dbget-bin/www_bget?%s`

**Comment by rykahsay** [comment]
Check now

**Comment by katewarner** [comment]
Fixed thanks
