### ISSUE TITLE
Query about OrthoDB IDs

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1921]
@jieluo321 I noticed that most of our OrthoDB xref links are not working and don't return any results. In these cases the OrthoDB ID we have matches the one on the UniProt website, but when you try to search for that ID on OrthoDB (because our OrthoDB url requires an OrthoDB ID as the target) it doesn't return any results. 

For example, for [Q93100](https://www.uniprot.org/uniprotkb/Q93100/external-links) the OrthoDB ID on the UniProt website and GlyGen is "3640971at2759" but that doesn't exist on OrthoDB - I'm not sure but it should probably be "5971574at2759". Do you know why this might be, and if it's going to be fixed at the next UniProt release?

**Comment by jieluo321** [comment]
We update OrthoDB cross reference regularly. 5971574at2759 will not be in 2025_01.  Since UniProt production, private release and public release. Any new update or remove of cross reference will take 4 months in uniprot from production to public release.

**Comment by katewarner** [comment]
Okay thanks for the info.
