### ISSUE TITLE
Dataset download issue 2.7

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#1923]
The 2.7.1 datasets are not getting downloaded from the data.tst.glygen.org

![image](https://github.com/user-attachments/assets/7a1426a8-ad40-485f-8b42-bb1e2f680beb)
https://data.tst.glygen.org/ln2data/releases/data/v-2.7.1/reviewed/human_protein_masterlist.csv

However replacing `version` with `current` works
https://data.tst.glygen.org/ln2data/releases/data/current/reviewed/human_protein_masterlist.csv

Please assign to @katewarner  for checking. I will only be able to check on Monday

**Comment by rykahsay** [comment]
It is fixed now
