### ISSUE TITLE
NT files for pig and bovine missing from data.tst.glygen.org

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#1924]
Hi Kate can you check why are the NT files for pig and bovine missing from data.tst.glygen.org
Were they added in masterlist? Please assign the ticket to Robel to fix if error found

![image](https://github.com/user-attachments/assets/885bcd0c-c24c-4f88-8a04-6c8dc798bdd0)

@ubhuiyan FYI

**Comment by katewarner** [comment]
@jeet-vora Pig and Bovine are in the masterlist and their *_protein_ntdata.nt files are in the unreviewed directory. I checked https://data.tst.glygen.org/ this morning and it looks like the bug has been fixed, and the Bovine and Pig nt files are there.  

![image](https://github.com/user-attachments/assets/20e7011f-a716-46f2-9e1d-bab3c37e266e)

**Comment by jeet-vora** [comment]
Done
