### ISSUE TITLE
Duplicated entries in "All records" tab on the data.tst.glygen.org

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#1925]
Robel, some of the datasets have duplicated entries in the "All records" tab on the data.tst.glygen.org. https://data.tst.glygen.org/GLY_001173 Minor issue but a issue.

![image](https://github.com/user-attachments/assets/d1944b22-ec1c-490e-af35-e16f36cec4f7)

Also the first header for this dataset is 'Id' rather than the 'uniprotkb_canonical_ac' as in the dataset. For glycan datasets also it is 'id' rather than 'glytoucan_ac'.eg [Link](https://data.tst.glygen.org/ln2data/releases/data/v-2.6.1/reviewed/glycan_masterlist.csv)
 No issues with other headers.

Assign to @katewarner and me if you fix the issue.

**Comment by rykahsay** [comment]
Tried to fix it, please check

**Comment by jeet-vora** [comment]
Done
