### ISSUE TITLE
Funding info on tst.data.glygen.org

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#1926]
Robel the funding information on tst.data.glygen.org must be changed. We are now funded by R24 and CFDE and not by U01. 
The data page can replicate what it is on glygen portal (see below) 
![image](https://github.com/user-attachments/assets/b0c848bc-dd06-455b-a343-e9ef00b2efca)

GlyGen portal
![image](https://github.com/user-attachments/assets/02d4fb14-909c-4816-95f3-4ad131431bd8)

**Comment by rykahsay** [comment]
Fixed, please check

**Comment by jeet-vora** [comment]
Done
