### ISSUE TITLE
Add Swathi to about page?

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1927]
should Swathi be added to the About page of GlyGen? If yes, Jeet can you please provide the necessary information.

**Comment by jeet-vora** [comment]
@SwathiMurali 

Please provide your picture and linkedin link to Sujeet for GlyGen about page.
hi-res picture - 
GlyGen role/position - Science and Social Media Outreach Manager
University/Institution affiliation - The George Washington University
linkedin link -

**Comment by sujeetvkulkarni** [comment]
@SwathiMurali Can you please give picture, linked in details. Please see comments above.

**Comment by SwathiMurali** [comment]
LinkedIn: https://www.linkedin.com/in/swathimuralisrinivasan/
![profile-pic-cropped](https://github.com/user-attachments/assets/bc5dd2b4-6841-41e6-bc01-39b0618b2430)

**Comment by sujeetvkulkarni** [comment]
@jeet-vora Fixed, please check.

**Comment by jeet-vora** [comment]
Looks good
