### ISSUE TITLE
O-linked/Other protein advanced search not working properly

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1929]
I found two problems with the "Glycosylation subtype" on the protein advanced research page on tst. If you select "O-linked" in the "Glycosylation Type" drop-down, and then look at the terms in the "Glycosylation subtype" drop-down the term "Other" occurs twice with the first letter capitalized and not capitalized (see below) whereas on prd only "Other" occurs.

![image](https://github.com/user-attachments/assets/a4c94d9b-74fc-4822-8ed4-66a8c5d52573)

I can't work out where the lowercase term is coming from as all the files I've looked at has other with the first letter capitalized.

Also, I don't think the search is working properly, as when I run the search on prd i.e. "O-linked">"Other", it only returns 15 results whereas on tst selecting "Other" or "other" as the "Glycosylation Subtype" they both return 299927 results. Which files I can use to check if which number is correct?

**Comment by rykahsay** [comment]
The first issue is fixed, as for the second issue, it may be as a result of relaxing some of the QC conditions ... please do some digging (comparison with what we have in prd) to find out why these are coming

**Comment by katewarner** [comment]
@rykahsay The drop down is fixed. I checked some of the entries returned from the search on tst, and it looks correct as all the proteins are associated with a O-linked/Other glycan. It looks like many of these sites were added by IsoGlypt, hence the large increase in the number of proteins in this release.
