### ISSUE TITLE
Maintain Google Analytics for GlyGen

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#193]
@tiwa1154 Just follow-up -- were you able to work with Reeya and retrieve it from Sharepoint, since Confluence is no longer accessible?

**Comment by tiwa1154** [comment]
Pass on to Reeya. She will retrieve the document once grant access to Confluence.

**Comment by jeet-vora** [comment]
@JingyueWu Email Reeya about it and cc me and Tianyi

**Comment by JingyueWu** [comment]
Tianyi has emailed me the GlyGen Google analytics tutorial -- closing this issue.

**Comment by jeet-vora** [comment]
Jingyue do the analytics from where Tianyi left till March for this ticket. The documentation will help you test it and to do the analytics.

**Comment by JingyueWu** [comment]
User stats spreadsheet from Mike: https://docs.google.com/spreadsheets/d/1jg3tmwUB9kiPMyPclnCdT1O7uEEii4F0XfkZleW_-PQ/edit?usp=sharing

**Comment by jeet-vora** [comment]
@JingyueWu Update the analytics on 1st of every month. Make this as your recurring task every month. Setup calendar invite reminder.

**Comment by JingyueWu** [comment]
Reminders set on my calendar. Closing the ticket.

**Comment by JingyueWu** [comment]
Reminders set on my calendar. Monthly analytics report will be sent to the team COB today. Closing the ticket.
