### ISSUE TITLE
Ask Vijay for tool name

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1936]
To display a name in the tool column of the literature mining data (from work with Rahi) we need to know the tool name Vijay prefers.

**Comment by jeet-vora** [comment]
Vijay's tool name - **RLIMS-G**
No base URL shared yet. They will let us know.

**Comment by rykahsay** [comment]
Done,

<img width="1336" alt="image" src="https://github.com/user-attachments/assets/aebdf0df-2441-4e7d-bc46-15504b1c9706" />

**Comment by jeet-vora** [comment]
@rykahsay FYI it is temporary and the tool name may change when the new tool is rolled out.
