### ISSUE TITLE
Provide correct tool name for literature mining data

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1937]
* for Robels pipeline use the latest name of the tool
* for Vijays pipeline see #1936 

These names need to be provided via the API to display in frontend (#1717) by @sujeetvkulkarni

**Comment by rykahsay** [comment]
Done,
<img width="1336" alt="image" src="https://github.com/user-attachments/assets/34437f09-71f1-498d-baba-dedca865d393" />
