### ISSUE TITLE
Glycosylation subtype advanced search issue

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#194]
Robel the O-glycosylation subtype shows peptides instead of O-glycosylation subtypes. It should show O-GlcNAcylation, O-Glucosylation. See below.

I am trying to see at the API level but cannot access https://tst.glygen.org/test/ or https://beta-api.glygen.org/test. I need to understand how can I use Swagger for the Advanced searches.

On tst
![image](https://user-images.githubusercontent.com/25825266/229189667-5b1a5ece-6339-46ce-b6f8-72480a9653a6.png)

On prd
![image](https://user-images.githubusercontent.com/25825266/229190100-cf30808d-ec45-40ab-88ed-6b920c8799ea.png)

@JingyueWu Go through the issue and understand.

**Comment by rykahsay** [comment]
check now
<img width="429" alt="image" src="https://user-images.githubusercontent.com/20584876/230419440-b0c55a58-ada4-4f8f-bf1c-d50cbf8a0bc2.png">

**Comment by jeet-vora** [comment]
Done -no issues
