### ISSUE TITLE
Protein advanced search fields should be exact

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1940]
I think the Protein advanced search > Pathway ID/ Disease ID should only return exact matches. 

When I tested the example "hsa:3082" it should only return the result "P14210-1", bit instead it also returns partial matches "Q9P0U4-1" which has the pathway "hsa:30827", and "Q9NZI2-1" which has the pathway "hsa:30820". These are not the same pathways as "hsa:3082" so I think the Pathway ID search should only return exact matches not partial matches. 

Also for Disease ID, I tested the example "DOID:1324" (lung cancer) and it also returned partial matches such as "Q9Z2V2-1" which contains the disease "DOID:13241" which is a different disease called "Behcet's disease". I think this field should only return exact matches

**Comment by rykahsay** [comment]
Done, please check

**Comment by katewarner** [comment]
Perfect, thanks
