### ISSUE TITLE
Video Editing - Nov 2024 - Dr. Elisa Fadda

### ISSUE THREAD

**Issue by SwathiMurali** [glygener/glygen-issues#1941]

**Comment by SwathiMurali** [comment]
Link to timestamps: https://docs.google.com/document/d/1ssyiKVxrJ4YJFO4fE30ka_M64PYl6LWmrmlVBoAG_gE/edit?usp=sharing

**Comment by ReneRanzinger** [comment]
https://youtu.be/xonQ-m_pexo
