### ISSUE TITLE
Reintegrate human_proteoform_glycosylation_sites_o_gluc.csv

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1943]
Can you check that `human_proteoform_glycosylation_sites_o_gluc.csv` has been integrated properly into tst? This is the dataset that we were going to retire because it failed QC but then we added the only glycan in the dataset to the whitelist. 

I checked the glycan in the dataset "G71142DF" and it has no associated proteins on tst but it should have at least 55 proteins.

```
[k.warner1@glygen-vm-dev]$ awk -F, '{print $1}' /data/projects/glygen/generated/datasets/unreviewed/human_proteoform_glycosylation_sites_o_gluc.csv | sort -u | grep -v "uniprotkb_canonical_ac" | wc -l
55
```

**Comment by rykahsay** [comment]
check now

**Comment by katewarner** [comment]
Excellent thanks
