### ISSUE TITLE
ChEMBL link broken in protein details pages

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1947]
I noticed that the ChEMBL url in the cross-references section of the protein details page wasn't working because the base url is incorrect. I've corrected the link in the xref_info.csv file from `https://www.ebi.ac.uk/chembldb/target/inspect/%s` to the correct base url `https://www.ebi.ac.uk/chembl/target/inspect/%s` which should fix the problem. Please update the files.

**Comment by rykahsay** [comment]
Check now:

<img width="1091" alt="image" src="https://github.com/user-attachments/assets/8c141f45-f1dc-4625-95e7-b3a134140f47">

**Comment by katewarner** [comment]
perfect thanks
