### ISSUE TITLE
Change Pfam links on protein pages

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1950]
Pfam is now hosted by Interpro so the old links to Pfam on the protein pages (e.g. http://pfam.xfam.org/family/PF01601) redirects you to the Pfam page in Interpro (i.e. https://www.ebi.ac.uk/interpro/entry/pfam/PF01601/). I've corrected the Pfam base url in the `xref_info.csv` so that it takes you straight to the Pfam page on Interpro: `https://www.ebi.ac.uk/interpro/entry/pfam/%s` . Please update the files.

**Comment by rykahsay** [comment]
Check now:

<img width="1025" alt="image" src="https://github.com/user-attachments/assets/2156b84f-dba9-4958-b55d-af85baae0bc7">

**Comment by katewarner** [comment]
Fixed thank you
