### ISSUE TITLE
Change AlphaFoldDB url links on protein pages

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1952]
The AlphaFoldDB links in the protein pages currently go to to UniProt 3D structure section e.g. https://www.uniprot.org/uniprotkb/P02751/entry#structure but I checked with Jeet and it should go to the AlphaFold website e.g. https://alphafold.ebi.ac.uk/entry/P02751. I've updated the xref_info.csv file to the new base url `https://alphafold.ebi.ac.uk/entry/%s`. Please update the protein pages.

**Comment by rykahsay** [comment]
Please check:

<img width="936" alt="image" src="https://github.com/user-attachments/assets/d460af12-33b5-44c7-b790-47711dd01f2f">

**Comment by katewarner** [comment]
Perfect thanks
