### ISSUE TITLE
Referenced proteins and Glycans download buttons not working

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1953]
On the Publication pages, the download buttons for the "Referenced Proteins" and "Referenced Glycans" sections are not working. The throbber icon appears for a few seconds but the download doesn't begin.

https://tst.glygen.org/publication/PubMed/20305658#Referenced-Proteins
![image](https://github.com/user-attachments/assets/0c4145c7-2a12-42a7-ad11-1e22a92fea1c)

https://tst.glygen.org/publication/PubMed/20305658#Referenced-Glycans
![image](https://github.com/user-attachments/assets/dc47b34e-56b6-4b13-ab71-8fc6f13157f2)

**Comment by sujeetvkulkarni** [comment]
section_download API call is failing for both referenced_proteins and referenced_glycans.

API:
```
https://api.tst.glygen.org/data/section_download?query=
{"id":"pubmed.20305658","download_type":"publication_section","section":"referenced_proteins","format":"csv","compressed":false}

repsonse:
{
  "error_list": [
    {
      "error_code": "exception-error-Y6OHBE"
    }
  ]
}
```

```
https://api.tst.glygen.org/data/section_download?query=
{"id":"pubmed.20305658","download_type":"publication_section","section":"referenced_glycans","format":"csv","compressed":false}

{
  "error_list": [
    {
      "error_code": "exception-error-HQRUHU"
    }
  ]
}
```

![Screenshot 2024-12-09 at 7 05 55 PM](https://github.com/user-attachments/assets/9651b507-a1ec-4167-a6a7-0c485ae378b4)

**Comment by rykahsay** [comment]
Please try now

**Comment by katewarner** [comment]
Fixed many thanks
