### ISSUE TITLE
Network error when I try BLAST on tst

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1956]
BLAST isn't working on tst; when I retrieved the example sequence "P14210" and tried to BLAST it, I get a network error message: 

![image](https://github.com/user-attachments/assets/8fc04405-8316-4b74-b011-90744410c879)

**Comment by rykahsay** [comment]
Please check now

**Comment by katewarner** [comment]
It still doesn't work for me. It's not working on PRD either

**Comment by rykahsay** [comment]
How about now? I was able to get some results

<img width="1379" alt="image" src="https://github.com/user-attachments/assets/b174c604-cdab-4620-b522-c6bd7f4efd31">

**Comment by katewarner** [comment]
tst is fixed but there's still a problem with BLAST on prd. 

On prd I still get the network error message if I retrieve the example sequence "P14210" or paste it's sequence into the sequence field and run BLAST. It only seems to occur with this protein, when I try a different accession it works fine.

**Comment by rykahsay** [comment]
Will be fixed when we move to prd on Dec 10

**Comment by katewarner** [comment]
Okay thanks
