### ISSUE TITLE
Isoform Mapper; Sequence and Site mapper examples 

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1957]
On tst and prd, when I try the "Protein Sequence" and "Enter Site Details" examples on the "Sequence and Site Mapper" section of the Isoform Mapper, I get the error "Enter Valid Sequence". I think it should return the isoform "A6NJB7-1"

**Comment by rykahsay** [comment]
@katewarner ... most of the issues you are reporting failures at the frontend level, you will need to report them to Sujeet and then he can point out the API failures that are causing the problem

**Comment by katewarner** [comment]
@rykahsay Apologies I'll pass it on to Sujeet. 

@sujeetvkulkarni Please see above. If it's a backend issue, can you tell us the API failures that are causing this issue?

**Comment by sujeetvkulkarni** [comment]
@katewarner @rykahsay this is a backend issue. Please see details below.

API:
```
https://api.tst.glygen.org/job/addnew

Payload:
{
  "jobtype": "isoform_mapper",
  "sequence": "MDTQGPVSQPFQQPEKPGRVRRRKTRRERNKALVGSRRPLAHHDPPVAIRDPPVVPTASKLVVITQGRLSREHRGLFNHEVKSLDVARLLSSGTLVPGSPTLPAKPSPSPGRAQEPAPRSRDKENQVPGGSGPGPPSSPELSGVGQLLAELQCQLSLPQAFPRRNLIQDARDAIVHTLQACHGCVPDLALVLRGCQPPLPGERPSCPCTPLSFVGSSSASLYASFLCARGQAWGL",
  "intable": [
    [
      "amino_acid_pos",
      "amino_acid"
    ],
    [
      "3",
      "T"
    ],
    [
      "8",
      "S"
    ]
  ],
  "parameters": "{}"
}

response:
{
    "error_list": [
        {
            "error_code": "no-isoform-accessions-found"
        }
    ],
    "result_count": 0
}
```

![Screenshot 2024-12-09 at 9 13 09 PM](https://github.com/user-attachments/assets/c0255809-d85a-4f73-8403-65a61380465d)


https://tst.glygen.org/protein/A6NJB7-1#Isoforms

**Comment by rykahsay** [comment]
I have tried to fix it, please try now

**Comment by katewarner** [comment]
Perfect thanks
