### ISSUE TITLE
GlyGen Mapper issue

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1961]
On tst, when I select the "From ID type" "PubChem Compound" and choose the example IDs below the search field, no matter what "To ID type" I choose (e.g. GNome, GlyCosmos etc.), the results always map to ChEBI. 

This only happens if I use the example IDs, if I input PubChem Compound IDs myself into the search field, then it works and the IDs map to what ever "To ID type" I choose.

**Comment by rykahsay** [comment]
Can you please give me a screenshot of what you have before you submit ? The following seems to be working

<img width="1188" alt="image" src="https://github.com/user-attachments/assets/2e959003-1fb9-4242-ad03-a87a1e00a56e">

**Comment by katewarner** [comment]
This looks like a front end issue as the data seems correct so I'll pass it to @sujeetvkulkarni 

I looked again and it looks like when you run the mapper the first time it maps fine using the example IDs e.g. "From ID: PubChem Compound" > "To ID: GNome" but if you try to run it a second time with the same "FROM ID" and change the "TO ID" to something else e.g. "From ID: PubChem Compound" > "To ID: ChEBI" the results revert to the first ID, in this case GNome. I tried this with several different "From IDs", and it always reverts back to the first "TO ID" you tried. 
1. Run mapper as below using example IDs:
![Untitled1](https://github.com/user-attachments/assets/75714a56-938d-4d78-9386-b2c3b0a906c1)

2. Results map to GNome
![image](https://github.com/user-attachments/assets/ffc3edfc-c7be-4216-a5e1-7c4b51470ca9)
.
3. Run mapper again but change "TO:ID" to ChEBI:
![Untitled2](https://github.com/user-attachments/assets/96b70ee1-41fa-4640-a3b4-374002c7f737)

4. Results map to GNome not ChEBI
![Untitled3](https://github.com/user-attachments/assets/1c46a713-f367-4e49-a82c-1af881b63b74)

**Comment by katewarner** [comment]
@sujeetvkulkarni @rykahsay I think this may actually be a backend issue because this is happening on the API, so I will assign the ticket back to Robel. I've made a new ticket for the API issue #1998

**Comment by sujeetvkulkarni** [comment]
@katewarner yes it is backend issue there are some changes which are needed from frontend which I am working but actual issue is a backend issue.

**Comment by sujeetvkulkarni** [comment]
@katewarner fixed frontend issue - calling list api twice. But this does not fixes the original issue. Original issue is a backend issue - API issue https://github.com/glygener/glygen-issues/issues/1998

**Comment by rykahsay** [comment]
I have fixed issue https://github.com/glygener/glygen-issues/issues/1998

**Comment by katewarner** [comment]
Works great! Thank you both
