### ISSUE TITLE
Modify BLAST request not working 

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1963]
On tst and prd, when I BLAST a protein sequence and get to the results page, if I select "Modify Request" it returns to the BLAST search page but displays a Network error message and the search fields are empty when it should contain the sequence I want to modify.

**Comment by rykahsay** [comment]
@sujeetvkulkarni ... can you please tell me which API call is failing if it is a backend issue?

**Comment by sujeetvkulkarni** [comment]
@katewarner @rykahsay 
Looks like there was a difference in how frontend was expecting "parameters" values and how api response was. I have fixed it.

```
current API response
"query":{
  "jobtype": "blastp",
  "parameters": {
    "seq": "MSIQENISSLQLRSWVSKSQRDLAKSILIGAPGGPAGYLRRASVAQLTQELGTAFFQQQQLPAAMADTFLEHLCLLDIDSEPVAARSTSIIATIGPASRSVERLKEMIKAGMNIARLNFSQHAIAREAEAAVYHRQLFEELRRAAPLSRDPTEVTAIGAVEAAFKCCAAAIIVLTTTGRS",
    "targetdb": "canonicalsequences_all",
    "evalue": 0.001,
    "num_alignments": 250
  }
}
```

**Comment by katewarner** [comment]
Fixed thank you
