### ISSUE TITLE
Blank glycan list page on tst

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1966]
On tst, when you search for a glycan using glycan search the glycan list page is blank e.g. https://tst.glygen.org/glycan-list/e0df9c1dfe74e596df64517b9da9fff1

**Comment by rykahsay** [comment]
I see the page, I do not know why it was blank for you

<img width="1013" alt="image" src="https://github.com/user-attachments/assets/e89f7a56-d88f-4a37-896d-df0cbb9f69ac">

**Comment by katewarner** [comment]
Yes it seems to be fixed now
