### ISSUE TITLE
Glycan Sequence Lookup Tool 

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1967]
The results do not populate for me when I submit the example sequence. I end up being stuck on the searching page: 

![Screenshot 2024-12-02 at 2 36 32 PM](https://github.com/user-attachments/assets/c598778f-5bbe-42e3-9b92-cf1b033b8939)

**Comment by sujeetvkulkarni** [comment]
@ubhuiyan I think @edwardsnj is maintaining https://glylookup.glyomics.org/ codebase/docker. 
@ReneRanzinger @jeet-vora Can you please confirm?

**Comment by edwardsnj** [comment]
Thanks Sujeet for letting me know. I've restarted the server, seems to be working correctly now.

**Comment by ubhuiyan** [comment]
It works fine now. Thanks!
