### ISSUE TITLE
On issues identified at the frontend level

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#1968]
When you find an issue when you are trying to test the frontend, UNLESS you have done the digging and found out the API that is causing he problem, you need to report it to Sujeet not to me.

**Comment by jeet-vora** [comment]
@katewarner @ubhuiyan Please think twice and check thrice before assigning the ticket to Robel for an issue. Lets not give him a chance to complain about it without doing our due diligence.
