### ISSUE TITLE
Need to remove PubMed ID column as it is duplicate of Publication column.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1982]
PubMed ID column and Publication refer to same property publication so need to remove duplicate column PubMed ID.

API: https://api.tst.glygen.org/pages/list_init
Payload: 
{
  "table_id": "glycan"
}

<img width="1598" alt="Screenshot 2024-12-04 at 1 54 11 AM" src="https://github.com/user-attachments/assets/d104ea53-517b-4ce8-b934-fc14b4131d6c">

**Comment by ubhuiyan** [comment]
@sujeetvkulkarni The duplicate has been removed. There should only be Publication in the Annotation box when Robel processes.

**Comment by rykahsay** [comment]
Fixed, check

**Comment by ubhuiyan** [comment]
Resolved.
