### ISSUE TITLE
Need to change PubMed ID column name to Publication as it contains DOI ids too.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1983]
API:
https://api.tst.glygen.org/pages/list_init
Payload:
{
    "table_id": "protein"
}

<img width="1459" alt="Screenshot 2024-12-04 at 2 03 45 AM" src="https://github.com/user-attachments/assets/65931de0-11bf-449d-b8dd-3d1faf011a4e">

**Comment by ubhuiyan** [comment]
@sujeetvkulkarni I have changed PubMed ID to Publications in the fields csv file. When Robel processes this change should reflect on the front-end.

**Comment by ubhuiyan** [comment]
As of note, I also fixed the "Number of Glycoproteins" and "Glycoprotein Count" duplicate to "Protein Count" and kept "Glycoprotein Count". I do not see any additional discrepancies between the front-end display and the back end csv. This should go for ticket #1982 as well. Robel you are free to proceed. I think once you process the updated csv it should fix these issues.

**Comment by rykahsay** [comment]
I have updated, please check

**Comment by ubhuiyan** [comment]
The publication/pubmed ID issue is resolved. 

I am still seeing "Number of Glycoproteins" instead of "Protein Count", @rykahsay do you need to change this in your file? It is already changed in the fields file that I manage.

**Comment by rykahsay** [comment]
Ok, please check now

**Comment by sujeetvkulkarni** [comment]
@ubhuiyan Looks like fixed - https://tst.glygen.org/glycan-list/a7e4068d39c1f9c017cb6f3c069e6ea5
Please close if it is working.
