### ISSUE TITLE
Problem with Biomarker advanced search using Pubmed IDs

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1984]
On tst, when I search for biomarkers using the Pubmed id: "32479790" the results page only contains three biomarkers ([results link](https://tst.glygen.org/biomarker-list/db897e8e80ca2be0afb3a9eee6ee1652)) but it should contain 14 biomarkers ([publication page](https://tst.glygen.org/publication/PubMed/32479790#Biomarkers)). 

This publication is in the publications section of all 14 biomarkers, so I'm wondering if this is a front end problem.

**Comment by sujeetvkulkarni** [comment]
@katewarner was not a front end issue but looks like it is working now.
https://tst.glygen.org/biomarker-list/db897e8e80ca2be0afb3a9eee6ee1652
https://tst.glygen.org/publication/PubMed/32479790#Biomarkers

**Comment by katewarner** [comment]
Okay thanks
