### ISSUE TITLE
Motif images not showing up

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#1993]
Robel please check the below Motif image error seen on both tst and prd.

https://api.glygen.org/glycan/image/GGM.000005/

<img width="1279" alt="image" src="https://github.com/user-attachments/assets/e3b83ea9-2e2f-4906-ac9c-85706739569f">

<img width="1380" alt="image" src="https://github.com/user-attachments/assets/866ce70f-618e-47e6-b278-cf2be3af485d">

@ubhuiyan FYI

**Comment by rykahsay** [comment]
It is fixed now, but you may need to clear your cache ...

<img width="1351" alt="image" src="https://github.com/user-attachments/assets/369ab0b9-f864-436f-b722-ab37fe9bec70">

**Comment by jeet-vora** [comment]
Issue resolved
