### ISSUE TITLE
Problem with SNV data filter in protein results

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1995]
On tst, when I search for Bovine proteins and then filter the results (https://tst.glygen.org/protein-list/9adc030a405819391b69e1704844dfa8) by the data "SNV", it shows 79 proteins. However, I looked at the api/protein/details page of several of these proteins (e.g. P06836, P06836 and Q0VC53) and none of them contain SNV data. Do you know why these are being included in the Bovine results as containing SNV data?

![image](https://github.com/user-attachments/assets/864702bb-2f90-4e16-981f-618c5a01c092)

**Comment by sujeetvkulkarni** [comment]
Bovine protein organism query when applied SNV filter returns 79 entries.
It looks like these results dont have SNV data. Please see if these 79 results are valid.

Page : https://tst.glygen.org/protein-list/9adc030a405819391b69e1704844dfa8


API:
```
https://api.tst.glygen.org/protein/list?query=
{"id":"9adc030a405819391b69e1704844dfa8","offset":1,
"limit":20,"order":"desc","sort":"hit_score",
"filters":[{"id":"by_data","operator":"OR","selected":["SNV"]}],
"columns":["uniprot_canonical_ac","reported_snv","gene_name",
"protein_name","hit_score","organism","length","mass","refseq_name","refseq_ac","uniprot_id"]}
```
![Screenshot 2024-12-09 at 7 43 39 PM](https://github.com/user-attachments/assets/aed59652-42dd-49a2-a57a-bc4b68040f9c)

**Comment by rykahsay** [comment]
I have tried to fix it but l don't know why the "filters panel" is now showing up when I get to the protein list page -- maybe @sujeetvkulkarni  is fixing something.




<img width="1201" alt="image" src="https://github.com/user-attachments/assets/176526eb-7c9b-4dea-beac-7639e2d75784">

**Comment by sujeetvkulkarni** [comment]
@rykahsay filters are not showing up because protein list api is not returning filters.
Same applies to glycan, site and glycosylation table\list page filters.

```
https://api.tst.glygen.org/protein/list?query=
{"id":"af8c4f3ea23eced3bf6fd1cdf6ba1066","offset":1,"limit":20,"order":"desc","sort":"hit_score","filters":[],"columns":["uniprot_canonical_ac","gene_name","protein_name","hit_score","organism","length","mass","refseq_name","refseq_ac","uniprot_id"]}

filters in api response are empty
{
  "applied": [],
  "available": []
}
```

![Screenshot 2024-12-10 at 2 30 58 PM](https://github.com/user-attachments/assets/5c5d9d90-7a07-4847-9740-8384f1342574)

**Comment by rykahsay** [comment]
Corrected now

<img width="1311" alt="image" src="https://github.com/user-attachments/assets/80370f31-c2c9-40e0-a1f0-89c167544995" />

**Comment by katewarner** [comment]
Thank you
