### ISSUE TITLE
Incorrect error codes on tst.api

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1997]
I'm not sure if this is an issue or not, but when I run one of the usecases list APIs i.e. `/usecases/genelocus_list/` or `/usecases/ortholog_list/` without adding an ID, the response body error code that I get on prd says?

```
{
  "error_code": "invalid-parameter-value"
}
```
But on tst  it says something like:
```
{
  "error_list": [
    {
      "error_code": "exception-error-YHNN9P"
    }
  ]
} 
```

**Comment by rykahsay** [comment]
check now

**Comment by katewarner** [comment]
Perfect thanks
