### ISSUE TITLE
idmapping search not working properly on tst.api

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1998]
I think this is related to issue #1961 so I've assigned the ticket back to you.

When I run the /idmapping/search/ on the API, the first time it runs with no problems but when I run it a second time **with the same proteins but different "output_namespace"**, it generates the same "list_id" as the first search and so maps to the first "output_namespace".e.g. 

1. I ran the example search for the /idmapping/search/ mapping to "GeneID": 
<img src="https://github.com/user-attachments/assets/fdffd732-ddf8-4c58-932f-fd707167c757" width="500">

and generated the "list_id":
<img src="https://github.com/user-attachments/assets/9e3d7547-f124-4ddd-aef8-23d775954ac8" width="500">

2. I ran the generated "list_id" in the /idmapping/list/ and got the correct results:
<img src="https://github.com/user-attachments/assets/350e6b82-b2d5-4789-b8a3-f23bd5330aa4" width="400">

3. I then ran the /idmapping/search/ **with the same proteins** but mapping to "RefSeq": 
<img src="https://github.com/user-attachments/assets/fbf98299-06e8-465f-9f00-54c2ab99ca51" width="400">

and generated the "list_id", which I think is identical to the "list_id" generated in step 1:
<img src="https://github.com/user-attachments/assets/c73593ef-ca4d-4cd2-97f7-850b2560d1b1" width="400">

4. I ran the "list_id" generated in step 3 in the /idmapping/list/ and it maps to "GeneID" not "RefSeq":
<img src="https://github.com/user-attachments/assets/6bd78939-b4c1-4e09-9058-6cb3e4813b1c" width="400">

5.  However, I then ran the /idmapping/search/ **with different proteins** mapping to "RefSeq" and it worked correctly:

<img src="https://github.com/user-attachments/assets/1dfff4ae-08ea-463e-a171-599eca8d8176" width="200">

<img src="https://github.com/user-attachments/assets/47e4e15f-d3fb-4d07-a19a-44dbbc160fe5" width="400">

<img src="https://github.com/user-attachments/assets/1b71fb8c-43e8-4a78-b3f6-064b9c8ce24a" width="400">

So it looks like it's a problem with the API `https://api.glygen.org/idmapping/search/` producing the same "list_id" as your first search if you use the same protein. This doesn't happen on prd, on prd it maps to the correct namespace even if you use the same proteins as the first search.

**Comment by rykahsay** [comment]
Good catch! I have tried to fix it, please check.


<img width="1083" alt="image" src="https://github.com/user-attachments/assets/13284279-ef22-4148-b63c-3cb525d764f6">

<img width="1071" alt="image" src="https://github.com/user-attachments/assets/a39c7d55-14a9-4ec6-9405-2cf870ab792a">

**Comment by katewarner** [comment]
Works perfectly, thanks
