### ISSUE TITLE
Script for creating BCOs automatically

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#2]
@jeet-vora and @kmartinez834 to create BCO templates for glycan, protein, proteoform, etc. and save as generated/misc/*_bco_template.json (where * is glycan, protein, proteoform, etc)

**Comment by jeet-vora** [comment]
Protein and Proteoform templates are here (Please note I have added Jeet, Karina and Robel as constant authors)

1. /data/projects/glygen/generated/misc/bco_protein_template.txt
2. /data/projects/glygen/generated/misc/bco_proteoform_template.txt

**Comment by kmartinez834** [comment]
**Glycan template is here:**
/data/projects/glygen/generated/misc/bco_glycan_template.json

@jeet-vora I found a couple differences between our templates. I think we should go with the most updated spec/schema versions from biocomputeobject.org, but let me know if you disagree:

 - "spec_version"
   - biocomputeobject.org: "https://w3id.org/ieee/ieee-2791-schema/2791object.json"
   - data.glygen.org: "1.3.0"
- "extension_schema"
  -  biocomputeobject.org: "http://www.w3id.org/biocompute/extension_domain/1.2.0/dataset/dataset_extension.json"
  - data.glygen.org: "http://www.w3id.org/biocompute/extension_domain/1.1.0/dataset/dataset_extension.json"
- "execution_domain"
  - Include script uri and file name?

**Comment by jeet-vora** [comment]
@kmartinez834 I think your third point refers to "execution_domain" instead of "extension_domain"

It looks like for most cases URI is the required field, access_time, filename and SHA checksum are not required fields
![image](https://user-images.githubusercontent.com/25825266/217079974-6eea5c8a-c083-4e6e-9dec-d0ca13639261.png)

Will still confirm it with Hadley.  #21

Also error-domain is optional so we can remove it from our template. We can let Robel know about it.

**Comment by kmartinez834** [comment]
@jeet-vora you are correct, it should be "execution_domain"

Updating original comment for clarification

**Comment by kmartinez834** [comment]
Per discussion on 2/15, we will update templates with the following:

```
"spec_version": "https://w3id.org/ieee/ieee-2791-schema/2791object.json"

"extension_schema": "http://www.w3id.org/biocompute/extension_domain/1.2.0/dataset/dataset_extension.json"

#path to include same dataset maker script as in pipeline steps field
"execution_domain": {
    "script": [
            {
                "uri": {
                    "uri": "https://github.com/glygener/glygen-backend-integration/blob/master/dataset-maker/make-species-agnostic-dataset.py",
                    "filename": "make-species-agnostic-dataset.py"
                }
            }
        ]
}
```

Check when completed:

- [x] /data/projects/glygen/generated/misc/bco_protein_template.txt
- [x] /data/projects/glygen/generated/misc/bco_proteoform_template.txt
- [x] /data/projects/glygen/generated/misc/bco_glycan_template.json

**Comment by kmartinez834** [comment]
The following templates are saved at /data/projects/glygen/generated/bco_templates/

glycan.1.json
protein.1.json
protein_citations.json
protein_citations_matrixdb.json
protein_xref.json
proteoform.1.json
