### ISSUE TITLE
Backend documentation for data integration in Sharepoint

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#20]
Update files:
[Data integration](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/[data_integration.docx](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/data_integration.docx?d=w0c84e59c4be6494d91cc017661cc9944&csf=1&web=1&e=jB5mgG)?d=w0c84e59c4be6494d91cc017661cc9944&csf=1&web=1&e=jB5mgG)

Add additional files as needed to [Backend folder](https://gwu0.sharepoint.com/:f:/r/sites/GlyGenTeam-GRP/Shared%20Documents/[Backend](https://gwu0.sharepoint.com/:f:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend?csf=1&web=1&e=Uu70bh)?csf=1&web=1&e=Uu70bh)

**Comment by rykahsay** [comment]
I have created the document. If you have anything to add in each sections (without modifying the sectioning), please do so
