### ISSUE TITLE
GlyGen Header missing on API portal

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#200]
Robel the GlyGen header is missing on the newly implemented swagger tst/beta API portal. See the ss below

https://api.glygen.org/
![image](https://user-images.githubusercontent.com/25825266/229200092-50f3cd59-c647-4c2c-b2c1-ef4c8e9d95b1.png)

https://beta-api.glygen.org/
![image](https://user-images.githubusercontent.com/25825266/229200403-3a1f22f3-7dd6-4c16-aaf9-e2d6703e0f8b.png)

@JingyueWu @kmartinez834

**Comment by JingyueWu** [comment]
Confirmed on my end.

**Comment by rykahsay** [comment]
This is moved to #230  for 2.1
