### ISSUE TITLE
Simple protein pathway search returns incorrect entries

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#2015]
Similar to the advanced search issue on tst (#1940), I think the Protein simple search > Pathway should only return exact matches.

When I tested the example "hsa:3082" it should only return the result "P14210-1", but instead it also returns partial matches "Q9P0U4-1" which has the pathway "hsa:30827", and "Q9NZI2-1" which has the pathway "hsa:30820". These are not the same pathways as "hsa:3082" so I think the 'Pathway' category search should only return exact matches not partial matches.

**Comment by rykahsay** [comment]
It is a text search and I cannot make it exact (MongoDB does not allow me) --- we have to live with this.

**Comment by katewarner** [comment]
Okay no problem
