### ISSUE TITLE
Organism search on protein search api not working

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#2017]
I found an issue with the api: https://api.glygen.org/protein/search/ 

I was trying to retrieve all the proteins for an organism but got an exception error message. I tried searching for "human", "homo sapiens", "906", and "Homo sapiens (9606)" and still got an error message

![image](https://github.com/user-attachments/assets/1a4ed344-83c6-4cc5-91bd-536292608453)

![image](https://github.com/user-attachments/assets/6363f5bd-74d3-45b6-8a48-8b2211f0123e)

**Comment by rykahsay** [comment]
I will fix the error response but the expected query is 

{"organism":{"id":9606}}
or
{"organism":{"name":"Human"}}

**Comment by katewarner** [comment]
@rykahsay Thank you that works. Can you also update the example for organism in the [request.schema.json](https://github.com/glygener/glygen-backend-api/blob/master/specs/protein/search/request.schema.json). This is what I was following:
```
        },
        "organism": {
          "$id": "/properties/query/properties/organism",
          "type": "object",
          "description": "This field is set if a search by organism (e.g. human) is performed. The value can either be a scientific species name (NCBI Taxonomy), a synonym or a NCBI Taxonomy ID.",
          "default": "Homo sapiens (9606)",
          "examples": [
            "Homo sapiens (9606)"
```

**Comment by rykahsay** [comment]
Done, see on the 2.7 branch

**Comment by katewarner** [comment]
Many thanks
