### ISSUE TITLE
I do not see Bovine in the Super Search 

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#2021]
![Screenshot 2024-12-17 at 2 17 46 PM](https://github.com/user-attachments/assets/0bc165ba-f263-4310-9ec2-38fdd5d5f743)

**Comment by sujeetvkulkarni** [comment]
Supersearch init api needs to add Bovine name and taxid.

API:
https://api.glygen.org/supersearch/search_init?query={}


<img width="1596" alt="Screenshot 2024-12-17 at 9 38 37 PM" src="https://github.com/user-attachments/assets/a0069ab5-5347-4fef-979a-3e5590f8945a" />

**Comment by rykahsay** [comment]
please check now

<img width="984" alt="image" src="https://github.com/user-attachments/assets/99b84d4e-28c0-4aec-a9a5-7f2ae4110212" />

**Comment by ubhuiyan** [comment]
Looks good
