### ISSUE TITLE
Bovine missing following all proteins search

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#2022]
On protein advanced search, if I select search to get all proteins, the results page is missing Bovine proteins.

![image](https://github.com/user-attachments/assets/192aa706-5046-403a-b2ae-2b65d2c95337)

I think this may be a front end issue because the protein/search_init/ does contain Bovine: 

![image](https://github.com/user-attachments/assets/e88c2aec-b922-405a-bbae-4c0ec4ee8474)

**Comment by sujeetvkulkarni** [comment]
@katewarner this is a backend issue. 
Bovine Filter is not showing because list api is not returning Bovine filter.
```
API:

https://api.glygen.org/protein/list?query=
{"id":"f3da238e7ac37cc5058f73be99cb434d","offset":1,"limit":20,
"order":"desc","sort":"hit_score","filters":[],"columns":["tax_id","uniprot_canonical_ac",
"gene_name","protein_name",
"hit_score","organism","length","mass","refseq_name","refseq_ac","uniprot_id"]}
```

![Screenshot 2024-12-18 at 8 24 09 AM](https://github.com/user-attachments/assets/4e612eaf-7711-4f6e-ae87-291d9c7d732b)

**Comment by katewarner** [comment]
@rykahsay Bovine is listed on a filter on tst https://tst.glygen.org/protein-list/f3da238e7ac37cc5058f73be99cb434d

**Comment by rykahsay** [comment]
Please try now:

<img width="1073" alt="image" src="https://github.com/user-attachments/assets/14cbde5f-35de-45d8-baa8-6ae4b552b476" />

**Comment by katewarner** [comment]
Fixed
