### ISSUE TITLE
Protein PTM annotation download not working

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#2023]
On the protein pages, the download for "PTM Annotation" is not working. The throbber icon appears for a few seconds but the download doesn't begin.

https://www.glygen.org/protein/P31749-1#PTM-Annotation

![image](https://github.com/user-attachments/assets/42920619-a3d9-4e24-9613-4ffecc78164e)

**Comment by sujeetvkulkarni** [comment]
Backend issue: 
500 INTERNAL SERVER ERROR API response for section_download API with "download_type":"protein_section" and "section":"ptm_annotation" parameters.

```
API:
https://api.glygen.org/data/section_download?query=
{"id":"P31749-1","download_type":"protein_section","section":"ptm_annotation",
"format":"csv","compressed":false}

response:
{
  "error_list": [
    {
      "error_code": "exception-error-5MNEFL"
    }
  ]
}
```

![Screenshot 2024-12-18 at 9 02 09 AM](https://github.com/user-attachments/assets/e9b7be2f-be6c-4239-9f88-a7083863ad28)

**Comment by rykahsay** [comment]
Please check now

**Comment by katewarner** [comment]
Fixed
