### ISSUE TITLE
Organism protein search is missing proteins  

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#2025]
When you carry out a search to find all the proteins for an organism, or you try to retrieve all the proteins in GlyGen, a number or organisms (Arabidopsis, Human, Mouse, Pig and Rat) are missing proteins in their results list. 

The numbers on tst are correct and match the numbers in the datasets: https://tst.glygen.org/protein-list/f3da238e7ac37cc5058f73be99cb434d
https://tst.glygen.org/protein-list/f3da238e7ac37cc5058f73be99cb434d

![image](https://github.com/user-attachments/assets/3ce84742-b7d7-4ac6-bf7f-87f06a4ec6d2)

The numbers on prd for Arabidopsis, Human, Mouse, Pig and Rat are not correct: https://www.glygen.org/protein-list/f3da238e7ac37cc5058f73be99cb434d

![image](https://github.com/user-attachments/assets/73c4dc0f-492d-4e50-8fa1-30ce663434ee)

Arabidopsis 27385/27448 = 63 missing proteins
Human 20579/20654 = 75 missing proteins
Mouse 21713/21750 = 37 missing proteins
Pig 22733/22782 = 49 missing proteins
Rat 22362/22456 = 94 missing proteins

**Comment by rykahsay** [comment]
Please check now

<img width="1142" alt="image" src="https://github.com/user-attachments/assets/1fc86653-4cd5-4bc2-a48d-6dad00d5da7b" />

**Comment by katewarner** [comment]
Looks good
