### ISSUE TITLE
Glycan with Motif Download Not Working

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#2026]
CSV won't download when selecting it in the Motif Details for GGM.000001 in the Glycan with Motif section. 
![Screenshot 2024-12-18 at 12 34 10 PM](https://github.com/user-attachments/assets/bb5a3d5d-76d6-4c21-ade2-7575ad02d22d)

**Comment by rykahsay** [comment]
Please try now

**Comment by ubhuiyan** [comment]
works now.
