### ISSUE TITLE
Downloads failing for Expression Tissue and Expression Disease sections 

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#2027]
On the protein pages, the downloads for the "Expression Tissue" and "Expression Disease" sections are not working. The throbber icon appears for a few seconds but the download doesn't begin.

It looks like the section_download API call may be failing for both "Expression Tissue" and "Expression Disease".

<img src=https://github.com/user-attachments/assets/cea3a656-be9a-4f02-aae2-328b62f986a2 width="400" />

**Comment by rykahsay** [comment]
Please checl now

**Comment by katewarner** [comment]
Fixed
