### ISSUE TITLE
"Fully Defined" Filter not Found in glycan "By Sequence Details" Section of List Page

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#2028]
![Screenshot 2024-12-18 at 2 36 20 PM](https://github.com/user-attachments/assets/9fa9ee1c-b395-453e-806f-1c6581a9de5a)

**Comment by sujeetvkulkarni** [comment]
@ubhuiyan backend issue.
glycan/list api is not returning "Fully Defined" Filter option.

API:
```
https://api.glygen.org/glycan/list?query=
{"id":"a7e4068d39c1f9c017cb6f3c069e6ea5","offset":1,"sort":"hit_score","limit":20,"order":"desc","filters":[],"columns":["glytoucan_ac","image_url","hit_score","mass","publication"]}
```

![Screenshot 2024-12-19 at 11 50 54 AM](https://github.com/user-attachments/assets/3430e8c3-f07b-475b-ac2c-60d3fb1b05e6)

**Comment by rykahsay** [comment]
please check now

<img width="1221" alt="image" src="https://github.com/user-attachments/assets/20eec32f-5264-4379-be20-498b09f4a2aa" />

**Comment by ubhuiyan** [comment]
looks good
