### ISSUE TITLE
HGNC link has changed

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#2029]
The base url for the HGNC links on the protein pages has changed and no-longer works. 

I've updated the xref_info.csv file to the following, is it too late to update the protein pages? 

`protein_xref_hgnc,HGNC,https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:%s,9020|11551|14499`

**Comment by rykahsay** [comment]
I am labeling such cases which were missed during testing period -- it's too late for me to fix it, we will have to live with them in 2.7

**Comment by katewarner** [comment]
moved to 2.8
