### ISSUE TITLE
Expression Tissue term does not match Uberon term

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#203]
Verify source file of UBERON terms for Bgee:

https://tst.glygen.org/protein/Q9BYF1-1#Expression-Tissue

![image](https://user-images.githubusercontent.com/90285371/229208437-c96c18dc-0433-4dbb-92cc-d6e38fdc40e6.png)

![image](https://user-images.githubusercontent.com/90285371/229208477-a2051ffd-c69b-47ea-a991-0fcda2b9d6a4.png)

**Comment by kmartinez834** [comment]
@rykahsay --> `expression_tissue.tissue.name` in API does not match dataset for UBERON:0005200 (should be thoracic mammary gland)

```
$ grep "Q9BYF1-1.*0005200" /data/shared/glygen/releases/data/v-2.0.3/reviewed/human_protein_expression_normal.csv
"Q9BYF1-1","UBERON:0005200","thoracic mammary gland","HsapDv:0000087","human adult stage (human)","MEDIUM","MEDIUM","GOLD","1.97E+04","64.18","protein_xref_bgee","ENSG00000130234"
```

https://api.tst.glygen.org/protein/detail/Q9BYF1-1
``` json
{
		"tissue": {
			"name": "Breast",
			"namespace": "UBERON",
			"id": "0005200",
			"url": "http://purl.obolibrary.org/obo/UBERON_0005200"
		},
```

**Comment by rykahsay** [comment]
The mapping comes from the 2nd and 4th fields of "generated/misc/doid2uberonid_mapping.csv".
Please edit whatever version "generated/misc/doid2uberonid_mapping.csv " is pointing  to and let me know when you are done.


<img width="1352" alt="image" src="https://user-images.githubusercontent.com/20584876/229633268-5f3f21ac-dccf-49f0-bc51-bcfe1c766f83.png">

**Comment by kmartinez834** [comment]
@rykahsay --> Done, updated misc/doid2uberonid_mapping_v5.csv

**Comment by rykahsay** [comment]
Please check

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/20584876/230432691-f77bed5d-a018-4930-bdcc-ffd9b4f61064.png">

**Comment by kmartinez834** [comment]
👍
