### ISSUE TITLE
Glycosylation download csv file is empty

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#2031]
When I try to download tables from the Glycosylation table (Reported with Glycan, Reported sites etc.) the table downloads but when I open the csv file it's blank. 

![image](https://github.com/user-attachments/assets/21dc0f86-b77e-431a-95a5-4b52a7f9cd63)

This also happens when you try it through the api api.glygen.org/data/section_download/

**Comment by ubhuiyan** [comment]
This is also the case with the Glycosylation download within the Publications Detail page.

**Comment by rykahsay** [comment]
Please try now

**Comment by katewarner** [comment]
Fixed
