### ISSUE TITLE
Proteoform Annotation download isn't working

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#2032]
On the protein pages, the download for "Proteoform Annotation" is not working. The throbber icon appears for a few seconds but the download doesn't begin e.g. https://www.glygen.org/protein/P02751-15#Proteoform-Annotation

When I try the section download on the api, I get an exception error:

```
{
  "error_list": [
    {
      "error_code": "exception-error-XBKAEG"
    }
  ]
}
```

**Comment by rykahsay** [comment]
Please check now

**Comment by katewarner** [comment]
Fixed
