### ISSUE TITLE
Protein Ontology xref link is broken on protein pages

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#2033]
The "protein_xref_pro_proteoform" base url has changed and so the PRO xref link no longer works, e.g. https://www.glygen.org/protein/P02751-15#Proteoform-Annotation 

![image](https://github.com/user-attachments/assets/a08cc1c8-bcfa-457b-9894-4b4f50b8f203)

I've corrected the base url in the xref_info.csv (see below), if possible for 2.7 please update the protein pages to correct the broken link

`protein_xref_pro_proteoform,PRO,https://proconsortium.org/cgi-bin/entry_pro?id=%s,PR:000050601|PR:000051541|PR:000058420
`

**Comment by rykahsay** [comment]
We have to live with it in 2.7

**Comment by katewarner** [comment]
moved to 2.8
