### ISSUE TITLE
Expression Download in Publications Detail Page Not Working

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#2034]
![Screenshot 2024-12-19 at 9 44 17 AM](https://github.com/user-attachments/assets/b796e49e-2d19-437e-ae9c-86f462001b7e)

**Comment by rykahsay** [comment]
Please make your screenshots such that I can see which page you are on

-- please check if the issue still persists

**Comment by ubhuiyan** [comment]
It works now.
