### ISSUE TITLE
MatrixDB xref link in broken

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#2036]
The base url for MatrixDB has changed, so the MatrixDB link in the glycan ligands section returns a blank page. 
I've updated the MatrixDB xref in the xref_info.csv (see below). If possible please update the links in the protein pages.

`glycan_xref_matrixdb,MatrixDB,https://matrixdb.univ-lyon1.fr/biomolecule/%s,GAG_7|GAG_2|GAG_1
`

**Comment by rykahsay** [comment]
I am labeling such cases which were missed during testing period -- it's too late for me to fix it, we will have to live with them in 2.7

**Comment by katewarner** [comment]
moved to 2.8
