### ISSUE TITLE
Limited version history view on data.glygen.org

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#2039]
![Screenshot 2024-12-19 at 11 01 43 AM](https://github.com/user-attachments/assets/5116a465-2dd6-4885-917a-d6d448b5b8d6)
When you select version history for GLY_000001 (for example) you can only see 2.7. I think we should provide access to all versions.

**Comment by rykahsay** [comment]
Please check now

<img width="701" alt="image" src="https://github.com/user-attachments/assets/1e1bf3f0-04e1-40e7-a400-a199901743ee" />

**Comment by ubhuiyan** [comment]
Looks good.
