### ISSUE TITLE
Rebekahs image on about us squeezed

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#204]
On the about us page the image of Rebekah is horizontally squeezed. I think the problem is that its no a square. Crop the picture to make it square.

**Comment by sujeetvkulkarni** [comment]
aa523d0bd987790381cd77c7f1b7875b30df3874

**Comment by sujeetvkulkarni** [comment]
9a8468a636c940406a2a75b811408cc47b6050bd
