### ISSUE TITLE
Hit Score issue for glycan and proteins

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#2040]
**Glycan**

https://www.glygen.org/glycan-list/a7e4068d39c1f9c017cb6f3c069e6ea5 | [G17689DH](https://www.glygen.org/glycan/G17689DH)
The hit score is 0 for Defined structural information, Enzyme annotations, Protein annotations and Species annotations which is incorrect.

<img width="1145" alt="image" src="https://github.com/user-attachments/assets/5689a06a-d5af-480d-afc1-61a09e9a8423" />

**Protein**

Similarly it is 0 for most of the protein properties. | [P14210-1](https://www.glygen.org/protein/P14210-1)

https://www.glygen.org/protein-list/af8c4f3ea23eced3bf6fd1cdf6ba1066 | 
<img width="1122" alt="image" src="https://github.com/user-attachments/assets/f692185d-747d-479e-80bf-d3ec24956116" />

**Comment by rykahsay** [comment]
Please check now

**Comment by jeet-vora** [comment]
@rykahsay The Glycan and Protein hit score still have issues. The other glycan properties than the structural info still are 0. Protein properties are still zero.

**Comment by rykahsay** [comment]
Please check now

<img width="1056" alt="image" src="https://github.com/user-attachments/assets/448ad23e-81b8-423e-8cc2-38223e55a2da" />

<img width="812" alt="image" src="https://github.com/user-attachments/assets/25138efe-a6ba-49ba-b610-808c66414755" />

**Comment by jeet-vora** [comment]
Resolved
