### ISSUE TITLE
Tab greying

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#205]
Can the tabs that do not have information can be greyed out more to distinguish between tabs having data. For eg tabs in Glycosylation, SNV?

If the feature can be implemented easily we should implement.

https://beta.glygen.org/protein/Q9HBG4-1#Glycosylation
In the example only the text mining tab has data.

![image](https://user-images.githubusercontent.com/25825266/229524613-94990111-fd8a-4a35-a289-fcaa3cf2043b.png)

**Comment by ReneRanzinger** [comment]
@sujeetvkulkarni Do we use this anywhere? I dont think it would be a big issues but we have to do it in all places that have tabs. So I see this as an improvement for 2.1.

**Comment by sujeetvkulkarni** [comment]
@jeet-vora please look at screen shot below. Rene suggested to keep background color same and to change the text color. Also the tabs with no data will be non clickable.

<img width="1143" alt="Screenshot 2023-07-19 at 8 30 15 PM" src="https://github.com/glygener/glygen-issues/assets/13891482/72fd8a32-58bc-4d19-b36a-6c45aa515572">

**Comment by jeet-vora** [comment]
@ReneRanzinger @sujeetvkulkarni 
No issues. Looks good.

**Comment by ReneRanzinger** [comment]
@sujeetvkulkarni Not sure about the color code you are using but I would make the text even lighter. Go to the middle between the current color and the background color. Lets see how this looks.

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger I have made the color lighter please see below screen shot.
<img width="1164" alt="Screenshot 2023-07-20 at 6 42 55 PM" src="https://github.com/glygener/glygen-issues/assets/13891482/72848b58-8868-4d2f-a260-85f33bd4e695">

**Comment by ReneRanzinger** [comment]
@sujeetvkulkarni I think that is better.

**Comment by sujeetvkulkarni** [comment]
436db692d833be9f83508e62f3beb347accf6b75
