### ISSUE TITLE
BCO specs questions

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#21]
Hi Hadley and Tianyi,

Can you answer the below

1. Can you point us to the most recent specs of BCO that includes all the domains and also the example?
2. Is this the latest extension_schema - https://w3id.org/biocompute/extension_domain/1.1.0/scm/scm_extension.json?
3. Is there any documentation on dataset extension schema?
4. For most domain properties are filename, SHA checksum, access_time optional fields? including in the IO domain, description domain? Only URI is a required field?
5. Is error_domain an optional domain?
Thanks

@kmartinez834

**Comment by tiwa1154** [comment]
Hi @jeet-vora Jeet,

To answer your questions:
1. Specs for each domain: https://github.com/biocompute-objects/BCO_Specification/tree/main/ieee-2791-schema
2. Correct. Information can be found at https://github.com/biocompute-objects/extension_domain/tree/main/dataset
3. https://github.com/biocompute-objects/extension_domain/tree/main/dataset
4. In most domains, 'name' and 'uri' are required fields. SHA checksum is usually not required but the current portal triggers an error with empty SHA_checksum fields, to fix this, please refer to https://wiki.biocomputeobject.org/index.php?title=Common_errors. We can also have a call to show you how to fix the issue.
5. Error domain is optional

**Comment by HadleyKing** [comment]
@jeet-vora 
> Hi Hadley and Tianyi,
> 
> Can you answer the below

> 2. Is this the latest extension_schema - https://w3id.org/biocompute/extension_domain/1.1.0/scm/scm_extension.json?

This is the root repo for extension domains that are maintained by us: https://github.com/biocompute-objects/extension_domain

https://w3id.org/biocompute/extension_domain/1.2.0/scm/scm_extension.json
is the most recent version. We needed to update it to add an additional term for ARGOS.

> 3. Is there any documentation on dataset extension schema?

Here is the [README](https://github.com/biocompute-objects/extension_domain/tree/1.2.0/dataset) for it.

> 5. Is error_domain an optional domain?
