### ISSUE TITLE
Need to use Google analytics 4 (GA4) property for glygen website and subdomain.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#214]
Google analytics warning for old property.
----
On July 1, 2023, this property will stop processing data. Starting in March 2023, for continued website measurement, migrate your original property settings to a Google Analytics 4 (GA4) property, or they'll be copied for you to an existing GA4 property, reusing existing site tags.
----

Currently both properties are working.
We have migrated to Google analytics 4 (GA4) property and need to use different id for tracking - G-47WSZ1WYRZ.
I don't think we can have different filters for bots, subdomains etc. So need to need look into ways to do that.

---
Install the Google tag manually
Below is the Google tag for this account. Copy and paste it in the code of every page of your website, immediately after the <head> element. Don’t add more than one Google tag to each page.

```
<script async src="https://www.googletagmanager.com/gtag/js?id=G-47WSZ1WYRZ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag() {
    dataLayer.push(arguments);
  }
  gtag("js", new Date());
  gtag("config", "G-47WSZ1WYRZ");
</script>
```

**Comment by jeet-vora** [comment]
@sujeetvkulkarni This is for Robel to implement the changes right?

**Comment by sujeetvkulkarni** [comment]
> @sujeetvkulkarni This is for Robel to implement the changes right?

@jeet-vora Yes, but you can look at different settings available in new property and how that can used to generate reports and collect data, specifically related subdomains, bot filtering etc.

**Comment by rykahsay** [comment]
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/20584876/230206440-a927bb9b-e5f2-45c2-9e89-57e3c775ab52.png">

<img width="805" alt="image" src="https://user-images.githubusercontent.com/20584876/230206168-c7d96294-8752-40c0-a452-2489fa730d3b.png">

**Comment by rykahsay** [comment]
As for the API subdomain, I need to look into ways of modifying the automatically generated swagger UI from flask-restx.

**Comment by sujeetvkulkarni** [comment]
frontend changes git - 68bdcccac3f1bc7aa56a2882e3610d764d5b8586, aa523d0bd987790381cd77c7f1b7875b30df3874

**Comment by rykahsay** [comment]
Remaining task is in a new issue #230 for 2.1
