### ISSUE TITLE
API /glycan​/detail​/G49108TO​/ does not load

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#215]
The Swagger API /glycan​/detail​/G49108TO​/ on https://api.tst.glygen.org/ does not load for me even after 30mins.
Even the https://api.tst.glygen.org/test does not work.

![image](https://user-images.githubusercontent.com/25825266/229587847-ac87e887-d505-4e89-840f-d51127f45512.png)

**Comment by rykahsay** [comment]
<img width="776" alt="image" src="https://user-images.githubusercontent.com/20584876/229642978-3765fbb0-9513-46bb-9a03-49243441e352.png">
