### ISSUE TITLE
Organism evidence for G49108TO

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#216]
Karina can you check why the below databases are not listed as evidence for the organism for glycan G49108TO

O-GlcNAc Database
O-GlcNAc Atlas

**O-GlcNAc Database**
    Human GLY_000517
    Mouse GLY_000631
    Rat GLY_000632
    Fruitfly GLY_000633

**O-GlcNAc Atlas**
    Human GLY_000708
    Mouse GLY_000709
    Rat GLY_000710
    Fruitfly GLY_000711

In Mouse, Rat and Fruifly it show GlyGen as evidence badge with O-GlcNAc Database dataset IDs as links

*The Glycan detail API does not load the json response for G49108TO for me. #215 

https://tst.glygen.org/glycan/G49108TO
![image](https://user-images.githubusercontent.com/25825266/229586949-92478a6d-bfe5-4f12-915c-75033c2a5851.png)

**Comment by kmartinez834** [comment]
@edwardsnj please add the following datasets to your processing pipeline:

- https://beta-data.glygen.org/GLY_000517
- https://beta-data.glygen.org/GLY_000708
- https://beta-data.glygen.org/GLY_000709
- https://beta-data.glygen.org/GLY_000710
- https://beta-data.glygen.org/GLY_000711

**Comment by kmartinez834** [comment]
Please check

https://tst.glygen.org/glycan/G49108TO
![image](https://github.com/glygener/glygen-issues/assets/90285371/20b3a650-d9ab-4706-8764-883a466bf51b)

**Comment by jeet-vora** [comment]
Yeast is missing. Based on our discussion it will be added in next release. Assigning the ticket back to @kmartinez834 to take it forward or to create a new ticket.
