### ISSUE TITLE
Info missing for G49108TO

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#217]
The glycan detail API for G49108TO is not working #215 so cannot attach json snippet.

The information from **O-GlcNAc Atlas** is missing in the sections below (no badges and/or info)
- species (Karina is looking into it)
- glycoprotein
- expression
- crossref
- publication

The information from **O-GlcNAc Database** is missing in the sections below (no badges and/or info)
- species (Karina is looking into it)
- crossref
- publication

P01106-1 Thr58 is currently present in the glycoprotein section. The data is from GlyConnect, UniCarbKB and so on.. P01106-1 Thr58 is present in the dataset human_proteoform_glycosylation_sites_oglcnac_atlas.csv however it is not present in the API. 

Please check and if possible include it in the current response?

@kmartinez834

**Comment by rykahsay** [comment]
I don't understand what the issue is -- I thought I explained what you should expect.
