### ISSUE TITLE
Update the xref fields for human_proteoform_glycosylation_sites_o_gluc.csv

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#218]
1)
The human_proteoform_glycosylation_sites_o_gluc.csv dataset lists the src_xref_id as GLY_000704 however after the migration to BioCompute Portal the BCO wasn't migrated and a new BCO had to be created which is GLY_000716. Please update the src_xref_id.

2) Add the protein_xref_glygen_ds and GLY_000704 in the xref_key and xref_id so that the evidence points to the GlyGen dataset GLY_000716 .

**Current**
| uniprotkb_canonical_ac | glycosylation_site_uniprotkb | amino_acid | saccharide | glycosylation_type | xref_key                     | xref_id  | src_xref_key           | src_xref_id |
| ---------------------- | ---------------------------- | ---------- | ---------- | ------------------ | ---------------------------- | -------- | ---------------------- | ----------- |
| O43897-1               | 596                          | Ser        | G71142DF   | O-linked           | protein_xref_prosite_prorule | PRU00076 | protein_xref_glygen_ds | GLY_000704  |

**New**
| uniprotkb_canonical_ac | glycosylation_site_uniprotkb | amino_acid | saccharide | glycosylation_type | xref_key                     | xref_id    | src_xref_key           | src_xref_id | … |
| ---------------------- | ---------------------------- | ---------- | ---------- | ------------------ | ---------------------------- | ---------- | ---------------------- | ----------- | - |
| O43897-1               | 596                          | Ser        | G71142DF   | O-linked           | protein_xref_glygen_ds       | GLY_000704 | protein_xref_glygen_ds | GLY_000704  | … |
| O43897-1               | 596                          | Ser        | G71142DF   | O-linked           | protein_xref_prosite_prorule | PRU00076   | protein_xref_glygen_ds | GLY_000704  | … |

**Comment by rykahsay** [comment]
check dataset now --

**Comment by jeet-vora** [comment]
No issues
