### ISSUE TITLE
Datasets part of Nathan's workflow?

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#219]
Can you ensure these datasets are part of Nathan's workflow? These contain GlyTouCan Ac and UniProtKB Ac and organism info.

O-Glucosylation Data
Human GLY_000716

**O-GlcNAc Database**
Human GLY_000517
Mouse GLY_000631
Rat GLY_000632
Fruitfly GLY_000633

**O-GlcNAc Atlas**
Human GLY_000708
Mouse GLY_000709
Rat GLY_000710
Fruitfly GLY_000711

**Comment by kmartinez834** [comment]
See issue #216
