### ISSUE TITLE
Glycan ChEBI submission Training with Dan

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#22]
Dan, 

Before us meet on Thursday (2/9), please go over the tutorial and glycan list in this folder and try to submit one base composition glycan to ChEBI:
https://gwu0.sharepoint.com/:f:/r/sites/GlyGenTeam-GRP/Shared%20Documents/ChEBI%20Submission?csf=1&web=1&e=3gPb25

**Comment by danlymangw** [comment]
Training completed on 2/16/23
