### ISSUE TITLE
Create a list of external speakers with their collaboration/data status

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#220]

**Comment by JingyueWu** [comment]
@jeet-vora not sure what you want me to do with this task - please either close it or provide more information.

**Comment by jeet-vora** [comment]
Have created the file - https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Outreach/Monthly%20Webinars/Webinar%20Speakers.docx?d=wcc9d968a8c5e44d5b0345c7d7d58f204&csf=1&web=1&e=axzfV5
