### ISSUE TITLE
Contact Michelle Gigleo to talk about CFDE and DRS

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#226]
Hi Michelle,

it was nice talking to you today. It would be great if we can meet with you/people from your group to talk about:
- DRS in general
- CFDE CC plans for DRS
- how a DRS implementation on our side would help CFDE CC

Let us know what a good day/time would be to have this chat.

All the Best,
  René

**Comment by jeet-vora** [comment]
DRS Meeting was held on APril 20, 2023. Felix and Anup provided initial guidance and shared documentation.
