### ISSUE TITLE
ASW containers stopped

### ISSUE THREAD

**Issue by tiwa1154** [glygener/glygen-issues#227]
api_prd were terminated by Exited (137) code, meaning it's using more memory than it's allowed. 
Mongo_prd and app_prd containers were stopped by Exited (128).

So it looks like there is a memory issue on the AWS server which prevents me from restarting the containers.  

@jeet-vora @rykahsay

**Comment by rykahsay** [comment]
I don't know what happened but I just did the following and the website is running now:
```
$ cd api
$ sudo python3 create_mongo_container.py -s prd
$ sudo systemctl start docker-glyds-mongo-prd.service
$ sudo python3 create_api_container.py -s prd
$ sudo systemctl start docker-glyds-api-prd.service

$ cd app
$ sudo python3 create_app_container.py -s prd
$ sudo systemctl start docker-glyds-app-prd.service
```

**Comment by tiwa1154** [comment]
Thanks @rykahsay for looking into this
