### ISSUE TITLE
Change "No data available" to " ... fetching data"

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#228]
This is minor but I think it is better to say " ... fetching data" instead of "No data available" while the progress icon is spinning.

 
<img width="989" alt="image" src="https://user-images.githubusercontent.com/20584876/230431683-96d97e47-822d-4015-92c2-fe8e45971b77.png">

**Comment by sujeetvkulkarni** [comment]
66f483b0449c9eac371968ee9bf97623fe7feadd

**Comment by sujeetvkulkarni** [comment]
d21f24041da8e6ddea5855eb5b74e36a9b54bf70

**Comment by sujeetvkulkarni** [comment]
488693eb6f88683fddba6da99866dd2fc9dc93d5
