### ISSUE TITLE
glycan dictionary link is not working

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#229]
Below link is not working,
https://wiki.glygen.org/index.php/Glycan_structure_dictionary

**Comment by jeet-vora** [comment]
@sujeetvkulkarni The link is working 
You can use this link instead - https://wiki.glygen.org/Glycan_structure_dictionary

**Comment by sujeetvkulkarni** [comment]
9d0c1dd292239f2e939dfcc64dd54399297f8664
