### ISSUE TITLE
Compose CFDE biomarker proposal Aims (2 hours)

### ISSUE THREAD

**Issue by danlymangw** [glygener/glygen-issues#23]
1.	Review discussions and prior biomarker proposals 
2.	Draft ~3 Specific Aims for a potential resubmission of a CFDE biomarker proposal

**Comment by danlymangw** [comment]
1.	Review discussions and prior biomarker proposals 
2.	Draft ~3 Specific Aims for a potential resubmission of a CFDE biomarker proposal

**Comment by danlymangw** [comment]
The biomarker data model has been revised following discussion on 2/13 with Darren Natale. The revision impacts the biomarker proposal, pending review of the suggested revisions to the model and delaying development of proposal Aims.

**Comment by danlymangw** [comment]
Development of Aims is in progress

**Comment by jeet-vora** [comment]
@danlymangw If this is done. Please close the issue.
