### ISSUE TITLE
Find 1 example of protein/glycan that have data for all of the section

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#232]
Please find 1 example of protein and glycan that have data for all of the sections. This task is created because there are 2 missing sections (Names and Glycan binding protein) for our current example (i.e. G17689DH) on the Ultra Quick Test document (see below screenshots). Once you find the example, I will update all the testing document accordingly. 

<img width="734" alt="Screen Shot 2023-04-07 at 4 27 16 PM" src="https://user-images.githubusercontent.com/61590108/230674816-52cc1418-fe75-48b2-8dfc-03d72d5c65cf.png">

<img width="928" alt="Screen Shot 2023-04-07 at 4 30 06 PM" src="https://user-images.githubusercontent.com/61590108/230674864-1b36381a-0df8-4acb-a846-a245b2edca00.png">

<img width="925" alt="Screen Shot 2023-04-07 at 4 30 23 PM" src="https://user-images.githubusercontent.com/61590108/230674908-c1d931f1-2966-45bb-bf4b-c89f7f1b8839.png">

@jeet-vora Please review the above instruction before I assign it to Robel, thanks.

**Comment by jeet-vora** [comment]
@rykahsay 

Can you provide few examples of protein and glycan accessions that have data for all the sections in the details page.

**Comment by rykahsay** [comment]
Follow instructions

```
cd /software/glygen/
python3 dump-object-completeness.py  -v 2.0.3 -r glycan > logs/completeness-glycan.txt
cat logs/completeness-glycan.txt | sort -nr | head
```

The above commands should give the lines shown below. 
```
32 properties out of 35 have value, G78059CC
32 properties out of 35 have value, G16828VN
31 properties out of 35 have value, G98559XP
31 properties out of 35 have value, G97765TT
31 properties out of 35 have value, G96921ZU
31 properties out of 35 have value, G94531EZ
31 properties out of 35 have value, G91905FJ
31 properties out of 35 have value, G91413ZX
31 properties out of 35 have value, G91365ZQ
31 properties out of 35 have value, G91023GB
```

**Comment by jeet-vora** [comment]
@JingyueWu Run the above script for Protein and let me know the results.

**Comment by JingyueWu** [comment]
@jeet-vora Here is results after running the above script:

<img width="393" alt="Screen Shot 2023-06-06 at 12 37 36 PM" src="https://github.com/glygener/glygen-issues/assets/61590108/acc9703f-1f99-443b-96a0-afa962b9f50c">

Same as what Robel showed.

**Comment by JingyueWu** [comment]
@jeet-vora Results for protein: 

<img width="344" alt="Screen Shot 2023-06-07 at 2 55 46 PM" src="https://github.com/glygener/glygen-issues/assets/61590108/d77e0aca-9ee4-456f-a5f5-95ce3b778dc5">
