### ISSUE TITLE
Detail and Ultra Quick Test on Beta

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#235]
Complete in the next 2-3 hours and report any issue here before assigning it to Robel.

**Comment by JingyueWu** [comment]
Ultra Quick Test on Beta -- 

Only 2 things:

1) Protein Advanced Search -- 
When E is entered in the search box, does the type ahead of UniProtKB ac work and shows a dropdown with accessions having E? --> No, just a standalone E

2) Simple Search -- what are the function of protein P14210?
--> Might need to consider finding a better example to replace P14120, because data are missing for the 4 sections: Phosphorylation, Glycation, PTM annotation, and Synthesized Glycans. See ticket #232 

Detailed Testing on Beta -- 

Issues:

1) Glycan Search --> Structure and Substructure Search --> No results found after inputting examples

2) /job/delete/ API --> error code 500

**Comment by kmartinez834** [comment]
@JingyueWu  --> FYI...if you need a protein/glycan with a particular section, you can check the corresponding dataset for accessions.

Issue 1. See #238 
Issue 2. I don't think this is an issue we need to be concerned about. You could bring it up on next Monday's call if you want to discuss with Robel
