### ISSUE TITLE
Creating CSV file for API response schema

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#236]
I expect a CSV file with the following fields (example generated/misc/schema_protein_detail.csv)

```
prop_path,is_required,description
mass,yes,some description
sequence,yes,some description
mass.chemical_mass,yes,some description
refseq.ac,yes,some description
refseq.name,yes,some description
refseq.summary,yes,some description
refseq.url,yes,some description
```

**Comment by kmartinez834** [comment]
CSV files created for glycan and protein schemas:
- **generated/misc/schema_glycan_detail.csv**
- **generated/misc/schema_protein_detail.csv**

@jeet-vora Review schema_protein_detail.csv and add descriptions

**Comment by jeet-vora** [comment]
Done. Check and track for further changes #267
