### ISSUE TITLE
Footer/sitemap doesn't match new menu structure

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#237]
@sujeetvkulkarni --> Update footer to match new menu structure.  Please assign to 2.0 or 2.1 milestone (not sure how much time this requires)

![image](https://user-images.githubusercontent.com/90285371/230958593-1ce9d83f-f77a-409f-94e7-2d13da6fdd75.png)

vs...

![image](https://user-images.githubusercontent.com/90285371/230958265-881a581e-a5da-4a8f-a781-9290c63f2528.png)

**Comment by sujeetvkulkarni** [comment]
e908ca3fd8a45bd772f64de894a7641297052af1

**Comment by sujeetvkulkarni** [comment]
@kmartinez834 can you please check now - https://tst.glygen.org/home/

**Comment by kmartinez834** [comment]
👍
