### ISSUE TITLE
Compose CFDE biomarker proposal use cases (3 hours)

### ISSUE THREAD

**Issue by danlymangw** [glygener/glygen-issues#24]
1.	Review discussions, DCC work, and prior biomarker proposals 
2.	Develop 2-3 use cases for a potential CFDE biomarker proposal resubmission

**Comment by danlymangw** [comment]
The biomarker data model has been revised following discussion on 2/13 with Darren Nadel. The revision impacts the biomarker proposal use cases, pending review of the suggested revisions to the model and delaying development of proposal use cases.

**Comment by danlymangw** [comment]
Development of use cases is in progress

**Comment by jeet-vora** [comment]
@danlymangw Close the issue if done
