### ISSUE TITLE
Download icon for tabular data section (all pages)

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#241]
Add a download icon to all tabular data section (see #239 ) and connect it with the download web service (#240 ).

**Dependencies**:
* #239 
* #240 
* #296

**Comment by sujeetvkulkarni** [comment]
62b001d6dcc7eac38ac8b39f2823beb8755cad10

**Comment by sujeetvkulkarni** [comment]
eee43c9e44751d3c3e78a2fa2edf7b020224e463

**Comment by sujeetvkulkarni** [comment]
568aeae401657bd894daff943e6315e9ccee7cf4
