### ISSUE TITLE
Apply filter for download results on list pages

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#242]
Modify the download list page service to also include the filter options. Filter the data rows from the list ID based on the filter before exporting. This is related to #10.

**Blocker for**:
* #243

**Comment by sujeetvkulkarni** [comment]
{"id":"f3cf76dbbbc57727260a5cab991ba11d","offset":1,"sort":"hit_score","limit":20,"order":"desc","filters":[{"id":"by_organism","operator":"OR","selected":["Mus musculus"]}]}

**Comment by sujeetvkulkarni** [comment]
use filters in above example for download apis in all cases where list api supports filters like glycan, protein, site api.

**Comment by rykahsay** [comment]
This is a list results for protein giving a total of 54 records (https://tst.glygen.org/protein-list/0e6f1dc7c69f71103450bbf04ff87214)

Now you can call the /data/list_download/ API with the following queries

### Without filters gives all 54 rows
```
{
    "id": "0e6f1dc7c69f71103450bbf04ff87214",
    "download_type": "protein_list",
    "format": "csv",
    "compressed": false
}
```


### With filters asking to show only "Homo sapiens" gives obly 36 rows
```
{
    "id": "0e6f1dc7c69f71103450bbf04ff87214",
    "filters":[{"id":"by_organism","operator":"OR","selected":["Homo sapiens"]}],
    "download_type": "protein_list",
    "format": "csv",
    "compressed": false
}
```

**Comment by sujeetvkulkarni** [comment]
62b001d6dcc7eac38ac8b39f2823beb8755cad10
