### ISSUE TITLE
Decide which tables need server side pagination

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#244]
We need to find all tables that have too much data and break the frontend. The usual suspects are:

Glycan details:
* List of papers
* List of proteins

Protein details:
* List of Phosphorylation sites
* List of glycosylation sites
* List of papers

Site details:

Publication details:
* List of Phosphorylation sites
* List of glycosylation sites
* List of proteins

**Blocker for**:
* #246 
* #247

**Comment by jeet-vora** [comment]
Glycan details:

    List of papers
    List of proteins
    Newly added **List of expression**

Protein details:

    List of Phosphorylation sites
    List of glycosylation sites
    List of papers
    Newly added **List of SNVs**

Site details: Not required

Publication details:

    List of Phosphorylation sites
    List of glycosylation sites
    List of proteins
    Newly added**List of Glycans**

@sujeetvkulkarni @kmartinez834 @ReneRanzinger I have added new sections.
