### ISSUE TITLE
Implement server side pagination for large datasets

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#246]
Based on the evaluation in #244 and the strategy in #245 implement the server side pagination for all chosen detail pages and sections. 

**Dependencies**:
* #244 
* #245 
* #521 

**Blocker for**:
* #247

**Comment by rykahsay** [comment]
```
The following API implement section paging

/glycan/detail/
/protein/detail/
/publication/detail/


Example queries for each of the above APIs are

https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/glycan/detail.json
https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/protein/detail.json
https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/publication/detail.json

```

**Comment by sujeetvkulkarni** [comment]
@rykahsay thanks, I am working on the details api. Please let me know when you are done with table pagination api and include section_stats:[] in details api. 
Also, "publication" table would need sort field with fields like - Title, Date, Journal, Author List.

**Comment by rykahsay** [comment]
<img width="461" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/17e48b48-837a-4d9b-a807-2119483314ab">


<img width="488" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/074832a1-88c6-4d35-9016-666a44e8a45b">


<img width="495" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/a6093795-b7cb-41ff-807d-856a6117e402">
