### ISSUE TITLE
Implement server side pagination for tables

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#247]
Based on the evaluation in #244, the strategy in #245, tables in #282 and the implementation in #246 implement server side pagination for all mentioned tables.

**Dependencies**:
* #282 
* #244 
* #245 
* #246 
* #572 
* #521 
* #586 
* #587

**Comment by sujeetvkulkarni** [comment]
436db692d833be9f83508e62f3beb347accf6b75

**Comment by sujeetvkulkarni** [comment]
9896db954fc3456b8f580268781bc546e76bda79
