### ISSUE TITLE
Update data pipeline to use Nathans Sandbox data

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#250]
@edwardsnj made fixes to the sandbox and deployed a new version. We have to fix the pipeline to load the data from the new place.

@edwardsnj what are the URL for the new sandbox and the location for the GlyGen data files?

**Blocker for**:
* #251 
* #252

**Comment by edwardsnj** [comment]
The primary URL is:

  https://sandbox.glyomics.org/

in place of 

  https://glygen.ccrc.uga.edu/sandbox/

throughout.

- n

**Comment by sujeetvkulkarni** [comment]
62b001d6dcc7eac38ac8b39f2823beb8755cad10
