### ISSUE TITLE
Process Nathans Sandbox data

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#251]
Based on #250 we need to integrate the new sandbox data into GlyGen. That might also require updated evidence and cross reference as needed.

**Dependencies**:
* #250

**Comment by rykahsay** [comment]
@kmartinez834 --> can you please specify what needs to be done if this is outside of running the pipeline to make relevant glycan dataset(s)?

**Comment by kmartinez834** [comment]
@rykahsay --> I updated `misc/xref_info.csv`, proceed with processing the sandbox data

**Comment by rykahsay** [comment]
Please these datasets that depend on sandbox data:

- unreviewed/glycan_pathway_glycotree.csv
- unreviewed/glycan_enzyme.csv
- unreviewed/glycan_toolsupport.csv
- unreviewed/glycan_xref_sandbox.csv

**Comment by kmartinez834** [comment]
- **unreviewed/glycan_enzyme.csv**
Change "xref_key" to "glycan_xref_sandbox" and "xref_id" to the glytoucan_ac
Ex.
```
"xref_key","xref_id"
"glycan_xref_sandbox","G00012RZ"
```
This should affect the Biosynthetic Enzyme source labels on the front end (https://glygen.org/glycan/G00012RZ#Biosynthetic-Enzymes)

- **unreviewed/glycan_toolsupport.csv**
There are duplicate lines for same glycan/tool.  Each accession should have 8 rows only.
```
$ grep G14127XU  unreviewed/glycan_toolsupport.csv
"G14127XU","gnome_glygen_oglycans","no"
"G14127XU","sandbox","yes"
"G14127XU","gnome_glygen","yes"
"G14127XU","gnome","yes"
"G14127XU","gnome_glycotree_oglycans","no"
"G14127XU","pdb","yes"
"G14127XU","gnome_glygen_nglycans","yes"
"G14127XU","gnome_glycotree_nglycans","yes"
"G14127XU","gnome_glygen_oglycans","no"
"G14127XU","sandbox","yes"
"G14127XU","gnome_glygen","yes"
"G14127XU","gnome","yes"
"G14127XU","gnome_glycotree_oglycans","no"
"G14127XU","pdb","yes"
"G14127XU","gnome_glygen_nglycans","yes"
"G14127XU","gnome_glycotree_nglycans","yes"
"G14127XU","gnome_glygen_oglycans","no"
"G14127XU","sandbox","yes"
"G14127XU","gnome_glygen","yes"
"G14127XU","gnome","yes"
"G14127XU","gnome_glycotree_oglycans","no"
"G14127XU","pdb","yes"
"G14127XU","gnome_glygen_nglycans","yes"
"G14127XU","gnome_glycotree_nglycans","yes"
"G14127XU","gnome_glygen_oglycans","no"
"G14127XU","sandbox","yes"
"G14127XU","gnome_glygen","yes"
"G14127XU","gnome","yes"
"G14127XU","gnome_glycotree_oglycans","no"
"G14127XU","pdb","yes"
"G14127XU","gnome_glygen_nglycans","yes"
"G14127XU","gnome_glycotree_nglycans","yes"
```

**Comment by rykahsay** [comment]
check now

**Comment by kmartinez834** [comment]
👍
