### ISSUE TITLE
Testing Literature mining pipeline

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#255]
After getting the literature pipeline running at GW (see #253) we need need to test it. 

1. Have a run through the entire pipeline
2. Compare if we get the same results
    * Run filter for all PMID that we gave to Vijay last time
    * Run it through Vijays tool
    * Check if the data files produced have the same content as the data files Vijay gave to GlyGen

**Dependencies**:
* #253

**Comment by kmartinez834** [comment]
Process Vijays output to fit GlyGen data files

**Comment by ReneRanzinger** [comment]
Currently stuck with #463 .
