### ISSUE TITLE
Document data formats and files needed for Europe PMC

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#256]
We need to figure out what files, formats or APIs to use to make GlyGen cross references appear in Europe PMC. That might be different than PMC since they support more information.

**Blocker for**:
* #256
* #258

**Comment by jeet-vora** [comment]
Documentation - https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/Documents/EuropePMC%20linkouts.docx?d=w8fc9c465fd094eee89b370747e7eac80&csf=1&web=1&e=55dfRg
