### ISSUE TITLE
Run 2.1 data update

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#262]
Run the data update for 2.1. This is a sibling of #259 that deals with the glycan data.

**Blocker for**:
* #263

**Comment by kmartinez834** [comment]
Glyconnect pending, all others have been downloaded

**Comment by kmartinez834** [comment]
There is an issue with the GlyConnect API for Homo sapiens data.  The request is working for other species.  Sent an email to Frederique and Catherine today.

Request URL:
https://glyconnect.expasy.org/api/glycosylations?taxonomy=Homo%20sapiens

Response:
java.sql.SQLException: Connection is closed
