### ISSUE TITLE
Update structure search container

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#269]
Based on Nathans update the structure search (see #268) update the GW infrastructure.

**Dependencies**:
* #268

**Comment by rykahsay** [comment]
<img width="1303" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/866f9832-37d3-49be-9c06-c31a3613718f">

**Comment by kmartinez834** [comment]
Structure search is working for >10 residues, but Substructure search is still giving an error:

![image](https://github.com/glygener/glygen-issues/assets/90285371/18ac89e7-53ae-4968-8548-10b09891e987)

Ex. G86357DX
```
RES
1b:b-dglc-HEX-1:5
2s:n-acetyl
3b:b-dglc-HEX-1:5
4s:n-acetyl
5b:b-dman-HEX-1:5
6b:a-dman-HEX-1:5
7b:b-dglc-HEX-1:5
8s:n-acetyl
9b:b-dgal-HEX-1:5
10b:b-dglc-HEX-1:5
11s:n-acetyl
12b:b-dgal-HEX-1:5
13b:a-dman-HEX-1:5
14b:b-dglc-HEX-1:5
15s:n-acetyl
16b:b-dgal-HEX-1:5
17b:a-lgal-HEX-1:5|6:d
LIN
1:1d(2+1)2n
2:1o(4+1)3d
3:3d(2+1)4n
4:3o(4+1)5d
5:5o(3+1)6d
6:6o(2+1)7d
7:7d(2+1)8n
8:7o(4+1)9d
9:6o(4+1)10d
10:10d(2+1)11n
11:10o(4+1)12d
12:5o(6+1)13d
13:13o(2+1)14d
14:14d(2+1)15n
15:14o(4+1)16d
16:1o(6+1)17d
```

**Comment by rykahsay** [comment]
I have restarted the container  and it pulls updated image when it restarts (Nathan). We should follow up with him on our tomorrow's meeting.

<img width="1383" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/db9353e6-5898-4f43-a5fd-51ed04096da1">

**Comment by kmartinez834** [comment]
Per Nathan, substructure search will not work with >10 residues.  Structure should work.
