### ISSUE TITLE
Provide new glycam file for 3D structure generation

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#276]
An example for the format can be found [here](https://github.com/ReneRanzinger/glycam.api.client/blob/master/data/2022.04.10.glycan.csv). We need an updated version after #259 is done.

**Dependencies**:
* #259 

**Blocker for**:
* #277

**Comment by kmartinez834** [comment]
I generated the file and saved it in Sharepoint here: [Documents/Data Files/glycam_iupac_20230518.csv](https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Data%20Files/[glycam_iupac_20230518.csv](https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Data%20Files/glycam_iupac_20230518.csv?d=wa6a750b2b2264b968cb0d339103d9179&csf=1&web=1&e=3wAOAz)?d=wa6a750b2b2264b968cb0d339103d9179&csf=1&web=1&e=3wAOAz)

**Comment by kmartinez834** [comment]
@ReneRanzinger can I close this ticket?
