### ISSUE TITLE
Glycosyltransferases for Drosophila throwing error

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#278]
https://beta.glygen.org/quick-search/
Expected 123 results per fruitfly_protein_glycosyltransferase.csv
![image](https://user-images.githubusercontent.com/90285371/230983835-091427f6-c4e6-47bd-8d75-8b001e335991.png)

API response to request https://beta-api.glygen.org/usecases/species_to_glycosyltransferases/7227/

``` json
{
  "error_list": [
    {
      "error_code": "exception-error-E15WYA"
    }
  ]
}
```

**Comment by rykahsay** [comment]
Please check now
<img width="643" alt="image" src="https://user-images.githubusercontent.com/20584876/231058333-db862637-0212-442b-804f-5c0e08e3ca99.png">

**Comment by kmartinez834** [comment]
👍
