### ISSUE TITLE
Glycohydrolases for Drosophila throwing error

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#279]
https://beta.glygen.org/quick-search/
Expected 41 results per fruitfly_protein_glycohydrolase.csv
![image](https://user-images.githubusercontent.com/90285371/230984848-de4ec6d8-a60a-4fe3-ae35-efe446bb4bae.png)

API response to request https://beta-api.glygen.org/usecases/species_to_glycohydrolases/7227/

``` json
{
  "error_list": [
    {
      "error_code": "exception-error-2B3UF0"
    }
  ]
}
```

**Comment by rykahsay** [comment]
Please check

<img width="612" alt="image" src="https://user-images.githubusercontent.com/20584876/231058116-5fa42359-efc0-4b52-aff2-cc16109c6c3d.png">

**Comment by kmartinez834** [comment]
👍
