### ISSUE TITLE
Species to glycoproteins error

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#280]
Getting an error for drosophila, Hep C virus (H & Japanese), SARS (1 & cov2)

![image](https://user-images.githubusercontent.com/90285371/230995462-77ba6f82-df8e-42d3-98fa-a71b8cf98624.png)

https://beta-api.glygen.org/usecases/species_to_glycoproteins/63746/reported/

``` json
{
  "error_list": [
    {
      "error_code": "exception-error-JN7S9Y"
    }
  ]
}
```

**Comment by rykahsay** [comment]
check now:
<img width="646" alt="image" src="https://user-images.githubusercontent.com/20584876/231057841-9d1811c5-e74d-42b1-8b3b-a2d8e5d34192.png">

**Comment by kmartinez834** [comment]
👍
