### ISSUE TITLE
Site sequence blocked by horizontal scroll bar

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#281]
Ex. https://beta.glygen.org/Siteview/P13611-1/1001

![image](https://user-images.githubusercontent.com/90285371/230998712-f62fae57-adee-4f8a-b7c2-0ca633fde9e2.png)

**Comment by sujeetvkulkarni** [comment]
@kmartinez834 what is the screen resolution, browser and operating system?

**Comment by kmartinez834** [comment]
1920x1080, Chrome, Windows

(Seeing the same thing on my laptop screen and my second monitor)

**Comment by sujeetvkulkarni** [comment]
@kmartinez834 , please check now - https://tst.glygen.org/Siteview/P13611-1/1001

**Comment by kmartinez834** [comment]
Looks good!
