### ISSUE TITLE
iPTMnet dead links

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#283]
iPTMnet links with dash in ID (ex. P54762-1) resulting in dead links.
Ex. https://beta.glygen.org/protein/P54762-1#Phosphorylation

All isoforms are found on the main identifier's page.
Ex. https://research.bioinformatics.udel.edu/iptmnet/entry/P54762/

@rykahsay --> Can you remove the dash-number from the protein details API `phosphorylation.evidence.url` (ex. P13611-1 to P13611)? Keep "id" as-is.
``` json
"phosphorylation": [
    {
      "start_pos": 2086,
      "end_pos": 2086,
      "residue": "Thr",
      "evidence": [
        {
          "database": "iPTMnet",
          "id": "P13611-1",
          "url": "http://research.bioinformatics.udel.edu/iptmnet/entry/P13611-1"
        },
        {
          "database": "PubMed",
          "id": "18491316",
          "url": "https://glygen.org/publication/PubMed/18491316"
        }
      ]
    },
```

**Comment by rykahsay** [comment]
Please check now

<img width="854" alt="image" src="https://user-images.githubusercontent.com/20584876/231253053-459856ca-2fc6-48b6-a35a-c8eb487be2fb.png">

**Comment by kmartinez834** [comment]
@rykahsay is it possible to keep the id as P13611-1 and only update the url to P13611?

Ex. 
``` json
"evidence": [
        {
          "database": "iPTMnet",
          "id": "P13611-1",
          "url": "http://research.bioinformatics.udel.edu/iptmnet/entry/P13611"
        },
```

**Comment by rykahsay** [comment]
Not a good idea,  we stay consistent
