### ISSUE TITLE
Protein function section has Uniprot IDs as PubMed evidence

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#284]
UniProt ID's are listed as PubMed evidence in Protein Function section:
Ex. https://beta.glygen.org/protein/P54762-1#Function

![image](https://user-images.githubusercontent.com/90285371/231016725-1a088769-6b54-4155-ad30-5419eeeef5c8.png)

Ex. reviewed/human_protein_function_uniprotkb.csv:
```
"uniprotkb_canonical_ac","xref_key","xref_id","annotation"
"P54762-1","protein_xref_pubmed","Q8CBF3","Receptor tyrosine kinase which binds promiscuously transmembrane...
```

@rykahsay --> In reviewed/*_protein_function_uniprotkb.csv, "xref_key" should be "protein_xref_uniprotkb_fun" if source file says http://purl.uniprot.org/uniprot/...

```
$ grep "P54762.*Q8CBF3" /data/shared/glyds/downloads/ebi/2022_05/uniprot-proteome-homo-sapiens.nt
<http://purl.uniprot.org/uniprot/P54762#attribution-1D43D0D294B6751AB94055EDA0BD6B4F> <http://purl.uniprot.org/core/source> <http://purl.uniprot.org/uniprot/Q8CBF3>
```

**Comment by rykahsay** [comment]
please check:

<img width="675" alt="image" src="https://user-images.githubusercontent.com/20584876/231191141-33c2055c-1924-4fc8-95f0-ff69b92e162d.png">

**Comment by kmartinez834** [comment]
👍
