### ISSUE TITLE
evidence in glycan publication has None id.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#285]
https://beta.glygen.org/glycan/G17689DH#Publications

go to -  Bisecting GlcNAc Protein N-Glycosylation Is Characteristic of Human Adipogenesis.

click on evidence 'Glyconnect'
'None' id is listed, if you click on it, you go to https://glyconnect.expasy.org/browser/proteins/None
which is invalid.

you get below response from api,
https://beta-api.glygen.org/glycan/detail/G17689DH

```
{
    "title": "Bisecting GlcNAc Protein N-Glycosylation Is Characteristic of Human Adipogenesis.",
    "journal": "Journal of proteome research",
    "date": "2021",
    "authors": "Wongtrakul-Kish K, Herbert BR, Packer NH",
    "evidence": [
        {
            "database": "GlyConnect",
            "id": "None",
            "url": "https://glyconnect.expasy.org/browser/proteins/None"
        }
    ],
    "reference": [
        {
            "type": [
                "PubMed"
            ],
            "id": "33383989",
            "url": "https://glygen.org/publication/PubMed/33383989"
        }
    ]
}

```

**Comment by rykahsay** [comment]
Please check now:

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/20584876/231283403-485e79a9-07b0-453f-8686-253ac758c992.png">

**Comment by sujeetvkulkarni** [comment]
Looks good to me.
