### ISSUE TITLE
Featured video missing on prd

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#289]
https://glygen.org/home/

![image](https://user-images.githubusercontent.com/90285371/231465929-3fa6c481-8a64-45ec-af7f-54153231a545.png)

**Comment by rykahsay** [comment]
@sujeetvkulkarni  -- you should be able to login 

<img width="819" alt="image" src="https://user-images.githubusercontent.com/20584876/231469865-0d6c0728-46ee-4e37-a27f-503b99fb1ca9.png">

**Comment by sujeetvkulkarni** [comment]
@kmartinez834 @rykahsay done, please check https://glygen.org/home/

**Comment by kmartinez834** [comment]
👍
