### ISSUE TITLE
Learn to download EBI data from the FTP site into GlyGen Server (1 hour)

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#29]
Learn to download the EBI files to GlyGen Dev server and understand them. 
https://ftp.ebi.ac.uk/pub/contrib/glygen/current_release/

Once ready to do the task ask Jeet to show you how to do it.

**Comment by jeet-vora** [comment]
@JingyueWu Here is the link to README to download the EBI files - [/ebi/README.txt](/data/projects/glygen/downloads/ebi/README.txt). By now you would have known how to access the server.

Follow the readme and download the files as mentioned. Once downloaded create a ticket for me and Robel to process.

Do not open the downloaded files in the server. Download them to your folder or computer prior to opening to avoid any accidental changes. 

Remove the yeast folder/files from it for now as it will be part of next release.

**Comment by JingyueWu** [comment]
This task is completed and is connected with issue #76
