### ISSUE TITLE
List filters do not include drosophila under "By Organism"

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#290]
Ex. https://glygen.org/protein-list/65b190ac84d036b3c1ffc5a9c8e86ada/question_10
![image](https://user-images.githubusercontent.com/90285371/231474403-68fd8736-ff41-4263-a7cc-75b0790fc76c.png)

Ex. https://glygen.org/glycan-list/474c27c37c81da3a4f8f51909f366bed
![image](https://user-images.githubusercontent.com/90285371/231472499-cf628256-4e0a-4d0b-8a42-33999a978eba.png)

**Comment by sujeetvkulkarni** [comment]
@kmartinez834 @rykahsay 
For https://glygen.org/protein-list/65b190ac84d036b3c1ffc5a9c8e86ada/question_10
below is api call and response, it does not returns filter options for Organism.
https://api.glygen.org/protein/list?query={%22id%22:%2265b190ac84d036b3c1ffc5a9c8e86ada%22,%22offset%22:1,%22limit%22:20,%22order%22:%22desc%22,%22sort%22:%22hit_score%22,%22filters%22:[]}

```
{
    "id": "by_organism",
    "label": "By Organism",
    "order": 2,
    "tooltip": "",
    "options": []
}
```

For https://glygen.org/glycan-list/474c27c37c81da3a4f8f51909f366bed
below is api call and response, it does not returns drosophila in the filter options.
https://api.glygen.org/glycan/list?query={%22id%22:%22474c27c37c81da3a4f8f51909f366bed%22,%22offset%22:1,%22sort%22:%22hit_score%22,%22limit%22:20,%22order%22:%22desc%22,%22filters%22:[]}

```
{
    "id": "by_organism",
    "label": "By Organism",
    "order": 2,
    "tooltip": "",
    "options": [
        {
            "id": "Homo sapiens",
            "label": "Human",
            "count": 812,
            "order": 1
        },
        {
            "id": "Mus musculus",
            "label": "Mouse",
            "count": 763,
            "order": 2
        },
        {
            "id": "Rattus norvegicus",
            "label": "Rat",
            "count": 719,
            "order": 3
        },
        {
            "id": "Hepatitis C virus (isolate H)",
            "label": "HCV-H",
            "count": 12,
            "order": 5
        },
        {
            "id": "Severe acute respiratory syndrome-related coronavirus",
            "label": "HCoV-SARS",
            "count": 19,
            "order": 8
        },
        {
            "id": "Severe acute respiratory syndrome coronavirus 2",
            "label": "SARS-CoV-2",
            "count": 319,
            "order": 9
        }
    ]
}
```

**Comment by rykahsay** [comment]
Please check now:

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/20584876/231501342-d65b52f1-f108-4995-8c18-aeccfac20bf4.png">


<img width="1167" alt="image" src="https://user-images.githubusercontent.com/20584876/231499909-c02c7144-b57b-488f-bbb6-db4d129c6c25.png">

**Comment by kmartinez834** [comment]
@rykahsay --> For consistency, can you make "Fruit Fly" two words, see example from protein details page below:
![image](https://user-images.githubusercontent.com/90285371/231513086-b3f59bb0-07db-43ca-98ac-181f489320dc.png)

**Comment by rykahsay** [comment]
done

**Comment by kmartinez834** [comment]
👍
