### ISSUE TITLE
Mapping for header labels to data

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#296]
It would be good if the download web service from #240 uses the same table headings as the frontend. Can we have a mapping file that both frontend and backend can use? For example:

"protein.glycosylation.with_glycan.glycan_id" = "GlyTouCan Accession"

Changes for the table heading could be done in this file and can have an effect on frontend and download.

**Blocker for**:
* #240

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger @rykahsay I have mapped all the existing tables on "protein", "glycan", "site", "paper" and "motif" details pages in the below file. Please review.

Existing columns names and data properties are mapped in below file,

https://gwu0.sharepoint.com/:f:/r/sites/GlyGenTeam-GRP/Shared%20Documents/GlyGen%20Tasks?csf=1&web=1&e=AQwhLf

File name : Mapping for Header Labels

**Comment by sujeetvkulkarni** [comment]
create a json file

**Comment by sujeetvkulkarni** [comment]
JSON file to map column labels to be used by frontend and download service.
@ReneRanzinger @rykahsay please review the file. I have created separate objects for each table. 

https://gwu0.sharepoint.com/:f:/r/sites/GlyGenTeam-GRP/Shared%20Documents/GlyGen%20Tasks?csf=1&web=1&e=AQwhLf

File name : Download.json
