### ISSUE TITLE
Unnecessary scroll bar in banner

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#302]
There is a scrollbar appearing in the banner that should not be there. 

![Scrollbar](https://user-images.githubusercontent.com/2267640/232339474-2a895c35-0b69-45e7-85de-0a2752e9e4e6.png)

There is enough space for the banner to the rights. There should not even a scrollbar be needed. But looking at the scrollbar it seems the component (div, span?) is only 40% of the available width.

**Comment by sujeetvkulkarni** [comment]
87d6407af99d7df971afeac7de610eed282dca7e
