### ISSUE TITLE
Michelle' name correction on we are glygen about page

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#303]
Hi Sujeet please fix Michelle's last name it is **V**esser and not **W**esser. Is is possible to fix it in 2.0 release?

<img width="278" alt="image" src="https://user-images.githubusercontent.com/25825266/232553606-dd85e72f-ff1d-4d43-b197-cd07e289def8.png">

https://www.glygen.org/about/

**Comment by sujeetvkulkarni** [comment]
@jeet-vora we can it's a quick fix. But Robel needs to redeploy front end. Let me know if I should make the change in 2.0

**Comment by jeet-vora** [comment]
@sujeetvkulkarni Robel will make a fuss since it is small inconsequential change. Lets see if we have more changes to do otherwise we can do it for next release.

**Comment by sujeetvkulkarni** [comment]
52bccdbf73879c651e71bcab5c0c6d63055785f9
