### ISSUE TITLE
Mismatch in Species numbers in supersearch

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#304]
Currently there are mismatches in the species numbers in the supersearch.

![SuperSearchOrganism](https://user-images.githubusercontent.com/2267640/232612790-847f6cf1-c188-46b3-9eef-333fcd82ff7a.png)

* It says that there are 10 organism in total (we only have 8). 
* 8 of the organisms have genes and proteins in GlyGen (that should be fine)
* 9 organism have Glycans (I think that comes from the rattus vs rattus norvegicus problem. But I dont think that should be exposed.

**Comment by kmartinez834** [comment]
@rykahsay --> Do you know why the supersearch init says the organism count is 10?
https://api.glygen.org/supersearch/search_init/
``` json
"id": "species",
    "label": "Organism",
    "description": "GlyGen Organism Concept",
    "fields": [
      {
...
    "record_count": 10,
    "list_id": "",
    "bylinkage": {
      "glycan": {
        "list_id": "",
        "result_count": 9
      },
      "protein": {
        "list_id": "",
        "result_count": 8
      },
      "gene": {
        "list_id": "",
        "result_count": 8
      }
    }
  }
```

**Comment by rykahsay** [comment]
fixed

**Comment by kmartinez834** [comment]
Glycan now has 7, but should be 8 I think
https://tst.glygen.org/super-search/
![image](https://github.com/glygener/glygen-issues/assets/90285371/00a058b8-2823-42dd-982e-cfb5e9b9e105)

![image](https://github.com/glygener/glygen-issues/assets/90285371/e660edf5-940e-4ec4-93a0-2b95c3a7fd5d)

**Comment by ReneRanzinger** [comment]
On beta is still shows 10?

**Comment by rykahsay** [comment]
Fixed now

<img width="531" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/52f11673-afc3-4004-aee7-210ed778c3a6">
