### ISSUE TITLE
Event banner comes up early and stops showing early than scheduled start and end date

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#305]
I tried on production and test creating event banner and looks like they come and go early than scheduled time as per Eastern Standard Time . Event banner should follow Eastern Standard Time.

**Comment by rykahsay** [comment]
Done

**Comment by sujeetvkulkarni** [comment]
email: myglygen@gmail.com

login api is failing with below error

500 INTERNAL SERVER ERROR

 response object:
{
  "error_list": [
    {
      "error_code": "exception-error-AW482T"
    }
  ]
}

**Comment by rykahsay** [comment]
Try now:

<img width="705" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/9bf28ebb-d001-4fa8-8e30-6d811ec7d4d0">

**Comment by sujeetvkulkarni** [comment]
done.
