### ISSUE TITLE
3D structures not working on production

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#306]
Example:

https://www.glygen.org/glycan/G36223VW

The widget is there but noting inside.

**Comment by sujeetvkulkarni** [comment]
![Screenshot 2023-04-18 at 10 38 22 AM](https://user-images.githubusercontent.com/13891482/232811784-4e6e5444-fa2d-4431-aff8-948f7c928802.png)

Looks fine to me.

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger browser, operating system related issue maybe?

**Comment by ReneRanzinger** [comment]
<img width="910" alt="3d" src="https://user-images.githubusercontent.com/2267640/232815679-2120c1d6-541e-41cc-ad56-ed1312731f3c.png">

Windows 10; Firefox and Chrome and Edge.

But I am from home right now.  Are you using tst service to get the structure?

**Comment by ReneRanzinger** [comment]
Manjaro: Firefox isnt working as well. Also from home.

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger yes earlier it was a separate url and then Robel moved it to api to avoid the CORS issue, so the new url is server specific. We might need to update the prod with the change.

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger should I make this change in 2.0 ?

**Comment by ReneRanzinger** [comment]
If its consistently not working outside GW and UGA ...yes.

Than we can also fix @jeetvora problem with the spelling error on about

________________________________________

**Comment by sujeetvkulkarni** [comment]
Ok, I will make those changes in 2.0 and we can ask Robel to deploy in tomorrow meeting.

**Comment by sujeetvkulkarni** [comment]
475fe1bfbba6c53670da1b8f804eec85efcbc1c5
