### ISSUE TITLE
Scrolling issue when changing pages

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#307]
Example:
https://www.glygen.org/glycan/G52264SX

* Scroll down to "Subsumption"
* Click on "Descendant"
* Click on one of the structures
* You are on the right page but in the **middle** of the page rather than on **top**

**Comment by sujeetvkulkarni** [comment]
Fixed for details pages : ffceef99388994bc6a3a7c73fe1ccdc2668a7272

**Comment by sujeetvkulkarni** [comment]
document it on the github wiki with solution (may have a better fix in future). and link this issue.

**Comment by sujeetvkulkarni** [comment]
wiki documentation - https://github.com/glygener/glygen-frontend/wiki/REACT-Version-Update
