### ISSUE TITLE
Talk to Dacian about failing GlyGen API containers and slowing of API responses

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#308]
Robel to talk to Dacian about failing GlyGen API containers and slowing of API responses and find a solution.

@ReneRanzinger @sujeetvkulkarni @kmartinez834

**Comment by rykahsay** [comment]
I think the issue has been resolved now -- I have optimized the mongo query and things are working ok now

**Comment by jeet-vora** [comment]
Closing the issue for now.
