### ISSUE TITLE
Glycan Structure Dictionary paper

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#309]
Sujeet please add the PMID for the Glycan Structure Dictionary paper
PMID: 36799723

RIS, BIBtex, ENDNOTE for the paper are in the zip file
[citation.zip](https://github.com/glygener/glygen-issues/files/11276751/citation.zip)

https://www.glygen.org/how-to-cite/
![image](https://user-images.githubusercontent.com/25825266/233176742-b839b678-c17b-4f83-8c28-09faf18d8ae4.png)
@ReneRanzinger

**Comment by sujeetvkulkarni** [comment]
https://pubmed.ncbi.nlm.nih.gov/36799723/

**Comment by sujeetvkulkarni** [comment]
744967b3d33944ef9a9eafb158740b42e7442f24
