### ISSUE TITLE
glygen production and beta api are down

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#312]
@rykahsay , @jeet-vora , @kmartinez834 , @ReneRanzinger 
glygen production and beta api services are down -
it returns
502 Proxy Error

**Comment by sujeetvkulkarni** [comment]
@rykahsay 
Looks like api is working now but video on glygen front page video is not coming. I tried to add it but the login api is failing with myglygen@gmail.com credentials.
api 
https://api.glygen.org/auth/login
response :
{"error_list": [{"error_code": "incorrect-email/password"}]}

**Comment by rykahsay** [comment]
I think this issue is no longer relevant
