### ISSUE TITLE
Protein Data Update for 2.1

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#313]
Update most protein/glycoprotein resources data
Track here #263 Close this once done

**Comment by JingyueWu** [comment]
Protein and Glycoprotein resources: EBI and Glyconnect

@jeet-vora Update as of 5/3/2023 - 

Still unable to download GlyConnect data from GlyConnect API — kept getting Unable to establish SSL connection error message even when I tried to run the bash script commands individually:

<img width="816" alt="Screen Shot 2023-05-03 at 3 39 24 PM" src="https://user-images.githubusercontent.com/61590108/236027576-2c5b3372-a3f9-4cc5-86a3-52b765194cec.png">

On GlyConnect API - 

<img width="1239" alt="Screen Shot 2023-05-03 at 3 40 27 PM" src="https://user-images.githubusercontent.com/61590108/236027860-3dfb534e-a213-4def-8b5c-e2ed65a3876c.png">

**Comment by JingyueWu** [comment]
Dependency of ticket #311
