### ISSUE TITLE
Test for glygen prd

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#318]
I had to reload mongodb on prd and we want to make sure everything on glygen prd looks ok. Please perform quick test on the APIs and the frontend

**Comment by JingyueWu** [comment]
@rykahsay @jeet-vora @kmartinez834 

Frontend - All buttons and pages are clickable. All examples are searchable. No issues found.
API - auth, video, and event are not working.

**Comment by kmartinez834** [comment]
No issues found

**Comment by rykahsay** [comment]
@kmartinez834 --> supersearch was not working. Is it included in your quick test protocol???

**Comment by kmartinez834** [comment]
@rykahsay no, supersearch is not included in the quick test protocol

**Comment by jeet-vora** [comment]
@JingyueWu 
Please add **SuperSearch**, **Site Search** and **List of Motifs** to the Quick Test Template similar to the ones we already have. There will be three separate bullet points, one for each. Once done, I can review what you have added.

Also add tests to check if the portals/APIs are working or not

- https://dsapi.glygen.org/
- https://gsaapi.glygen.org/
- https://gsa.glygen.org/
- https://gsaapi.glygen.org/
- https://data.glygen.org/
- https://dsapi.glygen.org/

**Comment by kmartinez834** [comment]
@JingyueWu

**Comment by JingyueWu** [comment]
@jeet-vora Super Search, Site Search. and List of Motifs have been added on the prd testing document on Sharepoint. Please review: 

https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B13D71B22-F9D9-43C9-8B87-CD012316675D%7D&file=UQT_PRD_JW1.docx&action=default&mobileredirect=true

**Comment by JingyueWu** [comment]
This task is completed. Files can be found in:

https://gwu0.sharepoint.com/sites/GlyGenTeam-GRP/SitePages/ProjectHome.aspx
