### ISSUE TITLE
How to add CFDE and GSA to the portal

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#319]
Currently nothing on the portal tells about our involvement in CFDE or GSA. How can we make this more visible? 

One option is to have a tight side card "Member of" below "Versions". Another alternative is to have them as badges on the webpage. Usually they are in the footer (not so good visible). Examples are the CoreTrustSeal and Global Biodata badges in the footer of the [PDB webpage](https://www.wwpdb.org/).

**Comment by jeet-vora** [comment]
Can we use the highlighted space for showing GSA and CFDE badges with links to the portals? I think the right side is already cluttered. At some point we may have to get rid of the GlyGen introduction or collapse it.

![image](https://github.com/glygener/glygen-issues/assets/25825266/d06a6aa6-d84d-4626-8f46-f5d972e2226e)

Maybe also add links to CFDE and GSA in the tools sections above the Other resources option. 

<img width="269" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/a99ffbcf-8d52-4469-ad4f-f80a35771937">

Also at some point we should also look into CoreTrustSeal and Global Biodata badges for GlyGen.

**Comment by rajamazumder** [comment]
AT https://proteininformationresource.org/ you can see "A UniProt Consortium Member" this is fashioned based on airlines on their website say "A Star Alliance Member" Or "A One World Member" We could say "A "GlySpace Alliance Member"

**Comment by ReneRanzinger** [comment]
> AT https://proteininformationresource.org/ you can see "A UniProt Consortium Member" this is fashioned based on airlines on their website say "A Star Alliance Member" Or "A One World Member" We could say "A "GlySpace Alliance Member"

I dont find that on the webpage.

**Comment by ReneRanzinger** [comment]
Based on the discussion on 8/30:
* We go with Jeets proposal to add them in the "empty" space left of the 3 buttons on the GlyGen Header.
* Add another stack of 2 buttons (these buttons should have 150% the hight of the "How to CITE" button
* First button:
  * [Logo](http://www.glyspace.org/img/logo.png)
  * Label: GlySpace Alliance
* Second button:
  * [Logo](https://commonfund.nih.gov/sites/default/files/CFDE_logo-color-web.png)
  * Label: Member of CFDE

We should also remove the default highlight of the "How to cite" button.

**Comment by sujeetvkulkarni** [comment]
b87bbd28a6d406a0e31f029f42330ced553cbce5

**Comment by sujeetvkulkarni** [comment]
Split Text into two lines:
![Screenshot 2023-09-12 at 3 57 23 PM](https://github.com/glygener/glygen-issues/assets/13891482/7f23433e-6706-4ba3-bbb6-e8b4c3ab0e80)



Single Line text:
![Screenshot 2023-09-12 at 4 07 21 PM](https://github.com/glygener/glygen-issues/assets/13891482/fc82b1ec-adae-4857-890b-4c25b358c439)



Single word text:
![Screenshot 2023-09-12 at 4 08 15 PM](https://github.com/glygener/glygen-issues/assets/13891482/31c2d206-1667-473b-bda7-b7480e6efad5)

**Comment by sujeetvkulkarni** [comment]
Number 2

**Comment by sujeetvkulkarni** [comment]
d43dd65e3902cf5fbb9d94b6eb8a12f62ed5bdbc
