### ISSUE TITLE
Provide GRITS download instructions

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#327]

**Comment by ReneRanzinger** [comment]
You can download GRITS Toolbox from the webpage: http://www.grits-toolbox.org/

There are Windows and Mac versions. The top of the download page has the program that requires a Java installed. If you dont have Java or an older Java version download the version on the bottom of the page (with bundled JRE). Simply decompress, and start the "GRITS" file in the MacOS folder.
