### ISSUE TITLE
Automatic Issue Creation from Email and Contact Page

### ISSUE THREAD

**Issue by HadleyKing** [glygener/glygen-issues#329]
[WIP]

**Comment by HadleyKing** [comment]
Currently BCO has a [Netlify](https://github.com/apps/netlify) to push "Contact Us" forms to Slack. 
We have a link on our page to forward to Github issue creation using templates.

**Comment by HadleyKing** [comment]
@rykahsay @rajamazumder

**Comment by ReneRanzinger** [comment]
There is an [documented API](https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#create-an-issue) on GitHub how to create tickets with all metadata (labels, milestone etc).
 
@rykahsay see if we can use this.

**Comment by rykahsay** [comment]
If I make the example request shown below, the issue will be created by rykahsay (if the authorization token is mine) and assigned to jeetvora. My question is, do we have some organizational github account which has a login token? If yes, please provide me it's login token. Until then, these automatically created issues will be created by rykahsay.


```
TOKEN="xyzabc123..."
curl -L -X POST -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/glygener/glygen-issues/issues \
  -d '{"title":"Found a bug","body":"I'\''m having a problem with this.","assignees":["jeetvora"],"labels":["fronten_user_issue"]}'
```

**Comment by jeet-vora** [comment]
@ReneRanzinger @rykahsay @sujeetvkulkarni 

Let me know what scopes to select for the token

<img width="812" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/b410aa88-1e6c-4f14-9441-d2624d61872f">

<img width="837" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/59a643ca-2c9a-418f-88fc-c8af5e904017">

<img width="851" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/3f5481ab-be79-4065-80cb-0b5241296129">

**Comment by ReneRanzinger** [comment]
@jeet-vora It seems there is no granularity for just ticket/issue access. You will need **public_repo** or if zou want to create the tickets in a private repository: **repo**.
@rykahsay please make sure that the token does not end up in the repository. Best a config file and that file on ignore. Otherwise somebody can really do some damage with this permissions.

**Comment by jeet-vora** [comment]
@rykahsay @ReneRanzinger 
Account login and token sent via email On Feb 14 titled Github (glygen-help)

**Comment by rykahsay** [comment]
It is using the "glygen-help" user now
