### ISSUE TITLE
Organism evidence is UniCarbKB and link is broken

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#330]

**Comment by sujeetvkulkarni** [comment]
https://www.glygen.org/glycan/G00194GV#Organism #330
https://api.glygen.org/glycan/detail/G00194GV

Severe acute respiratory syndrome coronavirus 2 

{
      "taxid": 2697049,
      "name": "Severe acute respiratory syndrome coronavirus 2",
      "annotation_category": "Direct",
      "evidence": [
        {
          "database": "UniCarbKB",
          "id": "UniCarbKB",
          "url": "http://unicarbkb.org/query"
        }
      ],

**Comment by kmartinez834** [comment]
@rykahsay --> 

- In **unreviewed/glycan_species.csv**, `"xref_id"` should match `"original_source_id"` if `"original_source_id"` starts with "comp_"

Currently: 
```
"glytoucan_ac","tax_id","tax_name","annotation_category","source","source_id","original_source_id","xref_key","xref_id","is_motif"
"G00194GV","2697049","Severe acute respiratory syndrome coronavirus 2","Direct","UniCarbKB","UniCarbKB","comp_HexNAc1Hex0dHex1NeuAc0NeuGc0Pent0S0P0KDN0HexA0","glycan_xref_unicarbkb_comp","UniCarbKB","False"
```
Change to:
```
"glytoucan_ac","tax_id","tax_name","annotation_category","source","source_id","original_source_id","xref_key","xref_id","is_motif"
"G00194GV","2697049","Severe acute respiratory syndrome coronavirus 2","Direct","UniCarbKB","UniCarbKB","comp_HexNAc1Hex0dHex1NeuAc0NeuGc0Pent0S0P0KDN0HexA0","glycan_xref_unicarbkb_comp","comp_HexNAc1Hex0dHex1NeuAc0NeuGc0Pent0S0P0KDN0HexA0","False"
```

- In glycan APIs, remove `species.evidence.url` for UniCarbKB id's that start with "comp_"


https://api.glygen.org/glycan/detail/G00194GV
Expected:

``` json
"species": [{
		"taxid": 2697049,
		"name": "Severe acute respiratory syndrome coronavirus 2",
		"annotation_category": "Direct",
		"evidence": [{
			"database": "UniCarbKB",
			"id": "comp_HexNAc1Hex0dHex1NeuAc0NeuGc0Pent0S0P0KDN0HexA0"
		},
```

**Comment by rykahsay** [comment]
please check  unreviewed/glycan_species.csv now --> the API response will change later when we push 2.1

**Comment by kmartinez834** [comment]
Issue taken up in #17
