### ISSUE TITLE
Info required on following pages and sections which have protein ac

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#331]
The below pages and sections would need additional info to better differentiate protein ac data.

**Glycan Detail**
Section - Expression
Tab - Tissue / Cell line
eg - https://www.glygen.org/glycan/G49108TO#Expression
Additional Info required - Organism name and Protein name (similar to associated protein)

**Publications Detail**
Section - Reference sections
eg - https://www.glygen.org/publication/PubMed/35289036#Referenced-Glycans
Additional Info required (for one organism) - Protein name
Additional info required (for two or more organisms) - Protein name and Organism

**Comment by jeet-vora** [comment]
@kmartinez834 

Can you review the mockup attached to add protein name and organism info - https://gwu0.sharepoint.com/:p:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Mockups/Protein_info%20-%20Name_Organism.pptx?d=w7f160d4e5f894b1891c8ce76ac0178af&csf=1&web=1&e=kI1Ljs

After you have reviewed it, please assign it to Rene and Sujeet

**Comment by kmartinez834** [comment]
Looks like this has been implemented on Publication page already. Glycan Expression changes still pending.

@sujeetvkulkarni --> Can you change "gene_name" header to "Gene Name"?

https://beta.glygen.org/publication/PubMed/23345538#Referenced-Proteins
![image](https://github.com/glygener/glygen-issues/assets/90285371/bbfab534-3791-40a9-895c-83e45c5d2aff)

**Comment by jeet-vora** [comment]
@sujeetvkulkarni Is this pending issue?

**Comment by sujeetvkulkarni** [comment]
@jeet-vora @kmartinez834 done on tst, please check.
https://tst.glygen.org/publication/PubMed/23345538#Referenced-Proteins

**Comment by jeet-vora** [comment]
Done
