### ISSUE TITLE
Update Contributor in Mindys curation table

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#332]
How would the "Contributor" [column value](https://docs.google.com/document/d/1QPWU29l6pzo8bKIQ6epEidPDDxyp-5JQk9drhS-zJOg/edit#) change if Ein (is her name spelled like this?) helps @Mindyporterfield by drawing the structures?

**Comment by kmartinez834** [comment]
createdBy:Mindy Porterfield([mindy@something.de](mailto:mindy@something.de), CCRC)|createdBy:Anh Nguyen(apnguyen@gwu.edu,The George Washington University)

**Comment by ReneRanzinger** [comment]
We have to update Senas tool to add this information.

**Comment by ReneRanzinger** [comment]
@senaarpinar Can you update the script to use the value above for the contributor column?

**Comment by ReneRanzinger** [comment]
There is also the update request in #622 .

**Comment by senaarpinar** [comment]
changed the contributor value
