### ISSUE TITLE
Human Pangenome evaluation

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#335]
I just learned about the human pangenome project (https://humanpangenome.org/). Currently we are mapping the proteins to the Ensembl Gene. Is it worth thinking about about mapping to the PanGenome? Is somebody working on this?

**Comment by ReneRanzinger** [comment]
From @rajamazumder:
Something to ask Maria, UniProt, EBI and NCBI. I briefly asked Evan who at NCBI we should talk to about genomic references and their plans. He asked me to reach out to Ilene. I will do so this summer. I have talked with her few times in the past years and it will be good to connect with her again.

**Comment by rajamazumder** [comment]
I am working with Maria, UniProt, folks at FDA to continue to explore this. This is a year long project and might get resolved end of 2024.

**Comment by ReneRanzinger** [comment]
@rajamazumder is this a typo or is that really end of 24?

**Comment by ReneRanzinger** [comment]
I will add this to as a task to the year 3 planning document.
