### ISSUE TITLE
GlyTouCan data processing

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#339]
Nathan's glycan export has been downloaded and saved at `/data/projects/glygen/downloads/glytoucan/current/`

Files were unzipped per `/data/projects/glygen/downloads/glytoucan/download_glytoucan.sh`

~~@rykahsay --> I was previously making the following changes to **byonic_glygen_human_nlinked.txt** using bash scripting, can you add/adjust your processing scripts instead?~~

~~- Print GlyTouCan Accession in first column, Byonic in second column~~
~~- Insert headers (GlyTouCanAccession, Byonic)~~
~~- Convert to tsv file~~

Edited: See new instructions below

**Comment by edwardsnj** [comment]
FYI, byonic_glygen_human_nlinked is not intended for y'all to load as a datafile. It is provided for others to use for Byonic - it is formatted as a Byonic database. 

- n

**Comment by kmartinez834** [comment]
We are currently using byonic_glygen_human_nlinked.txt as an input for glycan_type_n_linked_byonic.csv (GLY_000497), however we are creating byonic sequences for glycan_sequences_byonic.csv ourselves (using glycan_masterlist.csv and monocomp.tsv as inputs).

@rykahsay --> Please process glycan_type_n_linked_byonic.csv in the same way as glycan_sequences_byonic.csv

New inputs for **glycan_type_n_linked_byonic.csv**:
- downloads/glytoucan/current/export/classification.tsv
- downloads/glytoucan/current/export/species.tsv
- downloads/glytoucan/current/export/monocomp.tsv

Include accessions from 
classification.tsv:  `"Classification" == "N-linked"`
species.tsv:  `"Species" == "Human"`

**Comment by edwardsnj** [comment]
Probably should be using Byonic semantic names, not monocomp to determine Byonic format compositions - the specific thing that byonic_glygen_human_nlinked has is a reference to the specific GlyTouCan accession that is considered *the* accession for that composition. It should also remove Fuc containing Byonic strings. See my script here: https://github.com/glygen-glycan-data/PyGly/blob/master/smw/glycandata/scripts/byonic_database.py

**Comment by kmartinez834** [comment]
Closing issue and adding instructions for processing Byonic sequences in ticket #346
