### ISSUE TITLE
Remove size warning from Structure Search page...

### ISSUE THREAD

**Issue by edwardsnj** [glygener/glygen-issues#345]
The footnote: "Maximum number of monosaccharides supported is 10." is no longer correct.

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger still getting "Motif is too big" error for structure so assigning it to Robel. I guess he needs to make some changes to make it work on test server.

https://api.tst.glygen.org/job/status/?query={"jobid":23}

Dependent on :
remove size limit for structure search. #408

**Comment by ReneRanzinger** [comment]
@sujeetvkulkarni Not substructure search. This change only applies to structure search. The 10 residue max cap on substructure search remains as should the warning on the page.

**Comment by sujeetvkulkarni** [comment]
757aa68b37aebafd53685a35af31c028f69803de
