### ISSUE TITLE
Byonic sequence processing

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#346]
Adding details...

**Comment by kmartinez834** [comment]
@rykahsay Change processing steps for the following datasets:

:one:  **Dataset file: glycan_sequences_byonic.csv**

| Input files | 
| ----------- | 
| downloads/glytoucan/current/export/names.tsv | 
| downloads/glytoucan/current/export/subsumption.tsv| 
|unreviewed/glycan_masterlist.csv|

Steps: 
1. Extract rows from :page_facing_up:**names.tsv** which contain `"Domain" == "Byonic"`
```
GlyTouCanAccession      Name    Domain
G00194GV        HexNAc(1)dHex(1)        Byonic
G00273SJ        HexNAc(4)Hex(5)Fuc(4)   Byonic
```

2. The above file contains base composition structures only.  Use the :page_facing_up:**subsumption.tsv** file to assign the Byonic sequence to all descendants.
**Ex**: All accessions where `"RelatedAccession" == "G00194GV"` and `"Relationship" == "BaseComposition"` will have the Byonic for G00194GV: HexNAc(1)dHex(1)
```
$ grep "BaseComposition.*G00194GV" subsumption.tsv
GlyTouCanAccession      Relationship    RelatedAccession
G00194GV        BaseComposition G00194GV
G00362UY        BaseComposition G00194GV
G01002UX        BaseComposition G00194GV
G01447WV        BaseComposition G00194GV
G01854VF        BaseComposition G00194GV
...
```

3. Add mass to Byonic sequence.
4. Output file example:

| glytoucan_ac | sequence_byonic |
| ----------- | ----------- |
| G00009BX | HexNAc(2)Hex(2)dHex(1) % 894.33286578|
| G00012MO | HexNAc(1)Hex(3) % 707.248407805 |


:two:  **Dataset file: glycan_type_n_linked_byonic.csv**

| Input files | 
| ----------- | 
| downloads/glytoucan/current/export/byonic_glygen_human_nlinked.txt | 
|unreviewed/glycan_masterlist.csv|

Steps:
1. In :page_facing_up:**byonic_glygen_human_nlinked.txt** , move glytoucan accession to 1st column and byonic in 2nd column 
2. Add headers `"GlyTouCanAccession","Byonic"` and convert to tsv file
4. Generate output dataset with byonic sequences from this input file. Example output file:

| glytoucan_ac|byonic|
| ----------- | ----------- |
| G02438LG| dHex(1) % 146.057909|
| G81399MY| Hex(1) % 162.052823 |

@edwardsnj

**Comment by rykahsay** [comment]
Please check output files for correctness

**Comment by kmartinez834** [comment]
:one: **Dataset file: glycan_sequences_byonic.csv**
- ~~Sequence in dataset should match names.tsv exactly (ex. Fuc instead of dHex):~~ (See Nathan's comment below)
```
grep "G00273SJ.*Byonic" /data/projects/glygen/downloads/glytoucan/current/export/names.tsv 
G00273SJ        HexNAc(4)Hex(5)Fuc(4)   Byonic

grep "G00273SJ" /data/projects/glygen/generated/datasets/unreviewed/glycan_sequences_byonic.csv 
"G00273SJ","HexNAc(4)Hex(5)dHex(4) % 2224.8238081"
```
- We lost a lot more glytoucan ac's with Byonic sequences than I was expecting.  
--> Change subsumption logic so that `"RelatedAccession" == {GlyTouCanAccession from names.tsv}` and `"Relationship" == "Ancestor"`

**Comment by edwardsnj** [comment]
@kmartinez834 @rykahsay I think it is better to filter out the Fuc names (and use the dHex ones instead). Having both is confusing.

**Comment by rykahsay** [comment]
please check unreviewed/glycan_sequences_byonic.csv now

**Comment by kmartinez834** [comment]
Number of entries looks good.  

@rykahsay --> See Nathan's comment above, can you revert Fuc back to dHex?  Sorry :frowning:

**Comment by rykahsay** [comment]
I don't understand what you mean by "revert Fuc back to dHex" --> what exactly do I need to do? And I don't see Fuc in the row you showed.

<img width="1354" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/94264e3c-fe1b-4c95-9f13-3427372415ee">

**Comment by kmartinez834** [comment]
@rykahsay See instances where "Fuc" is still present below.  These are descendants of the accessions in names.tsv 

```
$ grep "Fuc" /data/projects/glygen/generated/datasets/unreviewed/glycan_sequences_byonic.csv | head -5
"G00012RZ","HexNAc(5)Hex(6)Fuc(3)NeuAc(1) % 2734.99351197"
"G00025HU","HexNAc(4)Hex(5)Fuc(1)NeuAc(1) % 2077.74549812"
"G00038JC","Hex(2)Fuc(2) % 634.23202944"
"G00056HH","HexNAc(5)Hex(6)Fuc(1) % 2151.78227759"
"G00068MO","Hex(1)Fuc(1) % 326.12129707"
```

**Comment by kmartinez834** [comment]
For clarification: Convert "Fuc" to "dHex" throughout

**Comment by edwardsnj** [comment]
@kmartinez834 @rykahsay I think there is a pretty fundamental misunderstanding here.

For the given glytoucan accession G00012RZ, it has two subsumption ancestors with Byonic semantic names:

G80075MS: HexNAc(5)Hex(6)Fuc(3)NeuAc(1)
G04784US: HexNAc(5)Hex(6)dHex(3)NeuAc(1)

G00012RZ is subsumed by G80075MS, which is subsumed by G04784US. 

My recommendation is that the dHex form "HexNAc(5)Hex(6)dHex(3)NeuAc(1)" be used as the Byonic sequence for G00012RZ. Note that the logic here is that as you look at the ancestors for one with a Byonic name, you disregard the Fuc names.

While functionally this is similar to just replacing all Fuc with dHex in whatever name you have, it will not have the correct logic for my request below. 

Furthermore, I'd really, really, really encourage you to generate the following output:

"G00012RZ","HexNAc(5)Hex(6)dHex(3)NeuAc(1) % 2734.99351197, G04784US"

So that the GlyTouCan accession that supplied the Byonic name is retained. 

Cheers!

- n

**Comment by rykahsay** [comment]
This is what I have now:


"glytoucan_ac","sequence_byonic","name_source"
"G00002CF","Hex(2)NeuGc(2) % 956.29687423","G93218EI"
"G00009BX","HexNAc(2)Hex(2)dHex(1) % 894.33286578","G93579XB"
"G00012MO","HexNAc(1)Hex(3) % 707.248407805","G08590QR"
**"G00012RZ","HexNAc(5)Hex(6)dHex(3)NeuAc(1) % 2734.99351197","G04784US"**
"G00013MO","Hex(4) % 666.2218587","G90306QO"
"G00014MO","HexNAc(2)Hex(2) % 748.27495691","G53434XO"
"G00015MO","HexNAc(1)Hex(3) % 707.248407805","G08590QR"
"G00016MO","Hex(2) % 342.1162117","G90627TW"
"G00017IP","HexNAc(4)Hex(3)Sulpho(1) % 1396.44334021","G67486RJ"

**Comment by kmartinez834** [comment]
There are still 347 accessions with "Fuc" in their Byonic sequence.  All of these are present in names.tsv, but they are subsumed by another Ancestor in names.tsv with "dHex"

```
$ grep "Fuc" /data/projects/glygen/generated/datasets/unreviewed/glycan_sequences_byonic.csv | head -1
"G00273SJ","HexNAc(4)Hex(5)Fuc(4) % 2224.8238081","G00273SJ"
```

Ancestor of G00273SJ is G05933EN:
```
$ grep "G00273SJ.*Ancestor" /data/projects/glygen/downloads/glytoucan/current/export/subsumption.tsv 
G00273SJ        Ancestor        G05933EN
```

Ignore the Byonic with "Fuc" in the name, and assign the ancestor's sequence with "dHex":
```
$ grep "G00273SJ\|G05933EN" /data/projects/glygen/downloads/glytoucan/current/export/names.tsv | grep Byonic
G00273SJ        HexNAc(4)Hex(5)Fuc(4)   Byonic
G05933EN        HexNAc(4)Hex(5)dHex(4)  Byonic
```

**Comment by rykahsay** [comment]
Done but the following still contain Fuc
```
$ cat unreviewed/glycan_sequences_byonic.csv | grep Fuc 
"G08539HC","HexNAc(7)Hex(6)Fuc(1)NeuAc(1) % 2849.03643944","G08539HC"
"G28320EF","HexNAc(3)Hex(2)Fuc(2)NeuAc(1) % 1534.56556389","G28320EF"
"G53495LU","HexNAc(7)Hex(6)Fuc(1)NeuAc(2) % 3140.13185607","G53495LU"
"G71504US","HexNAc(7)Hex(5)Fuc(1)NeuAc(1) % 2686.98361594","G71504US"
```

```
$ grep "G08539HC.*Ancestor" downloads/glytoucan/current/export/subsumption.tsv
G08539HC	Ancestor	G69509KI

$ grep "G08539HC\|G69509KI" downloads/glytoucan/current/export/names.tsv | grep Byonic
G08539HC	HexNAc(7)Hex(6)Fuc(1)NeuAc(1)	Byonic
```

**Comment by kmartinez834** [comment]
@edwardsnj see Robel's comment above.  For consistency, should we exclude these four accessions with "Fuc" sequences and no "dHex" alternative?

**Comment by edwardsnj** [comment]
Nope, IMO for consistency, these should not be kept. I will register the dHex versions so that they will ultimately be fine.

**Comment by kmartinez834** [comment]
@rykahsay --> Exclude the entries with "Fuc" in their Byonic sequence

**Comment by rykahsay** [comment]
Done, please check

**Comment by kmartinez834** [comment]
👍
