### ISSUE TITLE
download tst apis are down

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#347]
@rykahsay Download test apis are down. Can you please look into it.

https://api.tst.glygen.org/data/detail_download?query=
{"id":"P14210-1","download_type":"protein_detail","format":"json","compressed":false}
returns 
{
  "error_list": [
    {
      "error_code": "exception-error-EJ3IN4"
    }
  ]
}

similar case with
{
  "id": "G17689DH",
  "type": "glycan_detail",
  "format": "json",
  "compressed": false
}

**Comment by rykahsay** [comment]
Sorry, please try now

**Comment by sujeetvkulkarni** [comment]
@rykahsay still not working for me for section download. I am getting 502 Proxy Error
 error now.
https://api.tst.glygen.org/data/section_download?query=
{"id":"P13987-1","download_type":"protein_section","section":"glycosylation_reported_with_glycans","format":"csv","compressed":false}

**Comment by rykahsay** [comment]
Please try now

**Comment by sujeetvkulkarni** [comment]
done.
