### ISSUE TITLE
Resources to update?

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#348]
@rykahsay The following files are used as inputs for datasets, but haven't been updated in a while.  

--> Have you downloaded any of these files previously, or were they Rahi's responsibility?  

Resource | File name(s) | Last Downloaded
-- | -- | --
ChEBI | database_accession.tsv |  7/16/2021
GlyCosmos | glycosmos_gdgdb.csv <br /> ggdonto.ttl | 4/8/2021
Reactome | ChEBI2Reactome_PE_Pathway.csv |  4/8/2021

**Comment by rykahsay** [comment]
No --> at least I don't remember

**Comment by kmartinez834** [comment]
I've asked the admin team to retrieve documents from Confluence so I can look for documentation.  Plan to update these resources in 2.2

**Comment by kmartinez834** [comment]
@rykahsay Jeet was able to retrieve Rahi's documentation from Confluence, downloading now.  I will ping you when this is done.

**Comment by kmartinez834** [comment]
Status of downloads in #359
