### ISSUE TITLE
Unable to download new GlyConnect files

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#349]
When I tried to download new files, I got the following error:
```
$ wget https://glyconnect.expasy.org/api/glycosylations?taxonomy=Rattus%20norvegicus

--2023-05-18 11:57:26--  https://glyconnect.expasy.org/api/glycosylations?taxonomy=Rattus%20norvegicus
Resolving glyconnect.expasy.org (glyconnect.expasy.org)... 192.33.215.22
Connecting to glyconnect.expasy.org (glyconnect.expasy.org)|192.33.215.22|:443... connected.
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Unable to establish SSL connection.
```

Looking into the issue online, I think it's because our server's current version of wget (1.14) doesn't support SNI and needs to be udpated.  I was able to download from GlyConnect's API to my local computer, which uses wget version 1.20.3

@rykahsay --> Can you look into this?

**Comment by rykahsay** [comment]
I have asked Dacian and see if he can do it (I am not able to upgrade)

<img width="995" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/014529a2-c809-4188-aa22-167c2b03081f">

**Comment by rykahsay** [comment]
He proposed OS update and I don't want to do that since it will mean lots of disruptions in the middle of our work now. Since glyconnect is the only problem at this point, please download to your laptop and then scp it to the dev server for now.

**Comment by kmartinez834** [comment]
Done, the current link now points to the hybrid folder with new data for all species except human.  Human data was copied from the previous download.
