### ISSUE TITLE
Update Rajas about entry

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#350]
@rajamazumder provided a new picture for the about page. Please cut it and replace the old one. He will also send a new link. The current link is not working.

![Mazumder Rajapng](https://github.com/glygener/glygen-issues/assets/2267640/4ef406cc-17a9-4c51-9c9c-3b638afbcda0)

**Comment by ReneRanzinger** [comment]
Use this URL: https://www.linkedin.com/in/rajamazumder

**Comment by sujeetvkulkarni** [comment]
62b001d6dcc7eac38ac8b39f2823beb8755cad10

**Comment by sujeetvkulkarni** [comment]
d63d183caa6add9176f025775a503243c3d44383
