### ISSUE TITLE
Change processing steps for Reactome datasets

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#351]
The following datasets are affected:

| Dataset files | 
| ----------- | 
| glycan_xref_reactome.csv | 
| glycan_pathway_reactome.csv| 

**Processing steps:**

1. Convert  :page_facing_up:**downloads/reactome/current/ChEBI2Reactome_PE_Pathway.txt** to csv file
2. Add headers 
`"chebi_id,reactome_compound_id,compound_name,reactome_pathway_id,reactome_pathway_url,pathway_name,c7,species_scientific_name"`
3. Continue with dataset processing as usual

**Comment by rykahsay** [comment]
please check now

**Comment by kmartinez834** [comment]
Looks good
