### ISSUE TITLE
Allison's pathways

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#353]
From @mtiemeyer0919:

Here's the link:

http://glycoenzymes.ccrc.uga.edu/Glycomics3/

Mouse enzymes annotated, but sure that Kelley has human assignments as well.

**Comment by edwardsnj** [comment]
Actually need the corresponding human orthologs - I’m already using this mouse data.

**Comment by edwardsnj** [comment]
@mtiemeyer0919 - can you ask about human ortholgs? In addition, the “rules” about structural context are not explicit in this presentation. Where do these come from?

**Comment by mtiemeyer0919** [comment]
Will do regarding the ask.  As I mentioned at our all hands, I know that Alison and Kelley mapped the human orthologs to the extent they could.  I will ask Kelley what he can supply.

The rules come from Alison and Kelley and their consultations with literature and domain experts—similar to N-Glycotree but not necessarily documented as thoroughly yet.  A task that we need to consider.

Cheers,
MikeT

Sent from my iPhone

On May 20, 2023, at 6:47 PM, Nathan Edwards ***@***.***> wrote:

﻿ [EXTERNAL SENDER - PROCEED CAUTIOUSLY]


@mtiemeyer0919<https://github.com/mtiemeyer0919> - can you ask about human ortholgs? In addition, the “rules” about structural context are not explicit in this presentation. Where do these come from?

**Comment by mtiemeyer0919** [comment]
Send link and spreadsheet to Nathan

**Comment by mtiemeyer0919** [comment]
Sent, not send, link and spreadsheet to Nathan.  Spreadsheet included here.  
[Ortholog gene list.xlsx](https://github.com/glygener/glygen-issues/files/12021594/Ortholog.gene.list.xlsx)
@edwardsnj 
@ReneRanzinger
