### ISSUE TITLE
https://api.glygen.org/ Down

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#356]
- API giving 502 Proxy Error

![image](https://github.com/glygener/glygen-issues/assets/90285371/3c4341c0-8baa-4a46-a6bc-90761688c9fe)

- Data on glygen.org not loading:

![image](https://github.com/glygener/glygen-issues/assets/90285371/23f0d5ef-7bbb-4907-acdb-54ad48e6781d)

**Comment by rykahsay** [comment]
I do not know what happened but I don't see this problem anymore
