### ISSUE TITLE
Issue with BCO Portal URL

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#357]
@HadleyKing and @rykahsay 

The BCO Portal url in the BCO does not resolve the page in the BCO portal. Below is the error I am getting.

https://biocomputeobject.org/GLY_000001/2.0.3

<img width="1255" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/36551319-da63-4472-8427-1f7acf6f2c69">

**Comment by HadleyKing** [comment]
@jeet-vora The object you are looking for does not exist. That is the expected behavior.

**Comment by jeet-vora** [comment]
@HadleyKing What about this - https://biocomputeobject.org/GLY_000002/2.0.3
The object does exist - https://data.glygen.org/GLY_000002

**Comment by rykahsay** [comment]
<img width="746" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/1fd4cba6-6fc5-48d3-9839-217988ba462c">

**Comment by jeet-vora** [comment]
works
