### ISSUE TITLE
2.1 Downloads

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#359]
**Key:**
:ballot_box_with_check: Check if done
:x: Strike through if skipped
:construction: Add ticket number next to resource if dependencies exist

**All Resources:**
- [x] ~~Genome Alliance~~ (:x:skipped for next release)
- [x] ~~O-GlcNAc Atlas~~ (:x:Working on protocol)
- [x] ~~BiomarkerDB~~ (:x:No new updates)
- [x] ~~BioMuta~~ (:x:No new updates)
- [x] ~~BioXpress~~(:x:No new updates)
- [x] Cellosaurus #361 
- [x] ChEBI 
- [x] Disease Ontology #263
- [x] EBI #263
- [x] ~~Genomics England~~ (:x:File structure changes, will be updated in 2.2) 
- [x] ~~Glycan Structure Dictionary~~ (:x:No new updates)
- [x] Glycan List 
- [x] Glyconnect 
- [x] ~~Glycosmos~~ (:x:No new updates)
- [x] GlyTouCan
- [x] GNOme
- [x] ~~GPTwiki~~ (:x:No new updates)
- [x] ~~Glycogenes~~ (:x:No new updates)
- [x] ~~GlycoProtDB~~ (:x:skipped for next release)
- [x] ~~Harvard~~ (:x:No new updates)
- [x] iPTMnet #263
- [x] IsoGlyP (:x:skipped for next release)
- [x] ~~Literature mining~~ (:x:skipped for next release)
- [x] MatrixDB #364
- [x] Medline #361 
- [x] MGI #263
- [x] Mondo #263
- [x] NCBI RefSeq #263
- [x] ~~NCFG~~ (:x:No new updates)
- [x] O-GlcNAc DB  #263
- [x] ~~OHSU~~ (:x:No new updates)
- [x] OMA #366
- [x] ~~PDB~~ (:x:skipped for next release)
- [x] ~~Pharos~~ (:x:skipped for next release)
- [x] ~~PRO~~ (:x:No new updates)
- [x] Sandbox
- [x] PubChem/InChI key  #361 
- [x] Reactome
- [x] ~~UCSC~~ (:x:No new updates)
- [x] ~~UniCarbKB~~ (:x:No new updates)

**Comment by kmartinez834** [comment]
@jeet-vora @JingyueWu Update status of datasets you are working on above

**Comment by JingyueWu** [comment]
@kmartinez834 Done.

**Comment by kmartinez834** [comment]
@rykahsay

**Comment by kmartinez834** [comment]
@rykahsay all downloads are complete except those in #361 (assigned to you).  Once 361 is done, proceed with processing all remaining datasets.
