### ISSUE TITLE
Downloads for Robel

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#361]
@rykahsay --> download the following source files:

- [ ] Cellosaurus
- [ ] Medline
- [ ] InChI keys

**Comment by rykahsay** [comment]
All downloaded -- please check.
There is not processing needed for cellosaurus, so you can download it yourself next time.

<img width="1319" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/66b06a8c-0f96-4591-8050-04304e536bd1">

**Comment by kmartinez834** [comment]
Thanks, updating docs for cellosaurus download
