### ISSUE TITLE
GlyGen in Bioregistry

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#362]
https://bioregistry.io/registry/glygen

Do we know Charles Hoyt? It seems we do not have control over this entry. There are also several issues with it since it only focusing on glycans.

**Comment by jeet-vora** [comment]
@ReneRanzinger 
No we do not know Charles Hoyt.
Is it possible he might have pulled the data from here - https://fairsharing.org/FAIRsharing.aI1J5W 
It seems that our record in FAIRsharing hasn't been updated since 2019.

We can contact him and ask the details.
cthoyt@gmail.com

Let me know to contact him. Btw how did you come across the bioregistry link?

**Comment by ReneRanzinger** [comment]
Please do contact him. We should try to get control of both bioregistry and fairsharing + update them.

I was reviewing my old notes and we were talking about bioregistry in 2021. When I checked I found the entry but noticed it was outdated and "wrong".

**Comment by jeet-vora** [comment]
Aug 31, 2023

Hi Charles,

I work on the GlyGen project, and we came across GlyGen's page in Bioregistry - https://bioregistry.io/registry/glygen. It seems like you have contributed to the page, and we are thankful for that. Upon close examination, we found that certain details are missing and outdated. Is there a way we can get access to the page to edit the information and keep it updated?

We appreciate your help.

**Comment by jeet-vora** [comment]
Submitted a pull request (https://github.com/biopragmatics/bioregistry/pull/1015)

Some info yet to be added.

Hi Charles,
I hope you are doing well.

I have finally submitted a pull request for updated bioregistry.json with edited GlyGen information.

However can you let us know how do we add the below missing information? Thanks
![image](https://github.com/glygener/glygen-issues/assets/25825266/bcb75df1-5782-40a8-b4db-a3d57bbff142)

**Comment by jeet-vora** [comment]
Thanks @jeet-vora, I incorporated your suggestions. Note that UniProt is a fully distinct semantic space and therefore does not get included in the glygen prefix, even if the corresponding GlyGen website can resolve UniProt IDs.

Pull request successfully merged and closed
