### ISSUE TITLE
Redownload the OMA datasets

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#363]
Robel will reprocess the OMA files by adding headers. Please follow the instructions below.

- [ ] Create folder 2023_05_23 in oma directory
- [ ] Redownload the OMA files for the four organisms using the instructions in the server as txt files.
- [ ] Name the files accordingly.
- [ ] Create the symbolic link for the new release folder
- [ ] Change the group permission to 775

- Do not add the headers. Robel will add headers

Once downloaded, reassign the ticket to me.

**Comment by kmartinez834** [comment]
@JingyueWu @jeet-vora I created a script to complete the above steps, saved at `downloads/oma/download_oma.sh` 

I downloaded the new files to make sure there weren't any bugs in the script.  Note, the file names do not contain the date anymore so Robel's scripts won't break with each new release.

--> Please create ticket for Robel to convert to csv (if needed), add headers, and update his pipeline to accept the new file names without dates (ex. human_rat_oma_orthologs)

**Comment by jeet-vora** [comment]
Done
