### ISSUE TITLE
URGENT: bad downloads in downloads/alliance_genome/current/

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#365]
- file is not a text/tsv file
- why change file name? 
- wrong file persmissions

<img width="1326" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/8e8513de-ba56-4f0a-a27b-7431c0c77316">

**Comment by jeet-vora** [comment]
@rykahsay Genome Alliance is not to be processed for this release. It will be used as a new resource for orthology for next release. I will be creating a ticket for processing the file in next release.

**Comment by rykahsay** [comment]
@jeet-vora @JingyueWu --> then point the "current" link to the old folder

**Comment by jeet-vora** [comment]
Done. The dataset will be processed in next release.
