### ISSUE TITLE
Process OMA files

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#366]
@rykahsay Please add the following headers to downloaded OMA files under data/projects/glygen/downloads/oma/current/ and process the file accordingly, as mentioned below.

Organisms
human, mouse, rat and fruitfly
Steps

**Please note - The earlier OMA files had Ensembl ACs but they are being changed to UniProtAC as the format is now available. One of the issue with the source file is that it contains a mix of UniprotKB ac and UniProtKB IDs (for TrEMBL acs)

**Step 1a:** Map UniProtKB ac as per the organism to the canonicals from field 1 and field 2 with 1:1 ortholog_subtype only
`eg Q9VIE6	Q7L590	1:1	1176029`

**Step 1b** Map UniProtKB IDs as per the organism to the canonicals from field 1 and field 2 using the *_protein_info_uniprotkb.csv with 1:1 ortholog_subtype only
`eg Q9VR06_DROME	A0A6Q8PGC1_HUMAN	1:1	1102927
`
Note - There are certain rows that contain a mix of UniProtKB ac and UniProtKB ID so process accordingly with 1:1 ortholog_subtype. All UniProtKB IDs have "_ underscore".
`eg P33450	A0A6Q8JR05_HUMAN	1:1	687779
`

Rest of the processing workflow remains the same.

For adding headers to the source files
```
data/projects/glygen/downloads/oma/current/**fruitfly_human_oma_orthologs.txt**
uniprotkb_ac_fruitfly,uniprotkb_ac_human,ortholog_subtype,oma_group

data/projects/glygen/downloads/oma/current/**fruitfly_mouse_oma_orthologs.txt**
uniprotkb_ac_fruitfly,uniprotkb_ac_mouse,ortholog_subtype,oma_group

data/projects/glygen/downloads/oma/current/**fruitfly_rat_oma_orthologs.txt**
uniprotkb_ac_fruitfly,uniprotkb_ac_rat,ortholog_subtype,oma_group

data/projects/glygen/downloads/oma/current/**human_fruitfly_oma_orthologs.txt**
uniprotkb_ac_human,uniprotkb_ac_fruitfly,ortholog_subtype,oma_group

data/projects/glygen/downloads/oma/current/**human_mouse_oma_orthologs.txt**
uniprotkb_ac_human,uniprotkb_ac_mouse,ortholog_subtype,oma_group

data/projects/glygen/downloads/oma/current/**human_rat_oma_orthologs.txt**
uniprotkb_ac_human,uniprotkb_ac_rat,ortholog_subtype,oma_group

data/projects/glygen/downloads/oma/current/**mouse_fruitfly_oma_orthologs.txt**
uniprotkb_ac_mouse,uniprotkb_ac_fruitfly,ortholog_subtype,oma_group

data/projects/glygen/downloads/oma/current/**mouse_human_oma_orthologs.txt**
uniprotkb_ac_mouse,uniprotkb_ac_human,ortholog_subtype,oma_group

data/projects/glygen/downloads/oma/current/**mouse_rat_oma_orthologs.txt**
uniprotkb_ac_mouse,uniprotkb_ac_rat,ortholog_subtype,oma_group

data/projects/glygen/downloads/oma/current/**rat_fruitfly_oma_orthologs.txt**
uniprotkb_ac_rat,uniprotkb_ac_fruitfly,ortholog_subtype,oma_group

data/projects/glygen/downloads/oma/current/**rat_human_oma_orthologs.txt**
uniprotkb_ac_rat,uniprotkb_ac_human,ortholog_subtype,oma_group

data/projects/glygen/downloads/oma/current/**rat_mouse_oma_orthologs.txt**
uniprotkb_ac_rat,uniprotkb_ac_mouse,ortholog_subtype,oma_group
```

@JingyueWu Please read and try to understand.

**Comment by rykahsay** [comment]
Check the output file unreviewed/protein_homolog_clusters.csv

**Comment by jeet-vora** [comment]
Checked no issues

**Comment by jeet-vora** [comment]
@rykahsay You are not adding headers to the source files? You are processing them as is? Can you confirm.

**Comment by jeet-vora** [comment]
No answer received from Robel.
