### ISSUE TITLE
No rat glycan data on data

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#368]
* Go to data.glygen.org
* Apply species filter: Rattus norvegicus
* Apply Molecule filter: Glycan

![rat](https://github.com/glygener/glygen-issues/assets/2267640/75893849-4c90-4505-b7a1-e7c2489da46a)

**No result found!** 

Why?

**Comment by kmartinez834** [comment]
@ReneRanzinger --> Glycan datasets are species agnostic, glycan species data is located in [glycan_species.csv](https://data.glygen.org/GLY_000341)

**Comment by ReneRanzinger** [comment]
But wouldn't it be correct that at least this dataset is found when I am looking for "rat" + "glycan"?

**Comment by kmartinez834** [comment]
I will update the BCO to include the organisms, this should allow them to be filtered.  Same for #369

**Comment by kmartinez834** [comment]
@rykahsay if I want to assign multiple species tags to a dataset, do I add as separate items to the BCO or create an array within the species object?

``` json
"dataset_categories": [
                    {
                        "category_value": "Drosophila melanogaster",
                        "category_name": "species"
                    },
                    {
                        "category_value": "Homo sapiens",
                        "category_name": "species"
                    },

```

vs.

``` json
"dataset_categories": [
                    {
                        "category_value": ["Drosophila melanogaster", "Homo sapiens"],
                        "category_name": "species"
                    },
```

**Comment by rykahsay** [comment]
Yes, but are you assuming all glycan datasets have glytoucans that have rat annotation? In other words, if there is a glycan dataset which contains glytoucan accessions that are only in human, it would be wrong to give that dataset a category of rat. To do this correctly, you will need to write a script --

**Comment by kmartinez834** [comment]
@rykahsay @jeet-vora file requested with `"bco_id","file_name","tax_id","tax_name"` is located at **/data/projects/glygen/generated/misc/assign_bco_species_2.1.1.csv** --> Update BCO species field according to this file

Script saved at /software/glygen/ 
Run command:
`python3 /software/glygen/assign_bco_species.py -v 2.1.1`

Note: The following files did not have uniprotkb/glytoucan accessions, or weren't parsed due to file format:
```
No UniProtKB accession found: protein_ncbi_pubmed_linkouts_one.csv
No UniProtKB accession found: protein_disease_idmap.csv
No UniProtKB accession found: protein_ncbi_pubmed_linkouts_two.csv
No UniProtKB accession found: protein_ncbi_gene_linkouts.csv
No UniProtKB accession found: protein_disease_names.csv
File type not accepted: glycan_rdfdata.rdf.gz
No UniProtKB accession found: protein_ncbi_pubmed_linkouts_three.csv
```

**Comment by rykahsay** [comment]
Implemented now

<img width="1216" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/cb4699b3-5eb9-4334-b83e-88078a8b93b0">

**Comment by ReneRanzinger** [comment]
The original problem is solved but now it shows a lot of datasets that are rat but not glycan related and in turn that are glycan related but not rat. I think that is a problem of the filter logic. It seems it treats an tickbox as part of an "OR" statement. Within a category ("By species" or "by Molecule") that make sense but between categories I think it should be "AND". I can not think of a query for a dataset that I would search for "rat OR glycan". I my mind that should be "rat AND glycan" to find all glycan datasets with rat association. If you feel otherwise why not added an AND/OR option on top of the filters that allow the users to pick his own poison? Similar as we do it in glygen search result pages.

**Comment by rykahsay** [comment]
"... but now it shows a lot of datasets that are rat but not glycan related and in turn that are glycan related but not rat"

All checkboxes are joined by "AND". 

Can you tell me an example? When I check "Rattus norvegicus" and "Glycan", I see 60 datasets that are glycan datasets and have glycans annotated "Rattus norvegicus".


<img width="1053" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/c2fb8c4f-1271-4543-a583-f78c6b77b071">
