### ISSUE TITLE
Human glycan data not found

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#369]
This is similar to #368.

But there is at least one dataset in the glycan list that is explicitely labeled as human and still not found:

https://data.glygen.org/GLY_000497

**Comment by kmartinez834** [comment]
Added tag to BCO so "human" filter will apply to dataset
![image](https://github.com/glygener/glygen-issues/assets/90285371/2a58a17d-d405-4d82-89d5-652878ae392c)

Added testing tag to make sure this goes into effect

**Comment by kmartinez834** [comment]
GLY_000497 now appears when human filter is applied:
https://data.tst.glygen.org/
![image](https://github.com/glygener/glygen-issues/assets/90285371/67d2b053-f34e-4769-a520-075942ddcf92)

**Comment by ReneRanzinger** [comment]
Not sure that is working properly. I come to the page 562 datasets. I add the Glycan filter ... 61 datasets left. Now I add the Homo sapiens filter ... 182. I would expect it to be less or equal but not more. Just because I added a new filter the number of glycan datasets should not increase.

**Comment by ReneRanzinger** [comment]
Hmm ... seems like the different filter groups (By species, By Molecule etc) are OR connected. Shouldnt they be AND connected?

**Comment by kmartinez834** [comment]
Yes, adding the filtering issue as a bug to #418

Can we close this issue since the human glycan dataset contains the human label now?
