### ISSUE TITLE
Pagging issue when filtering on data.glygen.org

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#370]
* Go to data.glygen.org
* Go to page 5 of the list of datasets
* Open the filter option and select "Sars coronavirus (sars-cov-2 or 2019-ncov) (35)"
* Apply

![filter](https://github.com/glygener/glygen-issues/assets/2267640/00f653d2-d18c-4813-b43a-6016779a54a9)

The list is empty although there are 35 results. Its up to the user to understand that he needs to "page back" to get into the valid range.

When filtering the user should either consistently:
* end back on page 1 
**OR**
* if he leaves the valid range of pages end up on the current last page

**Comment by rykahsay** [comment]
The new search result appearance resolves this issue
