### ISSUE TITLE
Send report template to Advisors

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#374]
During the F2F we decided to send the advisors (Lynn, Rebecka, Mike) a template of the report they are to provide for us. The report will not go to NIH but be used internally.

**Comment by jeet-vora** [comment]
Template - https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Meetings/GlyGen%20Meetings/2023.05.%20Annual%20meeting%202023/GlyGen%20F2F%202023%20Feedback.docx?d=wa67bff1e482f43e19f472f02cc8d9187&csf=1&web=1&e=xwZWqt

**Comment by jeet-vora** [comment]
Closing this for now. Next time we should ask for the feedback right after the meeting and not wait till we edit/consolidate things.
