### ISSUE TITLE
Create GlycoCT{xml} dataset

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#375]
Determine if this will be done in 2.1 or 2.2...

Move to 2.2

**Comment by kmartinez834** [comment]
@rykahsay there will be a new glycan dataset in 2.2...
--> **Wait for new glycan export (~Aug 7) to process**

**New dataset:** glycan_sequences_glycoctxml.csv

**Source files:** 
Location: downloads/glytoucan/current/export/
glycoctxml.tsv
glycoctxml.zip.00
glycoctxml.zip.01
glycoctxml.zip.02
glycoctxml.zip.03

**Comment by rykahsay** [comment]
You will need to do the following steps to prepare this further.

```
$ cd  downloads/glytoucan/current/export/
$ mkdir glycoctxml
$ cat glycoctxml.zip.* > glycoctxml/glycoctxml_all.zip
$ cd glycoctxml
$ unzip glycoctxml_all.zip
$ cd ..
$ chown -R karina:glygen glycoctxml
$ chmod -R 775 glycoctxml
```

**Comment by rykahsay** [comment]
I have done those steps for now, please check the dataset (unreviewed/glycan_sequences_glycoctxml.csv)

**Comment by kmartinez834** [comment]
Added pre-processing step to download script.  Reviewed dataset, looks good 👍
