### ISSUE TITLE
Paper preprocessing

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#376]
Based on Mikes list (#333). 

* Download all the papers and supplementary materials and put them in Sharepoint.
For each paper create a separate folder in *Sharepoint://Mindys work/* which contains the PMID. Inside the new folder create a subfolder (e.g., *Material* or *Paper*) and place the downloaded files there.

* Create for each paper a new ticket
Title of the ticket is PMID - Paper title. As description point to the location of the paper files.

* Choose an order in which the papers should be processed
Lets focus on N-glycans first and put the O-glycans last

**Comment by Mindyporterfield** [comment]
Complete but put in a folder called paper curation not in my Mindy work folder
Download all the papers and supplementary materials and put them in Sharepoint.
For each paper create a separate folder in Sharepoint://Mindys work/ which contains the PMID. Inside the new folder create a subfolder (e.g., Material or Paper) and place the downloaded files there.

**Comment by Mindyporterfield** [comment]
Complete
Create for each paper a new ticket
Title of the ticket is PMID - Paper title. 
Not complete (how do i do that?)
As description point to the location of the paper files.

**Comment by ReneRanzinger** [comment]
@Mindyporterfield 

Two options:
1. Make a link: [Paper](https://gwu0.sharepoint.com/sites/GlyGenTeam-GRP/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FGlyGenTeam%2DGRP%2FShared%20Documents%2FPaper%20Curation%2FPMID%C2%A036740532%2FPaper&viewid=6ffb8fed%2D81e7%2D4af7%2Dbfcd%2Da6f29c268132)
Click on the little chain symbol above the text field (6 icon from left). It will add a placeholder `[](url)` at the position of the cursor. Add the label for the link (e.g. Paper) in the square bracket. Replace `url` with the URL to the folder with the paper, which you can copy from the browser. The URL is only accessible for people that have accounts in Sharepoint.

2. Just describe the location: e.g. Sharepoint://Paper Curation/PMID.../Paper

In addition you should leave some instructions for Anh in each ticket. I think what we need is:
* Type of Glycan (N,O,GSL)
* List of which glycans  to extract (e.g. Figure 2, Table B, Supplement File X: Table 3, Figure 4 only top right structure) The last might be useful for annotated MS spectra. We dont want her to draw fragments.
* Reducing end configuration to use (reduced, closed ring)
* How to split the glycans into files (e.g. one file per table/figure; all in one file) and how to name them. For at least the first few papers you will have to crosscheck the glycans. In that case it may be helpful to do them per figure or table so you do not have to search the entire paper so where she got a certain glycan from.

Any other information she may need to avoid mistakes or causing more work?

**Comment by ReneRanzinger** [comment]
@Mindyporterfield Also add them to the curation project. Right side of the ticket are a bunch sections (assignee, label etc.). In the project section choose "Curation Project".
