### ISSUE TITLE
More information needed in downloads/sandbox/current/glycotree_annotated_glycans.csv 

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#377]
Current version:
<img width="1170" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/c28556dc-7ff7-4374-b95a-023cf4fa05c3">

Older version:
<img width="1404" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/9533a189-4801-4736-b4e3-9e00ba19c641">

**Comment by kmartinez834** [comment]
Script updated and file corrected.

--> See `/data/projects/glygen/downloads/sandbox/current/glycotree_annotated_glycans.tsv`
