### ISSUE TITLE
Setup meeting with Maria to talk about SNV/variant data

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#379]

**Comment by jeet-vora** [comment]
Email sent to Maria and Preethi on May 26.
 https://doodle.com/meeting/participate/id/dNY3vj8b

**Comment by jeet-vora** [comment]
Done.
 Last meeting Sept 8, 2023

**Notes:**
UniProt can use the COSMIC data without a license. For patient frequency license would be required. The COSMIC data from UniProt can be distributed and reused.
UniProt can use Google Query for TCGA data, can pay small amount for Google Query.
The variation pipeline with all the components can be setup by early next year to produce data for UniProt and GlyGen.

**Action Items:**
Jeet to share COSMIC dataset with few rows with all the fields with James.
James to talk to COSMIC to see if all the fields can be retrieved from COSMIC. 
Maria/James to look into the TCGA pipeline at EBI and know what is collected and presented including patient frequency data.
James to check if COSMIC has ICGC data, also look into CIVIC resource.
Jeet to share details of the Google Query information and download files.
James to let Preethi know about additional HUMSAVAR data that can be added into the existing data.
Preethi-James to review the current ProtVar Xrefs information.
James to send the documentation/information about the selection of best 3D structure.
