### ISSUE TITLE
BCO Edits

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#380]
Go to https://beta-data.glygen.org/

Search under dataset metadata and search human in the search bar.
    
You will get 154 datasets. In the left By species box, select Sars coronavirus (sars-cov-1) (25)
<img width="1274" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/edc8104c-97d8-42e9-a06e-413b1b97c8ef">

    
The search page will show you 25 datasets. Note down the BCO IDs for the 25 datasets.
    
Click on view details for any of the dataset and go to BCO JSON tab. For eg GLY_000411 dataset
    
Search 'human' using CTRL+F, you will find the human is part of the uri and filename under input list under pipeline steps. The goal here is to remove the word human from sars-coronavirus files.
<img width="1130" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/ff86c59a-c9cb-4df8-b86c-9d9801b1cb48">

Go to biocomputeobject.org, go to Biocompute DB.

Search for GLY_000411 dataset under advanced search using the BCO IDs as search type, click on the draft version. 
    
<img width="1232" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/b41a5401-f65c-484b-b349-6a9abc99c0f8">

Go to raw view and search human using ctrl+F
    
Remove human-
    
Click submit changes and verify the change.
    
Do this for the rest of SARS-CoV1 and SARS-CoV2 datasets you found during the initial search.

**Comment by JingyueWu** [comment]
@jeet-vora Thanks for the detailed instructions. GLY_000411 has been modified (i.e. removing "human") and passed the validation test. Here is the link: https://biocomputeobject.org/builder?https://biocomputeobject.org/GLY_000411/DRAFT

Currently working on doing the same for the ones found during the initial search.

**Comment by JingyueWu** [comment]
@jeet-vora This task is completed, please check. 

All "human" have been removed under Raw View in all DRAFTS for 25 sars-cov-1 and 2 sars-cov-2.

**Comment by jeet-vora** [comment]
Done
