### ISSUE TITLE
Check protein datasets under unreviewed

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#389]

**Comment by jeet-vora** [comment]
Will be adding issues in the dataset here

- [x]  #400 
- [x] #403

**Comment by jeet-vora** [comment]
Protein datasets have been checked. No major issues found. Drop or increase in numbers as expected.
Datasets from Refseq source files have a drop in id and row count - the data from the source has changed, doesn't contain all the files like from the previous release. Will be reaching out to RefSeq to know more.
