### ISSUE TITLE
Creating BCOs from command line script

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#39]
On glygen dev server:

Create template BCOs under /data/projects/glygen/generated/bco_templates/ like
- /data/projects/glygen/generated/bco_templates/protein.1.json
- /data/projects/glygen/generated/bco_templates/protein.2.json
- /data/projects/glygen/generated/bco_templates/glycan.1.json
- /data/projects/glygen/generated/bco_templates/glycan.2.json
-  ... so on

Then use these commands to create one BCO at a time (where $TOKEN is your autherization token given to you by Hadley).

- cd /software/glygen/
- python3 create-bco.py -t $TOKEN -f bco_templates/protein.1.json

Note that /software/glygen/bco_templates is a symbolic link to /data/projects/glygen/generated/bco_templates/

**Comment by kmartinez834** [comment]
- Copied /data/projects/glygen/generated/misc/bco_glycan_template.json (#2 ) to /data/projects/glygen/generated/bco_templates/ and saved as **glycan.1.json**
- Successfully created a new BCO:
```
{
    "request_status": "SUCCESS",
    "status_code": "201",
    "message": "The object with ID 'https://biocomputeobject.org/GLY_000707/DRAFT' was created on the server.",
    "object_id": "https://biocomputeobject.org/GLY_000707/DRAFT"
}
```
FYI - the private token is located at https://biocomputeobject.org/account under the "Database, Groups, and Permissions" dropdown

**Comment by jeet-vora** [comment]
BCO creations successful

@JingyueWu You are at the moment not making any BCOs so closing the ticket but in future you can access the details from data integration documentation to create the BCOs
