### ISSUE TITLE
Issue human_protein_disease_genomics_england

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#400]
Robel the source file has 115 genes - /data/projects/glygen/downloads/genomics_england/current
 whereas the dataset human_protein_disease_genomics_england has only 61 genes.

Some of the genes like DDOST, PGAP3, POMGNT2 are not getting mapped. Can you look into it. I am expecting a mapped number of above 100 genes

@JingyueWu

**Comment by rykahsay** [comment]
Because the value for the "source" field does contain the string "Expert Review Green"

<img width="1425" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/e4190175-61d3-4963-8cd8-6a93bdcdfa73">

**Comment by jeet-vora** [comment]
Ok Got it

What about these genes, these are also being filtered out as Expert Review Green does not appear as first entry - NHS GMS;**Expert Review Green**;
| Gene Symbol | Sources(; separated)                                                                                                                                             |
| ----------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| B4GALNT1    | NHS GMS;Expert Review Green;Expert list                                                                                                                          |
| DPM2        | NHS GMS;Expert Review Green;Radboud University Medical Center, Nijmegen;Other;Illumina TruGenome Clinical Sequencing Services;Emory Genetics Laboratory          |
| EDEM3       | NHS GMS;Expert Review Green;Literature                                                                                                                           |
| EOGT        | NHS GMS;Expert Review Green;Expert list                                                                                                                          |
| G6PC3       | NHS GMS;Expert Review Green;Expert list                                                                                                                          |
| GORAB       | NHS GMS;Expert Review Green;UKGTN;Emory Genetics Laboratory;Radboud University Medical Center, Nijmegen;Illumina TruGenome Clinical Sequencing Services;Research |
| MAGT1       | NHS GMS;Expert Review Green;UKGTN;Radboud University Medical Center, Nijmegen;Literature                                                                         |
| PIGW        | NHS GMS;Expert Review Green;Emory Genetics Laboratory;Literature                                                                                                 |
| POMK        | NHS GMS;Expert Review Green;Expert list                                                                                                                          |
| SLC35A2     | NHS GMS;Expert Review Green;UKGTN;Radboud University Medical Center, Nijmegen;Other                                                                              |
| SLC37A4     | NHS GMS;Expert Review Green;Literature                                                                                                                           |
| STT3A       | NHS GMS;Expert Review Green;UKGTN;Other                                                                                                                          |
| TMEM199     | NHS GMS;Expert Review Green;Radboud University Medical Center, Nijmegen;Other                                                                                    |

**Comment by rykahsay** [comment]
Check now

**Comment by JingyueWu** [comment]
@rykahsay Checked. All the genes Jeet mentioned in the above table are present now.

**Comment by JingyueWu** [comment]
@rykahsay @jeet-vora Checked. Here are the genes that are still missing:

ATP6AP1
B3GALNT2
B3GALT6
GMPPA
ISPD
PGAP3
PGM3
PIGN
PIGT
POMGNT2
TMEM5
TUSC3
XYLT1
XYLT2

**Comment by rykahsay** [comment]
Check now, the above genes are present now. The following are missing because gene names do not map to canonical ac
```
ISPD
TMEM5
```

**Comment by jeet-vora** [comment]
Done. Will be contacting Genomics England for new gene names.
