### ISSUE TITLE
Setup training meeting with Anh and other preople interested

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#402]
We need to have a online training session with Anh (and other people interested) to provide training for drawing glycans in GRITS toolbox. We also should record this part of the meeting in case the need for training arises again.

After the training @Mindyporterfield, @apnguyen98, @ReneRanzinger, @jeet-vora ?, @kmartinez834 ? will sit down and plan the curation workflow and how information/files will flow between Mindy and Anh.

We identified 6/2/23 1pm as good time for the meeting. @jeet-vora will send an invite.

**Comment by Mindyporterfield** [comment]
Mindy- read paper, id data to be curated (which figures etc), draw an example structure paying attention to reducing end type (free or reduced) and modifications (permethylation). Write a ticket for Anh and link example structure.

Anh-Draw assigned structures using GRITS, export as gws file and put in the corresponding folder in sharepoint, comment in github to let me know its done.

Mindy-check structures, give any needed feedback

Mindy -proceed with the rest of the curation workflow


-convert structures (Sena) and get glytoucan ids
-verify structures match glytoucan structure
-Fill in remaining info for species, etc  [https://docs.google.com/document/d/1QPWU29l6pzo8bKIQ6epEidPDDxyp-5JQk9drhS-zJOg/edit#heading=h.urs6nll5b27n](url)
-deposit in sharepoint and comment on ticket

**Comment by jeet-vora** [comment]
GRITS Training Meeting recording - https://gwu0.sharepoint.com/:f:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Mindy%27s%20work?csf=1&web=1&e=8eQ6Sl
