### ISSUE TITLE
Issue with protein_glygen_pubchem_xref_mapping.csv dataset

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#403]
The protein_glygen_pubchem_xref_mapping.csv dataset should only contain entries that have UniProtKB accession mapped to GlyTouCan ac and PubChem CID. Please filter out entries that do not have UniProtKB accession like the below.

Can you let me know from which dataset the below annotation comes from? The annotation mentions 1 site for C,N,O linked glycans but no site or protein information. I checked PMID 34191522, it mentions no site or proteins and has only 58 glycans.

| uniprotkb_ac | refseq_ac | glycosylation_annotation                                                                                                                                         | start_pos | end_pos  | start_aa | end_aa   | saccharide | pubchem_cid | glycosylation_type | pmid |
| ------------ | --------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------- | --------- | -------- | -------- | -------- | ---------- | ----------- | ------------------ | ---- |
|              |           | 1 site, 1 C-linked glycan (1 site), 108 Free glycans (1 site), 581 N-linked glycans (1 site), 1 N-linked/o-linked glycan (1 site), 462 O-linked glycans (1 site) | G34219XL  | 71298079 | O-linked | 34191522 |
|              |           | 1 site, 1 C-linked glycan (1 site), 108 Free glycans (1 site), 581 N-linked glycans (1 site), 1 N-linked/o-linked glycan (1 site), 462 O-linked glycans (1 site) | G43761FR  | 71298187 | O-linked | 34191522 |
|              |           | 1 site, 1 C-linked glycan (1 site), 108 Free glycans (1 site), 581 N-linked glycans (1 site), 1 N-linked/o-linked glycan (1 site), 462 O-linked glycans (1 site) | G47649ZW  | 91857347 | O-linked | 34191522 |
|              |           | 1 site, 1 C-linked glycan (1 site), 108 Free glycans (1 site), 581 N-linked glycans (1 site), 1 N-linked/o-linked glycan (1 site), 462 O-linked glycans (1 site) | G10604KJ  | 71298227 | O-linked | 34191522 |
|              |           | 1 site, 1 C-linked glycan (1 site), 108 Free glycans (1 site), 581 N-linked glycans (1 site), 1 N-linked/o-linked glycan (1 site), 462 O-linked glycans (1 site) | G80147HT  | 71298220 | O-linked | 34191522 |
|              |           | 1 site, 1 C-linked glycan (1 site), 108 Free glycans (1 site), 581 N-linked glycans (1 site), 1 N-linked/o-linked glycan (1 site), 462 O-linked glycans (1 site) | G28911EK  | 71298372 | O-linked | 34191522 |
|              |           | 1 site, 1 C-linked glycan (1 site), 108 Free glycans (1 site), 581 N-linked glycans (1 site), 1 N-linked/o-linked glycan (1 site), 462 O-linked glycans (1 site) | G66489LJ  | 70698371 | O-linked | 34191522 |
|              |           | 1 site, 1 C-linked glycan (1 site), 108 Free glycans (1 site), 581 N-linked glycans (1 site), 1 N-linked/o-linked glycan (1 site), 462 O-linked glycans (1 site) | G33696UB  | 71298116 | O-linked | 34191522 |
|              |           | 1 site, 1 C-linked glycan (1 site), 108 Free glycans (1 site), 581 N-linked glycans (1 site), 1 N-linked/o-linked glycan (1 site), 462 O-linked glycans (1 site) | G63498YL  | 71298376 | O-linked | 34191522 |
|              |           | 1 site, 1 C-linked glycan (1 site), 108 Free glycans (1 site), 581 N-linked glycans (1 site), 1 N-linked/o-linked glycan (1 site), 462 O-linked glycans (1 site) | Asn       | Asn      | G62880PC | 91845854 | N-linked   | 34207636    |
|              |           | 1 site, 1 C-linked glycan (1 site), 108 Free glycans (1 site), 581 N-linked glycans (1 site), 1 N-linked/o-linked glycan (1 site), 462 O-linked glycans (1 site) | Asn       | Asn      | G71013KY | 91844946 | N-linked   | 34207636    |
|              |           | 1 site, 1 C-linked glycan (1 site), 108 Free glycans (1 site), 581 N-linked glycans (1 site), 1 N-linked/o-linked

**Comment by rykahsay** [comment]
check now

**Comment by JingyueWu** [comment]
Checked, looks good and no issues were found.
