### ISSUE TITLE
Errors in Glycam sequences

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#404]
There are a few problems with some of the GLYCAM sequences:
```
G38361UZ	DGalpNAca1-2DNeup5Aca2-OH
G69723YI	DGalpb1-2DNeup5Acb2-OH
```
There cant be a OH group of position 2 of NeuAc if there is another residue linked to position 2. There might be more than just the two but they were in the test set.

**Comment by edwardsnj** [comment]
@ReneRanzinger What is the correct GLYCAM sequence for the GlycoCT of this sequence?

**Comment by ReneRanzinger** [comment]
Ah ... hmm ... [see](https://github.com/GLYCAM-Web/website/issues/135)

**Comment by ReneRanzinger** [comment]
@edwardsnj Please see https://github.com/GLYCAM-Web/website/issues/135#issuecomment-1576577802. We should remove these GLYCAM sequences. At least for now. What do you think?

**Comment by edwardsnj** [comment]
See: https://github.com/GLYCAM-Web/website/issues/135#issuecomment-1581327137
