### ISSUE TITLE
Polysialic acid (O-glycan) contact

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#405]
In May 2022 @mtiemeyer0919  and I had a contact with Virginia M. Shapiro from Mayo clinic about polysialic acid on O-glycans. She wanted to know what structures we have and we send a search result. Her last email was:
```
Hi!  Thanks so much for doing this!  I looked at the results, and it appears that all the hits belong to 
Glycophorin-A, -B, and -C.  Hopefully in the future we'll be able to add our information to the database.
Safe travels!
Best wishes,
Ginny
```
We should see if there is data we can acquire. If its "just" published data we could add it to Mindys curation workflow. 

@jeet-vora Please evaluate if we want to move onto this. @mtiemeyer0919 and I can help with the contact if you want us to.

**Comment by jeet-vora** [comment]
@mtiemeyer0919 To explore more and contact Virginia.
