### ISSUE TITLE
Lost rows in human_proteoform_phosphorylation_sites_iptmnet.csv

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#407]
There are 28,221 fewer rows in the unreviewed/human_proteoform_phosphorylation_sites_iptmnet.csv dataset.  I believe this is due to the new human proteome download.

```
"id_count_diff","id_count_new","id_count_old","row_count_diff","row_count_new","row_count_old","field_count_diff","field_count_new","field_count_old","dataset_file_name","status_flags"
"75","9292","9217","-28221","377101","405322","0","9","9","human_proteoform_phosphorylation_sites_iptmnet.csv","old_dataset; rowcount_change; idcount_change"
```

@rykahsay --> The log file human_proteoform_phosphorylation_sites_iptmnet.log doesn't have any line breaks.  Can you fix this so I can parse the file?

FYI  @jeet-vora @JingyueWu

**Comment by rykahsay** [comment]
Sorry -- please check now

<img width="1418" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/5323d718-0130-4b0c-81e0-aa74e79e68e1">

**Comment by kmartinez834** [comment]
Ok, think I figured it out.  Due to the change implemented in #283, none of the rows contain "xref_id" or "src_xref_id" with "-1" (Ex. P13611-1)

@rykahsay --> Could we do something like this, where we preserve the source ID but ensure that the url will point to the link without "-1"?

**unreviewed/human_proteoform_phosphorylation_sites_iptmnet.csv**
```
"uniprotkb_canonical_ac","phosphorylation_site_uniprotkb","amino_acid","kinase_uniprotkb_canonical_ac","kinase_gene_name","xref_key","xref_id","src_xref_key","src_xref_id"
"P13611-1","2099","Ser","","","protein_xref_hprd","P13611","protein_xref_iptmnet","P13611-1"
"P13611-1","2099","Ser","","","protein_xref_iptmnet","P13611","protein_xref_iptmnet","P13611-1"
"P13611-1","2099","Ser","","","protein_xref_pubmed","18491316","protein_xref_iptmnet","P13611-1"
```

**Comment by rykahsay** [comment]
please check now

**Comment by kmartinez834** [comment]
Looks good
