### ISSUE TITLE
remove size limit for structure search.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#408]
Remove maximum number of monosaccharides supported limit (10) for structure search.

https://api.tst.glygen.org/job/status/?query={"jobid":23}

**Comment by ReneRanzinger** [comment]
This is only for structure search NOT substructure search.

**Comment by sujeetvkulkarni** [comment]
removed reference to sub structure search.

**Comment by rykahsay** [comment]
Where is that limit set? Is it coming to you on some init API -- if yes, which one?

**Comment by ReneRanzinger** [comment]
@edwardsnj Can you look at the JSON from the API call (initial post). Is the structure search (not sub...) invoked correctly. If so why is there a "Motif too big"? Could this be an update issue that the container is not the latest version?

**Comment by edwardsnj** [comment]
I can't see it (on glygen) - it is all hidden from me... but it seems to be working?

- n

**Comment by sujeetvkulkarni** [comment]
> Where is that limit set? Is it coming to you on some init API -- if yes, which one?

We dont send any size limit. I guess it's the default size limit set for the structure search. Nathan has made changes to remove the size limit. Do we use his containers or have our own containers for structure search? Maybe we need to update containers if we host them at our end.

**Comment by edwardsnj** [comment]
The JSON response from the docker container hasn't changed. However, it seems like it is only returning "strict" alignments, rather than all alignments. See: https://glygen.org/glycan-list/a636f27531ae19fff3be362dda8c3cba (this should have many hits), but only one strict alignment.

**Comment by ReneRanzinger** [comment]
@rykahsay 
* Update the container on tst
* Make sure there is no filtering of results from Nathans list.

**Comment by rykahsay** [comment]
You get 49 results now
<img width="1391" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/64b0258e-550b-4616-b4a5-302264382028">

**Comment by edwardsnj** [comment]
Great, thats the right number
