### ISSUE TITLE
M1 GRITS version

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#410]
Both, @JingyueWu and @jeet-vora, have Mac notbooks with the "new" M1 processors. We need to see that we can get GRITS working on these.

1. @senaarpinar Do we have a solution for this?

2. @JingyueWu Can you please download the Mac version to your M1-Mac and try to run it? What kind of error do you get when trying?

3. @senaarpinar Jingyue offered, that we could try remote build a M1 GRITS version on her computer using Zoom or WebEx. Do you want to try this depending on the answers to 1 and 2?

**Comment by senaarpinar** [comment]
@ReneRanzinger I don't have a solution for running on M1 processors as of now. I remember trying to generate a product using multi-platform build and failing. But I didn't have a chance to work directly on one of these new Macs.

**Comment by JingyueWu** [comment]
@ReneRanzinger Anh from our group said all problems have been resolved and there is no blocker or issue anymore. Do we still want to proceed?

**Comment by senaarpinar** [comment]
We still need to generate a version that works in the new architecture. I would like to test first with the latest version of Eclipse and multi-platform build to see if it works. If not, we can try remote connect option.

**Comment by jeet-vora** [comment]
@JingyueWu When you get time do work on this.

**Comment by ReneRanzinger** [comment]
I am closing this. We ordered a new M2 Mac and will build the version on our side. Might still take a bit but we will not need @JingyueWu help.
