### ISSUE TITLE
Mac issue getting GlycanBuilder to run

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#411]
When trying to get GRITS running on @apnguyen98 (Anh) Intel Mac we run into a few issues.

<img width="599" alt="Screen Shot 2023-06-02 at 2 01 50 PM" src="https://github.com/glygener/glygen-issues/assets/2267640/67124bc6-39bd-437e-9755-c1b946468001">

These are the log files:
[log.zip](https://github.com/glygener/glygen-issues/files/11637961/log.zip)

1. (Known problem with work around) When starting GRITS the main menu is not responsive. (Workaround) Change to a different Window, click on this Window to give it focus, change back to GRITS, click and give focus to GRITS. Main menu is working.
2. When clicking on _Tools>GlycanBuilder>Open GlycanBuilder_ nothing happens. I think the first session the problem was that the workspace path had a whitespace. Before the second session we remove  the whitespace and reopened the workspace. But the Builder would still not open. I also noticed that the Project we created in the first session had an issue. When double clicking on it the project view would not open.

Anh will be working with Mindy on the paper curation over the summer. It would be good if we can get the builder working on her notebook. She will be available to Zoom/WebEx if we want to remote diagnose.

**Comment by senaarpinar** [comment]
generated a new version (java 17 version) and works fine on Mac Big Sur
