### ISSUE TITLE
Glycan Dictionary 

### ISSUE THREAD

**Issue by Mindyporterfield** [glygener/glygen-issues#413]
[file](https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Mindy%27s%20work/GSD%20Hierarchy/Glycan%20dictionary%20summary2.xlsx?d=we5ecbd85935f476a9f15ac40d6115647&csf=1&web=1&e=g5ztpW)

**Comment by ReneRanzinger** [comment]
Duplicated ticket of #334 .

Please add the link there and close this ticket. I will need some more information on the spreadsheet. Which sheet should I look at? For the rule based rows make sure that the rules describe the term exhaustive. For example 3 branches is sufficient to describe "Triantennary" but not for "Triantennary sialylated".
