### ISSUE TITLE
FIGURE 4. TheN-linked glycan profile of wild-typeDrosophila embryos.

### ISSUE THREAD

**Issue by Mindyporterfield** [glygener/glygen-issues#414]
This is part of #399 

Please start with [Fly-N-077 paper](https://gwu0.sharepoint.com/:f:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Paper%20Curation/PMID%C2%A017264077%20Fly-N?csf=1&web=1&e=EACW7c)

FIGURE 4. TheN-linked glycan profile of wild-typeDrosophila embryos.

Draw the 42 glycans, they are free end (not reduced) 

I added an [example gws file](https://gwu0.sharepoint.com/sites/GlyGenTeam-GRP/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=QdbofB&cid=e6c564f8%2Da8bf%2D4df3%2D85db%2D39483b53a8e6&FolderCTID=0x01200081407FA815A7124E846BD764353D93CC&id=%2Fsites%2FGlyGenTeam%2DGRP%2FShared%20Documents%2FPaper%20Curation%2FPMID%C2%A017264077%20Fly%2DN%2FGWS&viewid=6ffb8fed%2D81e7%2D4af7%2Dbfcd%2Da6f29c268132) 
to be used in Grits 

Save the gws file in the same folder with the name Fly-N-077structures

**Comment by Mindyporterfield** [comment]
it is this PMID 17264077

**Comment by Mindyporterfield** [comment]
moved this to ticket #399

**Comment by apnguyen98** [comment]
Posted .gws file on SharePoint: https://gwu0.sharepoint.com/sites/GlyGenTeam-GRP/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=EACW7c&cid=aba533af%2Dff65%2D4b17%2D8c9a%2D5c21f48836db&FolderCTID=0x01200081407FA815A7124E846BD764353D93CC&id=%2Fsites%2FGlyGenTeam%2DGRP%2FShared%20Documents%2FPaper%20Curation%2FPMID%C2%A017264077%20Fly%2DN%2FGWS&viewid=6ffb8fed%2D81e7%2D4af7%2Dbfcd%2Da6f29c268132

**Comment by Mindyporterfield** [comment]
@apnguyen98 The structure with mass 1835 has a bracket that should not be there, please remove it and replace the file in sharepoint. Alert me once it has been done. Thank you it looks great!!

**Comment by apnguyen98** [comment]
@Mindyporterfield Reuploaded with the right structure. Please take a look.
