### ISSUE TITLE
Compression option not working properly for download apis.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#415]
Compression option is not working for detail_download, list_download, section_download

https://api.tst.glygen.org/data/detail_download?query=
{"id":"G17689DH","download_type":"glycan_detail","format":"json","compressed":true}

https://api.tst.glygen.org/data/section_download?query={"id":"G17689DH","download_type":"glycan_section","section":"motifs","format":"csv","compressed":true}

https://api.tst.glygen.org/data/list_download?query={"id":"d7a6549c87567e796d0d5c8905900c60","download_type":"glycan_list","format":"csv","compressed":true,"filters":[]}

**Comment by rykahsay** [comment]
Try now

**Comment by sujeetvkulkarni** [comment]
done.
