### ISSUE TITLE
Single Nucleotide Variation (SNV) download section (publication page) has missing example.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#416]
Single Nucleotide Variation (SNV) download section (publication page) has missing example.
https://github.com/glygener/glygen-backend-api/tree/2.1/tests/examples/data
section_download.publication.snv.json example is not there on Github.

**Comment by rykahsay** [comment]
I have added it now:
https://github.com/glygener/glygen-backend-api/blob/2.1/tests/examples/data/section_download.publication.snv.json

**Comment by sujeetvkulkarni** [comment]
6a8171e3831f361987fe34db66ea91be4686b257
