### ISSUE TITLE
Single Nucleotide Variation (SNV) download section (on site page) has two separate examples instead of one.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#417]
Single Nucleotide Variation (SNV) download section (on site page) has two separate examples instead of one.
snv_disease_associated_mutations (section_download.site.snv.1.json)
snv_non_disease_associated_mutations (section_download.site.snv.2.json)

https://github.com/glygener/glygen-backend-api/tree/2.1/tests/examples/data

GlyGen portal has one common table for both categories,
https://tst.glygen.org/Siteview/P07911-1/396#Single-Nucleotide-Variation

**Comment by rykahsay** [comment]
I have added a third example that downloads all snv

https://github.com/glygener/glygen-backend-api/blob/2.1/tests/examples/data/section_download.protein.snv.3.json

**Comment by sujeetvkulkarni** [comment]
59c13e9b0c2865a2c7cc67ab8ff112091d8a9d19
