### ISSUE TITLE
data.glygen.org searches

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#418]
Evaluate search bugs/improvements needed

**Comment by kmartinez834** [comment]
Issues with data.tst.glygen.org:

- Page crashing - https://data.tst.glygen.org/GLY_000003
- Filter producing OR instead of AND results.  For example, I would expect to see datasets with Homo sapiens AND Protein labels, but I'm getting all Homo sapiens and all Protein datasets:
![image](https://github.com/glygener/glygen-issues/assets/90285371/e482dccf-ad50-4bb6-a903-709b11ada551)
- Sample data not appearing for most datasets (ex. GLY_000004, GLY_000021, GLY_000034)
- Datasets not searchable by BCO ID (not working for any GLY_*)
- sarscov2_protein_signalp_annotation.csv not searchable by file name

**Comment by rykahsay** [comment]
Done items

- Page crashing - https://data.tst.glygen.org/GLY_000003
- Filter producing OR instead of AND results ...
- Sample data not appearing for most datasets (ex. GLY_000004, GLY_000021, GLY_000034)
- Datasets not searchable by BCO ID (not working for any GLY_*)
- sarscov2_protein_signalp_annotation.csv not searchable by file name

**Comment by kmartinez834** [comment]
- Odd filter behavior (both tst and beta)...

1. Clicked on Homo sapiens filter
![image](https://github.com/glygener/glygen-issues/assets/90285371/5d2d15a7-ed4d-47f3-8845-d81bf3d27cac)
2. Then glycan filter
 --> Summary shows filters homo sapiens, glycan but Rattus box is checked and glycan is not checked
![image](https://github.com/glygener/glygen-issues/assets/90285371/aa2b31bc-7fab-4939-9e60-cb4574c9a95e)

- Another example of issue above...
1. Clicked on Mus musculus filter
  --> Summary is correct but now Homo sapiens box is checked
![image](https://github.com/glygener/glygen-issues/assets/90285371/e30f2173-5a18-484f-92fb-b23f0fcbf16a)

- Columns with wrapped text are cut off
Ex. https://data.tst.glygen.org/GLY_000021
![image](https://github.com/glygener/glygen-issues/assets/90285371/9e9158cb-de64-4ce1-a885-6c4b8b479746)

**Comment by rykahsay** [comment]
Check on beta now

**Comment by kmartinez834** [comment]
@rykahsay filters are working as expected, but wrapped text is still cut off on dataset page (see last bullet point above)

**Comment by rykahsay** [comment]
check now on beta

**Comment by kmartinez834** [comment]
👍
