### ISSUE TITLE
Quick search tooltip

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#419]
https://gwu0.sharepoint.com/sites/GlyGenTeam-GRP/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=AQwhLf&cid=750b99d4%2D5b18%2D4d03%2D844b%2Dd9403a8cc8ac&RootFolder=%2Fsites%2FGlyGenTeam%2DGRP%2FShared%20Documents%2FGlyGen%20Tasks&FolderCTID=0x01200081407FA815A7124E846BD764353D93CC

**Comment by sujeetvkulkarni** [comment]
#166

**Comment by sujeetvkulkarni** [comment]
4b83ff09d43354ae323a5da4cb1833464dd2e44e

**Comment by sujeetvkulkarni** [comment]
f28ab4f7f46b494c68ae30f7c94901cf3c26354d

**Comment by sujeetvkulkarni** [comment]
Done. Please verify.

**Comment by jeet-vora** [comment]
Hi @sujeetvkulkarni

Whatever you have added looks good. However, the current text is generic. I need to understand what you want to achieve here and how specific you want the text to be.

**Comment by sujeetvkulkarni** [comment]
It's for user to understand what the input field is and what to input. Please close the ticket if you think the text explains it.
