### ISSUE TITLE
Generate list of dataset contributor types

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#42]
For Mindy curation/GSA update

**Comment by kmartinez834** [comment]
@jeet-vora

**Comment by jeet-vora** [comment]
@kmartinez834 This is the spreadsheet for authoring provenance that can be used to generate data/dataset authors.

https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/provenance.xlsx?d=w12364e6ccce246378d0db0a4a8f0490d&csf=1&web=1&e=Mava8Z

**Comment by kmartinez834** [comment]
I wrote a program to extract all contribution types from current bco jsons.  Found two additional fields:

provenance property | BCOs found in
-- | --
providedBy |  GLY_000142, GLY_000527, GLY_000580
createdWith |  GLY_000409

Also note - there are no BCOs in either v-2.0.2/jsondb/bcodb or generated/datasets/jsondb/bcodb/ folders that use "retrievedFrom"

@jeet-vora Can you add descriptions for providedBy and createdWith?

**Comment by kmartinez834** [comment]
Per discussion in 2/15 developer call,  "providedBy" and "createdWith" were used in error above. Although we are not currently using "retrievedFrom", we will keep this term as an option.

- [x] @kmartinez834 - update the BCOs above on biocomputeobject.org with the correct provenance property 
- [x] @jeet-vora - add description to "createdWith" for future datasets which are created with software

**Comment by kmartinez834** [comment]
@Mindyporterfield @ReneRanzinger 

The list of provenance properties and descriptions for GlyGen datasets can be found here:  [provenance.xlsx](https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/provenance.xlsx?d=w12364e6ccce246378d0db0a4a8f0490d&csf=1&web=1&e=57KoBt)

It is currently located in the GlyGen Sharepoint documents under the Backend folder.

**Comment by Mindyporterfield** [comment]
We need to talk about "created with" in the wednesday meeting

**Comment by kmartinez834** [comment]
Per 8/30 meeting, @jeet-vora to provide example of "curated by" for GRITS toolbox

**Comment by jeet-vora** [comment]
@Mindyporterfield 
If you are curating the paper use `curatedBy`, if you are using a software/tool/code to add information to the dataset use `createdWith`. For final dataset to be integrated GW will use `createdBy `. For final dataset to be integrated GW will use `createdBy`. If the initial dataset is shared to you by a researcher use `contributedBy` or `authoredBy` whichever is applicable as per [this](https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B12364E6C-CCE2-4637-8D0D-B0A4A8F0490D%7D&file=provenance.xlsx&action=default&mobileredirect=true). There is no need to add corresponding author or other author name list if curating the paper by yourself. 

<ins>**Example**</ins>
**curatedBy**:Mindy Porterfiel ([mindy@something.de](mailto:mindy@something.de),CCRC)|curatedBy:Name (email,institution).

**createdWith**:GRITS Toolbox (http://www.grits-toolbox.org/)|createdWith:Software/Tool/Code Name (URL or Sourecode URL)

**contributedBy**:Bob Haltiwanger (bh@ccrc.edu,CCRC)|contributedBy:Name (email,institution)

**authoredBy**: Daniel Williamson (daniel.williamson25@uga.edu,CCRC)|authoredBy:Name (email,instituition)

**createdBy**:Jeet Vora (jeetvora@gwu.edu,GW)|createdBy:Name (email,instituition)
