### ISSUE TITLE
Dead Sandbox link on tst

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#420]
https://tst.glygen.org/glycan/G17689DH
![image](https://github.com/glygener/glygen-issues/assets/90285371/c80efe7d-17b0-49e1-9cde-364efdb62666)

Sandbox button points to https://tst.glygen.org/static/media/sand-box.5ea93e99.svg (empty page)

Should be the same as Sandbox xref link --> https://sandbox.glyomics.org/explore.html?G17689DH

**Comment by ReneRanzinger** [comment]
@kmartinez834 can you shift+reload the page? It works for me.

**Comment by kmartinez834** [comment]
So it isn't a broken link, but I don't think this is the intended page?  Had to zoom in 500% but its just a static picture of the SandBox logo:
![image](https://github.com/glygener/glygen-issues/assets/90285371/52df0c4b-8017-4516-b25e-1f200977111b)

**Comment by ReneRanzinger** [comment]
@kmartinez834 You are looking at white lines on a white background.

**Comment by kmartinez834** [comment]
@ReneRanzinger Can you show me what you're seeing?

**Comment by sujeetvkulkarni** [comment]
@kmartinez834 when you click on the SandBox button does it take you to the sandbox link?
It's a button and not a link.
I believe what are you saying is when you hover over the button it shows https://tst.glygen.org/static/media/sand-box.5ea93e99.svg  link. This is an image link (SanBox logo link) used on SandBox button. But on clicking the button (SanBox) it should route you to the SanBox link properly.

**Comment by kmartinez834** [comment]
@sujeetvkulkarni yesterday when I clicked on the link, it took me to the image link.  This appears to be fixed, as its now taking me to the Sandbox explore page.
