### ISSUE TITLE
All glycan motif images missing on tst

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#421]
https://tst.glygen.org/list-of-motifs/
![image](https://github.com/glygener/glygen-issues/assets/90285371/9f75c661-0663-4668-bc3e-ca300d60ba5a)

**Comment by rykahsay** [comment]
Try now -- you may need to clear your cache
<img width="1262" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/8ac46cce-804e-4b6f-82dc-d8b4c9696605">

**Comment by kmartinez834** [comment]
👍
