### ISSUE TITLE
Download buttons not working (TST - Glycan Subsumption & Expression)

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#423]
Subsumption and Expression **DOWNLOAD** buttons not working:
https://tst.glygen.org/glycan/G17689DH
https://tst.glygen.org/glycan/G56749GV
![image](https://github.com/glygener/glygen-issues/assets/90285371/89ed4c0b-5275-4d6b-893b-0ab1c46fe9d6)
![image](https://github.com/glygener/glygen-issues/assets/90285371/9bb3e1c4-9a87-4d12-a408-8def08f40013)

**Comment by kmartinez834** [comment]
Protein sections with tabs are not working either.  You have to change the format/tab, then change again to get the default selection to work.

**Comment by sujeetvkulkarni** [comment]
124bb3089dbb27fb8224999a35f19df709921cc1
