### ISSUE TITLE
BCSDB xref info changed

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#426]
I updated the URL for "glycan_xref_bcsdb" in misc/xref_info.csv. Please update API so that records will point to correct URL.

Ex. https://api.tst.glygen.org/glycan/detail/G00016MO
``` json
{
"id": "6273",
"url": "http://csdb.glycoscience.ru/database/core/search_id.php?mode=record&id_list=6273", 
"database": "BCSDB"
```

**Comment by rykahsay** [comment]
What changed? It looks the same to me.

```
$ grep glycan_xref_bcsdb generated/misc/xref_info.csv 
glycan_xref_bcsdb,BCSDB,http://csdb.glycoscience.ru/database/core/search_id.php?mode=record&id_list=%s
```

In release 2.1.1
```
{
            "id": "6273",
            "url": "http://csdb.glycoscience.ru/bacterial/core/search_id.php?mode=record&id_list=6273",
            "database": "BCSDB"
}
```

In release 2.0.3
```
{
            "id": "6273",
            "url": "http://csdb.glycoscience.ru/bacterial/core/search_id.php?mode=record&id_list=6273",
            "database": "BCSDB"
}
```

**Comment by kmartinez834** [comment]
URL changed from csdb.glycoscience.ru/**_bacterial_**/ to csdb.glycoscience.ru/**_database_**/

--> I just updated xref_info.csv today so that's why 2.0.3 and 2.1.1 are still the same

**Comment by rykahsay** [comment]
It is updated in 2.1 now, please check /data/shared/glygen/releases/data/v-2.1.1/jsondb/glycandb/G00016MO.json

**Comment by kmartinez834** [comment]
Confirmed.

Keeping ticket open to verify change is implemented in API and portal
