### ISSUE TITLE
Misssing GLY_000001 from data.glygen.org

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#427]
Robel 
GLY_000001 (Human Proteome Masterlist) cannot be searched and nor it appears in the list.
Can you check?

Nothing was changed for the dataset or BCO

<img width="1212" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/02eb4f93-c94c-428b-912b-b3ba33070bf9">

**Comment by rykahsay** [comment]
Fixed it

**Comment by jeet-vora** [comment]
Checked no issues
