### ISSUE TITLE
Proteins with same mass button not working

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#428]
Nothing happens when I click on the magnifying glass symbol:
https://tst.glygen.org/protein/P14210-1
![image](https://github.com/glygener/glygen-issues/assets/90285371/5dbf5d75-61c9-4160-8f85-90a0f883affb)

**Comment by sujeetvkulkarni** [comment]
d690e26f7ee3b99e08558a1b30db5d0d7604f5df
