### ISSUE TITLE
Contact Sriram regarding the BioRender update

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#429]
@kmartinez834 will contact Sriram and explain the situation with BioRender. We want to ask him if he can (as head of SNFG) contact them and archive an update.

**Comment by kmartinez834** [comment]
There are two icon categories with glycans in BioRender:
Glycans: https://www.biorender.com/sub-categories/glycans
Carbohydrates: https://www.biorender.com/sub-categories/carbohydrates

The "glycans" use SNFG symbols, but "carbohydrates" are generic structures that do not.

@rajamazumder @mtiemeyer0919 @ReneRanzinger --> in your opinion, should we ask Sriram to address both or just the "glycan" icons?

**Comment by ReneRanzinger** [comment]
**For glycans**: the shapes are OK but the color code is off. 
**For carbohydrates**: not all of them will benefit from SNFG but there a many that could be "corrected". It may still conflict with there interest since for most of the carbohydrate shapes you can choose the coloring in a second step. If you use the SNFG colors they may fill it takes away flexibility. Then again for glycans they don't seem to have these options.

**Comment by kmartinez834** [comment]
Proposed changes in Google slides: https://docs.google.com/presentation/d/1BTeTB2v6hhqFvdqhrEoHWOJkrLr4BuvfcBB-1cVk2CU/edit?usp=sharing

**Comment by ReneRanzinger** [comment]
@kmartinez834 We reviewed this on 9/13. Its good to go. There may be some pushback for the proposals on the later slides since this are very generic "structures". We also talked about sending a copy to Rebecka.
