### ISSUE TITLE
BLAST and GSD on Homepage

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#43]
- [x] BLAST card can be added to the home page. 
![image](https://user-images.githubusercontent.com/25825266/217935838-3a6097ef-56ed-4096-a980-0ed9367dcdc1.png)

- [ ] Glycan Structure Dictionary Wiki page can be added in the explore option of the menu and maybe as a card on the homepage. 
![image](https://user-images.githubusercontent.com/25825266/217936054-28e814a2-2ca8-4c17-8947-553633e7ff1d.png)

Let me know what you think?

**Comment by ReneRanzinger** [comment]
I am fine with making both cards on the homepage but that we need logos and text for the cards and need to agree on a order. 

I dont think GSD belongs under Explore it should go to tools like MotifWiki. GSD is a dead end that does not allow you to go anywhere.

**Comment by jeet-vora** [comment]
@ReneRanzinger I can provide you with the text and image for BLAST.

I am fine with GSD under tools. Explore has more clicks than tools so preferred it under explore. 

Let me know if you want to add the above. Do we have a limit to add the cards as I believe Clustal Tool, Glycan drawer etc will also be added in near future.

**Comment by ReneRanzinger** [comment]
@jeet-vora How about: Move Sand Box up before Data. Add Blast and GSD between Sand Box and Data?

**Comment by sujeetvkulkarni** [comment]
@jeet-vora Can you please provide image and text for the blast card.

**Comment by jeet-vora** [comment]
@sujeetvkulkarni @ReneRanzinger - Let me know if this works
GSD
<img width="497" alt="GSD_Logo" src="https://user-images.githubusercontent.com/25825266/222200583-5deb8dbb-9ed9-47ee-ac5d-28179da1571a.png">

The Glycan Structure Dictionary provides a standardized list of widely recognized glycan terms for curating and mapping glycan structures described in publications.

BLAST

<img width="455" alt="BLAST_logo" src="https://user-images.githubusercontent.com/25825266/222202224-f7491116-375c-4787-8c9c-cdd38cfe56b8.png">


The GlyGen Protein BLAST (Basic Local Alignment Search Tool) allows to find regions of local similarity between protein sequences. The GlyGen Protein BLAST can be used to search similar sequences for glycosylated/phosphorylated peptide and protein sequences in the GlyGen protein sequences database.

**Comment by ReneRanzinger** [comment]
This is how it will look like:

![screen-fake](https://user-images.githubusercontent.com/2267640/222214700-5df04917-20f7-4335-b257-78156b20456c.png)

My suggestions for GSD:
- remove the white text
- Text below is too long we need 50% of it

My suggestions for Blast:
- remove the query text and bar and just keep the scale
- remove the text in the middle
- increase size of red lines by 50% and space by 50-100% ==> less red lines
- have more "Gaps" in between and at the end
- First text variant could be OK if we remove the parentheses and just call it BLAST.

**Comment by jeet-vora** [comment]
*** Updated *** Let me know
**GSD**

<img width="279" alt="image" src="https://user-images.githubusercontent.com/25825266/222233736-9f5067bc-934a-48b3-a1e0-fb95b5bbbaba.png">


Main title: Glycan Structure Dictionary (GSD)
The Glycan Structure Dictionary provides a standardized list of glycan structure terms commonly described in publications.
The GSD provides a standardized list of glycan structure terms commonly described in publications.

**BLAST**

![image](https://user-images.githubusercontent.com/25825266/222235554-8328aee7-9782-43a2-bff6-baa4a9d54337.png)

Main title: Protein BLAST

The GlyGen Protein BLAST allows to find regions of local similarity between protein sequences. 

The GlyGen Protein BLAST allows to find regions of local similarity between protein sequences. The GlyGen Protein BLAST can be used to search similar sequences for glycosylated/phosphorylated peptide and protein sequences in the GlyGen protein sequences database.

**Comment by ReneRanzinger** [comment]
OK, do you have vector graphics for it or how did you make them?

**Comment by jeet-vora** [comment]
SVG files. I hope they are useable.

![GSD_logo](https://user-images.githubusercontent.com/25825266/222511827-ce80581c-008b-4e77-93fe-c41c0961c689.svg)
![BLAST_logo](https://user-images.githubusercontent.com/25825266/222511829-b2d8096b-5b9f-4adf-bd1f-b9d0dfdebd4e.svg)

**Comment by sujeetvkulkarni** [comment]
efc637d4b969216f74dcf714824b80216efde487

**Comment by sujeetvkulkarni** [comment]
0b73f5fec18a6c5f4f5359d01a5c5d8c71ca910b
