### ISSUE TITLE
Provide examples for the Glyconnect issues

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#430]
There are a lot of Glyconnet entries for the same site and same paper that has just composition and partially defined structures. Is there any need to check.

**Comment by rajamazumder** [comment]
AT https://www.glygen.org/protein/P00533-1#Glycosylation Pubmed 10731668 in position 56
- Composition: G23863VK, G84452RH 
- Fully defined G78059CC, G83461WR
Can someone please check and confirm from the paper this is what we want? Or should we not display composition if they are subsumed by another more defined structure from the same paper? Whatever the decision is can we please have a FAQ with this EGFR example to explain?

**Comment by kmartinez834** [comment]
**Adding to the 1/17 agenda:**

Each GlyConnect entry has "composition" and "structure" fields. Some, but not all, compositions include a GlyTouCan accession; it depends on whether GlyConnect has a GlyTouCan xref for that composition.  The "structure" is the accession found in the publication, but both accessions are linked to the publication according to the GlyConnect data model.
```
"composition": {
        "id": 205,
        "format_numeric": "5,4,1,0,0,0,0,0,0,0,0,0,0,0",
        "format_glyconnect": "Hex:5 HexNAc:4 dHex:1",
        "format_byonic": "HexNAc(4)Hex(5)dHex(1)",
        "format_condensed": "H5N4F1",
        "mass": 1787.6503,
        "mass_monoisotopic": 1786.6501,
        "reviewed": true,
        "glytoucan_id": "G23863VK"
    },
    "structure": {
        "id": 1860,
        "glytoucan_id": "G78059CC",
        "reviewed": true,
        "is_undefined": false,
        "has_image": true,
        "glycan_type": "N-Linked",
        "glycan_core": "Complex"
    },
    "site": {
        "glyco_site": "Asn-56",
        "location": 56
    },
    "references": [
        {
            "id": 2545,
            "title": "Characterisation of the N-oligosaccharides attached to the atypical Asn-X-Cys sequence of recombinant human epidermal growth factor receptor",
            "authors": "Sato, Kim, Abe, Saito, Yokoyama, Kohda",
            "pmid": 10731668
        }
```

From the paper [10731668](https://github.com/glygener/glygen-issues/files/13955061/127-1-65.pdf):
![image](https://github.com/glygener/glygen-issues/assets/90285371/9d519829-413e-43b8-a433-73415a8f5ba6)
