### ISSUE TITLE
Remove UniCarbKB and GlycosciencesDE urls from APIs

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#431]
Exclude http://www.unicarbkb.org/ and http://www.glycosciences.de/ URLs from glycan and protein APIs.

This would apply to entries with the following xref ids:
glycan_xref_unicarbkb_comp
protein_xref_unicarbkb
glycan_xref_glycosciencesde

Ex. https://api.tst.glygen.org/glycan/detail/G00009BX
Currently:
``` json
"crossref": [{
		"id": "14295",
		"url": "http://www.glycosciences.de/database/start.php?action=explore_linucsid&linucsid=14295",
		"database": "Glycosciences.de"
	},
```
Change to:
``` json
"crossref": [{
		"id": "14295",
		"database": "Glycosciences.de"
	},
```

**Comment by rykahsay** [comment]
done

**Comment by kmartinez834** [comment]
@sujeetvkulkarni can you make text black for xref's without urls?

Ex. https://tst.glygen.org/glycan/G00009BX#Cross-References
![image](https://github.com/glygener/glygen-issues/assets/90285371/9d178b3e-913b-41db-a9ce-679e0194bf1c)

**Comment by sujeetvkulkarni** [comment]
bf19600b9ded04ad1325e2d9f28fcccee6bc6c19

**Comment by sujeetvkulkarni** [comment]
Done. Please verify.

**Comment by kmartinez834** [comment]
Looks good
