### ISSUE TITLE
Add banner to production when beta is released

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#432]
Add a banner to production when 2.1 is deployed to beta.
Time: From first beta deployment till June 30th
Headline: GlyGen 2.1 is available on beta
Text: The next GlyGen version is now available on our beta server for testing. The version includes new features like download of individual tables on details pages, a new Sandbox version and download of filtered search results.
URL: https://beta.glygen.org/

@jeet-vora, @rajamazumder and @mtiemeyer0919 please have a look at the text and let us know if you want to make changes.

**Comment by jeet-vora** [comment]
Looks good. You can also add the word now "is _now_ available" in the headline and text.

**Comment by sujeetvkulkarni** [comment]
Done. Please verify.
