### ISSUE TITLE
Share list for seminar speaker for review

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#433]
@jeet-vora will share the list of seminar speakers. @mtiemeyer0919 and @rajamazumder will review. After this we will start contacting speakers for the next 6 months.

**Comment by jeet-vora** [comment]
Hi Mike and Raja,

I have drafted a list of speakers for GlyGen webinars collected from different venues for your review. We have, at the moment, paused the webinars and decided to resume back in August. Please see the list, let me know your thoughts, and add comments if needed. I allotted speakers for the webinars till Feb for us to invite them way before the webinar date. 

The speaker for August is Manfred Wuhrer from Leiden University Medical Center (LUMC) suggested by Mike, let me know if we can reach out to him for the webinar. Once you are good with the list, I can plan to invite the other speakers.

In the document, I have also added other potential speakers/resources to invite in Other and also the speakers who were invited to give a talk at previous webinars/meetings.

https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7BCC9D968A-8C5E-44D5-B034-5C7D7D58F204%7D&file=Webinar%20Speakers.docx&action=default&mobileredirect=true

image.png
