### ISSUE TITLE
Issues on api.tst.glygen.org

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#435]
For /data/detail_download/ 

<img width="1399" alt="Screen Shot 2023-06-08 at 4 47 51 PM" src="https://github.com/glygener/glygen-issues/assets/61590108/0fb51c91-b0da-4581-944e-b901c4ebabaf">

For /data/list_download/

<img width="1397" alt="Screen Shot 2023-06-08 at 4 50 11 PM" src="https://github.com/glygener/glygen-issues/assets/61590108/8db1afcd-82dc-441e-8e66-c6adcbde2f23">

For /data/section_download/

<img width="1394" alt="Screen Shot 2023-06-08 at 4 51 24 PM" src="https://github.com/glygener/glygen-issues/assets/61590108/b9591f84-a359-4a7e-80d7-f380c2613ccc">

In addition, for /typehead/global_typehead/ 

<img width="1389" alt="Screen Shot 2023-06-08 at 5 28 32 PM" src="https://github.com/glygener/glygen-issues/assets/61590108/01dbb4ea-10d1-409f-9afd-ab99bd7e8959">

example.json is missing from https://github.com/glygener/glygen-backend-api/blob/master/specs/typeahead/global_typeahead/response.schema.json

**Comment by JingyueWu** [comment]
@kmartinez834 @jeet-vora FYI

**Comment by rykahsay** [comment]
@jeet-vora @JingyueWu -- use example request jsons from branch 2.1 not from master

<img width="1095" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/c282d8cf-474a-4245-a3a2-24c3d57f2294">

**Comment by jeet-vora** [comment]
@JingyueWu Check the issue again, use example request jsons from branch 2.1 not from master, and close the ticket.

**Comment by JingyueWu** [comment]
Done. This issue has been resolved.
