### ISSUE TITLE
Google analytics G4 tracking for SPARQL subdomain

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#436]
We need to add the G4 analytics code to the SPARQL subdomain as well. See #214. The old code are no longer supported after July 1st.

That might be one of the reasons for drop in activity that @jeet-vora is exploring.

**Comment by rykahsay** [comment]
Please check now

<img width="899" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/73dafe1b-9d18-48f5-b171-282ac6cbb8dc">

**Comment by sujeetvkulkarni** [comment]
verified. creating a new issue for page title - https://github.com/glygener/glygen-issues/issues/459
