### ISSUE TITLE
Google analytics G4 tracking for wiki subdomain

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#437]
We need to add the G4 analytics code to the SPARQL subdomain as well. See #214. The old code are no longer supported after July 1st.

I am not sure which mechanism we used in the past. Maybe this [extension](https://www.mediawiki.org/wiki/Extension:Google_Analytics_Integration)?

That might be one of the reasons for drop in activity that @jeet-vora is exploring.

**Comment by rykahsay** [comment]
Rts ticket  [rtshelp #80961]  has been created for Dacian

**Comment by rykahsay** [comment]
Done
