### ISSUE TITLE
Change Sandbox URL on Homepage

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#438]
Change link on Homepage from https://glygen.ccrc.uga.edu/sandbox/ to https://sandbox.glyomics.org/

![image](https://github.com/glygener/glygen-issues/assets/90285371/2aefc783-f0b3-4c84-9e10-0ea66ac8c123)

**Comment by kmartinez834** [comment]
Also in Tools menu:
![image](https://github.com/glygener/glygen-issues/assets/90285371/ac4474eb-cf1d-4f78-b59e-c9a847b18560)

**Comment by sujeetvkulkarni** [comment]
35af00f38dc6b646dad08a2194bdba5da6cf8048
