### ISSUE TITLE
Unexpected result when searching for Hex(5)HexNAc(4)dHex(1)

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#439]
Search term Hex(5)HexNAc(4)dHex(1) results include a single GalNAc, G57321FI, in results. I expected to get results with the entire string/name.

@ReneRanzinger Is this something we should try to fix?

https://tst.glygen.org/glycan-list/af97e7e35381fbb9114c9c158cc78b69

![image](https://github.com/glygener/glygen-issues/assets/90285371/9095fcf7-2416-4a46-8ad8-59e244670528)

**Comment by ReneRanzinger** [comment]
@kmartinez834 How did you trigger this search? Global search, simple search, composition search, direct search? Its certainly not what I would expect to see. Out of the top hit from these 45k !!! results only the second actually matches the search term. If its simple search or global search, maybe @rykahsay treats the parenthesis as separator (like whitespace) and it becomes a search for something with "Hex OR HexNAc OR dHex".

**Comment by kmartinez834** [comment]
Glycan Simple Search using example composition string:
![image](https://github.com/glygener/glygen-issues/assets/90285371/76623707-58cc-4e32-92f1-08fbfdec45c9)

**Comment by ReneRanzinger** [comment]
Ok, I think @rykahsay needs to look into the search logic that is triggered. My expectation would be that this is treated as one string and it finds all structures that match the string. It may be possible that if finds structures that have this string as substring (e.g.; NeuAc(2)**Hex(5)HexNAc(4)dHex(1)**) but that's a different issue.

**Comment by rykahsay** [comment]
The simple search implements MongoDB text search in which query is broken into words and those words are searched an indexed text for the entire collection content. In this case, it seems the sequence is broken to words because of the ")" characters. The simple way to address this is to load "NeuAc(2)Hex(5)HexNAc(4)dHex(1)"   instead of NeuAc(2)Hex(5)HexNAc(4)dHex(1) and the search should work as expected.

**Comment by ReneRanzinger** [comment]
@rykahsay There are several issues here:
* The user needs to know that he has to quote the input
* As predicted above this will find also structures that have this string as substring (e.g. structures with additional residues)
* Biggest problem: The user needs to use exactly the right order when using the quotes. One mistake in the order and it will fail.

Not for 2.1: How complex would be the following change to the glycan search logic. Separate each input string by white space. Check each of the generated sub-strings if it consisted of a series of pattern `<char> { <char> } "(" <number> ")"`. If this is the case, parse them as composition and see if the character sequences match our composition components. Yes, treat as composition string. No, treat as normal string.

**Comment by rykahsay** [comment]
Please check now

**Comment by kmartinez834** [comment]
Closing this ticket as resolved
- Now works without quotes and in any order (Ex. Hex(5)HexNAc(4)dHex(1) and dHex(1)Hex(5)HexNAc(4) both give 994 results)
- Results still include structures where the search term is a substring (Ex. Hex(5)HexNAc(4)dHex(1)NeuAc(2))
