### ISSUE TITLE
www in https://www.glygen.org/

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#44]
Is the www protocol in the portal URL https://www.glygen.org/ necessary?
It is only for the portal
https://data.glygen.org/

**Comment by ReneRanzinger** [comment]
www is not the protocol. HTTP/HTTPS is the protocol. www is the subdomain (similar as data or api are subdomains). 

[Some read on this topic](https://stackoverflow.com/questions/1109356/www-or-not-www-what-to-choose-as-primary-site-name)

I have no preference. We are not using www consistently anyway. Yes, the main page gets forced redirect to the www version but all sub-pages work both way:
https://www.glygen.org/glycan-search/
https://glygen.org/glycan-search/  

Dacian would have to make a redirect for the entire www domain if you wanted to get rid of it.

**Comment by jeet-vora** [comment]
Yeah you are right it is a subdomain and not a protocol. I mixed the two.

It is upto you, Robel and Dacian to decide. I prefer consistency.

Best,

*Jeet Vora*
Senior Research Associate
Scientific Coordinator for GlyGen.org
Project Manager for Glycosciences-NIH CFDE
The George Washington University
Ross Hall, Room 559
2300 Eye Street N.W.
Washington, DC 20052
***@***.***
*Pronouns - He/him/his*

**Comment by jeet-vora** [comment]
Closing the issue for now as no consensus is met.
