### ISSUE TITLE
Figures for PMID 23516363 Flu-363

### ISSUE THREAD

**Issue by Mindyporterfield** [glygener/glygen-issues#441]
This is part of ticket #396 

Draw structures for [Supplemental tables](https://gwu0.sharepoint.com/sites/GlyGenTeam-GRP/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=EACW7c&cid=4d9731ae%2Dd7ff%2D4faf%2D8d3d%2D71cb79fb4372&FolderCTID=0x01200081407FA815A7124E846BD764353D93CC&id=%2Fsites%2FGlyGenTeam%2DGRP%2FShared%20Documents%2FPaper%20Curation%2FPMID%C2%A023516363%2FPaper&viewid=6ffb8fed%2D81e7%2D4af7%2Dbfcd%2Da6f29c268132)  

Start with N-glycans, then I will teach you )-glycans

- [x] S1 N-glycan adult lung 
- [ ] 
- [x] S3 N-glycan adult bronchus 
- [ ] 
- [x] Table S5 Human adult lung O gly 
- [ ] 
- [x] TableS6 Human adult bronc O gly 
- [ ] 
- [x] TableS7 Human paed lung N gly 
- [ ] 
- [x] TableS8 Human paed bronc N gly 
- [ ] 
- [x] TableS9 Human paed lung O gly 
- [ ] 
- [x] TableS10Human paed bronc O gly

**Comment by apnguyen98** [comment]
@Mindyporterfield This is done and all the .gws files for each table have been uploaded on https://gwu0.sharepoint.com/sites/GlyGenTeam-GRP/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=EACW7c&cid=4d9731ae%2Dd7ff%2D4faf%2D8d3d%2D71cb79fb4372&FolderCTID=0x01200081407FA815A7124E846BD764353D93CC&id=%2Fsites%2FGlyGenTeam%2DGRP%2FShared%20Documents%2FPaper%20Curation%2FPMID%C2%A023516363%2FGWS&viewid=6ffb8fed%2D81e7%2D4af7%2Dbfcd%2Da6f29c268132

**Comment by Mindyporterfield** [comment]
@apnguyen98 looks good 
I saw 1 trivial thing but should be corrected, you named 2 of the GWS files as Fly instead of Flu , please change them. I would do it but I was concerned I might break something :)

**Comment by apnguyen98** [comment]
@Mindyporterfield I just renamed it. Must be a typo somehow haha, thank you for catching it!
