### ISSUE TITLE
Glycan G26481RZ not valid

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#442]
This glycan has a methyl group at the anomer of the reducing end monosaccharide. At least according to the GlycoCT definition that is not a valid glycan. A glycan has to start with a monosaccharide and no substituent can be attached to the anomer, only other monosaccharides.

Its the same like Asn or Ser. These non-monosaccharide should be "released" from the glycan. 

In addition its not clear to me why this glycan is in GlyGen at all. The ancestors have a species annotation but this structure not. In fact is has no information at all.

**Comment by edwardsnj** [comment]
This structure is in GlyGen because its monosaccharide composition is consistent with a Human annotated glycan (e.g. G03368AU)
