### ISSUE TITLE
G89097YO not valid

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#443]
The problem is the 3 linked Mannose. Its aldose with a 1:5 ring but the linkage from the parent goes to C2 instead of the anomer. I am not sure how this passed validation both molecular framework and wurcs validation should have yelled.

Similar to #442 its not clear why this structure is in GlyGen. It does not have descendants with annotations and itself does not have annotation either.

**Comment by edwardsnj** [comment]
This one is in GlyGen because its monosaccharide composition is consistent with a Human annotated glycan (e.g. G16119YF)
