### ISSUE TITLE
G62400VU not valid

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#444]
Pretty much the same as #443 just that the Sialic acid should be 2 linked not 1 linked. Shall we just swap the "2" and "1" between the two?

Same issue with validation that should have triggered an error.

Also similar to #442 and #443 no own annotations and no descendants with data.

Different than the others the image is wrong. It does not even show the sialic acid.

**Comment by edwardsnj** [comment]
What is my task here? Correctness checking of glycans is not part of my current pipeline. We can develop this infrastructure if you like, but I/we have no process for explicitly listing structures to exclude or for computationally checking sequences for correctness (or relevance). Ditto for #442 #443

**Comment by ReneRanzinger** [comment]
@edwardsnj

1. If we can agree that these structures are invalid we need to report them to GlyTouCan and they need to clean that up. After some time that should remove the structures from your system as well.

2. I think Yamada told me that there is an API to invoke their validation. That could be an easy way to get a sequence checked with little implementation effort. If we decide that is necessary.

3. The structures has no annotation (species, proteins, papers etc.). It has no descendants that could have annotations. Why is this structure in GlyGen?

**Comment by edwardsnj** [comment]
This one is in GlyGen because it has the same monosaccharide composition as structures (e.g. G08371CD) annotated as Human.

**Comment by ReneRanzinger** [comment]
@edwardsnj We may have to rethink this strategy. Besides the invalid part, I am not sure what the value of these structures is in GlyGen.
