### ISSUE TITLE
Not supported GLYCAM monosaccharides

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#445]
I run the GLYCAM evaluation on the 6659 GlyGen GLYCAM sequences I have. There are 138 structures that fail due to the following monosaccharides (furanoses):

- DAllf
- DAltf
- DFucf
- DGalf
- DGalfNAc
- DGlcf
- DGlcfNAc
- DGulf
- DIdof
- DManf
- DManfNAc
- DRhaf
- DTalf
- LAllf
- LAltf
- LFucf
- LGalf
- LGlcf
- LGulf
- LIdof
- LManf
- LRhaf
- LTalf

And these:
- DIdop
- LIdop

The GlyTouCan IDs with their GLYCAM sequences and error message are here:

[NonGLYCAMms.xlsx](https://github.com/glygener/glygen-issues/files/11710690/NonGLYCAMms.xlsx)

**Comment by edwardsnj** [comment]
Scripts making GLYCAM sequences now also check to see that GLYCAM will accept them - while slow, this guarantees that all supplied GLYCAM sequences will (ultimately) be good. Note that if they improve their tool to accommodate additional structures, the "check" will be out of date and all sequences will have to be rechecked.
