### ISSUE TITLE
GLYCAM does not like GlcA with 6 linked substituents

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#446]
Methyl:
* G32430MQ
* G73698CD

Sulfate:
* G47519VR
* G77291EZ

Off-topic: for the later 3 the question arises why they are in GlyGen. We may have to rethink the envelop. 

Other GlcA, even with substituents are fine, e.g.;  [G84168AG](https://www.glygen.org/glycan/G84168AG)

**Comment by edwardsnj** [comment]
Scripts making GLYCAM sequences now also check to see that GLYCAM will accept them - while slow, this guarantees that all supplied GLYCAM sequences will (ultimately) be good. Note that if they improve their tool to accommodate additional structures, the "check" will be out of date and all sequences will have to be rechecked.
