### ISSUE TITLE
Testing APIs on swagger testing

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#45]
On swagger: https://api.tst.glygen.org

For automated testing --- go to README.md for glygener/glygen-backend-api repo

Please report here ONLY failing APIs

**Comment by JingyueWu** [comment]
@rykahsay These are the API's that failed 
(Error code: 500; Error: INTERNAL SERVER ERROR)
/glycan/list/
/protein/list/
/idmapping/list/
/supersearch/list/
/data/download/
/typehead/categorized_typehead/
/typehead/global_typehead/
/typehead/typehead/
/auth/contact/
/auth/login/
/auth/register/
/video/detail/
/job/delete/

(Error code: 401; Error: UNAUTHORIZED)
/video/addnew/
/video/delete/
/event/addnew/
/video/delete/
/event/update/

**Comment by JingyueWu** [comment]
Duplicate ticket, issue to be transferred to #147
