### ISSUE TITLE
data.glygen file updates and QC

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#450]
Familiarize with https://data.glygen.org/uploads, refer to QC and upload tutorial (https://data.glygen.org/static/upload_help). This is needed to upload Rene's dummy files. It is important to ensure that the portal takes the files.

**Comment by rykahsay** [comment]
QC type "glycosylation site" is not working

<img width="936" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/a0540f0d-38f2-4085-908a-6e849446a304">

**Comment by JingyueWu** [comment]
@jeet-vora Who should I report/assign this to? Can we close this ticket?
