### ISSUE TITLE
Script to automatically test external URLs

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#451]
We need a script that automatically tests all external URLs (Links for cross references and sources) that we generate. It needs to dynamically find all evidence links and cross references and for each "base URL" test a few arbitrary examples. If they are dead links or HTTP codes >= 400 an error reports needs to generated and we need to investigate.

This script should be run automatically as part of our testing.

**Comment by rykahsay** [comment]
@kmartinez834 -- I have created a simple script (/software/glygen/check-external-urls.py) that parses our misc/xref_info.csv file to create example urls. For this to work, I have added one more column in misc/xref_info.csv  that will contain example xref IDs. This column needs to be edited to place correct example xref IDs.



```
xref_info_file = "/data/projects/glygen/generated/misc/xref_info.csv"

    with open(xref_info_file, "r") as FR:
        lcount = 0
        for line in FR:
            lcount += 1
            row = line.strip().split(",")
            if lcount == 1 or line[0] == "#" or line.find("%s") == -1 or line.find("xxx") != -1:
                continue
            url_template = row[-2]
            xref_id_list = row[-1].split("|")
            for xref_id in xref_id_list:
                url = ""
                if xref_id.find(";") != -1:
                    url = url_template % (xref_id.split(";")[0],xref_id.split(";")[1])
                else:
                    url = url_template % (xref_id)
                res = requests.get(url)
                print (res.status_code, url)
```

**Comment by kmartinez834** [comment]
FYI @jeet-vora @JingyueWu

**Comment by kmartinez834** [comment]
@rykahsay 
- Added example accessions to xref_info.csv
- Added a few lines of code to check-external-urls.py to handle timeout and request errors.

There is still a lot of work needed to correct other example accessions (for resources that don't use UniProt or GlyTouCan ac's), but was able to run the program through all urls.
