### ISSUE TITLE
Downloaded CSV fields and data does not match with section table

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#452]
https://tst.glygen.org/protein/P00533-1

<ins> **Glycosylation: Reported sites with Glycan (CSV)**

- **Add**

Glycan Image URLs in the CSV

- **Issue**

- Source information missing. 
The below info for Asn128 comes from UniCarbKB however the Source Xref DB only mentions PubMed. Also, there are two PMIDs associated with the entry 10988252,  10731668, however only one is in the CSV. PMID 10988252 is missing. This issue is seen in all the downloaded CSVs

- <ins> **Current**

| GlyTouCan Accession | Type     | Start Position | End Position | Start Amino Acid | End Amino Acid | Comment                                                                                                                                                | Source Xref DB | Source Xref ID | Source Xref URL                                |
| ------------------- | -------- | -------------- | ------------ | ---------------- | -------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------ | -------------- | -------------- | ---------------------------------------------- |
| G83461WR            | N-linked | 128            | 128          | Asn              | Asn            | GlycoSuiteDB  curation notes. Reported structure ... | PubMed         | 10731668       | https://glygen.org/publication/PubMed/10731668 |

<ins> **Change to**
| GlyTouCan Accession | Type     | Start Position | End Position | Start Amino Acid | End Amino Acid | Comment                                                   | Source Xref DB | Source Xref ID | Source Xref URL                                                                                  |
| ------------------- | -------- | -------------- | ------------ | ---------------- | -------------- | --------------------------------------------------------- | -------------- | -------------- | ------------------------------------------------------------------------------------------------ |
| G83461WR            | N-linked | 128            | 128          | Asn              | Asn            | GlycoSuiteDB  curation notes. Reported structure can be … | PubMed         | 10731668       | [https://glygen.org/publication/PubMed/10731668](https://glygen.org/publication/PubMed/10731668) |
| G83461WR            | N-linked | 128            | 128          | Asn              | Asn            | GlycoSuiteDB  curation notes. Reported structure can be … | PubMed         | 10988252       | [https://glygen.org/publication/PubMed/10988252](https://glygen.org/publication/PubMed/10988252) |
| G83461WR            | N-linked | 128            | 128          | Asn              | Asn            | GlycoSuiteDB  curation notes. Reported structure can be … | UniCarbKB      | P00533         |                                                                                                  |

<ins> ****Phosphorylation****

Phosphorylation csv

- <ins> **Add**

Kinase Protein and Kinase Gene fields in the CSV
![image](https://github.com/glygener/glygen-issues/assets/25825266/c9413ea5-c343-4144-98fe-8329db23e740)

- <ins> **Issue**

Source info missing, only one PMID is present
Infile
|Start Position|End Position|Residue|Comment|Source Xref DB|Source Xref ID|Source Xref URL                               |
|--------------|------------|-------|-------|--------------|--------------|----------------------------------------------|
|768           |768         |Ser    |       |PubMed        |10347170      |https://glygen.org/publication/PubMed/10347170|

- ****On** Portal**

<img width="757" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/9fabde52-b554-4848-a3f7-3e2f4c774cc6">

<ins>  **SNV**

Disease Associated Mutations and Non-disease associated Mutations CSVs

- <ins> **Add** 

Genomic Locus, Sequence and MAF fields to the CSV
<img width="769" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/f4a7ec01-ee39-4b88-afe2-259ed035536b">

- <ins> **Issue**

For pos 114 there is only 1 row with disease as cancer mutations. However there should be three rows for three cancers
**On portal**
<img width="767" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/e4f4eeb4-6705-4013-9e01-274d6baf9943">

- <ins> **Current** 

|Start Position|End Pos|Disease                  |Source Xref DB|Source Xref ID|Source Xref URL                                             |
|--------------|-------|-------------------------|--------------|--------------|------------------------------------------------------------|
|114           |114    |breast cancer (DOID:1612)|BioMuta       |P00533        |https://hive.biochemistry.gwu.edu/biomuta/proteinview/P00533|

- <ins> **Change to** 

| Start Position | End Pos | Disease                    | Source Xref DB | Source Xref ID | Source Xref URL                                              |
| -------------- | ------- | -------------------------- | -------------- | -------------- | ------------------------------------------------------------ |
| 114            | 114     | breast cancer (DOID:1612)  | BioMuta        | P00533         | https://hive.biochemistry.gwu.edu/biomuta/proteinview/P00533 |
| 114            | 114     | skin cancer (DOID:4159)    | BioMuta        | P00533         | https://hive.biochemistry.gwu.edu/biomuta/proteinview/P00533 |
| 114            | 114     | ovarian cancer (DOID:2394) | BioMuta        | P00533         | https://hive.biochemistry.gwu.edu/biomuta/proteinview/P00533 |

@JingyueWu Review the issue and understand it.

**Comment by rykahsay** [comment]
Check now --> if there are remaining issues, please make me one ticket per issue (I cannot follow up many issues put together in one ticket)

```
"GlyTouCan Accession","Type","Start Position","End Position","Start Amino Acid","End Amino Acid","Comment","Source Xref DB","Source Xref ID","Source Xref URL","Glycan Image Url"

"G83461WR","N-linked","128","128","Asn","Asn","GlycoSuiteDB  curation notes. Reported structure can be attached to the following: N-56, N-128, N-175, N-352, N-361, N-413, N-444, N-528, N-568, N-603","UniCarbKB","P00533","","","https://api.glygen.org/glycan/image/G83461WR"

"G83461WR","N-linked","128","128","Asn","Asn","GlycoSuiteDB  curation notes. Reported structure can be attached to the following: N-56, N-128, N-175, N-352, N-361, N-413, N-444, N-528, N-568, N-603","PubMed","10988252","https://glygen.org/publication/PubMed/10988252","","https://api.glygen.org/glycan/image/G83461WR"

"G83461WR","N-linked","128","128","Asn","Asn","GlycoSuiteDB  curation notes. Reported structure can be attached to the following: N-56, N-128, N-175, N-352, N-361, N-413, N-444, N-528, N-568, N-603","PubMed","10731668","https://glygen.org/publication/PubMed/10731668","","https://api.glygen.org/glycan/image/G83461WR"
```

**Comment by jeet-vora** [comment]
Glycosylation issue is solved.
New tickets for Phosphorylation and SNV created

- #457 
- #458
