### ISSUE TITLE
Featured video not appearing on beta

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#453]
![image](https://github.com/glygener/glygen-issues/assets/90285371/f9850183-97c4-4bf7-9f38-a75087782542)

**Comment by rykahsay** [comment]
@sujeetvkulkarni --> I have used the /video/addnew API to add video on beta but the frontend is not showing it saying "youtube refused connection"

<img width="1241" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/add39496-abe4-4b31-9e7c-4c220d37bed3">

**Comment by kmartinez834** [comment]
There is content now, but it's showing the ads before the video...
![image](https://github.com/glygener/glygen-issues/assets/90285371/4a7a23e9-20f0-495a-87d6-799907f9196a)

**Comment by sujeetvkulkarni** [comment]
Done. @rykahsay @kmartinez834 use https://youtube.com/embed/W13gi7nVCWc?rel=0 this url format for setting the video url. Please verify.

**Comment by kmartinez834** [comment]
👍
