### ISSUE TITLE
beta testing

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#454]
Finish COB Wednesday.

**Comment by JingyueWu** [comment]
The following beta API's gave me 500 error messages: 

/data/detail_download/
/data/list_download/
/data/section_download/
/typehead/global_typehead/ --> this one doesn’t have request.example.json on GitHub therefore the 500 error message still can’t get resolved, unlike the other 2 /typehead

The download is working on the frontend, we will need to look into it more

@jeet-vora @kmartinez834 FYI

**Comment by rykahsay** [comment]
When reporting API error, you need to give the actual request you used

**Comment by jeet-vora** [comment]
@JingyueWu Check if the error persists and provide Robel the API request. Once done close the ticket.
