### ISSUE TITLE
3D view not working on mobile device

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#455]
Both beta and production have same issue...Working as expected on computer browser though
https://beta.glygen.org/glycan/G17689DH
![IMG_1642](https://github.com/glygener/glygen-issues/assets/90285371/3bd27ef8-1004-445e-be6b-338565f7ef32)

**Comment by sujeetvkulkarni** [comment]
Attaching 3D view from iphone 14 pro max. Glycan id : G17689DH
@kmartinez834  what is the operating system of the mobile phone?
![IMG_1298](https://github.com/glygener/glygen-issues/assets/13891482/3f1e2e37-5554-490a-80a2-9b5405de5aa5)

**Comment by kmartinez834** [comment]
@sujeetvkulkarni iPhone X iOS V16.1.1

**Comment by sujeetvkulkarni** [comment]
@kmartinez834 I tried on chrome and safari browsers and 3D view was working. Did you check on both of them too?

**Comment by kmartinez834** [comment]
@sujeetvkulkarni I don't have chrome on my phone, but isn't working on safari.  Maybe just because its a older model?

**Comment by sujeetvkulkarni** [comment]
@kmartinez834 need to check up to what model 3D view is supported on Android and iPhone.

**Comment by sujeetvkulkarni** [comment]
iPhone 8 (2017) - safari browser working - Rene's phone.
ipad pro 11 2nd gen (2017) - safari browser working - Rene's ipad.

Will check on some android devices.

**Comment by sujeetvkulkarni** [comment]
![image](https://github.com/glygener/glygen-issues/assets/13891482/ff6b8e56-0188-4f82-861e-186a2a026ff8)

Samsung Galaxy A72 Android 13 - Chrome Browser working.
@ReneRanzinger , @kmartinez834 
I think we can close this issue.

**Comment by sujeetvkulkarni** [comment]
@kmartinez834 we can not reproduce this issue.
