### ISSUE TITLE
Phosphorylation csv Download Issue

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#457]
<p dir="auto"><ins> <strong>Phosphorylation</strong></ins></p>
<p dir="auto">Phosphorylation csv</p>
<ul dir="auto">
<li><ins> <strong>Add</strong></ins></li>
</ul>
<p dir="auto">Kinase Protein and Kinase Gene fields in the CSV<br>
<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/25825266/246143816-c9413ea5-c343-4144-98fe-8329db23e740.png"><img src="https://user-images.githubusercontent.com/25825266/246143816-c9413ea5-c343-4144-98fe-8329db23e740.png" alt="image" style="max-width: 100%;"></a></p>
<ul dir="auto">

@JingyueWu

**Comment by rykahsay** [comment]
Check now
```
"Kinase Protein","Kinase Gene","Start Position","End Position","Residue","Comment","Source Xref DB","Source Xref ID","Source Xref URL"
"P68400-1","CSNK2A1","692","692","Ser","","PubMed","19824718","https://glygen.org/publication/PubMed/19824718"
"P68400-1","CSNK2A1","692","692","Ser","","PubMed","9525959","https://glygen.org/publication/PubMed/9525959"

```

**Comment by jeet-vora** [comment]
done
