### ISSUE TITLE
SNV csv download issue

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#458]
<ins>  **SNV**

Disease Associated Mutations and Non-disease associated Mutations CSVs

- <ins> **Add** 

Genomic Locus, Sequence and MAF fields to the CSV
<img width="769" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/f4a7ec01-ee39-4b88-afe2-259ed035536b">

- <ins> **Issue**

For pos 114 there is only 1 row with disease as cancer mutations. However there should be three rows for three cancers
**On portal**
<img width="767" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/e4f4eeb4-6705-4013-9e01-274d6baf9943">

- <ins> **Current** 

|Start Position|End Pos|Disease                  |Source Xref DB|Source Xref ID|Source Xref URL                                             |
|--------------|-------|-------------------------|--------------|--------------|------------------------------------------------------------|
|114           |114    |breast cancer (DOID:1612)|BioMuta       |P00533        |https://hive.biochemistry.gwu.edu/biomuta/proteinview/P00533|

- <ins> **Change to** 

| Start Position | End Pos | Disease                    | Source Xref DB | Source Xref ID | Source Xref URL                                              |
| -------------- | ------- | -------------------------- | -------------- | -------------- | ------------------------------------------------------------ |
| 114            | 114     | breast cancer (DOID:1612)  | BioMuta        | P00533         | https://hive.biochemistry.gwu.edu/biomuta/proteinview/P00533 |
| 114            | 114     | skin cancer (DOID:4159)    | BioMuta        | P00533         | https://hive.biochemistry.gwu.edu/biomuta/proteinview/P00533 |
| 114            | 114     | ovarian cancer (DOID:2394) | BioMuta        | P00533         | https://hive.biochemistry.gwu.edu/biomuta/proteinview/P00533 |

@JingyueWu

**Comment by rykahsay** [comment]
```
"Start Position","End Pos","Sequence","Disease","MAF","Source Xref DB","Source Xref ID","Source Xref URL"
"114","114","E -> K","ovarian cancer (DOID:2394); skin cancer (DOID:4159); breast cancer (DOID:1612)","","BioMuta","P00533","https://hive.biochemistry.gwu.edu/biomuta/proteinview/P00533"
```

**Comment by jeet-vora** [comment]
Done
