### ISSUE TITLE
Jumbo glycan G49108TO has "non existent record" error 

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#460]
https://beta.glygen.org/glycan/G49108TO

![image](https://github.com/glygener/glygen-issues/assets/90285371/614e71c3-9257-4c2d-887e-33aea8526c13)

https://beta-api.glygen.org/glycan/detail/G49108TO
`{"error_list": [{"error_code": "non-existent-record"}], "reason": {"type": "added", "description": "introduced in data release 1.0.13"}}`

**Comment by rykahsay** [comment]
please check now

**Comment by kmartinez834** [comment]
Looks good
