### ISSUE TITLE
Lit mining

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#463]
@rykahsay --> please describe current problem with lit mining pipeline here

**Comment by rykahsay** [comment]
Problem: 
I run both the oger and litmining steps but the output files  (glygen_set_new_postprocessing*.tsv)  do not seem to have any results. Please see below for details on the shell scripts for these steps, logs and output files

## oger step
- shell script: https://data.glygen.org/ftp/udel/step_oger.sh
- logs: https://data.glygen.org/ftp/udel/log_oger.txt
- output files: https://data.glygen.org/ftp/udel/output_oger/

## litmining step
-  shell script: https://data.glygen.org/ftp/udel/step_litmining.sh
- logs: https://data.glygen.org/ftp/udel/log_litmining.txt
- output files: https://data.glygen.org/ftp/udel/output_litmining/

**Comment by ReneRanzinger** [comment]
@jeet-vora

**Comment by kmartinez834** [comment]
Add to agenda for next meeting w/ Vijay: #515

**Comment by kmartinez834** [comment]
From Shovan:
-----------------
Hello everyone,
Greetings. While running the Litmining software, please make sure you have carefully considered the following:
The website ([documentation](https://docs.google.com/document/d/1HD43GNAyRJ7gfXKUzI5kHYeUrm-qa6Cdr_CLc3JNLwc/edit?usp=sharing)) must be running before executing the bash files of the software ([documentation](https://docs.google.com/document/d/1NSuTlu69ToX0cO0muglCFN1RNnl_NY-ztWeHDo1feOI/edit?usp=sharing))

Website part: 
1. The MongoDB must be running before with the command: mongo
2. In step 1: There is a typo and the command should be similar to this: mongorestore -d glygen_set db_files/glygen_set/ (If you are downloading the same folder given in this [link](https://drive.google.com/drive/folders/1uz4O6ACwAvm4i-c3nyFDAWXx52WZhCA3?usp=drive_link))
3. In step 3: If you are using the localhost, check the web address. For example: When I run the software on our machine, the website address was: [127.0.0.1:4500/litmining](http://127.0.0.1:4500/litmining)
4. If you are able to see the website, the GlygenNew page should be empty and the website should not be turned off.

Glygen Litmining part:
1. Docker is installed and users are added to the docker group using the command:
docker run hello-world
newgrp docker
2. If any of the tools are running using the docker, those should be stopped and removed by using the command:
docker rm "docker_id" or similar to "docker rm -f edg_server"
3. In step 6: There is a typo and the command should be similar to this: cp "$(pwd)"/litmining/glygen_set_new_postprocessing.tsv "$(pwd)"/glygen_web

If other steps and these issues are carefully followed, then you would be able to see the results on the GlygenNew page after rerunning the website.

Let me know if you still face any issues.

---------------

@rykahsay is following through with the above instructions

**Comment by rykahsay** [comment]
@ReneRanzinger please create an account for me on your server

**Comment by ReneRanzinger** [comment]
@rykahsay see your email for credentials.

Its a virtual server with:
16 CPU vCore
60 GB RAM 
2.000 GB NVMe SSD
Connection up to 1.000 MBit/s
Traffic Unlimited

The contract for this server ends September 20th. Make sure to backup everything you might need by September 19th.
