### ISSUE TITLE
Add a paragraph to the meeting report paper

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#464]
@edwardsnj to add a paragraph about glycan motifs to the [meeting report paper](https://docs.google.com/document/d/1KSxS-cjobVqxqM0mVcrQQBm58HTLCvOWnNv7ieco1hE/edit). We discussed adding it to question one or two.

**Comment by edwardsnj** [comment]
I have added some prose about GNOme, Sandbox, and GlycoMotif.
