### ISSUE TITLE
Remove table from global search result

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#465]
To speed up the global search @rykahsay removed the section information (in which data field the match was found) from the global search result. Currently the page is "boken" since the table is empty (no rows). 

![global search](https://github.com/glygener/glygen-issues/assets/2267640/1420babb-7a8e-4f57-b6f6-b7407bb04aa8)

Remove the table from the page for now so that only the headline "xxx Glycan(s)" and "xxx Protein(s)/xxx Glycoprotein(s)" are left. "Database", "Glycan", "Protein" and "GlycoProtein" in the white part below the headline should be gone.

**Comment by sujeetvkulkarni** [comment]
8c97aa568087f253602fcaeb64942cd6e5009751

**Comment by sujeetvkulkarni** [comment]
done.
