### ISSUE TITLE
Produce glycan data for 2.2

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#471]
Based on #470 and the other resources produce the GlyGen glycan data for 2.2. That should also include a regeneration for the GLYCAM structures and the new Yeast (S. cerevisiae) data.

**Dependencies**:
* #470

**Blocker for**:
* #473 
* #477

**Comment by kmartinez834** [comment]
@edwardsnj we plan to update all of the downloads you'll need within the next 2 weeks

--> Are you able to provide your glycan data export by **August 7th**?
