### ISSUE TITLE
Add biomarker data to the GlyGen portal

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#476]
Implement the frontend changes to display biomarker data based on the API changes (see #475) and the [Mockups](https://docs.google.com/presentation/d/14vJ_o_fq6b0UR2DTgs0NhATl-C3uiPVN68wGLQnejq4/edit#slide=id.g25249709de5_0_26).

**Dependencies**:
* #135 
* #474 
* #475 
* #553
* #574 
* #575 
* #576
* #577 
* #578

**Comment by sujeetvkulkarni** [comment]
https://github.com/glygener/glygen-issues/issues/627

**Comment by sujeetvkulkarni** [comment]
8eafab4aa819117536d66c01fd5e8f57c8a90aa5
