### ISSUE TITLE
Generate list of 30k publiction for processing

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#479]
Generate the list of 30k papers that will be proccessed and integrated into GlyGen as part of 2.2. Document the utilized query.

**Dependencies**:
* #463 
* #255 
* #478 

**Blocker for**:
* #480 
* #481

**Comment by rykahsay** [comment]
@jeet-vora  --- I am waiting for the 30K PMIDs

**Comment by jeet-vora** [comment]
@rykahsay 

Here is the list of PMIDs and query in the spreadsheet. It contains PMIDs both from PubMed search and from GlyGen Human Glycosylation PMIDs, the total is 29,597. 277 overlap between the two.

Search query: ((((((((((glycosylation site) AND (glycan)) OR (glycosylation)) AND (glycan structure)) OR (glycan composition) ) OR (O-linked)) OR (N-linked)) NOT (Review)) NOT (Clinical Trial)) NOT (Book) AND (2014:2023[pdat])

The query at the moment is a bit stringent and can be relaxed to get thousands of PMIDs. More keywords can be added.

The PMIDs list in the txt file is here - /data/projects/glygen/downloads/lit_min/current/**pmids.txt**

and 

https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B7DA9749E-0257-44A6-BADE-EC27FFD5BED5%7D&file=pubmed_test_query_lit_mining.xlsx&action=default&mobileredirect=true
