### ISSUE TITLE
job/addnew API on tst server

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#48]
Can you tell me why substructure search is failing on tst?  

The swagger test is working.

<img width="1394" alt="image" src="https://user-images.githubusercontent.com/20584876/217352913-62b289c3-a27a-4159-a1ac-f88e54fc2037.png">

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/20584876/217353070-d4c7d2fb-e88a-47f6-93e3-1198a235114a.png">

**Comment by sujeetvkulkarni** [comment]
@rykahsay we can discuss this in our Wednesday meeting.

**Comment by sujeetvkulkarni** [comment]
You have removed "query" parameter from the POST methods, so all jobs like sub structure, structure and blast and other cases where POST is used is failing.
query={}
Substructure Search query={"jobtype":"structure_search","parameters":{"seq":"RES\\n1b:b-dglc-HEX-1:5\\n2s:n-acetyl\\n3b:b-dgal-HEX-1:5\\nLIN\\n1:1d(2 1)2n\\n2:1o(3 1)3d\","align":"substructure"}}"}

For image "GET" api not working,
https://api.tst.glygen.org/glycan/image/G17689DH/

**Comment by rykahsay** [comment]
@sujeetvkulkarni --> I have tried to fix these issues. Please check and close.

**Comment by sujeetvkulkarni** [comment]
efc637d4b969216f74dcf714824b80216efde487
