### ISSUE TITLE
Process 30k publictions

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#480]
After solving the current issue (#478) run the 30k papers provided by Jeet (#479) and extract the glycoproteomics data into a dataset. Perform evaluation of the dataset and dataset content as needed.

**Dependencies**:
* #463 
* #255 
* #478 
* #479 
* #770 

**Blocker for**:
* #481
* #771

**Comment by rykahsay** [comment]
@kmartinez834 
Output from the Udel pipeline is being placed under downloads/lit_min/current/ and is used to make *_proteoform_glycosylation_sites_literature_mining.csv datasets

```
$ ls -ltr downloads/lit_min/current/glycosylation_sites_*.csv
-rwxrwxr-x. 1 rykahsay glygen  39409 Jul 16  2021 glycosylation_sites_legacy.csv
-rw-r--r--. 1 rykahsay glygen  11119 Dec 17 16:39 glycosylation_sites_set_30k.csv
```

The *_proteoform_glycosylation_sites_literature_mining.csv datasets now have the field "additional_notes" that keeps which input files (from  downloads/lit_min/current/glycosylation_sites_*.csv) carries the site information.

```
"uniprotkb_canonical_ac","glycosylation_site_uniprotkb","amino_acid","saccharide","glycosylation_type","xref_key","xref_id","src_xref_key","src_xref_id","additional_notes","n_sequon","n_sequon_type","start_pos","end_pos","start_aa","end_aa","site_seq"
"Q11128-1","105","Asn","","N-linked","protein_xref_automatic_literature_mining","11511810","protein_xref_automatic_literature_mining","11511810","source files=glycosylation_sites_legacy","NIT","NXT","105","105","Asn","Asn","N"
"Q9NUM4-1","183","Asn","","N-linked","protein_xref_automatic_literature_mining","23742080","protein_xref_automatic_literature_mining","23742080","source files=glycosylation_sites_set_30k","NIT","NXT","183","183","Asn","Asn","N"
"Q9Y5Q5-1","1022","Asn","","N-linked","protein_xref_automatic_literature_mining","25451932","protein_xref_automatic_literature_mining","25451932","source files=glycosylation_sites_set_30k;glycosylation_sites_legacy","NVS","NXS","1022","1022","Asn","Asn","N"
```

Please check

**Comment by kmartinez834** [comment]
Looks good.  All *_proteoform_glycosylation_sites_literature_mining.csv files have expected number of new entries.
