### ISSUE TITLE
Check yeast data in the frontend

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#484]
After the integration of Yeast data into the backend (see #483) test if its working fine with the frontend. Places to test:
- statistic section on frontpage
- filter on protein and glycan list page
- Species section in glycan and protein page.

**Dependencies**:
* #477
* #483 
* #482

**Comment by sujeetvkulkarni** [comment]
check quick search also.

**Comment by sujeetvkulkarni** [comment]
done.
