### ISSUE TITLE
Setup VM for running backend at UGA

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#486]
After setup of the VM (#485) at UGA install the GlyGen backend at this server.

**Dependencies**:
* #485

**Comment by sujeetvkulkarni** [comment]
Got LAN access. Successfully connected to vpn and established a ssh connection with the server.

**Comment by ReneRanzinger** [comment]
* https://github.com/glygener/glygen-backend-api
* https://github.com/glygener/glygen-backend-datasetviewer

**Comment by sujeetvkulkarni** [comment]
backend API server installation document - https://github.com/glygener/glygen-issues/issues/798
datasetviewer server installation document - https://github.com/glygener/glygen-issues/issues/797
literature mining pipeline installation document - https://github.com/glygener/glygen-issues/issues/799
