### ISSUE TITLE
Prepare glycan related schema information

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#491]
Create CSV information for the glycan related schemas:
- glycan search
- glycan search init
- glycan search result

**Blocker for**:
* #492

**Comment by kmartinez834** [comment]
@rykahsay I just added the biomarker field to "glycan search init" schema and saved at `misc/glycan.search_init.response.schema.json`

:question: For "glycan search request" schema, I don't know what fields the query can accept other than the ones listed in [request.schema.json ](https://github.com/glygener/glygen-backend-api/blob/2.2/specs/glycan/search/request.schema.json). Can you send me this information?

--> "glycan search result" is a list id, no change needed
--> "glycan list response" no change needed

**Comment by rykahsay** [comment]
done
