### ISSUE TITLE
Add Google tacking for sandbox

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#495]
Preferable that should be linked up with the GlyGen google analytics account. Please talk with @sujeetvkulkarni about this.

**Comment by edwardsnj** [comment]
@sujeetvkulkarni Can you provide me some javascript boilerplate for getting the sandbox linked to the GlyGen google analytics account?

**Comment by sujeetvkulkarni** [comment]
@edwardsnj Please have a look at #214 
I have copied code below for pure java script solution (not react version) from #214. 

Install the Google tag manually
Below is the Google tag for this account. Copy and paste it in the code of every page of your website, immediately after the element. Don’t add more than one Google tag to each page.

```
<script async src="https://www.googletagmanager.com/gtag/js?id=G-47WSZ1WYRZ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag() {
    dataLayer.push(arguments);
  }
  gtag("js", new Date());
  gtag("config", "G-47WSZ1WYRZ");
</script>
```

**Comment by edwardsnj** [comment]
Done.
