### ISSUE TITLE
gene name is not coming in blast result api .

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#499]
Blast api result is not returning gene name in production.
https://api.glygen.org/job/results/?query={%22jobid%22:7}

**Comment by rykahsay** [comment]
Can you try now:

<img width="543" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/8547585f-7c92-4f85-bb81-060b4e224165">

**Comment by sujeetvkulkarni** [comment]
done.
