### ISSUE TITLE
pdb:yes support for glycam 3D structures in glycan details api

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#5]
Please add
"pdb":"yes" property in https://api.glygen.org//glycan/detail//

"tool_support": {
    "sandbox": "yes", 
    "gnome": "yes"

The glycam_3D structures are in sftp://glygen-vm-dev.biochemistry.gwu.edu/data/projects/glygen/downloads/glycam_3d/glycan/current/

eg. G00024MO.pdb

**Comment by rykahsay** [comment]
I have created a new glycan dataset called glycan_toolsupport.csv that will be used to populate the tool_support property. Please make a BCO for it.

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/20584876/217963655-c22e3ee5-2843-44e6-a838-682ee5e97590.png">

**Comment by kmartinez834** [comment]
Used script in #39 to create BCO GLY_000707
https://biocomputeobject.org/builder/https/biocomputeobject.org/GLY_000707/DRAFT

@jeet-vora can you review the `provenance_domain` and `usability_domain` and make sure it's correct for pdb tool support?

Close ticket if approved.  API updates are documented in ticket https://github.com/glygener/glygen-frontend/issues/167

**Comment by jeet-vora** [comment]
Reviewed the provenance_domain and usability_domain and made minor changes.
