### ISSUE TITLE
Use dump-request-stats.py from /software/glygen/

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#501]
@jeet-vora @JingyueWu @kmartinez834 

```
cd /software/glygen/
python3 dump-request-stats.py | grep "/protein/detail/"
```

<img width="1224" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/d2fc7189-cb59-44a4-9186-e34664b0ddc7">

**Comment by rykahsay** [comment]
Here I describe how the request log capture works ... sharing for documentation purposes.

This is done using the daily cronjob daemon which dumps from the MongoDB "c_request" collection to an archive file ( /data/shared/glygen/archive/requests-yyyy-mm-dd.json). These files are parsed by the dump-request-stats.py script to give daily numbers for all APIs.

I also would like to mention the request log functionality was off (accidentally) for the following days:

2023-07-03 (partially)
2023-07-04 (all day)
2023-07-05 (all day)

**Comment by ReneRanzinger** [comment]
@jeet-vora please put this into the sharepoint documentation.

**Comment by jeet-vora** [comment]
Done
