### ISSUE TITLE
GW Integrative Medicine podcast

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#505]
@rajamazumder Will come up with some content (SharePoint?) and look for some papers that can be used.

**Comment by rajamazumder** [comment]
Here are couple of papers that can be used. https://pubmed.ncbi.nlm.nih.gov/25548184/ (A red meat-derived glycan promotes inflammation and cancer progression. PNAS 2015)
https://medschool.ucsd.edu/som/cmm/research/labs/varki/Documents/A168.pdf Incorporation of a non-human glycan mediates human susceptibility to a bacterial toxin 2008

**Comment by mtiemeyer0919** [comment]
A few more for consideration:

alpha-gal syndrome, sensitization to red meat antigen induced by tick bite (not NeuGc related)
[https://pubmed.ncbi.nlm.nih.gov/35017216/]

use of dietary monosaccharide supplements for therapeutic relief in a subset of human CDGs
[https://pubmed.ncbi.nlm.nih.gov/29702557/]

a review of O-GlcNAcylation, Glc elevation, and various pathways impacted by altered Glc metabolism, perhaps relevant for Glucosamine supplementation
[https://pubmed.ncbi.nlm.nih.gov/35173739/]

Will keep on looking.....

**Comment by rajamazumder** [comment]
Email sent 8/3/2023
Hi Leigh,
We think it is a great idea. Below are some papers
Here are a few papers that can be used. What would be the next step?

- https://pubmed.ncbi.nlm.nih.gov/25548184/ (A red meat-derived glycan promotes inflammation and cancer progression. PNAS 2015)
- alpha-gal syndrome, sensitization to red meat antigen induced by tick bite (not NeuGc related)
[https://pubmed.ncbi.nlm.nih.gov/35017216/]
- use of dietary monosaccharide supplements for therapeutic relief in a subset of human CDGs
[https://pubmed.ncbi.nlm.nih.gov/29702557/]
- a review of O-GlcNAcylation, Glc elevation, and various pathways impacted by altered Glc metabolism, perhaps relevant for Glucosamine supplementation
[https://pubmed.ncbi.nlm.nih.gov/35173739/]
- https://medschool.ucsd.edu/som/cmm/research/labs/varki/Documents/A168.pdf Incorporation of a non-human glycan mediates human susceptibility to a bacterial toxin 2008
Best regards,
Raja

**Comment by rajamazumder** [comment]
Hi Leigh,
Hope you are doing well. Are you still interested in developing a podcast on this? Or if you have some other ideas let us know. 
Best regards,
Raja
