### ISSUE TITLE
Summary of PDB section strategy

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#507]
Based on the discussion with Raja provide a summary of the strategy to select a representative PDB ID for a protein to be shown as 3D structure in GlyGen. This should be presented and discussed in our weekly meeting.

**Comment by jeet-vora** [comment]
The strategy is [here](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/Documents/PDB%20Structures%20Selection%20Criteria.docx?d=w12390aa496f84d4aa5c91c68d4dc4d86&csf=1&web=1&e=i1WFp4)

The strategy was presented on Aug 2, 2023
