### ISSUE TITLE
Glycan Export Downloads

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#508]

**Comment by jeet-vora** [comment]
Nathan's glycan data export (GlyGen-GlycanData-Export-v1.14.0) is ready and in download's current folder.

The files for the following resource have been downloaded
data/projects/glygen/downloads/**sandbox**
data/projects/glygen/downloads/**gnome**
data/projects/glygen/downloads/**glyconnect**
data/projects/glygen/downloads/**glycan_list**

@rykahsay You can process the downloaded files.

**Comment by rykahsay** [comment]
I guess this can be closed now
