### ISSUE TITLE
Update download scripts to include YEAST

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#509]
FYI @jeet-vora @JingyueWu -->  I'll make a list of resources here.  Let me know if there's any others

**Comment by kmartinez834** [comment]
All download scripts are now saved at downloads/download_scripts/

Yeast added to script:
- [x] OMA
- [x] Glyconnect

**Comment by kmartinez834** [comment]
@JingyueWu --> Add Saccharomyces cerevisiae to mcw_oglcnac download instructions and chmod 775 instructions file

**Comment by JingyueWu** [comment]
Looks like Saccharomyces cerevisiae has been updated: 

<img width="801" alt="Screen Shot 2023-09-11 at 4 33 53 PM" src="https://github.com/glygener/glygen-issues/assets/61590108/eb121b83-2132-4e75-8fb8-78cde2b7a8a7">

Closing this ticket as I have also updated chmod 775 instructions and create symbolic step at the end.
