### ISSUE TITLE
Update Mondo ontology - glygen/downloads/mondo/current (current file is a folder now but file remains the same)

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#51]
- glygen/downloads/mondo/current (current file is a folder now but file remains the same)

**Comment by rykahsay** [comment]
what is mondo ontology?

**Comment by rykahsay** [comment]
I don't know why you have assigned back to me without answering my question -- What exactly do you mean by "update mondo ontology"? What dataset file or any other file should be updated? What dataset was being created using file(s) under downloads/mondo/current/ ???

**Comment by jeet-vora** [comment]
This is the mondo file in downloads/mondo/current/**mondo.owl**
The processing workflow remains the same.
The files that use mondo.owl are protein_disease_idmap.csv and protein_disease_names.csv

**Comment by rykahsay** [comment]
No, protein_disease_idmap.csv and protein_disease_names.csv depend on downloads/ohsu/mondo.json. I have never used downloads/mondo/current/mondo.owl

<img width="772" alt="image" src="https://user-images.githubusercontent.com/20584876/213034390-325e9330-d394-48ab-aaf4-b63b49a92e25.png">

**Comment by jeet-vora** [comment]
@rykahsay 
ohsu folder was used for the dataset coming from them (glycophenotype). Mondo resource is multi-institutional.

Do you still want to use the ohsu folder for mondo.json or you want to start using mondo.json from the mondo folder. I have updated the files at both the locations. If ohsu is continued to be used there needs to be folder structure for dataset release like other download folders. 

Let me know so the other files/folder can be removed/modified.

**Comment by rykahsay** [comment]
creare downloads/mondo/current/mondo.json  and let me know

**Comment by jeet-vora** [comment]
The file is in /data/projects/glygen/downloads/mondo/current/mondo.json
@rykahsay

**Comment by rykahsay** [comment]
done

**Comment by JingyueWu** [comment]
To me, it looks like Jeet has created mondo.json which I am able to open in my terminal. However, it is still a bit unclear to me what "mondo ontology" means or stands for based on this thread.

**Comment by JingyueWu** [comment]
@rykahsay Can you confirm that the file in /data/projects/glygen/downloads/mondo/current/mondo.json was used to generate protein_disease_idmap.csv and protein_disease_names.csv? 

Is there anything else I can review?

**Comment by rajamazumder** [comment]
@rykahsay it looks like this task is done. If not can you please clarify what @JingyueWu needs to do?
