### ISSUE TITLE
Update xref examples for external link script

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#511]
From #451 

Correct example accessions in file `misc/xref_info.csv` for resources that don't use UniProt or GlyTouCan ac's in external link script (/software/glygen/check-external-urls.py)

**Comment by kmartinez834** [comment]
`misc/xref_info.csv` has been updated with accurate example accessions for each xref link.  The following links are not working for me, @jeet-vora @JingyueWu can you please verify?

- (glycan_xref_cfg) http://www.functionalglycomics.org/glycomics/CarbohydrateServlet?pageType=view&view=view&operationType=view&carbId=carbNlink_30602_A

- (protein_xref_glycosmos_disease) https://glycosmos.org/glycogenes/show?source=kegg&gene_id=85365

**Comment by jeet-vora** [comment]
@kmartinez834 Yes both the links do not work. 

For `CFG` we can contact Akul Mehta and confirm the link/portal is active. For `GlyCosmos Disease` the link has probably changed. We might have to download and process the new dataset for disease associated genes from https://glycosmos.org/glycogenes which has different URL than mentioned above. There is another database we can look at - [Glyco-Disease Genes Database (GDGDB)](https://acgg.asia/db/diseases/gdgdb)

**Comment by kmartinez834** [comment]
@rykahsay I have disabled the CFG xref and updated the Glycosmos disease link:

```
#glycan_xref_cfg,CFG,http://www.functionalglycomics.org/glycomics/CarbohydrateServlet?pageType=view&view=view&operationType=view&carbId=%s,carbNlink_30602_A|carbOlink_20077_D000|carbOlink_20078_D000
glycan_xref_cfg,CFG,DISABLED
protein_xref_glycosmos_disease,GlyCosmos,https://glycosmos.org/glycogenes/show/%s#disease,85365|6448|3423
```

The only pages affected are Protein Detail and Glycan Detail. Please update.

**Comment by rykahsay** [comment]
please check on beta

<img width="568" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/d04c4a2d-e491-4877-bf82-e77c99d46bea">

**Comment by kmartinez834** [comment]
Looks good
