### ISSUE TITLE
Not important but is there any way we could arrange the subtypes by a certain order like for this example it will be : core 1 core 2 core 3 .... - Rahi

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#514]
Description

Note:

Not important but is there any way we could arrange the subtypes by a certain order like for this example it will be :
core 1
core 2
core 3
....

Rahi

https://app.pageproofer.com/to/note/207294
Reported by: myGlyGen@gmail.com

Window Size: 1707 x 803
Screen Size: 1536 x 864
Device: WebKit
Browser: Chrome version: 79.0.3945.79
Platform: Windows version: 10.0

rene@ccrc.uga.edu 
March 26, 2021 at 1:31 PM
Lets sort them alphanumerical. Both by type (first) and subtype (second).

**Comment by ReneRanzinger** [comment]
@sujeetvkulkarni Lets sort them alphanumerical. Both by type (first) and subtype (second).

**Comment by sujeetvkulkarni** [comment]
done.
