### ISSUE TITLE
Detect cell type in literature mining

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#515]
Rebekah made the following request at the F2F: "Indicate cell type where data is from. They may be valid structures depending on source - so dont make users have to dig to get the source"

After talking with Mike and Raja we decided that this could be a task for Vijay. We should add this to the agenda for the first meeting with him.

**Comment by kmartinez834** [comment]
@ReneRanzinger this should be covered by Vijay's Task 1 (detect contextual terms, such as disease, species, tissue, cell line, from publications) right?

**Comment by ReneRanzinger** [comment]
I think cell type is something different but we should ask him to consider to extract it as well:

"Cell lines are prepared by continuous passaging of primary cell cultures, whereas a cell strain is a specific cell obtained from a cell line, and the cell type refers to the finally differentiated cell." ([DifferenceBetween.com](https://www.differencebetween.com/difference-between-cell-line-and-vs-cell-strain-and-vs-cell-type/))

**Comment by kmartinez834** [comment]
Got it, I added this to the lit mining agenda for next time.  Ok to close this ticket?

**Comment by ReneRanzinger** [comment]
Lets keep it open for now. If Vijay agrees I think we should contact Rebecka and let her know. It shows that we are acting on the recommendations they gave us.
