### ISSUE TITLE
New potential tasks for Nathan (to discuss) 

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#516]
As you may remember we played a game at the F2F to collect ideas for GlyGen. We classified them last week and there were a bunch of items that we flagged as “ask Nathan”. These are items related to your current work or that fit with your expertise. I would like to have a meeting with you to talk about the items and see if you are interested in working on them. And if you want to work on them, in which year/release. The items are:
* Glycosylated sites from PRIDE 
* Links to large-scale data that can be re-analyzed
* API to connect to GNOME
* Better/more obvious integration of "validated" structure annotations from sandbox/glycotree 
   * in glycan score, in tables, highlight accessions
   * guide users to "sensual" structures
* Have a way similar to GlycoMaple to upload RNA seq data to focus on glycoenzymes that may be perturbed
   * For a list of enzymes show me the glyco-profile
* Reanalysis of GlyGen site data (MS) to provide annotated spectra for evidence (glycan attached to proteins)
* Glycan structure dictionary term mapping to glycans

What would be a good day/time next week to talk about this? Raja, Mike and Jeet would also like to join the discussion.

**Comment by ReneRanzinger** [comment]
@edwardsnj  We already had a short dive into the last bullet point today. I still need to meet to finalize this and talk about the other points. If that can be done before next Wednesday it would be great. Otherwise I will put the discussion (in the Wednesday meeting) on hold till we figured it out in the smaller group.

**Comment by edwardsnj** [comment]
I can meet, but you want to pull in three others too. Today and tomorrow (thurs, fri) are currently unscheduled. Monday afternoon is free, tuesday has gaps here and there.

**Comment by ReneRanzinger** [comment]
I will send the invite and we also will need to talk about GSA grant and if you will be interested on joining and what we would like you to do.
