### ISSUE TITLE
Update Disease Ontology data - data/projects/glygen/downloads/do/current

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#52]
data/projects/glygen/downloads/do/current

**Comment by rykahsay** [comment]
all disease related info is based on generated/sparql/disease/disease.nt (created from downloads/do/current/doid.owl). Can you show me any dataset in the unreviewed folder that is outdated in relation to downloads/do/current/doid.owl?

**Comment by JingyueWu** [comment]
@rykahsay 

Please let me know if my understanding is wrong: are we trying to check /data/projects/glygen/generated/datasets/unreviewed against data/projects/glygen/downloads/do/current/doid.owl  ?

Question: would the command line be:

python3 check-dataset.py -I /data/projects/glygen/generated/datasets/unreviewed -r data/projects/glygen/downloads/do/current/doid.owl
