### ISSUE TITLE
Details page web service implementation changes for server side pagination of tables.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#521]
Details page web service for protein, glycan, publication (based on tables chosen for pagination) needs to be modified for server side pagination.
As backend will be sending initial some records (based on initial page size) to frontend using details web service and to get rest of records frontend will be using table pagination web service. We will need to decide the schema for these two cases. This option (of sending initial records using details web service) was chosen to minimize network traffic by avoiding unnecessary web service calls and to reduce time delay in page loading. There are below two options,

1. Details page web service will use existing schema and table pagination web service will have different tab/table based schema.
For example in case of Glycosylation section we have 4 tabs and each tab has one table. So now based on the initial records requested by frontend backend needs to query separately for each tab/table and then merge the records for all tabs in the existing schema and send it to frontend using details page web service. And for table pagination web service backend will send records as requested per table separately.
https://glygen.org/protein/P05783-1#Glycosylation

As we are not changing details page schema in this case frontend will have less number of changes for details page. But same tables will get populated using two different schemas so api testing would need to consider this.

2. Details page web service and table pagination web service will get records using same schema.
Consider same above example, now in case of Glycosylation section which has 4 tabs/tables will get records in same schema as that of table pagination web service, they will not be merged but will be separate. Frontend needs to make changes in the post processing of data on the respective details pages to accommodate schema changes.

@rykahsay @ReneRanzinger Please review above suggestions and propose a solution for implementation.

**Blocker for**:
* #246 
* #247

**Comment by ReneRanzinger** [comment]
@sujeetvkulkarni Is this resolved? I think you told me that Robel went for the solution not to change the schema.

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger yes, this is resolved, we can close it.
