### ISSUE TITLE
SPARQL GA4 properties is not capturing analytics

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#522]
The GA4 properties Robel implemented is not capturing analytics so far. Can you check and if see if the implementation is done correctly by Robel.

Also API, beta and Wiki need to be implemented and Robel is working on it. Can you also check why the property is not distinguishing between the domains. eg hits from data.glygen.org. I am adding the screenshots of pages from UA and GA4 page hits

GA4
![image](https://github.com/glygener/glygen-issues/assets/25825266/925a038c-9386-48bc-a310-91d52afdb975)

UA
![image](https://github.com/glygener/glygen-issues/assets/25825266/b2c522b8-b5ef-412e-888c-b00a68497e3b)

**Comment by sujeetvkulkarni** [comment]
It is getting captured but you have to add the hostname property for GA-4.
Go to "Reports -> Engagement -> Pages and screens" and add a "hostname" column by clicking + sign near "Page path and screen class" and selecting "Page / screen" -> "Hostname.

**Comment by sujeetvkulkarni** [comment]
Also data from data.glygen.org, sparql, wiki is getting captured. See below screen shots for the period June 20 - July 17, 2023.

Only problem looks like tst server data from data portal is also getting captured (see third screenshot) . Which Robel can filter based on domain name or we can ignore while generating reports.

<img width="1603" alt="Screenshot 2023-07-18 at 8 17 43 PM" src="https://github.com/glygener/glygen-issues/assets/13891482/722aa858-4866-4989-821f-0e91ba3b43a8">



<img width="1598" alt="Screenshot 2023-07-18 at 8 18 43 PM" src="https://github.com/glygener/glygen-issues/assets/13891482/2edf783e-bd07-45fd-b607-afbc7468cd25">



<img width="1601" alt="Screenshot 2023-07-18 at 8 19 47 PM" src="https://github.com/glygener/glygen-issues/assets/13891482/9af63249-fc61-4825-b46e-03c3bfcce7b4">

**Comment by jeet-vora** [comment]
Issue resolved
