### ISSUE TITLE
Data downloads for 2.2

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#524]
List of resources downloaded for 2.2:

| Resource | Downloaded by | Notes | Issue |
| -------- | ------- | ------- | ------- |
| Cellosaurus | Karina | | |
| ChEBI| Karina | | |
| Glyconnect | Karina | Human still has internal 500 error, copied from previous release. Added yeast. |  |
| OMA| Karina | Added yeast ortholog pairs | |
| Reactome | Karina |  |  |
| EBI | Jeet & Jingyue | bash script has been updated and data downloaded | #529 |
| NCBI RefSeq  | Jeet | bash script has been updated and data downloaded | #530 |
| Genome Alliance  |  |  | |
| O-GlcNAc DB |  |  |  |
| Disease Ontology | Jeet | Assigned Robel to process | #547  |
| MGI |  |  |  |
| Mondo | Jeet | Assigned Robel to process | #548  |
| PDB |  | skip for now, waiting on new protocol??? |  |
| Medline |  | skip for now - Karina/Robel's tasks toward the end of the release |  |
| matrixdb | Jingyue |  |  |
| genomics_england | Jingyue |  |  |

**Comment by JingyueWu** [comment]
Refer to #359

**Comment by JingyueWu** [comment]
@kmartinez834 @jeet-vora can we close this ticket?

**Comment by JingyueWu** [comment]
@jeet-vora @kmartinez834 let's leave this ticket open as a reference for 2.3

**Comment by kmartinez834** [comment]
Closing this ticket. 
@JingyueWu you can always find it later by searching closed tickets
