### ISSUE TITLE
Expression and disease data integration

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#528]
We have tissue/cell line expression and disease data from OGlcNAc Atlas and UnicarbKB (possibly others?), but they aren't integrated with the API/front end:

```
$ head reviewed/human_proteoform_glycosylation_sites_oglcnac_atlas.csv
"uniprotkb_canonical_ac","glycosylation_site_uniprotkb","amino_acid","saccharide","glycosylation_type","xref_key","xref_id","src_xref_key","src_xref_id","sample_type","method","analytical_throughput","notes","carb_name","glycosylation_subtype","source_tissue_id","source_tissue_name","source_cell_line_cellosaurus_id","source_cell_line_cellosaurus_name","peptide","start_pos","end_pos","start_aa","end_aa","site_seq"
"A0A087WXM9-1","255","Thr","G49108TO","O-linked","protein_xref_oglcnac_atlas","A0A087WXM9","protein_xref_oglcnac_atlas","A0A087WXM9","HeLa cells","MS","HTP","","GlcNAc","O-GlcNAcylation","","","CVCL_0030","HeLa","STPEK-T-KKKKT","255","255","Thr","Thr","T"
```
https://glygen.org/glycan/G49108TO#Expression
![image](https://github.com/glygener/glygen-issues/assets/90285371/306c9ff2-2945-46b0-9035-e3176fc9c1dd)

```
$ head ~/reviewed/human_proteoform_glycosylation_sites_unicarbkb.csv
"uniprotkb_canonical_ac","glycosylation_site_uniprotkb","amino_acid","saccharide","glycosylation_type","xref_key","xref_id","src_xref_key","src_xref_id","start_pos","end_pos","start_aa","end_aa","site_seq","site_type","src_file_name","uckb_id","composition","curation_notes","additional_notes","pdb","swiss_model","abundance","source_tissue_id","source_tissue_name","source_cell_line_cellosaurus_id","source_cell_line_cellosaurus_name","n_sequon","n_sequon_type"
"O00391-1","","Leu","G57321FI","O-linked","protein_xref_unicarbkb","O00391","protein_xref_unicarbkb","O00391","488","500","Leu","Lys","LAGAPSEDPQFPK","known_site","fuzzy_legacy_cph_start_end_positions","G57321FI","HexNAc1Hex0dHex0NeuAc0NeuGc0Pent0S0P0KDN0HexA0","Data provided by GlycoDomainViewer","sec_vva_try with KO entrez:29071","","","","","","CVCL:0030","HeLa","",""
```
https://glygen.org/glycan/G57321FI#Expression
![image](https://github.com/glygener/glygen-issues/assets/90285371/48be3b61-4b2b-436f-933e-69892d0e6e38)

FYI @jeet-vora @JingyueWu

**Comment by jeet-vora** [comment]
@kmartinez834 I had reported the issue about G49108TO last release but Robel turned me down saying it cannot be fixed unless server side pagination is done. I had disagreed at that time. 

For G49108TO, it makes sense, but not for G57321FI or G83204BU or others, having cell/cell-line information. Something is broken at Robel's end. Do make an issue for him.

For G49108TO
You can't even search the accession G49108TO in simple search now. The detail page only shows when URL is entered. Also under 'organism' the data sources O-GlcNAc atlas/O-GlcNAc database are also being not shown.

**Comment by kmartinez834** [comment]
Robel has been alerted to the issue in #614 . Will close this ticket when above examples are addressed.

**Comment by kmartinez834** [comment]
cell_line.id: "6642" appears 4 times in https://api.tst.glygen.org/glycan/detail/G57321FI

The following sites for cell_line CVCL_6642 (HEK293-F) are still missing from `reviewed/sarscov2_proteoform_glycosylation_sites_glyconnect.csv`:

```
"P0DTC2-1","1076","Thr","G57321FI"
"P0DTC2-1","1077","Thr","G57321FI"
"P0DTC2-1","1097","Ser","G57321FI"
"P0DTC2-1","73","Thr","G57321FI"
"P0DTC2-1","76","Thr","G57321FI"
"P0DTC2-1","803","Ser","G57321FI"
```
