### ISSUE TITLE
Process EBI data for 2.2

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#529]
Process EBI data with Yeast (Tax ID 559292) for 2.2. Masterlist has been updated for Yeast files. Some yeast datasets can be potentially empty, will remove after processing.

`data/projects/glygen/downloads/ebi/current`

- Part of #472 
FYI, @JingyueWu

**Comment by rykahsay** [comment]
Check

**Comment by jeet-vora** [comment]
done
