### ISSUE TITLE
GLYG-1746 - Process O-Gluc dataset

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#53]
Readme for processing O-gluc dataset is below - Read the instructions before processing and process as mentioned.

**O-glucosylation dataset** 
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/25825266/211858380-4a729b89-aec7-4ea0-83a2-31a8ffcd4529.png">

input  data/projects/glygen/generated/datasets/compiled/human_proteoform_glycosylation_sites_o-gluc.csv 
  human_*masterlist 
  human_*canonical.fasta  
  
output  **human_proteoform_glycosylation_sites_o-gluc.csv**
   human_proteoform_citations_glycosylation_o-gluc.csv  
   log files 
   
  
                                         
Steps                                          
                                           
Step 1  Map uniprotkb_ac field to uniprot_canonical_ac, map gene name to the current gene names                                       
                                           
Step 2  Extract glycosylation_site and amino_acid from the input file to the output file as glycosylation_site and amino_acid. Validate the glycosylation_site and amino_acid with the human fasta canonical sequence.                                       
                                           
Step 3  Extract saccharide, glycosylation_type, glycosylation_subtype, carb_name fields as saccharide, glycosylation_type, glycosylation_subtype, carb_name into the output file                                       
                                           
Step 4  From evidence and data_source extract the information into xref_key, xref_id, src_xref_key, src_xref_id as shown in the output table( xref_key\src_xref_key - protein_xref_glygen_ds \ protein_xref_pubmed\protein_xref_prosite-prorule). Please note entries with Pubmed are reported sites whereas others are predictied using Prosite ProRule. Use Prosite Pro Rule ID - PRU00076. Use GLY_000704 for protein_xref_glygen_ds. Ignore GLY_000703 in the image.                                       
                                           
Step 5  Extract notes and glycosylation stoichiometry together as notes as e.g. - Consensus sequence  C3-x-N-T-x-G-S-(FY)-x-C4. Glycosylation by enzyme POGLUT2 and POGLUT3. \ glycosylation stoichiometry >70%                                                                               
Step 6  Generate log files with failed entries                                       
 
                                          
output  datasets/compiled/human_proteoform_glycosylation_sites_o-gluc.csv                                       
   log file                                       
   human_proteoform_citations_glycosylation_o-gluc.csv    

glygen/generated/misc/bcodb/GLY_000704.json can be processed to the new schema and added to the BCO portal.

Original readme - https://docs.google.com/spreadsheets/d/1-FYOI4CTWhmb6ABsgLBMNNyTTIIX71GmYYnIZKq4y3g/edit#gid=2007898417

**Comment by rykahsay** [comment]
Please change output file names to  *o_gluc.csv (instead of *o-gluc.csv) in your BCOs (I have edited the datamaster)

**Comment by jeet-vora** [comment]
@rykahsay 
Name changed in BCO /misc/bcodb/GLY_000704

Dataset has not been processed correctly. Broken dataset. Once reprocessed update the citations_o_gluc.csv
**See below**
<img width="596" alt="image" src="https://user-images.githubusercontent.com/25825266/208224162-c6eb1eb6-c88d-44b0-b609-ac0593bae973.png">

**Comment by rykahsay** [comment]
done

**Comment by jeet-vora** [comment]
@rykahsay 3 issues

1) carb_name from step 3 has to be extracted
2) step 5 and 6 is missing
3) fields need to be removed  **start_pos|end_pos|start_aa|end_aa|site_seq** from the dataset

**Comment by rykahsay** [comment]
@jeet-vora 

1. I don't see "carb_name" in step-3
2. step 5 and step 6 are done now
3. I cannot remove those fields --> they are required fields for protoeoform datasets

**Comment by jeet-vora** [comment]
@rykahsay 

1. Step 3 has been modified to include carb_name (Glc in dataset)
2. _ has been inserted in glycosylation_stoichiometry field
3. The log file has been checked for corrections in entries
Please reprocess

**Comment by jeet-vora** [comment]
@rykahsay There was one entry in log file which has been confirmed and corrected for aa mismatch with the source. 
The dataset needs final processing to include all entries. Please process so the issue can be closed.

**Comment by rykahsay** [comment]
done
