### ISSUE TITLE
Problem with current GlyGen data link (mcw_oglcnac)

### ISSUE THREAD

**Issue by edwardsnj** [glygener/glygen-issues#531]
The links:

  /ln2data/downloads/mcw_oglcnac/current/human_o-glcnacome_mcw.csv

etc. don't work, the current symbolic link seems broken

The urls:

  https://data.glygen.org/ln2data/downloads/mcw_oglcnac/2023_04/

do work though...

**Comment by rykahsay** [comment]
I have tried to fix it, please check https://data.tst.glygen.org/ln2data/downloads/mcw_oglcnac/current/

@JingyueWu please have a look at these two screenshots on the symbolic link you did and how I have fixed it. Please make sure all other symbolic links look like the second screenshot
 
<img width="1378" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/2e08bc61-17bc-47ef-ae58-da44dca39590">


<img width="1118" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/7b242869-c5aa-47d5-92bf-31c715056fec">

**Comment by edwardsnj** [comment]
Seems to work now...

**Comment by edwardsnj** [comment]
I think the process by which these are populated (the filenames needs work). I didn't understand why things that used to work now do not - and I noticed that 

https://data.glygen.org/ln2data/downloads/mcw_oglcnac/2023_04/

and

https://data.glygen.org/ln2data/downloads/mcw_oglcnac/2022_07_29/

do not use a consistent naming convention (- vs _ in the filename). We also hit a case where drosophila was used instead of fruitfly in a filename, sarcov2 rather than sarscov2, etc...

**Comment by kmartinez834** [comment]
In the last release we started updating all of our processing scripts, or creating scripts as some resources were still being downloaded manually.  We are finishing up this effort during the current release.  

Generally, we use the file name that was provided by the resource.  If a file name needs to be changed for Robel's pipeline, our download script is creating a symbolic link to the original file.

Moving forward, file names should not change from one release to the next.

**Comment by ReneRanzinger** [comment]
For the next version we should continue the discussion we had in the developer meeting and see if the alternative strategy is useful (see #563 )
