### ISSUE TITLE
GlyConnect filenames are incorrect in the Glycan File Tracker (GW Files tab)

### ISSUE THREAD

**Issue by edwardsnj** [glygener/glygen-issues#532]
The glyconnect_fruitfly.json and glyconnect_sarscov2.json filenames in the Glycan File Tracker (https://docs.google.com/spreadsheets/d/1PYsMSfi5Z_6ZxHDMM8z5iSEXDOr6SAlzfpx01rWr0zc/edit?usp=sharing) are incorrect. They should be: glyconnect_drosophila.json and glyconnect_sarcov2.json.

**Comment by kmartinez834** [comment]
Files in server were named incorrectly.  This has been fixed.  I also added glyconnect_yeast.json to the file tracker.

Note, files named glyconnect_*.json are symbolic links to the files from Glyconnect (names starting with glycosylations?taxonomy=).

![image](https://github.com/glygener/glygen-issues/assets/90285371/0d16c38a-237e-4a6c-a259-8ff9db776ba7)

**Comment by kmartinez834** [comment]
See #531 for file naming explanation
