### ISSUE TITLE
GlyGen Dataset output not available for mcw 

### ISSUE THREAD

**Issue by edwardsnj** [glygener/glygen-issues#533]
These datasets advertise (in their README/BCOJSON) that the output files for these datasets:
        GLY_000633
        GLY_000631
        GLY_000632
        GLY_000517

are https:/data.glygen.org/ln2releases/data/v-2.1.1/reviewed/fruitfly_proteoform_glycosylation_sites_oglcnac_mcw.csv

but the corresponding "current" link does not work:

https:/data.glygen.org/ln2releases/data/current/reviewed/fruitfly_proteoform_glycosylation_sites_oglcnac_mcw.csv

It does work for other datasets.

**Comment by rykahsay** [comment]
Can you try now? This works for me now

```
curl https:/data.glygen.org/ln2releases/data/current/reviewed/fruitfly_proteoform_glycosylation_sites_oglcnac_mcw.csv
```

**Comment by edwardsnj** [comment]
I agree, it does seem to be working now. What changed?

**Comment by edwardsnj** [comment]
OK, this is another naming inconsistency issue: 

rat_proteoform_glycosylation_sites_oglcnac_mcw.csv

vs 

rat_proteoform_glycosylation_sites_o_glcnac_mcw.csv

version 2.0.1 and 2.0.2 used the second form, 2.0.3 and 2.1.1 use the first form. 2.0.3 and 2.1.1 also do not have the dataset accession version of the files (which would dodge the need for this extra information).

**Comment by kmartinez834** [comment]
@jeet-vora why is the old name lingering? Can you look into this?

**Comment by jeet-vora** [comment]
@kmartinez834 Robel changed the filename from *_o_glcnac_mcw.csv to *_oglcnac_mcw.csv and the change was not conveyed to Nathan. It is now consistent with all species files and won't change in the future.

Here is the list of files whose names were changed (#54)
