### ISSUE TITLE
QC design for uploaded glycan related files in data.glygen.org

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#534]
First Jeet needs to share example files

**Comment by jeet-vora** [comment]
Here are the dummy files from Rene

[PMID18725413-fly-O-Glycans-Fig2-UPload.csv](https://github.com/glygener/glygen-issues/files/12071284/PMID18725413-fly-O-Glycans-Fig2-UPload.csv)
[PMID18725413-fly-O-Glycans-Fig2-UPload.xlsx](https://github.com/glygener/glygen-issues/files/12071285/PMID18725413-fly-O-Glycans-Fig2-UPload.xlsx)

FYI @JingyueWu

**Comment by ubhuiyan** [comment]
Would it be possible to get a bit more context for this ticket? I can add to the 09/04 meetings as well.

**Comment by ReneRanzinger** [comment]
@jeet-vora @rykahsay see Urnishas request.

**Comment by jeet-vora** [comment]
@ReneRanzinger @ubhuiyan 

As per our previous discussion, the new files will be uploaded to TableMaker and GlyGen/GW will pull from the TableMaker and hence there is no need to maintain/improve the GlyGen Upload feature.
