### ISSUE TITLE
SFG abstract planning

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#535]
We need to plan who is sending which abstract for SfG.

Possible topics
- GlyGen
- Glycan structure dictionary
- Array repository
- Biomarkers
- CFDE

**Comment by kmartinez834** [comment]
Per email from SFG today, abstract submission deadline is Sunday Sept 10th

**Comment by JingyueWu** [comment]
Adding myself to this ticket, as Raja has confirmed that I will also be attending. Per general meeting discussion, Mike thinks internship could be a potential topic.

**Comment by ReneRanzinger** [comment]
The following abstract will be submitted:
* @mtiemeyer0919: Data acquisition from data generators
* @mtiemeyer0919 + @jeet-vora: Data distillery (#657)
* @ReneRanzinger: GlyGen
* @kmartinez834: BioCuration workshop
* @JingyueWu + @jeet-vora: CFDE (#652)
* @edwardsnj: GlycoMotif/Sandbox
