### ISSUE TITLE
datasets requiring name changes in BCOs

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#54]
Please make the following changes in the BCOs (I have done the changes on the server files and dataset-masterlist)

>> GLYCOSYLATION
*_

- [x] proteoform_citations_glycosylation_glyconnect.csv --> *_proteoform_citations_glycosylation_sites_glyconnect.csv
- [x] *_proteoform_citations_glycosylation_literature_mining.csv --> *_proteoform_citations_glycosylation_sites_literature_mining.csv
- [x] *_proteoform_citations_glycosylation_o_glcnac_atlas.csv --> *_proteoform_citations_glycosylation_sites_o_glcnac_atlas.csv
- [x] *_proteoform_citations_glycosylation_o_glcnac_mcw.csv --> *_proteoform_citations_glycosylation_sites_o_glcnac_mcw.csv
- [x] *_proteoform_citations_glycosylation_unicarbkb.csv --> *_proteoform_citations_glycosylation_sites_unicarbkb.csv
- [x] *_proteoform_citations_glycosylation_uniprotkb.csv --> *_proteoform_citations_glycosylation_sites_uniprotkb.csv
- [x] *_proteoform_citations_glycosylation_harvard.csv --> *_proteoform_citations_glycosylation_sites_harvard.csv 
- [x] *_proteoform_citations_glycosylation_literature.csv --> *_proteoform_citations_glycosylation_sites_literature.csv
- [x] *_proteoform_citations_glycosylation_o_gluc.csv --> *_proteoform_citations_glycosylation_sites_o_gluc.csv
- [x] *_proteoform_citations_glycosylation_tyr_o_linked.csv --> *_proteoform_citations_glycosylation_sites_o_gluc.csv
 

>> PHOSPHORYLATION
*

- [x] _proteoform_citations_phosphorylation_iptmnet.csv.csv --> *_proteoform_citations_phosphorylation_sites_iptmnet.csv
- [x] *_proteoform_citations_phosphorylation_uniprotkb.csv --> *_proteoform_citations_phosphorylation_sites_uniprotkb

>> GLYCATION

- [x] *_proteoform_citations_glycation_uniprotkb.csv --> *_proteoform_citations_glycation_sites_uniprotkb.csv

**Comment by jeet-vora** [comment]
Done
