### ISSUE TITLE
Linking Pride/MassIVE datasets in GlyGen

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#543]
We can try to do this based on the publications in GlyGen and the same PMID in Pride or MassIVE. As a first step @jeet-vora  will check with @pkay47 if UniProt already has this.

**Comment by ReneRanzinger** [comment]
A while back we got the following from Tytus Mak:
```
If I may ask, what are the future development plans for GlyGen? Any plans for including mass spectra in the database? 
I'm a member of the NIST Mass Spectrometry Data Center, and we're responsible for producing MS libraries for 
everything from small molecules, to glycans, glycolipids, peptides, glycopeptides, etc. We have publicly available 
glycan spectral libraries both of pure glycan standards 
(https://chemdata.nist.gov/dokuwiki/doku.php?id=chemdata:glycan-library) and material/matrix specific 
(https://chemdata.nist.gov/dokuwiki/doku.php?id=peptidew:lib:oligosaccarides). If the inclusion of spectral data is 
anywhere on your roadmap we'd be quite happy to discuss a potential collaboration.
```
That could be another lead.

**Comment by pv47** [comment]
UniProt has xrefs to PRIDE & MassIVE. MassIVE xref is only for Human

![image](https://github.com/glygener/glygen-issues/assets/7321403/6df3e498-f8a9-442e-b4b1-0af3921aa146)


MassIVE xref for P0DOY2 in uniprot-proteome-homo-sapiens.nt
<http://purl.uniprot.org/uniprot/P0DOY2> <http://www.w3.org/2000/01/rdf-schema#seeAlso> <http://purl.uniprot.org/massive/P0DOY2> .  
<http://purl.uniprot.org/massive/P0DOY2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.uniprot.org/core/Resource> .                          
<http://purl.uniprot.org/massive/P0DOY2> <http://purl.uniprot.org/core/database> <http://purl.uniprot.org/database/MassIVE> .

**Comment by pv47** [comment]
MassIVE page can be linked using url template - https://massive.ucsd.edu/ProteoSAFe/protein_explorer.jsp?libraries=2&protein_name=<UNPROT_PRIDE_XREF_ID>

eg: https://massive.ucsd.edu/ProteoSAFe/protein_explorer.jsp?libraries=2&protein_name=P0DOY2
