### ISSUE TITLE
Process DO data

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#547]
Process Disease Ontology data
/data/projects/glygen/downloads/do/current

Part of https://github.com/glygener/glygen-issues/issues/472

FYI, @JingyueWu

**Comment by rykahsay** [comment]
Done, again, the ticket should have said:
"downloads/do/current has been updated, please update the following datasets"

protein_disease_idmap.csv
protein_disease_names.csv
*_protein_disease_glygen.csv
*_protein_disease_cdg.csv
*_protein_disease_genomics_england.csv
*_protein_disease_glyco.csv
*_protein_disease_glycosmos.csv
*_protein_disease_uniprotkb.csv
*_protein_disease_alliance_genome.csv
*_protein_disease_alliance_genome.csv

**Comment by jeet-vora** [comment]
Done
