### ISSUE TITLE
Process MONDO data

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#548]
Process MONDO data
/data/projects/glygen/downloads/mondo/current

Part of https://github.com/glygener/glygen-issues/issues/472

FYI, @JingyueWu

**Comment by rykahsay** [comment]
Done, but the ticket should have said "downloads/mondo/current is updated, please process the following dataset files that depend on it":
- protein_disease_idmap.csv
- protein_disease_names.csv

**Comment by jeet-vora** [comment]
Done
