### ISSUE TITLE
Process iptmnet dataset (new data - Yeast)

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#549]
Process iptmnet dataset with new data yeast. 

The workflow for human, mouse, rat and fruitfly remains the same.
For yeast, from column 5, extract the entries for

**`Saccharomyces cerevisiae (strain ATCC 204508 / S288c) (Baker's yeast)`**

/data/projects/glygen/downloads/iptmnet/current

Part of https://github.com/glygener/glygen-issues/issues/472

FYI, @JingyueWu

**Comment by rykahsay** [comment]
check

**Comment by jeet-vora** [comment]
Done no issues
