### ISSUE TITLE
Using check-citation-datasets.py

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#55]
Please read the documentation at section "Dataset Specific Documentation" and start checking citations datasets

**Comment by kmartinez834** [comment]
@rykahsay can you update the script to output a list of datasets missing an associated citations dataset?

There are 24 datasets with diff greater/less than 0.  What do you need from us to fix this?

**Comment by kmartinez834** [comment]
@rykahsay disregard previous comment regarding updating script (question was answered in #49 )

How should we address datasets that are missing PMIDs in citation files?

**Comment by rykahsay** [comment]
"How should we address datasets that are missing PMIDs in citation files?" --> this should not happen. If you find such cases, you create me a ticket with the following information.
-- a list of PMIDs that are in a dataset but missing in the corresponding citations dataset

**Comment by rykahsay** [comment]
If the above comment is clear, please close the ticket

**Comment by kmartinez834** [comment]
Tickets opened for issues related to citation datasets:
#80 
#84 
#85
