### ISSUE TITLE
Process atlas_oglcnac data (new data - Yeast)

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#550]
The OGlcNAc atlas datasets also contain yeast data. To extract yeast entires select `yeast` from the `speices` column from both the source data files.

The workflow for human, mouse, rat and fruitfly remains the same.

`PATH: /data/projects/glygen/downloads/atlas_oglcnac/current`

Part of https://github.com/glygener/glygen-issues/issues/472

FYI, @JingyueWu

**Comment by rykahsay** [comment]
check

**Comment by jeet-vora** [comment]
Done no issues
