### ISSUE TITLE
Update the News section on the homepage

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#552]
In the middle of August we will look into this again. We may have to use Mastodon instead.

**Comment by ReneRanzinger** [comment]
@rajamazumder send a few Mastodon servers people are using:

Raja- techhub.social
Lara- mstdn.social
Mike - sfba.social
Chris - mstdn.science

**Comment by ReneRanzinger** [comment]
Hi all,

As we discussed in our group meeting, we should make a move to mastodon since eX-twitter is not working as news feed for our webpage anymore. I had similar discussions with Kiyoko and Frederique (copied in) in individual emails. And it seems both think about the same thing. 

For GlyGen we will keep the twitter account active and post “toot’s” on twitter as well (both accounts will show the same). Mainly because we have (a few) followers. But the main question is, which mastodon instance should we use AND should we all try to go to the same (so we can have our little glyco-bubble)? This is the list of science related instance I came across (some of them are rather small):
•	Mstdn.science 
•	Sciencemastodon.com 
•	Genomic.social 
•	Sciences.social 
•	datasci.social  

Raja made a test account on techhub.social. You can drop the “URL’s” above in the browser and see the entry pages of the mastodon servers (including the number of active users in the left side). 

What do you think? Maybe the people going to Taiwan can have a short chat in person (maybe including Daniel Bojar) and decide on a server and we can all go there in our own time?

Best,
  René

**Comment by ReneRanzinger** [comment]
Hi Rene,

I have made a personal account on mstdn.science since I saw a few glycobiologists using this server.
Just my 2c, but I think GlyCosmos might use this one...

Best,
Kiyoko

**Comment by ReneRanzinger** [comment]
After discussion with Kiyoko hear at IGO, seems like the 'science' domain would make the most sense for GlyGen registration.

**Comment by sujeetvkulkarni** [comment]
1817c06c92be63f04bb589750ab80473bbaf0276

**Comment by sujeetvkulkarni** [comment]
5c5c86153abbd88b0eaf55b989570a48f46acb46
