### ISSUE TITLE
Biomarker card placements on Protein, Motif, Publication details page.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#553]
Can you please tell where biomarker card should be placed on Protein, Motif and Publication details page.
https://docs.google.com/presentation/d/14vJ_o_fq6b0UR2DTgs0NhATl-C3uiPVN68wGLQnejq4/edit?pli=1#slide=id.g25249709de5_0_26

**Comment by ReneRanzinger** [comment]
Place above expression (glycan, protein, publication) 

    Motif: above sequence section

**Comment by sujeetvkulkarni** [comment]
done.
8eafab4aa819117536d66c01fd5e8f57c8a90aa5
