### ISSUE TITLE
Instructions for isoform mapping tool

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#560]
Preethi can you add all the instructions about the isoform mapping tool here?

**Comment by pv47** [comment]
1. Install jdk 11 (opensource: https://openjdk.org/projects/jdk/11/) 
2. Download jar https://ftp.ebi.ac.uk/pub/contrib/glygen/previous_releases/2022_01/glygen.jar to <work_dir>
3. Prepare input 1 - get protein master list of current release in <work_dir>. sample https://docs.google.com/spreadsheets/d/1AVXfw8dd00r70x-eWLw0GsUHNyfCOz-agxHxHwFPcdI/edit?usp=drive_link
4. Prepare input 2 - sequence of each protein in master list in fasta format in <work_dir>. sample https://drive.google.com/file/d/1MBgTAW4InW0tvVsNeDeuc7fmhJ6lbW_F/view?usp=drive_link
5. Prepare input 3 - list of isoform accession, aa position & amino acid for mapping in <work_dir>. sample https://drive.google.com/file/d/1x0KZjhf24W6XR7qVb7Tv9mNX-ulFkR2o/view?usp=drive_link
6. Run app with 3 input parameters & output file_name
> java -classpath <work_dir>\glygen.jar uk.ac.ebi.uniprot.glygen.util.SiteMappingTool -protein_list <work_dir>\human_protein_masterlist.csv -glygen_fasta <work_dir>\human_protein_allsequences.fasta -isoform_info <work_dir>\input.csv -out_file <work_dir>\output.csv 
7. Results in <work_dir>\output.csv 
            7.1     uniprotkb isoform_ac: first col of input.csv
            7.2     aa_pos isoform: second col of input.csv
            7.3     amino_acid isoform: third col of input.csv
            7.4     uniprotkb canonical_ac: canonical accession of isoform
            7.5     aa_pos canonical: aa position in canonical (same as col 2)
            7.6     amino_acid canonical: aa at position in canonical
            7.7     status: aa at isoform & canonical is same for given position?   
            7.8     mapped_pos canonical: same as col 2 if aa's match else actual position in canonical
            7.9     aa_mapped can_pos: aa at mapped_pos canonical, same as col 3

**Comment by pv47** [comment]
[SiteMappingTool.zip](https://github.com/glygener/glygen-issues/files/14280053/SiteMappingTool.zip)

Java source code.

**Comment by pv47** [comment]
@rykahsay Steps to run tool

- create input.csv having list of isoforms that need canonical mapping. It has three columns isoform_ac, amino_acid_pos & amino_acid. Can use attached sample input.csv  
[input.csv](https://github.com/glygener/glygen-issues/files/15323340/input.csv)
- copy input.csv to a local folder <input_dir>
- replace <input_dir> with local folder name & run 'docker run -v <input_dir>:/input ebiglygen/mapper-java-jar:basic'
- output will be in <input_dir>/output.csv 

output.csv has eight cols - isoform_ac, aa_pos, amino_acid, canonical_ac, aa_pos_can,  aa_can,   status,   mapped_can_pos,  aa_in_mapped_canonical_pos.

**Comment by ReneRanzinger** [comment]
Only some changes needed to deal with the data format issue.

**Comment by pv47** [comment]
@rykahsay output will be in 'output.tsv'. Please check

**Comment by pv47** [comment]
Changes in latest docker image:

- output tsv has 9 columns
     uniprotkb_isoform_ac
     aa_pos_isoform
     aa_isoform_user
     aa_isoform_actual
     uniprotkb_canonical_ac
     aa_pos_canonical
     aa_canonical
     warning
     error
- output has glygen canonical
- optional input amino_acid 
- warning message - 'incorrect input aa' for invalid or empty input aa in warning column
- error messages
     invalid glygen accessions - no canonical for <input_accession>, mapping not done 
     missing input aa position - input position missing, mapping not done
     invalid input position (-ve or non-integer) - invalid input position, mapping not done
     invalid input position (0) - invalid input position: 0, mapping not done
     invalid input position (pos > seq length) - input position <aa_pos> greater than sequence length <len>, mapping not done

@rykahsay please take a look & let me know if any changes are needed

**Comment by rykahsay** [comment]
@pkay47  ... looks like there is a problem in the structure of the output.tsv file when there is no mapping done. Look at how the last object is coming out (less number of fields).

```
{
    "jobtype": "isoform_mapper",
    "objlist": [
        {
            "aa_canonical": "T",
            "aa_isoform_actual": "T",
            "aa_isoform_user": "T",
            "aa_pos_canonical": "3",
            "aa_pos_isoform": "3",
            "glygen_canonical_ac": "A6NJB7-1",
            "uniprotkb_isoform_ac": "A6NJB7-2"
        },
        {
            "aa_canonical": "S",
            "aa_isoform_actual": "S",
            "aa_isoform_user": "S",
            "aa_pos_canonical": "8",
            "aa_pos_isoform": "8",
            "glygen_canonical_ac": "A6NJB7-1",
            "uniprotkb_isoform_ac": "A6NJB7-2"
        },
        {
            "aa_canonical": "T",
            "aa_isoform_actual": "T",
            "aa_isoform_user": "T",
            "aa_pos_canonical": "36",
            "aa_pos_isoform": "36",
            "glygen_canonical_ac": "P08697-1",
            "uniprotkb_isoform_ac": "P08697-2"
        },
        {
            "aa_canonical": "S",
            "aa_isoform_actual": "S",
            "aa_isoform_user": "S",
            "aa_pos_canonical": "37",
            "aa_pos_isoform": "37",
            "glygen_canonical_ac": "P08697-1",
            "uniprotkb_isoform_ac": "P08697-2"
        },
        {
            "aa_canonical": "S",
            "aa_isoform_actual": "S",
            "aa_isoform_user": "S",
            "aa_pos_canonical": "656",
            "aa_pos_isoform": "514",
            "glygen_canonical_ac": "P19827-1",
            "uniprotkb_isoform_ac": "P19827-2"
        },
        {
            "aa_canonical": "N",
            "aa_isoform_actual": "N",
            "aa_isoform_user": "N",
            "aa_pos_canonical": "658",
            "aa_pos_isoform": "516",
            "glygen_canonical_ac": "P19827-1",
            "uniprotkb_isoform_ac": "P19827-2"
        },
        {
            "aa_canonical": "T",
            "aa_isoform_actual": "T",
            "aa_isoform_user": "T",
            "aa_pos_canonical": "659",
            "aa_pos_isoform": "517",
            "glygen_canonical_ac": "P19827-1",
            "uniprotkb_isoform_ac": "P19827-2"
        },
        {
            "aa_isoform_actual": "",
            "aa_isoform_user": "",
            "aa_pos_isoform": "",
            "glygen_canonical_ac": "no canonical for , mapping not done",
            "uniprotkb_isoform_ac": "null"
        }
    ],
    "parameters": {},
    "status": "finished"
}
```

```
$ cat /data/shared/glygen//userdata/tst/jobs/95/output.tsv 
uniprotkb_isoform_ac	aa_pos_isoform	aa_isoform_user	aa_isoform_actual	glygen_canonical_ac	aa_pos_canonical	aa_canonical	warning	error
A6NJB7-2	3	T	T	A6NJB7-1	3	T		
A6NJB7-2	8	S	S	A6NJB7-1	8	S		
P08697-2	36	T	T	P08697-1	36	T		
P08697-2	37	S	S	P08697-1	37	S		
P19827-2	514	S	S	P19827-1	656	S		
P19827-2	516	N	N	P19827-1	658	N		
P19827-2	517	T	T	P19827-1	659	T		
				null				no canonical for , mapping not done
```

**Comment by pv47** [comment]
changes:
warning only for valid invalid input aa
no warning for empty aa
remove 'mapping not done' from error message

**Comment by pv47** [comment]
one warning message 
- 'incorrect input aa' for invalid input aa in warning column

four error messages
- invalid glygen accessions - invalid glygen accession
- missing input aa position - input position missing
- invalid input position (-ve or zero or non-integer) - invalid input position <aa_pos>
- invalid input position (pos > seq length) - input position <aa_pos> greater than sequence length
