### ISSUE TITLE
List of BCO fields to populate

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#57]
_**Filled in by @rykahsay programatically:**_
- provenance_domain.version
- io_domain.input_subdomain
- io_domain.output_subdomain
- execution_domain.script
- execution_domain.software_prerequisites

_**Filled automatically by biocomputeobject.org:**_
- object_id
- etag
- provenance_domain.created
- provenance_domain.modified

_**Fill by bco templates:**_
- spec_version
- provenance_domain.license
- provenance_domain.contributors
- extension_domain.extension_schema
- extension_domain.dataset_extension
- extension_domain.dataset_categories
- description_domain.pipeline_steps.name
- description_domain.pipeline_steps.step_number
- execution_domain.script_driver

_**Manually filled by @jeet-vora @kmartinez834 :**_
- provenance_domain.name
- provenance_domain.version
- provenance_domain.contributors
- usability_domain
- description_domain.keywords
- description_domain.pipeline_steps.description
- description_domain.pipeline_steps.input_list
- description_domain.pipeline_steps.output_list

**Comment by rykahsay** [comment]
Editted top part

**Comment by kmartinez834** [comment]
#171
