### ISSUE TITLE
Process Genomics England

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#570]
Process Genomics England data

Path: `/data/projects/glygen/downloads/genomics_england`

FYI @jeet-vora

**Comment by rykahsay** [comment]
check

**Comment by JingyueWu** [comment]
Checked, I think this looks good. Closing this ticket. 

<img width="891" alt="Screen Shot 2023-08-18 at 4 20 09 PM" src="https://github.com/glygener/glygen-issues/assets/61590108/b499b070-ed2c-4214-a004-f8ee7132e8be">
