### ISSUE TITLE
Create pagination webservice

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#572]
For server side paginated tables the details webservice (glycan, protein etc.) will deliver the first batch of data to be displayed. If the user clicks on next page (etc.) a new batch needs to come from the server. In #245 we decided to have a single service for all tables that takes a pagination object:
```
        {
            "table_id": "glycosylation_with_glycans",
            "offset":1,
            "limit":20,
            "sort": "key",
            "order":"asc",
        }
```
And based on the table_id and the other values delivers the next batch of data.

**Dependencies**:
* #244 
* #245 
* #521 

**Blocker for**:
* #247

**Comment by rykahsay** [comment]
Here is the example queries and the webservice

https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/pagination/protein.json
https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/pagination/glycan.json
https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/pagination/publication.json


<img width="632" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/79140146-5580-43f9-a6ca-a1b1385743a7">
