### ISSUE TITLE
Combined data property for amino acid and position

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#573]
For the server side pagination (see #572 and #246) the backend needs to be able to sort data exactly the way the frontend does. A problem are joined columns (e.g. Residue column in Glycosylation and Phosphorylation table). Currently the backend delivers two properties "amino acid" and "position". The frontend make one sort-able property out of it (e.g. "Asn220"). Since you can not sort your JSON objects by two properties we need to add a new joined data property to the objects that mimic what frontend did so far.

@sujeetvkulkarni once this property is added we should use it for the display rather than building it ourselves in the frontend.

**Comment by rykahsay** [comment]
Added -- the property name is site_lbl -- also available for phosphorylation, snv

<img width="605" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/616126be-b8f8-46c9-abd8-415540a885ec">
