### ISSUE TITLE
Add biomarker data to publication and motif details webservice

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#574]
Similar to #475. The basic biomarker information needs to be added to publication and motif details webservices. @kmartinez834 placed example files in generated/misc folder and you can also see the [mockups](https://docs.google.com/presentation/d/14vJ_o_fq6b0UR2DTgs0NhATl-C3uiPVN68wGLQnejq4/edit#slide=id.g25249709de5_0_26).

**Blocker for**
* #476

**Comment by rykahsay** [comment]
<img width="600" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/b9363e12-cffa-480a-9e89-5e75065e184b">


<img width="693" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/46018fa2-e7c0-42a2-863a-2617a1e348ac">
