### ISSUE TITLE
Update glycan and protein search init to allow Biomarker type dropdowns in the advance searches

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#576]
The glycan and protein advanced searches should support searching by biomarker type. E.g. All, diagnostic, monotiring, prognostic, predictive, risk. The init Ws needs to provide this information to the frontend. @kmartinez834 placed example files in generated/misc folder and you can also see the [mockups](https://docs.google.com/presentation/d/14vJ_o_fq6b0UR2DTgs0NhATl-C3uiPVN68wGLQnejq4/edit#slide=id.g25249709de5_0_26).

**Blocker for**
* #476

**Comment by rykahsay** [comment]
screenshots for

- protein search init
- glycan search init


<img width="458" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/9851c883-936e-4ee3-a85b-63eb99312b5c">
<img width="429" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/f60fd84f-0f83-4088-822b-71e0ec4a4f31">
