### ISSUE TITLE
Update glycan and protein search to support biomarker type

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#577]
See #576. The search for glycan or protein needs to support search by biomarker type. That needs to be implemented in the search logic as well as be provided in the "cache_info". 

**Blocker for**
* #476

**Comment by rykahsay** [comment]
screenshots for

- protein search init
- glycan search init
- protein search
- glycabn search


<img width="458" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/9851c883-936e-4ee3-a85b-63eb99312b5c">
<img width="429" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/f60fd84f-0f83-4088-822b-71e0ec4a4f31">
<img width="459" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/17f6abd5-ff54-479f-8709-d3d1ac0c1521">
<img width="472" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/7277108c-01fd-47a3-bc27-ca3666f8e86b">

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger @rykahsay 
Frontend will not get Id, name in the init webservice.

Also need typeahead and search option  for biomarker disease.

**Comment by rykahsay** [comment]
Done, examples for /typeahead/typeahead/ API:

https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/typeahead/biomarker_id.json
https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/typeahead/biomarker_name.json
https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/typeahead/biomarker_type.json
https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/typeahead/biomarker_disease_id.json
https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/typeahead/biomarker_disease_name.json
