### ISSUE TITLE
Update filter list for protein and glycan list page to support filtering by biomarker type

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#578]
Protein and glycan list pages should have a filter option by biomarker type. The list web services for glycan and protein should be updated to support such a search filter.

**Blocker for**
* #476

**Comment by rykahsay** [comment]
<img width="753" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/a742959f-45b8-4845-bbb5-2c19c151ccd6">
