### ISSUE TITLE
Create script to make changes to GlyGen Wiki

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#58]
Primary use case: Add hyperlinks to all xrefs on [Glycan Structure Dictionary Wiki](https://wiki.glygen.org/Glycan_structure_dictionary) page

Ex. 
![image](https://user-images.githubusercontent.com/90285371/219451494-5f000c61-9a4a-470b-a432-67ded83a5e0e.png)

**Comment by rykahsay** [comment]
This ticket is not clear -- which file is this on the dev/tst/prd server?

**Comment by kmartinez834** [comment]
Ticket is obsolete
