### ISSUE TITLE
RefSeq cross reference data missing in current EBI downloads

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#582]
Look at these triples that existed on older download but not in current. Please report this to Pretty and fix it quickly.

<img width="1327" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/2908ba2a-7a5f-41e5-9119-febe85686166">

**Comment by jeet-vora** [comment]
@pkay47 Please look into the issue and let us know why the RefSeq xrefs are missing. It is a priority.

**Comment by rykahsay** [comment]
@pkay47  ... just want to make sure you are working on this! This is a blocker and I am running out of time for the upcoming release...

**Comment by pv47** [comment]
@rykahsay from history of (sample protein) P0DTC1, refseq x-ref was removed. 

![image](https://github.com/glygener/glygen-issues/assets/7321403/e7a8a3af-7781-4126-97a8-2774ec3661d4)

This is a reviewed entry, so curator may have updated this. I will check with team on monday to get more info on this.

**Comment by jeet-vora** [comment]
@pkay47, @rykahsay is patching using older version sarscov2 data for RefSeq. No need to create a new file with manual additions. 

Please reach out to PIR for the status when the issue will be resolved at their end.

**Comment by pv47** [comment]
thank you @jeet-vora. 

I will update NT for 2023_04 & 2023_05, until source gets fixed in 2024_01

**Comment by jeet-vora** [comment]
RefSeq data is manually getting added. By 2024_01 (Jan 17) release PIR will reshare the data with EBI. 

Comeback to the issue during Jan 2024

**Comment by pv47** [comment]
Still missing from PIR in 2024_02. Emailed PIR. 
Will check in 2024_03 glygen

**Comment by pv47** [comment]
Updated manually in 2024_03 dataset.

Data from PIR available in 2024_04
