### ISSUE TITLE
Search logic for protein disease search (after Biomarker update)

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#584]
With the biomarker changes (see #577) there will be three disease input fields on the protein advanced search page:
1. Disease name
2. Disease ID
3. Biomarker disease name

If 1 or 2 are entered all disease related fields (including the biomarker disease field and synonyms should be addressed. However, if 3. is entered only the biomarker disease field and synonyms will be searched. All other disease related to the protein will be ignored.

**Comment by rykahsay** [comment]
Done, please use these example queries:

>> /protein/search
https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/protein/search_by_biomarker_id.json
https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/protein/search_by_biomarker_name.json
https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/protein/search_by_biomarker_type.json
https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/protein/search_by_biomarker_disease_id.json
https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/protein/search_by_biomarker_disease_name.json
https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/protein/search_by_disease_name.json

The last one shows the old search using "disease_name" now targets the biomaerkers.disease property



>> /glycan/search
https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/glycan/search_by_biomarker_id.json
https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/glycan/search_by_biomarker_name.json
https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/glycan/search_by_biomarker_type.json
https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/glycan/search_by_biomarker_disease_id.json
https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/glycan/search_by_biomarker_disease_name.json
