### ISSUE TITLE
Serverside pagination support for other details pages

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#587]
Currently we do not have an tables selected for server side pagination of:
* Site
* Motif
* Biomarker
pages. To be consistent we should still implement the support on all pages. Add the `section_stats`. I dont think we need to preemptively implement server side pagination for all table. We can do this step by step if more large datasets get added.

**Comment by rykahsay** [comment]
Done:

/motif/detail/?query=QRY_OBJ
/site/detail/P02724-1.52.52/?query=QRY_OBJ
/biomarker/detail/?query=QRY_OBJ

Example queries
https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/motif/detail.json
https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/site/detail.json
https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/biomarker/detail.json
