### ISSUE TITLE
api.glygen.org no longer supports misc/gtclist API call...

### ISSUE THREAD

**Issue by edwardsnj** [glygener/glygen-issues#588]
The API call: https://api.glygen.org/misc/gtclist?query={} used to provide me a list of all GlyTouCan accessions ever used by GlyGen. This was so I could provide a list of retired accessions for y'all to use. There are now no API calls in the misc section of the swagger documentation and the server returns "METHOD NOT ALLOWED". I tried GET and POST methods. Please advise.

**Comment by edwardsnj** [comment]
Actually I take it back - it appears to need "{}" as a payload and a POST request. Except now I get a PROXY_ERROR after it hangs for a bit...

**Comment by rykahsay** [comment]
I have tried to fix it and both of the calls given below should work:

https://api.glygen.org/misc/gtclist/
https://api.glygen.org/misc/gtclist/?query={}

**Comment by edwardsnj** [comment]
Great, thanks.
