### ISSUE TITLE
Status of 2.2 Downloads

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#589]
**Status of resources to be downloaded for 2.2:**

Protein
--------
- [x] EBI (open issue with downloads)
- [x] Refseq
- [x] OMA
...

Proteoform
--------
- [x] GlyConnect
- [x] CarbBank
- [x] BiomarkerKB
...

Glycan
--------
- [x] Nathan's export
- [x] ChEBI
- [x] Reactome

Other
--------
- [x] Cellosaurus

**Comment by rykahsay** [comment]
I guess you can close this

**Comment by JingyueWu** [comment]
This task is completed.
