### ISSUE TITLE
Need to change interface into table with one protein id per row for server side pagination.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#591]
For server side pagination in Referenced Proteins card on publication details page we need to use table. Need to show one protein id per row. Should we add any additional columns into that table? 
https://www.glygen.org/publication/PubMed/24090084#Referenced-Proteins

<img width="859" alt="Screenshot 2023-08-01 at 12 03 29 AM" src="https://github.com/glygener/glygen-issues/assets/13891482/675bcf57-317c-41f3-9c88-311da03156a4">

**Comment by ReneRanzinger** [comment]
We could make it similar to the "Associated Protein" table on Glycan page:
* Protein name
* UniProtKB accession
* Gene name
* Organism

@jeet-vora what do you think?

**Comment by jeet-vora** [comment]
@sujeetvkulkarni and @ReneRanzinger 
We need to show what Rene has suggested above in the table. So there will be one protein ac on one row with all the information, in the table, which can be downloaded.

**Comment by ReneRanzinger** [comment]
Robel will implement this as part of:
* #593 

@sujeetvkulkarni once this is done make the frontend changes.

**Comment by sujeetvkulkarni** [comment]
436db692d833be9f83508e62f3beb347accf6b75
done.
