### ISSUE TITLE
Referenced Protein (Publication details) changes for serverside pagination

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#593]
According to #591 we need to change the publication details API. Currently we get referenced proteins as a list of IDs. We will change the display to have a table with the following columns:
* Protein name
* UniProtKB accession
* Gene name
* Organism

The API needs to be changed to include a list of referenced protein **objects** that have these 4 properties.

**Comment by rykahsay** [comment]
Done,

<img width="632" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/7ace7389-9267-41e9-a058-e6aed6e6adbd">
