### ISSUE TITLE
Improve planning for GlyGen data update

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#594]
Karina/Jeet --> give Rene table/timeline of development phase (downloads/update bcos/checking datasets) 

    downloads --> Nathan export --> Robel dataset generation --> QC and checks of datasets --> BCO tasks 

Make it as simple or fine granular as you think its useful. Add time estimation (number of days or should be done after the first week of new development cycle).

**Comment by jeet-vora** [comment]
@kmartinez834 This is my take on time estimates in days for the data update. Feel free to change the text. We can discuss this in the Wednesday meeting.

@JingyueWu FYI

| Type               | Phase                 | Task            | Days   | Dependency/Comments                                                                                          |
| ------------------ | --------------------- | --------------- | ------ | ------------------------------------------------------------------------------------------------------------ |
| Protein/Proteoform | Development           | Donwloads       | 3      | Dependent on EBI data (can cause delay if waiting for latest release, changes in the script for new organism |
| Protein/Proteoform | Development           | Pre-processing  | 1      | Making changes in masterlist, other misc files, tickets for Robel                                            |
| Protein/Proteoform | Development           | Manual curation | 2      | Some datasets for new organisms have to be manually curated (GT GH)                                             |
| Protein/Proteoform | Development           | Processing      | 2 or 3 | Robel depends on downloaded files, tickets and changes in misc files                                         |
| Protein/Proteoform | Development & Testing | QC checks       | 7      | Continous process, manual checks, automated checks                                                           |
| Protein/Proteoform | Testing | BCO edits       | 4      | BCO for new organisms, changes in exisiting BCOs                                                             |
|                    |
| Glycan             |   Development                    | Donwloads       |    1    |                                                                                                              |
| Glycan             |     Development                  | Nathan's Export  |    1    |  Nathan is dependent on proteoform and protein downloads, then need to wait for Nathan to push new release.  Once release is ready, download is quick to complete.
| Glycan             |       Development                | Processing      |    1-2    |   Robel depends on downloaded files, tickets and changes in misc files                                                                                                           |
| Glycan             |          Development & Testing             | QC checks       |   3     |    QC, then iteration if any changes are required                                                                                                           |
| Glycan             |    Testing                   | BCO edits       |   2     |    BCO for new organisms, changes in exisiting BCOs                                                                                                          |

**Comment by ReneRanzinger** [comment]
@jeet-vora For my understanding. QC checks happen before or after Robel integrates the data?

**Comment by jeet-vora** [comment]
@ReneRanzinger The QC checks are for the datasets (not data on portal) that Robel generates in the processing step. 
We do quick checks for the downloaded data once the downloads have completed.

**Comment by kmartinez834** [comment]
@jeet-vora @ReneRanzinger I updated the table.  Also changed protein/proteoform QC check to 7 days.  Glycan QC check is 3 days.  We usually spend ~2 weeks iterating with @rykahsay once he creates the datasets.
