### ISSUE TITLE
Idea collection for Flybase collaboration

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#596]
Create a Sharepoint file for collect ideas for the Flybase collaboration. Add an example URL to the file and share it with the following people.

@rajamazumder, @mtiemeyer0919, @ReneRanzinger and @jeet-vora should go over the page and add to the file:
* which of the Flybase data would we like to have in GlyGen
* which information in GlyGen could be added to Flybase (existing section, new section)
* beyond the Xref section how can we improve the linking between both resources.

**Comment by ReneRanzinger** [comment]
From @jeet-vora:
Please take a look at the [FlyBase Document](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Outreach/Collaboration/FlyBase.docx?d=w26cd6a4950554f738cba4b1f2f3519be&csf=1&web=1&e=FSFnPx) I have prepared for data collaboration on these three points, plus the GlyGen links in FlyBase (linkout)
- Which of the Flybase data would we like to have in GlyGen 
- Which information in GlyGen could be added to Flybase (existing section, new section) 
- Beyond the Xref section, how can we improve the linking between both resources.

**Comment by ReneRanzinger** [comment]
I added some ideas to each section and a few comments to existing ideas. We also need to confirm with them about their payment model (see general section of the [document](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B26CD6A49-5055-4F73-8CBA-4B1F2F3519BE%7D&file=FlyBase.docx&action=default&mobileredirect=true)).

**Comment by ReneRanzinger** [comment]
@jeet-vora: If @mtiemeyer0919 has time, he will review the document today or tomorrow. On Friday we should freeze the SharePoint file and make it a google doc. We can share this google doc as basis for the discussion with the Flybase people.

**Comment by jeet-vora** [comment]
FInal shared document - https://docs.google.com/document/d/11fmBPX-9Bwg7pkMFQJ25JToVygNN8qLx/edit?usp=sharing&ouid=111753837931198813258&rtpof=true&sd=true
