### ISSUE TITLE
BCO extension domain http to https

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#597]
Robel can you change http to https in extension_schema URL for all draft bco's
            “extension_schema”: `“http://www.w3id.org/biocompute/extension_domain/1.2.0/dataset/dataset_extension.json”,`

The BCO portal generates an error and does not let edit the extension domain if the protocol is not set to https.

eg https://biocomputeobject.org/builder?https://biocomputeobject.org/GLY_000142/DRAFT

![image](https://github.com/glygener/glygen-issues/assets/25825266/5111b8da-0549-4ef6-b620-8f986b403019)

**Comment by rykahsay** [comment]
Instead of fixing at the draft level, I will be fixing it when I make release BCOs.

**Comment by jeet-vora** [comment]
Done
