### ISSUE TITLE
GlyConnect Xrefs missing in Protein Xrefs and Protein Mapper tool

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#60]
The Glyconnect Xref is missing from the protein xref section and Mapper tool.

Please create the glyconnect xrefs for the below species in the protein xrefs and also add the xrefs to the protein mapper tool. The Glyconnect mapping is present in the "src_xref_id" field.

Files have been added to masterlist and xref is already in the xref_info.csv under misc. _https://glyconnect.expasy.org/browser/proteins/%s_

human
mouse
rat
sarscov2

**input files**
sarscov2_proteoform_glycosylation_sites_glyconnect.csv
rat_proteoform_glycosylation_sites_glyconnect.csv
mouse_proteoform_glycosylation_sites_glyconnect.csv
human_proteoform_glycosylation_sites_glyconnect.csv

watcher @JingyueWu

**Comment by rykahsay** [comment]
Check these datasets first and reassign the ticket to me if they are ok

<img width="1367" alt="image" src="https://user-images.githubusercontent.com/20584876/222592439-12ea5d63-55c8-4133-93ef-e9181b59b953.png">

**Comment by jeet-vora** [comment]
checked no issues

**Comment by rykahsay** [comment]
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/20584876/225426933-8f57b22f-8807-48f6-8de9-3c53e7382456.png">

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/20584876/225427368-fae60766-09ae-4219-a0f1-35708e43682d.png">

**Comment by jeet-vora** [comment]
Checked no issue
