### ISSUE TITLE
Review GAG classifiers

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#602]
At some point we will have to review the [GAG classifiers](https://glycomotif.glyomics.org/glycomotif/GlyGen_Classification_Motifs). I see two tasks there:
* It would be good to have subclasses for GAG such as Heparin, Chondroiten, Heparan. The motifs are there.
* [GGM.001213](https://glycomotif.glyomics.org/glycomotif/GGM.001213) matches [G00087BT](https://glytoucan.org/Structures/Glycans/G00087BT) (Core, strict). That is desired and correct I just dont understand why? The Motif has a 2NS but that queried structure does not match does in any place. I understand additional S would be permitted under non-strict rule, but missing substituents?

**Comment by edwardsnj** [comment]
@ReneRanzinger Second point - I don't understand - it appears to match correctly at the core. I'm wondering if there used to be an old (bad) image for that accession and now it is correct with a 2S on the monosaccharide at the reducing end?

First point - I agree it would be nice. I implemented Keratan sulfate as a GAG subtype but for the rest I couldn't pin down a definition. Just the core motif matching was not enough for the Keratan sulfate subclass, there were a bunch of additional heuristics needed. Similar heuristics could be defined for the other specific GAGs.

**Comment by ReneRanzinger** [comment]
@edwardsnj I dont see the second problem anymore. Either it was one of the tickets I made late at night and I was too tired and was not thinking clearly ... or it was an old image issue.
