### ISSUE TITLE
Banner for GlyGen webinar

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#603]
Add a banner for production and beta:

Headline: GlyGen Webinar with Dr. Manfred Wuhrer
Text: Mass spectrometry glycomics of tissues and biofluids
Link: https://wiki.glygen.org/GlyGen_Webinar_Series

You can take date and time from the wiki. Banner can be active right now till the talk.

@jeet-vora let us know if we need to update something.

**Comment by jeet-vora** [comment]
Looks good, no update required.

**Comment by sujeetvkulkarni** [comment]
Ok, I will go ahead and add the banner.

**Comment by sujeetvkulkarni** [comment]
done. please check.

**Comment by ReneRanzinger** [comment]
Its not working on beta.

**Comment by sujeetvkulkarni** [comment]
for beta blocked due to beta login api fails #610

**Comment by sujeetvkulkarni** [comment]
done.
