### ISSUE TITLE
Gene and Drug Landing Page Aggregator in tools

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#605]
Add a new menu entry in tools:
* Above "Other Resources" add "Third Party Tools"
* Add another separation line between "Other Resources" and "Third Party Tools"
* Add a submenu entry "[Gene and Drug Landing Page Aggregator](https://cfde-gene-pages.cloud/)" for "Third Party Tools"

Currently we do not have 3rd level menu entries. We have to see if that is properly supported.

**Comment by sujeetvkulkarni** [comment]
b87bbd28a6d406a0e31f029f42330ced553cbce5
