### ISSUE TITLE
Invite Weston Struwe for a talk in webinar series

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#609]
After we confirmed #608.

**Comment by ReneRanzinger** [comment]
I hope you are doing well. At the Beilstein meeting we talked about our GlyGen seminar series and the possibility for you to give a talk about your work. We have a monthly GlyGen Webinar series, usually on the first Tuesday of the month, to which we invite people to give a talk about their research, approx. 30-40 minutes to help our team understand more about their work.  The webinars are also publicized more generally through various listservs (SfG, eX-twitter etc.) and have been drawing reasonably broad audiences. 

Usually, the seminar is recorded, and the recordings are released on our YouTube channel. We've had Harry Brumer, Rebekah Gundry, Chris West, Stacy Malakar, Bob Haltiwanger, and Lingjun Li give talks. And a talk from Manfred Wuhrer is coming up next Tuesday.

I would like to invite you to give a talk at our seminar and I wonder whether you might be available some time middle to end of January. The talks are usually at 10:00 AM US Eastern Time.  The topic can be anything of interest to you. The audience for these meetings is comprised of the GlyGen team and few other bioinformaticians but also many glycobiologist that we reach via SfG and other outreach.

Talks are usually followed by another meeting to discuss collaboration and data exchange between the GlyGen project and the speakers. One topic that is of interest to us is your Covid data which would be a great addition for GlyGen. We would have to talk about how (which format) we can use to integrate this and any other data. Of course, any interest from your side on GlyGen data or suggestions for improvement of the database that might help you, are very welcome.
 
I've copied Jeet Vora onto this email.  He is part of Raja Mazumder's data team at George Washington University, and he is the organizer of the GlyGen seminar series. 
 
Let me know if you have any questions or if you prefer a date later in 2024.

**Comment by ReneRanzinger** [comment]
Hi Rene,

I was travelling and completely missed your email (really sorry)- Yes, happy to give a talk. This year may be a little tight with teaching/grants. Is it alright to do this in 2024?

Best wishes,
Weston

**Comment by ReneRanzinger** [comment]
Hi Weston,

no problem. I figured the email was pushed down due to holiday or travel. We are thinking about middle to end of January 2024. If you prefer a date later 2024 let us know. Jeet (copied in) is coordinating the seminar series. He will contact you about title, abstract and so on. He will also work with you to find a date that works.

Thank you for agreeing to give a talk,
  René

**Comment by jeet-vora** [comment]
Weston hasn't responded yet for February Talk.
