### ISSUE TITLE
Setup meeting with Vijay (initial year 2 meeting)

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#611]
Hi Vijay,

We'd like to set up a meeting to discuss Lit Mining Year 2 plans and current issues/questions.  Are you available for a 1 hour call the week of Aug 28th, either Thursday or Friday afternoon?

The proposed agenda is [here](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Meetings/Literature%20Mining/Lit_mining_agenda.docx?d=w25bd87ad6f0b40b3aec7d806c1c8b87b&csf=1&web=1&e=PYnyh1) on Sharepoint, feel free to add any new items.  You should already have access, but let me know if you have issues.

Best,
Karina

**Comment by kmartinez834** [comment]
Meeting has been scheduled for Thu Sep 14, 2023 3pm - 4pm
