### ISSUE TITLE
referenced_glycans table id in publication page needs some sort key.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#612]
referenced_glycans entry needs a sort key to sort the array on server side.
https://api.tst.glygen.org/publication/detail

```
    "referenced_glycans": [
        "G00912UN",
        "G01367ZS",
        "G01650EU",
        "G02815KT",
        "G02860WV",
        "G02886BB",
        "G03574QJ",
        "G03930BU",
        "G04595ZA",
        "G04784US",
        "G06704MH",
        "G07799LX",
        "G08293MJ",
        "G08520NM",
        "G09197ZW",
        "G09394JN",
        "G09635US",
        "G09775CH",
        "G10339FR",
        "G10486CT"
    ],
```

**Comment by rykahsay** [comment]
But this is just a simple list not a list of objects and cannot have a sort field

**Comment by sujeetvkulkarni** [comment]
@rykahsay But we still need to sort it by order, ascending and descending. How we can do that without sort field?

**Comment by rykahsay** [comment]
... just don't send sort field, send only order 

###  screenshots of query and response for order=asc
<img width="453" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/1d90f097-2846-4940-a479-e7fde2bd08e3">
<img width="292" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/7a683d94-cca2-451f-9318-a7e8317c886e">

### screenshots of query and response for order=desc
<img width="455" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/3e620938-2d0a-4698-b1f0-75a95eed9135">
<img width="358" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/cf82da31-a35f-40d6-b71e-b83b39144636">

**Comment by sujeetvkulkarni** [comment]
@rykahsay is it ok if we send empty "" sort field or some other value? Instead of not sending it. Looks like current implementation works even if if send some sort field instead of not sending it.

**Comment by sujeetvkulkarni** [comment]
@rykahsay need to convert referenced_glycans list into list of objects like below and  "glytoucan_ac" should be accepted as sort field in both https://api.tst.glygen.org/publication/detail and  https://api.tst.glygen.org/pagination/page/ APIs for "referenced_glycans" table id .

```
"referenced_glycans": [
        {
            "glytoucan_ac": "G00912UN"
        },
        {
            "glytoucan_ac": "G01367ZS"
        },
        {
            "glytoucan_ac": "G01650EU"
         },
        {
           "glytoucan_ac": "G02815KT"
        }
    ],
```

**Comment by rykahsay** [comment]
Please try now

**Comment by rykahsay** [comment]
please try now

**Comment by sujeetvkulkarni** [comment]
131f463d9b67eb444032b60bf2c03228d3d05143
