### ISSUE TITLE
need to define sort keys for columns of snv_non_disease and snv_disease table.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#613]
need to define sort keys for columns of snv_non_disease and snv_disease table.
Both protein details and table pagination api should support these sort keys.

**Comment by rykahsay** [comment]
I am giving list of fields that can be used for sorting (with each table_id in the section stats) 

<img width="555" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/357b5989-6aaf-4b5d-b92e-a7f3f68c0424">

**Comment by sujeetvkulkarni** [comment]
API : https://api.tst.glygen.org/pagination/page/

For table snv_disease,
If we sort by keys "comment", "chr_id", "chr_pos", "start_pos", "end_pos", "sequence_org", "sequence_mut", minor_allelic_frequency
we get empty "results": [] array.

```
{
  "record_type": "protein",
  "table_id": "snv_disease",
  "record_id": "P14210-1",
  "offset": 1,
  "limit": 20,
  "order": "desc",
  "sort": "comment"
}

{
    "query": {
        "record_type": "protein",
        "table_id": "snv_disease",
        "record_id": "P14210-1",
        "offset": 1,
        "limit": 20,
        "order": "desc",
        "sort": "comment"
    },
    "results": []
}
```

For table snv_non_disease,
If we sort by keys "comment", "chr_id", "chr_pos", "start_pos", "end_pos", "sequence_org", "sequence_mut", minor_allelic_frequency
we get empty "results": [] array.

```
{
  "record_type": "protein",
  "table_id": "snv_non_disease",
  "record_id": "P14210-1",
  "offset": 1,
  "limit": 20,
  "order": "desc",
  "sort": "comment"
}

{
    "query": {
        "record_type": "protein",
        "table_id": "snv_non_disease",
        "record_id": "P14210-1",
        "offset": 1,
        "limit": 20,
        "order": "desc",
        "sort": "comment"
    },
    "results": []
}
```
Backend need to send results even in case a sort column has no values in it and user sorts it.

**Comment by rykahsay** [comment]
Try now

**Comment by sujeetvkulkarni** [comment]
Looks like after sorting snv_disease, snv_non_disease tables with different sort fields - "comment", "chr_id", "chr_pos", "start_pos", "end_pos", "sequence_org", "sequence_mut", minor_allelic_frequency the result array is not empty but is not getting sorted with the field and order specified.

API: https://api.tst.glygen.org//pagination/page/

```
{
  "record_type": "protein",
  "table_id": "snv_disease",
  "record_id": "P14210-1",
  "offset": 1,
  "limit": 20,
  "order": "desc",
  "sort": "start_pos"
}
```

```
{
  "record_type": "protein",
  "table_id": "snv_non_disease",
  "record_id": "P14210-1",
  "offset": 1,
  "limit": 20,
  "order": "asc",
  "sort": "end_pos"
}
```

result array order does not change with different sort fields and order.

**Comment by rykahsay** [comment]
Please try now

**Comment by sujeetvkulkarni** [comment]
done.
