### ISSUE TITLE
URGENT: Mouse/Rat inconsistency in UniCarbKB data...

### ISSUE THREAD

**Issue by edwardsnj** [glygener/glygen-issues#615]
I'm reprocessing UniCarbKB data (I redid this approach to accommodate the large number of inconsistently formatted files for this datasource). I assumed that if the species value is provided, I should use it to assign taxid. However, this produces inconsistent results w/ GlyGen's Mouse UniCarbKB dataset: https://data.glygen.org/GLY_000041

GlyGen scripts appear to use the UniProt accession as the primary indicator of species, rather than the species value. I believe that my code did that too, until the recent change. I assumed it would be more reliable (because species wasn't specified sometimes). 

Here is an example: The GlyTouCan accession G09528DL in this dataset has two annotations to the UniProt accession Q640R3 (a mouse protein). However, the original file https://data.glygen.org/ln2data/downloads/unicarbkb/current/known_legacy_human_mouse_rat_glygen.csv has a species column which says Rattus novegicus and the paper cited: https://pubmed.ncbi.nlm.nih.gov/34106099/ is clearly about rats. 

The other UniCarbKB file known_34106099_glygen has the same issue (same pubmed id, too). 

I'm not (yet) sure how many cases there are of this kind of inconsistency. A potential short list (based on mouse) using species before UniProt accession - considered mouse by UniProt accession, not species value: G09528DL, G12580WI, G59626AS, G67324HN, G72961RM, G81572SC, G92050GC, G27919IH; considered mouse by species value, not be UniProt accession: G58667NI, G71142DF, G78059CC, G80858MF. I have only investigated the first accession G09528DL carefully. 

I'm going to re-process the GlyGen data-release to attempt to match your UniProt accession first strategy, but as you can see above, this results in at least one data correctness issue.

**Comment by ReneRanzinger** [comment]
@edwardsnj its off topic, but what is the purpose of this ticket? Just information or are you requesting to discuss this in one of the Wednesday meetings? It also does not have a date (Label) or milestone assigned. Will it effect 2.2 or the next release?

**Comment by rykahsay** [comment]
@kmartinez834 @jeet-vora, please follow the steps shown below to get list of such discrepancies. On our end, all glycosylation datasets are separated into species specific files ($species_proteoform_**.csv) where $species is derived based on the organism the uniprot accession belongs to.

```
$ cd /software/glygen/
$ python dump-unicarbkb-species-annotation-mismatch.py
$ head logs/unicarbkb_species_annotation_mismatch.csv 
```
The last command will give you:

```
"uniprotkb_ac","species_unicarbkb","species_from_uniprotkb_ac","pmid"
"Q91ZX7","rat","mouse","34106099"
"Q8BLQ9","rat","mouse","34106099"
"Q00493","rat","mouse","34106099"
"Q9CPW0","rat","mouse","34106099"
```

This means, the task is to look at referenced papers (PMIDs) and find out which assignment is wrong in rows given in the output file logs/unicarbkb_species_annotation_mismatch.csv.  I have tried to look into the first case (first row). The paper (PMID=34106099) seems to be on rat but the mouse uniprot accession (Q91ZX7) is listed on one of the supplementary tables (see screenshot below) which gives identification results. In my opinion, this is misleading if the experimental sample analyzed in the paper is not from mouse.

<img width="1046" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/ea047baa-2c5b-491f-af5a-e125227f66cf">

**Comment by rykahsay** [comment]
And these are all the cases, it is not too bad.
```
"uniprotkb_ac","species_unicarbkb","species_from_uniprotkb_ac","pmid"
"Q91ZX7","rat","mouse","34106099"
"Q8BLQ9","rat","mouse","34106099"
"Q00493","rat","mouse","34106099"
"Q9CPW0","rat","mouse","34106099"
"Q9R1V6","rat","mouse","34106099"
"Q640R3","rat","mouse","34106099"
"Q05186","rat","mouse","34106099"
"Q9WV18","rat","mouse","34106099"
"Q8R4G0","rat","mouse","34106099"
"Q6AXF6","rat","mouse","34106099"
"P20917","rat","mouse","34106099"
"Q9WTR5","rat","mouse","34106099"
"Q6PHU5","rat","mouse","34106099"
"Q9QUR8","rat","mouse","34106099"
"P70408","rat","mouse","34106099"
"Q05909","rat","mouse","34106099"
"P97952","rat","mouse","34106099"
"Q6PHS9","rat","mouse","34106099"
"Q6P9K9","rat","mouse","34106099"
"Q7TNR6","rat","mouse","34106099"
"Q9WV91","rat","mouse","34106099"
"Q80ZF8","rat","mouse","34106099"
"Q8BGU2","rat","mouse","34106099"
"P0DTC2","human","sarscov2","34004174"
"P0DTC2","0","sarscov2","32363391"
```

**Comment by rykahsay** [comment]
@kmartinez834 can you please read the article 34106099 carefully and confirm the material/sample was taken only from rat and not from mouse? After you confirm, please re-assign the ticket back to me and I will filter out those mouse accessions associated with  34106099 when I make the mouse_proteoform_*glycosylation_sites_unicarbkb.csv datasets.

**Comment by jeet-vora** [comment]
@rykahsay The paper 34106099 purely focuses on **rat** and not on mouse. The incorrect assignment of the species in the supplementary table can be as a result of Byonic and custom database. The peptides in the supplementary table have exact match in rat, mouse and human species.

This is what Materials and Methods says
`Each batch of synaptosomes was prepared from two eight to ten weeks old male Sprague-Dawley **rats** (Taconic) according to the protocol published by Dunkley et al.[10](https://pubs.rsc.org/en/content/articlelanding/2021/MO/D0MO00044B#cit10) Briefly, rats were decapitated and the brain excluding the cerebellum was immediately......`

Either we filter out the entries or we change the accessions with a comment in note field or contact the author/UniCarbKB to share corrected data.

**Comment by rykahsay** [comment]
The mouse entries has been removed from mouse_proteoform_glycosylation_sites_unicarbkb.csv and
mouse_proteoform_citations_glycosylation_sites_unicarbkb.csv. Please check

**Comment by kmartinez834** [comment]
Confirmed, entries from PMID:34106099 are no longer in these datasets.
