### ISSUE TITLE
Addition of GA4 properties to api.glygen.org

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#617]
GA4 is currently not tracking api.glygen.org as the properties have not been added.
Please add the GA4 properties like the other domains.

**Comment by rykahsay** [comment]
It is done on tst server now, please check if it is tracking and we will push changes to prd when we do 2.2 push
<img width="897" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/bc091fe7-54dd-4ba2-81e4-b6cd441c4e9a">

**Comment by jeet-vora** [comment]
Can see hits from tst.api.glygen.org. Will check again after a month.
<img width="923" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/2bcd00cd-c646-44b7-9926-78ae8d807123">
