### ISSUE TITLE
GlyGen Nodes and Edges

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#618]
Robel, I need to add the details of the total GlyGen's Nodes and Edges as well as for the individual property. Can you point me to the document/script where I can find the details.

**Comment by rykahsay** [comment]
Follow these commands on GlyGen dev server:

```
$ cd /software/glygen/
$ nohup python3 dump-triplestore-stats.py -v 2.1.1 &
```
When the last command finishes, run the following:

```
$ cat logs/triplestore_stats.txt
```
