### ISSUE TITLE
Intern workshop testimonials

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#619]
@JingyueWu collected the testimonials in a [document](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B6E0ED8B7-19C6-4259-AAF7-A16A426C1DA9%7D&file=GlyGen%20&%20CFDE%20Workshop%20Testimonials.docx=&action=default&mobileredirect=true) in SharePoint.

Rene reviewed it and marked the once that could be added to the wiki page.

@rajamazumder and @mtiemeyer0919 please review and also decide on the "naming" of the testimonials.

**Comment by ReneRanzinger** [comment]
I went over the list and marked the testimonials that I think we can add to the wiki page. Raja&Mike please review. There are a few spelling errors in there. I am not sure we want to fix them, because they are no longer "testimonials" if we "rewrite" them.

Regarding the naming:

A. Just the first name and no school.
B. Generic name "Internship student, Freedom High School" or "Workshop participant, Freedom High School"

I favor B.

**Comment by ReneRanzinger** [comment]
From @rajamazumder: 
I like  "Workshop participant, Freedom High School". I went to the link using my phone. Could not figure out which ones Rene marked. I am fine with what he an Mike chooses. For interns we can tag them as Summer 2023 Intern workshop organizer - x High School

@mtiemeyer0919 please have a look

**Comment by JingyueWu** [comment]
Status update: email sent. Once Raja reviews/replies, I will update it on the wikipage.

**Comment by ReneRanzinger** [comment]
@JingyueWu put them on the wiki and close the ticket.

**Comment by JingyueWu** [comment]
@ReneRanzinger Done: https://wiki.glygen.org/GlyGen_CFDE_Workshop_Summer_2023

Closing this ticket.
