### ISSUE TITLE
FYI: changes in biomarker data model and implications

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#620]
@sujeetvkulkarni @ReneRanzinger 

Please note the following changes based on our discussion with Karina:

### /biomarker/detail/
<img width="612" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/572562ef-161c-472e-95fd-12c89a2da429">

### /protein/detail/, /glycan/detail/ ...

<img width="647" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/1e045861-dfaa-4873-aac0-be10dddcdae6">

**Comment by sujeetvkulkarni** [comment]
Give us high level evidence for glycan, protein, publication, motif details page. 
On these pages in the current instances don't have evidence array.

**Comment by rykahsay** [comment]
<img width="510" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/67d777b6-5af0-46e3-9454-b8360c34a79e">
