### ISSUE TITLE
Protein & Glycan Xref categorization 

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#621]
Compile a list of categories that can be used for:
- Glycan details page
- Protein details page

We also need a strategy how aggregators fit into the Xref section.

Once we have the list @ReneRanzinger and @sujeetvkulkarni can think about how we display them (e.g. expandable lists).

**Comment by ReneRanzinger** [comment]
This is scheduled for the [group meeting on 8/23](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B3CD5C44B-0364-4992-BF1E-BA396AC54CBC%7D&file=2023.08.23.docx&action=default&mobileredirect=true)

**Comment by jeet-vora** [comment]
[GlyGen Xref Categorization](https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/Documents/glygen_xrefs.xlsx?d=wc84a5a4dddfb4f79853045d5a0d00e56&csf=1&web=1&e=HmGQJw)

**Comment by ReneRanzinger** [comment]
@JingyueWu and @jeet-vora will work on this document. @JingyueWu will add the missing cross references. @jeet-vora will review the categories. We also discussed that assigning a resources to multiple categories is OK. It will be the frontends problem to make sure its not to overwhelming to the user. @jeet-vora will also try to review his proposal with @rajamazumder to include his ideas and changes.

**Comment by JingyueWu** [comment]
Connected to issue #626

**Comment by ReneRanzinger** [comment]
@jeet-vora and @rajamazumder will meet online and finalize the list. We will review it in the weekly meeting 9/13.

**Comment by jeet-vora** [comment]
- [ ] Create a list of new xref dataset, create BCOs and update misc/xref_info.csv
- [ ] Create a file in misc having two columns `resource | category`

**Comment by ReneRanzinger** [comment]
@jeet-vora Also add for both (glycan and protein) an section for the databases with disabled links. Maybe `Inactive resources`.

**Comment by jeet-vora** [comment]
@rykahsay 

The `xref_categorization.csv` file has been created under `generated/misc`.
It has two columns `xref_dataset | xref_category`. 
Please note: A xref dataset can have more than one xref category which is separated by `|`.

**Comment by jeet-vora** [comment]
@sujeetvkulkarni 

The cross-reference section needs to have title which would consist of Xref category and below that would be a sub-title for Resource and then followed by linked IDs for the resource, in a hierarchy.
eg.
3D Structures - Title
PDB - Sub title
1PDB - Linked ID
2PDB - Linked ID

**Comment by rykahsay** [comment]
@jeet-vora 
It looks like you need to change the values for the first field (the first field should be the xref_key not the xref dataset name). 
This means, in  generated/misc/xref_categorization.csv, the following change has to happen:

From:  
glycan_xref_pubchem.csv,Chemical

To:
glycan_xref_pubchem_compound, Chemical
glycan_xref_pubchem_substance, Chemical

### what to do
I have created a script that will help you create an initial file (generated/misc/xref_categorization.csv-tmp) which you can edit to put the right categories. You don't need to run the script now since I have already created the file generated/misc/xref_categorization.csv-tmp for you (just edit it)


```
$ cd /software/glygen/
$ python3 dump-xref-categories.py > generated/misc/xref_categorization.csv-tmp
$ chmod 775 generated/misc/xref_categorization.csv-tmp
```

Now you can see the rows corresponding to pubchem
```
$ cat generated/misc/xref_categorization.csv-tmp | grep pubchem
glycan_xref_pubchem_compound,x|y
glycan_xref_pubchem_substance,x|y
```




Please run

**Comment by sujeetvkulkarni** [comment]
category needs to be collapsed - if possible. Just keep one category open by default - the first one and all others closed - Implement this feature only when we have a show all category button.
default category - Other Cross-References.

**Comment by jeet-vora** [comment]
@rykahsay Added categories to the file generated/misc/xref_categorization.csv-tmp. Please check

**Comment by rykahsay** [comment]
@sujeetvkulkarni ... crossref objects have a new property called "categories" now (objects are being loaded to mongodb now -- give it few hours and try it)


```
"crossref": [
        {
            "categories": [
                "Glycan"
            ],
            "database": "GlyTouCan",
            "id": "G18625KA",
            "url": "https://glytoucan.org/Structures/Glycans/G18625KA"
        },
        {
            "categories": [
                "Ontology and Dictionary"
            ],
            "database": "Glycan Structure Dictionary",
            "id": "GSD000096",
            "url": "https://wiki.glygen.org/Glycan_structure_dictionary#GSD000096"
        }
    ],
```

**Comment by sujeetvkulkarni** [comment]
Categorized databases on Cross Reference section of Protein and Glycan details pages.
GitHub: ddc6ed36ba93bd11ad0197a3a5d8ed84e4e827c2
