### ISSUE TITLE
Finalize new table format (glycomics)

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#622]
@Mindyporterfield will setup a meeting with @jeet-vora and @ReneRanzinger to finalize the new table format after Mike added more columns. Aim of the meeting is to identify the dictionaries to use for the new columns. 

@Mindyporterfield it seems you are no longer using the google doc file but made a local copy or a SharePoint copy. Share the link to the file here.

**Comment by Mindyporterfield** [comment]
I sent an email @ReneRanzinger and @jeet-vora to set a time monday or tuesday to meet. Once we have a mutually good time, I will schedule the zoom.

**Comment by Mindyporterfield** [comment]
https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B27A34C21-ADB9-4D85-A96D-4B7EB40A103A%7D&file=Mindy%20paper%20curation.docx&action=default&mobileredirect=true

**Comment by Mindyporterfield** [comment]
We (Mindy, Rene, Jeet) met and discussed and made changes to the format including changes to column order. The sheet is in sharepoint under documents/papercuration [CurationTable](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B27A34C21-ADB9-4D85-A96D-4B7EB40A103A%7D&file=Mindy%20paper%20curation.docx&action=default&mobileredirect=true) 
@ReneRanzinger @senaarpinar Can you please update the tool to produce the table in that order ?

**Comment by Mindyporterfield** [comment]
@jeet-vora 
the column "Glycan dictionary term ID " appears 2x, please delete 1
Columns in order are:
GlyTouCan ID 
Evidence 
Species  
Strain  
Tissue  
Cell line ID 
Disease  
Glycan dictionary term ID 
has_abundance 
has_expression 
Functional annotation/Keyword 
Experimental technique 
~~Glycan dictionary term ID~~
Variant 
Organismal/cellular Phenotype  
Molecular Phenotype 
Contributor

**Comment by senaarpinar** [comment]
I have updated the tool to add the missing columns. I kept the first Glycan dictionary term ID. If the order needs to change, please let me know.

**Comment by jeet-vora** [comment]
I have removed the one `Glycan dictionary term ID` from close to the bottom.
