### ISSUE TITLE
Curation documentation (wiki)

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#623]
Update the wiki page and describe: 
* the curation workflow (first read, drawing selection, Ains work, Senas tool, curation of the rest)
* Curation table (see #622)
* Curation rules

**Comment by Mindyporterfield** [comment]
[GlyGen Wiki (<https://wiki.glygen.org/Main_Page>)](https://wiki.glygen.org/Glycomics_paper_curation)

**Comment by Mindyporterfield** [comment]
https://wiki.glygen.org/Glycomics_paper_curation
