### ISSUE TITLE
Reinstall AWS instance

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#624]
Once the problem with the AWS payment is figured out we need to reinstall the GlyGen backend, frontend and data on AWS.

**Comment by rykahsay** [comment]
@jeet-vora please assign this ticket to me and Tianyi after you email Dacian and he switches on the instance

**Comment by jeet-vora** [comment]
Same as [#924](https://github.com/glygener/glygen-issues/issues/924) fo Luke
