### ISSUE TITLE
Try running the curation pipeline outside of GW network

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#625]
Since the current error with the pipeline could be related to GW blocking some external requests performed by the script it would be good to test the pipeline outside GW network. @rykahsay will try to run it on his notebook (from home without VPN) or his own AWS instance. 

**Note:** For running the docker containers on MAC you can use [docker desktop](https://docs.docker.com/desktop/install/mac-install/) that will install all dependencies and afterwards you can also run it on command-line even without GUI. 

If the problem persist it would mean its not related to the GW network but an issue with Vijays setup that is not documented and can not be reproduced. In that case Mike and Raja should meet with Vijay to ensure he understands that getting things to run on GW site is part of his task.

**Comment by rykahsay** [comment]
I tried to run the pipeline on my MacBook Pro and it fails at a step where one of the containers tries connect to the MongoDB on the host. I suspect the problem could be because the the warning it gives , which is:

"The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested"

When I tried to run the pipeline on my private AWS server, I run out of disk space because my AWS instance is a micro and has only 8GB space.

So, what do we do next? :)



This is what I get when I run it on my mac:
```
$ sh init_LitMining.sh   

litmining
Using default tag: latest
latest: Pulling from formulaone9275/glygen
Digest: sha256:0b19300cf93baeecc70f9e7db5d440148d8c3525568868dee8d68dad002f4213
Status: Image is up to date for formulaone9275/glygen:latest
docker.io/formulaone9275/glygen:latest

What's Next?
  View summary of image vulnerabilities and recommendations → docker scout quickview formulaone9275/glygen
litmining_init
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
mongodb://localhost:27017
Traceback (most recent call last):
  File "glygen.py", line 57, in <module>
    info = client.server_info()
  File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1658, in server_info
    session=session)
  File "/usr/local/lib/python2.7/site-packages/pymongo/database.py", line 655, in command
    read_preference) as (sock_info, slave_ok):
  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1135, in _socket_for_reads
    server = topology.select_server(read_preference)
  File "/usr/local/lib/python2.7/site-packages/pymongo/topology.py", line 226, in select_server
    address))
  File "/usr/local/lib/python2.7/site-packages/pymongo/topology.py", line 184, in select_servers
    selector, server_timeout, address)
  File "/usr/local/lib/python2.7/site-packages/pymongo/topology.py", line 200, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
```

**Comment by rykahsay** [comment]
Looks like the problem has been reproduced on their end as well.

<img width="1051" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/b9b40025-deac-4557-8a1c-f265afd9e1d5">

**Comment by ReneRanzinger** [comment]
@rykahsay It seems we are reading this differently. "I am getting the produced file generated on our machine". That sounds to me that he was running it with your PMIDs and got the result files as expected. He did not say anything about empty files.

**Comment by ReneRanzinger** [comment]
We did that and it resolved the problem.
