### ISSUE TITLE
Create a list of missing Databases on Protein Details Page Xref Section

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#626]
The task is to create a list of missing databases not in the cross-reference section on a protein details page.

<img width="861" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/5b720b09-ba81-443c-9365-377ef57bcb16">

Check all sections/buttons for Links. Use examples `P14210-1` and `P02649-1`.

For example, Ensembl Gene is missing from the cross-reference sections for any given protein having Ensembl Gene.

Add the Xrefs in Protein column in the sheet - [Missing Xrefs](https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/Documents/glygen_xrefs.xlsx?d=wc84a5a4dddfb4f79853045d5a0d00e56&csf=1&web=1&e=7LNR5w&nav=MTVfezRGRDgwN0Y0LTg1OUQtNEU0NS1BMjVFLUQxMDEwMEYwRUI3Qn0)

**Comment by JingyueWu** [comment]
@jeet-vora Done, please check the [spreadsheet](https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/Documents/[glygen_xrefs.xlsx](https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/Documents/glygen_xrefs.xlsx?d=wc84a5a4dddfb4f79853045d5a0d00e56&csf=1&web=1&e=farTrp)?d=wc84a5a4dddfb4f79853045d5a0d00e56&csf=1&web=1&e=farTrp)

**Comment by JingyueWu** [comment]
The orange are the ones xref is not needed. Doi and Pubmed are in references. MGI is in mouse accessions these are human accessions. This task is completed.
