### ISSUE TITLE
Biomarker filter gives wrong filter count.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#628]
Diagnostic (17) Filter shows shows 17 count on glycan-list/82ff33c24895a862a754e479fbf75eb4 page.
But when selected it gives 20 results.
<img width="1779" alt="Screenshot 2023-08-18 at 12 40 32 PM" src="https://github.com/glygener/glygen-issues/assets/13891482/cbc0c5e7-ccf0-4b15-9064-c89cc6c3091a">

**Comment by rykahsay** [comment]
Fixed

<img width="1028" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/6107fa11-afc0-4d02-82bd-0d77ea1ba103">

**Comment by sujeetvkulkarni** [comment]
Done.
