### ISSUE TITLE
Bad PMIDs in downloads/iptmnet/current/ptm.txt

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#630]
It looks like the following PMIDs from downloads/iptmnet/current/ptm.txt are invalid -- please check these to confirm

1629231415665377
1733095019823750
1840795619684113
1840795619779198
1977919816844691
1977919817563356
1982375019795423
2019027818407956
2117749518407956
2117749519684113
2117749519779198
2117749520702584
31745324
33428935
33431121
33451558
33451567
33451735
33453820
33453904
33453959
33455663
33473134
33498134
33516355
33516356
33516365
33526191
33563945
33580028

**Comment by jeet-vora** [comment]
Hi Hongzhan and Chuming,
Hope you are doing well.

While processing iPTMnet data from ptm.txt file for GlyGen we found out there are few PMIDs (at least for the species data we integrate) to be invalid/obsolete, attached below. The first 12 PMIDs are 16 digits long and are invalid, however if you split them into 8 digits and perform a search they are valid PMIDs. e.g.1629231415665377 > 16292314 | 15665377
16292314 - Chromatin remodelling at a DNA double-strand break site in Saccharomyces cerevisiae15665377- Quantitative phosphoproteomics applied to the yeast pheromone signaling pathway
The rest of the 18 PMIDs are invalid or obsolete and thus yield no result. 
All these PMIDs are also visible in your frontend aswell. There could be other similar PMIDs which could be invalid/obsolete in the file. Can you please review these PMIDs and make necessary changes in the ptm.txt file.
Many thanks.

1629231415665377
1733095019823750
1840795619684113
1840795619779198
1977919816844691
1977919817563356
1982375019795423
2019027818407956
2117749518407956
2117749519684113
2117749519779198
2117749520702584
31745324
33428935
33431121
33451558
33451567
33451735
33453820
33453904
33453959
33455663
33473134
33498134
33516355
33516356
33516365
33526191
33563945
33580028

**Comment by jeet-vora** [comment]
Aug 22, 2023
Hello Jeet, 

Thanks for letting us know about these issues.
Please remove those problematic PMIDs for now.
We have just checked those 16 digit PMIDs. They actually came from a source data file. We will look into this problem.

Best,

Hongzhan
