### ISSUE TITLE
No pathway info in EBI triples for yeast

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#631]
The following command shows not triples for pathway.

```
cat downloads/ebi/current/uniprot-proteome-saccharomyces-cerevisiae.nt | grep " <https://sparql.glygen.org/ontology/pathway> "
```

As a result, the following datasets will not be created (and I have removed them from mis/dataset-masterlist.json)
- yeast_protein_pathways_reactome.csv
- yeast_protein_xref_reactome.csv

Please make sure this is ok

**Comment by jeet-vora** [comment]
@pkay47 Can you look into the issue? Reactome has data for yeast. eg P17967

![image](https://github.com/glygener/glygen-issues/assets/25825266/4e36536a-0d9e-4dca-97d9-13ec76ca73ec)

**Comment by pv47** [comment]
Reaction appender uses taxId based query to get pathway. Proteome taxId is 559292, but in reactome 'Saccharomyces cerevisiae' has taxId 4932. 

Updated 
http://ftp.ebi.ac.uk/pub/contrib/glygen/current_release/uniprot-proteome-saccharomyces-cerevisiae.nt.gz 
http://ftp.ebi.ac.uk/pub/contrib/glygen/current_release/statistics-saccharomyces-cerevisiae.json

Yeast dataset now has pathway info. From stats (these were zero earlier)
"gly:Pathway_Annotation" : 522
"gly:cellularLocation" : 3677,
"gly:pathway" : 1600,
"gly:pathwayDatabase" : 522,
"gly:pathwayName" : 522,
"gly:pathwaySummary" : 522,
"gly:rxnSummary" : 1571

@rykahsay please take a look
