### ISSUE TITLE
Backend needs to send url for Biomarker ID and Assessed Biomarker Entity.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#633]
"assessed_biomarker_entity" and "biomarker_id" needs corresponding url in the https://api.tst.glygen.org/biomarker/detail/
API response.

![Screenshot 2023-08-23 at 12 18 20 PM](https://github.com/glygener/glygen-issues/assets/13891482/b8d7a6f1-832c-4dfd-8705-b9a5a38f4292)

**Comment by rykahsay** [comment]
You will need to extract these URLs from the component section (can be mutlple)

![image](https://github.com/glygener/glygen-issues/assets/20584876/1c7c7af6-417c-46fa-9ede-dcd2712c2df1)

<img width="581" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/5f188c80-3550-4316-b18d-b2f914bf8cfb">

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger 
We already show the urls mentioned above as evidence in component section. I think we can close this one.

**Comment by ReneRanzinger** [comment]
@kmartinez834 is this outdates or do you still want to use Biomarker ID and entry as links. If so, were should the link point?

**Comment by kmartinez834** [comment]
Remove links for Biomarker ID and entry in this release.
