### ISSUE TITLE
BEST Biomarker Type entry on biomarker details page should point to which link?

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#634]
Can you given an example url for BEST Biomarker Type entry like Prognostic etc.

![Screenshot 2023-08-23 at 12 28 22 PM](https://github.com/glygener/glygen-issues/assets/13891482/94340630-bcbd-4dc4-ac89-926a90b97a40)

**Comment by kmartinez834** [comment]
Diagnostic: https://www.ncbi.nlm.nih.gov/books/n/biomarkers/diagnostic/
Monitoring: https://www.ncbi.nlm.nih.gov/books/n/biomarkers/monitoring/
Response: https://www.ncbi.nlm.nih.gov/books/n/biomarkers/pharmacodynamic/
Predictive: https://www.ncbi.nlm.nih.gov/books/n/biomarkers/predictive/
Prognostic: https://www.ncbi.nlm.nih.gov/books/n/biomarkers/prognostic/
Safety: https://www.ncbi.nlm.nih.gov/books/n/biomarkers/safety/
Risk: https://www.ncbi.nlm.nih.gov/books/n/biomarkers/susceptibility/

**Comment by kmartinez834** [comment]
@sujeetvkulkarni updated comment above to include safety and risk.

**Comment by sujeetvkulkarni** [comment]
done for all above mentioned BEST Biomarker Types.
