### ISSUE TITLE
components array in biomarker details page response needs to be an object with with glycan and protein arrays.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#635]
API : https://api.tst.glygen.org/biomarker/detail/

```
  "components": [
    {
      "component_accession": "G33187NK",
      "component_category": "glycan"
    },
    {
      "component_accession": "P02750-1",
      "component_category": "protein"
    }
  ]
```

Needs to change to 

```
  "components": {
      "glycan": [
         {
             "glytoucan_ac": "G33187NK",
         },
     ],
    "protein": [
      {
          "uniprot_canonical_ac": "P02750-1",
          "protein_name": "protein"
      }
    ] 
  }
```

Backend needs to send empty protein or glycan array in case corresponding accession entries are not present.

**Comment by rykahsay** [comment]
The objects will also have url in them as shown below and you will need to use these multiple URLs when you display the "Assessed Biomarker Entity"


<img width="735" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/51d7bb15-8be7-467b-9312-9e4362aee1c1">

**Comment by sujeetvkulkarni** [comment]
@rykahsay @ReneRanzinger 

We might need to change mockup if we want to use multiple urls for "Assessed Biomarker Entity".
Linking - Backend needs to send url for Biomarker ID and Assessed Biomarker Entity. #633

![image](https://github.com/glygener/glygen-issues/assets/13891482/9114a384-7fed-44d7-9851-a06192003e33)

**Comment by rykahsay** [comment]
The objects will also have url in them as shown below, and you will need to use these multiple URLs when you display the "Assessed Biomarker Entity". This also takes care of ticket #633 

<img width="773" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/bc7f63a4-d555-4901-a3b9-eca222d31458">

<img width="735" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/51d7bb15-8be7-467b-9312-9e4362aee1c1">

**Comment by ReneRanzinger** [comment]
I think it would be better to work with evidence badges here rather than making the biomarker ID a link. One GlyGen evidence badge with 1-2 ID/Links.

**Comment by rykahsay** [comment]
You mean like this:

<img width="1289" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/2b8b7494-8578-42fd-befd-e05d6f1dbf29">

**Comment by rykahsay** [comment]
If not, please use this and edit 
```
"components": {
        "protein": [
            {
                "accession": "P02750-1",
                "name": "Leucine-rich alpha-2-glycoprotein",
                "evidence": [
                    {
                        "id": "GLY_000625",
                        "database": "GlyGen",
                        "url": "https://data.glygen.org/GLY_000625"
                    }
                ]
            }
        ],
        "glycan": [
            {
                "accession": "G33187NK",
                "evidence": [
                    {
                        "id": "GLY_000737",
                        "database": "GlyGen",
                        "url": "https://data.glygen.org/GLY_000737"
                    }
                ]
            }
        ]
    },
```

**Comment by rykahsay** [comment]
<img width="681" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/5271c1d3-627c-4985-ad26-ceb0a9e7adfc">

**Comment by sujeetvkulkarni** [comment]
done.
