### ISSUE TITLE
New datasets in masterlist.json

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#636]
The following datasets require processing. Info has been added to the masterlist and xref_info. _The first three datasets require no processing instructions._ Once done you can use comment and checkmark for me to check individual files.

- [x] yeast_protein_glycohydrolase.csv (path - /data/projects/glygen/generated/datasets/**compiled**/yeast_protein_glycohydrolase.csv
- [x] yeast_protein_glycosyltransferase.csv (path - /data/projects/glygen/generated/datasets/**compiled**/yeast_protein_glycosyltransferase.csv)
- [x] sarscov2_protein_xref_viralglycome.csv (/data/projects/glygen/generated/datasets/compiled/sarscov2_protein_xref_viralglycome.csv)
- [x] all_europepmc_linkouts.xml (#257)

**Comment by rykahsay** [comment]
check

**Comment by jeet-vora** [comment]
all_europepmc_linkouts.xml not .zip is still pending 
Rest are done and checked.
