### ISSUE TITLE
Biomarker details page download returns error.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#640]
Biomarker details download returns error.

API : https://api.tst.glygen.org/data/detail_download/

Input:
```
{
  "id": "A0001",
  "type": "biomarker_detail",
  "format": "json",
  "compressed": false
}
````

response

```
{
  "error_list": [
    {
      "error_code": "exception-error-2OSMRK"
    }
  ]
}
```

Are we supporting biomarker details download in 2.2? what formats are we supporting.

**Comment by rykahsay** [comment]
Note that the second parameter is "download_type" not "type"

<img width="617" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/0fc738bd-947f-4cb8-8d57-aa61ec4767d2">

**Comment by sujeetvkulkarni** [comment]
done.
