### ISSUE TITLE
No BCO created for this dataset, please create it.

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#644]
No BCO created for this dataset, please create it.
```
cd /software/glygen/
 python3 check-bco2filename-mapping.py
```

<img width="1256" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/7d847b82-a733-4f8b-b732-e84295106f66">

_Originally posted by @rykahsay in https://github.com/glygener/glygen-issues/issues/97#issuecomment-1614888331_
            
@jingyue add the script info to backend document for BCO checks

**Comment by JingyueWu** [comment]
Connected to #97

**Comment by JingyueWu** [comment]
@jeet-vora Done, please check: 

https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/[data_integration.docx](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/data_integration.docx?d=w0c84e59c4be6494d91cc017661cc9944&csf=1&web=1&e=9W1c4V)?d=w0c84e59c4be6494d91cc017661cc9944&csf=1&web=1&e=9W1c4V 

<img width="523" alt="Screen Shot 2023-08-30 at 11 31 24 AM" src="https://github.com/glygener/glygen-issues/assets/61590108/52043274-4fcb-436f-9dd3-f8e1943815b7">

**Comment by JingyueWu** [comment]
action items for @JingyueWu :
- run the script
- share with Jeet the output .csv file
- add example (screenshot) to the data integration doc
