### ISSUE TITLE
GET request for biomarker details api returns 404 NOT FOUND status code if we use semantic url format.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#645]
GET request for biomarker detail api is not working in semantic url format. It should work in semantic url format with query and without query parameter.

https://api.tst.glygen.org/biomarker/detail/A0001
and 
https://api.tst.glygen.org/biomarker/detail/A0001?query={"paginated_tables":[{"table_id":"publication","offset":1,"limit":200,"sort":"date","order":"desc"}]}

both above format should work.
```
Request URL:
https://api.tst.glygen.org/biomarker/detail/A0001
Request Method:
GET
Status Code:
404 NOT FOUND
```

Currently it works if we pass the id in the "query" as shown below.
https://api.tst.glygen.org/biomarker/detail?query={"id":"A0001","paginated_tables":[{"table_id":"publication","offset":1,"limit":200,"sort":"date","order":"desc"}]}

**Comment by rykahsay** [comment]
Try now

**Comment by sujeetvkulkarni** [comment]
done.
