### ISSUE TITLE
biomarker detail api is not returning cross reference section information

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#646]
As per [mockup](https://docs.google.com/presentation/d/14vJ_o_fq6b0UR2DTgs0NhATl-C3uiPVN68wGLQnejq4/edit#slide=id.g25e0a123e1a_0_145) we are supporting cross reference section on biomarker details page but the biomarker details api is not sending cross reference section information.

API : https://api.tst.glygen.org/biomarker/detail?query={"id":"A0001","paginated_tables":[{"table_id":"publication","offset":1,"limit":200,"sort":"date","order":"desc"}]}

**Comment by sujeetvkulkarni** [comment]
Please send us an empty cross reference array.

**Comment by rykahsay** [comment]
I am sending now

**Comment by sujeetvkulkarni** [comment]
done.
