### ISSUE TITLE
publication details api is not sending biomarker section information.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#647]
As per [mockup](https://docs.google.com/presentation/d/14vJ_o_fq6b0UR2DTgs0NhATl-C3uiPVN68wGLQnejq4/edit#slide=id.g25e0a123e1a_0_113) we are supporting biomarker section on publication details page but the publication details api is not sending biomarker section information.

```
API : https://api.tst.glygen.org/publication/detail?query={"id":"24980613","type":"PubMed","paginated_tables":[{"table_id":"glycosylation_reported_with_glycan","offset":1,"limit":20,"sort":"glytoucan_ac","order":"asc"},{"table_id":"glycosylation_reported","offset":1,"limit":20,"sort":"start_pos","order":"asc"},{"table_id":"glycosylation_predicted","offset":1,"limit":20,"sort":"start_pos","order":"desc"},{"table_id":"phosphorylation","offset":1,"limit":20,"sort":"uniprot_canonical_ac","order":"asc"},{"table_id":"referenced_proteins","offset":1,"limit":20,"sort":"protein_name","order":"desc"},{"table_id":"referenced_glycans","offset":1,"limit":20,"order":"desc"}]}
```

Also, please provide publication id which has biomarker section information present on it.

**Comment by rykahsay** [comment]
Check now
<img width="654" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/3b79ebdb-f388-4651-a063-2fdab954a53f">

**Comment by sujeetvkulkarni** [comment]
done.
