### ISSUE TITLE
Dictyostelium discoideum organism in GlyGen

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#649]
Preethi, 

We need to add Dictyostelium discoideum organism in GlyGen for 2.3. Can you provide info and make plans to add it in September?

**Comment by pv47** [comment]
@jeet-vora it is already part of release http://ftp.ebi.ac.uk/pub/contrib/glygen/current_release/uniprot-proteome-dictyostelium-discoideum.nt.gz

Please let me know if anything is missing

**Comment by jeet-vora** [comment]
Downloaded data for DD.
