### ISSUE TITLE
CFDE Abstract for SfG

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#652]
Jingyue begin drafting (basic) CFDE abstract and have Jeet review/add comments. Dependency of #535 

SfG abstract requirements: https://www.glycobiology.org/abstracts---posters-2023

Due 11:59 pm ET on Sunday, September 10, 2023.

Abstract [draft](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Conference%20Abstracts%20and%20Posters/Abstracts/[CFDE_Abstract_SfG_November_2023](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Conference%20Abstracts%20and%20Posters/Abstracts/CFDE_Abstract_SfG_November_2023.docx?d=w035b682e3f0a42f6b03fed1ff8914fac&csf=1&web=1&e=u7smPE).docx?d=w035b682e3f0a42f6b03fed1ff8914fac&csf=1&web=1&e=u7smPE)

**Comment by jeet-vora** [comment]
Abstract: https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Conference%20Abstracts%20and%20Posters/Abstracts/CFDE_Abstract_SfG_November_2023.docx?d=w035b682e3f0a42f6b03fed1ff8914fac&csf=1&web=1&e=kEyOXD

**Comment by JingyueWu** [comment]
Closing this ticket - submitted on Friday (9/8).
