### ISSUE TITLE
Provide an example for software annotation in the contributor column

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#658]
We need an example how we can add information about utilized software to the "contributor" (BCO) column in the curated spreadsheet. It would be good to get GRITS example:

Name: GRITS Toolbox
URL: http://www.grits-toolbox.org/
Source code repository: https://github.com/GritsToolbox

Let me know if anything else is needed to make the example.

**Comment by jeet-vora** [comment]
@Mindyporterfield @ReneRanzinger 

<ins>**Example**</ins>
**createdWith**:GRITS Toolbox (http://www.grits-toolbox.org/) |**createdWith**:Software/Tool/Code Name (URL or Sourecode URL)

<ins>**Combined Example**</ins>
**curatedBy**:Mindy Porterfield (mindyp@ccrc.uga.edu, CCRC)|**curatedBy**:Anh Nyugen (anh@gwu.edu, GW)|**createdWith**:GRITS Toolbox (http://www.grits-toolbox.org/)

The field can have multiple contribution types separated by `|`

There is no need to add a corresponding author or other author name list if curating the paper by yourself.

**Comment by Mindyporterfield** [comment]
I added this to the wiki for reference
