### ISSUE TITLE
Add CFDE grant number and reporter link to the footer

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#659]
Change the footer from "GlyGen is supported and funded by the [National Institue of General Medical Sciences ](https://www.nigms.nih.gov/)under the grant # [1R24GM146616 - 01](https://reporter.nih.gov/project-details/10494610)"

to

"GlyGen is supported and funded by the [National Institute of General Medical Sciences ](https://www.nigms.nih.gov/)under the grant # [1R24GM146616 - 01](https://reporter.nih.gov/project-details/10494610) and the [NIH Office of the Director](https://www.nih.gov/institutes-nih/nih-office-director) under the grant #[3OT2OD032092-01S1](https://reporter.nih.gov/search/YDQYsN0VFEu60r2iryHcAA/project-details/10683512)."

@jeet-vora please review than assign to @sujeetvkulkarni

**Comment by jeet-vora** [comment]
I would suggest to use this - 


"GlyGen is supported and funded by the [National Institute of General Medical Sciences ](https://www.nigms.nih.gov/)under the grant # [1R24GM146616 - 01](https://reporter.nih.gov/project-details/10494610) and the [National Institutes of Health Office of Strategic Coordination - The Common Fund](https://commonfund.nih.gov/) under the grant #[1OT2OD032092](https://reporter.nih.gov/project-details/10397274)."

------------------------------------------------------------------------------------------------------------------------

 1OT2OD032092 has the latest date although the new CFDE award amount has not been added yet.

CFDE is overseen by The Common Fund which is overseen by the [Office of Strategic Coordination (OSC)](https://commonfund.nih.gov/contact). OSC is housed within the [Division of Program Coordination, Planning, and Strategic Initiatives (DPCPSI)](https://dpcpsi.nih.gov/), [Office of the Director (OD)](https://www.nih.gov/institutes-nih/nih-office-director), [National Institutes of Health (NIH)](https://www.nih.gov/).

**Comment by ReneRanzinger** [comment]
"GlyGen is supported and funded by the [National Institute of General Medical Sciences ](https://www.nigms.nih.gov/)under the grant # [1R24GM146616 - 01](https://reporter.nih.gov/project-details/10494610) and the [National Institutes of Health Office of Strategic Coordination - The Common Fund](https://commonfund.nih.gov/) under the grant #[1OT2OD032092](https://reporter.nih.gov/project-details/10397274)."

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger 
https://tst.glygen.org/about/ page in GlyGen
Funding And Support section contains similar information. Can you please check if we need modification there too?

**Comment by sujeetvkulkarni** [comment]
Current 
From 2022 onward GlyGen is supported and funded by the [National Institue of General Medical Sciences](https://www.nigms.nih.gov/) at [National Institute of Health (NIH)](https://www.nih.gov/) under the grant [1R24GM146616-01](https://reporter.nih.gov/project-details/10494610).

Needs to be 
From 2022 onward GlyGen is supported and funded by the [National Institute of General Medical Sciences ](https://www.nigms.nih.gov/)under the grant # [1R24GM146616 - 01](https://reporter.nih.gov/project-details/10494610) and the [National Institutes of Health Office of Strategic Coordination - The Common Fund](https://commonfund.nih.gov/) under the grant #[1OT2OD032092](https://reporter.nih.gov/project-details/10397274).

**Comment by ReneRanzinger** [comment]
Yes update this and add the CFDE logo on the right side as well.

**Comment by sujeetvkulkarni** [comment]
done.
d43dd65e3902cf5fbb9d94b6eb8a12f62ed5bdbc

**Comment by sujeetvkulkarni** [comment]
e2c2245a390719b09e9532c365a338b2ec305b5b
