### ISSUE TITLE
Table download for component->protein and component->glycan section on biomarker details page. 

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#662]
As per [mockup](https://docs.google.com/presentation/d/14vJ_o_fq6b0UR2DTgs0NhATl-C3uiPVN68wGLQnejq4/edit#slide=id.g25e0a123e1a_0_83) we need to support table download option for component->protein and component->glycan tabs on biomarker details page. 
https://tst.glygen.org/biomarker/A0417#Components

Can you please provide us table id ("section" property) to use to download component->protein and component->glycan tabs.
API : https://api.tst.glygen.org/data/section_download/

```
{
  "id": "A0417",
  "download_type": "biomarker_section",
  "section": "component_glycan",
  "format": "csv",
  "compressed": false
}
```

```
{
  "id": "A0417",
  "download_type": "biomarker_section",
  "section": "component_protein",
  "format": "csv",
  "compressed": false
}
```

**Comment by rykahsay** [comment]
Please use:



https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/data/section_download.biomarker.component_glycan.json
https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/data/section_download.biomarker.component_protein.json

**Comment by sujeetvkulkarni** [comment]
97c43564df0be94340a800dfce2f2eded0882d30
