### ISSUE TITLE
Give an example(protein id) for alternative sites.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#663]
Protein id for range - P0DTC2

**Comment by sujeetvkulkarni** [comment]
Getting 
start_pos :  -1
type :  "Undefined type"

![Screenshot 2023-09-06 at 10 24 14 AM](https://github.com/glygener/glygen-issues/assets/13891482/6331d5bb-983e-470b-97aa-c61aabb25e92)

**Comment by rykahsay** [comment]
We don't have any protein with alternative sites.

As for the -1 value, are you sure you are getting that from the API? For example, for the first case where glytoucan_ac=G03382KH and PMID = "34369795", the API is not giving  start_pos/end_pos fields, which means this is a case where the site is not known.

<img width="604" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/f037885a-0fd5-4272-bf61-68551e72295f">

**Comment by rykahsay** [comment]
I have fixed the issue, please ignore my last comment:

 "As for the -1 value, are you sure you are getting that from the API? For example, for the first case where glytoucan_ac=G03382KH and PMID = "34369795", the API is not giving start_pos/end_pos fields, which means this is a case where the site is not known."
