### ISSUE TITLE
Biomarkers on details page

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#665]
https://tst.glygen.org/glycan/G06356OH#Biomarkers

- Where Source is GlyGen, change to BiomarkerKB 
- A0245 is listed as a source twice, can duplicates be filtered out?

![image](https://github.com/glygener/glygen-issues/assets/90285371/a9b628f0-02e8-401c-a979-3d0aadaff2a2)

**Comment by sujeetvkulkarni** [comment]
Assigning it to Robel.

Backend should send "database": "BiomarkerKB", instead of "GlyGen" for biomarker evidence in glycan, protein, publication and motif details apis.

API : https://api.tst.glygen.org/glycan/detail/G06356OH
Duplicate ids "id": "A0245", from evidence array should be filtered.
```
biomarkers": [
    {
      "assessed_biomarker_entity": "Glyco-typer 50 N-glycan liver disease panel",
      "biomarker_id": "A0245",
      "evidence": [
        {
          "id": "A0245",
          "database": "GlyGen",
          "url": "https://data.glygen.org/GLY_000737"
        },
        {
          "id": "31721442",
          "database": "PubMed",
          "url": "https://glygen.org/publication/PubMed/31721442"
        },
        {
          "id": "31177770",
          "database": "PubMed",
          "url": "https://glygen.org/publication/PubMed/31177770"
        },
        {
          "id": "A0245",
          "database": "GlyGen",
          "url": "https://data.glygen.org/GLY_000625"
        }
      ],

```

**Comment by rykahsay** [comment]
We have talked about this on our internal meeting. Since it is pointing to data.glygen.org, we do not want to say it is BiomarkerDB website now. It will change in the feature when we have external BiomakerDB cross reference.

<img width="1181" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/2d164079-f7c8-4f25-87ee-edb663449506">

**Comment by kmartinez834** [comment]
Looks good 👍
