### ISSUE TITLE
Process new dataset (Glyconnect - Yeast)

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#671]
The following new datasets need to be created:

- yeast_proteoform_glycosylation_sites_glyconnect.csv
- yeast_proteoform_citations_glycosylation_sites_glyconnect.csv

Source file: glyconnect/current/glyconnect_yeast.json

Same processing steps as other species.

**Comment by rykahsay** [comment]
please check

**Comment by kmartinez834** [comment]
Looks good 👍
