### ISSUE TITLE
Add Saccharomyces cerevisiae to glycan search init

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#672]
Add Saccharomyces cerevisiae to https://api.tst.glygen.org/glycan/search_init/

``` json
{
      "name": "Saccharomyces cerevisiae",
      "id": 4932
}
```

FYI @sujeetvkulkarni , should appear in drop down once added:
![image](https://github.com/glygener/glygen-issues/assets/90285371/fa8ab631-7026-40bd-bf35-d77f9661dcaf)

**Comment by rykahsay** [comment]
Check now

**Comment by kmartinez834** [comment]
Checked 👍
