### ISSUE TITLE
Add Saccharomyces cerevisiae to list & home init APIs

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#673]
- For both https://api.tst.glygen.org/glycan/list/ and https://api.tst.glygen.org/protein/list/
Add Yeast between Fruitfly and HCV-H:
``` json
{
            "id": "Saccharomyces cerevisiae",
            "label": "Yeast",
            "count": ,
            "order": 6
}
```

- Add Saccharomyces cerevisiae to https://api.tst.glygen.org/pages/home_init/
`"species": "Saccharomyces cerevisiae"`

**Comment by rykahsay** [comment]
check now

**Comment by kmartinez834** [comment]
👍
