### ISSUE TITLE
Push 2.2 BCOs to data.glygen.org

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#675]
All new 2.2 datasets now have BCOs. You can push them to data.glygen.org. There are some minor fixes to be made and will reflect when pushed to prd.

**Q)** Can you let me know what the error `in_bco` means, see below when `check-bco2filename-mapping.py` is run

`ERROR	in_bco`

| GLY_000747 | yeast_protein_citations_reactome.csv | ERROR | in_bco |
| ---------- | ------------------------------------ | ----- | ------ |
| GLY_000762 | yeast_protein_ntdata.nt              | ERROR | in_bco |

**Q)** Does `ERROR	in_fs` means the dataset does not exist? e.g. rat_proteoform_glycosylation_sites_carbbank.csv

**Comment by rykahsay** [comment]
I thought this was documented! If not, please document now.

This means datasets are in file system (in_fs) but there is NO BCO for them
```
NO-BCO,protein_glygen_genecards_xref_mapping.csv,ERROR,in_fs
NO-BCO,protein_glygen_uniprotkb_xref_mapping.csv,ERROR,in_fs
NO-BCO,all_europepmc_linkouts.xml,ERROR,in_fs
```

These means BCO exists but the dataset file does not exist by the given file name. Some of these errors might disappear if you correct the file name
```
GLY_000747,yeast_protein_citations_reactome.csv,ERROR,in_bco
GLY_000765,yeast_protein_pathways_reactome.csv,ERROR,in_bco
GLY_000777,yeast_protein_xref_reactome.csv,ERROR,in_bco
GLY_000815,all_europepmc_linkouts.zip,ERROR,in_bco
GLY_000818,rat_protein_citations_reactome.csv,ERROR,in_bco
GLY_000819,mouse_protein_citations_reactome.csv,ERROR,in_bco
```

**Comment by jeet-vora** [comment]
@rykahsay Please see https://github.com/glygener/glygen-issues/issues/679

Below are the comments in the ticket added yesterday.

1) protein_glygen_genecards_xref_mapping.csv and protein_glygen_uniprotkb_xref_mapping.csv don't seem to have BCOs
-> These are tsv and not csv. /data/projects/glygen/generated/datasets/unreviewed/protein_glygen_uniprotkb_xref_mapping.tsv
/data/projects/glygen/generated/datasets/unreviewed/protein_glygen_genecards_xref_mapping.tsv and these have BCOs. Please remove them from the list.

2) change file name from "all_europepmc_linkouts.zip" to "all_europepmc_linkouts.xml" for GLY_000815
-> Once you work on https://github.com/glygener/glygen-issues/issues/257, it will be all_europepmc_linkouts.zip and not all_europepmc_linkouts.xml

3) yeast_protein_citations_reactome.csv, GLY_000747
yeast_protein_pathways_reactome.csv, GLY_000765
yeast_protein_xref_bgee.csv, GLY_000777
-> Checking these, if no data found will remove them.
-------------------------------------------------------------------------------------------------------------
These datasets have data but are missing. Please create the datasets (added in the masterlist) BCOs already created.

```
yeast_protein_citations_reactome.csv
yeast_protein_pathways_reactome.csv
yeast_protein_xref_chembl.csv 
yeast_protein_xref_reactome.csv 
mouse_protein_citations_reactome.csv 
rat_protein_citations_reactome.csv 
```

removing bco for
`GLY_000777 yeast_protein_xref_bgee.csv`

**Comment by rykahsay** [comment]
Check now

**Comment by jeet-vora** [comment]
Done
