### ISSUE TITLE
glycosylation table sort returns empty result array with pagination api.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#676]
When sorted with glytoucan_ac , type, comment, start_pos etc. or changed offset or limit with table ids: glycosylation_reported, glycosylation_reported_with_glycan, 
glycosylation_predicted, glycosylation_automatic_literature_mining pagination api returns empty reesults:[] array.

API : https://api.tst.glygen.org/pagination/page/

```
{
  "record_type": "protein",
  "table_id": "glycosylation_reported_with_glycan",
  "record_id": "P14210-1",
  "offset": 1,
  "limit": 20,
  "order": "desc",
  "sort": "type"
}
```

```
{
  "record_type": "protein",
  "table_id": "glycosylation_reported",
  "record_id": "P14210-1",
  "offset": 1,
  "limit": 20,
  "order": "desc",
  "sort": "start_pos"
}
```

**Comment by rykahsay** [comment]
Please try now

**Comment by sujeetvkulkarni** [comment]
done.
