### ISSUE TITLE
Issue updating BCOs

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#678]
The DRAFT BCOs in https://biocomputeobject.org/ are based on the 2.0.2 version and were not updated when 2.1.1 was published. How can I make a change to the most recent version of the BCO?

![image](https://github.com/glygener/glygen-issues/assets/90285371/93a6d14f-21a1-4c95-bb33-35ab3188e6f1)

**Comment by rykahsay** [comment]
You don't have to do that at the draft level -- when inject the right version when I publish them (or use them in GlyGen).

<img width="1020" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/090a24be-e71e-4c8a-9352-2ad7720a8d78">

**Comment by kmartinez834** [comment]
How can I update the BCO?

**Comment by kmartinez834** [comment]
Per meeting with Robel and Hadley, changes are made in DRAFT.

@rykahsay Remove fields from DRAFT that you are automatically populating. Also remove authors who no longer work on the project: Amanda, Millicent, Rahi, Xavier

**Comment by rykahsay** [comment]
I have tried to do it, please check

**Comment by kmartinez834** [comment]
BCO changes were made, thanks
