### ISSUE TITLE
Missing BCOs or dataset files

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#679]
- protein_glygen_genecards_xref_mapping.csv and protein_glygen_uniprotkb_xref_mapping.csv don't seem to have BCOs
- change file name from "all_europepmc_linkouts.zip" to "all_europepmc_linkouts.xml" for GLY_000815
- I was not able to create dataset for the following. Look at corresponding downloads to show me data existence for these, otherwise retire the BCOs and remove them from dataset-masterlist.json

yeast_protein_citations_reactome.csv, GLY_000747
yeast_protein_pathways_reactome.csv, GLY_000765
yeast_protein_xref_bgee.csv, GLY_000777

**Comment by jeet-vora** [comment]
@rykahsay 
**1)** protein_glygen_genecards_xref_mapping.csv and protein_glygen_uniprotkb_xref_mapping.csv don't seem to have BCOs
 -> These are tsv and not csv. `/data/projects/glygen/generated/datasets/unreviewed/protein_glygen_uniprotkb_xref_mapping.tsv`
`/data/projects/glygen/generated/datasets/unreviewed/protein_glygen_genecards_xref_mapping.tsv` and these have BCOs. Please remove them from the list.

**2)** change file name from "all_europepmc_linkouts.zip" to "all_europepmc_linkouts.xml" for GLY_000815
-> Once you work on #257, it will be all_europepmc_linkouts.zip and not all_europepmc_linkouts.xml

**3)** yeast_protein_citations_reactome.csv, GLY_000747
yeast_protein_pathways_reactome.csv, GLY_000765
yeast_protein_xref_bgee.csv, GLY_000777
-> Checking these, if no data found will remove them.

**Comment by jeet-vora** [comment]
@rykahsay --- see below for new datasets

These datasets have data but are missing. Please create the datasets (added in the masterlist). BCOs already created.
- [ ] yeast_protein_citations_reactome.csv
- [ ] yeast_protein_pathways_reactome.csv
- [ ] yeast_protein_xref_chembl.csv 
- [ ] yeast_protein_xref_reactome.csv
- [ ] mouse_protein_citations_reactome.csv
- [ ] rat_protein_citations_reactome.csv

**removing bco for** 
GLY_000777	yeast_protein_xref_bgee.csv

**Comment by rykahsay** [comment]
Please read carefully to what I wrote:

" ... Look at corresponding downloads to show me data existence for these, otherwise retire the BCOs and remove them from dataset-masterlist.json"


You need to show me the triples exist, please read carefully below.

This command does not give any triples
```
cat downloads/ebi/current/uniprot-proteome-saccharomyces-cerevisiae.nt | grep "<https://sparql.glygen.org/ontology/pathway>"
```

While the above command for human gives triples
```
cat downloads/ebi/current/uniprot-proteome-homo-sapiens.nt | grep "<https://sparql.glygen.org/ontology/pathway>"
```

**Comment by rykahsay** [comment]
As for "mouse_protein_citations_reactome.csv", please read carefully what I am writing here.

First, use the following command to get list of reaction URIs connected pathways
```
cat downloads/ebi/current/uniprot-proteome-mus-musculus.nt | grep "R-MMU-"  | grep "<https://sparql.glygen.org/ontology/pathway>" | awk '{print $1}' | sort -u > reaction_uris_with_pathway.txt
```

Next, use the following command to get list of reaction URIs connected PMIDs
```
cat downloads/ebi/current/uniprot-proteome-mus-musculus.nt | grep "R-MMU-"  | grep "<http://purl.uniprot.org/core/citation>"  | awk '{print $1}' | sort -u  > reaction_uris_with_pmid.txt
```

You will find out that the files reaction_uris_with_pathway.txt and reaction_uris_with_pmid.txt DO NOT HAVE any reaction incommon. This means I cannot make mouse_protein_citations_reactome.csv (since pathway is the one that connects me to protein accessions).

**Comment by jeet-vora** [comment]
@rykahsay - Removed these from the masterlist and removed the BCOs

```
yeast_protein_citations_reactome.csv
yeast_protein_pathways_reactome.csv
yeast_protein_xref_reactome.csv
mouse_protein_citations_reactome.csv
rat_protein_citations_reactome.csv
```
