### ISSUE TITLE
GlyGen webinar: CAZypedia (Harry Brumer)

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#68]
Dear Rene,

I'd certainly be happy to present a webinar on CAZypedia for GlyGen.  Later in the spring (April, May) would probably be best for me, but I can certainly make other dates work.

All the best,

Harry

**Comment by jeet-vora** [comment]
Harry is giving a talk in GlyGen Webinar on April 18, 2023
