### ISSUE TITLE
Clarify tax ID issues

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#680]
Proteins use these tax IDs:
```
"tax_id","short_name","long_name","common_name","nt_file","is_reference","sort_order"
"9606","human","Homo sapiens","Human","uniprot-proteome-homo-sapiens.nt","yes","1"
"10090","mouse","Mus musculus","Mouse","uniprot-proteome-mus-musculus.nt","yes","2"
"10116","rat","Rattus norvegicus","Rat","uniprot-proteome-rattus-norvegicus.nt","yes","3"
"63746","hcv1a","Hepatitis C virus (isolate H)","HCV-H","uniprot-proteome-hepatitis-c-virus-1a.nt","yes","4"
"11116","hcv1b","Hepatitis C virus (isolate Japanese)","HCV-Japanese","uniprot-proteome-hepatitis-c-virus-1b.nt","yes","5"
"694009","sarscov1","Severe acute respiratory syndrome-related coronavirus","HCoV-SARS","uniprot-proteome-sars-coronavirus.nt","yes","6"
"2697049","sarscov2","Severe acute respiratory syndrome coronavirus 2","SARS-CoV-2","uniprot-proteome-sars-cov-2.nt","yes","7"
"7227","fruitfly","Drosophila melanogaster","Fruit fly","uniprot-proteome-drosophila-melanogaster.nt","yes","8"
"559292","yeast","Saccharomyces cerevisiae S288C","Yeast","uniprot-proteome-saccharomyces-cerevisiae.nt","yes","9"
```

Glycans use these tax IDs:
```
"tax_id","short_name","long_name","common_name","nt_file","is_reference","sort_order"
"9606","human","Homo sapiens","Human","uniprot-proteome-homo-sapiens.nt","yes","1"
"10090","mouse","Mus musculus","Mouse","uniprot-proteome-mus-musculus.nt","yes","2"
"10116","rat","Rattus norvegicus","Rat","uniprot-proteome-rattus-norvegicus.nt","yes","3"
"63746","hcv1a","Hepatitis C virus (isolate H)","HCV-H","uniprot-proteome-hepatitis-c-virus-1a.nt","yes","4"
"694009","sarscov1","Severe acute respiratory syndrome-related coronavirus","HCoV-SARS","uniprot-proteome-sars-coronavirus.nt","yes","6"
"2697049","sarscov2","Severe acute respiratory syndrome coronavirus 2","SARS-CoV-2","uniprot-proteome-sars-cov-2.nt","yes","7"
"7227","fruitfly","Drosophila melanogaster","Fruit fly","uniprot-proteome-drosophila-melanogaster.nt","yes","8"
"10114","","Rattus","rats","","no","1000"
"4932","","Saccharomyces cerevisiae","Yeast","","no","1000"
"11103","","Hepacivirus C","HCV","","no","1000"
"9823","","Sus scrofa","Pig","","no","1000"
"9825","","Sus scrofa domesticus","","","no","1000"
"44689","","Dictyostelium discoideum","","","no","1000"
```

Issues:
- Clarify which "long_name" to use on front end and in BCO organism field
--> NCBI, EBI, UniProt?
- Can "common_name" be the same for two tax ids (ex. Yeast, Rat)?
- Will glycans also have yeast (559292) annotation?  
- How to ensure glycan stats and searches will include both (applies to Rat, Pig, HCV)?

**Comment by kmartinez834** [comment]
Items to discuss w/ @rykahsay on Monday:
- How is proteoform species mapping occurring?
- How does multiple genus/species/strain for one organism affect searching & filtering? 
- Homepage statistics & BCO filters --> could we use common names instead of scientific names so we can combine different tax id's for Rat, Yeast, etc.?

**Comment by ReneRanzinger** [comment]
From Group meeting on 9/20: for 2.2 we go with common name to collapse numbers for yeast and rat.

@jeet-vora will setup a dedicated meeting to come to a final decision moving forward (#717)

**Comment by kmartinez834** [comment]
Note, collapsing common names leaves `"11103","Hepacivirus C","HCV"` glycans out of the homepage statistics because it would apply to both HCV isolates.  Discuss how to handle this in meeting #717

**Comment by kmartinez834** [comment]
Organism decisions documented here: [GlyGen Organisms](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/Backend%20Workflow/Supplemental%20Files/GlyGen%20Organisms.docx?d=w4e505d8e40aa4bc5970cac7da288107d&csf=1&web=1&e=qTd882)
