### ISSUE TITLE
Pig to added as a new organism in 2.4

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#681]
Please provide info about proteome.

**Comment by pv47** [comment]
@jeet-vora  uniprot-proteome-sus_scrofa.nt.gz in 2023_04
Reference proteome: UP000008227 
TaxId: 9823
Sequences: 46254
Glycosylation_Annotation: 1601

**Comment by jeet-vora** [comment]
Stats
    "up:Simple_Sequence:up:canonical:xsd:boolean:false" : 23465,
    "up:Simple_Sequence:up:canonical:xsd:boolean:true" : 22789,
    "up:Simple_Sequence:up:reviewed:xsd:boolean:false" : 44721,
    "up:Simple_Sequence:up:reviewed:xsd:boolean:true" : 1533,
