### ISSUE TITLE
Create a list of xrefs resources for each organism for GlyGen in spreadsheet

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#682]

**Comment by pv47** [comment]
@jeet-vora dbXrefMap csv 2023_04 uploaded. Please take a look at http://ftp.ebi.ac.uk/pub/contrib/glygen/current_release/dbXrefMap.csv.gz

Please let me know if this meets requirement or any change required.

**Comment by jeet-vora** [comment]
Done
