### ISSUE TITLE
TCGA and COSMIC entries in GlyGen dataset from EBI variation pipeline

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#683]

**Comment by pv47** [comment]
@jeet-vora there was a discussion about this on 14-jun & Jie is looking into this. Please close this ticket or assign to Jie if another ticket has not been created

**Comment by ReneRanzinger** [comment]
@jeet-vora please check how much this overlaps with #1676. If its duplicated please close this.

**Comment by jeet-vora** [comment]
New tickets https://github.com/glygener/glygen-issues/issues/1676 and https://github.com/glygener/glygen-issues/issues/1725
