### ISSUE TITLE
Litmin pipeline output

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#685]
Location: https://data.glygen.org/ftp/udel/meeting/

These are the recent output files that contain "uniprotkb_ac", which one is the final output file that contains equivalent content like 
downloads/lit_min/current/proteoform_glycosylation_sites_literature_mining.csv?

litmining/glygen_set_new_site_fusion_output_contain_empty_site_tmp.tsv:pmid	uniprotkb_ac	protein	amino_acid	site_position
litmining/glygen_set_new_site_fusion_output_contain_empty_site.tsv:pmid	uniprotkb_ac	protein	amino_acid	site_position
litmining/glygen_set_new_site_fusion_output_tmp.tsv:pmid	uniprotkb_ac	protein	amino_acid	site_position
litmining/glygen_set_new_site_fusion_output.tsv:

**Comment by kmartinez834** [comment]
litmining/glygen_set_new_site_fusion_output.tsv:
```
pmid	uniprotkb_ac	protein	amino_acid	site_position
31958346	P42261	GluA1	Asn	401
```

Has equivalent content as the current file in downloads.  Only difference is header names and column order:
```
head downloads/lit_min/current/proteoform_glycosylation_sites_literature_mining.csv 
uniprotkb_ac,amino_acid,glycosylation_site,evidence
A5PKW4,Thr,9,9363430
O00300,Asn,183,16491292
O00555,Asn,283,29470411
O00622,Thr,242,26424659
O00622,Thr,242,26424659
O00744,Gly,60,17334647
O08537,Ser,16,11150304
O14672,Asn,278,18381078
O14672,Asn,551,18381078
```

**Comment by rykahsay** [comment]
Great, then just ask him to confirm that "litmining/glygen_set_new_site_fusion_output.tsv" is the final output file we should expect

**Comment by kmartinez834** [comment]
Per our meeting with Vijay, "glygen_set_new_site_fusion_output_contain_empty_site.tsv" also contains glycosylated proteins without site position:

```
pmid	uniprotkb_ac	protein	amino_acid	site_position
31958346	P23818	subunits		
25903135		glycoprotein		
31958346	P23818	GluA1		
19202066	O88351	IKKbeta		
30903686		proteins		
27480293		proteins		
31958346	P42261	GluA1	Asn	401
31958346		receptors		
16474139	P54296	M protein		
30903686		glycoproteins		
27480293		N-glycoproteins		
31577193				
16474139		proteins		
16474139		glycoprotein		
```
