### ISSUE TITLE
Detailed testing on tst.glygen.org

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#686]
Reporting issues that I've found while testing: 

1. Video pre-view image not showing on the page. I checked all video APIs and got the 401 error unauthorized message for all:

<img width="330" alt="Screen Shot 2023-09-13 at 4 12 48 PM" src="https://github.com/glygener/glygen-issues/assets/61590108/e1dee373-8999-4a0a-896f-9e7b4e60166b">

2. For Data -> Data (https://data.tst.glygen.org), BCOs aren't loading:3. 

<img width="1427" alt="Screen Shot 2023-09-13 at 4 15 04 PM" src="https://github.com/glygener/glygen-issues/assets/61590108/9102cf0a-5bb7-470a-9828-97ff65d19974">

3. On the same page as 2 above, scroll down, the logo images aren't showing in the bottom banner: 

<img width="953" alt="Screen Shot 2023-09-13 at 4 15 49 PM" src="https://github.com/glygener/glygen-issues/assets/61590108/497fc7af-f55d-4bc4-9508-0dc82ec498ba">

4.  Like reported in 2 and 3, BCOs and readme links are not displaying the content.

5. SPARQL examples (https://sparql.tst.glygen.org) aren't loading

**Comment by kmartinez834** [comment]
@JingyueWu Can you please open ticket for Robel for # 5

https://data.tst.glygen.org/ is running again.  Continue testing https://tst.glygen.org/

**Comment by JingyueWu** [comment]
Okay will do. @kmartinez834
