### ISSUE TITLE
Update BCO species tags

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#687]
- misc/dataset2species.csv has been updated
---> Please use this file to update BCOs species tags

**Comment by rykahsay** [comment]
done, check https://data.tst.glygen.org/

**Comment by kmartinez834** [comment]
These BCOs look good.  The misc/dataset2species.csv only includes files that don't begin with human/mouse/rat/etc. 
--> Can you change BCOs for datasets that start with yeast* from "Saccharomyces cerevisiae (strain atcc 204508 / s288c)" to "Saccharomyces cerevisiae S288C":

![image](https://github.com/glygener/glygen-issues/assets/90285371/44db0013-ef84-468a-9215-d0c4c1da512d)

**Comment by rykahsay** [comment]
done

**Comment by kmartinez834** [comment]
Looks good 👍
