### ISSUE TITLE
Contact Genomics England for new gene names.

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#689]
Please contact Genomics England for using of new gene names for ISPD and TMEM5

TMEM5 is now RXYLT1 (Q9Y2B1)
ISPD is now CRPPA (A4D126)

Draft an email and share it with me. Refer to the downloaded file and version we are using for Genomics England.

Contact
Sarah Leigh​
Scientific Curator
e: Sarah.Leigh@genomicsengland.co.uk | 

_Originally posted by @jeet-vora in https://github.com/glygener/glygen-issues/issues/400#issuecomment-1720101840_

**Comment by JingyueWu** [comment]
@jeet-vora please review the below draft. Is the file congenital_disorders_of_glycosylation.tsv and the version is 2.1.1?

Subject: Request to Update Gene Names in Genomics England - TMEM5 and ISPD

Hi Sarah,

I hope this email finds you well. I am writing on behalf of the Mazumder Lab at GWU regarding a request to update gene names in our Genomics England dataset. We have recently come across updated nomenclature for two genes, and we would like to align our data with these changes for accuracy and consistency. The gene names in question are TMEM5 and ISPD.

Based on the latest information we have obtained, we propose the following updates:

TMEM5:
Current Name: TMEM5
Proposed New Name: RXYLT1
Uniprot ID: Q9Y2B1

ISPD:
Current Name: ISPD
Proposed New Name: CRPPA
Uniprot ID: A4D126

To ensure that we are using the correct versions of these gene names, we kindly request access to any relevant files or resources that Genomics England provides for this purpose. If there are specific procedures or documentation required for us to make this update in our dataset, please let us know, and we will be happy to comply.

We appreciate your assistance in helping us maintain the highest standards of data accuracy in our genomics research. If you have any questions or need further information from us, please feel free to reach out. We are eager to proceed with these updates as soon as possible to ensure the consistency and reliability of our data.

Thank you for your attention to this matter, and we look forward to your guidance on the necessary steps to implement these changes.

Best regards,

**Comment by JingyueWu** [comment]
@jeet-vora please review.

**Comment by jeet-vora** [comment]
@JingyueWu Please add the dataset namen and link from GE below and send the email to both Ellen and Sarah ellen.mcdonagh@genomicsengland.co.uk and [panelapp@genomicsengland.co.uk](mailto:panelapp@genomicsengland.co.uk)

cc Raja, Karina, myself


Subject: Request to Update Gene Names/Symbols in Genomics England - TMEM5 and ISPD

Hi Elllen and Sarah,

I hope this email finds you well. I am writing on behalf of GlyGen regarding a request to update gene names in the Genomics England dataset that we integrate into GlyGen (Dataset name and Link - .....). We have recently come across updated nomenclature for these two genes, and we would like to align our data with these changes for accuracy and consistency.  The gene names in question are TMEM5 and ISPD and are currently being filtered out in our pipeline.

Below are the new gene names/symbols:

TMEM5:
Current GE Name: TMEM5
HGNC/UniProtKB New Name: RXYLT1
Uniprot ID: Q9Y2B1

ISPD:
Current GE Name: ISPD
HGNC/UniProtKB New Name: CRPPA
Uniprot ID: A4D126

To ensure that we are using the correct names/symbols of these gene names, we would like to ask you to review the information and update any relevant files containing these genes in Genomics England. 

Thank you and let us know for any questions.

Best regards,
The GlyGen Team

**Comment by jeet-vora** [comment]
Dear Jingyue
Thank you for contacting me about the discrepancy of gene names.  Unfortunately, within PanelApp there are a number genes, where the old gene name is still displayed.  We are unable to update these genes at present, but they should all have a “New gene name” tag added, to alert users of this issue.  Would you be able to adjust your pipeline to find these old gene names?
 
I apologise for my delayed reply. I thought I had responded in December 2023.
 
Best regards
 
Sarah

Hi Sarah,
Happy New Year and no worries.

While processing the dataset we will ensure that we update the old gene names to the new names.

@Jingyue, please create a ticket to make changes in our processing workflow.
