### ISSUE TITLE
Update glycan structure dictionary links & xrefs

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#69]
- [x] In file allmotifs.tsv, change GlycanDictionary accession prefix from GD to GSD
- [x] Download new source file from Glycan Structure Dictionary wiki page
- [x] Request processing of glycan_dictionary.csv and glycan_xref_dictionary.csv files
- [x] Change xref_info.csv "xref_badge" from Glycan Dictionary to Glycan Structure Dictionary
- [x] Add GSD xref to motifs page

**Comment by kmartinez834** [comment]
Saved accession prefix in /downloads/glytoucan/current/export/allmotifs.tsv

Original file is named allmotifs.tsv-original

**Comment by kmartinez834** [comment]
Process Glycan Structure Dictionary datasets #91

**Comment by kmartinez834** [comment]
Add Glycan Structure Dictionary xref to motif API #93

**Comment by kmartinez834** [comment]
@jeet-vora can you take a look at the checklist above and let me know if I missed anything?

**Comment by jeet-vora** [comment]
@kmartinez834 You have covered it all. Thanks
