### ISSUE TITLE
Banner for GlyGen webinar 9/23

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#690]
Add a banner for production and beta:

Headline: GlyGen Webinar with Dr. Marissa Maciej-Hulme
Text: Pushing new frontiers in GAGomics
Link: https://wiki.glygen.org/GlyGen_Webinar_Series

You can take date and time from the wiki. Banner can be active right now till the talk.

@jeet-vora let us know if we need to update something.

**Comment by sujeetvkulkarni** [comment]
done on prod - banner came early than scheduled. 
Will do on beta after 2.2 push.

**Comment by sujeetvkulkarni** [comment]
done.
