### ISSUE TITLE
Add tool tip for new biomarker sections

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#691]
On biomarker detail page:
![image](https://github.com/glygener/glygen-issues/assets/90285371/c3db738f-3c0c-4fe3-a4cd-266b1789b0d2)

On glycan, protein, motif & publication pages:
![image](https://github.com/glygener/glygen-issues/assets/90285371/026ab896-f44f-43ab-a014-b08e99947311)

**Comment by kmartinez834** [comment]
@ReneRanzinger where do I add tool tip descriptions?

**Comment by ReneRanzinger** [comment]
@kmartinez834 send them to @sujeetvkulkarni . They are either hard coded or their is a configuration file in the frontend.

**Comment by kmartinez834** [comment]
@sujeetvkulkarni --> Please add/update the following tool tips:

| Page | Section | Description |
| ----------- | ----------- | ----------- |
| Biomarker Detail | Biomarker Description| The Biomarker Description section describes the measured change of the biomarker entity within a specific tissue and disease. |
| Biomarker Detail |Components | The Components section contains glycan and protein accessions associated with the biomarker.|
| Glycan Detail | Expression | The Expression section contains information on the expression of the glycan within tissues and cell lines. |
| Glycan Detail |Biomarkers| The Biomarkers section contains biomarkers that involve the glycan. |
| Protein Detail |Biomarkers| The Biomarkers section contains biomarkers that involve the protein. |
| Motif Detail |Biomarkers| The Biomarkers section contains biomarkers that involve the motif. |
| Publication Detail |Biomarkers| The Biomarkers section contains biomarkers referenced in the publication. |

**Comment by sujeetvkulkarni** [comment]
dbc5e1eee2800220e857baa6665a8d11c391bfdc

**Comment by sujeetvkulkarni** [comment]
done - please verify.

**Comment by kmartinez834** [comment]
Looks good...I just realized the publication expression section also says "glycan (attached to proteins)." Can you please make one more update?

| Page | Section | Description |
| ----------- | ----------- | ----------- |
| Publication Detail | Expression | The Expression section contains information on the expression of glycans within tissues and cell lines. |

**Comment by sujeetvkulkarni** [comment]
d82dca46ab8735311cf38f8aba63629b2515ab60

**Comment by sujeetvkulkarni** [comment]
done please check on tst server.

**Comment by rykahsay** [comment]
why am I assigned this ticket?
@rykahsay By mistake. Should have assigned it @kmartinez834

**Comment by kmartinez834** [comment]
Looks good
