### ISSUE TITLE
G49108TO (O-GlcNAc) Error

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#692]
Having issues with the jumbo glycan again...

https://tst.glygen.org/glycan/G49108TO

![image](https://github.com/glygener/glygen-issues/assets/90285371/e95f9d37-4efd-4728-9b3d-2e41b2ff64a7)

https://api.tst.glygen.org/glycan/detail/G49108TO/
``` json
{
  "error_list": [
    {
      "error_code": "non-existent-record"
    }
  ],
  "reason": {
    "type": "added",
    "description": "introduced in data release 1.0.13"
  }
}
```

**Comment by rykahsay** [comment]
<img width="1342" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/7426aafa-ec7b-4e34-9638-289cf27fc54e">

<img width="1351" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/386bd51e-1a8a-4dbb-9304-cfb505a593f5">

**Comment by kmartinez834** [comment]
1. Page is working, however Expression section is empty:
![image](https://github.com/glygener/glygen-issues/assets/90285371/87415fb7-976d-4755-95be-2872f0ed67b0)
There should be 18326 records according to https://api.tst.glygen.org/glycan/detail/G49108TO/
```
{
      "table_id": "expression",
      "table_stats": [
        {
          "field": "total",
          "count": 18326
        },
        {
          "field": "total_sites",
          "count": 18326
        }
      ],
```

2. I only see 127 Publications:

![image](https://github.com/glygener/glygen-issues/assets/90285371/a00b2008-118d-47c0-9520-2731de9a7b70)

**Comment by rykahsay** [comment]
@kmartinez834 --- you have to make sure the target_objects in "generated/misc/dataset-masterlist.json" is set to both "protein" and "glycan" if the citation dataset file contributes to both protein and glycan objects. I will try to edit this for now ... 

<img width="842" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/29d657a3-df3d-4134-97f6-6120102755f8">

**Comment by rykahsay** [comment]
check now

**Comment by kmartinez834** [comment]
@rykahsay I added "glycan" for the following as well, please reprocess.

"name": "citations_glycosylation_sites_uniprotkb"
"name": "citations_glycosylation_sites_o_gluc"
"name": "citations_glycosylation_sites_tyr_o_linked"

**Comment by rykahsay** [comment]
citations_glycosylation_sites_uniprotkb does not have glytoucans but it doesn't harm anything

**Comment by rykahsay** [comment]
Done, please check
<img width="715" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/0ce3546a-3ed2-4d87-803f-daad7aa50385">

**Comment by kmartinez834** [comment]
Your first screenshot shows 2492 publication results for [G49108TO](https://tst.glygen.org/glycan/G49108TO).  Now I'm seeing 969, is this correct?
![image](https://github.com/glygener/glygen-issues/assets/90285371/b72f5430-a2d5-40c0-b692-3c68e96f2c82)

**Comment by rykahsay** [comment]
```
cat reviewed/*citations* | grep G49108TO | awk -F"\",\"" '{print $6, $7}' | sort -u |wc
    969    1938   27925
```

**Comment by kmartinez834** [comment]
Ok, I see now the 2492 publications was for P04637-1.
