### ISSUE TITLE
Biomarker LOINC code links

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#695]
There are some protein biomarkers with multiple LOINC codes. Make this field an array and add links in next version.
https://api.tst.glygen.org/biomarker/detail/A0461/
"loinc_code": "10334-1|21365-2|15081-3|2485-1"

**Comment by kmartinez834** [comment]
--> Loinc.org requires user registration/login so we will not create links for loinc codes

@rykahsay can you replace pipes with a comma+space in the biomarker api loinc values?

ex. https://api.tst.glygen.org/biomarker/detail/A0461/
`"loinc_code": "10334-1, 21365-2, 15081-3, 2485-1"`

**Comment by rykahsay** [comment]
Done --> json files at /data/projects/glygen/generated/datasets/jsondb/biomarkerdb/*.json reflect this change and will be propagated to tst server API when we finish making datasets and deploy data 2.3 to tst

<img width="729" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/7f09ddcc-05a2-44c6-8573-6257821eb3aa">
