### ISSUE TITLE
GSA and CFDE logos are smooshed

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#696]
Looks like the dimensions got messed up a bit:

![image](https://github.com/glygener/glygen-issues/assets/90285371/e361a75c-a914-49e5-8369-6496a6eb746f)

**Comment by sujeetvkulkarni** [comment]
have fixed this with latest tst release.
![Screenshot 2023-09-15 at 2 33 42 PM](https://github.com/glygener/glygen-issues/assets/13891482/1aabaa58-1b59-45c5-9e4a-a12b59655717)

**Comment by kmartinez834** [comment]
👍
