### ISSUE TITLE
Glycan simple search - Composition not working

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#697]
Example glycan composition giving an error:

https://tst.glygen.org/glycan-search/

![image](https://github.com/glygener/glygen-issues/assets/90285371/0b6afbcc-b660-4a5c-a7fd-db5792d6dd04)

**Comment by kmartinez834** [comment]
It only results in an error when using the "Glycan" Category.  Works when Category is "Any":

https://tst.glygen.org/glycan-list/af97e7e35381fbb9114c9c158cc78b69

**Comment by rykahsay** [comment]
Check now

**Comment by kmartinez834** [comment]
Looks good
