### ISSUE TITLE
Glycan structure search example not working

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#698]
https://tst.glygen.org/glycan-search/

![image](https://github.com/glygener/glygen-issues/assets/90285371/4cb0d004-5922-40f5-8853-b32865636b6d)

**Comment by kmartinez834** [comment]
Same issue with Substructure Search:

![image](https://github.com/glygener/glygen-issues/assets/90285371/22902caf-bd6e-4926-ae1f-e6d7079b4e7c)

**Comment by rykahsay** [comment]
check now

**Comment by kmartinez834** [comment]
Looks good
