### ISSUE TITLE
SPARQL page isn't loading

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#700]
https://sparql.tst.glygen.org 

<img width="1437" alt="Screen Shot 2023-09-15 at 2 51 41 PM" src="https://github.com/glygener/glygen-issues/assets/61590108/3c207172-5ccb-481b-9076-9a25a446ef8f">

**Comment by rykahsay** [comment]
I don't deploy it on tst -- please close this ticket
