### ISSUE TITLE
0 results for site search @ N

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#701]
tst says 0 sites, expected ~44931 sites 

https://tst.glygen.org/site-list/bdbfad65b202504ab94fc3e4754f8980

![image](https://github.com/glygener/glygen-issues/assets/90285371/40756336-a83d-481f-8995-c370caf5377e)

**Comment by kmartinez834** [comment]
Site list isn't loading from SuperSearch either:
![image](https://github.com/glygener/glygen-issues/assets/90285371/e019b190-7648-479e-8925-3c78aef99851)

https://tst.glygen.org/site-list/e53289a5441fa1fc7d160467b061521a/sups
![image](https://github.com/glygener/glygen-issues/assets/90285371/57a56522-1b66-43d8-9bb9-da07c6b97db5)

**Comment by rykahsay** [comment]
@sujeetvkulkarni  ... can you please give me the corresponding API request for this?

**Comment by sujeetvkulkarni** [comment]
@rykahsay 

API calls for
https://tst.glygen.org/site-list/bdbfad65b202504ab94fc3e4754f8980

https://api.tst.glygen.org/supersearch/search?query=
{"concept_query_list":[{"concept":"site","query":{"aggregator":"$and","unaggregated_list":[{"path":"site_seq","order":0,"operator":"$eq","string_value":"N"}],"aggregated_list":[]}}]}

https://api.tst.glygen.org/supersearch/list?query=
{"id":"bdbfad65b202504ab94fc3e4754f8980","offset":1,"sort":"hit_score","limit":20,"order":"desc","filters":[]}

API calls for
https://tst.glygen.org/site-list/e53289a5441fa1fc7d160467b061521a/sups

https://api.tst.glygen.org/supersearch/list?query=
{"id":"e53289a5441fa1fc7d160467b061521a","offset":1,"sort":"hit_score","limit":20,"order":"desc","filters":[]}

**Comment by rykahsay** [comment]
try now

**Comment by kmartinez834** [comment]
It's working now
