### ISSUE TITLE
Holiday and off-time for 2.3

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#704]
For the task planning in 2.3 we need to consider holiday and other times we can not work on the project (e.g. SfG meeting, CFDE meeting). Please send you holiday plans and off-times to Rene via email:
- [x] @kmartinez834 
- [x] @jeet-vora 
- [x] @sujeetvkulkarni 
- [x] @rykahsay

**Comment by rykahsay** [comment]
A couple of days on December when I am on transit/flight
