### ISSUE TITLE
Quick Search - Yeast glycosyltransferase error

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#706]
Getting an error when searching for Yeast glycosyltransferases on Quick Search.  There should be 69 according to yeast_protein_glycosyltransferase.csv
https://tst.glygen.org/quick-search/

![image](https://github.com/glygener/glygen-issues/assets/90285371/5777516c-c013-49aa-bf3a-b98ce60ab5fb)

![image](https://github.com/glygener/glygen-issues/assets/90285371/4df4c4d6-3189-46f0-bcd1-77b14cf7f66a)

**Comment by kmartinez834** [comment]
Same issue for glycohydrolases.  There should be 38 results per yeast_protein_glycohydrolase.csv

![image](https://github.com/glygener/glygen-issues/assets/90285371/b0a60451-7b03-4987-8ebe-89ec94dd54a6)

**Comment by kmartinez834** [comment]
Also getting an error for glycosylated proteins:

![image](https://github.com/glygener/glygen-issues/assets/90285371/2e8372dd-eb62-44fb-94c3-22ee3e6f1ca6)

**Comment by rykahsay** [comment]
try now

**Comment by kmartinez834** [comment]
It is working now
