### ISSUE TITLE
Search icon for yeast on protein page is on the next line

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#709]
Was seen on Karinas screen during the meeting.

**Comment by sujeetvkulkarni** [comment]
@kmartinez834 can you please give link/id for the page.

**Comment by kmartinez834** [comment]
https://tst.glygen.org/glycan/G30505TQ

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger 
We have to choose between 3 per row to two per row.
If we choose three per row then it would look like this (current implementation).

https://tst.glygen.org/glycan/G30505TQ#Organism

![Screenshot 2023-09-20 at 12 49 20 PM](https://github.com/glygener/glygen-issues/assets/13891482/a09e8d89-39b5-4c2b-84be-7aea8462d702)

https://tst.glygen.org/glycan/G17689DH#Organism

![Screenshot 2023-09-20 at 12 30 05 PM](https://github.com/glygener/glygen-issues/assets/13891482/9a52aa29-44d9-4fd7-8772-e8def1f84a9d)

If we choose two per row then it would look like this.

https://tst.glygen.org/glycan/G30505TQ#Organism

![Screenshot 2023-09-20 at 12 29 35 PM](https://github.com/glygener/glygen-issues/assets/13891482/eca2033a-7745-453a-90e6-abe8c35b6377)

https://tst.glygen.org/glycan/G17689DH#Organism

![Screenshot 2023-09-20 at 12 29 06 PM](https://github.com/glygener/glygen-issues/assets/13891482/a04fe28d-788b-4f96-b5b3-e58f8054b78a)

**Comment by ReneRanzinger** [comment]
Go with 2 for now. We will add it to the agenda next week.

**Comment by sujeetvkulkarni** [comment]
a57fcb495a0c270f5c444b5b3c48bdc4e7998bd9
