### ISSUE TITLE
Accssion history error msgs

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#71]
See the task also at the bottom.

Related  - https://github.com/glygener/glygen-issues/issues/71
Related to https://github.com/glygener/glygen-frontend/issues/151

| No | Accession Type | Accession Status | Message | Example |
| ---- | ------- | ------- | -------- | ------- |
| 1 | Protein | Merged or replaced accession | The UniProtKB accession XXX has been replaced with accession YYY | Q921W5 replaced by P42867 , **Q13065 replaced by P0DTW1 and P0DSO3 (one accession replaced by two accession)** |
| 2 | Protein | Accession that was part of GlyGen but is now obsolete | The accession is no longer a valid UniProtKB accession in GlyGen | G3V9U9 |
| 3 | Protein | Gibberish Accession | The accession XXX does not exist in GlyGen | XGHDGUP |
| 4 | Protein | Accession was never part of GlyGen accessions (but a valid UniProtKB accession) | The UniProtKB accession XXX does not exist in GlyGen but exists in UniProtKB | Q921W5 (will have to wait for EBI dump) |
| 5 | Glycan | Merged or replaced accession | The GlyTouCan accession XXX has been replaced with accession YYY | G00318GT replaced by G63349UI|
| 6 | Glycan | Accession that was part of GlyGen but is now obsolete | The accession is no longer a valid GlyTouCan accession in GlyGen | G01410DC |
| 7 | Glycan | Gibberish Accession | The accession XXX does not exist in GlyGen | XGHDGUP |
| 8 | Glycan | Accession was never part of GlyGen accessions (but a valid GTC accession) | The GlyTouCan accession XXX does not exist in GlyGen but exists in GlyTouCan | G03456QP |

These error messages are to be shown in the list pages of glycan and protein searches, GlyGen Mapper
For No 4 entire UniProtKB accession dump is needed to be checked (Preethi is working on the dump)
For No 8 entire GlyTouCan accession dump is needed to be checked (Nathan has provided GTC dump)

- [ ] @rykahsay Robel to provide error msg types from API response
- [ ] Jeet to update the table with addition of types received from Robel

**Comment by rykahsay** [comment]
The are the case I am covering at these point. 
@sujeetvkulkarni  -- the only time you need to create a link is when the "reason.type" key path has a value of "replacement_in_glygen"

## Protein
```
{
        "valid_uniprotkb":{
            "replacement_in_glygen":{
                "conditions":[
                    "$QRY_AC was a valid UniProtKB accession",
                    "was replaced by $NEW_AC",
                    "$NEW_AC is in glygen"
                ],
                "example":{
                    "request":"https://api.tst.glygen.org/protein/detail/Q69ZH5/",
                    "response":{
                        "error_list": [{"error_code": "non-existent-record"}],
                        "reason":{
                            "description": "Valid old UniProtKB accession which was replaced by Q9CXB8",
                            "replacement_id": "Q9CXB8-1",
                            "type": "replacement_in_glygen"
                        }
                    }
                }
            },
            "replacement_not_in_glygen":{
                "conditions":[
                    "$QRY_AC was a valid UniProtKB accession",
                    "was replaced by $NEW_AC",
                    "$NEW_AC is not in glygen"
                ],
                "example":{
                    "request":"https://api.tst.glygen.org/protein/detail/G3X9Q5/",
                    "response":{
                        "error_list": [{"error_code": "non-existent-record"}],
                        "reason":{
                            "description": "Valid old UniProtKB accession which was replaced by O55074",
                            "replacement_id": "O55074",
                            "type": "replacement_not_in_glygen"
                        }
                    }
                }
            },
            "discontinued_in_glygen":{
                "conditions":[ 
                    "$QRY_AC was a valid UniProtKB accession",
                    "was in GlyGen", 
                    "was discontinued"
                ],
                "example":{
                    "request":"https://api.tst.glygen.org/protein/detail/B1AXE0/",
                    "response":{
                        "error_list": [{"error_code": "non-existent-record"}],
                        "reason": {
                            "description": "was in GlyGen but discontinued in data release 1.5.11",
                            "type": "discontinued_in_glygen"
                        }
                    }
                }
            },
            "never_in_glygen":{
                "conditions":[
                    "$QRY_AC was a valid UniProtKB accession",
                    "was never in GlyGen"
                ],
                "example":{
                    "request":"https://api.tst.glygen.org/protein/detail/E9PWH1/",
                    "response":{
                        "error_list": [{"error_code": "non-existent-record"}],
                        "reason": {
                            "description": "Valid current UniProtKB accession",
                            "type": "never_in_glygen"
                        }
                    }
                }
            },
        },
        "invalid":{
            "conditions":[
                "$QRY_AC is an invalid accession"
            ],
            "example":{
                "request":"https://api.tst.glygen.org/protein/detail/G00002CF/",
                "response":{
                    "error_list": [{"error_code": "non-existent-record"}],
                    "reason": {
                        "description": "Invalid Accession",
                        "type": "invalid"
                    }
                }
            }
        },  
    }

```
## Glycan
```
{
        "valid_glytoucan":{
            "replacement_in_glygen":{
                "conditions":[
                    "$QRY_AC was a valid GlyTouCan accession",
                    "was replaced by $NEW_AC",
                    "$NEW_AC is in glygen"
                ],
                "example":{
                    "request":"https://api.tst.glygen.org/glycan/detail/G00318GT/",
                    "response":{
                        "error_list": [{"error_code": "non-existent-record"}],
                        "reason": {
                            "description": "replaced by G63349UI in data release 1.10.6",
                            "replacement_id": "G63349UI",
                            "type": "replacement_in_glygen"
                        }
                    }
                }
            },
            "discontinued_in_glygen":{
                "conditions":[ 
                    "$QRY_AC was a valid GlyTouCan accession",
                    "was in GlyGen", 
                    "was discontinued"
                ],
                "example":{
                    "request":"https://api.tst.glygen.org/glycan/detail/G04307DP/",
                    "response":{
                        "error_list": [{"error_code": "non-existent-record"}],
                        "reason": {
                            "description": "was in GlyGen but discontinued in data release 1.10.6",
                            "type": "discontinued"
                        }
                    }
                }
            },
            "never_in_glygen":{
                "conditions":[
                    "$QRY_AC was a valid GlyTouCan accession",
                    "was never in GlyGen"
                ],
                "example":{
                    "request":"https://api.tst.glygen.org/glycan/detail/G00001LE/",
                    "response":{
                        "error_list": [{"error_code": "non-existent-record"}],
                        "reason": {
                            "description": "Valid current GlyTouCan accession",
                            "type": "never_in_glygen"
                        }
                    }
                }
            },
        },
        "invalid":{
            "conditions":[
                "$QRY_AC is an invalid accession"
            ],
            "example":{
                "request":"https://api.tst.glygen.org/glycan/detail/Q9CXB8/",
                "response":{
                    "error_list": [{"error_code": "non-existent-record"}],
                    "reason": {
                        "description": "Invalid Accession",
                        "type": "invalid"
                    }
                }
            }
        },  
    }
```

**Comment by sujeetvkulkarni** [comment]
1. 
protein id in glycan detail api should return invalid id response.
glycan id in protein detail api should return invalid id response.
2.
replacement id should not be given in case of intermediate replaced ids.

**Comment by sujeetvkulkarni** [comment]
@rykahsay 
Looks like it does not cover case where Q13065 replaced by P0DTW1 and P0DSO3. It is only returning P0DSO3-1.

https://api.tst.glygen.org/protein/detail/Q13065

{"error_list": [{"error_code": "non-existent-record"}], "reason": {"type": "replacement_in_glygen", "replacement_id": "P0DSO3-1", "description": "replaced by P0DSO3-1 in data release 1.8.24"}}

**Comment by rykahsay** [comment]
@sujeetvkulkarni  -- please check now and note that property containing replacement IDs is a list now.

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/20584876/226665314-9432f7d8-00fa-41b7-b6f3-b385314039c8.png">


## Protein example requests
```
"https://api.tst.glygen.org/protein/detail/Q69ZH5/",
"https://api.tst.glygen.org/protein/detail/Q13065/"
"https://api.tst.glygen.org/protein/detail/G3X9Q5/"
"https://api.tst.glygen.org/protein/detail/B1AXE0/"
"https://api.tst.glygen.org/protein/detail/A0A161SEP9/"
"https://api.tst.glygen.org/protein/detail/A0A008XH72/"
"https://api.tst.glygen.org/protein/detail/G00002CF/"
```

## Glycan example requests
```
"https://api.tst.glygen.org/glycan/detail/G00318GT/"
"https://api.tst.glygen.org/glycan/detail/G04307DP/"
"https://api.tst.glygen.org/glycan/detail/G00001LE/"
"https://api.tst.glygen.org/glycan/detail/Q9CXB8/"
```

**Comment by sujeetvkulkarni** [comment]
@rykahsay 
A link is created for description in this case it would be difficult to create two links for same description.

**Comment by rykahsay** [comment]
"A link is created for description in this case it would be difficult to create two links for same description."

@sujeetvkulkarni -- not clear what you want me to do by assigning the ticket to me.

**Comment by jeet-vora** [comment]
Few comments @rykahsay @sujeetvkulkarni 
```
1. https://api.tst.glygen.org/protein/detail/B1AXE0/
{"error_list": [{"error_code": "non-existent-record"}], "reason": {"type": "discontinued_in_glygen", "description": "Valid current UniProtKB accession discontinued in GlyGen 1.5.11"}}

The UP ac has been obsolete in UP so calling it current is incorrect.
```

```
2. https://api.tst.glygen.org/protein/detail/Q13065/
{"error_list": [{"error_code": "non-existent-record"}], "reason": {"type": "replacement_in_glygen", "replacement_id_list": ["P0DSO3-1", "P0DTW1-1"], "description": "Valid old UniProtKB accession replaced by P0DSO3-1,P0DTW1-1 in data release 1.8.24"}}

Should we call **GlyGen** data release 1.8.24. Also are release version available for all such descriptions? Below example does not have the release version.

https://api.tst.glygen.org/protein/detail/G3X9Q5/
{"error_list": [{"error_code": "non-existent-record"}], "reason": {"description": "Valid old UniProtKB accession replaced by O55074", "replacement_id_list": ["O55074"], "type": "replacement_not_in_glygen"}} 

```

```
3. https://api.tst.glygen.org/protein/detail/A0A161SEP9/
{"error_list": [{"error_code": "exception-error-E6VX2H"}]}

Is this an error? This ac does not exist in GlyGen 
```

``` 
4. https://api.tst.glygen.org/glycan/detail/G04307DP/
{"error_list": [{"error_code": "non-existent-record"}], "reason": {"type": "discontinued_in_glygen", "description": "Valid current GlyTouCan accession discontinued in GlyGen 1.10.6"}}
How do you know it is valid ac in GTC. The ac has been archived in GTC. Calling it current GTC ac is incorrect. 
```

```
5. https://api.tst.glygen.org/glycan/detail/G00001LE/
{"error_list": [{"error_code": "non-existent-record"}], "reason": {"type": "never_in_glygen", "description": "Valid current GlyTouCan accession"}}

Shouldn't the description be - Valid current GlyTouCan accession not in GlyGen. The current description feels incomplete.
```

**Comment by sujeetvkulkarni** [comment]
remove bullet point from description.
use text Go to Protein:

**Comment by rykahsay** [comment]
@sujeetvkulkarni  ---> I am moving your  comment from issue 163 here:

/protein/E9PWH1
{"error_list": [{"error_code": "non-existent-record"}], "reason": {"description": "Valid current UniProtKB accession never been in GlyGen", "type": "never_in_glygen_current_in_uniprotkb"}}

Is this is a new type ("never_in_glygen_current_in_uniprotkb")? Is this similar to or replacement of "never_in_glygen".
And can you give me a similar example in Glycans.
Also it would be better if we use similar types in proteins or glycans and not use anything like uniprotkb or glytucan in type.

https://api.tst.glygen.org/glycan/detail/G00001LE returns "never_in_glygen".

**Comment by jeet-vora** [comment]
@rykahsay @ReneRanzinger @sujeetvkulkarni @kmartinez834 

In the new description I have removed the words **Valid** and **Current** because it is confusing and we may be incorrect. Feel free to change the decriptions.

| Category | api_link                                                                                                     | api_reason_description                                                             | new_api_reason_description                                                          | api_reason_type                           | frontend_description                                                                                                                                    |
| -------- | ------------------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------- | ----------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Protein  | [https://api.tst.glygen.org/protein/detail/Q69ZH5/](https://api.tst.glygen.org/protein/detail/Q69ZH5/)       | Valid old UniProtKB accession replaced by Q9CXB8-1                                 | Old UniProtKB accession replaced by Q9CXB8-1 in GlyGen data release XXX             | replacement_in_glygen                     |  Q69ZH5 is no longer valid Protein Id |<br>Valid old UniProtKB accession replaced by Q9CXB8-1                                                           |
| Protein  | [https://api.tst.glygen.org/protein/detail/Q13065/](https://api.tst.glygen.org/protein/detail/Q13065/)       | Valid old UniProtKB accession replaced by P0DSO3-1,P0DTW1-1 in data release 1.8.24 | Old UniProtKB accession replaced by P0DSO3-1,P0DTW1-1 in GlyGen data release 1.8.24 | replacement_in_glygen                     |  Q13065 is no longer valid Protein Id |<br>Valid old UniProtKB accession replaced by P0DSO3-1,P0DTW1-1 in data release 1.8.24                           |
| Protein  | [https://api.tst.glygen.org/protein/detail/G3X9Q5](https://api.tst.glygen.org/protein/detail/G3X9Q5)         | Valid old UniProtKB accession replaced by O55074                                   | Old UniProtKB accession replaced by O55074 not available in GlyGen                  | replacement_not_in_glygen                 |  G3X9Q5 is no longer valid Protein Id<br>Valid old UniProtKB accession replaced by O55074                                                               |
| Protein  | [https://api.tst.glygen.org/protein/detail/B1AXE0](https://api.tst.glygen.org/protein/detail/B1AXE0)         | Valid current UniProtKB accession discontinued in GlyGen 1.5.11                    | Old UniProtKB accession discontinued in GlyGen data release 1.5.11                  | discontinued_in_glygen                    |  B1AXE0 is no longer valid Protein Id |<br>Valid current UniProtKB accession discontinued in GlyGen 1.5.11                                              |
| Protein  | [https://api.tst.glygen.org/protein/detail/A0A161SEP9](https://api.tst.glygen.org/protein/detail/A0A161SEP9) | Valid current UniProtKB accession never been in GlyGen                             | UniProtKB accession not available in GlyGen                                         | never_in_glygen_current_in_uniprotkb      |  A0A161SEP9 is no longer valid Protein Id |<br>Valid current UniProtKB accession never been in GlyGen                                                   |
| Protein  | [https://api.tst.glygen.org/protein/detail/A0A008XH72](https://api.tst.glygen.org/protein/detail/A0A008XH72) | Valid discontinued UniProtKB accession never been in GlyGen                        | Old UniProtKB accession not available in GlyGen                                     | never_in_glygen_discontinued_in_uniprotkb |  A0A008XH72 is no longer valid Protein Id \\<br>Valid discontinued UniProtKB accession never been in GlyGen                                             |
| Protein  | [https://api.tst.glygen.org/protein/detail/G00002CF/](https://api.tst.glygen.org/protein/detail/G00002CF/)   | Invalid Accession                                                                  | Invalid Protein Accession                                                           | invalid                                   | The accession G00002CF does not exist in GlyGen                                                                                                         |
| Glycan   | [https://api.tst.glygen.org/glycan/detail/G00318GT/](https://api.tst.glygen.org/glycan/detail/G00318GT/)     | Valid old GlyTouCan accession replaced by G63349UI in data release 1.10.6          | Old GlyTouCan accession replaced by G63349UI in GlyGen data release 1.10.6          | replacement_in_glygen                     |  G00318GT is no longer valid Glycan Id |<br>Valid old GlyTouCan accession replaced by G63349UI in data release 1.10.6<br><br>    Go to Glycan: G63349UI |
| Glycan   | [https://api.tst.glygen.org/glycan/detail/G04307DP/](https://api.tst.glygen.org/glycan/detail/G04307DP/)     | Valid current GlyTouCan accession discontinued in GlyGen 1.10.6                    | GlyTouCan accession discontinued in GlyGen data release 1.10.6                      | discontinued_in_glygen                    |  G04307DP is no longer valid Glycan Id |<br>Valid current GlyTouCan accession discontinued in GlyGen 1.10.6                                             |
| Glycan   | [https://api.tst.glygen.org/glycan/detail/G00001LE/](https://api.tst.glygen.org/glycan/detail/G00001LE/)     | Valid current GlyTouCan accession                                                  | GlyTouCan accession not available in GlyGen                                         | never_in_glygen                           |  The GlyTouCan accession G00001LE does not exists in GlyGen |<br>Valid current GlyTouCan accession                                                      |
| Glycan   | [https://api.tst.glygen.org/glycan/detail/Q9CXB8/](https://api.tst.glygen.org/glycan/detail/Q9CXB8/)         | Invalid Accession                                                                  | Invalid Glycan Accession                                                            | invalid                                   | The accession Q9CXB8 does not exist in GlyGen                                                                                                           |

**Comment by rykahsay** [comment]
I have tried to make the responses uniform and meaningful as given below. Can we move on with this for now?

## Protein
```
>replacement_in_glygen (Q69ZH5)
 "description": "Old UniProtKB accession replaced by Q9CXB8-1",

>replacement_not_in_glygen (G3X9Q5)
 "description": "Old UniProtKB accession replaced by O55074",

>discontinued_in_glygen (B1AXE0)
 "description": "Current UniProtKB accession discontinued in GlyGen",

>never_in_glygen_current_in_uniprotkb (A0A161SEP9)
 "description": "Current UniProtKB accession never been in GlyGen",

>never_in_glygen_discontinued_in_uniprotkb (A0A008XH72)
 "description": "Discontinued UniProtKB accession never been in GlyGen",

>invalid (G00002CF)
 "description": "Invalid accession",
```

## Glycan
```
>replacement_in_glygen (G24211OH)
 "description": "Old GlyTouCan accession replaced by G74684KO"

>discontinued_in_glygen (G97470TL)
 "description": "Current GlyTouCan accession discontinued in GlyGen"

>never_in_glygen_current_in_glytoucan (G67362RV)
 "description": "Current GlyTouCan accession never been in GlyGen"

>never_in_glygen_discontinued_in_glytoucan (G23000QI)
 "description": "Discontinued GlyTouCan accession never been in GlyGen"

>invalid (Q9CXB8)
 "description": "Invalid accession"
```

**Comment by jeet-vora** [comment]
@rykahsay 
Remove "current" from descriptions.

B1AXE0 is not current and is currently replaced by other accession. Please look into it.

**Comment by rykahsay** [comment]
Please check now:

## protein
```
>replacement_in_glygen (Q69ZH5)
 Old UniProtKB accession replaced by Q9CXB8-1

>replacement_not_in_glygen (G3X9Q5)
 Old UniProtKB accession replaced by O55074

>discontinued_in_glygen (B1AXE0)
 Old UniProtKB accession discontinued in GlyGen

>never_in_glygen_current_in_uniprotkb (A0A161SEP9)
 UniProtKB accession never been in GlyGen

>never_in_glygen_discontinued_in_uniprotkb (A0A008XH72)
 Discontinued UniProtKB accession never been in GlyGen

>invalid (G00002CF)
 Invalid accession
```

## glycan
```
>replacement_in_glygen (G24211OH)
 Old GlyTouCan accession replaced by G74684KO

>discontinued_in_glygen (G97470TL)
 GlyTouCan accession discontinued in GlyGen

>never_in_glygen_current_in_glytoucan (G67362RV)
 GlyTouCan accession never been in GlyGen

>never_in_glygen_discontinued_in_glytoucan (G23000QI)
 Discontinued GlyTouCan accession never been in GlyGen

>invalid (Q9CXB8)
 Invalid accession
```

**Comment by sujeetvkulkarni** [comment]
be96e74add081eaf9cb14b290527a2aed34dc7e3

**Comment by sujeetvkulkarni** [comment]
Valid id in GlyTouCan: {id} -> link
Valid id in UniProtKB: {id} -> link

Replace "GlyTouCan accession never been in GlyGen" msg sent by backend. with above msg.

**Comment by sujeetvkulkarni** [comment]
glycan : G00000CV
protein : A0SVK0

**Comment by sujeetvkulkarni** [comment]
84cf10117c610962ea5d19f332191cb17f100527
