### ISSUE TITLE
home_init returns incorrect no of glycans for "Saccharomyces cerevisiae" in "statistics" section.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#711]
API : https://api.tst.glygen.org/pages/home_init
returns incorrect no of glycans for "Saccharomyces cerevisiae" in "statistics" section.

```
"statistics": [
        {
            "species": "Saccharomyces cerevisiae S288C",
            "glycans": 1,
            "proteins": 6060,
            "glycoproteins": 883
        },
```

**Comment by rykahsay** [comment]
check now

**Comment by sujeetvkulkarni** [comment]
The numbers are little different on home page (1102) and when you do glycan search (1101).
On home page ->
```
Yeast ->
Glycans  -> 1102
Proteins -> 6060
Glycoproteins -> 883
```
search with yeast as organism on beta ->
https://beta.glygen.org/glycan-list/84242e23b93ee6f8bf3ea59d52d345e3
![Screenshot 2023-09-25 at 12 23 32 PM](https://github.com/glygener/glygen-issues/assets/13891482/ba77a52e-eaaf-4bf7-9abb-b4bd8de462e0)

**Comment by rykahsay** [comment]
Corrected on tst ... beta will be updated when we finish addressing all issues

**Comment by sujeetvkulkarni** [comment]
done.
