### ISSUE TITLE
Setup meeting to discuss the Taxonomy ID issue

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#717]
Use of strain IDs vs species ID. Its also related to #680. @rajamazumder wants to have a dedicated meeting to come to a solution that we will use moving forward. People that should join the meeting are:
* @ReneRanzinger 
* @edwardsnj 
* @rykahsay 
* @kmartinez834 
* @rajamazumder 
* @jeet-vora 
* @mtiemeyer0919 (optional)

**Comment by jeet-vora** [comment]
Done
