### ISSUE TITLE
Use common names on homepage statistics

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#719]
Replace scientific names on homepage statistics with common names and collapse tax id's with the same common name:

``` json
{
	"Human": [9606],
	"Mouse": [10090],
	"Rat": [10116, 10114],
	"SARS-CoV-2": [2697049],
	"Fruit fly": [7227],
	"HCoV-SARS": [694009],
	"HCV-H": [63746],
	"HCV-Japanese": [11116],
	"Yeast": [559292, 4932]
}
```

**Comment by rykahsay** [comment]
check

**Comment by kmartinez834** [comment]
- Rat glycan count should include tax ID 10114
- Homepage stat says 20342 glycans but there are only 20258 with human annotation --> what are the extra 84 glycans?

![image](https://github.com/glygener/glygen-issues/assets/90285371/db5fe884-3068-4f5b-abc9-d708314510e6)

https://beta.glygen.org/glycan-list/f3cf76dbbbc57727260a5cab991ba11d
![image](https://github.com/glygener/glygen-issues/assets/90285371/ea2761c4-5220-4152-aaa1-7d42d29fa7da)

**Comment by rykahsay** [comment]
The rat issue has been addressed but for the human one, it looks like Nathan was not told to consider getting GlyTouCan IDs from the "composition" field in downloads/glyconnect/current/glyconnect_human.json

<img width="668" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/05a775fb-70e8-46a5-9961-6911e7c59b13">

**Comment by kmartinez834** [comment]
Nathan is getting annotations from the Glyconnect "composition field", however he's also applying rules to QC the species annotations (ex. Human: "No N-linked Xyl and no NeuGc, Alt").  G94826KT contains NeuGc so I'm assuming that's why this one is "false" for Human.  @edwardsnj can you confirm if I'm interpreting this correctly?

```
$ grep "G94826KT.*Human" downloads/glytoucan/current/export/species.tsv
G94826KT        Human   false
G94826KT        Human Evidence  GlyConnectComposition:940 TaxID 9606
```

**Comment by edwardsnj** [comment]
Correct.

**Comment by kmartinez834** [comment]
@rykahsay --> can you correct the homepage stats so only glycans with annotations in reviewed/glycan_species.csv are included?

**Comment by rykahsay** [comment]
check tst now

**Comment by kmartinez834** [comment]
Looks good
