### ISSUE TITLE
Update Automated API readme

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#72]
1. Fix missing ``` causing Step 6 and Step 7 to appear within code blocks:

![image](https://user-images.githubusercontent.com/90285371/221682513-0186aa7c-6c10-4a51-8cf2-64f099929e3e.png)

2. Someone running the python wrapper on the tst server will need the following info:
   - Clone the `glygen-backend-api` repository into their home directory
   - Check out the branch you want to test and confirm you are in the correct branch
   - Navigate to the tests folder before running `run_api_test.py`

**Comment by rykahsay** [comment]
Please check now

**Comment by kmartinez834** [comment]
👍 Readme format looks good

I added instructions for cloning the repo, checking out branch, etc to a new Testing section in the Data Integration doc in Sharepoint [here](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/[data_integration.docx](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/data_integration.docx?d=w0c84e59c4be6494d91cc017661cc9944&csf=1&web=1&e=gdelsQ)?d=w0c84e59c4be6494d91cc017661cc9944&csf=1&web=1&e=gdelsQ).
