### ISSUE TITLE
Biomarker evidence tags missing on publications page

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#720]
- Biomarker evidence tags missing on publication API (PMID:32619411):
A0117: GLY_000625, 32619411
A0118: GLY_000625, 32757722, 32619411
A0120: GLY_000625, 32619411
https://tst.glygen.org/publication/PubMed/32619411#Biomarkers
![image](https://github.com/glygener/glygen-issues/assets/90285371/7f8fd690-4abc-4730-813f-9da2a26b214f)

- Evidence tags missing on publication API (PMID:22435486):
A0419: GLY_000737, 22435486
https://tst.glygen.org/publication/PubMed/22435486#Biomarkers:
![image](https://github.com/glygener/glygen-issues/assets/90285371/2ae32d6b-0aa9-4eee-8b6f-1c1326b8bcdb)

**Comment by rykahsay** [comment]
check now

**Comment by kmartinez834** [comment]
Looks good
