### ISSUE TITLE
Add tissue and cell line name to glycan expression section

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#721]
Currently: 
--------
https://tst.glygen.org/glycan/G57321FI#Expression
![image](https://github.com/glygener/glygen-issues/assets/90285371/d4a45b7d-00a2-4b4e-a92a-b243a7d96e32)
![image](https://github.com/glygener/glygen-issues/assets/90285371/3e866626-0bab-4ab7-8461-8d25e7fccb77)

Add tissue and cell line names to be consistent with protein expression:
--------
https://api.tst.glygen.org/glycan/detail/G57321FI
``` json
"tissue": {
                "name": "urine",
                "namespace": "UBERON",
                "id": "0001088",
                "url": "http://purl.obolibrary.org/obo/UBERON_0001088"
            },

"cell_line": {
                "name": "AGS",
                "namespace": "CVCL",
                "id": "0139",
                "url": "https://web.expasy.org/cellosaurus/CVCL_0139"
```

Example:
![image](https://github.com/glygener/glygen-issues/assets/90285371/d07d59a2-d613-408f-9870-281023711ac3)

**Comment by sujeetvkulkarni** [comment]
a57fcb495a0c270f5c444b5b3c48bdc4e7998bd9

**Comment by sujeetvkulkarni** [comment]
Fixed but little slow because of - https://github.com/glygener/glygen-issues/issues/727.

can verify with https://beta.glygen.org/glycan/G17689DH#Expression

**Comment by kmartinez834** [comment]
Looks good
