### ISSUE TITLE
Yeast missing from protein list filters (beta)

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#725]
https://beta.glygen.org/protein-list/6587be4a62c9b51692ebacc17eb2a5b9
![image](https://github.com/glygener/glygen-issues/assets/90285371/ce97e937-a4cc-4373-8193-869da75d3bc2)

--> Add yeast to protein list API https://beta-api.glygen.org/protein/list/

``` json
 "options": [
          {
            "id": "Saccharomyces cerevisiae S288C",
            "label": "Yeast",
            "count": 6060,
            "order": 5
          },
```

**Comment by rykahsay** [comment]
Check it on tst ... don't worry about beta, will update once all issues are resolved on tst

**Comment by kmartinez834** [comment]
👍
