### ISSUE TITLE
beta-data.glygen.org version #

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#726]
- Data page version # is still 2.1.1

![image](https://github.com/glygener/glygen-issues/assets/90285371/07418c57-9464-475c-afe6-c35a2e115f10)

- BCO, README, and Download URL all say version v-x.x.x

![image](https://github.com/glygener/glygen-issues/assets/90285371/e41ebc32-cc93-4309-a95e-c8d0bed16fc8)

**Comment by rykahsay** [comment]
fixed on tst, beta will be updated soon

**Comment by kmartinez834** [comment]
On tst:

- Download link points to https://data.tst.glygen.org/ln2data/releases/data/v-x.x.x/reviewed/human_protein_masterlist.csv

- Readme still has v-x.x.x:
https://data.tst.glygen.org/GLY_000001
![image](https://github.com/glygener/glygen-issues/assets/90285371/07396179-4708-42f2-b2a8-11139fe0fbad)

**Comment by rykahsay** [comment]
sorry, check now

**Comment by kmartinez834** [comment]
Looks good, just need to add v-2.2.1 to tst and beta ln2data:

![image](https://github.com/glygener/glygen-issues/assets/90285371/fd737dad-7db7-4688-883f-f540bcabb7d7)

**Comment by rykahsay** [comment]
<img width="815" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/c111d5cc-3ea9-4fb4-9ef6-e831bfa96f9d">
