### ISSUE TITLE
exact matches in global search

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#728]
The following pages should also be supported as exact matches,
1. publicaton
2. motif
3. biomarker

**Comment by rykahsay** [comment]
You can use IDs:
10101234 --> publication
GGM.000001 --> motif
A0001 --> biomarker

I don't know how you are constructing the link to the detail pages, but all of them are pointing to protein. You will need to fix that based on the "type" property within the exact_match list


<img width="629" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/14aabf55-a5d4-4a9b-930d-d043c4d02f8b">

**Comment by sujeetvkulkarni** [comment]
@rykahsay 
For type : publication will need more information like PubMed or DOI to construct the link.

**Comment by rykahsay** [comment]
It come like this now:

```
"exact_match": [
        {
            "id": "pubmed.10101234",
            "name": "pubmed.10101234",
            "type": "publication"
        }
    ],
```

**Comment by sujeetvkulkarni** [comment]
currently doi ids fail in global search, have added comment in #946, #629

**Comment by sujeetvkulkarni** [comment]
Github : 9b589899780c693b9b629272a209c18c4028b14f
