### ISSUE TITLE
Contact Us and Feedback API service not working

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#730]
Robel,

The Contact Us and Feedback API service is not working on prd and beta of glygen.org, no email is recieved. The portal form is working.

Please share the database of the records for these form to look at the missed ones. Also add @JingyueWu to the recipient of emails.

@JingyueWu Please add testing of Contact Us and Feedback form in Quick Test and Detailed Test

<img width="569" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/ea2fea52-f910-4352-8b61-c5d4bfb09e39">

**Comment by jeet-vora** [comment]
Still pending

**Comment by rykahsay** [comment]
It is working now, and is also creating github ticket -- see the example I just created #1050
