### ISSUE TITLE
FAQ Page on beta and prd data.glygen.org not working

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#731]
- [ ] https://data.glygen.org/static/faq and https://beta-data.glygen.org/static/faq

<img width="1194" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/0525bdef-199d-4d24-a5cb-d4abe93b4d59">

- [ ] The footer on data.glygen.org is different from beta portal
The grant information has changed

GlyGen is supported and funded by the [National Institue of General Medical Sciences ](https://www.nigms.nih.gov/)under the grant # [1R24GM146616 - 01](https://reporter.nih.gov/project-details/10494610) and the [National Institutes of Health Office of Strategic Coordination - The Common Fund ](https://commonfund.nih.gov/)under the grant # [1OT2OD032092](https://reporter.nih.gov/project-details/10397274).

<img width="1416" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/4dd052dc-516a-4507-b9e2-5b743a5dff2a">

**Comment by rykahsay** [comment]
check

**Comment by jeet-vora** [comment]
Checked

![image](https://github.com/glygener/glygen-issues/assets/25825266/a40cd8a3-1920-4b69-8737-212f25d0e24b)
