### ISSUE TITLE
Change Organism names in BCOs

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#732]
@rykahsay or @kmartinez834 

As the organisms names have been changed from UniProtKB NCBI names, the organism names have to change in BCOs as well in the `extension_domain`

Please change in the BCOs (mostly protein and proteoform) where

- [ ] Sars coronavirus (sars-cov-1) (37) to Severe acute respiratory syndrome-related coronavirus 
- [ ] Sars coronavirus (sars-cov-2 or 2019-ncov) (36) to Severe acute respiratory syndrome coronavirus 2
- [ ] Hepatitis c virus (genotype 1a, isolate h) (30) to Hepatitis c virus (isolate h) 
- [ ] Hepatitis c virus (genotype 1b, isolate japanese) (27) to Hepatitis c virus (isolate japanese)

<img width="246" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/e3030a68-75ae-4d4e-9927-8c44c6460000">

<img width="254" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/e52bf683-6624-4fa0-aded-d38fdbb37a1f">

**Comment by rykahsay** [comment]
It is done on tst, beta will be updated soon

**Comment by jeet-vora** [comment]
Checked and done
