### ISSUE TITLE
G49108TO missing in Publication pages/API

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#733]
G49108TO has expression evidence from PMIDs 30703153 and 28604694.  However, these publication pages and APIs show 0 referenced glycans and 0 expression records.

https://tst.glygen.org/glycan/G49108TO#Expression
![image](https://github.com/glygener/glygen-issues/assets/90285371/bc8cda20-ac1f-4aa0-ab4d-85fbf8821a20)

https://api.tst.glygen.org/publication/detail/
``` json
{
      "table_id": "referenced_glycans",
      "table_stats": [
        {
          "field": "total",
          "count": 0
        }
      ]
    },
```

**Comment by kmartinez834** [comment]
Issue related to #692

**Comment by rykahsay** [comment]
Fixed, please check

<img width="447" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/4b2b63b8-f8fc-4888-bae0-b575270576a4">

**Comment by kmartinez834** [comment]
Looks good
