### ISSUE TITLE
Super Search: Organism count

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#736]
https://tst.glygen.org/super-search/

The current super search organism count is 8 which should be 9 in all because of protein.
However, the glycan organisms are at genus level whereas proteins are at species|strain|isolate level.

![image](https://github.com/glygener/glygen-issues/assets/25825266/0e62d111-5989-4539-9382-9514f5755116)

Should the supersearch show all the organisms together, glycan and protein combined?

 Protein                                               | Glycan                                                |
| ----------------------------------------------------- | ----------------------------------------------------- |
|                                                       |                                                       |
| Drosophila melanogaster                               | Drosophila melanogaster                               |
| Hepatitis C virus (isolate H)                         | Hepatitis C virus (isolate H)                         |
| Hepatitis C virus (isolate Japanese)                  | Homo sapiens                                          |
| Homo sapiens                                          | Mus musculus                                          |
| Mus musculus                                          | Rattus norvegicus                                     |
| Rattus norvegicus                                     | Saccharomyces cerevisiae                              |
| Saccharomyces cerevisiae S288C                        | Severe acute respiratory syndrome coronavirus 2       |
| Severe acute respiratory syndrome coronavirus 2       | Severe acute respiratory syndrome-related coronavirus |
| Severe acute respiratory syndrome-related coronavirus |

FYI @JingyueWu

**Comment by rykahsay** [comment]
check now

**Comment by jeet-vora** [comment]
works

**Comment by jeet-vora** [comment]
works
