### ISSUE TITLE
Map these BCO IDs to output file names

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#738]
when editing your draft BCOs automatically, I shouldn't have emptied the io_domain.output_subdomain list. This is something you populate. I was able to recover it from release folder for most but was not able for the following. 
Please edit the drafts for the following BCOs to populate io_domain.output_subdomain.

```
GLY_000705
GLY_000706
GLY_000726
GLY_000740
GLY_000741
GLY_000747
GLY_000748
GLY_000765
GLY_000777
GLY_000795
GLY_000797
GLY_000817
GLY_000818
GLY_000819
GLY_000820
```

**Comment by jeet-vora** [comment]
@rykahsay - Three BCOs edited `GLY_000741 | GLY_000748 | GLY_000817`. Others do not exist or are retired.


| BCO        | Status         |
| ---------- | -------------- |
| GLY_000705 | Does not exist |
| GLY_000706 | Does not exist |
| GLY_000726 | Retired        |
| GLY_000740 | Retired        |
| GLY_000741 | **Added**          |
| GLY_000747 | Retired        |
| GLY_000748 | **Added**          |
| GLY_000765 | Retired        |
| GLY_000777 | Retired        |
| GLY_000795 | Retired        |
| GLY_000797 | Retired        |
| GLY_000817 | **Added**          |
| GLY_000818 | Retired        |
| GLY_000819 | Retired        |
| GLY_000820 | Retired        |
