### ISSUE TITLE
2.3 Dataset plan

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#746]
Robel will provide a skeleton what this is.

**Blocker for**
* #747 
* #748

**Comment by rykahsay** [comment]
A simple CSV file (generated/misc/dataset_plan_2.3.csv) should be created at the beginning of each release with the following format. 

The status field can have the following values --> ["new", "structural_change", "volume_increase", "volume_decrease", ""]

```
file_name_pattern,status
dicty_protein_*.csv,new
dicty_proteoform_*.csv,new
*_proteoform_glycosylation_sites_glyconnect.csv,volume_increase
```
