### ISSUE TITLE
QC of 2.3 processed data

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#756]
QC of all datasets generated by Robel in #755.

**Dependencies:**
* #746
* #747 
* #748 
* #749 
* #750 
* #751 
* #752 
* #753 
* #754 
* #755

**Comment by Luke-Johnson-5** [comment]
Qc for * _ protein_* and * _ proteoform_* datasets completed on 12/22/23

**Comment by kmartinez834** [comment]
QC for *proteoform* and *glycan* datasets completed
