### ISSUE TITLE
Implement Glycan Highlighting Widget for Glycan details page

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#758]
Implement the Widget based on the Mockups in #497. Documentation for the SVG and JSON can be found in #496.

Examples can be found:
* https://glymage.glyomics.org/demo/demo1.html
* https://glymage.glyomics.org/demo/demo2.html
* https://edwardslab.bmcb.georgetown.edu/glymagedev/demo/demo3.html

We will use the highlight scheme from demo3. 

Integrate the widget into the glycan details page base on the Mockup.

**Note**
Robel will work on the webservice in parallel (#759). You can use example files from Nathans server or static files for development.

**Comment by kmartinez834** [comment]
https://github.com/glygen-glycan-data/PyGly/tree/master/smw/glycandata/export

**Comment by sujeetvkulkarni** [comment]
[Mockups in SharePoint](https://gwu0.sharepoint.com/:p:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7BA52E11AE-5E55-4498-AD18-58D867B7276F%7D&file=2023.09.20%20-%20Mockup%20-%20Glycan%20Highlighting.pptx&action=edit&mobileredirect=true)

**Comment by sujeetvkulkarni** [comment]
e02246540307093ff1653637ab54cbc69995f63e

**Comment by sujeetvkulkarni** [comment]
0f8445e1fc5ff6326e308bf433bded4bdaafc9ca

**Comment by sujeetvkulkarni** [comment]
3cceb06a94a976134d7c3b677c237dbb71e0d0f9
