### ISSUE TITLE
Implement webservice for glycan highlighting

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#759]
To support glycan highlighting the frontend needs two new files from Nathan. Instead of the glycan image (PNG/JPG) we need the corresponding SVG. In addition a JSON generated from Nathan needs to be provided as well.

* Implement webservice to provide SVG
* Implement webservice to provide image metadata (JSON)

**Note**: The old image service needs to remain unchanged since its still used in many pages.

**Comment by sujeetvkulkarni** [comment]
Preferably JSON and svg url should be semantic. 
Javascript file for widget will receive url and accession separately and will have to reconstruct url based on predefined strategy.

**Comment by rykahsay** [comment]
API responding with SVG image
https://api.tst.glygen.org//glycan/image_svg/G17689DH/

API responding with image metadata 
https://api.tst.glygen.org//glycan/image_metadata/G17689DH/

**Comment by kmartinez834** [comment]
See #897 for json api processing

**Comment by rykahsay** [comment]
It works now:

<img width="640" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/eee763eb-f74e-4d37-b1f2-42f06783679e">

**Comment by sujeetvkulkarni** [comment]
done. closing the issue.
