### ISSUE TITLE
Process EBI files in the current folder

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#76]
Robel, can you please process the EBI files in the current folder? /data/projects/glygen/downloads/ebi/current

FYI -- currently, Preethi is preparing 2023_01 and will share it with us by Friday or next Monday. You may wait until then if you would like.

**Comment by rykahsay** [comment]
@jeet-vora  --- why are we doing this? Isn't what we had recent enough?

**Comment by jeet-vora** [comment]
@rykahsay The recent version of EBI in GlyGen is from Dec 2022 and by the time we push the new update in July the data will be 7 months old. This will also cause problems with CFDE submission.

**Comment by rykahsay** [comment]
I have done the update and created two tickets for @jeet-vora  and @kmartinez834 to check all datasets that have been affected by this update. Please close this ticket
