### ISSUE TITLE
Implement motif highlighting on Motif details page

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#760]
Implement the motif highlight based on the Mockups in #497. Documentation for the SVG and JSON can be found in #496.

Examples can be found:
* https://glymage.glyomics.org/demo/demo1.html
* https://glymage.glyomics.org/demo/demo2.html
* https://edwardslab.bmcb.georgetown.edu/glymagedev/demo/demo3.html

We will use the highlight scheme from demo3. 

**Note**
Robel will work on the webservice in parallel (#759). You can use example files from Nathans server or static files for development.

**Comment by sujeetvkulkarni** [comment]
e02246540307093ff1653637ab54cbc69995f63e

**Comment by sujeetvkulkarni** [comment]
0f8445e1fc5ff6326e308bf433bded4bdaafc9ca
