### ISSUE TITLE
Which web services need to be updated if a new species is added

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#762]
* Home init - statistics section
* Search init - species list
* Quick search init - species lists
* Search result page (protein, glycan) - filter section for species
* Supersearch numbers
* ...

**Comment by rykahsay** [comment]
The following config files used by the API scripts need to be updated:

   glygen/conf/config.json --> here, there is a property named "taxid2name" that affects the usecase APIs
   glygen/conf/list_filters.json --> this affects the list pages when filtering by organism

**Comment by sujeetvkulkarni** [comment]
Webservice/page list:

- Glycan
  1. init
  2. search
  3. list
  4. detail

- Protein
  1. init
  2. search
  3. list
  4. detail

- alignment
  1. Isoform (protein/alignment)
  2. homolog (protein/alignment)

- Site
  1. detail

- publication
  1. detail

- blast 
  1. init
  2. job api - /job/addnew, /job/status
  3. blast-result (/job/results)

- download
  1. list page downloads
  3. table downloads
  4. blast result download
  5. detail download

- Super search
  1. init
  2. search

- Quick search
  1. init (usecases/search_init)
  4. Organism section questions.
      a. usecases/species_to_glycosyltransferases
      b. usecases/species_to_glycohydrolases
      c. usecases/species_to_glycoproteins

**Comment by sujeetvkulkarni** [comment]
done, added Webservice/page list above.
