### ISSUE TITLE
Smart ID feature on details pages

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#764]
If a valid GlyTouCan ID or UniProt Accession is used on the details pages and this ID is not in GlyGen:  Return a specific message that allows frontend to link to the corresponding pages.

**Blocker for:**
* #765

**Comment by sujeetvkulkarni** [comment]
related : https://github.com/glygener/glygen-issues/issues/766

**Comment by rykahsay** [comment]
This is already done in ticket #71
