### ISSUE TITLE
Implement smart Id feature on details pages 

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#765]
Look at the changes in #764 and change the details page (protein, glycan) as needed. If an invalid ID is used the existing message is shown. If a valid ID is used that is not in GlyGen show a message that the ID is valid but not in GlyGen. In addition link to the corresponding UniProt or GlyTouCan page.

**Dependencies:**
* #764

**Comment by sujeetvkulkarni** [comment]
see ticket #71

**Comment by sujeetvkulkarni** [comment]
84cf10117c610962ea5d19f332191cb17f100527
