### ISSUE TITLE
Integration of GlyTouCan crossreference data of ANY GlyTouCan ID

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#767]
To implement the Smart ID mapper feature from Raja we need to retrieve the crossreferences for all GlyTouCan Accessions not only for the glycans we have in GlyGen. This is need for the 2.4 data update.

@kmartinez834 and @edwardsnj will work the details out.

**Comment by kmartinez834** [comment]
@edwardsnj Looks like we need xrefs for all GTC ac's from you.  Is this something you can include in the upcoming release, or the next one?

**Comment by edwardsnj** [comment]
Dump of all available GlyTouCan xrefs is now part of the GlycanData export
