### ISSUE TITLE
Enable 2FA for GitHub or be banned from CFDE GitHub resources

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#77]
From the CFDE monthly email:

_On April 1 the CFDE GitHub will turn on 2 Factor Authentication (2FA) requirements for all CFDE associated repositories. Use the [Configuring 2FA on GitHub](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication) to update your account for access. Some users may already have this feature enabled. Users who do not will be removed from CFDE GitHub organization and will need to resubscribe after April 1st with 2FA enabled. This will not impact your access to other GitHub resources. If you have any questions, contact the [helpdesk](mailto:support@cfde.atlassian.net)._

@rajamazumder @jeet-vora @edwardsnj @mtiemeyer0919 @danlymangw

**Comment by ReneRanzinger** [comment]
Already done.

**Comment by danlymangw** [comment]
Performed successful 2FA.

**Comment by jeet-vora** [comment]
All of us have done the 2FA
