### ISSUE TITLE
QC for 30k

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#771]
We need to perform QC on the information extract in the 30k dataset. If these steps can be automated scripts should be written that allow the next larger datasets (#773) to be QC'ed automatically. 

**Dependencies:**
* #770 
* #480 

**Blocker for:**
* #481 
* #773

**Comment by rykahsay** [comment]
The downloaded putator files (corresponding to all PubMed PMIDs) are processed to extract the information that will allow us to perform various queries. These CSV files are stored under /data/shared/nlp/pubtator/query_target/ and one can use simple grep to make a set based on filters on the columns.

For example, the following command gives a list of PMIDs that "mention GlyGen species",  "GeneIDs that are mappable to  UniProtKB canonical accessions in GlyGen", and "mention a protein site":

$ cat /data/shared/nlp/pubtator/query_target/*  | grep glygen_species | grep with_geneid2canon | grep with_site | head

8641803,with_gene,glygen_species,with_geneid2canon,with_site
21766387,with_gene,glygen_species,with_geneid2canon,with_site
8389452,with_gene,glygen_species,with_geneid2canon,with_site
16882668,with_gene,glygen_species,with_geneid2canon,with_site
16882944,with_gene,glygen_species,with_geneid2canon,with_site
31602590,with_gene,glygen_species,with_geneid2canon,with_site
18764781,with_gene,glygen_species,with_geneid2canon,with_site
31907281,with_gene,glygen_species,with_geneid2canon,with_site
12140288,with_gene,glygen_species,with_geneid2canon,with_site
11502742,with_gene,glygen_species,with_geneid2canon,with_site

**Comment by rykahsay** [comment]
@jeet-vora  and @kmartinez834 are documenting this process
