### ISSUE TITLE
Automate, document and cleanup data update pipeline

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#776]
We will run the complete data update in each version moving forward:
* Automate as much as possible. 
* Cleanup as needed. 
* Document thoroughly.

**Comment by JingyueWu** [comment]
Closing this ticket as per 2.5, 
1) Karina updated most of the script to improve automation
2) We deleted some unnecessarily download_instructions.txt in a lot of the directories 
3) We completed documentation for protein, glycan, proteomics data download, backend workflow, and misc file editing as we trained Kate, Cyrus, and Urnisha.
