### ISSUE TITLE
Dataset for Vijay

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#777]
<div id="WACViewPanel_ClipboardElement" contenteditable="false" class="WACEditing EditMode EditingSurfaceBody FireFox WACViewPanel_DisableLegacyKeyCodeAndCharCode usehover" spellcheck="false" style="overflow: hidden; visibility: visible; direction: ltr;" tabindex="0"><div class="OutlineElement Ltr SCXW51314006 BCX2" style="direction: ltr;"><div class="TableContainer Ltr SCXW51314006 BCX2" style="display: flex; justify-content: flex-start;"><div id="{07f37b21-dfa7-40ce-a5ca-fa4c79798857}{41}" class="WACAltTextDescribedBy SCXW51314006 BCX2" aria-hidden="true"></div>

T1.2 | Generate reference dataset
-- | --
Due Date | 12/31/2023
Task owner | GW
Dependencies | None
Description | For all protein/glycan abstracts in GlyGen generate a table with the annotation
Deliverable | CSV table with annotations <br/>  PMID <br/>  Disease ID <br/>  Species ID<br/>  Tissue ID<br/>  Cell line ID

</div></div></div>

This table is for Vijay.

**Comment by ReneRanzinger** [comment]
Let @Shovan5795 know once you have a first version of this file. I can talk with Vijay and see if there are change requests.

**Comment by kmartinez834** [comment]
@kmartinez834 Add datasets to target for this task...

**Comment by kmartinez834** [comment]
@ReneRanzinger no need for meeting on Friday, I will provide info to Robel so he can generate these datasets.

**Comment by kmartinez834** [comment]
@rykahsay the files to target are listed here: `generated/misc/files_for_udel_dataset.csv`

Do you have time to create the dataset for Vijay this week?  If not, let me know and I will fit it into my schedule.

**Comment by rykahsay** [comment]
@kmartinez834 

I have created a script for (you can modify it if it is missing something), and have an new file (files_for_udel_dataset.csv -- which has now three fields) that can work with the script. This new file is not fully populated -- you need to edit/fully populate it.

I have moved the file you created to files_for_udel_dataset.csv-backup


```
cd /software/glygen/
$ python3 make-udel-dataset.py
```

**Comment by kmartinez834** [comment]
The curated and reference files for Tasks 1.1 and 1.2 are located in this Sharepoint folder:  [Literature Mining](https://gwu0.sharepoint.com/:f:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Literature%20Mining?csf=1&web=1&e=AEttaD)

Direct links to the file and README:
[literature_mining_t1.2.csv](https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Literature%20Mining/Task%20T1.2/literature_mining_t1.2.csv?d=w8638bcb7fc12422d818687423c95d9f6&csf=1&web=1&e=3vUAjS)
[README.xlsx](https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Literature%20Mining/Task%20T1.2/README.xlsx?d=wdc6b5ced50484f61999857fb6044fa9a&csf=1&web=1&e=FPgyUg)
