### ISSUE TITLE
Curated dataset for Vijay

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#778]
<div id="WACViewPanel_ClipboardElement" contenteditable="false" class="WACEditing EditMode EditingSurfaceBody FireFox WACViewPanel_DisableLegacyKeyCodeAndCharCode usehover" spellcheck="false" style="overflow: hidden; visibility: visible; direction: ltr;" tabindex="0"><div class="OutlineElement Ltr SCXW241996674 BCX2" style="direction: ltr;"><div class="TableContainer Ltr SCXW241996674 BCX2" style="display: flex; justify-content: flex-start;"><div id="{715a816e-ac29-4793-a168-04085d20e421}{46}" class="WACAltTextDescribedBy SCXW241996674 BCX2" aria-hidden="true"></div>

T1.1 | Generate starting dataset
-- | --
Due Date | 12/31/2023
Task owner | GW
Dependencies | None
Description | Set of PMIDs where abstract has been annotated, and extracted manually into a table  <br/>Small groups (20-25 papers) <br/>May want to include “negative” examples as well
Deliverable | CSV table with annotated PMID abstracts <br/>PMID <br/>Annotation type (disease, species, tissue, cell line) <br/>Concept ID (DOID, NCBI Taxon ID …) <br/>Abstract phrase (text from the abstract that triggered the annotation)

</div></div></div>

**Comment by ReneRanzinger** [comment]
1. Does this mean 20-25 per concept (disease, species, tissue, cell line) or 20-25 total?
2. Is 20-25 sufficient?
3. How is negative examples done?

**Comment by ReneRanzinger** [comment]
From Vijay:
1. at least 20-25 per concept. but I don't mean 20-25 x 4 abstracts. That is, there could be an abstract that mentions all four types. then it will count as one for each concept.
2. Ideally more would be better. But 25  should give a reasonable picture of how these tools are working. we can go through a second iteration if we are not confident. 
3. some papers which don't have any instance of a specifc type.

**Comment by ReneRanzinger** [comment]
Let @Shovan5795 know if you have questions or once you have a few datasets you want him and Vijay to review.

**Comment by kmartinez834** [comment]
Updates from 12/14 meeting:
- @jeet-vora & @kmartinez834 to provide queries
- Urnisha, Luke, Jingyue to help identify abstracts, Karina and/or Jeet to review
- Will provide in batches, with goal to provide all abstracts by third week in January.
- Ok if batches consist of one concept at a time
- Abstracts which do not overlap with GlyGen reference set (see task #777 )
- Papers do not need to specifically mention glycosylation

**Comment by kmartinez834** [comment]
@Shovan5795 Can you confirm if you'll need the abstract pdf files as well?

**Comment by Shovan5795** [comment]
@kmartinez834 if you can give us the PMID, that would be great. We can extract the abstracts from there and process them later.

**Comment by jeet-vora** [comment]
@ubhuiyan Will be working on this task to generate the csv.

**Comment by kmartinez834** [comment]
Email sent to Shovan and Vijay:
12/20/2023 11:02 AM 
----------------
Thanks Shovan.  We've put together an instruction document and excel sheet with examples for Urnisha, who will be doing most of the curation work. Could you and Vijay please take a look and let us know if you have any feedback or changes?

[Task T1.1 - Generate starting dataset.docx](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Literature%20Mining/Task%20T1.1/Task%20T1.1%20-%20Generate%20starting%20dataset.docx?d=w6761164cfda144cbac26f6c897054288&csf=1&web=1&e=rKFkw4)

[literature_mining_t1.1.xlsx](https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Literature%20Mining/Task%20T1.1/literature_mining_t1.1.xlsx?d=w2d2771ef4f17483cbffb5b311eecb08a&csf=1&web=1&e=Qo2vIS)

Also, we have a couple more questions:
1. Negative examples: Do you need papers that are negative for all four concepts?  Or, for example, could a paper be positive for disease but negative for tissue?
2. Concept IDs: Do you need us to map each term to the corresponding DOID/UBERON/Taxonomy ID/Cellosaurus ID?  If so, does it need to be exact or can it be a best match/synonym? If we can't find an appropriate UBERON, should we use other ontologies (e.g. BTO)?
3. Species: Is it acceptable to map to the appropriate species/strain level based on context or domain knowledge? For example, PMID 38081891 mentions the strain "C57BL/6J mice" so I mapped to the species NCBI:txid10090 (Mus musculus).  PMID 38105611 mentions "mouse" so I mapped to the genus NCBI:txid10088 (Mus).  However, I assume the model wouldn't be able to predict which strains are associated with a species unless it's included as a synonym in your mapping file.

Thanks so much,
Karina

**Comment by kmartinez834** [comment]
The curated and reference files for Tasks 1.1 and 1.2 are located in this Sharepoint folder:  [Literature Mining](https://gwu0.sharepoint.com/:f:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Literature%20Mining?csf=1&web=1&e=AEttaD)

Direct link to the file:
[literature_mining_t1.1.xlsx](https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Literature%20Mining/Task%20T1.1/literature_mining_t1.1.xlsx?d=w2d2771ef4f17483cbffb5b311eecb08a&csf=1&web=1&e=1ML0C5)
