### ISSUE TITLE
test for closing with comment.

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#782]
## Details
**Created by:** myGlygen

**Feedback from:** myGlyGen@gmail.com

**Assigned to:** myGlygen

**Priority:**  normal

[Open Note](https://app.pageproofer.com/to/note/322367)

## Note
> test for closing with comment.

## Browser Information
**Window Size:** 1421 x 862
**Screen Size:** 1920 x 1080
**Device:** Macintosh
**Browser:** Chrome version: 116.0.0.0
**Platform:** OS X version: 10_15_7

**Comment by ReneRanzinger** [comment]
#### myGlygen commented:

add something.

**Comment by sujeetvkulkarni** [comment]
do something from github.

**Comment by ReneRanzinger** [comment]
#### myGlygen commented:

close the ticket.
