### ISSUE TITLE
Usability Domain for Protein Biomarkers

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#79]
Dan please provide me with info about the Protein Biomarkers for the usability domain of the BCO.

The below was for Cancer biomarkers

"This is a Human Cancer Biomarkers dataset. It contains human [taxonomy:9606] cancer biomarker information including biomarker main x-ref mapped to UniProtKB, assessed biomarker entity, BEST biomarker type, literature evidence, disease name and LOINC code from the cancer biomarker portal (https://data.oncomx.org/cancerbiomarkers). If you use this dataset, please provide proper attribution to OncoMX and GlyGen. Cite:PMID:32142370, PMID:34015823, and PMID:31616925. This dataset can be used for obtaining cancer biomarker information for 19 cancer types."

**Comment by danlymangw** [comment]
This is a Human Protein Biomarkers dataset. It contains human [taxonomy:9606] protein biomarker information, including cross mapped UniProtKB or Protein Ontology accessions, assessed biomarker entity, biomarker status, biomarker type, specimen type, LOINC code, disease name, and source evidence from the cancer biomarker portal (https://data.oncomx.org/cancerbiomarkers). This dataset can be used to obtain biomarker information for 19 cancer types and COVID-19. If you use this dataset, please provide proper attribution to OncoMX and GlyGen. Cite: PMID:32142370, PMID:34015823, and PMID:31616925.

**Comment by jeet-vora** [comment]
Done
