### ISSUE TITLE
Update input files for check-citation-datasets.py

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#80]
Update check-citation-datasets.py mapping to compare these files:

| src_file |citations_file|
| ----------- | ----------- |
downloads/glytoucan/current/export/pubs.tsv|glycan_citations_glytoucan.csv| 
downloads/ncfg/current/glycan_evidence_ncfg.csv|glycan_citations_ncfg.csv| 
human_protein_reactions_reactome.csv|human_protein_citations_reactome.csv|
glycan_motif.csv|glycan_citations_glycomotif.csv | 

Reassign to @kmartinez834 when done to rerun check-citation-datasets.py

**Comment by kmartinez834** [comment]
@rykahsay check-citation-datasets.py is not checking the above citation files

**Comment by rykahsay** [comment]
Fixed --> I am adding "xref_key and xref_id" fields to glycan_masterlist.csv dataset and populating it from export/pubs.tsv. This way, glycan_citations_glytoucan.csv depends on "glycan_masterlist.csv" and not on  export/pubs.tsv

 
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/20584876/223246422-8e3ccdc8-310e-4126-94e3-ef4a4390f5bb.png">

**Comment by kmartinez834** [comment]
- Missing input file for `human_protein_citations_reactome.csv`
```
$ python3 check-citation-datasets.py | grep reactome
0,,0,human_protein_citations_reactome.csv,20355
```

- There are 101 PMIDs missing from `human_protein_citations_reactome.csv` that are present in `human_protein_reactions_reactome.csv`.  These have not been downloaded from Medline.  Examples are:
25631445
19641022
12048180
24920680
18772890
18607724
26962010

**Comment by rykahsay** [comment]
Check the logfiles (logs/*_protein_citations_reactome.log) and you will see what is given below. In short, the PMID source datasets (unreviewed/*_protein_reactions_reactome.csv) contain pathway_id but not protein accessions. So, when making *_protein_citations_reactome datasets, the protein accession to PMID connection has to be established using the *_protein_xref_reactome datasets which contain both pathway_id and protein accessions. So, if pathway_id="" (empty string) in the PMID source files, no connection can be made.

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/20584876/225436738-2a3ed632-9852-4b75-8dc0-876165717f74.png">
