### ISSUE TITLE
Karina and Jeet should be able to access the archive

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#803]
Provide @kmartinez834  and @jeet-vora with access and instructions for the archive.

**Comment by rykahsay** [comment]
Sorry -- what archive?

**Comment by ReneRanzinger** [comment]
@rykahsay You told me to create this ticket for you. It was part of the developer meeting 10/4 and the discussion about us loosing the contract us and feedback information. It seems there is an "archive" of older data (like an backup). Karina and Jeet both did not know about this and how to access it so you said you will provide them with instructions.

**Comment by rykahsay** [comment]
@jeet-vora @kmartinez834  --> all mongodb collections that contain information that we do not want to lose are daily archived at /data/shared/glygen/archive/

Please document this and assign back the ticket to Rene so that he can close it

**Comment by kmartinez834** [comment]
Done, created MongoDB section in sharepoint backend integration doc

**Comment by ReneRanzinger** [comment]
@kmartinez834 what do you want me to do here?

**Comment by kmartinez834** [comment]
@ReneRanzinger See Robel's comment above - assigning back to you so you can close it
