### ISSUE TITLE
Retrieve old contact logs from the snapshots

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#804]
Try if we can retrieve the old contact logs from the snapshots (backup). We only need to look into the snapshots from the day before production deployment.

**Comment by rykahsay** [comment]
I was able to look into logs from the api "/auth/contact/" starting from June 08, 2023 and it looks like there was only one user who tried to contact us (given below). The last message recorded while the email was working was on Mar 23, 2023. This means we cannot find any contact attempts that may have happened between Mar 23, 2023  and June 08, 2023.


{

    "api": "/auth/contact/",

    "req": {

        "fname": "Adam",

        "lname": "Wright",

        "email": "[adam.wright@oicr.on.ca](mailto:adam.wright@oicr.on.ca)",

        "subject": "dataIssue",

        "message": "I work for reactome and as part of our release pipeline we are pulling the following file: https://data.glygen.org/ln2wwwdata/reviewed/protein_glygen_uniprotkb_xref_mapping.tsv. Unfortunately, we are getting an error when trying to retrieve the file. Do you know what changed and if there is another URL I should be using to get the file?"

    },

    "ts": "2023-06-21 15:40:26 EDT-0400"

}

{

    "api": "/auth/contact/",

    "req": {

        "fname": "Rene",

        "lname": "Ranzinger",

        "email": "[rr@uga.edu](mailto:rr@uga.edu)",

        "subject": "general",

        "message": "Does this even work?"

    },

    "ts": "2023-09-26 14:05:24 EDT-0400"

}

{

    "api": "/auth/contact/",

    "req": {

        "fname": "Rene",

        "lname": "Ranzinger",

        "email": "[rr@uga.edu](mailto:rr@uga.edu)",

        "page": "https://www.glygen.org/glycan-search/",

        "subject": "Feedback Form Problem",

        "message": "Is this feedback working?"

    },

    "ts": "2023-09-26 14:06:29 EDT-0400"

}

{

    "api": "/auth/contact/",

    "req": {

        "fname": "Tom",

        "lname": "Cruise",

        "email": "[jeetvora@gwu.edu](mailto:jeetvora@gwu.edu)",

        "subject": "general",

        "message": "Mission Impossible !@#$%"

    },

    "ts": "2023-09-26 15:44:22 EDT-0400"

}

{

    "api": "/auth/contact/",

    "req": {

        "lname": "fdgadf",

        "message": "sdfd",

        "email": "f",

        "fname": "fgg",

        "subject": "dfsdf"

    },

    "ts": "2023-09-27 10:59:45 EDT-0400"

}
