### ISSUE TITLE
Persisting of some MongoDB content

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#805]
We need to make sure that with a restart of the container the MongoDB server is not wiped empty. That's a problem in case of a power outage in general, but also when we restart the container by hand. At least the following information need to persisted permanently:
- Frontend log
- API log
- Contacts
- Videos, banners etc.
- ...?

One way to do this is to "mount" a docker volume at the place (folder) that contains the information that needs to be persisted over a restart. 

Here is [an example](https://github.com/ReneRanzinger/docker.compose.archive/blob/main/PostgreSQL/docker-compose.yaml) from one of my compose files. In line 8+9 you can see that the volume with the name "postgres" is mounted at the /var/lib/postgresql/data folder of the container. All files written into this folder or subfolder will be written into the volume (which is essentially a folder at the host file system). When the container restarts the volume is mounted again and the files are still there. In line 33-35 you see the volume configuration, which essentially just say its a local volume (folder in the host file system). 

If you do not like docker compose you also have the same options in the [docker command](https://docs.docker.com/storage/volumes/). That would be one way to make sure the data in MongoDb is persisted.

**Comment by rykahsay** [comment]
I think this is solved now, let's visit this if there comes a related problem
