### ISSUE TITLE
dataIssue (Adam Wright) - 2023-06-21 15:40:26 EDT-0400

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#808]
I work for reactome and as part of our release pipeline we are pulling the following file: https://data.glygen.org/ln2wwwdata/reviewed/protein_glygen_uniprotkb_xref_mapping.tsv. Unfortunately, we are getting an error when trying to retrieve the file. Do you know what changed and if there is another URL I should be using to get the file?

**Comment by ReneRanzinger** [comment]
Jeet,

will you take care of Adam? Are they supposed to use this link? Because the public URL pattern looks different:

https://data.glygen.org/ln2data/releases/data/v-2.2.1/reviewed/human_protein_masterlist.csv

Looks like he is accessing some pre-release data?

Best,
  René

**Comment by jeet-vora** [comment]
Contacted Adam Oct 6 2023

Dear Adam,
Thanks for contacting GlyGen.
We apologize for not getting back to you earlier regarding the dataset access issue. Our "Contact Us" service was down for quite some time so we couldn't receive any notifications to respond. The issue has now been resolved, and the "Contact Us" option now works.

I recommend you to use the below URL which will provide access to the current version of the dataset.
https://data.glygen.org/ln2data/releases/data/current/reviewed/protein_glygen_uniprotkb_xref_mapping.tsv

Alternatively, you can access the information about the dataset, including the dataset download link, from the Download tab in our data portal (note - the link in the option contains the versioned URL for the dataset). 
https://data.glygen.org/GLY_000410 (GlyGen-UniProtKB Crossreferences Mapping)

We did some changes in the backend to make the URLs accessible and stable therefore, the previous links got changed. I believe the URL pattern won't change for the next 4-5 years and will be stable and working. In case it changes, we will let you know, or you can contact us.
Let us know for any issues or if you need any other help.
