### ISSUE TITLE
Data download master list for 2.3

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#811]
2.3 downloads need to be completed by Friday 10/13.

List of resources downloaded for 2.3:

| Resource | Downloaded by | Notes | Issue |
| -------- | ------- | ------- | ------- |
| Cellosaurus |Karina  | | |
| ChEBI| Karina | | |
| Glyconnect |Karina  | Added Dictyostelium  |  |
| OMA| Karina | Added Dictyostelium ortholog pairs | |
| Reactome | Karina |  |  |
| EBI | Jingyue | Need to coordinate with Jeet to make changes in dataset-masterlist.json and create tickets for Robel |  |
| NCBI RefSeq  | Jeet  | Jingyue updated download instructions | |
| Genome Alliance  | Jingyue  |  | |
| O-GlcNAc DB | Jingyue | Including Saccharomyces cerevisiae  |  |
| Disease Ontology | Jingyue | Instruction has been updated. Assigned Robel to process |  |
| MGI |  | Need to include dictyostelium for 2.3 |  |
| Mondo | Jingyue  | Instruction has been updated. Assigned Robel to process |  |
| PDB |  | skip for now, waiting on new protocol??? |  |
| Medline |  | Karina/Robel's tasks toward the end of the release |  |
| InChI |  | Karina/Robel's tasks toward the end of the release |  |
| matrixdb | Jingyue |  |  |
| genomics_england | Jingyue | Instruction has been updated  |  |
| iPTMnet | Jingyue | current release is still 6.1 - updated in readme.txt |

**Comment by kmartinez834** [comment]
@JingyueWu go ahead and download MGI file.  No changes to script necessary because this file contains all homology classes in MGI.
