### ISSUE TITLE
Mapping file with motif name and ids for Glycan Highlight widget.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#813]
Can you please create a mapping file with motif name and ids.
I have given an example below.

```
[
    {
        "id" : "GGM.000001",
        "name": "Type 2 LN"
    },
    {
        "id" : "GGM.000005",
        "name": "Type 1 LN"
    },
]
``` 
This file will need to be maintained for changes, so can you please add it to your pipeline.

**Comment by kmartinez834** [comment]
I'm adding export files for uga to this folder: https://data.glygen.org/ln2data/downloads/export_files/for_uga/

Motif mapping file is located here: https://data.glygen.org/ln2data/downloads/export_files/for_uga/motif_mapping.json

**Comment by kmartinez834** [comment]
Note for backend: Saved motif-mapping.py in /software/glygen/

**Comment by sujeetvkulkarni** [comment]
done. closing the issue.
