### ISSUE TITLE
Mapping file with enzyme name, ids and organism for Glycan Highlight widget.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#814]
Can you please create a mapping file with enzyme name (Gene Name), ids (not isoforms) and organism name.
I have given an example below.

```
[
    {
        "id" : "P42867",
        "name": "Dpagt1",
         "tax_common_name": "Mouse",
         "tax_name": "Mus musculus"
    },
    {
        "id" : "P27808",
        "name": "Mgat1",
         "tax_common_name": "Mouse",
         "tax_name": "Mus musculus"
    },
]
```
This file will need to be maintained for changes, so can you please add it to your pipeline.

**Comment by kmartinez834** [comment]
This file is available here: https://data.glygen.org/ln2data/downloads/export_files/for_uga/enzyme_mapping.json

_Note for backend: File was created with script enzyme-mapping.py, saved at /software/glygen_

**Comment by sujeetvkulkarni** [comment]
done. closing the issue.
