### ISSUE TITLE
Download EBI Data for 2.3

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#817]
Part of #811 and #748 

**To download EBI Data for 2.3**

- [x] Go to https://ftp.ebi.ac.uk/pub/contrib/glygen/current_release/  and make sure all the dataset including the new organism is present (Dictyostelium discoideum for 2.3)

- [x] Go to `data/projects/glygen/downloads/download_scripts/download_ebi.sh` and try to understand the content of the script.

- [x] In the download_scripts run the bash script - `bash download_ebi.sh` to download all the files

- [x] Go to downloads/ebi/ and check the new folder with all downloaded and unzipped contents.

- [x] Check the softlink of the current folder and permissions

- [x] Update the "README" if download instructions changes including addition of new files, URLs etc

- [x] Proceed to make changes in dataset-masterlist.json and create tickets for Robel (Jeet will tell you what to do)

**Comment by JingyueWu** [comment]
@jeet-vora Thanks for taking the time to make this ticket, and for making the download instruction clear for me to document. Confirm that Dictyostelium discoideum is present. Symbolic link is pointing at 2023_10_10 folder. Permissions seem to be changed successfully. I have updated the README download instruction in ebi directory. All is done with EBI except the last step. Let's talk tomorrow to tackle that.
