### ISSUE TITLE
Searching P14210-1 in global search gives result in which the accession appears in almost all glycans, proteins and glycoproteins. Somehow the service is indirectly associating with several hundreds accessions rather than few (less than 100)
jkv

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#820]
## Details
**Created by:** myGlygen

**Feedback from:** myGlyGen@gmail.com

**Assigned to:** myGlygen

**Priority:**  normal

[Open Note](https://app.pageproofer.com/to/note/323120)

## Note
> Searching P14210-1 in global search gives result in which the accession appears in almost all glycans, proteins and glycoproteins. Somehow the service is indirectly associating with several hundreds accessions rather than few (less than 100)
jkv

## Attachments
- [screenshot-2023-10-11 at 12:59:50 pm.jpg](https://s3.amazonaws.com/pageproofer-attachments/18b1fae2f04/screenshot-2023-10-11+at+12:59:50+pm.jpg)

## Browser Information
**Window Size:** 1269 x 716
**Screen Size:** 1440 x 900
**Device:** Macintosh
**Browser:** Chrome version: 117.0.0.0
**Platform:** OS X version: 10_15_7

**Comment by ReneRanzinger** [comment]
From @jeet-vora

**Comment by jeet-vora** [comment]
![image](https://github.com/glygener/glygen-issues/assets/25825266/faba7dce-aa75-44de-b79c-ea223849df11)

<img width="480" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/f981a8d2-973e-4744-805e-32370ddbb4b7">

FYI @JingyueWu

**Comment by rykahsay** [comment]
MongoDB text search was treating "P14210-1" as "P14210 1" and was trying to find documents which have "P14210" or "1". To address the issue, I am quoting any word that contains hyphen before I do the search -- this means, when you submit "P14210-1" it will be transformed into "\"P14210-1\"" which means it will be strictly looking for "P14210-1".

The problem now is that it takes too long to find exact phrases for the protein collection (which contains large amount of documents) and the API is getting a time out. I need to look into ways how to address this issue.

**Comment by rykahsay** [comment]
Test now on tst

**Comment by jeet-vora** [comment]
No issues found
