### ISSUE TITLE
Summary Report Script

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#822]
Create script that checks download files for:
- New 'current' folder
- Number of files
- If files changed
- File size
- Name change
- Files added or deleted

**Comment by kmartinez834** [comment]
@jeet-vora @JingyueWu the file at `/data/projects/glygen/generated/misc/download_summary.csv` contains information on all the files that were used as inputs for the last release.

Some example rows are below.  You can compare the previous and current folder, file creation times (ctime), file sizes, permissions (if they're not 775), folder status (new or same as last time), and error flags.

--> Make sure to check files with error flags for name changes, folder changes, unzipped files, etc.

<html>
<body>


file_name | previous_folder | current_folder | previous_ctime | current_ctime | ctime_flag | previous_size | current_size | size_flag | permissions_flag | folder_status | error_flag
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
glytoucan_allacc.txt | /data/projects/glygen/downloads/glycan_list/08_17_2023/ | /data/projects/glygen/downloads/glycan_list/08_17_2023/ | 08/17/2023, 12:07:21 | 08/17/2023, 12:07:21 | same | 1989063 | 1989063 | same |   | Same folder |  
Saccharomyces_cerevisiae.R64-1-1.110.gtf | /data/projects/glygen/downloads/ucsc/gtf/ | /data/projects/glygen/downloads/ucsc/gtf/ | 08/21/2023, 11:47:28 | 08/21/2023, 11:47:28 | same | 10463408 | 10463408 | same | 644 | Same folder |  
cfg.tsv | /data/projects/glygen/downloads/glytoucan/gtc_08_17_2023/export/ | /data/projects/glygen/downloads/glytoucan/gtc_08_17_2023/export/ | 08/17/2023, 12:20:00 | 08/17/2023, 12:20:00 | same | 157082 | 157082 | same |   | Same folder |  


</body>
</html>

**Comment by jeet-vora** [comment]
@kmartinez834 This is great. It does a good job in detecting errors. In the future version the script can be modified to spit out specific errors. Is the script in software/glygen?

@JingyueWu Look into the errors and correct them. Ensure that you are unzipping all the downloaded files (except for CFDE) and ensuring the folder/file permissions are 775.

Compare the current file with the previous release file to check for errors. For example you downloaded mondo.owl and not mondo.json.

**Comment by kmartinez834** [comment]
@jeet-vora I saved the script in at /software/glygen/download_summary.py

I need to clean up the code some more, and can add additional functionality if needed.  You can run it now to get a report like the one I provided.

`python3 /software/glygen/download_summary.py`

--> Will save download_summary_{username}.csv file to the /data/projects/glygen/generated/misc/ folder

**Comment by kmartinez834** [comment]
@JingyueWu can you fix the errors for alliance_genome also?
