### ISSUE TITLE
Add Europe PMC tweet

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#824]
[Tweet of the week](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B1A02CAE5-B282-49F0-A56A-9B0179EABFDB%7D&file=Tweet%20of%20the%20week.docx&action=default&mobileredirect=true)

Short text and image if possible.

**Comment by jeet-vora** [comment]
@ReneRanzinger Feel free to edit

10/11/2023 - Europe PMC 

🥁 Explore the [@gly_gen](https://twitter.com/gly_gen) links in EuropePMC [@EuropePMC_news](https://twitter.com/EuropePMC_news) under the ‘Data’ section. Through the link 🔍 protein and glycan and other information available on the GlyGen Publications page for a given PMID. Example: https://europepmc.org/article/MED/35289036#data

![GLyGen-PMC](https://github.com/glygener/glygen-issues/assets/25825266/b255df7e-b255-4b9e-a155-d230e8c38d2e)
