### ISSUE TITLE
Evaluation of Avi's glycan enrichment tool

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#829]
@JingyueWu and @rajamazumder will talk and plan if there is something to discuss in the group meeting.

**Comment by JingyueWu** [comment]
Action item per general meeting on 10/25 - Jingyue schedule a one-hour meeting with Raja (adding others as optional) to further discuss why Glycan Enrichment Analysis Tool is bad. Tentatively planning to meet after SfG meeting (after 11/10).

**Comment by JingyueWu** [comment]
Closing this ticket as it is the same as #860
