### ISSUE TITLE
Inactive resources

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#833]
For xref resources that we deactivated the links for (e.g. GLYCOSCIENCES.de or UniCarb-KB) create a place (SharePoint, wiki) that use to list them with 
* resource name
* original base URL
* URL pattern used for XREF
* Date they became inactive

We should keep this list updated and after one year of inactivity we can discuss what to do with them.

**Comment by kmartinez834** [comment]
File is saved in Sharepoint:

https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/Inactive%20Resources.xlsx?d=w554bf1f5bd814c239410a6444185bee2&csf=1&web=1&e=Ckm8y4
