### ISSUE TITLE
Process EBI data for 2.3

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#840]
Please process EBI data for 2.3, dataset-masterlist.json has been updated to reflect changes this time which is Dictyostelium has been added as organism.

/data/projects/glygen/downloads/ebi/current

FYI - @jeet-vora

**Comment by rykahsay** [comment]
My script is failing to create the following datasets (reason also given for each). Please fix the issues very soon.


```
sarscov2 protein_xref_geneid.csv
$ cat downloads/ebi/current/uniprot-proteome-sars-cov-2.nt | grep GeneID

dicty_protein_xref_orthodb.csv
$ cat downloads/ebi/current/uniprot-proteome-dictyostelium-discoideum.nt  |  grep OrthoDB

dicty_protein_transcriptlocus.csv
$ cat downloads/ebi/current/uniprot-proteome-dictyostelium-discoideum.nt  | grep transcriptRange

human_protein_disease_genomics_england.csv
Downloaded file  downloads/genomics_england/current/congenital_disorders_of_glycosylation.tsv is not TSV file

dicty_protein_genelocus.csv
There needs to be a gtf file for dicty (downloads/ucsc/gtf/dicty.gtf) --> dataset affected:
```

**Comment by ReneRanzinger** [comment]
`PK`
Look like a zip file

**Comment by jeet-vora** [comment]
@rykahsay @pkay47 

sarscov2 protein_xref_geneid.csv
$ cat downloads/ebi/current/uniprot-proteome-sars-cov-2.nt | grep GeneID
**--> GeneID not available in UniProtKB for sarscov2. Removed from master list. @pkay47 to double check it.**

dicty_protein_xref_orthodb.csv
$ cat downloads/ebi/current/uniprot-proteome-dictyostelium-discoideum.nt  |  grep OrthoDB
**--> OrthoDB not available in UniProtKB for Dicty. Removed from master list. @pkay47 to double check it.**

dicty_protein_transcriptlocus.csv
$ cat downloads/ebi/current/uniprot-proteome-dictyostelium-discoideum.nt  | grep transcriptRange
**--> @pkay47 to can you check why we do not have start and end pos for transcripts.**

human_protein_disease_genomics_england.csv
Downloaded file  downloads/genomics_england/current/congenital_disorders_of_glycosylation.tsv is not TSV file
**--> @rykahsay  Try Again**

dicty_protein_genelocus.csv
There needs to be a gtf file for dicty (downloads/ucsc/gtf/dicty.gtf) --> dataset affected:
**--> @pkay47 to check the error for Ensemble genes info for dicty.**

**@pkay47 These are high priority and needs to be resolved immediately.**

**Comment by pv47** [comment]
uniprot-proteome-sars-cov-2.nt missing GeneID is similar to missing Refseq xrefs. Have created a ticket for PIR. 

Manually added GeneID xrefs to https://ftp.ebi.ac.uk/pub/contrib/glygen/current_release/uniprot-proteome-sars-cov-2.nt.gz

**Comment by pv47** [comment]
looking into dictyostelium-discoideum related issues

**Comment by rykahsay** [comment]
@jeet-vora  @pkay47:

The following nt files do not contain gene locus information
```
$ cat downloads/ebi/current/uniprot-proteome-hepatitis-c-virus-1a.nt | grep geneRange
$ cat downloads/ebi/current/uniprot-proteome-hepatitis-c-virus-1b.nt | grep geneRange
$ cat downloads/ebi/current/uniprot-proteome-sars-coronavirus.nt | grep geneRange
$ cat downloads/ebi/current/uniprot-proteome-drosophila-melanogaster.nt | grep geneRange
$ cat downloads/ebi/current/uniprot-proteome-dictyostelium-discoideum.nt | grep geneRange
```

The following nt files do not contain transcript locus information
```
$ cat downloads/ebi/current/uniprot-proteome-hepatitis-c-virus-1a.nt | grep transcriptRange
$ cat downloads/ebi/current/uniprot-proteome-hepatitis-c-virus-1b.nt | grep transcriptRange
$ cat downloads/ebi/current/uniprot-proteome-sars-coronavirus.nt | grep transcriptRange
$ cat downloads/ebi/current/uniprot-proteome-sars-cov-2.nt | grep transcriptRange
$ cat downloads/ebi/current/uniprot-proteome-dictyostelium-discoideum.nt | grep transcriptRange
```

**Comment by pv47** [comment]
Checked in database, dictyostelium discoideum does not have OrthoDB xrefs.  No results in uniprot website for ` (proteome:UP000002195) AND (database:orthodb)` 

Please note OrthoDB row has false for dictyostelium_discoideum column in (https://ftp.ebi.ac.uk/pub/contrib/glygen/current_release/dbXrefMap.csv.gz)

**Comment by pv47** [comment]
hcv 1a, hcv 1b, sars coronavirus are imported from ENA, no gene info, so no geneRange or transcriptRange

**Comment by pv47** [comment]
Configured our pipelines to import genomic co-ordinates for dictyostelium-discoideum, will be available from 2024_02.

**Comment by rykahsay** [comment]
@pkay47 do you have genomic coordinates for fruitfly? This gives no triples on what we have 

$ cat downloads/ebi/current/uniprot-proteome-drosophila-melanogaster.nt | grep geneRange

**Comment by pv47** [comment]
@rykahsay, @jeet-vora Drosophila/fruitfly updated. Please take a look at
https://ftp.ebi.ac.uk/pub/contrib/glygen/current_release/uniprot-proteome-drosophila-melanogaster.nt.gz

**Comment by pv47** [comment]
@rykahsay @jeet-vora got geneRange for social amoeba. transcriptRange will be available from 2024_02.
Please take a look at updated https://ftp.ebi.ac.uk/pub/contrib/glygen/current_release/uniprot-proteome-dictyostelium-discoideum.nt.gz.

@jeet-vora please close this ticket once verified.

**Comment by rykahsay** [comment]
All protein datasets have been created, please check all of them now

**Comment by jeet-vora** [comment]
Done
