### ISSUE TITLE
Autoforwarding of the old links

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#841]
Robel 

- [ ] ISSUE 1) Raja wants you to ensure auto-forwarding is active from old data.glygen.org links to new one.

eg - https://data.glygen.org/ln2wwwdata/reviewed/protein_glygen_iptmnet_xref_mapping.csv to  https://data.glygen.org/ln2data/releases/data/current/reviewed/protein_glygen_iptmnet_xref_mapping.csv

- [ ] ISSUE 2) Add complete links to the BCO IO domain especially the input domain for downloaded source file.

eg URI: /data/shared/glyds/downloads/biomuta/v-5.0/biomuta.csv to https://data.glygen.org/ln2data/downloads/biomuta/current/biomuta.csv

https://data.glygen.org/GLY_000024

<img width="1138" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/0572cc48-1863-4434-82b6-7d6ccbf3809e">

**Comment by rykahsay** [comment]
Issue-1: fixed
This link works now:
 https://data.glygen.org/ln2wwwdata/reviewed/protein_glygen_iptmnet_xref_mapping.csv 

Issue-2: fixed
<img width="688" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/afc07ca5-faa4-46ad-82ea-ae4ddd9d9645">

**Comment by rykahsay** [comment]
Why did you assign this back to me? Any remaining issue?

**Comment by jeet-vora** [comment]
@rykahsay 

https://data.glygen.org/ln2wwwdata/reviewed/protein_glygen_iptmnet_xref_mapping.csv this link does not work again.
![image](https://github.com/glygener/glygen-issues/assets/25825266/182d96de-fac7-43e6-87b3-7f5a18e1f756)

**Comment by rykahsay** [comment]
It should work now

screenshot below is for my own note

<img width="1202" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/b92e0912-73ec-4959-a0e2-f5f4c07d2ab5">
