### ISSUE TITLE
Create a residue mapping file with hierarchy to use in Glycan Highlight widget.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#842]
Nathan #812  - See: https://github.com/glygen-glycan-data/PyGly/blob/master/smw/glycandata/export/iupac_syms.tsv now part of my standard export script

**Comment by sujeetvkulkarni** [comment]
Sample mapping file.

```
    [
        {
            "id": "Hex",
            "name": "Hexose",
            "children" : [
                {
                    "id": "Gal",
                    "name": "Gal"
                }
            ]
        },
        {
            "id": "HexNAc",
            "name": "N-Acetyl-Hexosamine",
            "children" : [
                {
                    "id": "GlcNAc",
                    "name": "GlcNAc"
                }
            ]
        },
        {
            "id": "Sia",
            "name": "N-Glycolyl-Neuraminic acid",
            "children" : [
                {
                    "id": "NeuAc",
                    "name": "N-Acetyl-Neuraminic acid"
                }
            ]
        },
        {
            "id": "Man",
            "name": "Manose"
        }
    ]
```

**Comment by kmartinez834** [comment]
@sujeetvkulkarni I created this file for you, see attached. Let me know if there's any changes needed.
[mono_mapping.json](https://github.com/glygener/glygen-issues/files/13396759/mono_mapping.json)

**Comment by kmartinez834** [comment]
Note for backend: File was created with script mono-mapping.py, saved at /software/glygen

**Comment by ReneRanzinger** [comment]
@kmartinez834 sorry. Sujeet and I already talked about this thats the reason the ticket was assigned to me. 

@sujeetvkulkarni Please use the JSON file from [here](https://github.com/glygener/glycan.viewer.json.converter/blob/main/data/glycan-viewer-residues.json). With regards to the logic:
1. Get the JSON file for an SVG and get all used IUPAC IDs
2. Match the IDs with the `id` field from my JSON file.
  a. If the ID can not be found in my file, generate and error log message and hide the IUPAC ID from the widget.
  b. If the ID is found in my file AND the `ignore` field is `false`, add them to the widget
  c. If the ID is found in my file AND the `ignore` field is `true`, hide them from the widget. No error log generated.

Please note:  You also need all the SVGs from the [this folder](https://github.com/glygener/glycan.viewer.json.converter/tree/main/data/svg). 

**Display**
Add all residues that match my JSON file AND where `ignore` is `false` to the widget in the provided hierarchy. Use the order from my JSON file. If that is an issue, let me know and I will add an `order_id`. For displaying a residue (any level in the hierarchy):
1. Display the SVG. You get the filename to use from the `image` property. All SVGs are in the folder above. You need to copy them into the project and add the corresponding path. The `image` property is **optional**! 
2. Show the name from the `name` field.

For now we will ignore the `url` and `pubChemCompound` property. But I think about using them for a tool-tip.

@kmartinez834 the JSON file is based on this [Excel file](https://github.com/glygener/glycan.viewer.json.converter/blob/main/data/glycan-viewer-residues.xlsx). If Nathan adds new residues we need to update the file as well.

**Comment by ReneRanzinger** [comment]
@sujeetvkulkarni I update the Excel file and JSON file based on our discussion with Mike. Please use the latest version.

**Comment by sujeetvkulkarni** [comment]
done. closing the issue.
