### ISSUE TITLE
Document tickets for data update

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#844]
All the tickets that have been create for 2.3 data update. We should document them and automate their creation in the future versions, so you do not have to do it one by one by hand. One way of documentation could be a spreadsheet:
* Ticket title
* Assignee
* Ticket text
* Parent ticket

I also talked with Jeet about this. Let me know what you think.

**Comment by kmartinez834** [comment]
Discussed during F2F
