### ISSUE TITLE
Check xref_dicty in dataset-masterlist.json

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#848]
I updated xref_dicty right after xref_mgi on the dataset-masterlist.json in the server, please check and let me know if there is any issue:

<img width="983" alt="Screen Shot 2023-10-19 at 11 50 54 PM" src="https://github.com/glygener/glygen-issues/assets/61590108/d9317806-9e4a-41ed-8dfe-1a1df98377b7">

**Comment by jeet-vora** [comment]
It is correct. Done
