### ISSUE TITLE
502 issues using API

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#849]
First Name: Indresh
Last Name: Singh
Email: ******@****.org
Subject: technical
Message: Greetings, We have been using glygen for Glycosylation data but since last week most of API calls are getting 502 error. Are there any changes that we should be aware? Also is there any bulk download feature? Thanks Indresh

**Comment by ReneRanzinger** [comment]
Dear Indresh,

thank you for using GlyGen and sorry about the problem. In the last few weeks we had some performance issues due to high usage and the issue you observe could be related. Can you please let us know which API's you are using and maybe with one or two example parameters that failed for you?

For the GlyGen team,
  René

**Comment by ReneRanzinger** [comment]
Greetings Rene,

 

Thanks for the quick response! We are using API URL like https://api.glygen.org/protein/detail/O43149/, and we know "glycosylation" records are there, but downloads are failing due to 502 error.

 

Is there any bulk download mechanism to download data so that we don't have to make too many API calls?

**Comment by ReneRanzinger** [comment]
Dear Indresh,

We talked with out backend team and there were some issues with too much load on the data store. They have allocated more resources to it which should resolve the issue. Can you please test if the problem still persists?

For the GlyGen team,
  René

**Comment by rykahsay** [comment]
I think the problem is gone for now and I will make bulk downloads available for protein/glycan/motif objects -- since these are the primary objects.
