### ISSUE TITLE
Datasets with protein_xref_pubmed xref_id that is not a PMID

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#85]
**The following datasets have "xref_key":"protein_xref_pubmed" but "xref_id" is not a PMID**

```
# Example from /data/projects/glygen/generated/datasets/unreviewed/human_proteoform_phosphorylation_sites_iptmnet.csv

"uniprotkb_canonical_ac","phosphorylation_site_uniprotkb","amino_acid","kinase_uniprotkb_canonical_ac","kinase_gene_name","xref_key","xref_id","src_xref_key","src_xref_id"
"P00740-1","114","Ser","Q6P1J9-1","CDC73","protein_xref_pubmed","N.N.","protein_xref_iptmnet","P00740"
```
**Files and corresponding xref_id's in question:**

human_proteoform_phosphorylation_sites_iptmnet.csv
N.N.

mouse_proteoform_phosphorylation_sites_iptmnet.csv
N.N.

fruitfly_proteoform_phosphorylation_sites_iptmnet.csv
N.N.

mouse_proteoform_phosphorylation_sites_uniprotkb.csv
SIPB413F5C4E8CFC6B4

mouse_proteoform_glycosylation_sites_o_glcnac_atlas.csv
doi.org/10.3389/fragi.2021.757801

human_proteoform_phosphorylation_sites_uniprotkb.csv
SIP7EAD55F486403408
SIP72962F6164E91CCB
SIP58A26231E44523C
SIPC61C9B24E82638F4
SIPABB712DD4A2B085E
SIP571DDAAA35F3CE1B
SIP3BE6892E3EE38AB2
SIP7184669397665E84
SIP39DAA639E15CD8E0
SIP5ACE61CC9253A2D6
SIP6B3E89C00F0EBD9D
SIP773441D7FC87FA58
SIP32BDC84668A3E6FD
SIP2586BEBD3009E059
SIPCC36DE3A6246F6EA
SIP101D0BDC5D24ACB4
SIPEFBD053E4C6A7382
SIP6029848A1C3C8CE9
SIPE01820B6CF2E0488
SIPB09A7DFD68CB69AE
SIP1B944FFD76493A20
SIPFBC7BC58DF81F3A2

rat_proteoform_phosphorylation_sites_iptmnet.csv
N.N.

rat_proteoform_phosphorylation_sites_uniprotkb.csv
SIPD2060C48DF377E9D
SIPA9E53566F3049D10

mouse_protein_matrixdb.csv
IM-20972
IM-22964

rat_protein_matrixdb.csv
IM-25784
IM-14084

human_protein_matrixdb.csv
IM-18768
IM-14134
IM-20977
IM-14084
IM-16033
IM-21580
IM-16040
IM-22964

**Comment by kmartinez834** [comment]
@jeet-vora FYI

**Comment by rykahsay** [comment]
Fixed --> please check

**Comment by kmartinez834** [comment]
👍 all resolved
