### ISSUE TITLE
Create documentation for editing dataset-masterlist.json

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#851]
Create documentation for editing dataset-masterlist.json in the SP

**Comment by JingyueWu** [comment]
I created it in the backend folder on SP. @jeet-vora Please review and edit: https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/dataset-masterlist.json%20Editing%20Instructions.docx?d=wb01b849fb8a746699eb3e937be19d7cb&csf=1&web=1&e=8IJ7Cz

**Comment by jeet-vora** [comment]
The document contains incomplete information. Exapand what the fields mean for eg Name, Format, primary field etc.

Use info from https://github.com/glygener/glygen-issues/issues/867

**Comment by JingyueWu** [comment]
@jeet-vora Done, please review and let me know if I need to change anything: 

https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/dataset-masterlist.json%20Editing%20Instructions.docx?d=wb01b849fb8a746699eb3e937be19d7cb&csf=1&web=1&e=aiMkkp

**Comment by JingyueWu** [comment]
Update on 4/1 - @kmartinez834 and @JingyueWu will be working on it.
