### ISSUE TITLE
Look into GlycoShape

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#852]
Dear all,

 

It is my pleasure to introduce to you this test (beta) version of our GlycoShape database and toolbox for glycomics and glycoanalytics. GlycoShape is our open access (OA) online repository of equilibrium 3D structures of glycans obtained from > 890 us (and running) molecular dynamics (MD) simulations. For this beta testing version we currently have 380 unique glycans, with a max (default) of 5 conformers each obtained from clustering analysis.

 

Through GlycoShape you can download the free glycan structures or link them to your protein of choice with Re-Glyco, a glycoprotein builder we designed to restore the glycosylation of structures from the AF DB and PDB or your own with the glycans you choose.  

 

The beta version of GlycoShape is live at ****

 

README file is at ****

 

Why are you receiving this email? Because we would really like your feedback on how the tools and DB look and perform before the official (public) launch, we anticipate for the end of November. To this end we would like for you to test the functionalities that interest you within GlycoShape and to give us feedback. Your input will be essential for us to make this first release better, but also, you are more than welcome to give us tips on bigger and better improvements we can implement in future releases.

 

Some caveats. This version is PRIVATE and CONFIDENTIAL, so please please please make sure that it doesn’t go around and that the word doesn’t spread yet. We will eventually change domain for the official launch so we definitely want to keep it private.

 

Finally I would like to thank Callum and Ojas cc-ed here who are the beautiful minds (developers) behind this project and co-first authors of the upcoming publication that will accompany the official launch, and Rich and Mike at ORACLE Research (also bcc-ed here) who granted us access to the fantastic ORACLE cloud infrastructure, which also hosts GlycoShape and that enthusiastically supported us through this long year of development and implementation.

 

Looking fwd to get your feedback on this work, it has been a long time coming!

 

Best Wishes,

Elisa

**Comment by ReneRanzinger** [comment]
Its a private version for now. Long term we can even extract their data. They have species and disease as well. So we may even get new records and not just cross references.

Best,
  René

**Comment by CyrusAY** [comment]
GlycoShape presentation on Feb 21:
[G20240202_GlycoShape.pptx](https://github.com/glygener/glygen-issues/files/14361202/G20240202_GlycoShape.pptx)

- url:  https://glycoshape.org

- Preprint: https://www.biorxiv.org/content/10.1101/2023.12.11.571101v1

Thanks,
Cyrus

**Comment by ReneRanzinger** [comment]
@mtiemeyer0919 will invite Elisa Fadda and/or the first author of the paper to a talk in the GlyGen seminar series in May.

**Comment by ReneRanzinger** [comment]
#1090
