### ISSUE TITLE
Provide an account for Vijays group to the AWS instance with the literature pipeline

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#857]

**Comment by ReneRanzinger** [comment]
Talk with Dacian and @rykahsay to see how we can give them access to fix the pipeline.

**Comment by jeet-vora** [comment]
@ReneRanzinger In the meeting @rykahsay  said he is going to talk to Dacian for the account creation.

**Comment by rykahsay** [comment]
I think we don't need to do this any more

**Comment by ReneRanzinger** [comment]
@rykahsay If tickets are done please close them.
