### ISSUE TITLE
ToW: CFDE release

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#858]
Provide some text and a figure to the tweet of the week about the CFDE release.

**Comment by jeet-vora** [comment]
https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B1A02CAE5-B282-49F0-A56A-9B0179EABFDB%7D&file=Tweet%20of%20the%20week.docx&action=default&mobileredirect=true

[@gly_gen](https://twitter.com/gly_gen)submitted a data package containing 44 glycoconjugate datasets and 1897 glycan array datasets to the [@CfdeNih](https://twitter.com/CfdeNih)portal for the September release. The data files are publicly available at [https://app.nih-cfde.org](https://t.co/6xywQkvacR)

![image](https://github.com/glygener/glygen-issues/assets/25825266/eb0b6090-b102-4bfd-9160-767ad7c29070)

**Comment by ReneRanzinger** [comment]
@jeet-vora did you pick the bar chart configuration for a reason? I mean nothing in there says GlyGen or can be translated to the numbers in the post.

**Comment by jeet-vora** [comment]
@ReneRanzinger I sent you the wrong screenshot

![image](https://github.com/glygener/glygen-issues/assets/25825266/b14223c6-03f0-42bf-a849-9dd74d8f4f5c)
