### ISSUE TITLE
Explore throttling for API users

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#859]
Explore if there is a way/tool to throttle API users that overuse the API. This should in no way impact the frontend usage of the API. There are several ways:

1. Throttling based on IPs
2. Have a separate instance with a "public" API and one for the frontend. In this case we can even not throttle the public API and just not care if that one becomes slow as long as it does not effect the performance of the other container.

**Comment by rykahsay** [comment]
Looks like the problem is gone  (using multiple instances flag). If the problem comes back, we will revisit this issue -- for now, I will move it to the next version

**Comment by rykahsay** [comment]
I don't think this is necessary now --
