### ISSUE TITLE
glycan_xref_pubmed vs protein_xref_pubmed

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#86]
The following files use "glycan_xref_pubmed" for "xref_key"

glycan_biomarkers.csv
glycan_citations_biomarkers.csv
glycan_citations_glycomotif.csv
glycan_citations_ncfg.csv

Whereas all other files (including glycan_citations_glytoucan.csv and glycan_synthesized.csv) use "protein_xref_pubmed".  Should this be updated for consistency?

**Comment by rykahsay** [comment]
Fixed --> please check glycan_citations_glytoucan.csv and glycan_synthesized.csv

**Comment by kmartinez834** [comment]
👍
