### ISSUE TITLE
Empty site search not working

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#865]
On production. 
* Go to site search
* Search without any input
* Search ID is generated and list page opened (https://www.glygen.org/site-list/e5e9e8999a3451a947eb2f05508b4a29)
* => Ops, something went wrong

Check if this a frontend or backend problem.

**Comment by sujeetvkulkarni** [comment]
below api return 500 INTERNAL SERVER ERROR with "e5e9e8999a3451a947eb2f05508b4a29" list id as input on prod please check.

```
https://api.glygen.org/supersearch/list?query=
{"id":"e5e9e8999a3451a947eb2f05508b4a29","offset":1,"sort":"hit_score","limit":20,"order":"desc","filters":[]}
```

Above list id ("e5e9e8999a3451a947eb2f05508b4a29") is returned from below api call
```
https://api.glygen.org/supersearch/search?query=
{"concept_query_list":[]}
```


But with other input like "bdbfad65b202504ab94fc3e4754f8980" it works fine.
```
https://api.glygen.org/supersearch/list?query=
{"id":"bdbfad65b202504ab94fc3e4754f8980","offset":1,"sort":"hit_score","limit":20,"order":"desc","filters":[]}
```

**Comment by sujeetvkulkarni** [comment]
Also, looks like all the intial ids from super search init are failing.
https://api.glygen.org/supersearch/search_init?query={}

Click on any id below, looks like all are failing.

![Screenshot 2023-10-31 at 3 59 46 PM](https://github.com/glygener/glygen-issues/assets/13891482/2961174b-1d6a-4c91-8f38-84e21e6b474f)

**Comment by rykahsay** [comment]
Tried to fix it, please check

**Comment by sujeetvkulkarni** [comment]
done. can be closed.
