### ISSUE TITLE
New Dataset: protein_glygen_mgi_xref_mapping.tsv

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#866]
Please create a new dataset to be used by MGI for cross-references. This is for mouse species only

Input files - 

- mouse_protein_xref_mgi.csv
- mouse_proteoform_glycation_sites_*.csv

Output File (TSV)

- protein_glygen_mgi_xref_mapping.tsv

**Processing Instructions:**

Create the file **exactly** as per the example table.

uniprotkb_ac | mgi_id | glycosylation_annotation | url
-- | -- | -- | --
P31750 | MGI:87986 | 8 site(s) total, 8 O-linked site(s) | https://www.glygen.org/protein/P31750-1#Glycosylation
Q09163 | MGI:94900 | 11 site(s) total, 7 N-linked site(s), 13 O-linked site(s) | https://www.glygen.org/protein/Q09163-1#Glycosylation
Q9CS84 | MGI:1096391 | 6 site(s) total, 7 N-linked site(s), 2 O-linked site(s) | https://www.glygen.org/protein/Q9CS84-1#Glycosylation
P15116 | MGI:88355 | 17 site(s) total, 10 N-linked site(s), 10 O-linked site(s) | https://www.glygen.org/protein/P15116-1#Glycosylation

**Step 1:** From mouse_protein_xref_mgi.csv, extract the UniProtKB accessions (strip canonical indication) and the corresponding MGI ids, add **MGI:** for the given ID

**Step 2:** For a given UniProtKB accession, create a annotation for glycosylation from mouse_proteoform_glycation_sites_*.csv files as shown in the table.

**Step 3:** Generate the GlyGen Protein detail URLs without the canonicals. The output file will be a tsv - **protein_glygen_mgi_xref_mapping.tsv**

@JingyueWu

**Comment by rykahsay** [comment]
The script is done but the dataset has not been created since it depends on other glycosylation datasets ("mouse_proteoform_glycation_sites_*.csv") which will be created when we get Nathan's export. Please check it when glycan and proteoform datasets are created.

I have tested the script using old "mouse_protein_xref_mgi.csv" and  "mouse_proteoform_glycation_sites_*.csv" dataset files and the rows look like this.

```
uniprotkb_ac	mgi_id	glycosylation_annotation	url
Q8CGC7	97838	1 site, 1 O-linked glycan (1 site)	https://glygen.org/protein/Q8CGC7#Glycosylation
P26339	88394	1 site	https://glygen.org/protein/P26339#Glycosylation
P14901	96163	1 site, 1 O-linked glycan (1 site)	https://glygen.org/protein/P14901#Glycosylation
Q6PFX9	1341087	1 site, 1 O-linked glycan (1 site)	https://glygen.org/protein/Q6PFX9#Glycosylation
Q7TPM1	1923304	9 sites, 1 O-linked glycan (9 sites)	https://glygen.org/protein/Q7TPM1#Glycosylation

```

**Comment by jeet-vora** [comment]
@rykahsay 

Can you create the dataset using old files for now so I can share it with MGI to make frontend changes at their end? I can let them know when we update it. They are waiting for it.

**ISSUE**
Uppend **MGI:** before MGI id 87986.
`MGI:87986`

**Comment by rykahsay** [comment]
```
$ head unreviewed/protein_glygen_mgi_xref_mapping.tsv

uniprotkb_ac	mgi_id	glycosylation_annotation	url
Q8CGC7	MGI:97838	1 site, 1 O-linked glycan (1 site)	https://glygen.org/protein/Q8CGC7#Glycosylation
P26339	MGI:88394	1 site	https://glygen.org/protein/P26339#Glycosylation
P14901	MGI:96163	1 site, 1 O-linked glycan (1 site)	https://glygen.org/protein/P14901#Glycosylation
Q6PFX9	MGI:1341087	1 site, 1 O-linked glycan (1 site)	https://glygen.org/protein/Q6PFX9#Glycosylation
Q7TPM1	MGI:1923304	9 sites, 1 O-linked glycan (9 sites)	https://glygen.org/protein/Q7TPM1#Glycosylation
P08046	MGI:95295	2 sites, 1 O-linked glycan (2 sites)	https://glygen.org/protein/P08046#Glycosylation
Q7M758	MGI:2685810	10 sites	https://glygen.org/protein/Q7M758#Glycosylation
Q9EPK6	MGI:1932040	3 sites, 3 N-linked glycans (1 site), 1 O-linked glycan (1 site)	https://glygen.org/protein/Q9EPK6#Glycosylation
Q9CQN1	MGI:1915265	1 site, 1 O-linked glycan (1 site)	https://glygen.org/protein/Q9CQN1#Glycosylation
```
