### ISSUE TITLE
Backend is sending two objects in some cases like Mouse/ Mus musculus and the second object has no database name (in some cases) in evidence object.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#869]
Looks like backend is sending two objects in some cases like Mouse/ Mus musculus in species:[]. The second object has no database name (in some cases) in evidence object which results in "undefined" name, the second mouse object overwrites the first mouse object which causes no listing of evidence from first object on the details page. 
API should only send one mouse object and needs to merge all evidence in one evidence array and send database name in each evidence object. 
Also, backend need not send "annotation_category" as we are not using it here. I believe different "annotation_category" values causing it to send more than one mouse objects.
This is a prod issue.

API: https://api.glygen.org/glycan/detail/G41247ZX

```
"species": [
{
      "taxid": 10090,
      "name": "Mus musculus",
      "annotation_category": "Subsumption",
      "evidence": [
        {
          "database": "GNOme",
          "id": "G19747OA",
          "url": "https://www.glygen.org/glycan/G19747OA"
        },
        {
          "database": "GNOme",
          "id": "G21001NA",
          "url": "https://www.glygen.org/glycan/G21001NA"
        },
        {
          "database": "GNOme",
          "id": "G39188ZX",
          "url": "https://www.glygen.org/glycan/G39188ZX"
        },
        {
          "database": "GNOme",
          "id": "G80966KZ",
          "url": "https://www.glygen.org/glycan/G80966KZ"
        },
        {
          "database": "GNOme",
          "id": "G48442VP",
          "url": "https://www.glygen.org/glycan/G48442VP"
        },
        {
          "database": "GNOme",
          "id": "G57484FV",
          "url": "https://www.glygen.org/glycan/G57484FV"
        },
        {
          "database": "GNOme",
          "id": "G59311AO",
          "url": "https://www.glygen.org/glycan/G59311AO"
        },
        {
          "database": "GNOme",
          "id": "G76666KS",
          "url": "https://www.glygen.org/glycan/G76666KS"
        },
        {
          "database": "GNOme",
          "id": "G76924RW",
          "url": "https://www.glygen.org/glycan/G76924RW"
        },
        {
          "database": "GNOme",
          "id": "G09416DG",
          "url": "https://www.glygen.org/glycan/G09416DG"
        }
      ],
      "common_name": "Mouse"
    },


    {
      "taxid": 10090,
      "name": "Mus musculus",
      "annotation_category": "Direct",
      "evidence": [
        {
          "id": "GLY_000341"
        }
      ],
      "common_name": "Mouse"
    },
]

```

**Comment by sujeetvkulkarni** [comment]
What's the purpose of annotation category? If not important then can we create a single species object?

**Comment by rykahsay** [comment]
@kmartinez834  --> this was caused because we decided to disable "glycan_xref_unicarbkb_comp_species" in generated/misc/xref_info.csv. As a fix for this bug, I am enabling it back with some edits (UniCarbKB label goes to GlyGen), and have tried to patch data release 2.2.1.

glycan_xref_unicarbkb_comp_species,GlyGen,https://data.glygen.org/GLY_000341,


<img width="795" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/167d090a-e2f3-403a-a331-ba8690804c8f">

**Comment by sujeetvkulkarni** [comment]
> What's the purpose of annotation category? If not important then can we create a single species object?

This issue still need to be fixed. Need to create one object per species in the species array like discussed.

**Comment by rykahsay** [comment]
I remember the need to fix the incomplete evidence object you showed but I don't remember deciding "create one object per species in the evidence array".  Giving below is what you are getting and I don't understand why it is a problem to put multiple evidence tags.

```
[
    {
        "taxid": 63746,
        "name": "Hepatitis C virus (isolate H)",
        "annotation_category": "Direct",
        "evidence": [
            {
                "database": "GlyGen",
                "id": "GLY_000335",
                "url": "https://data.glygen.org/GLY_000335"
            }
        ],
        "common_name": "HCV-H"
    },
    {
        "taxid": 9606,
        "name": "Homo sapiens",
        "annotation_category": "Direct",
        "evidence": [
            {
                "database": "GPTwiki",
                "id": "G41247ZX",
                "url": "https://edwardslab.bmcb.georgetown.edu/gptwiki/G41247ZX"
            },
            {
                "database": "GlyGen",
                "id": "GLY_000341",
                "url": "https://data.glygen.org/GLY_000341"
            }
        ],
        "common_name": "Human"
    },
    {
        "taxid": 10090,
        "name": "Mus musculus",
        "annotation_category": "Direct",
        "evidence": [
            {
                "database": "GlyGen",
                "id": "GLY_000341",
                "url": "https://data.glygen.org/GLY_000341"
            }
        ],
        "common_name": "Mouse"
    },
    {
        "taxid": 10116,
        "name": "Rattus norvegicus",
        "annotation_category": "Direct",
        "evidence": [
            {
                "database": "GlyGen",
                "id": "GLY_000341",
                "url": "https://data.glygen.org/GLY_000341"
            }
        ],
        "common_name": "Rat"
    },
    {
        "taxid": 2697049,
        "name": "Severe acute respiratory syndrome coronavirus 2",
        "annotation_category": "Direct",
        "evidence": [
            {
                "database": "GlyGen",
                "id": "GLY_000341",
                "url": "https://data.glygen.org/GLY_000341"
            }
        ],
        "common_name": "SARS-CoV-2"
    },
    {
        "taxid": 694009,
        "name": "Severe acute respiratory syndrome-related coronavirus",
        "annotation_category": "Direct",
        "evidence": [
            {
                "database": "GlyGen",
                "id": "GLY_000341",
                "url": "https://data.glygen.org/GLY_000341"
            }
        ],
        "common_name": "HCoV-SARS"
    }
]
```

**Comment by sujeetvkulkarni** [comment]
- remove annotation category.
- make one species object that differ by annotation category.
- Change database name GNOme to Subsumption.
- Collapsing of duplicated species under the same genum. Rattus (Rat) and Rattus norvegicus (Rat) https://tst.glygen.org/glycan/G41247ZX

**Comment by rykahsay** [comment]
The last bullet point means that we are at liberty to make the following change (and I remember Nathan was opposing this):

From
"G99524KA","10114","Rattus","Direct","GlyCosmos","G99524KA","","glycan_xref_glycosmos","G99524KA","True"

To:
"G99524KA","10116","Rattus norvegicus","Direct","GlyCosmos","G99524KA","","glycan_xref_glycosmos","G99524KA","True"

**Comment by ReneRanzinger** [comment]
@rykahsay But this is a decision we made earlier. We will not have "duplicated" Species visible anywhere on the webpage:
* Rat vs Rattus
* Strain and species annotation for yeast

We wanted to remove this from all places:
* Home page statistic
* Advanced search pages
* Quick search pages
* Details pages
* Filter option in search result pages

**Comment by sujeetvkulkarni** [comment]
Fixed. Closing the issue. 

Below comment need further discussion,
Collapsing of duplicated species under the same genum. Rattus (Rat) and Rattus norvegicus (Rat) https://tst.glygen.org/glycan/G41247ZX
