### ISSUE TITLE
Sample mapping questions

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#87]
1. I wrote a script to make sure all the UnicarbKB terms were included in sample_mapping.csv and applied it to the oglcnac atlas files as well. A list of terms from the "sample_type" field that aren't explicitly included in sample_mapping.csv is saved at `/data/projects/glygen/generated/misc/atlas_sample_type.txt`

2. It looks like some terms are still separated by commas in the "in_dataset" field.  A few examples:

"MESH:D013574","synaptosomes","artificial_structure","Medical Subject Headings","brain (synaptosome),synaptosome"
```
ambiguous_sites_version_2.0.csv:221,A000221,human,brain (synaptosome),Q9Y6V0,UniProt,PCLO_HUMAN,Protein piccolo,PCLO,ITSNYEVIR,T,2,3975,MS,LTP,20563614,

unambiguous_sites_version_2.0.csv:23066,U023066,mouse,synaptosome,F7C376,UniProt,F7C376_MOUSE,Voltage-dependent L-type calcium channel subunit alpha,Cacna1c,AGGLFGNHVTYYQSDSR,T,10,1791,MS,HTP,34678516
```

"CVCL_0045","HEK293","cell_line","Cellosuarus","HEK 293 cells,over-exppressed in HEK 293 cells"
```
ambiguous_sites_version_2.0.csv:275,A000275,human,HEK 293 cells,P54198,UniProt,HIRA_HUMAN,Protein HIRA,HIRA,WSPDGHYLVSAHAMNNSGPTAQIIER,S,2,231,MS,LTP,27217568

unambiguous_sites_version_2.0.csv:11700,U011700,mouse,over-exppressed in HEK 293 cells,Q8CFN5,UniProt,MEF2C_MOUSE,Myocyte-specific enhancer factor 2C,Mef2c,KIQITRIMDER,T,5,9,"MS, site-directed mutagenesis",LTP,32736694,
```

**Comment by kmartinez834** [comment]
I separated terms with commas in sample_mapping.csv "in_dataset" field, except for those where comma exists in dataset (ex. "Bel-7402 cells, SMMC-7721 cells")

See `/data/projects/glygen/generated/misc/atlas_sample_type.txt` for terms still missing from sample_mapping.csv

**Comment by jeet-vora** [comment]
sample_mapping.csv looks good now.

atlas_sample_type.txt contains sample_types that could not be standardized.
Will share these with the resource.

Best,

*Jeet Vora*
Senior Research Associate
Scientific Coordinator for GlyGen.org
Project Manager for Glycosciences-NIH CFDE
The George Washington University
Ross Hall, Room 559
2300 Eye Street N.W.
Washington, DC 20052
***@***.***
*Pronouns - He/him/his*

**Comment by jeet-vora** [comment]
Done
