### ISSUE TITLE
When a Biomarker associated with a disease is searched and viewed on the details page, the biomarker section does not show the disease column. For example, if liver cancer is searched and the identifier with the biomarker is clicked in the list page,
the biomarker does not show the disease Liver cancer in any field of the biomarker section on the details page which can be confusing and maybe disappointing for a user. I think we can add a disease column to both the glycan and protein biomarker section.
jkv

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#870]
## Details
**Created by:** myGlygen

**Feedback from:** myGlyGen@gmail.com

**Assigned to:** myGlygen

**Priority:**  normal

[Open Note](https://app.pageproofer.com/to/note/327312)

## Note
> When a Biomarker associated with a disease is searched and viewed on the details page, the biomarker section does not show the disease column. For example, if liver cancer is searched and the identifier with the biomarker is clicked in the list page,
the biomarker does not show the disease Liver cancer in any field of the biomarker section on the details page which can be confusing and maybe disappointing for a user. I think we can add a disease column to both the glycan and protein biomarker section.
jkv

## Attachments
- [biomarkers disease.png](https://s3.amazonaws.com/pageproofer-attachments/18bb01aab79/biomarkers+disease.png)

## Browser Information
**Window Size:** 1269 x 716
**Screen Size:** 1440 x 900
**Device:** Macintosh
**Browser:** Chrome version: 118.0.0.0
**Platform:** OS X version: 10_15_7

**Comment by sujeetvkulkarni** [comment]
@jeet-vora We have made changes to biomarker details page now. If disease column needs to be added on protein, glycan details pages etc then @rykahsay needs to make changes in corresponding details apis.

**Comment by jeet-vora** [comment]
Current section looks good. We do not need anything else for now.
