### ISSUE TITLE
Dataset preview not working

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#873]
Dataset preview is blank for csv files on data.glygen.org:
https://data.glygen.org/GLY_000001

![image](https://github.com/glygener/glygen-issues/assets/90285371/82e24dbe-6007-4e6a-883c-0030fe32ab9c)

**Comment by rykahsay** [comment]
Fixed, please try now

**Comment by kmartinez834** [comment]
Looks good
