### ISSUE TITLE
Better name and tooltip for Glycan Highlight widget.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#874]
Current name : Glycan Highlighter

![Screenshot 2023-11-20 at 3 30 55 PM](https://github.com/glygener/glygen-issues/assets/13891482/2d5d9fd4-c850-4a9f-954f-144f9672807f)

**Comment by ReneRanzinger** [comment]
**Header:**  Glycan Sequence Browser

**Tooltip:** The Feature View is an interactive tool that displays the glycan sequence in SNFG notation and allows user to highlight residues based on their type, motifs or residues that can be added by enzymes.

**Link:** https://wiki.glygen.org/Glycan_details/Feature_view

**Comment by sujeetvkulkarni** [comment]
Feature View

**Comment by sujeetvkulkarni** [comment]
Need tooltips for motifs, residues, enzymes check kdn names, remove parentheses.
#813
#814

**Comment by ReneRanzinger** [comment]
### Decision
* For each "row" in the left side listing the display elements are: Tickbox, Name, Tooltip icon (for tooltip content see below)
* Remove the image from the General section
* Remove of consistently add spacing between the accordions
* Reduce the height of the accordion headers

### Residue tooltip
**Tooltip heading:** <name of the residue>
**Tooltip content:**
SNFG symbol: [svg image]

[name of the residue] on Wikipedia `[name of the residue] is the link to the wiki page`

[name of the residue] on PubChem `[name of the residue] is the link to the PubChem page`
**Note:**
* Both wikipedia URL and PubChem are optional. If the information is not in the JSON the corresponding line will not be there in the tooltip.
* The JSON file only has the compound ID for PubChem. The URL patter is: https://pubchem.ncbi.nlm.nih.gov/compound/[compoundID]

### Motif tooltip
**Tooltip heading:** [name of the motif]
**Tooltip content:**
[name of the motif] in GlycoMotif `[name of the motif] is the link to the GlycoMotif page`

Glycans with [name of the motif] in GlyGen. `[name of the motif] is the link to the GlyGen motif page`
**Note:**
* The JSON file only has the motif ID. The URL pattern for GlycoMotif is https://glycomotif.glyomics.org/glycomotif/[MotifID] and for GlyGen it is https://www.glygen.org/motif/[MotifID]

### Enzyme tooltip
**Tooltip heading:** [name of the enzyme]
**Tooltip content:**
Species: [tax_common_name] ([tax_name])

[name of the enzyme] in GlyGen `[name of the enzyme] is the link to the GlyGen protein page`
**Note:**
* You have the protein ID in the mapping file and can use it to link to the corresponding protein details page

### General note
* All links in the tooltips should open new tabs

**Comment by sujeetvkulkarni** [comment]
8a9afef055868c10187fe0d0b0867909a2b053ca
