### ISSUE TITLE
Large scale datasets from EMBL

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#876]
Mira,
We have received your message and will make every effort to respond to you within a reasonable amount of time.

First Name: Mira
Last Name: Burtscher
Email: ****************
Subject: general
Message: Dear glygen team,
I contacted you a couple of months ago regarding the upload of large scale glycoproteomic datasets (https://www.biorxiv.org/content/10.1101/2023.09.13.557529v1). Could you please advise us, how we can integrate this best in glygen?
Thank you very much!
Best,
Mira Burtscher

**Comment by ReneRanzinger** [comment]
Hi Mira,

We appreciate and thank you for your interest in sharing and integrating glycoproteomics data with GlyGen. We had issues for a couple of months with our contact page that disabled us from getting any messages from users and the community.

To integrate the data into GlyGen, we can have a call to understand the data and chalk out the next steps for integration. Let me know if you will be willing to hop on a call, with your timezone and availability from the last week of November to mid-December.

**Comment by jeet-vora** [comment]
A template was shared on Dec 12 with Clement and a discussion will occur post webinar to finalise data ingestion.
