### ISSUE TITLE
Proteoform Datasets

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#878]
Please process these datasets after processing Nathan's export

protein_glygen_mgi_xref_mapping.tsv
protein_glygen_genecards_xref_mapping tsv
protein_glygen_iptmnet_xref_mapping csv
protein_glygen_mgi_xref_mapping csv
protein_glygen_pharos_xref_mapping csv
protein_glygen_pubchem_xref_mapping csv
protein_glygen_uniprotkb_protvista_mapping tsv
protein_glygen_uniprotkb_xref_mapping tsv
*_protein_citations_mutation_germline
*_protein_citations_mutation_somatic
*_protein_mutation_cancer
*_protein_mutation_cancer_glycoeffect
*_protein_mutation_cancer_glycosylation_loss
*_protein_mutation_germline
*_protein_mutation_germline_glycoeffect
*_protein_mutation_somatic
*_protein_mutation_somatic_glycoeffect
*_protein_xref_biomuta
*_protein_xref_glyconnect
*_protein_xref_oglcnac_atlas
*_protein_xref_oglcnac_db
*_protein_xref_unicarbkb

@Luke-Johnson-5 These datasets rely on Proteofom datasets.

**Comment by rykahsay** [comment]
Done
