### ISSUE TITLE
download api needs to support svg file download for glycan images.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#881]
Below api needs to support svg format download.

API: 
https://api.glygen.org/data/detail_download?query=
{"id":"G17689DH","download_type":"glycan_image","format":"png","compressed":false}

**Comment by rykahsay** [comment]
This works now:

https://api.tst.glygen.org/data/detail_download?query={"id":"G17689DH","download_type":"glycan_image","format":"svg","compressed":false}

**Comment by sujeetvkulkarni** [comment]
84cf10117c610962ea5d19f332191cb17f100527
