### ISSUE TITLE
For GGM.000027 motif 6S should not get highlighted for G00659GQ and G95837WQ glycans.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#882]
In Glycan highlight widget when GGM.000027 is clicked/highlighted then 6S (above Gal) should not get highlighted. Motif does not contain 6S above Gal.

[GGM.000027](https://glycomotif.glyomics.org/glycomotif/GGM.000027)

<img width="976" alt="Screenshot 2023-11-21 at 9 49 20 PM" src="https://github.com/glygener/glygen-issues/assets/13891482/9f22dab8-e8b6-4468-a966-d05817592c7e">

[G95837WQ](https://glygen.org/glycan/G95837WQ) 

<img width="613" alt="Screenshot 2023-11-21 at 9 50 01 PM" src="https://github.com/glygener/glygen-issues/assets/13891482/636c3774-1b2b-490f-a4f2-dfa52537f017">

[G00659GQ](https://glygen.org/glycan/G00659GQ)

<img width="578" alt="Screenshot 2023-11-21 at 9 50 26 PM" src="https://github.com/glygener/glygen-issues/assets/13891482/b2f8244e-34c5-4919-959c-53044d0d275a">

**Comment by edwardsnj** [comment]
You need up update the JSON files and maybe the JS file, this was fixed a couple of weeks ago. See: https://glycomotif.glyomics.org/glycomotif/GGM.000027 alignments...

**Comment by sujeetvkulkarni** [comment]
done. closing the issue.
