### ISSUE TITLE
Upload photos from SFG

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#883]
Add photos of posters, GlyGen table, etc. from SFG 2023 to Sharepoint folder:
https://gwu0.sharepoint.com/:f:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Meetings/2023%20SFG%20Conference/Photos?csf=1&web=1&e=We2G43

**Comment by ReneRanzinger** [comment]
Added mine.

**Comment by JingyueWu** [comment]
Added mine.
