### ISSUE TITLE
Add GlyGen Webinar Info to portal banner

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#884]
Add GlyGen Webinar Info to portal banner about Nadine Samara Talk
https://wiki.glygen.org/GlyGen_Webinar_Series#November_28,_2023_-_Nadine_Samara

[GlyGen_Webinar_Series_Nadine_Samara_Nov28_2023.docx](https://github.com/glygener/glygen-issues/files/13442885/GlyGen_Webinar_Series_Nadine_Samara_Nov28_2023.docx)

**Comment by sujeetvkulkarni** [comment]
done, please check.
