### ISSUE TITLE
Check GeneID to species mapping for lit mining failed entries

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#885]
Check GeneID to species mapping for lit mining failed entries

**Comment by rykahsay** [comment]
I mixed it up, their pipeline does not rely on Gene ID, it relies on some files they download from UniProtKB (I have emailed the UD team on the need to update those files). It is my pipeline that relies on Gene ID and I will visit the limitation soon.

**Comment by rykahsay** [comment]
Please close this ticket for now
