### ISSUE TITLE
TOW 3/1

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#89]
Make a proposal for the [TOW](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B1A02CAE5-B282-49F0-A56A-9B0179EABFDB%7D&file=Tweet%20of%20the%20week.docx&_DSL=1&action=default&mobileredirect=true) announcing open slots in the workshop.

**Comment by kmartinez834** [comment]
Email sent to Raja, Mike & Rene on 3/7:

Draft tweet is here for your review:   [Tweet of the week.docx](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/General/Tweet%20of%20the%20week.docx?d=w1a02cae5b28249f0a56a9b0179eabfdb&csf=1&web=1&e=eYbo0P)

Thanks,
Karina
