### ISSUE TITLE
File in UniProt Downloads ?(uniprot_human_sprot_sorted.csv)

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#892]
Preethi,

Can you find if the below file is available for downloads from UniProtKB. 

The file can be names differently or could have mixed organisms in it. 

[uniprot_human_sprot_sorted.csv](https://github.com/glygener/glygen-issues/files/13621136/uniprot_human_sprot_sorted.csv)

Example
cui	resource	original_id	term	preferred_term	entity_type
CUI-less	Swiss-Prot	O15178	T	T-box   transcription factor T	gene
CUI-less	Swiss-Prot	Q04671	P	P   protein	gene
CUI-less	Swiss-Prot	P19526	H	Galactoside   alpha-(1
CUI-less	Swiss-Prot	P28074	X	Proteasome   subunit beta type-5	gene
CUI-less	Swiss-Prot	P28072	Y	Proteasome   subunit beta type-6	gene
CUI-less	Swiss-Prot	Q99436	Z	Proteasome   subunit beta type-7	gene
CUI-less	Swiss-Prot	Q15477	W	Helicase   SKI2W	gene
CUI-less	Swiss-Prot	P35326	21	2-1	protein
CUI-less	Swiss-Prot	P01871	IgM	IgM	protein

@pkay47

**Comment by pv47** [comment]
@jeet-vora is CUI - Concept Unique Identifier? eg: https://ncimeta.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C1527755 

If yes, it is not used.  If no, please provide more info about CUI

**Comment by jeet-vora** [comment]
@pkay47 I guess it means CUI - Concept Unique Identifier. 
Does that mean it is not an UniProt file?

**Comment by pv47** [comment]
CUI is not used in UniProt.

**Comment by jeet-vora** [comment]
Got it
