### ISSUE TITLE
Process proteoform & glycan datasets

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#893]
Nathan's export has been downloaded, please proceed with making the proteoform and glycan datasets

**Comment by rykahsay** [comment]
@jeet-vora --> dicty does not seem to have data for glycation. So, the following datasets will not be created (I have modified datamaster list json)

```
dicty_proteoform_glycation_sites_uniprotkb.csv
dicty_proteoform_citations_glycation_sites_uniprotkb csv
```

**Comment by rykahsay** [comment]
@kmartinez834 --> I am removing the following from dataset-masterlist.json untill we start creating carbbank proteoform datasets.

```
{
                "name": "glycosylation_sites_carbbank",
                "format": "csv",
                "primaryfield": "uniprotkb_canonical_ac",
                "target_objects": [
                        "protein", "glycan"
                ],
                "integration_status": {
                        "status": "integrate_none",
                        "excludelist": []
                },
                "categories": {
                        "molecule": "proteoform",
                        "species": [
                                "human",
                                "mouse",
                                "rat",
                                "sarscov2",
                                "fruitfly",
                                "yeast"
                        ]
                }
        }
```

**Comment by rykahsay** [comment]
@jeet-vora @kmartinez834 @JingyueWu @Luke-Johnson-5 --> bad naming of downloaded file:

"glyconnect_dictyostelium.json" should have been named "glyconnect_dicty.json"

I have corrected it this time, please document this so that it does not happen again.

<img width="1219" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/bee7f22f-18cc-4d77-82c1-d1f2b2bf00d6">

**Comment by rykahsay** [comment]
@kmartinez834 --> missing download file downloads/sandbox/current/glycotree_annotated_glycans.tsv

**Comment by kmartinez834** [comment]
Fixed bug in processing script, file is now present in current folder

**Comment by rykahsay** [comment]
Looks like you didn't check the content of the file:

```
$ cat downloads/sandbox/current/glycotree_annotated_glycans.tsv 
<br />
<b>Fatal error</b>:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 164382048 bytes) in <b>/var/www/html/api/glygenData.php</b> on line <b>24</b><br />
""
```

**Comment by rykahsay** [comment]
All proteoform datasets have been created, please check.

All glycan datasets with the execption of glycan_enzyme.csv have been created, please check.

For glycan_enzyme.csv, please fix the problem with the input file downloads/sandbox/current/glycotree_annotated_glycans.tsv

**Comment by kmartinez834** [comment]
@edwardsnj https://sandbox.glyomics.org/api/glygenData.php

**Comment by edwardsnj** [comment]
@kmartinez834 I think this has been fixed. Please let me know if you don't agree. Note that this file contains non-glygen accessions (it is a superset of the glygen glycans)

**Comment by kmartinez834** [comment]
@edwardsnj Thank you, it is working now

Closing this ticket - opened #896 for reprocessing sandbox datasets
