### ISSUE TITLE
Process Sandbox files

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#896]
Process/reprocess all of the Sandbox datasets:

- [ ] glycan_enzyme.csv
- [ ] glycan_pathway_glycotree.csv
- [ ] glycan_toolsupport.csv
- [ ] glycan_xref_sandbox.csv

**Comment by rykahsay** [comment]
Done, please check

**Comment by rykahsay** [comment]
Please not the significant volume change:

```
   383253    downloads/sandbox/08_17_2023/glycotree_annotated_glycans.tsv
       16012  downloads/sandbox/08_17_2023/accessionlist.csv
     919777    downloads/sandbox/08_17_2023/allPaths.json
    383252    reviewed/glycan_enzyme.csv

  1141544   downloads/sandbox/current/glycotree_annotated_glycans.tsv
      27250  downloads/sandbox/current/accessionlist.csv
  1636674    downloads/sandbox/current/allPaths.json
     711134   unreviewed/glycan_enzyme.csv

```

**Comment by kmartinez834** [comment]
@edwardsnj I noticed there are accessions in the GNOme GlyGen.valid-accessions.txt file that do not appear in the glycan data export.  Not an issue for us but just a heads up. 

Some examples:
'G00019MO', 'G00020MO', 'G00021MO', 'G00022MO'

**Comment by kmartinez834** [comment]
@rykahsay files look good, closing the ticket

**Comment by edwardsnj** [comment]
Yes, GNOme still has accessions that were removed in this iteration. Once GlyGen releases the data, I will update the GlyGen accessions list for GNOme
