### ISSUE TITLE
Medline and InChi downloads

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#898]
@rykahsay Download the following if you have not already:

- [ ] Medline
- [ ] InChI keys

**Comment by rykahsay** [comment]
Done, but please check the difference in volume for the cid2inchi:

```
> Last version
 $ wc /data/shared/glygen/releases/data/v-2.2.1/compiled/cid2inchi.csv 
   9767    /data/shared/glygen/releases/data/v-2.2.1/compiled/cid2inchi.csv

> Now
$ wc /data/projects/glygen/generated/datasets/compiled/cid2inchi.csv
   9451   compiled/cid2inchi.csv
```

**Comment by kmartinez834** [comment]
Looks good, fewer lines due to reduction in source file: downloads/glytoucan/gtc_12_09_2023/export/pbch.tsv
