### ISSUE TITLE
Process GH and GT for Dicty

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#899]
Robel processes the GT AND GH datasets for Dictyostelium present in the compiled folder

/glygen/generated/datasets/compiled/**dicty_protein_glycohydrolase.csv**
/data/projects/glygen/generated/datasets/compiled/**dicty_protein_glycosyltransferase.csv**

added to masterlist

**Comment by rykahsay** [comment]
Done, check

**Comment by jeet-vora** [comment]
Done
