### ISSUE TITLE
Start collecting ideas for tools that can be implemented in GlyGen

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#90]
Create a Word document with a template that everybody can use.

**Comment by ReneRanzinger** [comment]
[File with ideas](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7Bcf3b01a9-09d1-4c20-846e-650a143969f2%7D&action=edit&wdPreviousSession=0a998f5c-ebb0-4bf1-b82c-92d3111c40b2)

@edwardsnj @kmartinez834 @jeet-vora @rajamazumder @mtiemeyer0919 @rykahsay please add own tool ideas.

**Comment by jeet-vora** [comment]
@ReneRanzinger Added Clustal Omega as new tool.

Is the doc for only new tool? What about existing tool that requires new features?
