### ISSUE TITLE
Protvista issues

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#901]
There are multiple issues I found all can be shown on the [ProtVista page](https://www.glygen.org/protVista/P00533-1#) of [P00533](https://www.glygen.org/protein/P00533-1).

1. Glycosylation summary: `21 site(s) total, 101 N-linked glycan(s) at 15 site(s), 1 O-linked glycan(s) at 6 site(s)`
There are several glycans with unknown position information but they all should collapse into "one site". Which means there are at least 14 N-glycan sites and 5 O-glycan sites with glycans on this protein. However, in ProtVista the `N-Glycan` and `O-glycan` track are empty. The `N-Glycan Sites` track which comes from the "Reported sites" tab is filled correctly.

2. Phosphorylation: There are "stacks" of dotes in this track. Each node in this stack has the same information. Why are they there? For glycans we collapse these annotation into one symbol with a sentence "Click marker to show xxx more on this site". The same should happen here.

3. Glycation and SVN: Stacks see 2.

4. Mutagenesis: There are these long arcs. The sequence in the headline gets cut off. It also says undefined->1210. Why does it have an arbitrary start point? 

5. Mutagenesis: Click on any of the 4. or other section that span more than one amino acid (e.g. 1005-1006) will also result into a dead page.

6. Stacks: Working on 2. and 3. will reduce the stacks. There is still a possibility that we have more than 4. Leading to the 5th being cut of and 5+ not being visible/clickable.

**Comment by sujeetvkulkarni** [comment]
84cf10117c610962ea5d19f332191cb17f100527
