### ISSUE TITLE
Mapping isoforms to canonical accession for RefSeq ac

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#903]
Robel,

It seems like you are mapping the refseq ac of isoforms to the canonical accession in the RefSeq files. See below example as detected by @Luke-Johnson-5 

all files using *protein_xref_refseq.csv dataset could potentially be impacted.

Issue found with mapping accession numbers to xref_id in file 
rat_protein_xref_refseq.csv. In both the /reviewed/ and /unreviewed/ 
accession F1LVT6-1 maps as so:</p>

| Unreviewed                                                                                                                                                     | Reviewed                                                                                                                                                       |
| -------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| "F1LVT6-1","protein_xref_refseq","XP_008764072",""<br>"F1LVT6-1","protein_xref_refseq","XP_017458989",""<br>"F1LVT6-1","protein_xref_refseq","XP_008764066","" | "F1LVT6-1","protein_xref_refseq","XP_008764072",""<br>"F1LVT6-1","protein_xref_refseq","XP_017458989",""<br>"F1LVT6-1","protein_xref_refseq","XP_008764066","" |

<p dir="auto">The issue that was found is that in the source file 
(/data/shared/glyds/downloads/ebi/2023_10_30/uniprot-proteome-rattus-norvegicus.nt)
 the accession F1LVT6-1 is only found to map to xref_id XP_017458989.</p>
<p dir="auto">Xref_id XP_008764072 in the source file is mapped to accession: A0A0G2JVG1<br>
Xref_id XP_008764066 in the source file is mapped to accession: A0A0G2K1R8</p>
<p dir="auto">Screenshot:<br>
<a target="_blank" rel="noopener noreferrer" href="https://private-user-images.githubusercontent.com/144174552/290315860-85a847ea-1f0a-4ba9-af82-3721348611b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1ODkzNjcsIm5iZiI6MTcwMjU4OTA2NywicGF0aCI6Ii8xNDQxNzQ1NTIvMjkwMzE1ODYwLTg1YTg0N2VhLTFmMGEtNGJhOS1hZjgyLTM3MjEzNDg2MTFiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQyMTI0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDdmODE2NjhkMGUxNjQ2MjZkNGY3Nzc1YWU1YmJjZTk3ODFhM2UzODIzN2I0N2ZhYWQzNDAzMDdmYzk0NjQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dzegagSZ5LOiBKRzFcRhSXwF_3WLhQSqymKXpkw8GWc"><img src="https://private-user-images.githubusercontent.com/144174552/290315860-85a847ea-1f0a-4ba9-af82-3721348611b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1ODkzNjcsIm5iZiI6MTcwMjU4OTA2NywicGF0aCI6Ii8xNDQxNzQ1NTIvMjkwMzE1ODYwLTg1YTg0N2VhLTFmMGEtNGJhOS1hZjgyLTM3MjEzNDg2MTFiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQyMTI0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDdmODE2NjhkMGUxNjQ2MjZkNGY3Nzc1YWU1YmJjZTk3ODFhM2UzODIzN2I0N2ZhYWQzNDAzMDdmYzk0NjQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dzegagSZ5LOiBKRzFcRhSXwF_3WLhQSqymKXpkw8GWc" alt="Screenshot 2023-12-13 150929" style="max-width: 100%;"></a></p>
<p dir="auto"><strong>NOTE:</strong> The two accessions A0A0G2JVG1 and 
A0A0G2K1R8 are the accessions for computationally mapped potential 
isoforms of F1LVT6-1.

**Comment by rykahsay** [comment]
Tried to fix them -- check all *_protein_xref_refseq.csv dataset files

**Comment by jeet-vora** [comment]
@Luke-Johnson-5 Check this ticket and let me know. I will proceed to send email to Robel

**Comment by jeet-vora** [comment]
@rykahsay 
Have you re-processed all files eg `*refseq.csv` which use `*protein_xref_refseq.csv`. If not, then please reprocess those, as their row and id counts will also change as *protein_xref_refseq.csv   has changed

eg
*proteinnames_refseq.csv
*xref_refseq.csv
*info_refseq.csv
*citations_refseq.csv
*function_refseq.csv
FYI @Luke-Johnson-5

**Comment by Luke-Johnson-5** [comment]
@jeet-vora I looked ay the *xref_refseq.csv and *proteinnames_refseq.csv and *info_refseq.csv files and this issue seemed to be fixed and I did not see any obvious issues however I missed the citation and function files but I can look at those now.

**Comment by jeet-vora** [comment]
Done
