### ISSUE TITLE
 Create icons of demo, talk etc for outreach page.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#904]
Need to create icons for paper, meeting_talk, online_talk, poster, workshop, training, demo. Total 7 filter categories for outreach page.

**Comment by ReneRanzinger** [comment]
[Archive.zip](https://github.com/glygener/glygen-issues/files/13709204/Archive.zip)

**Comment by sujeetvkulkarni** [comment]
06add09ec002dcfc3f3109b8ebea7b921e01239a

**Comment by sujeetvkulkarni** [comment]
done. closing the issue.
