### ISSUE TITLE
Create icons for file format - power point, pdf and default to use on outreach page.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#905]

**Comment by ReneRanzinger** [comment]
[Archive 2.zip](https://github.com/glygener/glygen-issues/files/13709396/Archive.2.zip)

**Comment by sujeetvkulkarni** [comment]
06add09ec002dcfc3f3109b8ebea7b921e01239a

**Comment by sujeetvkulkarni** [comment]
done. closing the issue.

**Comment by sujeetvkulkarni** [comment]
icon background to white.

**Comment by ReneRanzinger** [comment]
[Archive 3.zip](https://github.com/glygener/glygen-issues/files/13721309/Archive.3.zip)

**Comment by sujeetvkulkarni** [comment]
done. closing the issue.
