### ISSUE TITLE
Create real json data to use on outreach page.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#906]
Final json format getting used now in the frontend.

[input.json](https://github.com/glygener/glygen-issues/files/13688964/input.json)

**Comment by ReneRanzinger** [comment]
@sujeetvkulkarni That is real data please see if it works. If it does we will use it for Beta and Production as well.

[outreach.zip](https://github.com/glygener/glygen-issues/files/13952833/outreach.zip)

**Comment by sujeetvkulkarni** [comment]
Mapping file for the outreach page.
Funding project names need change.

```
  "funding": {
    "GlyGen U24": {
      "id": "GlyGen U24",
      "label": "GlyGen U24",
      "order": 1
    },
    "CFDE": {
      "id": "CFDE",
      "label": "CFDE",
      "order": 2
    },
    "default": {
      "id": "default",
      "label": "Default",
      "order": 101
    }
  },
```
[outreach.json](https://github.com/glygener/glygen-issues/files/13954016/outreach.json)

**Comment by ReneRanzinger** [comment]
@sujeetvkulkarni Change the mapping file for funding:

GlyGen U01   =>		GlyGen U01 (2017-2023)
GlyGen R24   => 	GlyGen R24 (2022-2027)
CFDE		 =>		CFDE

**Comment by ReneRanzinger** [comment]
[outreach.json](https://github.com/glygener/glygen-issues/files/13954073/outreach.json)

**Comment by sujeetvkulkarni** [comment]
e71941504aa84f13dcb786350bacc850215f6df4
