### ISSUE TITLE
For some glycans json/metadata is missing.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#908]
image_metadata api call returns, 
```
{
  "status": "comming soon"
}
```
it should return proper json object. Please also check if any other glycans have similar problem.

https://api.tst.glygen.org/glycan/image_metadata/G46799JK
https://tst.glygen.org/glycan/G46799JK

https://api.tst.glygen.org/glycan/image_metadata/G00171RJ
https://tst.glygen.org/glycan/G00171RJ

**Comment by kmartinez834** [comment]
- There are 1296 missing json files
--> @rykahsay Log file saved to /software/glygen/logs/missing_img_json.csv
- There are 0 missing png files
- There are 0 missing svg files

**Comment by rykahsay** [comment]
Now you will get empty json:

For example: https://api.tst.glygen.org/glycan/image_metadata/G62018OZ/


<img width="561" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/59445ff3-6223-40ec-95a9-1ca7eb02c264">

**Comment by sujeetvkulkarni** [comment]
@kmartinez834 @rykahsay Can we please check why in some cases JSON files are missing. Ideally I think all glycans those have svg should have associated json.

**Comment by kmartinez834** [comment]
Adding to the 1/10 developer agenda

FYI @edwardsnj
