### ISSUE TITLE
Backend should return json with error message for json/metadata api and empty svg file for svg api in case respective files are missing for a glycan.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#910]
- If no JSON data is available for a glycan then backend API responding with image metadata should return the attached JSON with error message 
[Missing_JSON.json](https://github.com/glygener/glygen-issues/files/13746100/Missing_JSON.json)

https://api.tst.glygen.org/glycan/image_metadata/G17689DH/

- If no SVG file is available for a glycan then backend API responding with SVG image should return the attached empty SVG image 
[Missing_svg.svg](https://github.com/glygener/glygen-issues/assets/13891482/4436eec8-2d22-45e0-97d2-9fa4ca969b82)

https://api.tst.glygen.org/glycan/image_svg/G17689DH/

Status code in both above cases should be,
Status Code: 200

**Comment by rykahsay** [comment]
$ http POST :8082/glycan/image_metadata/foo/
```
HTTP/1.1 200 OK
Connection: close
Content-Length: 56
Content-Type: application/json
Date: Fri, 22 Dec 2023 03:06:24 GMT
Server: gunicorn

{
    "error_list": [
        {
            "error_code": "non-existent-record"
        }
    ]
}
```

$ http POST :8082/glycan/image_svg/foo/
```
HTTP/1.1 200 OK
Cache-Control: public, max-age=43200
Connection: close
Content-Length: 177
Content-Type: image/svg
Date: Fri, 22 Dec 2023 03:06:55 GMT
ETag: "1703214304.02151-177-692984454"
Expires: Fri, 22 Dec 2023 15:06:55 GMT
Last-Modified: Fri, 22 Dec 2023 03:05:04 GMT
Server: gunicorn

<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="100" viewBox="0 0 100 100" width="100">
</svg>
```

**Comment by sujeetvkulkarni** [comment]
done. closing the issue.
