### ISSUE TITLE
Biomuta and Bioxpress Datasets

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#911]
After running check-dataset-group.py we found major change in the datasets. However I haven't created any ticket for any changes to these datasets and the following datasets that use these files. I am not aware if you have done anything at your end.

The row and id count shows major change which have affected downstream datasets. Also the status flag for human_protein_mutation_cancer.csv says structure_change however I compared with the previous 2.2.1 version and found no change in the headers.

Let me know if this was expected.

```
human_protein_expression_normal.csv
human_protein_mutation_cancer.csv
```

| id_count_diff | id_count_new | id_count_old | row_count_diff | row_count_new | row_count_old | field_count_diff | field_count_new | field_count_old | dataset_file_name                   | status_flags                                                   |
| ------------- | ------------ | ------------ | -------------- | ------------- | ------------- | ---------------- | --------------- | --------------- | ----------------------------------- | -------------------------------------------------------------- |
| \-678         | 18693        | 19371        | \-6605         | 217889        | 224494        | 0                | 12              | 12              | human_protein_expression_normal.csv | old_dataset; rowcount_change; idcount_change                   |
| \-8198        | 8887         | 17085        | \-135935       | 57032         | 192967        | 1                | 22              | 21              | human_protein_mutation_cancer.csv   | old_dataset; structure_change; rowcount_change; idcount_change |

**Comment by rykahsay** [comment]
Looks like you didn't compare agains 2.2.1. This is what I see from logs/luke.johnson_qc_check_protein_datasets.csv and logs/rykahsay_qc_check_protein_datasets.csv


```
"1","18693","18692","13","217889","217876","0","12","12","human_protein_expression_normal.csv","old_dataset; rowcount_change; idcount_change"
"19","8887","8868","184","57032","56848","0","22","22","human_protein_mutation_cancer.csv","old_dataset; rowcount_change; idcount_change"
```

It looks like you didn't use refrel to be 2.2.1 --> looks like you used one of [1.12.1,  1.12.2, 1.12.3, 1.13.1, 2.0.1] as can be seen below.

```
    192968    3123520   48905603 /data/shared/glygen/releases/data/v-1.12.1/reviewed/human_protein_mutation_cancer.csv
    192968    3123520   48905603 /data/shared/glygen/releases/data/v-1.12.2/reviewed/human_protein_mutation_cancer.csv
    192968    3123520   48905603 /data/shared/glygen/releases/data/v-1.12.3/reviewed/human_protein_mutation_cancer.csv
    192968    3123520   48905603 /data/shared/glygen/releases/data/v-1.13.1/reviewed/human_protein_mutation_cancer.csv
    192968    3123520   48905603 /data/shared/glygen/releases/data/v-2.0.1/reviewed/human_protein_mutation_cancer.csv
```
