### ISSUE TITLE
remove annotation_category from your queries

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#913]
When someone is doing advanced search for glycans and want to get glycans by organis, you are sending the following query. You will need to remove the "annotation_category" from your query since we have removed it from the JSON objects

```
{
	"operation":"AND",
	"query_type":"search_glycan",
	"glycan_name":"",
	"organism":{
		"organism_list":[
			{"name":"Homo sapiens","id":9606}
		],
		"annotation_category":"",
		"operation":"or"
	}
}
```

**Comment by sujeetvkulkarni** [comment]
@rykahsay @ReneRanzinger 
I believe the request - #869 was to remove "annotation_category" from evidence objects part of species array on details pages/apis to create one object per species in the species array not from glycan search inputs. In my opinion we should not change search interface with respect to "annotation_category" as it is getting used to provide - Any (empty annotation_category value), Annotated (direct), Inferred (subsumption) options to user on frontend.

**Comment by kmartinez834** [comment]
Put back the annotation category with values "direct" and "subsumption" (see above)

**Comment by rykahsay** [comment]
Annotation category can have the following values:
"subsumption" --> (mapped to "Inferred" in frontend pulldown)
"direct" -->  (mapped to "Annotated" in frontend pulldown)
"" --> (mapped to "Any" in frontend pulldown)
"both" --> (not mapped in frontend pulldown --> you may need to add this in your pulldown)


```
{
	"operation":"AND",
	"query_type":"search_glycan",
	"glycan_name":"",
	"organism":{
		"organism_list":[
			{"name":"Homo sapiens","id":9606}
		],
		"annotation_category":"both",
		"operation":"or"
	}
}
```

**Comment by sujeetvkulkarni** [comment]
done.
