### ISSUE TITLE
Release notes before beta release on 10th of January

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#917]
@sujeetvkulkarni 
* Add the 4-7 main changes on [Portal release note page](https://wiki.glygen.org/Portal_release_notes)
* Add the same items on the [General release notes page](https://wiki.glygen.org/Release_notes)
* Add detailed release notes on the [2.3 page](https://wiki.glygen.org/Portal_release_notes/2.3)

@jeet-vora and @kmartinez834 
*  Add the 4-7 main changes on [Data release notes page](https://wiki.glygen.org/Data_release_notes)
* Add the same items on the [General release notes page](https://wiki.glygen.org/Release_notes)
* Create  detailed release notes page with the right version number by editing [Data release notes page](https://wiki.glygen.org/Data_release_notes) and clicking on the link
* Add the link to the [General release notes page](https://wiki.glygen.org/Release_notes)

**Comment by sujeetvkulkarni** [comment]
Done. Will amend the release notes once new issues are closed.

**Comment by sujeetvkulkarni** [comment]
Done.

**Comment by kmartinez834** [comment]
Done
