### ISSUE TITLE
Setup GlyGen failover on AWS

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#918]
As part of 2.4 Robel and **xxx** will work on setting up a running GlyGen instance:
* Frontend
* MongoDB and API
* SparQL
* Data
 
on AWS. This instance will be updated together with the mayor release to production and serve as a failover in case GlyGen is intentional or incidentally down.

**Blocker for**
* #919

**Comment by rykahsay** [comment]
@Luke-Johnson-5  ... https://aws.api.glygen.org/ is now working. Please set up a webex meeting with @sujeetvkulkarni so that he can help you with deployment of the frontend on our aws server
