### ISSUE TITLE
Checking group of datasets in comparison to old release

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#92]
I have created a script on how to check a group of datasets (glycan/protein/proteoform), please document and use

$ cd /software/glygen/
$ python3 check-dataset-group.py  -m glycan -r 1.12.3

Output
=====
id_count_diff,id_count_new,id_count_old,row_count_diff,row_count_new,row_count_old,field_count_diff,field_count_new,field_count_old,dataset_file_name
0,364,364,0,364,364,0,2,2,glycan_glytoucan_accession_history.csv
0,123404,123404,0,123404,123404,0,1,1,glycan_glytoucanidlist.csv
0,9276,9276,0,280375,280375,0,12,12,glycan_enzyme.csv
0,1475,1475,0,5446,5446,0,9,9,glycan_citations_glytoucan.csv
0,0,0,0,0,0,0,0,0,glycan_citations_biomarkers.csv
-115,0,115,-274,0,274,-9,0,9,glycan_citations_glycomotif.csv
866,8625,7759,866,8625,7759,0,1,1,glycan_fully_determined.csv
4704,22941,18237,26143,98073,71930,0,10,10,glycan_species.csv
6996,30941,23945,10869,52875,42006,0,7,7,glycan_classification.csv
11437,45192,33755,11437,45192,33755,0,10,10,glycan_masterlist.csv

**Comment by kmartinez834** [comment]
Added to [data_integration.docx](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/[data_integration.docx](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/data_integration.docx?d=w0c84e59c4be6494d91cc017661cc9944&csf=1&web=1&e=OV3clO)?d=w0c84e59c4be6494d91cc017661cc9944&csf=1&web=1&e=OV3clO) >>Testing >> Dataset Testing

**Comment by kmartinez834** [comment]
@rykahsay --> Please change `wrk_dir` path in check-dataset-group.py

I'm getting the following error:

```
$ python3 check-dataset-group.py -m glycan -r 1.12.3
Traceback (most recent call last):
  File "check-dataset-group.py", line 115, in <module>
    main()
  File "check-dataset-group.py", line 58, in main
    ds_obj_list = json.loads(open(misc_dir + "dataset-masterlist.json", "r").read())     
PermissionError: [Errno 13] Permission denied: '/home/rykahsay/glygen-backend-integration/object-maker/generated/misc/dataset-masterlist.json'
```

**Comment by rykahsay** [comment]
done -- try again

**Comment by kmartinez834** [comment]
👍
