### ISSUE TITLE
GlyGen AWS Deployment

### ISSUE THREAD

**Issue by tiwa1154** [glygener/glygen-issues#924]

**Comment by tiwa1154** [comment]
@jeet-vora Please track the AWS progress here and leave comments here

**Comment by tiwa1154** [comment]
@rykahsay I have created a ticket for the deployment.

**Comment by tiwa1154** [comment]
@rykahsay Issue with testing APIs, seems like there are some errors but I am not sure how to fix them:
![Screenshot 2024-01-08 at 12 47 06](https://github.com/glygener/glygen-issues/assets/90009613/40888d0e-903b-45dd-a274-34acd58f2665)

**Comment by tiwa1154** [comment]
@rykahsay issue below:
![Screenshot 2024-01-09 at 12 00 07](https://github.com/glygener/glygen-issues/assets/90009613/84cb06d8-9168-451c-b394-088c5c7e1c05)

**Comment by rykahsay** [comment]
Edit queries/dataset_historydetail.json and change version to the data version you are using, and ignore the the /dataset/submit and gsd/submit APIs for now

**Comment by tiwa1154** [comment]
@rykahsay What about the Mapping APP and API containers issue:
![Screenshot 2024-01-09 at 12 00 07](https://github.com/glygener/glygen-issues/assets/90009613/9eb6a538-5ab5-41bf-8112-b59e03cd3ede)

**Comment by tiwa1154** [comment]
@rykahsay For the [glygen-backend-api](https://github.com/glygener/glygen-backend-api) repo, which branch should I work on?

**Comment by tiwa1154** [comment]
@ReneRanzinger I am trying to deploy frontend on AWS, followed server-installation.md and ran into the issues below:
1. where is the docker-glygen-frontend.service file, if not exit, what's the content for the file?
![Screenshot 2024-01-10 at 9 53 11](https://github.com/glygener/glygen-issues/assets/90009613/cecdcf50-2652-4b0b-8097-23d106467d6e)
2. Receive error `make: docker-compose: No such file or directory` and `make: *** [MakeFile:22: prod] Error 127`
![Screenshot 2024-01-10 at 9 54 46](https://github.com/glygener/glygen-issues/assets/90009613/0baccb4d-6599-411f-8dc1-bfef26461c4c)

**Comment by tiwa1154** [comment]
@rykahsay Can't download data for `[glygen-backend-api](https://github.com/glygener/glygen-backend-api)` repo, figured it's related to `userdata_dir = config_obj["data_path"] + "/userdata/%s/jobs/" % (config_obj["server"])` in download_data.py. 
![Screenshot 2024-01-10 at 11 44 51](https://github.com/glygener/glygen-issues/assets/90009613/4585d6ad-1657-4caa-b4ac-3e14470c13e7)

**Comment by Luke-Johnson-5** [comment]
@rykahsay @ReneRanzinger I don't have access to the AWS server yet but I know these issues that Tianyi submitted yesterday and the day before are blockers. If you have some time please look at these.

**Comment by rykahsay** [comment]
What exactly is the blocker now?

**Comment by Luke-Johnson-5** [comment]
I believe I may need to contact Rene or Sujeet about the front end issues however;
@rykahsay The blockers are as follows:



GlyGen Backend Api:
Which branch should I be working on? and the data download using download_data.py is returning the following error.
![image](https://github.com/glygener/glygen-issues/assets/144174552/f7237f58-aed0-42a2-95fc-d027398ed32e)

GlyGen Backend Dataset viewer: 
Mapping APP and API containers issue:
![image](https://github.com/glygener/glygen-issues/assets/144174552/6bf19b3a-f16c-4bf0-b5c8-77f34fe8de6d)

Glygen Front End:
Where is the docker-glygen-frontend.service file, if not exit, what's the content for the file?
![image](https://github.com/glygener/glygen-issues/assets/144174552/4a56015b-4b2b-4bfa-95f0-7b225b857da0)
Receive error make: docker-compose: No such file or directory and make: *** [MakeFile:22: prod] Error 127
![image](https://github.com/glygener/glygen-issues/assets/144174552/ab9b10d5-5000-4ba5-9a86-8d5fc56fd982)

**Comment by rykahsay** [comment]
"Which branch should I be working on? and the data download using download_data.py is returning the following error."
```
work with 2.1.1 for now and  you need to use "sudo python3 download_data.py -s prd -v 2.1.1 "
```

On the apache restart issue:
I have tried to fix it and the following command should work now.
```
$ sudo apachectl restart
```

Location of docker-glygen-frontend.service 
```
/usr/lib/systemd/system/docker-glygen-frontend.service 
```


You need to do the following after you build the containers for the frontend

```
  $ sudo systemctl daemon-reload 
  $ sudo systemctl enable docker-glygen-frontend.service
  $ sudo systemctl start docker-glygen-frontend.service
```

**Comment by rykahsay** [comment]
@tiwa1154   .... since Luke has created another ticket on this now, please close this
