### ISSUE TITLE
UniprotKB recommended name for accessions missing. 

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#925]
UniprotKB Recommended names for proteins are not appearing on tst API but appear to be in the dataset.

![Screenshot 2024-01-05 125448](https://github.com/glygener/glygen-issues/assets/144174552/0204329d-e3ca-46fd-8bea-3ff0bbf4b54a)
![Screenshot 2024-01-05 125456](https://github.com/glygener/glygen-issues/assets/144174552/a0bbdd3f-9737-41c3-9b5e-48a2621280a5)

fyi: @jeet-vora

**Comment by rykahsay** [comment]
@Luke-Johnson-5 -- next time you report an issue that involves API response, you need to provide the API URL and request input

**Comment by rykahsay** [comment]
I have tried to fix it, please check now
