### ISSUE TITLE
Add Glycan Structure Dictionary xref to motif API

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#93]
Final result should look like this example (modified from [GGM.000115](https://api.glygen.org//motif/detail?query={%22motif_ac%22:%22GGM.000115%22})):
```json
"crossref": [
    {
      "url": "https://glytoucan.org/Structures/Glycans/G18625KA", 
      "id": "G18625KA", 
      "database": "GlyTouCan"
    },
    {
      "url": "https://wiki.glygen.org/index.php/Glycan_structure_dictionary#GSD000096", 
      "id": "GSD000096", 
      "database": "Glycan Structure Dictionary"
    }
  ]
```

Once this is done, @kmartinez834 to make ticket for front end to add link to Cross References

**Comment by rykahsay** [comment]
Done --> it will look like this now:

"crossref": [
        {
            "id": "G18625KA",
            "database": "GlyTouCan",
            "url": "https://glytoucan.org/Structures/Glycans/G18625KA"
        },
        {
            "id": "GSD000096",
            "url": "https://wiki.glygen.org/index.php/Glycan_structure_dictionary#GSD000096",
            "database": "Glycan Structure Dictionary"
        }
    ]

**Comment by kmartinez834** [comment]
Front end issue opened: #183
