### ISSUE TITLE
Exception Errors in Swagger Data Download API

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#931]
These API URLs are returning exception errors and may need to be looked at:

These payloads are the default inputs.

| API URL                | Payload                                                                                                     | Response                                                                                             |
| ---------------------- | ----------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------- |
| /data/detail_download/ | {<br>  "id": "G17689DH",<br>  "type": "glycan_detail",<br>  "format": "json",<br>  "compressed": false<br>} | {<br>  "error_list": [<br>    {<br>      "error_code": "exception-error-5HCHA0"<br>    }<br>  ]<br>} |
| /data/list_download/   | {<br>  "id": "",<br>  "type": "glycan_list",<br>  "format": "csv",<br>  "compressed": false<br>}            | {<br>  "error_list": [<br>    {<br>      "error_code": "exception-error-TMOAQK"<br>    }<br>  ]<br>} |

**Comment by rykahsay** [comment]
Changed the example query -- please check all of them again

<img width="652" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/1f7ea098-39b8-4f4a-bba8-c2cb010a60fa">

**Comment by Luke-Johnson-5** [comment]
looks good.
