### ISSUE TITLE
Processing API request logs to compare to Google Analytics

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#932]
@kmartinez834  if you have created a ticket for me on this, please close it.

Please use and document this:

```
$ cd /software/glygen/
$ python3 dump-api-request-stats.py -y 2023 -m 12
```

The above instructions will generate two files under logs/ folder

```
logs/rykahsay_api_request_stats_daily.csv
logs/rykahsay_api_request_stats_monthly.csv

$ cd /software/glygen/

$ head -5 logs/rykahsay_api_request_stats_daily.csv
"request_end_point","request_date","request_count_total","request_count_frontend"
"/auth/userid/","2023-12-02","6","unknown-api2page-map"
"/auth/userid/","2023-12-03","1","unknown-api2page-map"
"/auth/userid/","2023-12-04","4","unknown-api2page-map"
"/auth/userid/","2023-12-05","2","unknown-api2page-map"

$ head -5 logs/rykahsay_api_request_stats_monthly.csv 
"request_end_point","request_count_total","request_count_frontend"
"/auth/userid/","90","0"
"/biomarker/detail/","56","77"
"/data/detail_download/","11","0"
"/data/list_download/","46","0"
```

ls -ltr logs/rykahsay_api_request_stats_monthly.csv 
-rw-r--r--. 1 rykahsay glygen 1550 Jan  8 14:34 logs/rykahsay_api_request_stats_monthly.csv
[rykahsay@glygen-vm-dev glygen]$ python3 dump-api-request-stats.py -y 2023 -m 12

**Comment by kmartinez834** [comment]
I've added this to the [Data Integration](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/Tutorials/[data_integration.docx](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/Tutorials/data_integration.docx?d=w0c84e59c4be6494d91cc017661cc9944&csf=1&web=1&e=ksjrKU)?d=w0c84e59c4be6494d91cc017661cc9944&csf=1&web=1&e=ksjrKU) document
