### ISSUE TITLE
Usecases species_to_glycosyltransferases not working for Dicty

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#935]
https://api.tst.glygen.org/usecases/species_to_glycosyltransferases/44689/

```
{
  "error_list": [
    {
      "error_code": "exception-error-DWINVN"
    }
  ]
}
```

**Comment by kmartinez834** [comment]
Also:

https://api.tst.glygen.org/usecases/species_to_glycohydrolases/44689/
https://api.tst.glygen.org/usecases/species_to_glycoproteins/44689/both/

**Comment by rykahsay** [comment]
Check now

**Comment by kmartinez834** [comment]
👍
