### ISSUE TITLE
Uniprot AC 26662-1 protein detail page not working.

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#936]
The front end at https://tst.glygen.org/protein/P26662-1 gets stuck loading forever however the API appears to be working.

API URL /protein/detail/{uniprot_canonical_ac}/ 
Query:
{
  "uniprot_canonical_ac": "P26662-1"
}
Response: 
[response_1704813213011.json](https://github.com/glygener/glygen-issues/files/13875529/response_1704813213011.json)

**Comment by rykahsay** [comment]
@sujeetvkulkarni -- do you know what is going on here?

**Comment by sujeetvkulkarni** [comment]
Looks like some backend data issue, now fixed. Can you please check.
