### ISSUE TITLE
Motif images not available

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#937]
https://tst.glygen.org/list-of-motifs/

![image](https://github.com/glygener/glygen-issues/assets/90285371/1eae946a-87ec-4dc0-aacc-878e142c1f5d)

**Comment by rykahsay** [comment]
check now

**Comment by kmartinez834** [comment]
Now just [GGM.000001](https://tst.glygen.org/motif/GGM.000001) is missing.  Should be the same image as https://tst.glygen.org/glycan/G00055MO
![image](https://github.com/glygener/glygen-issues/assets/90285371/1d656716-a795-438d-9a8c-c86553b3e229)

**Comment by rykahsay** [comment]
Maybe you need to clean your cache, this is what I see:

<img width="940" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/adacae7e-53e2-4a89-81ca-304754f0f4d1">

**Comment by kmartinez834** [comment]
Yes, working now
