### ISSUE TITLE
Master list for 2.4 data download 

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#938]
List of resources downloaded for 2.4:

| Resource | Downloaded by | Notes | Issue |
| -------- | ------- | ------- | ------- |
| Cellosaurus | Karina | | |
| ChEBI|Karina  | | |
| Glyconnect |Karina | Added pig  |  |
| OMA| Jingyue |Added pig  | #1028 -> done, closed the ticket|
| Reactome | Karina |  |  |
| EBI | Jingyue  | confirm Sus scrofa is included in 2.4 |  |
| NCBI RefSeq  | Jingyue | confirm Sus scrofa is included in 2.4; bash script and README.txt have been updated to include this |#1031 |
| Genome Alliance  |Karina  |Added orthology_alliance_combined.tsv  | |
| O-GlcNAc DB | Jingyue |  |  |
| Disease Ontology |Karina  |  |  |
| MGI | Jingyue |  |  |
| Mondo | Jingyue |  |
| Medline |Robel  | |#1029  |
| InChI |Robel  |  |#1029  |
| matrixdb | Karina |  |  |
| genomics_england |Karina  |  |  |
| iPTMnet | Karina |  ||
| Glycan Array Data Repository| Karina | new dataset |#1078|

**Comment by JingyueWu** [comment]
@jeet-vora @kmartinez834 I've finished downloading most of the data resources I've been responsible for, please take a look at the above table. Karina, could you please write scripts for Genomics England and update the script for Genome Alliance?

**Comment by kmartinez834** [comment]
@JingyueWu can you update the Data Download document with the download scripts you used, and any other required steps?  Let's move away from using README's in the folders

**Comment by jeet-vora** [comment]
@JingyueWu @kmartinez834 Lets discuss about download documentation together.

@JingyueWu Setup a separate meeting for all of us.

**Comment by JingyueWu** [comment]
Reopening this ticket to use it as a reference to track status for 2.4 downloads.
