### ISSUE TITLE
check-citation-datasets.py

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#94]
Robel can you add the feature in your script to compare PMIDs in src_file and citations_file and print out the PMIDs not in the citations files.

@kmartinez834 @JingyueWu

**Comment by rykahsay** [comment]
The script now creates files under the "logs/" subdirectory

$ cd /software/glygen/
$ python3 check-citation-datasets.py  > summary.csv &
$ ls -ltr logs/

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/20584876/222821862-84d79f83-0555-4add-a0c5-79ca64b69808.png">

**Comment by jeet-vora** [comment]
Done
