### ISSUE TITLE
30k result report

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#943]
Karina to provide stats from proteoform_glycosylation_sites_literature_mining.csv w/ overlapping and discrete glycan, sites & proteins 

For both:
* Proteins 
* Sites

Find the numbers
* How many where in the original dataset
* How many are in the 30k dataset
* How many are unique to the original dataset
* How many are unique to the 30k dataset

Either as an email to Raja, Mike, Rene and others or we talk about it in one of the Wednesday meetings.

**Comment by kmartinez834** [comment]
![image](https://github.com/glygener/glygen-issues/assets/90285371/1ca666ba-3ffc-4873-852b-572511ae99d1)

**Comment by kmartinez834** [comment]
@rykahsay was the 30k abstract data processed through the old Udel pipeline?  Raja is planning to discuss it during the F2F so just checking

**Comment by kmartinez834** [comment]
Sorry, previous figures (removed from the thread) used processed dataset with both legacy and 30k data.  Diagrams below show overlap between the original 2k abstracts and the new 30k abstracts:

![image](https://github.com/glygener/glygen-issues/assets/90285371/674c0c75-e4da-4849-bf25-56d76c619742)

**Comment by rykahsay** [comment]
I hope my presentation on the F2F made this clear
