### ISSUE TITLE
On protein simple search when category &quot;any&quot; selected and hsa:3082 is searched it gives a network error. I looked into the API and did not get the error. Can you please confirm the error and let Robel know if this is a back end error. 
-Luke Johnson

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#948]
## Details
**Created by:** myGlygen

**Feedback from:** myGlyGen@gmail.com

**Assigned to:** myGlygen

**Priority:**  high

[Open Note](https://app.pageproofer.com/to/note/334840)

## Note
> On protein simple search when category &amp;quot;any&amp;quot; selected and hsa:3082 is searched it gives a network error. I looked into the API and did not get the error. Can you please confirm the error and let Robel know if this is a back end error. 
-Luke Johnson

## Attachments
- [screenshot-2024-01-12 at 2:01:38 pm.jpg](https://s3.amazonaws.com/pageproofer-attachments/18cff0d1e0b/screenshot-2024-01-12+at+2:01:38+pm.jpg)

## Browser Information
**Window Size:** 1500 x 839
**Screen Size:** 1500 x 1000
**Device:** WebKit
**Browser:** Chrome version: 120.0.0.0
**Platform:** Windows version: 10.0

**Comment by sujeetvkulkarni** [comment]
This was a backend issue and looks like it is addressed now. Can you please verify.
