### ISSUE TITLE
InChIKey update

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#95]
Karina like Medline?PubMed Robel also downloads InChIKeys from PubChem and updates the InChIKey database in GlyGen.
Can you check where any new glycan that do not have InChIKey in GlyGen and let Robel know for such cases?

Also we would need to document it.

**Comment by kmartinez834** [comment]
@rykahsay please process InChI key update

**Comment by rykahsay** [comment]
Please check unreviewed/glycan_sequences_inchi.csv now

**Comment by kmartinez834** [comment]
👍 Looks good
