### ISSUE TITLE
Convert Dictyostelium discoideum common name to Slime mold

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#952]
Per Raja and Mike at 1/10 general meeting.

I have updated the `misc/species_info.csv` file.  Please change the following init common names from "Dictyostelium discoideum" to "Slime mold":

```
glycan/search_init/
protein/search_init/
usecases/search_init/
supersearch/search_init/
pages/home_init/
```

**Comment by rykahsay** [comment]
Check
