### ISSUE TITLE
Motif highlight should highlight "root" residue anomer...

### ISSUE THREAD

**Issue by edwardsnj** [glygener/glygen-issues#954]
See: https://glymage.glyomics.org/demo/demo4.html

Of course, since you have multiple types of annotations (IUPAC, Enzyme, and Motif) on the same figure for the glycan details pages, it might take some fancy footwork to make this work - perhaps you can tweak your own CSS creatively, switch the figure's CSS class in javascript when you switch different modes.

**Comment by sujeetvkulkarni** [comment]
@edwardsnj Can we handle the above issue by updating JSON files associated with glycans?

**Comment by edwardsnj** [comment]
I have a fix for this issue, for motif page (simple, existing functionality), and for the glycan details page (requires javascript and css changes). I have developed the fix, you can see here: https://glymage.glyomics.org/demo/demo5.html

On the motif page, the following additional configurations should be sufficient:

 parentlinkclass:       "glymagesvg_low_opacity",
 parentlinkinfoclass:   "glymagesvg_high_opacity_anomer",
 highlight_parent_link: "true",

Note that I'm having some trouble reverse engineering the javascript / css flow, but this *should* work with the current javascript and css.

On the glycan details page you will need a new copy of the glymage.js and glymage.css files, add the above parameters, plus:

imageclass_byannotation: "true"

No updates to the JSON or SVG files are needed.

Cheers!

**Comment by sujeetvkulkarni** [comment]
@edwardsnj thanks above changes work.
