### ISSUE TITLE
Motif pages on beta display hightlighting poorly...

### ISSUE THREAD

**Issue by edwardsnj** [glygener/glygen-issues#955]
...due to the odd/even and hover behavior which changes the background of the table row. This probably needs to be fixed in the CSS applied to the glycan figure (to set the background appropriately). I may be able to clobber to ensure a white background always (as is done for monosaccharides), but is this what is desired?

**Comment by edwardsnj** [comment]
I have updated glymagesvg.js to ensure the figure background remains solid white even when highlighting is applied.

**Comment by sujeetvkulkarni** [comment]
Done, updated glymagesvg.js file in 2.3 branch. 
GitHub SHA: 3df627f705ce679e6db05179634b05db5bbff227
