### ISSUE TITLE
GlyGen AWS deployment blockers

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#956]
Some issues left by Tianyi on ticket [924](https://github.com/glygener/glygen-issues/issues/924) are yet to be addressed. I have gotten AWS access today and would like to continue working on the deployment however, there are some unresolved Issues from when Tianyi was doing this task and if you were able to look at these issues/questions from her and respond in that ticket that would be a great help.

**Comment by rykahsay** [comment]
Let's follow things on that ticket -- I have commented there. Please close this ticket
