### ISSUE TITLE
Protein name is missing in referenced_proteins array of publication detail api.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#957]
https://api.tst.glygen.org/publication/detail?query={"id":"10101234","type":"PubMed","paginated_tables":[{"table_id":"glycosylation_reported_with_glycan","offset":1,"limit":20,"sort":"start_pos","order":"asc"},{"table_id":"glycosylation_reported","offset":1,"limit":20,"sort":"start_pos","order":"asc"},{"table_id":"glycosylation_predicted","offset":1,"limit":20,"sort":"start_pos","order":"asc"},{"table_id":"phosphorylation","offset":1,"limit":20,"sort":"start_pos","order":"asc"},{"table_id":"referenced_proteins","offset":1,"limit":20,"sort":"uniprot_canonical_ac","order":"asc"},{"table_id":"referenced_glycans","offset":1,"limit":20,"sort":"glytoucan_ac","order":"asc"}]}

returns referenced_proteins:[] without protein_name

```
"referenced_proteins": [
        {
            "uniprot_canonical_ac": "Q5HZE6-1",
            "gene_name": "Rnd2",
            "tax_name": "Rattus norvegicus"
        },
        {
            "uniprot_canonical_ac": "Q9QYM5-1",
            "gene_name": "Rnd2",
            "tax_name": "Mus musculus"
        }
    ],
```

**Comment by rykahsay** [comment]
Try now

**Comment by sujeetvkulkarni** [comment]
done.
