### ISSUE TITLE
got geneRange for social amoeba. transcriptRange will be available from 2024_02.

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#958]
@rykahsay @jeet-vora got geneRange for social amoeba. transcriptRange will be available from 2024_02.
Please take a look at updated https://ftp.ebi.ac.uk/pub/contrib/glygen/current_release/uniprot-proteome-dictyostelium-discoideum.nt.gz.

@jeet-vora please close this ticket once verified.

_Originally posted by @pkay47 in https://github.com/glygener/glygen-issues/issues/840#issuecomment-1833304623_

**Comment by pv47** [comment]
@rykahsay geneRange is available in 2024_02, but transcriptRange is still missing. Am looking into it

**Comment by pv47** [comment]
Fixed missing config in one of the pipeline bricks. Input for genomic service generated for 2024_03.  

https://www.ebi.ac.uk/proteins/api/coordinates?offset=0&size=-1&taxid=44689 should have entries after 2024_03 release on 29th may

**Comment by pv47** [comment]
transcriptRange available for dictyostelium/social amoeba in 2024_03.
