### ISSUE TITLE
Downloads button generating empty file

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#959]
https://beta.glygen.org/publication/PubMed/10988252

**Referenced Proteins** and **Reference Glycans** `DOWNLOAD` button generates empty file.

Outfile contents:
```
""
""

```

**Comment by rykahsay** [comment]
That's frontend issue unless you get to the API level and show me the API call

**Comment by kmartinez834** [comment]
@sujeetvkulkarni can you look into this? Also, can you let me know which API call you use for the publications page downloads?

**Comment by sujeetvkulkarni** [comment]
@kmartinez834 sure, I will add api details here for your reference and let Robel know. This is a backend issue. I will assign the ticket to Robel after adding those details.

**Comment by sujeetvkulkarni** [comment]
@rykahsay @kmartinez834 please find the API details below,

Referenced protein,

API:
https://beta-api.glygen.org/data/section_download?query=
{"id":"pubmed.10988252","download_type":"publication_section","section":"referenced_proteins","format":"csv","compressed":false}

response:
```
""
""
```

Referenced glycan,

API:
https://beta-api.glygen.org/data/section_download?query=
{"id":"pubmed.10988252","download_type":"publication_section","section":"referenced_glycans","format":"csv","compressed":false}

response:
```
""
""
```

In both above cases a file with proper data should be returned from the API.

**Comment by rykahsay** [comment]
Check now

**Comment by kmartinez834** [comment]
Referenced proteins is working, but Referenced Glycans is still giving an empty file.

**Comment by rykahsay** [comment]
Check now

**Comment by kmartinez834** [comment]
Looks good
