### ISSUE TITLE
In feature view, N-acetly Glucosamine is mispelled...

### ISSUE THREAD

**Issue by edwardsnj** [glygener/glygen-issues#960]
...should be N-acetyl Glucosamine

Cheers!

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger 
For this I will update the json directly but you also need to update the excel from which json is getting generated.

**Comment by sujeetvkulkarni** [comment]
Made changes in 2.3 branch.
GitHub : ddc6ed36ba93bd11ad0197a3a5d8ed84e4e827c2

@ReneRanzinger please correct the corresponding excel spreadsheet.

**Comment by ReneRanzinger** [comment]
@sujeetvkulkarni did you fix it? And which Excel file?

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger yes, I have fixed this in 2.3 branch.
I was talking about updating excel file you used in #842 to create JSON file - [Excel file](https://github.com/glygener/glycan.viewer.json.converter/blob/main/data/glycan-viewer-residues.xlsx) .
