### ISSUE TITLE
common name is same as name for Dictyostelium discoideum species on protein details page. Common name should be Slime Mold.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#964]
API:
https://beta-api.glygen.org/protein/detail/P04988-1/

    "species": [
        {
            "name": "Dictyostelium discoideum",
            "taxid": 44689,
            "evidence": [
                {
                    "database": "UniProtKB",
                    "id": "P04988",
                    "url": "https://www.uniprot.org/uniprot/P04988"
                }
            ],
            "common_name": "Dictyostelium discoideum"
        }
    ],

**Comment by rykahsay** [comment]
<img width="1342" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/411e8f72-487b-4c18-830a-c263670c9c22">

**Comment by sujeetvkulkarni** [comment]
done.
