### ISSUE TITLE
Do we need to use organism common name on list/result pages too?

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#965]
1. protein/list api (https://beta-api.glygen.org/protein/list) filter section shows common name (Human) and table shows name (Homo sapiens). Backend needs to send common name in this case.
https://beta-api.glygen.org/protein/list?query=
{"id":"a46c706d17d264f07ba71f98dd5424d9","offset":1,"limit":20,"order":"desc","sort":"hit_score","filters":[]}

```
{
  "uniprot_canonical_ac": "P14210-1",
  "mass": 83134,
  "protein_name": "Hepatocyte growth factor",
  "gene_name": "HGF",
  "organism": "Homo sapiens",
  "refseq_name": "hepatocyte growth factor isoform 1 preproprotein",
  "refseq_ac": "NP_000592",
  "gene_names_uniprotkb": "HGF; HPTA",
  "gene_names_refseq": "DFNB39; F-TCF; HGFB; HPTA; SF; HGF",
  "protein_names_uniprotkb": "Hepatocyte growth factor; Hepatopoietin-A; SF; Scatter factor",  
}
```
<img width="1550" alt="Screenshot 2024-01-19 at 8 30 52 PM" src="https://github.com/glygener/glygen-issues/assets/13891482/35d208c0-5e2b-48bd-b020-e1aad2f9736d">

2. supersearch/list api also sends name (Homo sapiens) instead of common name (Human).
https://beta-api.glygen.org/supersearch/list?query=
{"id":"09a7c68179c78b465dc37c421e7c337a","offset":1,"sort":"hit_score","limit":20,"order":"desc","filters":[]}

<img width="1550" alt="Screenshot 2024-01-19 at 8 30 52 PM" src="https://github.com/glygener/glygen-issues/assets/13891482/3faa4b44-0767-48c6-aaef-597bd5a1fd89">

```
{
  "uniprot_canonical_ac": "Q9NZ52-1",
  "protein_name": "ADP-ribosylation factor-binding protein GGA3",
  "start_pos": 276,
  "end_pos": 276,
  "site_seq": "L",
  "tax_id": 9606,
  "organism": "Homo sapiens",
  "record_type": "site",
}
```

3. same with /usecases/genelocus_list  api "organism" is "Homo sapiens" instead of Human.
https://beta-api.glygen.org/usecases/genelocus_list?query=
{"id":"dc6c48316a12e3f4a3bcb0bd4b9e0d76","offset":1,"sort":"uniprot_canonical_ac","limit":20,"order":"asc"}

response
```
       {
            "uniprot_canonical_ac": "O60512-1",
            "protein_name": "Beta-1,4-galactosyltransferase 3",
            "gene_name": "B4GALT3",
            "gene_link": "https://www.uniprot.org/uniprot/O60512",
            "tax_id": 9606,
            "organism": "Homo sapiens",
            "chromosome": "1",
            "start_pos": 161176060,
            "end_pos": 161171819
        },
```

4. with  /usecases/ortholog_list 
https://beta-api.glygen.org/usecases/ortholog_list?query=
{"id":"7db9220fe2a58c1b7724ec1a582c08c5","offset":1,"sort":"uniprot_canonical_ac","limit":20,"order":"desc"}
backend sends both name and common name in this case, front end needs to use common name.

5.similarly [/blast-result/](https://beta.glygen.org/blast-result/14) also shows name instead of common name do we need to change it there too (in all places)? backend sends both name and common name in case of blast result.

**Comment by ReneRanzinger** [comment]
@sujeetvkulkarni @rykahsay : We should be using the species names consistently across the portal. That being said I will move this to 2.4 since we will be working on details pages in this context anyway and I do not want to make any of these changes days before the release.

**Comment by rykahsay** [comment]
Good idea, I am labeling this ticket 2.4

**Comment by rykahsay** [comment]
<img width="1248" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/1f7ef4ed-0f0a-4648-a0b3-9210b6b55b4b">

**Comment by sujeetvkulkarni** [comment]
For Point 3 - /usecases/genelocus_list api - #1142.

**Comment by sujeetvkulkarni** [comment]
cbbf4e39784521a13448f2198e87566841c81bb5
