### ISSUE TITLE
2.3 DOI Issue

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#966]
@kmartinez834 

The DOI link is not working for one of the biomarker. Can you check - 

<img width="657" alt="image" src="https://github.com/glygener/glygen-issues/assets/25825266/a5116394-b26f-4723-bc52-ccaf55f7101f">

https://beta.glygen.org/biomarker/A0078
https://glygen.org/publication/DOI/10.1101/2020.05.31.20118315

**Comment by kmartinez834** [comment]
@rykahsay `compiled/doi_citations.csv` needs to be updated --> is this done manually or does a script populate it?

**Comment by kmartinez834** [comment]
There are 798 publications without json objects (784 pubmed, 14 doi).  See `misc/missing_pubs.csv` for list.

Couple notes:
- `yeast_proteoform_phosphorylation_sites_iptmnet.csv` has some pmid's that look like they've been concatenated, but it's an error in the source file (`downloads/iptmnet/2023_10_13/ptm.txt`)
```
"protein_xref_pubmed","1629231415665377","/data/shared/glygen/releases/data/v-2.3.1/reviewed/yeast_proteoform_phosphorylation_sites_iptmnet.csv"
"protein_xref_pubmed","1840795619779198","/data/shared/glygen/releases/data/v-2.3.1/reviewed/yeast_proteoform_phosphorylation_sites_iptmnet.csv"
"protein_xref_pubmed","1982375019795423","/data/shared/glygen/releases/data/v-2.3.1/reviewed/yeast_proteoform_phosphorylation_sites_iptmnet.csv"
```
- Script to generate the outfile above: `/software/glygen/check-pubs.py`

**Comment by rykahsay** [comment]
You will need to add rows in compiled/doi_citations.csv for the following doi artcile IDs:

doi.org/10.3389/fragi.2021.757801,unreviewed/mouse_proteoform_glycosylation_sites_oglcnac_atlas.csv
10.1074/mcp.M114.046862,unreviewed/human_proteoform_glycosylation_sites_unicarbkb.csv
10.1038/s42256-020-0180-7,unreviewed/human_protein_biomarkers.csv
10.1101/2020.03.10.20033613,unreviewed/human_protein_biomarkers.csv
10.1101/2020.05.27.20114678,unreviewed/human_protein_biomarkers.csv
10.2139/ssrn.3552854,unreviewed/human_protein_biomarkers.csv
10.21203/rs.3.rs-29567/v1,unreviewed/human_protein_biomarkers.csv
10.1101/2020.03.19.20034447,unreviewed/human_protein_biomarkers.csv
10.1101/2020.05.31.20118315,unreviewed/human_protein_biomarkers.csv
10.33218/001c.13525,unreviewed/human_protein_biomarkers.csv
10.21203/rs.3.rs-78038/v2,unreviewed/human_protein_biomarkers.csv

**Comment by kmartinez834** [comment]
Done

**Comment by rykahsay** [comment]
<img width="913" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/636b4378-219e-4329-a1fe-61c7a5144fb6">

**Comment by kmartinez834** [comment]
Biomarker is missing from Publication page and API: https://glygen.org/publication/DOI/10.1101/2020.05.31.20118315

![image](https://github.com/glygener/glygen-issues/assets/90285371/4c0f8b57-a117-4b18-a37e-6ed332431e9f)

**Comment by rykahsay** [comment]
<img width="1320" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/94c90dbc-771d-43a5-931d-2d5a685dbd49">

**Comment by kmartinez834** [comment]
👍
