### ISSUE TITLE
https://beta.glygen.org/protein/P14328-1 for Dictyostellium is not working. Can you check. I guess the backend is working.

jkv

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#967]
## Details
**Created by:** myGlygen

**Feedback from:** myGlyGen@gmail.com

**Assigned to:** myGlygen

**Priority:**  high

[Open Note](https://app.pageproofer.com/to/note/335871)

## Note
> https://beta.glygen.org/protein/P14328-1 for Dictyostellium is not working. Can you check. I guess the backend is working.

jkv

## Browser Information
**Window Size:** 1269 x 714
**Screen Size:** 1440 x 900
**Device:** Macintosh
**Browser:** Chrome version: 120.0.0.0
**Platform:** OS X version: 10_15_7

**Comment by sujeetvkulkarni** [comment]
This issue has been fixed in tst - https://tst.glygen.org/protein/P14328-1
Please check.

**Comment by jeet-vora** [comment]
checked
no issue
