### ISSUE TITLE
beta-data.glygen.org tsv viewer formatting

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#968]
TSV file data is bunched up in the first column:
https://beta-data.glygen.org/GLY_000555
https://beta-data.glygen.org/GLY_000410
https://beta-data.glygen.org/GLY_000627

Ex.
![image](https://github.com/glygener/glygen-issues/assets/90285371/04cc48aa-8030-4602-b7c3-25d510ac3e3e)

**Comment by rykahsay** [comment]
check

**Comment by kmartinez834** [comment]
👍
