### ISSUE TITLE
Data download documentation 

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#969]
Please review and let me know if I need to change anything. Feel free to add instructions for data resources that you have been downloading as well.

https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/Data%20Download.docx?d=w6538b6993847482fac79174a1cbe6e1f&csf=1&web=1&e=I0ZMhs

**Comment by JingyueWu** [comment]
@jeet-vora atlas_oglcnac doesn't seem to have download instructions in its directory.

**Comment by kmartinez834** [comment]
Added comments in doc

**Comment by kmartinez834** [comment]
[Data downloads](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/Backend%20Workflow.docx?d=w54fd6f54e20f443ea74ff1c4aca4e6a8&csf=1&web=1&e=kl5zAp&nav=eyJoIjoiNDg4MjU3Nzc2In0%3D)
