### ISSUE TITLE
CFDE Datasets in data.glygen.org

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#97]
Robel, Raja wants the files generated for CFDE to be part of data.glygen.org and eventually on aws.data.glygen.org
There are 50 output files generated via a script. I don't want to have them in the unreviewed folder. Is there a way these files can be on data.glygen.org without being in the unreviewed folder.

Also there will be one bco for these files. Also note the generated files are named as per CFDE.

Can you let me know or the changes on masterlist.json 

The files are in ```data/projects/glygen/downloads/cfde/current/```

- [ ] Robel - To make CFDE as part of workflow add to data.glygen.org
- [ ] To create BCO as per Robel's instructions

**Comment by rykahsay** [comment]
"Is there a way these files can be on data.glygen.org without being in the unreviewed folder." -- short answer is no because it will break lots of things. The question is why you don't want them to be with the others if you want to see them on data.glygen.org?

**Comment by jeet-vora** [comment]
They have no use in GlyGen. They have no meaning except when added to the CFDE portal. That is why. 
So I will also have to update the masterlist.json for the 50 files. Is there a way I don't have to add all these 50 files in the masterlist.json?

**Comment by jeet-vora** [comment]
To be discussed after 2.0 is pushed

**Comment by jeet-vora** [comment]
@rykahsay One of the solutions for adding CFDE datasets (50 files) to data.glygen.org are to zip them as one file. If there is only one zip file I do not have to worry about adding all the file info to dataset-masterlist and also the display issue on data.glygen.org would go away. Let me know what you think of the proposed solution.

Below is how the info looks in dataset-masterlist. Please note the format is zip, no target objects, no molecule and no species. The file also does not have to be integrated. 

```
{
		"name": "cfde_data_package",
		"format": "zip",
		"primaryfield": "",
		"target_objects": [
			""
		],
		"integration_status": {
			"status": "integrate_none",
			"excludelist": []
		},
		"categories": {
			"molecule": "",
			"species": []
		}
	}	
```

The file name is **cfde_data_package.zip** under /data/projects/glygen/downloads/cfde/2023_03_15/current/

**Comment by rykahsay** [comment]
Since all our datasets have to have "molecule",  I am setting the molecule to be "all"

reviewed/all_cfde_data_package.zip 

<img width="717" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/0022ee9d-3c75-4ac6-8704-fd006ab50451">

**Comment by rykahsay** [comment]
No BCO created for this dataset, please create it.
```
cd /software/glygen/
 python3 check-bco2filename-mapping.py
```

<img width="1256" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/7d847b82-a733-4f8b-b732-e84295106f66">

**Comment by jeet-vora** [comment]
Done
