### ISSUE TITLE
Create data download scripts for several resources 

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#970]
For 2.4 and onward data download, please create scripts for the following data resources. Each script should include final steps such as version control and symbolic link creation: 

- [x] Genome Alliance
- [x] Disease Ontology (DO)
- [x] MatrixDB
- [x] IPTMET 
- [ ] Genomics England

This is related to #969 @jeet-vora

**Comment by kmartinez834** [comment]
@jeet-vora can you update the permissions to `/data/projects/glygen/downloads/download_scripts/download_alliancegenome_disease.sh` so I can add the orthology file to it?

--> Actually, can you update permissions to all files you've created in download_scripts so we can update if needed?

**Comment by JingyueWu** [comment]
@kmartinez834 Could you please write a script for Genomics England? I added another check box in the above comment for you.

**Comment by jeet-vora** [comment]
@kmartinez834 Changed permissions. Let me know if you can't access.

**Comment by kmartinez834** [comment]
@JingyueWu the website is using a POST request, so unfortunately this one can't be automated.  I went ahead and updated the file for this release

**Comment by ReneRanzinger** [comment]
@kmartinez834 just out of curiosity what is the issue? We had a similar problem before and you can wget POST requests as well.

**Comment by kmartinez834** [comment]
@ReneRanzinger this is for Genomics England Panel App.  If you go to https://panelapp.genomicsengland.co.uk/panels/25/ and click on the "Download Latest Signed Off Version" button, it submits a POST request to their server.  I inspected the site and tried using `wget https://panelapp.genomicsengland.co.uk/panels/25/download_version/` but this downloads an old version of the file.  

If you can figure out how to retrieve the latest version of the file, let me know, as I exhausted all options I could think of. Also, they do have an API, but the response contains slightly different information from the download tsv file.

**Comment by ReneRanzinger** [comment]
@kmartinez834 You can do it like this:
```
curl -H "Referer: https://panelapp.genomicsengland.co.uk/panels/25/" -H "Cookie: csrftoken=rzWFtvgI47lg61oKk6Lb1kSUgTsFzp6ehYArpLb1vxlPeS7LXVa9ySx1hOe7Wg4c" -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0" -d "csrfmiddlewaretoken=ECZk1CnRvJR4totugZy504nbf4OIvmOku1D6XSiaW9RDBfcvTOX3xC2igZAaSdMi&panel_version=4.0" -X POST https://panelapp.genomicsengland.co.uk/panels/25/download_version/ > curl.tsv
```
Pretty bad screen-scrapper hack. @sujeetvkulkarni and I talked about this recently. Essentially you are bypassing all their means to prevent robot (automated) download by:
* pretending you are a Firefox browser `-H "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0"`
* pretending that the post request was triggered from their download page `-H "Referer: https://panelapp.genomicsengland.co.uk/panels/25/"` 
* hijacking their two part authentication (cookie in the header and token in the post data).

If they are smart they have a lifetime for the cookie (e.g. 1 hour or 1 day) to prevent that the line above works for longer time. But even that you can circumvent by:
* first making a curl request to the download page
* Extracting the cookie from the response header 
* Extracting the token from the HTML body.  
* making the request above with the refreshed token and cookie

As I said bad screen-scrapper stuff. We should probably respect their wish to not allow automated downloads.

**Comment by kmartinez834** [comment]
Thanks for looking into this.  The command you provided still works, but I agree we should respect their wish not to allow automated downloads - especially since this command would need to be updated with each new version of the file anyway.
