### ISSUE TITLE
AWS Deployment issues.

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#971]
@rykahsay I am having some issues with the API and the APP mapping for the backend dataset viewer and I am not sure what domains to use and IPs. I would like to meet and talk some if you are available either Tuesday 1/23 or Wednesday 1/24 after the meetings. The domain aws.dsapi.glygen.org does not appear to be working even after deployment.

**Comment by Luke-Johnson-5** [comment]
Current Blockers: 

Glygen-backend-API download_data.py not working:

I ran "sudo python3 download_data.py -s prd -v 2.1.1" however I am currently getting this error:
![image](https://github.com/glygener/glygen-issues/assets/144174552/69c21875-6099-465c-b542-eb32769f6050)
This appears to be true when looking in the code:
![image](https://github.com/glygener/glygen-issues/assets/144174552/1206e462-2d0f-440e-a402-642af24c48c2)
Also I am currently trying this on git branch 2.3 but after checking the master the script appears to be the exact same so I am not sure what to do here.

Glygen-Backend-dataviewer: 
At the data mapping step however, The domain aws.dsapi.glygen.org does not load anything after completing all the steps found [here](https://github.com/glygener/glygen-backend-datasetviewer). Tianyi and I have determined this to be an issue with the set up of this file: /etc/httpd/conf.d/glyds.conf however, both of us are not sure what to setup there. Here is what is currently working:
![image](https://github.com/glygener/glygen-issues/assets/144174552/ca987b56-cedf-4b7a-aa2e-0faa56771f2f)

Glygen-frontend:
"make -f MakeFile prod" command does not appear to be working still. Have even run this command as "sudo make -f MakeFile prod" Even after following the steps you gave in [this ticket](https://github.com/glygener/glygen-issues/issues/924) I am not sure how to proceed. This is the error: 
![image](https://github.com/glygener/glygen-issues/assets/144174552/d2db0c51-d9c6-4f91-a62d-0ad2ae52566d)

I am not sure if the container has been built. I would like to meet to discuss these Issue so that I can learn from them so if you are available to meet soon let me know.

**Comment by rykahsay** [comment]
@Luke-Johnson-5 ... can you please maintain on ticket for your AWS blockers. Just keep the most recent and close others

**Comment by Luke-Johnson-5** [comment]
this ticket is outdated and I forgot to close this one apologies. There is a new ticket open with current blockers.
