### ISSUE TITLE
Prd Ultra Quick Test

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#972]
@Luke-Johnson-5 and @ubhuiyan 

Here is the template for the Ultra Quick Test for glygen.org. Please follow the instruction and begin the testing. Use this ticket to mention the issues with details, URLs and screen shots. Let me know for any questions.

https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B1F68A0AC-7241-477F-ACEF-3430B1904454%7D&file=UQT_Production_Template_JW1.docx&action=default&mobileredirect=true

**Comment by Luke-Johnson-5** [comment]
@jeet-vora I believe this is complete.
