### ISSUE TITLE
Glycan Simple Search Bug when searching Hex(5)HexNAc(4)dHex(1)

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#973]
On prd when Hex(5)HexNAc(4)dHex(1)  is searched in a glycan simple search with the category as any there is a empty list ID generated in the api. However, when the category is set to glycan a working list id is generated.

URL: https://api.glygen.org/glycan/search_simple/
Input: 
{
  "term_category": "any",
  "term": "Hex(5)HexNAc(4)dHex(1)"
}

Response:
{
  "list_id": ""
}

However, 
When input is:
{
  "term_category": "glycan",
  "term": "Hex(5)HexNAc(4)dHex(1)"
}

Response:
{
  "list_id": "ac1307ac2af0e46810a104e892d206c3"
}
^^ This is a working list id.

**Comment by rykahsay** [comment]
check now
