### ISSUE TITLE
Missing datasets on data.glygen.org

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#974]
There is only one Dicty proteoform dataset, and 0 for protein. @jeet-vora and I created BCOs up to GLY_000858 but looks like it only goes up to GLY_000823 on the data site.

![image](https://github.com/glygener/glygen-issues/assets/90285371/73acb142-5bdd-4744-9df4-16f18d6964f3)

**Comment by jeet-vora** [comment]
@kmartinez834 Yes I do not see the other datasets for Dicty.

**Comment by rykahsay** [comment]
Check now

**Comment by kmartinez834** [comment]
Done
