### ISSUE TITLE
Missing dictyBase namespace

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#975]
dictyBase missing database name from api/front end (see screenshot below).  `misc/xref_info.csv` file has been updated for protein_xref_dictybase.

https://api.glygen.org/protein/detail/Q54PT0-1
``` json
{
"id": "DDB_G0284351", 
"categories": ["Organism-specific"]
},
```

![image](https://github.com/glygener/glygen-issues/assets/90285371/8161a8af-f64c-47d9-af96-6dd40a2fe797)

**Comment by rykahsay** [comment]
check on beta now

**Comment by kmartinez834** [comment]
👍
