### ISSUE TITLE
Processes and files for pre processing and post processing of data

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#976]
Karina can you, in the backend documentation, add the list of steps/processes and files we need to edit for pre-processing and post-processing of data?

Like 

- xref_info.csv
- xref_categorization.csv
- compiled files etc

Thanks

**Comment by kmartinez834** [comment]
[Misc and compiled files](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/Misc%20and%20Compiled%20Files.docx?d=wc4dff933051f49148561ce51352c3731&csf=1&web=1&e=QnlRXb)
