### ISSUE TITLE
Export 2.4 glycan data for Nathan

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#988]
Prepare the files for Nathan

**Deadline:** 2/5/2024

**Dependencies:**
* #983 
* #984 

**Blocker for:**
* #989
* #990 
* #991 
* #992

**Comment by kmartinez834** [comment]
@edwardsnj I have created a new repo for the glycan data pipeline (https://github.com/glygener/glygen-glycan-pipeline) that contains the tracking file and README. I've documented changes and details in the README -- let me know if you have any questions.

Also, the new file from EMBL has glycan compositions in Byonic format.  These will need to be mapped to GlyTouCan accessions -- we don't expect you to do this for the current release, but wanted to make sure you had the file for future exports.

**Comment by kmartinez834** [comment]
@jeet-vora FYI
