### ISSUE TITLE
2.4 glycan data processing

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#989]
Processing the glycan data from GlyGen and generating the glycan export for GlyGen.

**Deadline:** 2/18/2024

**Dependencies:**
* #983 
* #984 
* #987 
* #1003 

**Blocker for:**
* #990 
* #991 
* #992

**Comment by edwardsnj** [comment]
#1003 is a blocker here...

**Comment by edwardsnj** [comment]
Complete. 

See: 

https://github.com/glygen-glycan-data/PyGly/releases/tag/GlyGen-GlycanData-Export-v1.16.0

and: 

https://github.com/glygen-glycan-data/PyGly/tree/GlyGen-GlycanData-Export-v1.16.0/smw/glycandata/export

Note too that the tag "GlyGen-GlycanData-Export-Current" points to the current release. 

Release highlights:

* Glycans: 1535 additions, 0 removals, 47576 glycans in total
* GlyCosmos taxonomy annotations not updated (circularity with GlyGen species annotations)
* Fix bug in PNG image generation for undetermined linkage glycans
* Indicate PubMed ids as species annotation source when provided in source data
* Implement species specific GlyGen dataset source ids
* EMBL glycan data-source w/ GlyTouCan ids
* Updated (registered) compositions, GNOme lookup table update
* Updated subsumption (GNOme) and motif alignments (GlycoMotif)
* Updated Glymage SVG, PNG, and JSON files
