### ISSUE TITLE
EMBL data evaluation

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#995]
@jeet-vora will explain and coordinate. Important is to listen to the seminar on 1/30.

**Comment by jeet-vora** [comment]
@kmartinez834 @ubhuiyan 

We have received the dataset from EMBL without the relative abundance and we need to process it.

The dataset needs to be first processed by Nathan and then by Robel. We should bring this up on Wed and discuss the protocol.

[glygen_upload.xlsx](https://github.com/glygener/glygen-issues/files/14143099/glygen_upload.xlsx)

**Comment by kmartinez834** [comment]
Dataset was provided to Nathan in 2.4, so it's included in species data.  Will be creating a proteoform dataset in 2.5.

**Comment by kmartinez834** [comment]
@ReneRanzinger ok to close this ticket?
