### ISSUE TITLE
Test frontend API logging

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#999]
We will try to use HTTP header information to identify the frontend.

**JS example**:

https://reqbin.com/req/javascript/kekxzr6z/get-request-with-custom-headers

We could make a custom **header field**:

ggcaller : frontend

Test this with one WS and let @rykahsay see if he can access the field.

**Blocker for:**
* #998 
* #1000 
* #1001

**Comment by ReneRanzinger** [comment]
@sujeetvkulkarni will provide documentation for Robel which headers to use in which documentation for which webservice.

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger @rykahsay Currently I am looking into some more options to identify bots,
isbot (https://www.npmjs.com/package/isbot/v/4.4.0) is javascript and node js based library and I believe we can use it in frontend to identify bots. It takes "User-Agent" as arguments and returns boolean value to tell if its bot or not.

Similarly, python has user-agents library which can be used on server side (https://pypi.org/project/user-agents/)
to identify bots (user_agent.is_bot). I believe this or similar library which is compatible to our python version can be used on server side to identify bots base on "User-Agent".

These bot identifying libraries are used in analytics or similar cases.

Currently I am exploring client side isbot library and custom header argument a little more. Please let me know if you have any suggestion. Or strong preference to use server side logic using user_agent.is_bot functionality and Origin (value: https://www.glygen.org or https://glygen.org) or Referer (value: https://www.glygen.org/ or https://glygen.org/) header properties. 
Referer  - is always present in all apis and browsers (Safari, Edge, Mozilla, Chrome) and it has partial or full url stating from where the request originated.
Origin  - is always present in all apis except image tags where we give url as source to display images (like glycan images) and browsers (Safari, Edge, Mozilla, Chrome) and it has partial or full url stating from where the request originated.

In case of beta (corresponding partial or full url), 
Origin: https://beta.glygen.org
Referer: https://beta.glygen.org/

In case of data (corresponding partial or full url),
Origin: https://data.glygen.org
Referer: https://data.glygen.org/
Custom property wont be present in data if we dont add it explicitly.

**Comment by ReneRanzinger** [comment]
I think we should do it backend. I am not sure we want to just "throw away" the bot requests. We should log them as well and mark them accordingly.

**Comment by sujeetvkulkarni** [comment]
Use below header properties in the backend to differentiate between who is calling.

1. Origin (value: https://www.glygen.org or https://glygen.org)
2. Referer (value: https://www.glygen.org/ or https://glygen.org/)
3. User-Agent - bot identification.

For bot identification we can additionally use libraries like (https://pypi.org/project/user-agents/)
to identify bots (user_agent.is_bot).
